### ISSUE TITLE
Hashstate still appearing

### ISSUE THREAD

**Issue by georgerichmond** [rackt/react-router#1001]
I'm still gettting '/#/' even when using 

`Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(<Handler/>, document.body);
});`

I've seen this article, but it's quite old now:
http://stackoverflow.com/questions/25086832/how-to-stop-in-browser-with-react-router

I am using Chrome and Safari on a mac.

**Comment by srph** [comment]
It can be assumed that you are using `v0.13`?

**Comment by georgerichmond** [comment]
Apologies, I've started again and it's working now. Thanks.
