### ISSUE TITLE
Possible bug in Safari when calling callback() method

### ISSUE THREAD

**Issue by JFusco** [rackt/react-router#1004]
The below code does not work in Safari 8.0.4.  I'm using HistoryLocation for my routes:

    statics: {
        willTransitionTo: function (transition, params, query, callback) {
          checkAuthAndStoreItSomewhere().then(function (auth) {
            if (auth == null)
              transition.redirect('login');
          }).then(callback);
        }
    }

It will not continue to the route - but, when I call callback() manually without waiting for anything to return from the promise - it works just fine, like this:

     statics: {
        willTransitionTo: function (transition, params, query, callback) {
         //this will work
          callback();
        }
    }

**Comment by JFusco** [comment]
Maybe this has something to do with HistoryLocation?  I'm doing a little more digging and testing to see what I can find and provide more information.

**Comment by ryanflorence** [comment]
We could be clearer on the documentation, but you need to call `callback` even after you redirect. 
(Maybe we should call it automatically)

```
statics: {
    willTransitionTo: function (transition, params, query, next) {
      checkAuthAndStoreItSomewhere().then(function (auth) {
        if (auth == null)
          transition.redirect('login');
          next();
      }).then(next);
    }
}
```

**Comment by JFusco** [comment]
Thanks @ryanflorence - figured this out a while after I had posted the question.  Would there be any reason to not call callback() automatically?

Thanks for the hard work here

**Comment by taurose** [comment]
@ryanflorence the code you posted doesn't seem right; why invoke `callback` twice?

I don't see anything wrong with the original code assuming that the promise resolves in time. So my guess would be that `checkAuthAndStoreItSomewhere` returns a rejected promise or never resolves, which would cause `callback` to never be invoked.

**Comment by JFusco** [comment]
@taurose - The promise does resolve correctly, but callback was simply not doing anything.

**Comment by JFusco** [comment]
@taurose and @ryanflorence - Even after I call the callback() method after redirect - it's still not working.  Not sure what to do about it at this point..Perhaps I can find another work-around for now (maybe do a hard refresh with window.location.href).  Any other ideas?  If I could show you the real code it might help debug

Let me know how I could help to resolve this.  Thanks again!

**Comment by adjavaherian** [comment]
we had the same problem and definitely need to callback after the transitionTo().  stumped as to why this wouldn't automatically do that.
