### ISSUE TITLE
Means of tying freeform params to a route for transition hooks

### ISSUE THREAD

**Issue by mshick** [rackt/react-router#1010]
I've run into a problem in a project. I'd like to use a few paths in a nested route, like:

```
<Route path="/post" handler={Post}>
  <Route path="edit" handler={PostOperations} />
  <Route path="view" handler={PostOperations} />
</Route>
```

Now, say I need to use the static `willTransitionTo` hook to perform some activities before those routes load. With both operations being handled by the same component, I have one static hook, and no context to rely upon to differentiate between the two routes directing the action, other than the `transition.path` which includes extraneous data `/post/edit` and really feels like a hack. 

If I was to instead do `path=":op"` that gives me a `params.op` which I can tie to the operation in a clear way, but I've now opened myself up to handling anything in that position, and have made delivering back a NotFound view more difficult.

What I would love is the ability to specify parameters on the route itself, like:

```
<Route path="edit" params={{ op: 'edit' }} handler={PostOperations} />
```

So that I can more easily match routes in transitions.

**Comment by ryanflorence** [comment]
Use two handlers and share code inside of them, they can render the same component, but since you are *handling* the routes differently, it stands to reason that you should have two *handlers* :)

You can dynamically create them to, just pass the params to yourself instead of the router.

```
<Route path="/post" handler={Post}>
  <Route path="edit" handler={createPostOperations({op: 'edit'})} />
  <Route path="view" handler={createPostOperations({op: 'view'})} />
</Route>
```
