### ISSUE TITLE
Unable to get server-side rendering to work after upgrading to 0.13.2

### ISSUE THREAD

**Issue by murz** [rackt/react-router#1011]
Hi,

I'm having trouble figuring out how to get server-side rendering to work after upgrading to React 0.13 and react-router 0.13.2

I first tried something like this:
```js
Router.run(Routes, "/path", function(Handler, matched) {
  res.send("<!doctype html>"+React.renderToString(Handler()));
});
```
But that gives me the error `TypeError: Cannot read property '__reactAutoBindMap' of undefined`

Poking around I saw [this bug](https://github.com/facebook/react/issues/3466), which hints that I might need to be using `createFactory` for server-side rendering. But when I try this:
```js
Router.run(Routes, "/path", function(Handler, matched) {
  var fact = React.createFactory(Handler);
  res.send("<!doctype html>"+React.renderToString(fact()));
});
```
I get the following error: `TypeError: Cannot read property 'mountComponent' of undefined`

The app I'm trying to render is not a very complex react-router app. The Routes look like this:
```
<Route name="app" path="/path" handler={App}>
    <DefaultRoute name="dashboard" handler={Dashboard} />
    <Route name="otherPage" handler={OtherPage} />
    <NotFoundRoute name="notFound" handler={NotFound} />
  </Route>
```

And the App.jsx looks something like this:
```
var App = React.createClass({

  render: function() {
    return (
      <div>
        ...
        <li><Link to="dashboard">Dashboard</Link></li>
        <li><Link to="otherPage">Other Page</Link></li>
        ...
        <RouteHandler />
        ...
      </div>
    );
  }

});

```

Any tips or ideas as to what's going wrong?

**Comment by taurose** [comment]
Your createFactory snippet should work like that, but I would prefer using `React.renderToString(React.createElement(Handler));`. I suspect the error you're getting is caused by something else. 

Are you using `createFactory` at other places perhaps? Apparently mixing it with JSX can cause that error, e.g.: 

```js
var Component = React.createFactory(require('./component'));

render(){
   return <Component />; // bad
}
```

To clear things up, those are equivalent:

```js
var Component = React.createClass(..); // or as ES6 class

// 1) JSX 
React.renderToString(<Component />);

// 2) createElement (this is also the output of JSX after processing)
React.renderToString(React.createElement(Component));

// 3) createFactory
var fact = React.createFactory(Component);
React.renderToString(fact());
```

**Comment by murz** [comment]
Thanks for clearing things up so quickly! I was able to get `React.renderToString(React.createElement(Handler))` working after all. As you suspected, I overlooked using `createFactory` when building my routes.

**Comment by devangpaliwal** [comment]
Exactly the mistake i made.  I wrapped my jsx component with React.createFactory call as shown below. 

var App = React.createFactory(require('./components/app.jsx'));

This is wrong - 

right way is 

var App = require('./components/app.jsx');
