### ISSUE TITLE
[Proposal] Allow data to be stored on routes and available within state. 

### ISSUE THREAD

**Issue by ryardley** [rackt/react-router#1017]
It would be advantageous to attach data to routes that could be available in route changed callbacks. A concrete usecase would be attaching action references to a specific route whilst using flux.

```javascript

var doSomethingEverytime = require('actions/doSomethingEverytime');
var fetchAboutData = require('actions/fetchAboutData');
var fetchHomeData = require('actions/fetchHomeData');

export default (
  <Route name="app" path="/" handler={Application} data={doSomethingEverytime} />
    <Route name="about" handler={About}  data={fetchAboutData} />
    <DefaultRoute name="home" handler={Home} data={fetchHomeData} />
  </Route>
)
```

It would then be useful to get the data in the callback after a route has changed:

```javascript
// example if data happened to be references to action functions.
Router.run(routes, HistoryLocation, (Handler, state) => {
  state.routes.forEach(route => context.executeAction(route.data));
});
```

**Comment by ryardley** [comment]
Altered the proposal a little bit as I am starting to think it isn't really the routers responsibility to organise the data output necessarily but simply allowing data to be attached to Routes is really useful.

**Comment by Jigarsolanki** [comment]
+1

**Comment by lukehorvat** [comment]
This would be nice. [UI Router](https://github.com/angular-ui/ui-router) offers this functionality and it is really useful.

**Comment by komackaj** [comment]
I would love that.

I usually fire an action on route change using ActionCreator (e.g. to set a data filter on store). Nowadays I define Route with a name, then route name to ActionCreator method mapping, in Router.run callback I find current route name, map it to action call and fire it.

The ability to attach ActionCreator method directly to route would simplify this for me.

**Comment by charosez** [comment]
+1

**Comment by ryanflorence** [comment]
in 1.0 you can now add whatever props you want to a route (JSX, or plain object), which will be available as `this.props.route` in the route component.
