### ISSUE TITLE
Improve componentWillRecieveProp docs

### ISSUE THREAD

**Issue by morenoh149** [rackt/react-router#1019]
Right now when I navigate between views in my app the code in `componentDidMount` is not firing again. I'm pretty sure I need to implement `componentWillReceiveProps` but I'm not sure what it's intent is, nor when it fires relative to the other react component lifecycle callbacks, nor what should be added inside the callback.

Any help here would be appreciated. Re https://github.com/rackt/react-router/blob/master/examples/master-detail/app.js#L94 & https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments

**Comment by mjackson** [comment]
The [React docs on `componentWillReceiveProps`](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) may help.
