### ISSUE TITLE
Question about using react-router and Flux together

### ISSUE THREAD

**Issue by x1a0** [rackt/react-router#1020]
https://github.com/rackt/react-router/blame/master/docs/guides/flux.md#L148

As you said above - that's not how you use them together. What is your way?

**Comment by gaearon** [comment]
I think this is only meant to be related to the last approach with putting `Handler` into payload.
Other approaches are more “ok”.

**Comment by ryanflorence** [comment]
we'll have the flux.md guide filled out eventually
