### ISSUE TITLE
Bug in transition.redirect()

### ISSUE THREAD

**Issue by JFusco** [rackt/react-router#1021]
In the application layer (top level) I tested this code to transition to pagetwo

    statics: {
        willTransitionTo(transition, params, query, callback){
            var defer = Q.defer();

            var something = function(){
                setTimeout(function(){
                    defer.resolve();
                }, 3000);

                return defer.promise;
            }

            something()
                .then(function(){
                    transition.redirect('pagetwo');
                }).then(callback);
        }
    }

I see the URL changing but the page does not render.  I also submitted a bug for inconsistencies with redirecting and calling callback() in Safari that was previously closed, but shouldn't have been because it's still an issue.

I believe these issues are related:
https://github.com/rackt/react-router/issues/1004

Thank you

**Comment by JFusco** [comment]
Here is my pagetwo component:

    var React = require('react');

    var PageTwo = React.createClass({
	    render: function(){
		    return (
			    <div>
				   Page Two
			    </div>
		    );
	    }
    });

    module.exports = PageTwo;

Here is my routes file:

    import React from 'react';
    import {Router, Route, NotFoundRoute} from 'react-router';
    import Application from '../components/Application';


    export default (
	    <Route handler={Application}>
		    <Route name="pageone" path="/" handler={require('react-proxy!../pages/PageOne')}/>
            <Route name="pagetwo" path="/pagetwo" handler={require('react-proxy!../pages/PageTwo')}/>
	    </Route>
    );

**Comment by taurose** [comment]
Have you tried without react-proxy-loader?

**Comment by JFusco** [comment]
@taurose - I'll try it without the loader but it's essential I have lazy loaded assets.  If it works without the react-proxy-loader I'll have to use another method of lazy loading.

If I wanted to take out react-proxy-loader, I wonder if something like this would work as mentioned by @gaearon 

https://github.com/rackt/react-router/issues/476
https://gist.github.com/gaearon/fbd581089255cd529e62

If this implementation above doesn't work with this particular issue I will let you know..I'll report back in about 20 minutes.

Thanks!

**Comment by JFusco** [comment]
@taurose - I tried without the react-proxy-loader and it's the same result, it changes the url to /pagetwo but never renders page two.

I was thinking this is probably because the willTransitionTo override is happening in the top level where it executes on every route change...so, when I redirect to 'pagetwo' it will hit the same willTransitionTo method and execute that code all over again.  Below is how I got around it for this example, but it can't be like this for production code.

before class definition:

    var happened = false;

then:

    statics: {
		willTransitionTo(transition, params, query, callback){
			if(happened){
				callback();
			}


			var defer = Q.defer();

			var test = function(){
				setTimeout(function(){
					defer.resolve();
				}, 4000);


				return defer.promise;
			}

			test()
				.then(function(){
					happened = true;

					transition.redirect('pagetwo');
				})
				.then(callback);
		}
	}

I just need the code to execute one time only on the very first entry of the application, no matter what route the user hits, to act as an authentication layer.

**Comment by JFusco** [comment]
I found this...but I don't see how this could work either.  Is there a best practice for what I'm trying to accomplish?

https://gist.github.com/BenoitZugmeyer/0bfd2ce23788b06ffb25

**Comment by taurose** [comment]
I'm unable to reproduce this. Here's what I tried: https://gist.github.com/taurose/791359450e4d9acbda1b . Works as expected.

Did your app suddenly start working with the flag you mentioned above?

As for your use case, have you looked at the [auth-flow](https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js) example?

**Comment by JFusco** [comment]
Your willTransitionTo is in PageOne components where mine is in the App (top level) component

**Comment by JFusco** [comment]
It's in the App component because I want to authenticate all routes underneath...every page needs authenticated - so I figured the App would be a good place to check since it's top level and all routes fall underneath

**Comment by taurose** [comment]
Ah, that makes sense. In that case, you're causing a redirect loop. 
If all your routes require authentication, what are you planning to show to the unauthenticated visitors anyway?

I can think of two approaches:

1. Change your route config to include a route that doesn't need authentication:

  ```js
  <Route handler={Root} > {/* could simply render <RouteHandler /> */}
    {/* private routes */}  
    <Route handler={Application}>
        <Route name="pageone" path="/" handler={..}/>
    </Route>
    {/* public routes */}
    <Route name="pagetwo" path="/pagetwo" handler={..}/>
  </Route>
  ```

2. Check authentication before starting react-router

  ```js
  checkAuth(.., function(result) {
    if(!result) {
      window.location = "http://google.com";
      return;
    }
    Router.run(..);
  });
  ```

**Comment by JFusco** [comment]
Yup..Redirect loop.  I think your first solution would better fit my needs.  I see what you're saying..My public route(s) would be what I would show an unauthenticated user ie. '/denied'...my 'Root' would just render the routehandler and the 'Application' would check authentication and redirect accordingly in the willTransitionTo.

Looking forward to trying this - I'm hoping this can also work with lazy loading the assets too.  You can probably go ahead and close this - don't think this is an issue with react-router..just an issue with my implementation.

Really appreciate the help and thanks for the hard work.

**Comment by JFusco** [comment]
You know, thinking about solution #1.  That would also send you in a redirect loop.  It's essentially the same thing as the original problem - just one level deeper.

If a user hits 'pageone' under the 'Application' layer, which has the auth check in the willTransitionTo, it will be a redirect loop because pageone falls under Application and will hit willTransitionTo every time no matter what route is under Application.  Perhaps I'm missing something crucial about react-router.  Someone has to have done this before.

**Comment by taurose** [comment]
You shouldn't redirect to routes under `Application`. That's why I pulled `PageTwo` outside of it.

As long as you redirect from public to private (= descendants of route with willTransitionTo hook) routes there shouldn't be any issues.

1. User opens `/pageone`, which resolves to handlers Root > **Application** > PageOne
2. Redirect to `/pagetwo`, which resolves to handlers Root > PageTwo
