### ISSUE TITLE
Route params doesn't handle '?' properly

### ISSUE THREAD

**Issue by tko** [rackt/react-router#1025]
I have 
```javascript
<Route name="article" path="/article/:articleId" handler={Article} />
```
Which I then use in one of two ways:
```javascript
<Link to="article" params={{articleId: article.id}}>{article.title}</Link>

this.context.router.transitionTo('article', {articleId: article.id})
```
Now an `article.id` containing '?' in it completely breaks the routing. Only the URL changes, seemingly interpreting characters following '?' as query parameter name -- the route is activated with similarly wrong argument. If I add `.replace('?', '%3F')` in the manual call the route is activated with correct argument but the 'active' class isn't set in the link (and it does nothing to help with clicking the links)

**Comment by ryanflorence** [comment]
failing test case on master would amazing :D (API has changed quite a bit but docs are up to date)

**Comment by tko** [comment]
I think this might capture part of it, for URLUtils-test.js:
```javascript
    describe('and some params contain special characters', function () {
      it('returns the correct path', function () {
        expect(formatPattern(pattern, { id: '?not=confused&with=query#string' })).toEqual('comments/%3Fnot=confused%26with=query%23string/edit');
      });
    });
```
Testing the reverse left as an exercise for the reader :-P
