### ISSUE TITLE
Page refresh breaks with Router.HistoryLocation

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#1026]
I'm using React 0.13.1 with router 0.13.2

When I try to use the HistoryLocation like this:
```javascript
Router.run(routes, Router.HistoryLocation, (Handler) => {
  React.render(<Handler />, document.getElementById('app'));
});
```
It works fine, until I hit the page refresh button. Then I get a 404 on the route. I'm only using simple routes atm

```javascript
<Route handler={App} path="/">
    <DefaultRoute handler={Home} name="home" />
    <Route handler={About} name="about" />
    <Route handler={Features} name="features" />
    <NotFoundRoute handler={NotFound} name="not-found" />
  </Route>
```

**Comment by schickling** [comment]
Same here!

**Comment by EdwardReed** [comment]
#110

**Comment by 0x80** [comment]
So we can work around this by specifying the paths explicitely, but routes without the path property set should just work with history api without any workaround, no? I would still consider this a bug.

**Comment by failpunk** [comment]
This is still an issue.

**Comment by SubatomicHero** [comment]
Im having the same issue.

**Comment by SubatomicHero** [comment]
"Reading the current state

When your page loads, it might have a non-null state object.  This can happen, for example, if the page sets a state object (using pushState() or replaceState()) and then the user restarts their browser.  When your page reloads, the page will receive an onload event, but no popstate event.  However, if you read the history.state property, you'll get back the state object you would have gotten if a popstate had fired.

You can read the state of the current history entry without waiting for a popstate event using the history.state property like this:

var currentState = history.state;"

I was reading this from Mozillas site. Has this been considered?

**Comment by ryanflorence** [comment]
I'm going to guess your server isn't configured to work with history location. All urls need to serve the same page.

https://rackt.github.io/react-router/#HistoryLocation

If you think you have your server configured, then please ask to reopen.

**Comment by 0x80** [comment]
I was testing with webpack-dev-server. Not sure how this express catch all route applies to that. I'll give it another try.

**Comment by taurose** [comment]
For webpack-dev-server you can use the `historyApiFallback` option. Here's a write-up: http://jaketrent.com/post/pushstate-webpack-dev-server/

**Comment by 0x80** [comment]
Wonderful! Thanks :+1:

**Comment by robert-chiniquy** [comment]
I'm trying to use `react-router` on both the server and client side. On the server side, when I pass `      location: Router.RefreshLocation` or `location: Router.HistoryLocation` to `Router.create`, I get the error `ERR 2015-07-12T20:27:18-07:00 rr: Error: Invariant Violation: You cannot use <RefreshLocation> without a DOM` and `ERR 2015-07-12T20:26:03-07:00 rr: Error: Invariant Violation: You cannot use <HistoryLocation> without a DOM`. 

Not sure how this squares with
> I'm going to guess your server isn't configured to work with history location.

How do I configure `react-router` on my server to work with `HistoryLocation` ?

**Comment by mvnnn** [comment]
I am having the same issue. "react": "~0.14.3" but i am using gulp in my project.

**Comment by 0x80** [comment]
@mvnnn This is not related to your build tool like Gulp. Whatever you're using to serve the static files needs to implement the historyApiFallback kind of mechanism. All request which are not targeting files need to be served the index.html file. It could be webpack-dev-server, express, nginx, apache...

**Comment by vimniky** [comment]
same problem !!!!!!

**Comment by Karthik248** [comment]
What about Tomcat server?
I have an app built using react,react-router and jquery(ajax).
On Tomcat server when i reload the page it shows erro 404.
