### ISSUE TITLE
13.2 upgrade: this.context.router is undefined

### ISSUE THREAD

**Issue by mega-cache-money** [rackt/react-router#1028]
There is no reference to this.context.router within my own routing code.

I've loaded React 13.1 in the browser before loading ReactRouter 13.2. 

When I try to `run` the router, the following error specifically is thrown at line 550 in the non minified dist:

`Uncaught TypeError: Cannot read property 'getRouteAtDepth' of undefined`

What is going on here?

**Comment by mega-cache-money** [comment]
Specifically,  the following error is thrown at line 550 in the non minified dist:

Uncaught TypeError: Cannot read property 'getRouteAtDepth' of undefined

**Comment by tmbtech** [comment]
Can you post your router.run function?

**Comment by mega-cache-money** [comment]
I'm certainly not calling router.run twice. My setup works perfectly with react 0.12.2 and react-router 0.12.4 on both browser and server.

Here's my run function:

    Router.run(routes, Router.HistoryLocation, function (Handler, state){
        React.render(<Handler {...prop} query={state.query}/>, document.getElementById('app-hook'));
    }

**Comment by tmbtech** [comment]
I ask because we are getting the same error, It only happens on `React.renderToString()`. 
We are using webpack to bundle our code on the client side, when `React.render()` gets called we don't get the error. 

It almost seems like there are two instances of react getting loaded, but it's hard to debug. We are still investigating, I'll update here if we figure it out. 

https://github.com/rackt/react-router/issues/720

**Comment by mega-cache-money** [comment]
Thanks for the lead! Helped me solve it :) So it turns out I was loading two versions of react-router: one browserified from node, the other being the browser dist. Hope you crack it.

**Comment by tmbtech** [comment]
@mega-cache-money it was the same thing. We had to alias react in webpack so it would load from the same place. React-router, react-time, radium were all trying to pull it in.

**Comment by skuridin** [comment]
@tmbtech Can you show me how to fix it in webpack?
