### ISSUE TITLE
How to set page url outside app?

### ISSUE THREAD

**Issue by wmertens** [rackt/react-router#1029]
I'm sorry if this is covered somewhere, I can't find it.

I want to redirect my app to an authentication URL on user action, but when I use `transitionTo` or simply `document.location.href=...` then this gets intercepted and the app stays where it is. It works when I make it a simple link to click on.

How can I do the equivalent of clicking on a href?

**Comment by taurose** [comment]
That's what `router.transitionTo` is for. Where do you call it? Can you share some code or create an example where it fails?
