### ISSUE TITLE
Overlay as a sub router

### ISSUE THREAD

**Issue by vachi** [rackt/react-router#1030]
I have seen a similar question, and the answer was, that this is the while point of react-router. 
That said, i have not been able to find exactly how to do this. 

So my router looks like this. 
```javascript
<Route name="search" path="search/:searchID/:searchPage" handler={Search}>
  <Route name="search-single" path=":searchSingleId" handler={SearchSingle} />
</Route>
```

I need the SearchSingle to be a overlay on top of the already rendered Search route.

Is it possible to render a sub route inside a div? or is there a way to append the sub-router at the end of the current router render... ?

I don't actually know whats the correct way. 
In my backbone app, I would just change window history and append to a pre designated div.

I imagine in react using -router this would be cleaner/smarter. 

thanks, vache

**Comment by ryanflorence** [comment]
if I'm understanding you correctly, this is basically the primary feature of react-router, to nest routes and UI.

So if you're on 0.13.x use a `<RouteHandler/>` inside of `Search`, if you're on 1.0.0-beta, use `this.props.children`

**Comment by gajus** [comment]
https://reacttraining.com/react-router/web/example/modal-gallery
