### ISSUE TITLE
0.12.4 > 0.13.2 Upgrade Error: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by eriklharper** [rackt/react-router#1032]
To keep up with the latest changes, in a 0.12.4 React Router project I'm working on, I did a drop-in replacement upgrade to 0.13.2, and out of the gate, I get this error:

![image](https://cloud.githubusercontent.com/assets/821864/6946769/7e4e5a04-d857-11e4-8e4a-3d2b0663b285.png)

Seems like a compile-time error.  I'm running Browserify to compile my modules (want to move to Webpack eventually, but need more time), and I also have React Router installed via Bower, with a browser entry pointing to the global unminified build: `./bower_components/react-router/build/global/ReactRouter.js`.  Any tips on ways to get around this?

**Comment by pbeshai** [comment]
This happened to me on one of my machines. The problem for me was that React.Component was not defined, which meant React was still at version 0.12.x, not 0.13.x. I had forgotten to `npm install` the newer version of React in that environment. Doing so fixed the problem.

**Comment by gaearon** [comment]
Yep, I also had it for the same reason. Pretty sure it's not a router issue so closing down.

**Comment by renak** [comment]
I'm getting this exact issue, with React.Component as undefined, after upgrading React to 0.13.2 and React Router to 0.13.3

**Comment by Hkmu** [comment]
I had the same problem.It's because that I didn't spell `Component` correctly,the first letter should be uppercase.

**Comment by simoneduca** [comment]
@Hkmu :+1:

**Comment by hoverCow1990** [comment]
haha thanks for Hkmu
