### ISSUE TITLE
Pages refreshes on ever link to=

### ISSUE THREAD

**Issue by fourq** [rackt/react-router#1033]
Every Link is use refreshes the entire site. I cannot figure out why this is happening. Here's my route and app setup. https://gist.github.com/fourq/d83e6a40150ca1487e38 

Any advice would be great.

```
    "react-router": "^0.13.1"
    "react": "^0.13.1"
```

Thanks

**Comment by fourq** [comment]
As soon as I removed HistoryLocation everything started working again.

**Comment by ryanflorence** [comment]
BrowserHistory falls back to full page refreshes in browsers that don't support `pushState`.

Not using `Link` and using anchor tags, will work with `HashLocation` as a side-effect of the implementation, but not with BrowserHistory.

Not sure which case you've got, but I don't think we've broken the most basic features of the library :P
