### ISSUE TITLE
Error when requiring react-router

### ISSUE THREAD

**Issue by shaimo** [rackt/react-router#1035]
It doesn't even load. I get:
Uncaught TypeError: Super expression must either be null or a function, not undefined
in ContextWrapper.js:5

Am I doing anything wrong?

**Comment by njsuperfreak** [comment]
I am also seeing an error in IE8
![screen shot 2015-04-02 at 12 23 10 pm](https://cloud.githubusercontent.com/assets/1198354/6968227/0e432e38-d933-11e4-8f06-3de10fef1caa.png)
using the following:
```
import { Route } from 'react-router';
```

**Comment by shaimo** [comment]
The issue had to do with using two different versions of react simultaneously...
