### ISSUE TITLE
routing problem on server

### ISSUE THREAD

**Issue by rhacker** [rackt/react-router#1038]
I have problem regarding the routing on server. The problem is I have a `Html.js` layout , and the body to render the content inside.
example of `Html.js` template ( reactjs template ): 
```html
<html>
<head>
  <script src="/public/dist/main.js"></script> 
</head>
<body>
  <div dangerouslySetInnerHTML={{__html: this.props.markup}} id="app"></div> 
</body>
</html>
```

When the requested request from `/something`, it works just fine.
But if it's a nested route like `something/anotherthing`, the routing would request the css with '/something/public/dist/main.js` instead of `public/dist/main.js`, and of course the file is not available.

I've tried to request with pure server routing, it works without a problem.

**Comment by ryanflorence** [comment]
I can't follow what the problem is here, but nothing makes me think it has anything to do with the router.
