### ISSUE TITLE
Idea: Auth in Route

### ISSUE THREAD

**Issue by fourq** [rackt/react-router#1039]
I'd like to move my auth logic out of my jsx components and into Routes. Something that would let me control my available routes when logged in. At the moment I use a mixin, in my LoggedIn handler but I'd like to remove it from there and into the Route by grouping routes within a Route that has a authRequired attrib. 

```jsx
<Route handler={App}>
    <Route handler={LoggedIn} authRequired={MyAuthHandler} noAuth={LogIn}>
      <Route name="acts" handler={Acts}/>
      <Route name="home" path="/" handler={Home}/>
    </Route>
    <Route name="login" handler={LogIn}/>
    <NotFoundRoute handler={NotFound}/>
  </Route>
```

**Comment by jketcham** [comment]
If you define your routes the programmatic way, you can set onEnter handlers that can take on this functionality, though it means giving up the JSX definition of your routes.
Check out this PR for more details https://github.com/rackt/react-router/pull/845

**Comment by ryanflorence** [comment]
1.0 you can have any props you want on routes, and use getRoutes to decide what to do (like check app state like authentication) and return different routes.

personally, I'd have a parent route w/o a path that redirects if you're not logged in.

```js
// requireAuth redirects if they aren't auth'd
<Route component={Auth} onEnter={requireAuth)>
  <Route .../>
  <Route ../>
</Route>
```
