### ISSUE TITLE
IE8: Error importing react-router

### ISSUE THREAD

**Issue by jefferyvincent** [rackt/react-router#1040]
Hello,

I have all the required shims to get React 13.0.1 to work in IE8 (console-shim.min, es5-shim.min, es5-sham.min), however once I require react-router I get the following error:

![screen shot 2015-04-02 at 12 23 10 pm](https://cloud.githubusercontent.com/assets/1198354/6968596/e5c9789c-d935-11e4-889e-4bbcbda07413.png)

I am using react-hot-loader running webpack-dev-server with the following command:
```
import { Route } from 'react-router';
```

**Comment by pkese** [comment]
Me too

**Comment by richfisher** [comment]
Me too

**Comment by moimikey** [comment]
i'm assuming you've tried the non-minified version of es5-sham to see if the error gets thrown unminified? if it does, then you can continue to assume it's es5-sham, if it works unminified, then something went awry during uglification. if it's still the sam having problems, then i'd attribute that to the sham itself and icky support across IE versions :/... the warning in particular you're getting is seemingly only attributed to es5-sham not catching errors it throws and IE 8 doesn't like that explicitly.

**Comment by jefferyvincent** [comment]
Yes, here is the results of the non-minified version of es5-sham and your assumptions are correct.

![screen shot 2015-04-06 at 11 10 00 am](https://cloud.githubusercontent.com/assets/1198354/7006222/7ce9f926-dc4d-11e4-96f7-69ab659ba9f6.png)

![screen shot 2015-04-06 at 11 11 06 am](https://cloud.githubusercontent.com/assets/1198354/7006246/a6c56438-dc4d-11e4-901f-f53e89a3c5d8.png)

![screen shot 2015-04-06 at 11 29 40 am](https://cloud.githubusercontent.com/assets/1198354/7006575/4ccc5466-dc50-11e4-83b7-22d900179a7c.png)

**Comment by moimikey** [comment]
looks familiar https://github.com/es-shims/es5-shim/issues/297

**Comment by pkese** [comment]
Is this related #1022 ?

**Comment by gitim** [comment]
Any updates for this issue?

**Comment by jyustman** [comment]
@gitim Looks like it'll be fixed in 1.0 https://github.com/rackt/react-router/pull/1143#issuecomment-102718570

**Comment by gitim** [comment]
Seems that no, because I still have error in ie8

**Comment by jyustman** [comment]
1.0 hasn't been released yet: https://github.com/rackt/react-router/pull/1158

**Comment by ryanflorence** [comment]
current master (1.0 api) doesn't use getters or Object.defineProperty, so we should be good for IE8

**Comment by GilbertGan** [comment]
I have to use v2.0.0+ for the new APIs, but it seem not support IE8 just the reason you told.

**Comment by timdorr** [comment]
IE8 and lower no longer work because we switched to Babel 6 and it has a breaking change with IE8 and lower: https://phabricator.babeljs.io/T7322
