### ISSUE TITLE
goBack goes outside the site

### ISSUE THREAD

**Issue by santiagoaguiar** [rackt/react-router#1042]
I'm using `Navigation.goBack()` with a fallback in case there are no elements in the history, in a code similar to:

    if (!this.goBack())
        this.transitionTo('/my_route');

 However, it seems that the following sequence causes `react-router` to go outside the site:

1. Open any site X on browser.
2. Write react site's URL on browser.
3. Execute an interaction that executes the code above:
     * `goBack()` fails because `History.length == 0`, 
     * So it goes to a `/my_route` and `History.length++`.
4. Click back on the browser, so we are back where we were on step 2.
5. Execute an interaction that executes the code above.
    * `History.length` is still 1 so it executes `window.history.back()` and goes back to site X.

I think the issue happens because when there's a browser activated back/forward and `onPopState` is called on `HistoryLocation` the `History.length` is not modified, so it gets out of sync.

**Comment by mjackson** [comment]
This bug is not present in 1.0 (current master) because we cannot track `History.length` reliably in browsers, so we don't even try.
