### ISSUE TITLE
Remove current from getters?

### ISSUE THREAD

**Issue by natew** [rackt/react-router#1045]
Just wondering thoughts on this... I don't see the reason behind getCurrent__() on the getters, seems like in all cases we could do getParams(), getPathname().

I can make a PR for this if theres interest in changing them.

**Comment by rgrwkmn** [comment]
+1, I believe there are even other places (meaning not the Router Context) where methods returning the same data are called getParams, getPathName, etc.

**Comment by ryanflorence** [comment]
all this stuff comes in as props now on master (1.0 API)
