### ISSUE TITLE
TypeError: Cannot call method 'getRouteAtDepth' of undefined    at RouteHandler.createChildRouteHandler 

### ISSUE THREAD

**Issue by yanivefraim** [rackt/react-router#1050]
I am experiencing this error while trying to use the router. 
All details here:

http://stackoverflow.com/questions/29444357/react-router-error-cannot-call-method-getrouteatdepth-of-undefined

Thanks!

**Comment by yanivefraim** [comment]
Apparently it was related to server side rendering of my component, which included the react router. I guess it is not relevant ??

**Comment by chiunhau** [comment]
@yanivefraim I got the same problem. Client side router is fine, but server side rendering isn't. Please tell me how you fix it :) Thanks!
