### ISSUE TITLE
Route validation

### ISSUE THREAD

**Issue by mockdeep** [rackt/react-router#1051]
I spent an hour trying to debug the following route:

```jsx
<Route path='/scratch' hanler={Questlog.ScratchPage} />
```

Not sure if it's possible, but one thing that might be nice is if routes require a `handler` prop and err out if they are missing one.

**Comment by pedronauck** [comment]
Just to tell you, the prop has a typo ;)

**Comment by mockdeep** [comment]
Yes, I understand that now. I spent a while scratching my head and wondering if something was wrong somewhere else before copying and pasting another route and discovering the typo. I'm saying it would be nice if react-router gave some indication when one of the necessary props for the route is missing instead of failing silently.

**Comment by ryanflorence** [comment]
there are use-cases to not have a component (handler) at a route, (like scrolling to a record on the page instead of rendering a component for the route), so we can't make it a required prop.

I've been there, I wish we had something help out there :(
