### ISSUE TITLE
Preserve scroll position with slower renders?

### ISSUE THREAD

**Issue by braco** [rackt/react-router#1052]
Testing forward/back behavior, it seems like the scroll position will sometimes not be updated, and the page will start at the top again.

I'm assuming this is because the route has a very long list of content that takes a little extra time to render, so Chrome isn't able to scroll to the desired position in time.

Is there any way to defer the repositioning until (render has successfully completed + (pad time in ms))?

**Comment by ryanflorence** [comment]
the master branch (1.0 API) does this stuff in `componentDidUpdate`, which seems to be our best chance of doing it right. let us know if you find issues on master
