### ISSUE TITLE
Using <RouteHandler /> in a function other than `render`

### ISSUE THREAD

**Issue by yoni-tock** [rackt/react-router#1054]
Hey all,

In the app I'm working on, there's a workflow that involves going between modal dialogs. I'd like to manage which dialog is visible by giving each one a different route. I'm currently displaying the modal dialog using the `OverlayMixin` from react-bootstrap which means rendering some react elements inside a different function called `renderOverlay` which inserts the contents into the modal.

I'm having trouble with the router context when doing this. I keep getting the following error:
![screen shot 2015-04-06 at 4 56 55 pm](https://cloud.githubusercontent.com/assets/11616747/7013396/640e9750-dc7e-11e4-8331-e036bd7e8bab.png)

I haven't been able to resolve the issue after a couple hours of googling for the error and trying to read about the context object. Any thoughts / advice would be appreciated!

```js
'use strict';

var React = require('react');
var Router = require('react-router');
var RouteHandler = Router.RouteHandler;
var rbs = require('react-bootstrap');
var Modal = rbs.Modal;
var OverlayMixin = rbs.OverlayMixin;


var MyComponent = React.createClass({
  mixins: [OverlayMixin],
  contextTypes: {
    router: React.PropTypes.func
  },
  getInitialState: function() {
    return {
      isModalOpen: true,
    };
  },
  render: function() {
    return (
      <span />
    );
  },
  // This is called by the `OverlayMixin` when this component
  // is mounted or updated and the return value is appended to the body.
  renderOverlay: function() {
    if (!this.state.isModalOpen) {
      return <span />;
    }
    return (
      <Modal>
        <div className={cx('modal-body')}>
          <RouteHandler />
        </div>
      </Modal>
    );
  },
});

module.exports = MyComponent;

```

**Comment by taurose** [comment]
`<Modal>` triggers a new React.render which is why the context gets lost.

You'd need to somehow inject it, e.g. by using a wrapper that takes the values via props

```js
class ContextWrapper extends React.Component {
  getChildContext() {
    return {
      routeDepth: this.props.routeDepth,
      router: this.props.router
    };
  }

  render() {
    return this.props.children;
  }
}

ContextWrapper.propTypes = {
  routeDepth: PropTypes.number.isRequired,
  router: PropTypes.router.isRequired
};

ContextWrapper.childContextTypes = {
  routeDepth: PropTypes.number.isRequired,
  router: PropTypes.router.isRequired
};


// Usage
var MyComponent = React.createClass({
  mixins: [OverlayMixin],
  contextTypes: {
   routeDepth: PropTypes.number.isRequired,
   router: React.PropTypes.func
  },

  renderOverlay: function() {
    if (!this.state.isModalOpen) {
      return <span />;
    }
    return (
      <Modal>
        <ContextWrapper router={this.context.router} routeDepth={this.context.routeDepth}>
          <div className={cx('modal-body')}>
            <RouteHandler />
          </div>
        </ContextWrapper>
      </Modal>
    );
  },
});
```

**Comment by yoni-tock** [comment]
Doesn't that pass them as props rather than as context? I tried this and am still getting the same (or a closely related) error:

![screen shot 2015-04-07 at 9 49 01 am](https://cloud.githubusercontent.com/assets/11616747/7025760/5977d274-dd0b-11e4-9363-405a5bee07ff.png)

**Comment by yoni-tock** [comment]
So, I resolved this issue by moving away from using the `OverlayMixin`. Closing.

However, I am still having an issue with the owner vs. parent context being different.
