### ISSUE TITLE
Test component with <RouteHandler />

### ISSUE THREAD

**Issue by iam4x** [rackt/react-router#1055]
Hello,

When I try to stub a component with a `<RouteHandler />` it will just throw me a warning and won't render:

```
'Warning: Failed Context Types: Required child context `routeDepth` was not specified in `<<anonymous>>`
```

I followed https://github.com/rackt/react-router/blob/master/docs%2Fguides%2Ftesting.md

Suggestions?

**Comment by clementdubois** [comment]
+1

**Comment by taurose** [comment]
Try
```js
  childContextTypes: {
      router: React.PropTypes.func,
      routeDepth: React.PropTypes.number
    },

    getChildContext () {
      return {
        router: RouterStub,
        routeDepth: 0
      };
    },
```

**Comment by clementdubois** [comment]
This works fine thank you,
Do not forget to add the methods : 
```javascript
getRouteAtDepth() {},
setRouteComponentAtDepth() {},
```

in the assign RouterStub

**Comment by iam4x** [comment]
Thank's working like a charm @taurose 

I submitted a PR to update the docs.

**Comment by iam4x** [comment]
Since PR #1068 is merged, this is solved.
