### ISSUE TITLE
Tabbed Area with React Router not working

### ISSUE THREAD

**Issue by StuartHickey** [rackt/react-router#1056]
Hi All,

I'm trying to get TabbedArea working with react router but each time I hit a different Tab it just refreshes and displays the current Tab again. If I enter the path name in the browser it displays correctly but again if I click to go to another tab i just get a refresh of the current Tab. 

code snips below. Any Idea where I'm going wrong?

On a layout page I have the following 

      <div className="container">
        <Row>
          <Col md={12}>
            <TabbedArea defaultActiveKey={1}>
              <TabPane eventKey={1} tab='Stock' to="index"><RouteHandler /></TabPane>
              <TabPane eventKey={2} tab='Data' to="data"><RouteHandler /></TabPane>
              <TabPane eventKey={3} tab='Dashboard' to="dashboard"><RouteHandler /></TabPane>
            </TabbedArea>
          </Col>
        </Row>
      </div>

on the data page I have another tab area to display tabs below a header for the data page. 

            <Row>
              <Col md={12}>
                <TabbedArea defaultActiveKey={1}>
                  <TabPane eventKey={1} tab='Tab1' to="tab1"><RouteHandler /></TabPane>
                  <TabPane eventKey={2} tab='Tab2' to="tab2"><RouteHandler /></TabPane>
                  <TabPane eventKey={3} tab='Tab3' to="tab3"><RouteHandler /></TabPane>
                </TabbedArea>
              </Col>
            </Row>

Router Code in the app.js. 

    <DefaultRoute name="index" handler={IndexPage} />
    <Route name="profile" path="/profile" handler={ProfilePage} />
    <Route name="sign-in" path="/signin" handler={SignInPage} />
    <Route name="sign-up" path="/signup" handler={SignUpPage} />
    <Route name="sign-out" path="/signout" handler={SignOut} />
    <Route name="data" path="/data" handler={DataPage}>
        <Route name="tab1" path="/data/performance" handler={Tab1Page} />
        <Route name="tab2" path="/data/classification" handler={Tab2Page} />
        <Route name="tab3" path="/data/imagery" handler={Tab3Page} />
    </Route>
    <Route name="dashboard" path="/dashboard" handler={DashboardPage} />
    <NotFoundRoute handler={NotFoundPage} />

Router.run(routes, Router.HashLocation, function (Handler) {
  React.render(<Handler/>, container);
});

**Comment by srph** [comment]
Ah, you might want to fix the router code in the `app.js` ;).

**Comment by StuartHickey** [comment]
It's from react-bootstrap:
http://react-bootstrap.github.io/components.html#tabs

app.js code snippet not appearing for some reason.  


<Route handler={App}>
    <DefaultRoute name="index" handler={IndexPage} />
    <Route name="profile" path="/profile" handler={ProfilePage} />
    <Route name="sign-in" path="/signin" handler={SignInPage} />
    <Route name="sign-up" path="/signup" handler={SignUpPage} />
    <Route name="sign-out" path="/signout" handler={SignOut} />
    <Route name="data" path="/data" handler={DataPage}>
        <Route name="tab1" path="/data/performance" handler={Tab1Page} />
        <Route name="tab2" path="/data/classification" handler={Tab2Page} />
        <Route name="tab3" path="/data/imagery" handler={Tab3Page} />
    </Route>
    <Route name="dashboard" path="/dashboard" handler={DashboardPage} />
    <NotFoundRoute handler={NotFoundPage} />
</Route>

**Comment by mtscout6** [comment]
I posted a solution for this at react-bootstrap/react-bootstrap#129

**Comment by StuartHickey** [comment]
thanks, really appreciate it... it worked a treat!!!
