### ISSUE TITLE
this.context.router is undefined in ES6 class constructor

### ISSUE THREAD

**Issue by torarnek** [rackt/react-router#1059]
this.context.router is accessible in getInitalState(), however, it is undefined in 

```javascript
class MyComp extends React.Component{
  constructor(props){
    super(props);
    this.context.router // is undefined
  }
}

MyComp.contextTypes = {
    router: React.PropTypes.func.isRequired
};
```

My workaround is to do the init in componentDidMount(), however, that is weird...

**Comment by nukr** [comment]
```javascript
class MyComp extends React.Component{
  constructor(props, context){
    super(props);
    context.router // will work
  }
}

MyComp.contextTypes = {
    router: React.PropTypes.func.isRequired
};
```

**Comment by torarnek** [comment]
Fantastic. Thanks!

**Comment by ryanflorence** [comment]
should also `super(props, context)`

note in the 1.0 API you don't need to ask for the router off of context.

**Comment by juhaelee** [comment]
@ryanflorence can you explain and point to the api what you mean by you don't need to ask for the router off of the context. Does that mean you don't have to access the context by context.router? How else would you access the router?

**Comment by tygriffin** [comment]
+1 for @juhaelee's question. Can we access the router somehow without using context if we're using the class syntax? Or @ryanflorence, did you mean we don't need context if we're using the mixin with the `createComponent` syntax?

**Comment by BabakMN** [comment]
I'd also like some clarification about accessing router in 1.0 (when using ES6)

**Comment by taurose** [comment]
I guess he was referring to https://github.com/rackt/react-router/issues/1173 . There's no implementation yet, so I'd just use context for now.

**Comment by ali-master** [comment]
Hi
@nukr 
@torarnek 

**router** is not a **function**, it's an **object**, so:
```javascript
router: React.PropTypes.object.isRequired
```
