### ISSUE TITLE
How can I get current route name?

### ISSUE THREAD

**Issue by skuridin** [rackt/react-router#1060]
I want to change one param in current path: `this.context.router.transitionTo(currentRouteName, {lang: 'de'});` How can I get currentRouteName?

**Comment by kilometers** [comment]
https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md
``` javascript
var currentRouteName = this.context.router.getCurrentPath();
this.context.router.transitionTo(currentRouteName, {lang: 'de'});
```
If want to avoid adding another entry into History, you can instead use `this.context.router.replaceWith(currentRouteName, {lang: 'de'})`

**Comment by skuridin** [comment]
@kilometers I tried this method, but it doesn't work because when you pass two arguments to `transitionTo ` it wants to get route name instead of path as first param. My route name can be `home`, but path of it - `/`. Sorry for my English.

**Comment by kilometers** [comment]
I just ran a test, and both 'home' and '/' should work for transitionTo's first parameter. Assuming '/' was named 'home', they should both transition to the same route as well.

**Comment by skuridin** [comment]
My routes:
```
var routes = (
  <Route name="app" path="/:lang?" handler={AppComponent}>
    <DefaultRoute name="home" handler={HomeComponent}/>
    <Route name="about" handler={AboutComponent}/>
    <NotFoundRoute handler={NotFountComponent}/>
  </Route>
);
```
Place where I try to change lang:
```
`handleChangeLang: function(e) {
    e.preventDefault();
    var currentPath = this.context.router.getCurrentPath();
    var currentParams = this.context.router.getCurrentParams();
    if(currentParams.lang == e.currentTarget.lang) return;
    this.context.router.transitionTo(newPath, {lang: currentParams.lang});
  },
```

**Comment by taurose** [comment]
As far as I know `transitionTo(path, newParams)` is not supported. IIRC, there was some talk about supporting something like `transitionToParams(params)` where you wouldn't need the name, but I don't think it's implemented.

You can do:

```js
var currentRoutes = this.context.router.getCurrentRoutes();
var activeRouteName = currentRoutes[currentRoutes.length - 1].name;
this.context.router.transitionTo(activeRouteName, ...);
```

**Comment by skuridin** [comment]
@taurose thank you! You solution works for me.

**Comment by frg** [comment]
@taurose This also worked for my use case. Thanks

**Comment by mrdulin** [comment]
what's now with react-router v2.4.1?

**Comment by tommytcchan** [comment]
Also want to know what the method is for version >2.0 since I don't see that method anymore.

**Comment by jbayardo** [comment]
this.props.router.transitionTo is still there. However, when used, it seems to be throwing an exception when using substring in line 5 of the following snippet:

```
	    function addQuery(location) {
	      if (location.query == null) {
	        var search = location.search;

	        location.query = parseQueryString(search.substring(1));
	        location[SEARCH_BASE_KEY] = { search: search, searchBase: '' };
	      }

	      // TODO: Instead of all the book-keeping here, this should just strip the
	      // stringified query from the search.

	      return location;
	    }
```

The exception is:

> Uncaught TypeError: search.substring is not a function

**Comment by taurose** [comment]
`router.transitionTo` is now internal API; you shouldn't call it directly. Use `router.push` instead. 

The original question doesn't make sense anymore, since the router dropped support for named routes.

**Comment by Verikon** [comment]
for react-router ^2.4.1; this.props.location.pathname returns a string of the current route.

**Comment by yussan** [comment]
if you're using react-router ^2.0.0 just `this.props.route.name`

**Comment by simlw** [comment]
for **react-router ^2.4.1**, when I console.log this.props, I get a crtRoute property, It's the current I want.
`this.props.crtRoute `

**Comment by tanduong** [comment]
@anilapu That required `withRouter`. See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md.

**Comment by brunoAltinet** [comment]
Ok, you get the current route with pathname. But how dou you change a single param of that route?
