### ISSUE TITLE
RouteHandlerMixin is undefined?

### ISSUE THREAD

**Issue by kilometers** [rackt/react-router#1061]
``` javascript
import {RouteHandlerMixin} from 'react-router';
console.log(RouteHandlerMixin);  // returns undefined
```

Looking around, I'm seeing a lot of chatter about trashing RouteHandler... has that already happened? The context here is that I'm trying to get ReactTransitionGroup working, and from what I read the RouteHandlerMixin is needed.

**Comment by kilometers** [comment]
There's no /mixins directory... Is there any documentation on the new approach? I'm attempting what's shared in https://github.com/rackt/react-router/issues/727#issuecomment-76532035

**Comment by kilometers** [comment]
I found #543...

**Comment by duro** [comment]
I see you closed this, but did you find the Mixin? I am still really unclear on how to implement what is referenced in #543. Have you had any success?

**Comment by owais** [comment]
@kilometers @duro Any luck finding that Mixin?

**Comment by duro** [comment]
It's gone.

**Comment by owais** [comment]
@duro what a bummer. Any alternative to pull off stuff like this? 
```
var Index = React.createClass({
      mixins: [RouteHandler],
      render: function () {
        var handler = this.getRouteHandler({ myProp: 'value'});
        return (
            <div>
                <header>Some header</header>
                {handler}
           </div>
        );
  }
});
```

**Comment by legomushroom** [comment]
:( mixin was pretty useful, any alternatives?
