### ISSUE TITLE
auth-flow logout revisit

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1063]
The example of how to "Logout" in the auth-flow example isn't really very realistic. A "you're logged out" page isn't very common. A more common practice is that when you click "Logout" the user is taken back to the login page.

I can't seem to be able to figure out how to do this properly. I was assuming that the onChange event in the logout method (https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L159) would cause the App component to automatically re-issue the `willTransitionTo` call inside the requireAuth method -- but this doesn't happen.

Should I achieve the behavior I want by calling `this.context.router.transitionTo('login');` directly? It seems a bit counter-intuitive considering the `requireAuth` mixin is supposed to handle automatic redirection when the user isn't authenticated.

**Comment by ShaneG** [comment]
In my app I store the auth token and info in sessionStorage, so I basically clear the sessionStorage and transition to the frontpage:

```
import React from 'react';

class Logout extends React.Component {
    componentDidMount() {
        sessionStorage.clear();
        setInterval( () => this.context.router.transitionTo('/'), 2000);
    }

    render() {
        return (
            <p>You have been logged out, you will be redirected shortly to login...</p>
        );
    }
}

Logout.contextTypes = {
    router: React.PropTypes.func
};

export default Logout;
```

I'm not sure if there is a better way to handle this, but it seems to work. The user sees the logged out message for 2 seconds and then is taken to the front page.

**Comment by WRidder** [comment]
The way I handle it is by using a session store as well. When logging in/out the store is updated and relevant components are updated which are listening to the store. 

For pages which require auth (and are loaded when logging out) the app will transition to the login screen. 

```javascript
"use strict";
var sessionStore = require("local/stores/session");
var sessionActions = require("local/actions/sessionActions");
var connect = require("local/libraries/tmp_connect");
var State = require("react-router").State;

var authRoute = {
  mixins: [connect(sessionStore, "session"), State],
  statics: {
    willTransitionTo: function (transition, params) {
      if (!sessionStore.isLoggedIn()) {
        // Set return path
        sessionActions.setLoginReturnPath(transition.path);

        // Redirect
        transition.redirect("login");
      }
    }
  },
  componentWillUpdate: function() {
    var router = require("local/core/router").router;
    if (!sessionStore.isLoggedIn()) {
      // Set return path
      sessionActions.setLoginReturnPath(this.getPath());

      // Redirect
      router.transitionTo("login");
    }
  }
};

module.exports = authRoute;
```
See: https://github.com/WRidder/react-spa/blob/master/client/src/mixins/authRoute.js

**Comment by globexdesigns** [comment]
@WRidder Cool, that definitely helped. I ended up with a more simplified form of the componentWillUpdate. Basically, the only change made to the auth-flow demo was:

```
	// Have to save this to a variable so we can assign contextType below
	var Authenticated = class Authenticated extends React.Component {
		static willTransitionTo(transition) {
			if (!Auth.loggedIn) {
				transition.redirect('/login', {}, {
					target: transition.path
				});
			}
		}

		componentWillUpdate () {
			// We we logged out - go to login page
			if (!Auth.loggedIn) {
				this.context.router.transitionTo('/login');
			}
		}

		render() {
			return <Component {...this.props} />;
		}
	};

	// Assign a contextType so that we can reference the Router in componentWillUpdate
	Authenticated.contextTypes = {
		router: React.PropTypes.func
	};
```

**Comment by WRidder** [comment]
@globexdesigns Nice! Thanks for the update.
