### ISSUE TITLE
Referencing other statics objects in transition hooks

### ISSUE THREAD

**Issue by super-cache-money** [rackt/react-router#1073]
This may be a javascript question - but maybe there's something I'm overlooking. What would be the canonical way of achieving what I've set out to in this example:

    statics: {
        someKey: 'value',
        willTransitionFrom : function(transition, component){
           // how do I reference someKey?
        }
    }

**Comment by browniefed** [comment]
```
var aComponent = React.createClass({

statics: {
 abc: 'abc',
willTransitionFrom: function() {
//aComponent.abc
}
}
});
```

**Comment by super-cache-money** [comment]
Thanks!

**Comment by browniefed** [comment]
If you need to access statics in the instance I believe you can do `this.constructor.abc`
