### ISSUE TITLE
Get old active routes in willTransitionTo()

### ISSUE THREAD

**Issue by super-cache-money** [rackt/react-router#1075]
I'd like to determine which route is being transitioned **from** in a `willTransitionTo()` hook. Given that it's a static method, I can't see how to access context.router. What's the canonical way of achieving this?

**Comment by ryanflorence** [comment]
we've thought about this a bit, not a lot though.

I'd like to know what you're trying to achieve in your app. What's the product use-case?

**Comment by super-cache-money** [comment]
I needed to toggle animations when changing away from certain routes. I've since worked around this by putting the code in `componentWillReceiveProps()` of the root Route.

**Comment by ryanflorence** [comment]
on master routes come to your route components as props, so you can `componentWillReceiveProps` to get the old ones
