### ISSUE TITLE
Link onClick Promise Support

### ISSUE THREAD

**Issue by CalebMorris** [rackt/react-router#1077]
Currently Link only supports synchronous decision on whether or not to interrupt a transition.
It would be nice to have support of promises (or callbacks at least) to allow asynchronous workflow without adding the router from the context.

**Comment by stevenpetryk** [comment]
:+1:

**Comment by stevenpetryk** [comment]
I can work on a PR for this later today.

**Comment by ryanflorence** [comment]
`<Link>` is simply a router-aware `<a>`, which does not have an asynchronous `onClick` API.
