### ISSUE TITLE
Confused about partial-app-loading

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1080]
I've used the partial-app-loading example to build a similar process in my app, but now I'm seeing this warning message in the console:

```
Warning: Don't set .props.activeRoute of the React component <RouterComponent />. Instead, specify the correct value when initially creating the element.
```

Is the example out of date? Is there another way I should be setting the RouteHandler? The example shows the code as:

```
// Can't find RouteHandler in the loaded component, so we just grab
// it here first.
this.props.activeRoute = <RouteHandler/>;
return <Component {...this.props}/>;
```

**Comment by globexdesigns** [comment]
I've switched over to using this instead: https://github.com/rackt/react-router/issues/751#issuecomment-72381416 which has made the error go away.

I also see #755 is meant to address this in the future.

Closing.

**Comment by rgrwkmn** [comment]
Make a new object from your props and set activeRoute. The error is from React because it doesn't want you to set props, they should only be passed into the component from a parent.

```javascript
var props = this.props;
props.activeRoute = <RouteHandler/>;
return <Component {...props}/>;
```

**Comment by globexdesigns** [comment]
@rgrwkmn That didn't help. Still getting the warning message.

**Comment by rgrwkmn** [comment]
Ah, right, you need to actually make a new object, just setting it to another variable still references this.props. If you use underscore or something like it, this works: 

```javascript
var props = _.extend({}, this.props);
props.activeRoute = <RouteHandler/>;
return <Component {...props}/>;
```

**Comment by globexdesigns** [comment]
That did the trick.

Should I keep the issue open so the official example code can be updated?

**Comment by ryanflorence** [comment]
go check out the new `huge-apps` example, partial-app loading just got amazing in on master (1.0 API)
