### ISSUE TITLE
How to navigate to new route outside of a React Component

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1081]
Is it possible to interact with the React Router outside a React Component's context?

For example, let's say I want to have a random Javascript module simply navigate me to the home page every 10 seconds, ie:

```
var Router = require('react-router');

module.exports = function () {
	setTimeout(function () {
		// Need a way to navigate the router here since I don't have access to React.context
		Router.Something.navigate('/home');
	}, 10000);
};
```

**Comment by globexdesigns** [comment]
Nevermind. Looks like the solution is to save the return value from `Router.run`.

```
// Where ever you call Router.run(). Save the return value
window.AppRouter = Router.run(...);

// Now you can reference the Router programmatically anywhere
setTimeout(function () {
        AppRouter.transitionTo('/home');
    }, 10000);
```

I would recommending adding this to the docs as it wasn't obvious that the return value of Router.run was actually useful.

**Comment by srph** [comment]
It would be useful, but I think it can create a circular dependency in most cases.

**Comment by srph** [comment]
Also, you might want to use [`Router.create`](https://github.com/rackt/react-router/blob/master/docs/api/create.md) instead :wink:

**Comment by markthethomas** [comment]
Is there a better way to do this with in an individual component than assigning it to the global window object? I try to avoid that when possible :) I'm using browserify to bundle my react app and the `Router.run()` is called in a root `App` component. I would just use the mixin to accomplish this, but I've read that mixins are on their way out as far as react goes and am trying to avoid relying on them too much

**Comment by EugeneZ** [comment]
If you're using browserify, you can simply export the return value of `Router.run()`.

    //router.js
    module.exports = Router.run(...)

    //MyComponent.js
    var router = require('./router.js');
    router.transitionTo('routeName');

**Comment by markthethomas** [comment]
Yeah, that was my initial approach, but for some reason browserify is having trouble `requiring` it; I persistently get a `cannot find module ../app`. Trying to require it w/ the following structure consistently throws an error:
    ----`../other-files`
    ----`jsx/`
     --------| `app.jsx` (w/ `module.exports =  Router.run(...)`)
     --------| `shared/`
     ------------|  `File-A` (`require`ing from here as `require('../app)`)

Really puzzled by why it's not working. Other sibling files of the same kind don't throw an error. At any rate, this isn't a react-router thing as far as I can tell.

**Comment by th0r** [comment]
@markthethomas Maybe circular dependency?

**Comment by EugeneZ** [comment]
@markthethomas I had the same issue. Place your `require('../app')` call inline worked for me. I don't know why!

**Comment by markthethomas** [comment]
@th0r I thought so too but don't seem to find that to be the case. I'll try inlining it. Thanks all!

**Comment by markthethomas** [comment]
Still not working with `require('../app.jsx').transitionTo('/foobar);`. I'll have to keep looking into it

**Comment by ryanflorence** [comment]
you've probably got circular deps, might need a module/container to register the instance on, then other modules can require that container and ask for it later.

**Comment by markthethomas** [comment]
Good point; I'll try that. Thanks!
