### ISSUE TITLE
How to disable Link

### ISSUE THREAD

**Issue by jmgarciamari** [rackt/react-router#1082]
Hi, I need all Links disables until user fills all data in inputs, how can I do this?
Thanks

**Comment by Chrazy** [comment]
Use willTransitionFrom?
https://github.com/rackt/react-router/blob/master/docs/api/components/RouteHandler.md

**Comment by ryanflorence** [comment]
there is no "disabled" attribute for anchor tags, and `Link`s are just router aware anchor tags.

**Comment by Neta-Alon** [comment]
This question scores high on Google, I think it should contain an answer.
## 1. onClick event ##
`````javascript
class foo extends React.Component {
  handleClick(e) {
    e.preventDefault();
  }
  render() {
    return (
      <Link to='/bar' onClick={this.handleClick}>Bar</Link>
    );
  }
}
`````
Even simpler:
`````javascript
class foo extends React.Component {
  render() {
    return (
      <Link to='/bar' onClick={e => e.preventDefault()}>Bar</Link>
    );
  }
}
`````

## 2. using CSS's `pointer-events` attribute ##
`````javascript
/* js file */
class foo extends React.Component {
  render() {
    return (
      <Link to='/bar' className='disabled-link'>Bar</Link>
    );
  }
}
`````
`````css
/* css file */
.disabled-link {
  pointer-events: none;
}
`````

Method 2 is the "right" way to do it, but it lacks browser support. Today, only latest versions of Chrome, FireFox and Opera support it (IE doesn't).
See [StackOverflow answer](http://stackoverflow.com/a/10276157/2422544) for more details and methods.

@ryanflorence `disabled` attribute **does** exist for anchor tags, only by IE. The StackOverflow answer attached suggested using both `disabled` and `pointer-events: none` for maximum browser-support.
`````css
a[disabled] {
    pointer-events: none;
}
`````
