### ISSUE TITLE
Unneeded "No route matches" warning on Redirect from "/"?

### ISSUE THREAD

**Issue by cluelessjoe** [rackt/react-router#1088]
I'm using the following routes
```javascript
  <Route name="app" path="/" handler={App}>
    <Redirect from="/" to="desk" />
    <Route name="desk" handler={Desk}/>
    <Route name="search" handler={Search}/>
  </Route>
```

The corresponding [zombie](https://github.com/assaf/zombie) test displays the following warning:
Warning: No route matches path "". Make sure you have <Route path=""> somewhere in your routes

It feels like it's wrong, in this case path "" is matched by the redirect from "/"...

Or am I missing something (quite likely)?

And thanks a lot for react-router!

**Comment by ryanflorence** [comment]
```js
<Route name="app" handler={App}>
    <Route path="/" name="desk" handler={Desk}/>
    <Route name="search" handler={Search}/>
  </Route>
```

**Comment by cluelessjoe** [comment]
thanks a lot for your answer

however, your route definition is not the same as the one above:
1 - I would like the /desk path to still exist and serve the Desk handler
2 - I would like /desk to be the default url when reaching the app, currently it means redirecting / to /path

The point 1 isn't fulfilled in your solution

When I tried 
  <Route handler={App}>
    <Redirect from="/" to="desk"/>
    <Route name="desk" path="desk" handler={Desk}/>
    <Route name="search" path="search" handler={Search}/>
  </Route>
this still triggers the warning "Warning: No route matches path "". Make sure you have <Route path=""> somewhere in your routes"
