### ISSUE TITLE
willTransitionTo cannot parse query params when hash url is the last element

### ISSUE THREAD

**Issue by alanrubin** [rackt/react-router#1090]
Hey guys,

When trying to initialise an application with a sample URL http://localhost/?code=XXX&state=YYY, I get redirected by the HashLocation.js to http://localhost/?code=XXX&state=YYY/#/ (ensureSlash method).

It seems that RFC states that the hash part should be last part of the URL so that seems right.

The problem is that willTransitionTo(...) API is not able parse the queryParams in that way. We get  the query params object empty (3rd param in the callback) even that we have a query string. 

Checking the code for HashLocation#getHashPath I see you are using window.location.href.split("#")[1] to decode the query+hash - this seems to be wrong, as this only returns "/" and ignores the query string.

What do you think ?

**Comment by ryanflorence** [comment]
https://rackt.github.io/react-router/tags/v0.13.3.html#HashLocation
