### ISSUE TITLE
Using Link only updates path and doesn't change anything in the DOM

### ISSUE THREAD

**Issue by DanielMSchmidt** [rackt/react-router#1091]
Hi there, first of all thanks for this great lib!

I wanted to build an application with it, so I copied and renamed parts of the [overview example](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md). I used links everywhere, but only the url is getting updated and not the content (a full page reload does the job, though).
What am I missing?

My routes are defined [here](https://github.com/DanielMSchmidt/danceTrainingCompanion/blob/5f7ad9e542e22f0ad4a6f81a8ec0577cad4d760d/frontend/src/scripts/components/main.js#L15-21), the route handler [here](https://github.com/DanielMSchmidt/danceTrainingCompanion/blob/5f7ad9e542e22f0ad4a6f81a8ec0577cad4d760d/frontend/src/scripts/components/FrontendApp.js#L56-65) and the links [here](https://github.com/DanielMSchmidt/danceTrainingCompanion/blob/5f7ad9e542e22f0ad4a6f81a8ec0577cad4d760d/frontend/src/scripts/components/Header.js#L28-29).
Thanks for your help!

**Comment by babsonmatt** [comment]
Does removing the PureRenderMixin do anything?

**Comment by DanielMSchmidt** [comment]
Yes, that did the trick. Well, could have thought about that, thanks for your help!

**Comment by babsonmatt** [comment]
No prob!
