### ISSUE TITLE
I would like to use indices in query array

### ISSUE THREAD

**Issue by davidtheclark** [rackt/react-router#1092]
https://github.com/rackt/react-router/issues/901 reflects a decision to hard-code qs's arrayFormat as "brackets" instead of providing react-router users with the option to decide.

I would like to use indices as my query's arrayFormat, not brackets. Is there a way you know that this can be done currently with react-router? Or are you open to build in some way for users to choose the arrayFormat?

Otherwise I will have to resort to hacking the URL/history myself, which is very much not ideal.

**Comment by worklez** [comment]
:+1: I would like to have this configurable too. Escaped brackets just look ugly when you have otherwise human-readable query string.

**Comment by ryanflorence** [comment]
on master (1.0 API) you can plug in your own query parsing/stringifying, guide coming soon.
