### ISSUE TITLE
ERR_ACCESSORS_NOT_SUPPORTED with V0.13.2 when using IE8

### ISSUE THREAD

**Issue by codeuniquely** [rackt/react-router#1095]
React-Router v0.13.2 when using es5 Shim / Sham (v4.1.1) and V 0.13.1 of React always throws the error ERR_ACCESSORS_NOT_SUPPORTED at line 361 of es5Sham.

When env !=== production REACT Fails (So the advise is to set "production" and then test on IE 8.

in env !=== production its :
```
  defineProperty [Line: 360, Col: 13], es5-sham.js
  defineWarningProperty [Line: 33, Col: 3], ReactElement.js
  defineMutationMembrane [Line: 75, Col: 7], ReactElement.js
  Anonymous function [Line: 146, Col: 3], ReactElement.js
  Anonymous function [Line: 1, Col: 1], ReactElement.js
```

But if you set env==="production" the React Router causes the Failure....

in env == production the Call stack is:
```
  defineProperty [Line: 361, Col: 17], es5-sham.js
  defineProperties [Line: 391, Col: 17], es5-sham.js
  defineProperties [Line: 3, Col: 192], TestLocation.js        (react-router)
  Anonymous function [Line: 3, Col: 307], TestLocation.js  (react-router)
  Anonymous function [Line: 24, Col: 3], TestLocation.js    (react-router)
  Anonymous function [Line: 15, Col: 1], TestLocation.js    (react-router)
```

**Comment by pkese** [comment]
This has been discussed before. Check #1022 #1040 #1072 

There's a pull request waiting for someone to decide if react-router is ever intended to support IE8 again. Id doesn't seem there's much activity on this project.

**Comment by leoselig** [comment]
Again, +1 on this!
IE8 support is still important for many businesses
We'd have to drop react-router if this does not get fixed
Also, I think it makes sense for one of the most popular react plugins to provide the same browser support as react itself

**Comment by cateland** [comment]
Same as above IE8 can run natively on Windows 7 and is still widely used by our business partnairs.

**Comment by ryanflorence** [comment]
master (1.0 API) is IE8 compatible (removed all the babel and getter stuff)
