### ISSUE TITLE
componentDidMount for childmost route?

### ISSUE THREAD

**Issue by braco** [rackt/react-router#1096]
I would like to know when the last child route is actually rendered. Is this possible from the top down?

```
 Router.run(routes, function (Handler, state) {
     // How can we attach a componentDidMount to the lowest child here?:
    routes.slice(-1)[0];
 })
```

**Comment by MikeBarnhardt** [comment]
What is stopping you from just putting `componentDidMount` in the last child routes handler?

I don't think what you're trying is possible.
