### ISSUE TITLE
Redirects should merge properties before validating

### ISSUE THREAD

**Issue by TimothyRHuertas** [rackt/react-router#1097]
For backward compatibility when a user navigates to `my-space/search` I want to redirect to `my-space/search/partners`.  I tried the following approach, but got 'Uncaught Error: Invariant Violation: Cannot find a route named ":space/search/:searchType"'.  

```
 <Route name="app" path="/" handler={App}>
    <Route name="search" path=":space/search/:searchType" handler={ArtworkSetListPage}/>
    <Redirect from=":space/search" to=":space/search/:searchType" params={{searchType: "partners"}}/>
  </Route>
```

I think the router should merge the arguments (:space and :searchType) before doing the validation.

**Comment by ryanflorence** [comment]
hi tim!

duplicate #1034 (I think)

**Comment by TimothyRHuertas** [comment]
Agreed.
