### ISSUE TITLE
Declarative constraints for dynamic segments ?

### ISSUE THREAD

**Issue by jeron-diovis** [rackt/react-router#1103]
I'm surprised that it's impossible to define constraints for dynamic segments - like "match route only when ':foo' is number". Do you have any plans for implementing this feature?

Also, how do you handle such cases for now? Let say I have 
```JSX
<Route name="player" path="player/:mode" handler={Player} />
```
where `:mode` can be only one of `video`, `img`, `quiz`. As we have no constraints, when someone enters `player/foo`, route is matched, components tree is created and rendered, and only then, in the `Player` component, I should do something like
```JavaScript
if (!/^video|img|quiz$/.test(this.context.router.getCurrentParams().mode)) {
   this.context.router.transitionTo('not-found');
}
```
Besides that this puts routing logic deep inside components and produces a boilerplate code, it doesn't work with server-side rendering - because in Node router is always initialized with StaticLocation and so `transitionTo` raises an error.
So could you please give any advice about this?

**Comment by bishtawi** [comment]
Its actually a bigger issue. If I have a route like "/room/:id", I dont know if that room id is valid until I check with the server. We need a way to be able to return a 404 on invalid dynamic segments. On the client it isnt so bad as you can just render your 404 component and call it a day. However, this does not work well on the server as there is no way to return a 404 error status.

**Comment by ryanflorence** [comment]
you can render a 404 with server side rendering, and transitionTo calls onAbort and gives you a chance to redirect to wherever you need to go, and finally, you can validate in `willTransitionTo` and then redirect somewhere else if a parameter is invalid.

Not sure there's anything actionable here.

FYI, starting an issue with "I'm surprised that it's impossible to ..." makes me less helpful, not more.

**Comment by jeron-diovis** [comment]
> transitionTo calls onAbort and gives you a chance to redirect to wherever you need to go

[Where it calls `onAbort`?](https://github.com/rackt/react-router/blob/57543eb41c/modules%2FcreateRouter.js#L247-L256)

As on server side only `StaticLocation` can be used (because other ones use `window` inside), using `transitionTo` we always will get [there](https://github.com/rackt/react-router/blob/57543eb41c/modules%2Flocations%2FStaticLocation.js#L32-L34).

>  finally, you can validate in willTransitionTo and then redirect somewhere else if a parameter is invalid.

Ok, besides my source question.
Let say we have a bunch of routes "products/:productSlug". Need to check that a product with specified productSlug exist - so need an access to data store. 

`willTransitionTo` receives a transition, params, query and callback. And is called in context of Route instance. 

How do I access my data with this stuff? 

In [callback](https://github.com/rackt/react-router/blob/57543eb41c/modules%2FcreateRouter.js#L402) I can do whatever I want - but callback is called *after* all hooks are executed, so there is no chance to abort transition there. The only option remained is `transitionTo` - whose problem is described above. The circle is closed.
