### ISSUE TITLE
<RouteHandler> and <CSSTransitionGroup> not removing components properly.

### ISSUE THREAD

**Issue by MikeBarnhardt** [rackt/react-router#1104]
In a parent route handler:
```
render () {
    return (
        <Transition component='div' transitionName='RouteTransition'>
            <RouteHandler {...this.props} key={this.props.pathname}/>
        </Transition>
    );
}
```
In a nested route handler:
```
render () {
    return <RouteHandler {...this.props}/>;
}
```

And then when I navigate between pages of the child route it doesn't properly remove them and I get warning messages: _Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition._

However if I do this:
```
render () {
    return <div><RouteHandler {...this.props}/></div>;
}
```
...it works fine. Adding a key to the `<RouteHandler/>` doesn't fix it.

Not sure if this is an issue with CSSTransitionGroup or not. Anyone have any ideas aside from just adding unnecessary div's to the route handlers?

**Comment by dozoisch** [comment]
What does your css looks like?

You need to set an on-leave transition OR set the `transitionLeave={false}` in order for the cleanup to happen properly.

See https://facebook.github.io/react/docs/animation.html

**Comment by airwin** [comment]
I think this is an issue of the CSSTransitionGroup, because browsers sometimes didn't trigger the transitionEnd event. May this can help: https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx 
But in fact even using the 'setTimeout' way there's also problem with more than one elements entering or leaving, confusing..

**Comment by MikeBarnhardt** [comment]
@dozoisch I have the CSS transitions set up properly for both `enter`, `enter-active`, `leave`, and `leave-active`. Like I said it works fine with the `<RouteHandler/>` wrapped in a `<div>`.

```
.RouteTransition-enter {
    opacity: 0.01;
    -webkit-transition: opacity 150ms ease-in;
    transition: opacity 150ms ease-in;
}

.RouteTransition-enter.RouteTransition-enter-active {
    opacity: 1;
}

.RouteTransition-leave {
    opacity: 1;
    -webkit-transition: opacity 150ms ease-in;
    transition: opacity 150ms ease-in;
}

.RouteTransition-leave.RouteTransition-leave-active {
    opacity: 0.01;
}
```

@airwin Interesting... maybe `transitionend` is not reliable across browsers. That may explain some of the weird results I'm getting. I don't mind wrapping my `<RouteHandler/>` in a `<div>` if that solves the problem.

**Comment by jonaswindey** [comment]
I have the same problem even when putting it in a div. The strange thing is that I can't reproduce it easily, it just randomly happens when I navigate through my app.

**Comment by RassaLibre** [comment]
Have the same problem like @jonaswindey. It just happens randomly.

**Comment by vincenzo-antolini-os** [comment]
Have the same problem more frequently using Project Spartan IE10.

**Comment by marbemac** [comment]
has anybody made any progress investigating this? running into it now

**Comment by postbud** [comment]
+1 @dozoisch
A similar problem. After key added, the components are not removed after the transition. Adding to the properties of the line `transitionLeave={false}` to correct the situation

**Comment by Kamilius** [comment]
Same problem for me. It appears to do something with animation time on enter/leave. My scenario is that I have an item which appears/disappears on button click. When button is clicked really fast multiple times this problem appears. 
But besides this scenario, it simply appears randomly from time to time.

**Comment by bbnnt** [comment]
damn… sorry to end up thinking that but csstransition are as limited as extremely weak. randomly working. hope that'll improve
