### ISSUE TITLE
Provide more general willTransition

### ISSUE THREAD

**Issue by maspwr** [rackt/react-router#1105]
`willTransitionTo` and `willTransitionFrom` are really useful when routing changes cause different components to render. But if you have the same component, and you still want to hook in transition logic on a routing change, it would be useful to have a callback that still gets called. For example, in the following scenario:

```
# App -> TodoList (/todos)
# App -> TodoEdit (/todo/1)
```

Imagine `TodoEdit` has a link to `/todos`. I might want to catch transitions away from `TodoEdit` and abort them if the todo has not been saved. `willTransitionFrom` on `TodoEdit` will work for that. But if I want to do that for *any* component at any level of the router hierarchy, it would be more convenient to define some callback at the `App` component to handle that logic.

**Comment by ryanflorence** [comment]
`Router.run` is your "hook" for all transitions.

in 1.0 `<Router onChange={fn}/>` is your hook.
