### ISSUE TITLE
DefaultRoute does not work

### ISSUE THREAD

**Issue by rogierschouten** [rackt/react-router#1107]
With react-router 0.13.2:

The snippet below always ends up in the NotFoundRoute.
```
	<Route name="navigation" path="/" handler={Navigation}>
		<DefaultRoute name="home" handler={Dashboard}/>
		<NotFoundRoute handler={NotFound}/>
	</Route>
```

This however works as intended and shows the Dashboard by default:
```
	<Route name="navigation" path="/" handler={Navigation}>
		<Route path="/" name="home" handler={Dashboard}/>
		<NotFoundRoute handler={NotFound}/>
	</Route>
```

Am I doing something wrong?

**Comment by FelikZ** [comment]
Same here

**Comment by taurose** [comment]
Works as intended for me using DefaultRoute. Can you put together a minimal failing example?

**Comment by VladZheleznyak** [comment]
Doesn't work for me too.
var routes = (
    <Route handler={App}>
        <DefaultRoute handler={LoginPage.Login} />
        <Route name='login' handler={LoginPage.Login}/>
        <Route name='sign_up' handler={LoginPage.SignUp}/>
        <Route name='trading_account' handler={TradingAccount}/>
        <Route name='my_account' handler={UserAccount}/>
        <Route name='my_account_edit' handler={EditUserAccount}/>
        <Route name='sign_up_investor' handler={InvestorSignUp}/>
    </Route>
);
console.log(routes);
--------------
at console: 

1) ReferenceError: DefaultRoute is not defined
React.createElement(DefaultRoute, {handler: LoginPage.Login}),
compone...?body=1 (строка 53)

2) ReferenceError: DemoComponent is not defined
DemoComponent
react_u... > eval (строка 1)

**Comment by gregbenner** [comment]
var Router = require('react-router')
var DefaultRoute = Router.DefaultRoute

**Comment by elverskog** [comment]
Thanks! Can someone update the official docs to include this?

**Comment by ryanflorence** [comment]
default route has tests and examples that all work. maybe we have a weird bug with adding a name, remove that and it should be fine?

**Comment by alexanderbanks** [comment]
I'm still getting similar behavior. I do not have a name on my routes. Am I misunderstanding the defaultroute functionality?

````javascript
var routes = (
	<Route path="/" handler={App}>
		<DefaultRoute handler={LoginForm} />
	</Route>
);

Router.run(routes, function(Handler) {
	React.render(<Handler />, document.body);
})
````

In the above code App is run but LoginForm never gets rendered.

**Comment by kevr** [comment]
@ryanflorence The current documentation as of today does not work as expected. There are errors about how DefaultRoute attempts to render the component. I'm using React with ES6.

**Comment by timdorr** [comment]
This is a very old API that is not in the current version. Please read the docs for the latest API you should be using. You're looking for IndexRoute now.
