### ISSUE TITLE
Expose LocationActions

### ISSUE THREAD

**Issue by koggdal** [rackt/react-router#1110]
I need to write my own `Location` implementation for a project I'm working on, and according to the [docs](https://github.com/rackt/react-router/blob/master/docs/api/Location.md) that should be totally okay. However, all the built-in `Location` implementations use the `LocationActions` module, but as [suggested in the docs](https://github.com/rackt/react-router/tree/master/docs/api#public-modules) only things exposed on the default export object are considered public, which means I can't access `LocationActions`.

* Is there a reason this is not public, or should I send a PR to expose it?
* Is this module used internally so that the action values can be swapped later? In other words, it's not safe to just use the action values directly?

**Comment by ryanflorence** [comment]
if you have a commonjs build, just require it in.

Note that in 1.0 this is all quite different though.

**Comment by funkytek** [comment]
@ryanflorence any guidance on migrating from using LocationActions?  Didn't see anything in 1.0 migration guide
