### ISSUE TITLE
Custom getWindowScrollPosition

### ISSUE THREAD

**Issue by steffenmllr** [rackt/react-router#1112]
Just wanted to ask if it is possible to customize the `getWindowScrollPosition` function?

Trying to record the scroll position within a overflow scroll div and I want the router to retain the position within the div when the router changes.

Would you accept a PR to make the `getWindowScrollPosition` configurable within the `scrollBehavior` like the `updateScrollPosition` function ?

**Comment by nhutquang97** [comment]
I also need this configuration. This is very useful, especially on mobile.

**Comment by marciocaraballo** [comment]
I am also having a similar issue, customization of that function could help it

**Comment by gaearon** [comment]
Yeah.. Let's do it in [1.0](https://github.com/rackt/react-router/pull/1158)

**Comment by zhenkunou** [comment]
+1 
thx @gaearon

**Comment by ryanflorence** [comment]
I haven't looked much at the current scroll implementation, is this possible on master?

**Comment by gaearon** [comment]
It appears possible.

https://github.com/rackt/react-router/blob/d11e1417c2e8a7f47e53c6936c0a87a87a8dc259/modules/DOMHistory.js#L11
https://github.com/rackt/react-router/blob/d11e1417c2e8a7f47e53c6936c0a87a87a8dc259/modules/ScrollManagementMixin.js#L40-L43

**Comment by mjackson** [comment]
Yes, you can do this in 1.0. Use [`new BrowserHistory({ getScrollPosition })`](https://github.com/rackt/react-router/blob/5d674c9515aa628b644c223b2e3f43bb28ac24bc/modules/DOMHistory.js#L11) to specify a custom function that should return `{ scrollX, scrollY }`. Of course, this only works with DOM histories (`HashHistory` and `BrowserHistory`).
