### ISSUE TITLE
When a link is hit again (no change in the address) nothing happens when a refresh is expected

### ISSUE THREAD

**Issue by emp** [rackt/react-router#1115]
Currently, the only way to reload the same "page" is to actually refresh the browser. If you have a link to, say, /home and you click it again, no new content from /home is fetched, same behavior with the hash URLs.

A quick question on the reactiflux general group in slack told me this is expected, but from an user perpective I'd say the expected behavior is that a link when clicked again should refresh, say that I am on reddit/r/all and I've been away for a while, when I return I click on ALL again in the topbar to refresh the content, not just hitting CMD+R, F5 or the browser reload.

Is there a way to work around that without something like a randomized parameter for links?

**Comment by rgrwkmn** [comment]
Why does the user want the page to refresh? Maybe there should be a refresh button somewhere to update the content on the page.

**Comment by emp** [comment]
I believe the reddit example explains it well, you have 100+ links in the same place, you end up re-using those links to refresh content since it is how you got there in the first place.

**Comment by taurose** [comment]
I'd prefer that behavior as well  (#826); it's also how browsers behave on static pages.
I can't think of a clean workaround. You could give the PR (#1031) a try though.

**Comment by emp** [comment]
Thanks, #826 also shed some light on the history spam in your example, which I didn't consider. The PT looks in the right direction.

**Comment by th0r** [comment]
+1
I think "refresh on click"  behavior should be configurable.

**Comment by hiddentao** [comment]
+1

**Comment by frontengineer** [comment]
Help, please. Given the reddit example "yes," the page reloads, but the when you hit "back" button your history goes -1, whereas the ReactRouter each reload is a new history.push()...meaning I might click "href=/About" 5 times...then I will need to hit back button 5 times to get off about.  

Is there a discussion or correct approach (beyond < Link to="About" >) for this?

**Comment by ryanflorence** [comment]
follow #826 and #1031 thanks :)
