### ISSUE TITLE
Transition animation for specific route

### ISSUE THREAD

**Issue by genxstylez** [rackt/react-router#1116]
As title, how do I set animation for one route in a routehandler?

Cheers.

**Comment by MikeBarnhardt** [comment]
I know this is a bit of a workaround but if you use just plain `TransitionGroup` instead of `CSSTransitionGroup` then you can call the animation methods at the component level. You could only call those components on the one route.

[TransitionGroup Docs](http://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup)

**Comment by genxstylez** [comment]
Sorry,

Can you give me a quick example?

**Comment by MikeBarnhardt** [comment]
```js
<TransitionGroup>
    <RouteHandler/>
</TransitionGroup>
```
```js
let routeWithAnims = React.createClass({
    componentWillAppear (callback) {
    },
    componentDidAppear (callback) {
    },
    componentWillEnter (callback) {
    },
    componentDidEnter (callback) {
    },
    componentWillLeave (callback) {
    },
    componentDidLeave (callback) {
    }
});
```

**Comment by genxstylez** [comment]
So that means I declare the routes under the routehandler first, then create the route again?

**Comment by genxstylez** [comment]
@MikeBarnhardt 

So I will need to create the route using a component instead of the <Route xxxx /> tag?

**Comment by MikeBarnhardt** [comment]
I don't really know what you're asking since you're giving no information about your project.

Assuming you have the following `routes.js` files:
```
...
var Post = require('./components/Post.jsx');
...

module.exports = {
    <Route path='/' handler={App}>
        <Route path='about' handler={About}/>
        <Route path='posts' handler={PostsHandler}>
            <Route path=':id' hander={Post}/>
            <DefaultRoute handler={Posts}/>
        </Route>
    </Route>
}
```

Try this in your `Post.jsx`:
```
var React = require('react/addons');
var ReactCSSTransitionGroup = React.addons.CSSTransitionGroup;
...
var Post = React.createClass({
    render: function () {
        var path = this.props.path;
        var handler = <RouteHandler {...this.props}/>;

        if (path === '/posts/123' ) {
            handler = (
                <ReactCSSTransitionGroup>
                    <RouteHandler {...this.props}/>
                </ReactCSSTransitionGroup>
            );
        }

        return {handler};
    }
});
```

It will only return the TransitionGroup for the path and/or params you specify...

**Comment by genxstylez** [comment]
Cool, that's exactly what I need, Sorry for the confusion though.

**Comment by genxstylez** [comment]
The transition works, but when I do a `this.goBack()` the component is not deleted, and getting a warning saying 
`Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.`

```
       const name = this.getPath();
        return (
             <TransitionGroup component="div" transitionName="post">
                <RouteHandler key={name}/>
            </TransitionGroup>
        );
```

**Comment by MikeBarnhardt** [comment]
You either need to add the relevant CSS classes in your file:
```css
.post-enter { opacity: 0; transition: opacity 100ms ease-in; }
.post-enter.post-enter-active { opacity: 1; transition: opacity 100ms ease-in; }
.post-leave { opacity: 1; transition: opacity 100ms ease-in; }
.post-leave.post-leave-active { opacity: 0; transition: opacity 100ms ease-in; }
```

or remove the leave transition entirely:
```js
<TransitionGroup component="div" transitionName="post" transitionLeave={false}>
```

**Comment by genxstylez** [comment]
closing this issue, thanks for the help.
