### ISSUE TITLE
RouteHandler somehow loops

### ISSUE THREAD

**Issue by tmcw** [rackt/react-router#1117]
I'm upgrading a 0.12 app to 0.13 with the react-router upgrade. My routes look like:

```js
module.exports = (
  <Route handler={App}>
    <DefaultRoute name='style_menu' handler={StyleMenu} />
    <Route
      path='/styles/view/:styleId/'
      name='view'
      handler={ViewPage}>
    </Route>
    <Route
      path='/styles/edit/:styleId/'
      name='style'
      handler={Workspace}>
      <Route name='layers' handler={Layers}>
        <Route name='new_layer' path='new' handler={NewLayer} />
        <Route name='layer' path=':layerId' handler={EditLayer} />
        <Route name='multilayer' path='multi/:layerIds' handler={Layers} />
        <Route name='property' path='property/:type/:property' handler={EditProperty} />
      </Route>
      <NotFoundRoute name='index' handler={Layers} />
    </Route>
    <Route path='login' name='login' handler={AuthenticationModal} />
    <Redirect from='/styles/edit' to='style_menu' />
    <Redirect from='/styles/edit/' to='style_menu' />
    <Redirect from='/styles' to='style_menu' />
    <Redirect from='/styles/' to='style_menu' />
    <NotFoundRoute name='not_found' handler={NotFound} />
  </Route>);
```

and I'm getting the oddest error: using RouteHandler, pretty vanilla, to nest my components, I get this structure:

![2015-04-23 at 2 15 pm](https://cloud.githubusercontent.com/assets/32314/7304137/37789914-e9c3-11e4-9d55-b34a024a313d.png)

As you can see, at a certain point RouteHandler exposes the `App` component again, deeper in the app's structure. And even weirder, the [App component is totally scoped to the routes module](https://gist.github.com/tmcw/62c24a0c8f2f1d68172a) so it's not like I could be accidentally requiring and instantiating it.

**Comment by tmcw** [comment]
I was mutating getRoutes in place :| Classic Thursday! Sorry for the noise.

**Comment by scoarescoare** [comment]
Ah, I too was running into this. Thanks for mentioning `getRoutes`. I was using that because I followed an old docs example: https://github.com/rackt/react-router/commit/9fb2615d015827522bf72911f6782492596256f3. Guessing others using that approach will run into this.
