### ISSUE TITLE
Support for multiple trailing slash replacement

### ISSUE THREAD

**Issue by vegetableman** [rackt/react-router#1118]
So here's are my routes:-

```js
<Route name='agency' path='/agency/?:agencyCode?/?' handler={Agency}>
    <Route name='agency-info' path='contact-info' handler={AgencyContactInfo}/>
</Route>
```

When I do a transition to agent-info using:-
```js
this.context.router.transitionTo('agency-info', null, {agencyCode: 1})
```
am expecting a url like :- ```agency/contact-info?agentCode=1```

instead I get this:- ```agency/?%2Fcontact-info=&agentCode=1```

Assigning  ```/\/\/\?|(\/\?)+\/|\/\?\/|\/\?/g``` to  ```paramInjectTrailingSlashMatcher``` which checks for multiple slashes fixes the issue.

**Comment by ryanflorence** [comment]
we don't have named routes in 1.0, so you'll just make your own path in transitionTo now.
