### ISSUE TITLE
Routing policies

### ISSUE THREAD

**Issue by tanertopal** [rackt/react-router#1119]
I added some functionality to handle transition hooks in the router definition to be able to do this.
My question: Is that a good approach or is there a more convenient for a similar effect way which I did not see?
Commit: https://github.com/tanertopal/react-router/commit/ab5c76f55f5eeb332300a9850b5e041cfb77950d

(This only works in the example but in  a more complicated setup it will fail)

```javascript
var isLoggedIn = function(transition, params, query, next) { 
  // do something
  next(); 
};

var isPremiumUser = function(transition, params, query, next) { 
  // do something
  next();
};

var routes = (
  <Route handler={App}>
    <DefaultRoute handler={Home}/>
    <Route name="dashboard" policies={[isLoggedIn]} handler={Dashboard}/>
    <Route name="downloads" policies={[isLoggedIn, isPremiumUser]} handler={Downloads}/>
  </Route>
);
```

**Comment by srph** [comment]
I like this idea
