### ISSUE TITLE
Incorrectly escaped character in hash causes uncaught URIError

### ISSUE THREAD

**Issue by kpalmvik** [rackt/react-router#1121]
An incorrect path, containing incorrectly escaped characters, will cause an unhandled error in [HashLocation.js:101](https://github.com/rackt/react-router/blob/06ed4f1019e23bdd8892fed95b7859eec5c4a810/modules/locations/HashLocation.js#L101)

Steps to reproduce:
1) Run examples server in react-router repo: *npm run examples* 
2) Navigate to an incorrect path, for example <http://localhost:8080/query-params/index.html#/user/123?showAge=true%whatever>
=> The %whatever part in the query string causes an [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError). No component will be rendered as a result of this error.

Is this a bug, or am I supposed to catch this myself with *try { ReactRouter.run(...) }*?

**Comment by ryanflorence** [comment]
fixed on master, doubt there is a test though, should probably have a test in the `history` package
