### ISSUE TITLE
Scrolling to a anchor link on refresh not working

### ISSUE THREAD

**Issue by ferrannp** [rackt/react-router#1123]
Hello!

So I am using a similar system like react docs where the headers are anchor links: https://facebook.github.io/react/docs/getting-started.html#starter-kit

If you click on the link, it goes to the correct section of the page. In my [app](http://audioprofiles.herokuapp.com/guide/priority_calls#google-groups) (that uses react-router with HistoryLocation), that doesn't really work... Clicking on the header/link focuses correctly but refreshing doesn't (going directly to the link in another tab does). It's weird because it makes a glitch, first seems that refreshes to the correct position and then scroll to where you were before hitting refresh.

I wonder if this is because the scrolling behavior of react-router... Or do I have to manually scroll (which seems bad idea) ? Also I wonder if this is a very silly question :)

**Comment by dahei** [comment]
+1

I can confirm this. It's not working at all for me.

When using a <Link> to link to a named anchor <a name="contact"></a>

    <Link to="/#contact" >Contact</Link>

the app is not jumping to the anchor (like the usual browser behavior). When using a standard 

    <a href="/#contact">Contact</a>

It works initially, but when coming from another route within the app (/foo -> /#contact) a full round-trip to the server is happening.

What is the best practice to use PushState and have normal anchor-Behavior? Is there something like the params or query prop for anchor-hashbangs?

**Comment by dbburgess** [comment]
+1 on this. It seems that using anchors in `<Link>`s would be useful.

**Comment by mouhsinelonly** [comment]
+1

**Comment by taion** [comment]
This should probably be handled on `scroll-behavior`. Feel free to open an issue there if this is still a problem for you. Ideally this ought to work for all `PUSH` transitions, not just clicking on `<Link>`s.
