### ISSUE TITLE
404 for invalid parameters

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1124]
Currently, this is what I'm doing to show a 404 page in the case that a parameter value is invalid:

```javascript
Router.run(routes, Router.HistoryLocation, function (Handler, state) {
    state.routes.forEach(function(Route) {
        var RouteHandler = Route.handler;
        if (RouteHandler.validateParams && !RouteHandler.validateParams(state.params)) {
            Handler = NotFound;
            return false; // break
        }
    });
    React.render(<Handler/>, document.body);
});
```

This is not a good solution because it by-passes the `<NotFoundRoute />` definitions. React Router should have some kind of hook enabling a Route to be considered "Not Found" if its parameter is an invalid value.

Does this exist? I can't find anything to this effect in the documentation.

**Comment by ryanflorence** [comment]
`NotFound` is a misnomer, it should really be `NoMatch`. There's a difference between "this path is not a valid path" and "the resource at this valid path does not exist".

Your matched route component can do the validation and then render whatever it needs to if the params or resource don't exist.
