### ISSUE TITLE
Expose routing state outside of the component context

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1125]
Today the routing state can be accessed via the (undocumented) component context API:

```javascript
this.context.router.getCurrentParams();
```

It would be nice to be able to access this outside of components and without the context magic:

```javascript
Router.state.getCurrentParams();
```

What's the rational for not exposing this?

**Comment by aldendaniels** [comment]
Not having this is particularly awkward for the flux pattern, where accessing URL parameters in a store is a common requirement.

**Comment by saulshanabrook** [comment]
If we want to change the route while not in a React class, what is the current recommended method?


Like @aldendaniels  I want to change the path when an event is broadcasted in a store in Reflux.

**Comment by saulshanabrook** [comment]
I just figured out a workaround for changing a route outside of a react class, that applies to Reflux.

1. Create action `giveRouter`
2. Call that action in a react class [that has the router](https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md#api-router-context), passing in `this.context.router`.
3. On the store that you want to change routes, create a `onGiveRouter(router)` function, and assign `this.router = router`.
4. Then on another event in that store, you can use the `this.router.transitionTo('home')`

**Comment by aldendaniels** [comment]
Ah, looks like this is possible:

**My router.js file**
```javascript
// Create and export router.
// Most happen before requiring route components,
// Since these may want to access the router.
var Router = require('react-router');
var router = Router.create({
    routes: [],
    location: Router.Location
});
module.exports = router;

// Add routes.
router.addRoutes(require('./routes'));

// Start.
var React = require('react');
router.run(function (Handler, state) {
   React.render(<Handler/>, document.body);
});
```

The return value of `Router.create` (and `Router.run` for that matter) exposes the full Router API:

```
childContextTypes
scrollHistory
name
getScrollPosition
clearAllRoutes
stop
refresh
length
getLocation
replaceRoutes
getRouteAtDepth
dispatch
caller
displayName
recordScrollPosition
cancelPendingTransition
propTypes
match
getCurrentParams
transitionTo
setRouteComponentAtDepth
getCurrentPathname
replaceWith
namedRoutes
routes
getCurrentRoutes
makePath
getScrollBehavior
getCurrentPath
addRoutes
getCurrentQuery
isRunning
isActive
handleError
arguments
prototype
type
goBack
run
makeHref
handleAbort
handleLocationChange
```
Currently this top-level API is mostly undocumented.

**Comment by ryanflorence** [comment]
yep, use at your own risk :P

1.0 has some official top-level methods that will be documented.

**Comment by Pomax** [comment]
Just found this issue from http://stackoverflow.com/questions/34077734/is-it-possible-to-access-the-current-route-component-with-react-router, it would be great if there was a link here to those docs so people can follow the trail to the solution.
