### ISSUE TITLE
Add default params?

### ISSUE THREAD

**Issue by gniquil** [rackt/react-router#1126]
It seems currently there's no way to have default query params. The use case is the following:

```javascript
this.context.router.transitionTo('users', null, {page: 1})
```
Currently it generates a path similar to `/users?page=1`. However, it would be nice to specify `page=1` being the default and so the generated path woudl just be  `/users`. 

Since you already have the nice `<Router/>` syntax for configuration, I think we can extend it like below:

```javascript
<Router name="users" defaultParams={{page: 1}} />
```
Frank

**Comment by whather** [comment]
+1 for default route query params

**Comment by BowlingX** [comment]
+1 here too, should also work with redirects..

UseCase:

```
<Redirect 
  from='old/route/that/contains/just/one/:parameter'
  params={{newRouteParameter:1, secondNewRouteParameter:2}}
  to='newRouteThatHasMoreThenOneParameter'} />
```

right now this does not work, I expected the parameters to be combined (like Object.assign()).

**Comment by tsingson** [comment]
+1

**Comment by ryanflorence** [comment]
For default params on a route just have a `params` default prop on your route component

If we used `Object.assign()` for redirects, how would you opt-out of the merge if you wanted to replace?

In 1.0 you have `onEnter` at the route level, so you could do whatever logic you want to perform a redirect :)

**Comment by frg** [comment]
@ryanflorence  "For default params on a route just have a params default prop on your route component"

How would I go about doing this? Thanks in advance.

**Comment by abimelex** [comment]
In router component:

```
//...
<Route path="/users/(:page)" component={Users}> // parenthesis to make page param optional
//...
```
And in your users component:

```
class Users extends React.Component {
    constructor(props) {
        super(props);
        props.params.page = 1;
//...
```

**Comment by bakatrouble** [comment]
There are now [optional URL portions](https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteMatching.md#path-syntax).
(For those who comes here from Google like me)
