### ISSUE TITLE
Nested routes with custom animation or without any

### ISSUE THREAD

**Issue by cmnstmntmn** [rackt/react-router#1129]
i was playing with **animations** from *examples* directory and it workd great without nesting; 
but when nested routes are added, they're inheriting the parent **RouteHandler** behaviour

i've made an animated gif with the normal behaviour; 
it's pretty much like any other tabs

![neste-routes](https://cloud.githubusercontent.com/assets/2312755/7337848/298944e0-ec41-11e4-8700-113aad39b35a.gif)

**Comment by ThibWeb** [comment]
Hey there,

I had the same issue and tried to solve it by removing the children's segment of the path from the parent component's `RouteHandler` `key`. Here's some code: https://github.com/rackt/react-router/pull/1226

**Comment by ryanflorence** [comment]
in 1.0 there are no longer route handlers, just `this.props.children`, so animations should be identical to anything else in react.

**Comment by cmnstmntmn** [comment]
this is great, ryan :+1:
