### ISSUE TITLE
fetchData return two ajax calls

### ISSUE THREAD

**Issue by kennethaa** [rackt/react-router#1130]
Hi. Love your package and the ability to fetch data both on server and client with fetchData inside statics. 
https://github.com/rackt/react-router/blob/master/examples/async-data/app.js

When I want to get one feed inside fetchData, the solution is simple: 

```javascript
statics: {
    fetchData: function(params) {
        return WebAPIUtils.get('feed/' + params.id);
    }
},
```

But when I want to get two or more feeds I can't find a solution. Does anyone have a solution for that?

**Comment by taurose** [comment]
The function just needs to return a promise, so what you're actually asking is how to combine promises.

There are lots of ways. If you want them to execute in parallel, you can use `Promise.all`:

```js
statics: {
    fetchData: function(params) {
        return Promise.all([WebAPIUtils.get('feed/1'), WebAPIUtils.get('feed/1')]);
    }
},
```

**Comment by kennethaa** [comment]
Thanks.
