### ISSUE TITLE
Best way to do `DefaultRedirectRoute`

### ISSUE THREAD

**Issue by camsong** [rackt/react-router#1132]
My problem is exactly like this https://github.com/rackt/react-router/issues/622, `DefaultRedirectRoute` would be the idle way to handle this. Nearly 1 year has passed, cannot find `DefaultRedirectRoute` in the code base, what's the idle way to handle this in 2015?

**Comment by ryanflorence** [comment]
the 1.0 matching algorithm removes the need for all of this, if you'd like to post a sample route config for what you're trying to do I can show you what it looks like in 1.0.

Also: 

https://github.com/rackt/react-router/issues/1333#issuecomment-113165238

**Comment by ascrazy** [comment]
In our project we use `DefaultRoute` in the following style:

```jsx
<Route path="users">
  <DefaultRoute name="AllUsersPage" component={AllUsersPage}/>
  <Route path="top" name="TopUsersPage" component={TopUsersPage}/>
  <Route path=":userId">
    <DefaultRoute name="UserProfilePage" component={UserProfilePage}/>
    <Route path="photos" name="UserPostsPage" component={UserPostsPage}/>
    <Route path="comments" name="UserCommentsPage" component={UserCommentsPage}/>
  <Route/>
<Route/>
```

And we handle all links and transitions by names.

Should we stop using nested routes in such manner with router-1.0.0?
