### ISSUE TITLE
Is context.router accessible server-side?

### ISSUE THREAD

**Issue by voronianski** [rackt/react-router#1133]
I'm migrating from `0.12` to `0.13` and getting rid of State and Navigation mixins. 

However on server-side I've got exceptions like `TypeError: Cannot call method 'getCurrentParams' of undefined`. I'm calling it like `this.context.router.getCurrentParams()` inside `getInitialState`.

**Comment by gaearon** [comment]
You need to put `contextTypes` on your component.
https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md

**Comment by voronianski** [comment]
@gaearon thanks, though link is 404 :/ 

For some reason there's no warnings in console for use of `Navigation` and `State` mixins with react-router's `0.13.3` version, that's why I will wait with switching to context for a while.

**Comment by ryanflorence** [comment]
we brought the mixins back, they are much better than asking folks to mess around w/ context.
