### ISSUE TITLE
When you mutate router.getCurrentQuery() it changes the internal state

### ISSUE THREAD

**Issue by 0xR** [rackt/react-router#1135]
I am working on a pagination component which works even without javascript.
I have code like this to create a href for a link on the page:
``` javascript
hrefForPage(page) {
    const router = this.props.router;
    const path = router.getCurrentPathname();
    const params = router.getCurrentParams();
    const query = router.getCurrentQuery();
    query.page = page;
    return router.makeHref(path, params, query);
  }
```

In my onclick handler I have code like this:
``` javascript
  handleClick(e, page) {
    e.preventDefault();
    const router = this.props.router;
    const path = router.getCurrentPathname();
    const params = router.getCurrentParams();
    const query = router.getCurrentQuery();
    if (query.page !== page) {
      query.page = page;
      router.transitionTo(path, params, query);
      searchForQuery(query);
    }
  }
```

But because I set `page` in the `hrefForPage` method I have changed the interal state of react-router. In my case this causes me not to be able to go to the last page since `getCurrentQuery` tells we are already on the last page.

**Comment by ryanflorence** [comment]
1.0 (beta is on master) no longer has this method, you get new objects as props to your route components.
