### ISSUE TITLE
When performing a `window.open()`, parent page is resetting its route

### ISSUE THREAD

**Issue by psbanka** [rackt/react-router#1138]
I have a project using `react-router` which at one point performs a `window.open()` in order to show additional information to a user in a new tab. This is all fine, but when the user returns to their original tab, the route has changed to the base.

For example, the user might be on the following route:
```
https://localhost/services/#/manage-services/TTESI22UMLULF542ZBKGQ3W7BMVZDPI
```
And after opening the new tab and closing it, the browser will have changed the original tab to:

```
https://localhost/services/#/manage-services/
```
This is happening on both Firefox 37.02 and Chrome 42.0.2311.90

**Comment by ryanflorence** [comment]
I can't reproduce this, if you can track down where the router is doing something wrong, please let us know. Thanks.

**Comment by omrihq** [comment]
Seeing similar behavior from `MemoryRouter`, commenting to see if this has been re-opened elsewhere or addressed
