### ISSUE TITLE
Update documentation for server side rendering

### ISSUE THREAD

**Issue by StevenIseki** [rackt/react-router#1139]
It seems to me, all the documentation for React Router refer to client side applications. I can only find the following 2 examples using server side rendering

https://github.com/rackt/react-router/blob/master/docs/guides/server-rendering.md
http://stackoverflow.com/questions/28553904/client-routing-using-react-router-and-server-side-routing

It might be good to include a really simple example of server side rendering for an app using React Router. I am confused on how to get started with an Express/React Router app due to the lack of examples, even though I have created a few server side Flux websites using just Express for routing.

**Comment by ScreenDriver** [comment]
+1

**Comment by StevenIseki** [comment]
I have been working on some react router isomorphic routing examples using alt and iso, over here.
https://github.com/goatslacker/isomorphic-react-examples

I might be able to help out with some more isomorphic react router examples in some other flux libraries as well, mcfly, fluxxor and flummox if I get some time, which will help with documentation

**Comment by ryanflorence** [comment]
since this issue will probably apply for the lifetime of this project, I'm going to close, but yes, we can always use more and better documentation :)
