### ISSUE TITLE
Is it possible to access the component instance in the stubRouterContext?

### ISSUE THREAD

**Issue by pherris** [rackt/react-router#1140]
While testing with Jest, I have a component I am wrapping in stubRouterContext per this guide:
https://github.com/rackt/react-router/blob/master/docs/guides/testing.md

I would like to call setState() and manually invoke the _onChange method on my component instance to trigger the re-rendering of the component and its behavior. However, with my component wrapped in the class returned from stubRouterContext I'm unclear how to access these methods.

```
    "react": "~0.13.2",
    "react-router": "^0.13.2",
```

**Comment by taurose** [comment]
Since `stubRouterContext()` allows you to pass props to your Component, you should be able to make use of the recent feature to pass a ref function:

```js
var Test = stubRouterContext(App, {
    ref: function(comp){
        comp.hello();
    }
});
```

**Comment by bradrobertson** [comment]
Can you explain this in the context of accessing the original component's refs? I don't really understand what that `comp` object is. I'm trying to make assertions about the original components refs, but I can't seem to access them. Something like:

```javascript
var App = React.createClass({
  render: function () {
    return (
      <h1 ref="header">Header!</h1>
    );
  }
});

var Test = stubRouterContext(App, {
    ref: function(comp){
        return comp.refs
    }
});
subject  = TestUtils.renderIntoDocument(<Test />);
expect(subject.refs.header).to.exist
```

I always get an assertion failure saying `subject.refs.header` 
> AssertionError: expected undefined to exist

The `comp` object appears to have access to the App refs, but I can't seem to proxy them over to my Test object.

**Comment by ryanflorence** [comment]
I've done this with refs, must be something with jest. Since this is all just react contexts + jest but not anything unique to react router, I'm closing the issue.

**Comment by bradrobertson** [comment]
Can you provide *any* help though for those of us *not* using Jest? I love ReactRouter, it's a really great library, but it's a pretty hard sell to use it if we don't have the ability to test it. Right now, by default on a project, I can't test components because ReactRouter throws errors. In my mind this **is** a ReactRouter issue because I would have working tests if I weren't using it.

I'm using Karma/Mocha/Chai btw.

**Comment by srph** [comment]
Can you check if `refs` exist? This shouldn't be an issue since the error seems to be about `.header` being undefined.
