### ISSUE TITLE
Add website link (rackt.github.io/react-router) to project description and/or README.md

### ISSUE THREAD

**Issue by newoga** [rackt/react-router#1141]
Website looks nice @ryanflorence!

Thought it might be good idea to link to the website from the readme/project description so people can find it easily. That should help until it gets indexed by search engines.

**Comment by yangit** [comment]
+1

**Comment by ryanflorence** [comment]
done, thanks :)

**Comment by gaearon** [comment]
Why not add it here?

![screen shot 2015-06-18 at 17 46 13](https://cloud.githubusercontent.com/assets/810438/8233974/f2f22e40-15e1-11e5-932c-4eb0c4e62c0a.png)

**Comment by gaearon** [comment]
I mean the “Website” field which is currently empty.
