### ISSUE TITLE
Link to a nested route

### ISSUE THREAD

**Issue by kevinsimper** [rackt/react-router#1142]
Right now you can do

```
<Link to="user"/>
```

But how should you do it if you have nested routes, because this does not work
```
var routes = (
  <Route handler={App}>
    <Route name='user' handler={User}>
      <Route name='create' handler={UserCreate}/>
    </Route>
  </Route>
)
<Link to="user/create"/>
```

`Uncaught Error: Invariant Violation: Cannot find a route named "user/create"`

http://rackt.github.io/react-router/#Link

**Comment by taurose** [comment]
You can...

* use name directly `<Link to="create" />`
* use full path `<Link to="/user/create" />`

Note that names are not nested, so they must be unique.

**Comment by kevinsimper** [comment]
Okay, did not read that names were unique, then it makes more sense!
