### ISSUE TITLE
AcitveHandler RouteHandler duplication

### ISSUE THREAD

**Issue by english** [rackt/react-router#1145]
I've just noticed [ActiveHandler.js](https://github.com/rackt/react-router/blob/master/modules/components/ActiveHandler.js) and [RouteHandler.js](https://github.com/rackt/react-router/blob/master/modules/components/RouteHandler.js) are duplicates of each other, each exporting a `RouteHandler` component. Looks like `ActiveHandler.js` was introduced in 81a8edfe.

Is this a mistake?

**Comment by ryanflorence** [comment]
yeah, that was a mistake
