### ISSUE TITLE
Access all routes defined in router

### ISSUE THREAD

**Issue by bkniffler** [rackt/react-router#1149]
Hello, 
Is there any possibility to access all the routes within the router, like
```
console.log(router.routes);
=> [{name: "root1"}, {name: "root2", childRoutes: [...]}]
```

**Comment by johanneslumpe** [comment]
You can just traverse the route tree. Check out https://github.com/rackt/react-router/issues/885#issuecomment-76911482 - that might help you.

**Comment by ryanflorence** [comment]
You defined your routes, you can traverse them :)

```js
var routes = (
  <Route>
    <Route/>
  </Route>
);

traverseRoutes(routes);
```
