### ISSUE TITLE
How to define a route that does nothing ?

### ISSUE THREAD

**Issue by misterfresh** [rackt/react-router#1150]
Usually when we create a link that does nothing, we give it an href of "#". But with react-router this redirects to the main page (path = '/'). How can I define a route that does nothing, that I will then put in the href of such links? Thanks.

**Comment by taurose** [comment]
Can you elaborate on what you're trying to achieve?

**Comment by ryanflorence** [comment]
I'm not sure why you'd want an element that does nothing, seems like a `<span/>` should be enough.  also `<a href="#"/>` is an accessibility anti-pattern.
