### ISSUE TITLE
Link not setting active class

### ISSUE THREAD

**Issue by nhjk** [rackt/react-router#1151]
Routes
```jsx
<Route handler={App}>
  <Route name='facility' path='facilities/:id' handler={Facility} />
</Route>
```

Link `<Link to="facility" params={facility}>{facility.get('name')}</Link>`

Rendered as `<a class="" href="#/facilities/1" data-reactid=".0.1.0.0.0.0">Facility Name</a>`

url: `http://localhost:8080/#/facilities/1`

**Comment by ryanflorence** [comment]
we're not going to call `get` on an objects you pass as params, we need a plain object.

**Comment by KurganskySergey** [comment]
the thing is if Link has params in props then active className won't be added if you click on that link
