### ISSUE TITLE
Is possible the same path for different nested Routers?

### ISSUE THREAD

**Issue by IDVsbruck** [rackt/react-router#1152]
For example, I want to create the form with confirmation:

```
var routes = (
	Route({name: "app", path: "/", handler: App},
		DefaultRoute({name: "index", handler: Default}),
		Route({name: "somepage", handler: SPage},
			Route({name: "somepage.form", path: "/somepage", handler: SPageForm}),
			Route({name: "somepage.confirm", path: "/somepage", handler: SPageConfirm})
		),
		NotFoundRoute({handler: NotFound})
	)
);
```

When I go to "somepage" I call "somepage.form", after successful result of form submitting I call "somepage.confirm". But in any selection I get only one page - second. I understand that navigation occurs by path (not by name), but I want to get confirmation page without address changing. Is it possible? Or in any case I need to change "somepage's" render() with dynamic parameters?

**Comment by ryanflorence** [comment]
its possible in 1.0, using `getChildRoutes` you can branch on whatever session/app data you've got to provide different routes with the same path, check out the pinterest example.
