### ISSUE TITLE
Transition is changed to replace, if a replace is pending

### ISSUE THREAD

**Issue by ropez** [rackt/react-router#1154]
Assume we have a route handler with an asynchronous hook, something like this:

```coffeescript
Foo = React.createClass
  mixins: [Router.Navigation]

  statics:
    willTransitionTo: (t, p, query, callback) ->
      doAjax("getFoo", query, callback)

  onUpdateQuery: ->
    @replaceWith('foo', params, { arg: 1 })

  onClick: ->
    @transitionTo('bar')
```

Now, imagine we are in the "foo" view, and our history contains "home" and "foo". Then we do something that triggers the `onUpdateQuery` method. A "replace" transition is now pending.

A little later, while still waiting for the transition to complete, `onClick` causes us to abort the pending transition by making a transition to the "bar" route instead.

What happens then is that the second transition, the one using `@transitionTo`, is changed to a `replace`, because we have a pending transition. This would make sense if the first transition was also a `@transitionTo`. But what actually happens is that we lose a step in the history. The user would expect `@goBack` to go from "bar" to "foo", but instead we go straight back to "home"!

(edit: updated the example code)

**Comment by taurose** [comment]
Never thought of that, good catch :)

So I guess we should only force replaceWith for transitionTo if the pending transition (or any non-finalized transition before that) was a transitionTo and added a new history entry already.

**Comment by ryanflorence** [comment]
failing test case would be amazing here.

**Comment by ryanflorence** [comment]
responsibility has probably moved to `history` package

**Comment by taion** [comment]
https://github.com/rackt/history/pull/43
