### ISSUE TITLE
mutating the [[Prototype]] of an object

### ISSUE THREAD

**Issue by lpillonel** [rackt/react-router#1155]
Hello,

When I run my app (or even latest react-router examples) in Firefox (36.0.4 and 37.0.2 at least), I get a warning : 

    mutating the [[Prototype]] of an object will cause your code to run very slowly; 
    instead create the object with the correct initial [[Prototype]] value using Object.create

Maybe it's nothing, but can we do something about it ?

Thanks,

Luca

**Comment by nivekmai** [comment]
Seeing this warning on the [documentation page](http://react-bootstrap.github.io/components.html) as well.

**Comment by iyn** [comment]
I'm also seeing this error. However, I'm not sure if this is related only to `react-router`. Related discussion at `react-bootstrap`: https://github.com/react-bootstrap/react-bootstrap/issues/550

**Comment by ryanflorence** [comment]
this is definitely not us.

**Comment by AlexKVal** [comment]
You can safely close the issue.

It seems there is no solution with FF at this time.
https://github.com/babel/babel/issues/1466#issuecomment-99752513
