### ISSUE TITLE
Documentaion: v0.13.3 displays old version (v0.12) with no context information

### ISSUE THREAD

**Issue by kiddhustle** [rackt/react-router#1156]
The latest version of the documentation seems to be an older version of the docs and has no reference to accessing the router via the context property (unless the way the router works has changed back to the pre-Context way).

* current docs - http://rackt.github.io/react-router
* previous docs (what works) - https://github.com/rackt/react-router/blob/v0.13.2/docs/api/RouterContext.md

**Comment by davidtheclark** [comment]
Yes. This documentation inconsistency combined with the deprecating-then-non-deprecating of the mixins is making this library pretty confusing to work with right now.

**Comment by mjackson** [comment]
@kiddhustle thank you for bringing this to our attention. we'll definitely update the docs. `this.context.router` is no longer part of our user-facing API. it's still public API, but people shouldn't have to know about `context` in order to use the router.

@davidtheclark apologies for the confusion. yes, things are a bit messy right now. we're working hard on a new release that should clear up a lot of confusion very soon! see #1158

**Comment by ryanflorence** [comment]
updating now

**Comment by ryanflorence** [comment]
but the current docs are correct, `in v0.13.3` you don't access context directly anymore

**Comment by kiddhustle** [comment]
Oh OK now that's strange I recently upgraded from v0.12 to v0.13.3 and started seeing errors related to the context object. That's when I decided to switch to using the `context` directly.After that the errors went away.

I'll have to try reverting the code back to when I get time to investigate the problem again.

Thanks

**Comment by ryanflorence** [comment]
What are the errors?

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#0132---0133

**Comment by SevereOverfl0w** [comment]
How should we continue if we wish to use ES6 classes?

**Comment by kiddhustle** [comment]
OK so I've just reverted the mixin calls in my project to follow the latest documentation and everything seems to work OK now.

I think maybe some of the dependencies weren't all up to date when I last tried so that could have caused the errors I was seeing.

Sorry for the false alarm!
