### ISSUE TITLE
Passing custom properties within a route

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [rackt/react-router#1159]
I know this was previously discussed, but wondered if a workaround is possible when passing custom properties to a route. so:

```<Route handler={App} path='/'>
		<DefaultRoute name="home" handler={Home} customProp='thisIsCustom' />
	</Route>```

This is really useful when using react server side. It would allow to set custom properties in the Routes class and then utalise them when the route is being handled.

Thanks

**Comment by ivan-kleshnin** [comment]
:+1:

This was discussed at least in:
https://github.com/rackt/react-router/issues/615
https://github.com/rackt/react-router/issues/927
https://github.com/rackt/react-router/issues/930
https://github.com/rackt/react-router/pull/1002

Standard answer was **You don't need this, just attach required things as static props**.
However it turned out to be short-sighted. Wich HOC (higher-order components) static no longer works.
Noone HOC builder provides access to original component (which is, surely, kinda stupid omission of HOC builders, but that's how it is).

This issue undermines **React-Router** fundamentally, cause it's currently incompatible with Webpack async loading.

The syntax for lazy components
```js
import {RobotIndex, RobotAdd, RobotDetail, RobotEdit} from "react-proxy!frontend/components/model/robot";
import {MonsterIndex, MonsterAdd, MonsterDetail, MonsterEdit} from "react-proxy!frontend/components/model/monster";
```

doesn't work. Because `react-proxy` wraps component in HOC and cloaks `static` props.

**Comment by komackaj** [comment]
Possible duplicate #1017

**Comment by kryptt** [comment]
I believe this is relatively important that react router offer this flexibility as well.

**Comment by davidsielert** [comment]
+1 This is supercritical at least to be able to set custom props and have them passed into the data received on the router.run end to deal with it from there

**Comment by ivan-kleshnin** [comment]
> +1 This is supercritical at least to be able to set custom props and have them passed into the data received on the router.run end to deal with it from there

Oh, man. Considering they remove `router.run` in the next release I'm afraid this will never happen.
React gradually turns into Polymer where AJAX request is represented by Web Component...
Total mess :disappointed:

**Comment by davidsielert** [comment]
Though in another issue it's stated that you'll be able to pass prop data in route Def .. (the one about metadata)  ;)

**Comment by ivan-kleshnin** [comment]
> Though in another issue it's stated that you'll be able to pass prop data in route Def .. (the one about metadata)  ;)

Pass, and access them only from components, cause `run` is removed...
As there will be no centralized place to handle metatasks a lot of cases where metadata could be used become more or less blocked.

**Comment by ryanflorence** [comment]
you can pass any prop you want to routes and access them wherever you have access.

> Oh, man. Considering they remove router.run in the next release I'm afraid this will never happen.
React ecosystem gradually reproduces Polymer where AJAX request is represented by Web Component... Total mess

We have a different `Router.run` now that lets you match before rendering (but it doesn't set up the history listeners anymore, rendering a router does that).

Don't be so quick to dismiss declarative data handling though, we're working on AsyncProps and its going to be pretty awesome.

**Comment by alexwakeman** [comment]
Passing custom props won't work with statically typed TypeScript.

**Comment by joelhoward0** [comment]
@alexwakeman +1. This stopped me pretty much immediately as I tried to move on from 'Hello World', and after reading maybe 10 issues, examples and d.ts files, I am at a dead end. I can't find a way to set up my Route components that both lets me control their props (without contaminating them with knowledge of Route) AND preserves my type information. 

I'm really reluctant to make either of those tradeoffs, even for something as powerful as RR.

**Comment by theboyWhoCriedWoolf** [comment]
Hello @joelhoward0 its hard to know the best approach without seeing your code. Maybe have a look at [React Router v4](https://github.com/ReactTraining/react-router/tree/v4) it might provide a slightly different approach and help out.

**Comment by ryanflorence** [comment]
Yep, in v4 it looks like this:

```js
<Match
  pattern="/foo"
  render={(props) => (
    <YourRouteComponent {...props} custom="prop"/>
  }
/>
```

Should work w/ your type definitions just fine, no more `React.cloneElement`

**Comment by sawatsky** [comment]
I'm not allowed to update react-router, so I'm stuck on v1.0. Any idea how to tell TypeScript to accept my custom props?

**Comment by alexwakeman** [comment]
@sawatsky I was forced to write my own router. It offers a workaround for this. You can find it [here](https://github.com/alexwakeman/qadb/blob/master/public/app/utils/router.tsx). It is not a fully fledged project, it just does what I need it to. Also look at app.tsx and around for usage.
