### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by jedverity** [rackt/react-router#1160]
See the "API Docs" link at the bottom of this page: https://github.com/rackt/react-router/blob/master/docs/guides/overview.md (which itself is linked as the "overview guide" in the README).

It tries to go to this 404: https://github.com/rackt/react-router/blob/master/docs/api

**Comment by mjackson** [comment]
This was [fixed](https://github.com/rackt/react-router/commit/8bd1498c377bcfcaedfef82a68aa6b27289f36b2).
