### ISSUE TITLE
Examples/transitions not upgraded

### ISSUE THREAD

**Issue by ocorpening** [rackt/react-router#1161]
The upgrade guide for react-router advises that

this.context.router.transitionTo

is now

this.context.transitionTo

Yet the example functions properly, even though it is wrong according to the upgrade guide.

**Comment by ocorpening** [comment]
I asked this in stackoverflow, seems like a real bug, there is no way to know which is the right syntax without the examples matching the upgrade guide:

http://stackoverflow.com/questions/30084127/react-router-this-is-undefined

**Comment by ryanflorence** [comment]
Oh, that's right, I haven't updated the upgrade guide since we brought the mixins back.

**Comment by ryanflorence** [comment]
correct syntax is us the `Navigation` mixin and then use `this.transitionTo`

**Comment by ocorpening** [comment]
So the examples are indeed misleading?

**Comment by ocorpening** [comment]
Also this still leaves me with "this" undefined in ReactRouter? I know using "use strict" if one forgets the "new" this will default to undefined, but I don't see any "use strict" in react-router?

**Comment by ocorpening** [comment]
So I never noticed that both this.context as well as this have transitionTo on them! So using:

this.transitionTo('createAppointmentsEvent');

I am still lose 'this' during the location.push: it is present then push calls notifyChange and inside notify change 'this' is undefined. 

Also even inside ReactRouter it calls this.context.transitionTo, so there is some inconsistency still, helps make it truly difficult for use new people.

**Comment by ocorpening** [comment]
I tried correcting transitions in app.js line 51 in handleSubmit, and transitionTo is not on this, it is on this.context.router. I added the Navigation Mixin, that is one other extra line. That reproduces this 'defect'!

**Comment by ryanflorence** [comment]
transitions are working on master with the new 1.0 api (I believe they eventually were updated for 0.13.x as well?)
