### ISSUE TITLE
Add *Mixin alias for mixins

### ISSUE THREAD

**Issue by cesarandreu** [rackt/react-router#1162]
It's pretty common for mixins to include `Mixin` at the end. For example, [PureRenderMixin](http://facebook.github.io/react/docs/pure-render-mixin.html).

Would you consider adding `NavigationMixin` and `StateMixin` as aliases for `Navigation` and `State`?

This is probably the ultimate nitpick, but I want `*Mixin` so I can do:

```jsx
var React = require('react')
var {StateMixin} = require('react-router')

var Foo = React.createClass({
  mixins: [
    StateMixin
  ],

  render () {
  // ...
  }
})

module.exports = Foo
```

All the other mixins I'm using export `*Mixin`.

**Comment by mjackson** [comment]
I'd like to avoid having two separate names that reference the same thing. If the name really bothers you, you can always:

```js
var { State: StateMixin } = require('react-router');
// Now you have StateMixin
```
