### ISSUE TITLE
More complex tree

### ISSUE THREAD

**Issue by gilesbradshaw** [rackt/react-router#1164]
Forgive me if I am not explaining this very well but have you any thoughts on how to implement a more complex tree where one route results in multiple branches?

So you could have a structure like this...

     A - C
      |
      B - C

    -------------------------------------
    | A                ---------------  | 
    |                  |       C     |  |
    |                  ---------------  |
    |                                   |
    |  -----------------------------    |
    |  |  B                        |    |
    |  |         ----------------- |    |
    |  |         |               | |    |
    |  |         |        C      | |    |
    |  |         ----------------- |    |
    |  -----------------------------    |
    -------------------------------------

where the path A/B/C would display two different components for the C part - one could be a menu on a different part of the page for example 

maybe this would be the code:

    Main=()=>
	 <div>
            <RouteHandler type='menu'/>
	    <RouteHandler/>
	 </div>

    CMenu=()=>
         <div>C menu is here</div>

    DMenu=()=>
         <div>DMenu is here</div>

    BMain= ()=>
         <div>
            <RouteHandler/>
	 </div>

    CMain=()=> <div>Cmain!</div>
    DMain=()=> <div>Dmain!</div>

    <Route name="A" path = "A" handler="Main">
        <Route type="menu" path="B">
            <Route path="C" handler="CMenu"/> 
            <Route path="D" handler="DMenu"/>
        </Route>
        <Route path="B" handler="BMain">
            <Route name="C" path="C" handler="CMain"/> 
            <Route name="D" path="D" handler="DMain"/>
        </Route>
    </Route>

**Comment by taurose** [comment]
There's currently no built-in support for this yet, but named handlers are planned for 1.0 (see #1158)

As for solving this right now, I don't think there's a best practice everyone would agree upon. Anyway, I would probably do it by parsing `state.routes` and passing a prop, i.e.

```js
var routes = ...
var menuHandlers = {
  // routeName: Handler
  B: BMenu,
  C: CMenu,
  D: DMenu
};

Router.run(routes, function(Handler, state){
  // only takes innermost route into account; you can adapt this to your needs
  var innerRoute = state.routes[state.routes.length - 1];
  var menuHandler = menuHandlers[innerRoute.name];

  React.render(<Handler menuHandler={menuHandler} />, document.body);
});

// Root handler
render: function(){
  var Menu = this.props.menuHandler;
  return <div><Menu /><RouteHandler /></div>;
}
```

**Comment by ryanflorence** [comment]
If I'm understanding correctly, 1.0 allows you to have multiple components for a route.

https://rackt.github.io/react-router/tags/v1.0.0-beta2.html#Route

Check out the `components` prop.
