### ISSUE TITLE
Using Link with another Component like Buttons

### ISSUE THREAD

**Issue by owais** [rackt/react-router#1176]
Lets say I have a component called `MyButton`. Is there a quick way to attach link behaviour to it without writing an onClick handler for every button?

**Comment by ksmth** [comment]
Have you tried:
```
<MyButton to="user" />
```
```
class MyButton extends React.Component{
    render() { return <Link to={this.props.to} />; }
}
```

**Comment by owais** [comment]
MyButton is not really my button :) It could be imported from any third party UI lib. I could do things like,

```
class MyButton extends ThirdPartyButton {
    render() { return <Link to={this.props.to}><ThirdPartyButton {...this.props}/></Link>; }
}
```

or simply have `Link` inside the `ThirdPartyButton` or vice-versa but that doesn't seem very clean to me.

**Comment by gaearon** [comment]
I don't like this approach but if you absolutely need this, you can set up a top-level document link handler [like here](https://github.com/acdlite/flummox/blob/cc646710361732bd911b0c749cd0cea72ac056d2/docs/src/client/app.js#L35-L53):

```js
document.onclick = event => {
  const { toElement: target } = event;

  if (!target) return;

  if (target.tagName !== 'A') return;

  const href = target.getAttribute('href');

  if (!href) return;

  const resolvedHref = url.resolve(window.location.href, href);
  const { host, path } = url.parse(resolvedHref);

  if (host === window.location.host) {
    event.preventDefault();
    router.transitionTo(path);
  }
};
```

However, in my opinion, it's kinda strange to have some link components out of your control that nevertheless link to the internal routes in your app.

**Comment by owais** [comment]
Agreed. `onclick`  handlers are better :)

**Comment by ksmth** [comment]
I haven't tried this yet, but I think you could also use one of the mixins to generate the correct link in your render function and pass that along. 



Gruß
Kevin

—————————————

Webseite: http://ksmth.de
E-Mail: k@ksmth.de
Mobil: +49 (0) 173 68 414 76

Kevin Smith — Full Stack Web Developer
Nebenhofstr. 3
23558 Lübeck
Germany

**Comment by ryanflorence** [comment]
we provide `Link` as a router-aware href, and mixins that have everything that link uses to work, so you can build whatever elements you want that interact with the router.
