### ISSUE TITLE
Bug: this.props.path not provided

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1178]
[The documentation](http://rackt.github.io/react-router/#Route Handler) states that the following props are provided to a route handler component:

 - params
 - query
 - path

I'm only seeing `this.props.params` and `this.props.query`. `this.props.path` is simply not populated.

I'm running the latest version (`v0.13.3`).

**Comment by edvinerikson** [comment]
Hi.
Created a PR with the fix https://github.com/rackt/react-router/pull/1181

**Comment by ryanflorence** [comment]
1.0 passes even more stuff, and definitely includes the path, thanks :)

**Comment by pavamanad** [comment]
Is this available for v0.13.3 ?
