### ISSUE TITLE
Problems with HistoryLocation

### ISSUE THREAD

**Issue by davidSevenOrtiz** [rackt/react-router#1184]
i am trying to use routes with history location because i dont want to use # inside my url's,i want to work with normal ones, i have been trying everything and every time i am getting the same error "Cannot GET /loginpro". i don't understand how the locations works, this is my code 

![image](https://cloud.githubusercontent.com/assets/10422670/7604156/fe54d36e-f903-11e4-895c-3e590a2bebd4.png)

Thanks!.

**Comment by edvinerikson** [comment]
Hi.
Are you using the [`<Link />`](http://rackt.github.io/react-router/#Link) component when creating links?

**Comment by taurose** [comment]
Sounds to me like you didn't configure your server correctly. When using HistoryLocation, you need to make sure that when requesting your app's URLs (`/loginpro`) the server returns the html entry file of your app. The easiest way to get there is to simply always return the html file if no other static files (javascript files, images etc) match the requested path.

Here's an express setup I just found that might help: https://gist.github.com/therebelrobot/747953c392d8a6ed5aaf
Note the wildcard route at the end.

**Comment by ryanflorence** [comment]
you need to set up your server to send your app at every non-static-asset url.
