### ISSUE TITLE
transitionTo returns if path is the same

### ISSUE THREAD

**Issue by leishman** [rackt/react-router#1186]
If the path does not change when calling `transitionTo`, the dispatch method does not fire. For me this is not the ideal behavior because it is causing problems for my app. If user clicks a link that is equal to their current path, then shouldn't this event still fire? If not, there is no way to easily capture this behavior and do something with it. Any thoughts? Am I missing something?

In createRouter.js:
```javascript
      dispatch: function (path, action) {
        Router.cancelPendingTransition();

        var prevPath = state.path;
        var isRefreshing = action == null;

        if (prevPath === path && !isRefreshing)
          return; // Nothing to do!
```

**Comment by leishman** [comment]
If I comment out the return in the conditonal, everything works as I would have expected.

**Comment by tenfef** [comment]
I'm also experiencing this. If you have a route called  /customer/:id
And you are on /customer/3 and you run

    router.transitionTo('/customer/4);

The route changes in the URL bar but the route handler doesn't update.

**Comment by ryanflorence** [comment]
I believe #1031 tries to fix this, please follow there, or let me know if I'm wrong and we'll reopen this.

**Comment by leishman** [comment]
@ryanflorence That looks good to me. Thanks!
