### ISSUE TITLE
Can't generate links outside of component that will use them

### ISSUE THREAD

**Issue by NicholasGW** [rackt/react-router#1187]
Hey, not sure if this is expected behaviour and there's something I'm missing, but it seemed strange to me so I decided to post.

I'm working on a app that has pluggable content, so we fetch things at runtime. Because of this, I have to dynamically generate my routes and am also trying to generate a sidebar, based on if the pluggable component is identified as an item that should be in the menu bar. The problem I am having is this: I can easily generate dynamic routes:

    pluginsLoaded.then(function(plugins) {

    pluggableRoutes = [];

    plugins.routes.forEach(function(route) {

     pluggableRoutes.push(<Route name={route.name} path={route.path} handler={route.handler} />

    }

    routes = ( <Route name="app" path="/" handler={App} >
     {pluggableRoutes}
    <Route />);

     Router.run(routes, function(Handler) {
     React.render(>Handler />, document.body);
     });  
  
  
This works great, and as expected. However, say the App component has the sidebar, I can't do this:

    pluggableLinks = [];

    plugins.links.forEach(function(link) {

    pluggableLinks.push = ( <Link to={link.path} /> {link.name} </Link>

    }

and then later pass pluggableLinks to the App component or via the router etc and have this in the components render function:

    render: function() {
    
    <div> {this.props.pluggableLinks} </div>

     }

It keeps erroring and saying that "required context router was not found in Link".

Am I doing fundamentally wrong or is react-router not intended to work this way?

**Comment by taurose** [comment]
As far as I know, this is due to React not using parent-based context yet. So I think this might work with the next major version version of React or so.

Why not create a factory function that creates links on demand?

```js
pluggableLinks.push(function(){return ( <Link to={link.path} /> {link.name} </Link>)});

//render
<div>{this.props.pluggableLinks.map(function(createLink){return createLink(); })}</div>;

**Comment by ryanflorence** [comment]
will work with parent-based context.
