### ISSUE TITLE
Preserve input value states with history

### ISSUE THREAD

**Issue by dmitry** [rackt/react-router#1188]
Normally (it depends on the caching strategy sending in headers from the server and few other circumstances), when you are changing location in your browser by pressing the link, sending a form or any other way, you can retrieve back all the values of your inputs once you click on the "back" button in your browser. 

How do I preserve inputs with react-router when changing browser history from current page to previous?

**Comment by taurose** [comment]
There's currently no way to make use of the browser's history state object (there are plans though).

I'd say the best you can do right now (without some serious effort) is to store the state (indexed by path) yourself in some variable, and persist it using `sessionStorage` if you want to. You can check `state.action === 'pop'` to avoid restoring state after clicking a link.

**Comment by dmitry** [comment]
Just to mension some related things I've found:

https://github.com/rackt/react-router/pull/843
https://github.com/rackt/react-router/issues/1200

**Comment by ryanflorence** [comment]
the new `location.state` feature in 1.0 would allow this

https://rackt.github.io/react-router/tags/v1.0.0-beta2.html#Router

Look at the `transitionTo(pathname, query, state)` method there.

(also, we'll be writing up a guide on the state feature)

**Comment by dmitry** [comment]
@ryanflorence how do I change the state for the back/forward browser events?
