### ISSUE TITLE
Return actual handler component instead of RouteHandler wrapper?

### ISSUE THREAD

**Issue by jakemmarsh** [rackt/react-router#1190]
I'm using this library along with [react-async](https://github.com/andreypopp/react-async) to achieve isomorphism. This works great on the initial render. However, when moving from one page to another and attempting to use their `Preloaded` component, it never fetches the initial state asynchronously.

This is because  the `<RouteHandler />` component is the child to `<Preloaded>`. This means that none of the ACTUAL handler component's functions are available, in this case `getInitialStateAsync`. This results in the RouteHandler failing the [Preloaded checks](https://github.com/andreypopp/react-async/blob/d7ac620d87028e2e521513e9e89d2f451b021fa3/lib/isAsyncComponent.js#L9), and so `getInitialStateAsync` is not called on page change and any initial data will not be present.

In 0.11.6, I fixed this by exporting the `RouterHandlerMixin` and calling `this.getRouteHandler()` instead of `<RouteHandler />`. However, I just upgraded to 0.13.3 and can't figure out a similar solution.

Any ideas?

**Comment by jakemmarsh** [comment]
Closing, as I was using 0.11.6 and it seems to be fixed in 0.13.x.

**Comment by jakemmarsh** [comment]
It looks like this may be possible in the rackt/react-router#next branch since the `RouterHandler` component is removed, but I'd really rather not move to the development branch (on top of that, installing directly from Github means no build files).

**Comment by taurose** [comment]
Yeah, this kind of incompatibility is one of the reasons why it's being changed (or at least why I support it).

I believe RouteHandlerMixin was removed by accident. If you really want this to work with the current version, I guess the easiest way is to extract a RouteHandlerMixin from RouteHandler yourself.

**Comment by jakemmarsh** [comment]
Yeah, for now I'm just using 0.11.6 and requiring the mixin directly. Unfortunately, this also means I have to revert to React 0.12.x as well (due to peerDependencies).

**Comment by ryanflorence** [comment]
1.0 we just send components as `props.children`, so no more RouteHandler getting in the way.
