### ISSUE TITLE
'Animations' example outdated?

### ISSUE THREAD

**Issue by belohlavek** [rackt/react-router#1194]
Currently you need to require ``react/addons`` and access ``React.addons.CSSTransitionGroup`` in order to use CSS animations with React (as seen in: https://facebook.github.io/react/docs/animation.html).

The example provided is still using ``require('react/lib/ReactCSSTransitionGroup')``. I'd submit a pull request but I can't get the new example to work on my system (react-noob over here). I hope some react-guru can lend a hand!

**Comment by mjackson** [comment]
The animation story in version 1.0 is a lot better than it was in 0.13. Please check [the current animations example](https://github.com/rackt/react-router/blob/master/examples/animations/app.js#L17-L19). We're still using `CSSTransitionGroup`, but regular `TransitionGroup` works as well.
