### ISSUE TITLE
React router is retaining nested child when browsing from a given nested url to root

### ISSUE THREAD

**Issue by ilmattodel93** [rackt/react-router#1195]
I all!
First of all I would like to thank you all for your awesome work on react-router!

I have a problem when browsing from nested to parent routes.
I dynamically build the routes tree by loading various modules.

https://github.com/ilmattodel93/react-router-error/blob/master/src/Track/Track.js - / root
https://github.com/ilmattodel93/react-router-error/blob/master/src/Track/Modules/Auth/Auth.js - /auth auth
https://github.com/ilmattodel93/react-router-error/blob/master/src/Track/Modules/Auth/Auth.js - /auth/login auth.login
If you go to http://matt93.altervista.org/cold/ all works fine as it should, but if your given url is http://matt93.altervista.org/cold/#/auth/login and then you click "home" the content of /auth/login is retained, why? have I done something wrong?

Thanks in advance for any support! :smile:

**Comment by taurose** [comment]
You produce invalid dom by nesting `<p>`. Change it to div [here](https://github.com/ilmattodel93/react-router-error/blob/master/src/Track/Modules/Auth/Layout.js#L7).

**Comment by ilmattodel93** [comment]
Thanks! I did'nt noticed it!
