### ISSUE TITLE
Transition (scrollTop) between routes.

### ISSUE THREAD

**Issue by genxstylez** [rackt/react-router#1196]
How can I disable the ScrollTopBehavior for transition between routes?

please refer to my test site.

1. Go to  `http://test.o-logy.com/category/4`
2. Click on `People` on the secondary navigation bar

I want it to only change the content instead of a new page which starts from the top.
(the scrolling animation is done by jquery btw.)

**Comment by genxstylez** [comment]
Can anyone offer me help? thanks!

**Comment by taurose** [comment]
Link doesn't work for me (404).

Have you tried  http://rackt.github.io/react-router/#Route `ignoreScrollBehavior` ?

**Comment by gaearon** [comment]
Wrap the routes that need to be switched without scroll into a parent route, and give it `ignoreScrollBehavior`.

**Comment by genxstylez** [comment]
@gaearon I tried, without luck
@taurose the link works now, please try it again.

Thanks.

**Comment by gaearon** [comment]
@genxstylez 

It's hard to debug a minified website without the source code. I do not see you using `ignoreScrollBehavior`.

**Comment by genxstylez** [comment]
@gaearon 
Please see https://github.com/genxstylez/potential-sansa/tree/master/posts/static/js for my source code.

I am still trying ignoreScrollBehavior locally, doesn't really work

**Comment by genxstylez** [comment]
Below is the snippet I m using locally.
```js
    <Route name="app" path="/" handler={Application} ignoreScrollBehavior>
        <DefaultRoute handler={IndexPage} ignoreScrollBehavior/>
        <Route name="category" path="category/:categoryId" handler={IndexPage} ignoreScrollBehavior/>
        <Route name="subcategory"  path="category/:categoryId/:subcategoryId" handler={IndexPage} ignoreScrollBehavior />
        <Route name="search" path="search" handler={SearchPage}/>
        <Route name="albums" path="albums" handler={AlbumsPage} />
        <Route name="album" path="albums/:albumId" handler={AlbumPage} />
        <Route name="subscribe" path="subscribe" handler={SubscribePage}/>
        <Route name="post" path="post/:postId" handler={PostPage}/>
    </Route>
```

**Comment by genxstylez** [comment]
@gaearon really sorry for keeping on asking, but I am kinda urgent on this matter.  Any thoughts?

**Comment by gaearon** [comment]
@genxstylez 

Sorry, `gulp watch` fails for me. I can't even figure out how to begin reproducing your problem, because in production it is minified, and in development, well, it doesn't build:

```
gulp watch
[00:31:56] Using gulpfile ~/Documents/Projects/potential-sansa/gulpfile.js
[00:31:56] Starting 'watch'...
[00:31:56] gulp-notify: [Compile Error] Cannot find module './undefined/static/js/app.js' from '/Users/dan/Documents/Projects/potential-sansa'
```

Really, I'd love to help, but please make it easy for me. It's frustrating to clone a project and install the dependencies, only to figure out that there's no way for me to actually reproduce your problem.

**Comment by gaearon** [comment]
Please, provide a runnable project (or host an unminified project somewhere).

At the very least, you're not using `ignoreScrollBehavior` as intended. If you just put it on the top-level route, the router will *completely* fail to restore scroll. I think you only wanted that for certain routes, not for your whole app.

`ignoreScrollBehavior` is supposed to “mark” certain routes (and all their descendants) as not needing any scroll adjustment. In your case, you're not using the nesting where you should. Your route config should probably look like

```js
    <Route name="app" path="/" handler={Application}>
        <Route handler={HomePage} ignoreScrollBehavior>
            <DefaultRoute handler={Index} />
            <Route name="category" path="category/:categoryId" handler={Category} />
            <Route name="subcategory" path="category/:categoryId/:subcategoryId" handler={Category} />
        </Route>
        <Route name="search" path="search" handler={SearchPage}/>
        <Route name="albums" path="albums" handler={AlbumsPage} />
        <Route name="album" path="albums/:albumId" handler={AlbumPage} />
        <Route name="subscribe" path="subscribe" handler={SubscribePage}/>
        <Route name="post" path="post/:postId" handler={PostPage}/>
    </Route>
```

where `Index` and `Category` as placed into `HomePage` as nested routes.

In this case `ignoreScrollBehavior` is applied to `HomePage` because all transitions within it should not adjust scroll.

**Comment by ryanflorence** [comment]
wait a sec ... `<Route handler={HomePage} ignoreScrollBehavior>` is valid jsx? don't you need `ignoreScrollBehavior={true}`?

**Comment by gaearon** [comment]
>don't you need

You don't, attribute without value is a shortcut for specifying `true`.

**Comment by giantelk** [comment]
I have this bug/issue too wtih `ignoreScrollBehavior={true}` not working. 

Here's my repo: 
https://github.com/giantelk/react-router-scroll-issue

`Steps`
1. Scroll to bottom of page.
2. Click to second page.
3. Click back to 1st page.
4. Contents should not be scrolled to top of window. Should stay scrolled at the bottom of the window.

**Comment by giantelk** [comment]
Here's a hack-around using jQuery `$(window).scrollTop()`

```
// Capture state of last window location, i.e. in `componentWillUnmount` of the Component you want to save scroll position for i.e. `<MyFeed />`
this.props.setLastWindowPosition( $(window).scrollTop() );

// In a parent Component, i.e. <App />:
setLastWindowPosition: function(value) {
   setState( {lastWindowPosition: value} );
},
getLastWindowPosition: function(value) {
   return this.state.lastWindowPosition;
}
```
Then in `componentDidMount` of `<MyFeed />` (if works in componentWillMount it will be better, less visible).
```
$(window).scrollTop( this.state.lastWindowPosition )
```

**Comment by giantelk** [comment]
I guess in theory this should work, but for me this isn't doing anything. In `componentDidMount` I checked `$(document).height()` to verify that the DOM is loading with enough space to scroll into view. `$(window).scrollTop()` shows the last value before going away and back to my view, but then somewhere between that and when `componentDidUpdate` get's called `$(window).scrollTop()` goes back to 0.

```
// In componentDidMount of <MyFeed />
$(window).scrollTop( this.props.getLastWindowPosition )
```

**Comment by LeoFidjeland** [comment]
I'm having issues with scroll behavior as well.

ignoreScrollBehavior correctly prevents react router from imitating the browser behaviour, but it seems like the browsers are having this behavior by themselves now (no need to imitate), and I can't find a way to stop it.

Both chrome and firefox restore the scroll position of the previous page when I go back. Is there anyway we can affect this?

**Comment by ryanflorence** [comment]
a new scrolling implementation will come on top of the router after (maybe with) 1.0

**Comment by genxstylez** [comment]
@gaearon Sorry for the very late reply, was away from the project for a while now.

@ryanflorence great to know something will be done! looking forward, Thanks
