### ISSUE TITLE
Object is not a function error 

### ISSUE THREAD

**Issue by pyxis92** [rackt/react-router#1199]
my script kooks like this, and i get the following error "Uncaught TypeError: object is not a function"

    function estimatedbill() {      

		 var objJSON = {
				task: cal,
				seconds: seconds; 
				
			}

			$.post('ajax.php', objJSON ).error(function() {
				console.log("error");
			}).success(function(data) {
				console.log(objJSON); 
				
				$("p").text(data);

				console.log(seconds); 

			});

	}

html table part where function is called: 

    <td id="bill"> <button id= "estimatedbill" onclick="estimatedbill();">  Estimated bill:</button> <p>....</p></td>

what can i do to fix this ?

**Comment by KevinTCoughlin** [comment]
This is a JavaScript issue. Most likely your `estimatedbill` function is defined outside of the scope of your `<td>`'s onclick handler so it reports undefined when it tries to call the function.

**Comment by srph** [comment]
I'm wondering how this is related to react-router.. hmm.

**Comment by mjackson** [comment]
@KevinTCoughlin Thanks for helping out!
