### ISSUE TITLE
Child route components rerendered on parent route component setState() 

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1201]
When you have a nested route:
```javascript
<Route path="/" handler={ParentRoute} >
  <Route name="child-route" handler={ChildRoute} />
</Route>
```

... and you call `setState()` on the parent component:
```javascript
this.setState({ key: value });
```

... then the `ChildRoute` component is also re-rendered. I'm not sure if this is intentional, but this feels wrong. The parent component can't pass any `props` to the child component, so the child component shouldn't be re-rendered with it.

I expect the fix is to modify the `shouldComponentUpdate` logic on the `RouteHandler` component.

**Comment by taurose** [comment]
> The parent component can't pass any props to the child component, so the child component shouldn't be re-rendered with it.

Yeah, you can. Any props you pass to `<RouteHandler />` will be passed down to the corresponding component.

**Comment by aldendaniels** [comment]
@taurose - Thanks for the correction - I'd missed that! 

I would suggest, however, that passing `props` to `<RouteHandler />` may be bad practice. One of the great things about nested routing is that the route handler components are ignorant of how they will be nested. Passing `props` to `<RouteHandler />` breaks this isolation.

State shared between routes handlers is typically better put in a URL param or (if it doesn't belong in the URL) in some flux-like store accessible by all components.

Disabling passing props through `<RouteHandler />` would enforce strong component isolation. Incidentally, this also makes it possible to return false in the `RouteHandler`s `shouldComponentUpdate` method, enabling efficient re-rendering of parent components by default.

Thoughts?

**Comment by gaearon** [comment]
I think the router shouldn't be opinionated about that. In the next version, you're going to have `this.props.children` instead of `<RouteHandler />` so you'll need to go an extra mile to clone them with other `props` by calling `cloneElement`. Still, it's possible (and I think *should* be possible).

Because in the next version, there's no `RouteHandler`, the optimization you're suggesting can't be done. You are free to put an optimized `shouldComponentUpdate` into your route handlers. Other than that, the router should behave exactly as React behaves normally—if parent sets state, the child is reconciled.

Thanks for feedback!

**Comment by aldendaniels** [comment]
@gaearon - I wasn't aware that `RouteHandler` was going away  - thanks for the heads up. And yes, I'm using `shouldComponentUpdate` on my Route Handlers today to good effect. If you feel that passing through `props` to a child component is a valid use case, then leaving React Router unopinionated makes sense.

**Comment by gaearon** [comment]
>If you feel that passing through props to a child component is a valid use case, then leaving React Router unopinionated makes sense.

Here's a great use case if you're unconvinced: https://youtu.be/z5e7kWSHWTg?t=25m51s

**Comment by aldendaniels** [comment]
Interesting - thanks for the link!
