### ISSUE TITLE
reactiflux#react-router, gitter.im, discuss.reactjs.org ...

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1203]
I already have Slack open most of the day, and there are quite a few people that ask questions about the router in [reactiflux](http://www.reactiflux.com/)' #react-router channel. I almost never have gitter.im open.

Can we just remove the link to gitter.im from the README and recommend that people join reactiflux instead? Seems like this would be better for the React community in general as well.

Also: https://discuss.reactjs.org/ is a thing now (instead of the Google group). Should we have a tag/category for the router there as well? If so, one of us should definitely monitor that.

**Comment by mjackson** [comment]
Basically I just want a way to tell people "here is where we hang out. ask your q's here"

**Comment by henriquea** [comment]
+1 for discuss.reactjs.org

**Comment by bensmithett** [comment]
:+1: reactiflux

**Comment by mjackson** [comment]
I think discuss.reactjs.org is more of an email-list replacement. So that'll definitely be a thing for people who want that.

I guess what I'm looking for is more of chat-like environment. FWIW, there's also #reactjs on Freenode...

Currently reactiflux seems like it has the most activity. We should probably just chat there.
