### ISSUE TITLE
docs for those who need to do testing?

### ISSUE THREAD

**Issue by Pomax** [rackt/react-router#1205]
I don't see any mention in the README.md on where to find the docs if you're a dev and need to test things like "does this `<Link>` actually point to the correct location". How would one test those things, and can that information be put into, or linked to from, the README.md?

**Comment by gaearon** [comment]
Here's [a doc about testing](https://github.com/rackt/react-router/blob/master/docs/guides/testing.md).
For testing links, [check out the `Link` tests](https://github.com/rackt/react-router/blob/master/modules/components/__tests__/Link-test.js).

PRs to make the docs better are welcome.
