### ISSUE TITLE
Routes Configuration

### ISSUE THREAD

**Issue by dprentis** [rackt/react-router#1206]
Why not just use a plain js object for routes configuration?
The jsx seems unnecessarily verbose - what's the advantage?
(sorry if this is a duplicate of some other issue)

**Comment by BerkeleyTrue** [comment]
This is a duplicate.

https://github.com/rackt/react-router/issues/784
https://github.com/rackt/react-router/issues/865

Also see https://github.com/rackt/react-router/pull/1158 for future non-jsx config coming in 1.0.0

Hopefully this address your issue. Please close this if it does.

**Comment by dprentis** [comment]
thanks for the quick reply - looking fwd to that functionality!
