### ISSUE TITLE
ability to redirect to url

### ISSUE THREAD

**Issue by ryanzec** [rackt/react-router#1210]
Lets say someone has a page like this bookmarked:

```
/projects/test/issues/123
```

Now the router for this might look like this:

```
/projects/:projectId/issues/:issueId
```

Now if someones tried to hit this page, they get transitioned to a authentication page.  What I am trying to do is be able to redirect the user back to the `/projects/test/issues/123` however I can't seem to find a way to redirect to a url instead of a route name.

Not sure if this already exists but I can't find it if is does.

**Comment by edvinerikson** [comment]
Hi.
You can use the `transitionTo` method available in the [`Navigation`](http://rackt.github.io/react-router/#Navigation) mixin.

e.g `this.transitionTo('/users/10?showAge=true');`

**Comment by sheerun** [comment]
What if I use ES6 classes for component, and I cannot use mixins?

**Comment by edvinerikson** [comment]
You can access the router context directly from your component.
Check the [source](https://github.com/rackt/react-router/blob/master/modules/Navigation.js#L24) of the Navigation mixin for an implementation. 
Or you can create an High order component and use the mixin.

**Comment by sheerun** [comment]
Can this be documented on official site?

**Comment by ryanflorence** [comment]
@ryanzec <Redirect from="/old/:path/with/:stuff" to="/new/:path/with/:stuff"/>

@sheerun don't use ES6 classes when you need mixins. React still ships with mixins, and react still uses createClass, also https://twitter.com/soprano/status/610867662797807617

**Comment by sheerun** [comment]
@ryanflorence That's a poor reason to not use ES6 classes :) Especially there are real alternatives like decorators or higher-order component wrappers.
