### ISSUE TITLE
Is it possible to use react-router in a component ?

### ISSUE THREAD

**Issue by manuquentin** [rackt/react-router#1212]
Hi,
I'm working on a library that uses react-router. To allow everyone using this library I've created a component.
The issue is that Router.run() expect a callback as second argument and I don't know how to render my component.

Here is a fiddle of [what I'm trying to do](https://jsfiddle.net/x8b2de23/1/). with the error:
```js
Uncaught TypeError: Cannot read property 'makeHref' of undefined
```

Do you know how can I manage to get this working ?
Thanks!

**Comment by taurose** [comment]
The callback argument gives you a Handler component which you're supposed to render. So you simply need to call setState at that point, and then make the wrapper render it.

https://jsfiddle.net/mdp8fxzn/1/

**Comment by manuquentin** [comment]
Works like a charm.

Thanks!
