### ISSUE TITLE
peerDependencies will be deprecated in npm@3.x 

### ISSUE THREAD

**Issue by johannestroeger** [rackt/react-router#1216]
[https://docs.npmjs.com/files/package.json#peerdependencies](https://docs.npmjs.com/files/package.json#peerdependencies) - kthxbye!

**Comment by gaearon** [comment]
I don't think it says they are deprecated. It says that *they will no longer be automatically installed*. There's nothing RR as a library should do here: with NPM 3, it's up to you to install React on your own (which you probably already have in your app anyway).
