### ISSUE TITLE
Non-nested routes

### ISSUE THREAD

**Issue by norbertpy** [rackt/react-router#1220]
Hi. First of all, thanks for this awesome project. I'm easily sold to use it from now on. But I'm a little confused. I have an HTML like this:
```
<main>
    <nav>
        <level1>
            <Link to="contentA" />
            <Link to="level2" />
        </level1>
        <level2>HERE</level2>
    </nav>
    <content />
</main>
```

If I put a `RouteHanlder` in place of `content` and add some `Link`s inside `level1`, I can render `contentA` when route state is `/contentA`. That's easy. The problem is, I need to render something else in place of `level2` when I'm at `/level2`. As you can see the two `RouteHandler`s will be sibling somehow and it results in rendering the same thing for both. 

Nested state but not nested views. How would I go about this?

**Comment by stevenpetryk** [comment]
> Nested state but not nested views

AFAIK, that's not particularly possible. However, you *can* have nested URLs but non-nested states, which is probably what you're after. See [this section](http://rackt.github.io/react-router/#nested-ui-and-nested-urls-need-not-be-coupled) of the documentation for details.

**Comment by norbertpy** [comment]
Thanks.
