### ISSUE TITLE
Remembering scroll behaviour for page content

### ISSUE THREAD

**Issue by gyzerok** [rackt/react-router#1222]
Is there a good way to simulate router scroll behaviour not for a full page, but for a concrete div tag?

**Comment by gaearon** [comment]
You can supply a custom `scrollBehavior` to `Router.create` that does that.

**Comment by gyzerok** [comment]
@gaearon I've understand how to scroll to the needed position with this solution. But how do I customize remembering previous position for concrete div with it?

**Comment by gaearon** [comment]
Oh right. There's no easy way to do this yet. But we will support this in 1.0 which will be out soon.
