### ISSUE TITLE
Request: Official Ruby on Rails Gem

### ISSUE THREAD

**Issue by thisiserik** [rackt/react-router#1225]
Is it possible at all to release an official Rails gem?

**Comment by krzysiek1507** [comment]
You can use https://rails-assets.org/

**Comment by uberllama** [comment]
I've been using the rails assets version since the beginning with no issues. As a general rule, I've replaced all of my assets-based gems with rails assets equivalents. Makes for an easier transition out of asset pipeline.

**Comment by thisiserik** [comment]
@uberllama  Thanks for the recommendation, but I think I will actually separate my JS from the Rails code. I really don't like the way the Javscript is handled and I think a more modular approach would work better for the projects that I work on.
