### ISSUE TITLE
ES6 named imports not working in the browser

### ISSUE THREAD

**Issue by jedrichards** [rackt/react-router#1227]
Hey there

I'm using Babel `5.1.13`, and using ES6 named imports to grab a component like so,

```
import {Link} from 'react-router';
```

doesn't work in the browser, `Link` is `undefined`, but the exact same code works fine server side when using the same version of Babel and invoked via `babel-node`. Is this a react-router problem, or a Babel thing I wonder?

Thx!

**Comment by ryancole** [comment]
Strange. I'm also using babel, with browserify, and that definitely works for me. Looking at the code also shows that `Link` is a named export that's available. Sounds like maybe something with babel or something else you're using?

**Comment by jedrichards** [comment]
Aha. I will dig a little deeper ... thanks.

**Comment by jedrichards** [comment]
This is happening on some other libs too, so going to close this and follow up with jspm and Babel. Will report back here I find something out.
