### ISSUE TITLE
Error with NPM Install on Windows

### ISSUE THREAD

**Issue by Wolfeitz** [rackt/react-router#1229]
-= Workaround included =-
Running NPM Install on Windows resulted in:
> react-router@0.13.3 build D:\Projects\react-router
> scripts/build.sh

'scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-router@0.13.3 build: `scripts/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-router@0.13.3 build script 'scripts/build.sh'.
npm ERR! This is most likely a problem with the react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\react-router\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-router@0.13.3 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-router@0.13.3 prepublish script 'npm run build'.
npm ERR! This is most likely a problem with the react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\react-router\npm-debug.log

D:\Projects\react-router>npm install
npm WARN package.json events@1.0.2 events is also the name of a node core module
.
npm WARN package.json karma-mocha@0.1.10 No README data
npm WARN package.json rf-changelog@0.4.0 No repository field.
-------------------------------------------------------------

Change the prepublish line in package.json from "prepublish": "npm run build" -> "prepublish": "npm run && npm build" and everything installs without error.

**Comment by frg** [comment]
This worked for me. Thanks @Wolfeitz !

**Comment by frg** [comment]
@Wolfeitz dou have a fix for when you try running "npm run examples"?

I'm getting this error;

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'examples' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preexamples', 'examples', 'postexamples' ]
6 info preexamples react-router@1.0.0-beta3
7 info examples react-router@1.0.0-beta3
8 verbose unsafe-perm in lifecycle true
9 info react-router@1.0.0-beta3 Failed to exec examples script
10 verbose stack Error: react-router@1.0.0-beta3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples --inline`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-router@1.0.0-beta3
12 verbose cwd C:\sauce\examples\react\react-router
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "examples"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error react-router@1.0.0-beta3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples --inline`
18 error Exit status 1
19 error Failed at the react-router@1.0.0-beta3 examples script 'webpack-dev-server --config examples/webpack.config.js --content-base examples --inline'.
19 error This is most likely a problem with the react-router package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack-dev-server --config examples/webpack.config.js --content-base examples --inline
19 error You can get their info via:
19 error     npm owner ls react-router
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by frg** [comment]
As a quick fix I replaced all "/__build__/" references in examples to "../__build__/" and just run index.html straight.

Not pretty, but it works.
