### ISSUE TITLE
Put the docs as the URL in the repo description

### ISSUE THREAD

**Issue by ericclemmons** [rackt/react-router#1232]
Github repository should link to docs:
> http://rackt.github.io/react-router/

Example:
> ![screen shot 2015-05-26 at 4 05 38 pm](https://cloud.githubusercontent.com/assets/15182/7823441/2127593a-03c1-11e5-92bd-6107c7c33c75.png)

How this repo looks currently:
> ![screen shot 2015-05-26 at 4 05 15 pm](https://cloud.githubusercontent.com/assets/15182/7823453/2fcecd10-03c1-11e5-8537-c4974bd32855.png)

Unfortunately, I can't PR this :)

**Comment by gaearon** [comment]
@ryanflorence you can do this

**Comment by ericclemmons** [comment]
@ryanflorence I was suggestion a commit-less way of doing it:
> ![](https://cloud.githubusercontent.com/assets/15182/7823441/2127593a-03c1-11e5-92bd-6107c7c33c75.png)

Or run the following on https://github.com/rackt/react-router:
```javascript
document.querySelector('.edit-link').click()
```

And, depending on your timezone... :)
> https://www.youtube.com/watch?v=5BV85WRsIyo

**Comment by BerkeleyTrue** [comment]
It would be nice to add this up their in the description itself.
