### ISSUE TITLE
server and client with different url path

### ISSUE THREAD

**Issue by Yixi** [rackt/react-router#1233]
I use react-router for render both server side and client side. but the project is a secondary directory project. 

that means my project's url is xxx.com/react

at server side , the  root  route path '/'  means xxx.com/react
so I define like this:

```jsx`
<Route path="/library" handler={require('./components/Html')}></Route>
```
when server side render xxx.com/react/library is works fine.

but I built client js with the same file like:

```javascript`
var React = require('react');
var Router = require('react-router');
var routes = require('./routes');

Router.run(routes,Router.HistoryLocation, function(Handler,state){

    React.render(<Handler/>,document.getElementById('markup'));
});
```

I get a error

````
No route matches path "/react/library". Make sure you have <Route path="/react/library"> somewhere in your routes.
```

so  how  can I use a same router file to render both server and client?

**Comment by ryanflorence** [comment]
put the "root path" in your root route in the client.

`<Route path="/react/library"/>`

**Comment by Yixi** [comment]
but i need use this route file both server and client
