### ISSUE TITLE
How to distinguish redirect (to a login page) from manual user navigation to that page

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1238]
Hi,

I am trying to make my app display an info message in the login page when the user gets redirected to it (e.g. 'You need to be logged in as an administrator to access the requested page').  However, no message should show if the user navigates to the login page manually.

The only way I can think of to accomplish this is to put the message as a URL parameter, but I want a more elegant solution.  If I put the message in some store upon redirect, it will still be stuck there when the user manually navigates back to the login page later.  I was wondering if I could use a location listener to do this, but I'm not sure how I could detect when the location change comes from a redirect triggered by code.

Is there any way I can accomplish this?

**Comment by ryanflorence** [comment]
the new `location.state` feature would let you do this.

https://rackt.github.io/react-router/tags/v1.0.0-beta2.html#Router

check out the `transitionTo` method

**Comment by jedwards1211** [comment]
I read this requires putting a key into the URL...couldn't there be a less complicated way to do it, i.e. just pass what route is being transitioned from to the hook along with what's being transitioned to?

**Comment by jedwards1211** [comment]
Sorry, ignore the previous, I was mixing up the issues I opened
