### ISSUE TITLE
Invariant violation when using <Link />

### ISSUE THREAD

**Issue by MhSaadany** [rackt/react-router#1241]
I've created a [Gist] (https://gist.github.com/MhSaadany/eeffcb31eb5153708666) showcasing the issue.

#### My routes
```javascript
<Route handler={App}>
    <DefaultRoute name='dashboard' handler={Dashboard} />
    <Route name='list' path='list' handler={ListController} />
    <Route name='detail' path='detail/:id' handler={Detail} />
</Route>
```

#### App
```javascript
<div>
  App
  <Bar />
  <hr />
  <RouteHandler />
  <Link to='list'>Goto List</Link>
</div>
```
#### Bar
```javascript
// Just using <Link> will caue invariant violation when accesing '/detail/:id'
var Bar = React.createClass({
  mixins: [Router.State],

  render: function () {
    return (
      <ul>
        {this.getRoutes().map(function (route, i) {
          return (
            <li key={i}>
              <Link to={route.path}>{route.path}</Link>
            </li>
          );
        })}
      </ul>
    );
 }
});
```
#### ListController
```javascript
var ListController = React.createClass({
  mixins: [Router.Navigation],

  handleClick: function (id) {
    this.transitionTo('detail', {id: id});
  },

  render: function () {
    return (
      <List handleClick={this.handleClick} />
    );
  }
});
```
#### List
```javascript
var List = React.createClass({
  render: function () {
    return (
      <ul>
        {[0, 1, 2, 3, 4].map(function (elem, i) {
          return (
            <li key={i} onClick={this.props.handleClick.bind(null, i)}>
              {'Link ' + i}
            </li>
          );
        }.bind(this))}
      </ul>
    );
  }
});
```
The issue is that if I use the `<Link />` component inside `<Bar />`, I get 
> Uncaught Error: Invariant Violation: Missing "id" parameter for path "/detail/:id"

From the click events in `<List />`

**Comment by krzysiek1507** [comment]
https://rackt.github.io/react-router/#Link
Missing params with <code>id</code> for <code>detail</code> path.

Better way than
```javascript
{this.getRoutes().map(function (route, i) {
  return (
	<li key={i}>
	  <Link to={route.path}>{route.path}</Link>
	</li>
  );
})}
```
is writing each Link manually, because of customization, params, etc.

**Comment by MhSaadany** [comment]
I am sorry @krzysiek1507, I am not sure what you mean.

**Comment by krzysiek1507** [comment]
Can you reproduce this [here](https://jsfiddle.net/)?

**Comment by MhSaadany** [comment]
Thank you @krzysiek1507 for your help.

I Now understand your previous comment. The issue was that when the router was transitioning to the 'detail' route, `<Bar />` was generating a `<Link />` for the 'detail' route without an id parameter which was throwing the invariant violation.

I assumed that since I was providing the 'path' prop to <Link />, I didn't need to provide the 'params'  prop.

**Comment by mjackson** [comment]
Thanks @krzysiek1507

**Comment by jackyon** [comment]
hi, @MhSaadany,

how did you solved that? I got same errors as yours when using Link component

codes:
```javascript
<Link to={`article/${item.id}`}>
	article
</Link>
```

router:
```javascript
module.exports = {
	path: '/article/:postId',

	getComponent(location, cb) {
		require.ensure([], (require) => {
			cb(null, require('../../../containers/News/Article/'))
		})
	}
}
```

plz advise, thx!

**Comment by jackyon** [comment]
UPDATE:
The problem wasn't with react-router, but it was when I was triggering a dispatch. I was triggering an Action before a previous dispatch called emitChange, causing the Invariant Violation.
