### ISSUE TITLE
Noticeable lag in setting active class on Link

### ISSUE THREAD

**Issue by NicholasGW** [rackt/react-router#1242]
I have a page that has a pretty large render + lots of aysnc going on, but I haven't been able to diagnose the cause of this issue. When I click a new link, there is a long, noticeable delay in when the link adds the active class. It appears even after all the rendering and network activity as stopped, there can still be a long delay (5 seconds or so). Wondering if anyone else is experiencing this behaviour or has a workaround, otherwise I'm looking at imperatively modifying the class in componentDidMount for each of my sub-views.  
  
Links are sidebar nav icons, and the active class gives them a shaded background, if that matters.

**Comment by mjackson** [comment]
@NicholasGW Would you mind upgrading and testing your site on version 1.0.0-beta2? The [current code implements the `isActive` check as a simple string comparison](https://github.com/rackt/react-router/blob/5d674c9515aa628b644c223b2e3f43bb28ac24bc/modules/RouterContextMixin.js#L8-L9), so perf should improve considerably 99% of the time.

**Comment by gaearon** [comment]
Do any components between the `<Link>` and the `<Router>` implement `shouldComponentUpdate`?
This might be the same problem as #470 and facebook/react#2517.

**Comment by ryanflorence** [comment]
Link now listens to the history to know if its active, so they should be much faster now on re-renders, though time will tell if they are slower now to set up :neutral_face: 

Closing and waiting for tickets to come in with the new implementation as being slow :pray:

**Comment by billyshena** [comment]
@ryanflorence Do you still have this issue?
I'm also currently rendering <Link> dynamically and I can notice a small delay when the active class is set on the component.
Did listen to the history fixed the performance problem ?

Best,

**Comment by stooboo** [comment]
Hows about this then ?
