### ISSUE TITLE
Allow willTransitionTo() to get the current path/params/query that will be transitioned from

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1247]
After working on my auth flows, I realized the ideal behavior for my site in most cases is simply to transition back to whatever page the user was on before logging in.

So ideally in the `willTransitionTo()` hook of my login route, I simply save off the path/params/query being transitioned from.  However, I can't get that from the State mixin since of course `willTransitionTo()` is a static lifecycle method.   I can't even use `window.location.href` because it's already the URL of the new route.   I guess I could use the HTML5 history API or do something with a Location listener, but to me it just seems like plain common sense that if I'm being told I'm about to transition to something, I should be able to find out *easily* what I'm transitioning from as well.  I don't want to have to mix in a `willTransitionFrom()` into every single route in my application.

Thanks!

**Comment by jedwards1211** [comment]
I think it will eventually become apparent that saving and retrying a transition only handles a limited number of authentication flows.  At least in the case of my single-page app, certain routes will render differently depending on the user's authorization status (rather than a given route being simply forbidden or not).

For instance, in my app, one dialog shows as read-only if the user isn't authorized to modify certain data; but I'm trying to make it where they can click a link to the dialog to go to the login page, and once they log in it will redirect them back to the page with the dialog, which (if they logged in as a user with write permissions) will no longer be read-only.  Implementing this flow is not convenient with the hooks react-router currently provides.

**Comment by ryanflorence** [comment]
the auth flow example does this.

**Comment by jedwards1211** [comment]
No, reopen.  The auth flow example is different.  It uses `willTransitionTo()` on each page that needs authorization.  I'm talking about putting `willTransitionTo()` on the login page itself, to save off whatever page is being transitioned from.  This way even if the user manually clicks the login link it will save what page they're coming from.  The auth flow way of doing things only works when it automatically redirects the user to the login page.

Once again, why not just provide the route being transitioned from to `willTransitionTo()` hooks?

**Comment by ryanflorence** [comment]
You can wrap all your authed routes in a parent route, and only do it in one place: https://github.com/rackt/react-router/issues/1157#issuecomment-113184641

**Comment by jedwards1211** [comment]
Maybe I'm not explaining well, because that's not what I'm to achieve.  Here is the corollary of what I was saying:

1) The user begins on route A *that doesn't require authorization*
2) The user clicks the login link
3) The user logs in
4) The user is redirected back to route A

And then if they started from paroutege B that doesn't require auth, it would redirect them back to that, etc.

In other words when the program redirects *or the user navigates* to login from *any* route besides login/logout, it saves what route they were on and goes back to it after login.

**Comment by ryanflorence** [comment]
ah I gotcha, sorry, I'm cruising through tickets, perhaps too quickly.

We've been talking about adding `location.referrer` on our location objects.

I've opened a ticket for it at #1353

**Comment by jedwards1211** [comment]
Okay, cool, that would work!

**Comment by goldensunliu** [comment]
what for example, I want to consume a query parameter and redirect to the same path with the query parameter removed? I can see myself needing the getQuery() method in willTransitionTo
