### ISSUE TITLE
Question: Pass props to App handler.

### ISSUE THREAD

**Issue by jannavarro** [rackt/react-router#1251]
Is there a way to pass props to the App react component.For example just taking the main sample from the docu and adding a props. What should be the declaration of AppComponent?

    -App.jsx
       export default React.createClass({
       render: function () {
       return (
        <div>
      *************accessing props here************
      <h1>Hello {this.props.user}</h1>
      <ul>
        <li><Link to="home">Home</Link></li>
          <li><Link to="search">Search</Link></li>
            <li><Link to="passenger">Passenger</Link></li>
        <li><Link to="login">Login</Link></li>
      </ul>
      <RouteHandler />
    </div>
    );
    }
    });

    -main.jsx
      *************passing props here. What should be the declaration of AppComponent? Doing the code below does not make the routing work.************
        var AppComponent = <App user="Joe"/>;
        var routes = (
          <Route handler={AppComponent}>
            <DefaultRoute handler={RouterHome} />
            <Route name="home" handler={RouterHome} />
            <Route name="search" handler={RouterSearch} />
            <Route name="passenger" handler={RouterPassenger} />
            <Route name="login" handler={RouterLogin} />
          </Route>
        );
       //render here

**Comment by BerkeleyTrue** [comment]
Try adding them after the Router Run method.
```js
Router.run((Handler, state) => {
  React.render(<Handler user='joe'>); // <-Here
});
```
