### ISSUE TITLE
Detect when transition to a child page

### ISSUE THREAD

**Issue by totopia** [rackt/react-router#1252]
I have following route structure at the moment:

````
 <Route name="app" handler={Application}>
       <Route name="main">
            <Route name="child" />
       </Route>
</Route>
````

The use case is simple. When I am on the main page, I don't display the back button, but on the child page i do. Currently I have all the child handlers update a header store to make sure app header is in sync with a `childPage` flag. This requires me to use a mixin among all the child pages. 

But I wonder if there is an alternative way to leverage react-router for this task. I'd need to determine that I am transitioning to a sub-route of certain route by specifying some attribute on the <Route> and trigger some child route handling logic.

**Comment by ryanflorence** [comment]
in `v1.0` the `RouteHandler` was moved to `this.props.children`, so now you should be able to:

```js
var showBackButton = this.props.children != null;
```
