### ISSUE TITLE
Add support for supplying a path to DefaultRoute

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1253]
It would be nice, as mentioned in #883, to be able to give a default route a path so that, for example, when someone hits a top level path `/settings/` they would be redirected to `/settings/general/` or similar. Just a piece of the code I'm working on for an example:

    <Route name="settings" handler={SettingsBase}>
      <DefaultRoute name="settings_general" path="general" handler={SettingsGeneral}/>
      <Route name="settings_team" path="team" handler={SettingsTeam}/>
    </Route>

**Comment by ryanflorence** [comment]
Default routes match when their parent matches, they don't have a path. Maybe you're after a `defaultRedirect`? in which case you redirect in the default route's transitionTo.

**Comment by chrisdrackett** [comment]
hm, I'm not sure what you mean by the default route's transitionTo. I just want `/settings/` to redirect to `/settings/general/` but don't see an easy way to make this happen. I tried the above first and next tried:

```
<Route name="settings" handler={SettingsBase}>
  <Redirect from="/" to="general"/>
  <Route name="settings_general" path="general" handler={SettingsGeneral}/>
  <Route name="settings_team" path="team" handler={SettingsTeam}/>
</Route>
```

but that also does not work.

**Comment by chrisdrackett** [comment]
that being said, the following does work, but I'd rather the above.

```
<Redirect from="settings" to="settings_general"/>
<Route name="settings" handler={SettingsBase}>
  <Route name="settings_general" path="general" handler={SettingsGeneral}/>
  <Route name="settings_team" path="team" handler={SettingsTeam}/>
</Route>
```

**Comment by Wildhoney** [comment]
+1 &mdash; would much prefer the former, as it keeps all related items encapsulated in the parent `<Route />`.
