### ISSUE TITLE
conditions on Dynamic Segments 

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1254]
I'm trying to figure out if its possible to "pass over" dynamic segments if they don't match a pattern you are looking for. for example, say you have a site (like github) with the following urls:

`/blog/`
`/explore/`

and the site also puts usernames at the top level:

`/rackt/`

I'm guessing that you could put `/:username` below the routes for blog and explore. But what if you have need to match something else dynamic on the same level? I come from django where you can define a pattern like so:

`url(r'^(?P<page>blog|explore)/', 'static_page'),`
`url(r'^(?P<username>[-\w]+)/$', 'member_profile'),`

Not sure if something like this is possible currently, I'm still getting my feet wet!

**Comment by ryanflorence** [comment]
You simply define the routes you want to specifically match ahead of the dynamic ones.

In `v1.0` you can use `router.getChildRoutes` and do whatever matching you want on the path to decide which children to return. https://rackt.github.io/react-router/tags/v1.0.0-beta1.html#Plain Route

**Comment by chrisdrackett** [comment]
Sounds like I need 1.0 to do what I want (have two dynamic routes on the same level)

Thanks!
