### ISSUE TITLE
default route with Dynamic Segments

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1257]
I have my static pages (About, Terms, etc.) all being rendered by the same route that uses a dynamic segment so its a bit easer to add a new static page. I would like to set one of these as the default route, but don't currently see a way to do that.

**Comment by ryanflorence** [comment]
You'll need a different component that then renders the shared component.

```js
<DefaultRoute handler={OtherHandler}/>
<Route path="/static/:page"/ handler={SharedHandler}>

var OtherHandler = React.createClass({
  render: function() {
    return <OtherHandler params={{page: 'whatever'}}/>
  }
});
```
