### ISSUE TITLE
Path components with URI-encoded `$` in them aren't correctly decoded

### ISSUE THREAD

**Issue by nornagon** [rackt/react-router#1264]
```
router.transitionTo("foo", { component: encodeURIComponent("{foo$bar") })
```
results in the URI `http://host/foo/%7Bfoo%24bar`. Subsequently calling `router.getCurrentParams().component` returns `"{foo%24bar"`, which is half-decoded. This appears to be related to the `decodeURI` call in `getCurrentPath`.

**Comment by mjackson** [comment]
@nornagon Can you please verify this is fixed on current master? Should we add a test for it?

**Comment by ericlynnpeterson** [comment]
I made a pull request #1727 with a test case showing it is fixed in the current version of master.

**Comment by mjackson** [comment]
Thanks, @elpete !
