### ISSUE TITLE
ability to set key on Link?

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1269]
I'm working on animating a list of `Link`'s and noticed that when I set a key on links I'm not seeing it in the rendered component. I'm fairly new to react, so I might be missing something, but I thought it was worth raising.

**Comment by mjackson** [comment]
You don't see keys anywhere in rendered components. It's an attribute that React uses internally to track component instances between `render` calls, but the only place it shows up in the DOM is in the `data-reactid` attribute.
