### ISSUE TITLE
Add link to doc sites to head of project

### ISSUE THREAD

**Issue by KyleAMathews** [rackt/react-router#1271]
Next to the project description

**Comment by BerkeleyTrue** [comment]
duplicate, please close. https://github.com/rackt/react-router/issues/1232

**Comment by KyleAMathews** [comment]
This actually isn't a duplicate. My suggestion was to add a link to top of the page as that's more convenient than going hunting down in the README.

![rackt_react-router](https://cloud.githubusercontent.com/assets/71047/8153302/838ee65a-12e0-11e5-898c-079a5b5d5399.png)

**Comment by KyleAMathews** [comment]
Oh nvm, it wasn't a duplicate, it just wasn't fixed by https://github.com/rackt/react-router/commit/aef87479b16d1f12fdf02cfbd297e2d8e1032392

**Comment by BerkeleyTrue** [comment]
That is what @ericclemmons is suggesting in #1232
