### ISSUE TITLE
Programattic createRoute error

### ISSUE THREAD

**Issue by jannavarro** [rackt/react-router#1272]
I did the workaround stated in #887 but I get an error of ReactDefaultInjection.js: Uncaught TypeError: type.toUpperCase is not a function. I just want to ask for guidance if there is something I need to correct in the ff because I tried different approaches already.

    --MainRoute.jsx
    import App from "../../app0";
    import Login from "../auth/login"

    var MainRoute = Router.createRoute({
    handler: {App}
    });

    Router.createRoute({
    name: "login",
    parentRoute: MainRoute,
    handler: {Login},
    isDefault: true
    })

    export {MainRoute}

    --Index.jsx
    import {MainRoute} from "./modules/routes/AuthRoute"
    //some code
    Router.run([MainRoute], function (Handler, state) {
          React.render(
            <Handler  cursor={data} statics={state} />, document.body);
        });

**Comment by jannavarro** [comment]
I added the code [here](https://github.com/jannavarro/react-router-issue-1272) so it can be repro. The index.js contains the code with error and below that there is a commented equivalent code that is not the programattic way but is working.

**Comment by mjackson** [comment]
`createRoute` is gone in the 1.0 API (current master). You can use plain js objects instead.

**Comment by eriknyk** [comment]
did you @jannavarro solved this issue anyway?

Regards.

**Comment by gryzzly** [comment]
@mjackson how does one define `RedirectRoute` with plain JS objects in 1.0? Thanks!

**Comment by knowbody** [comment]
@gryzzly see #2256
