### ISSUE TITLE
How to deal with non-singleton stores inside of static transition hooks?

### ISSUE THREAD

**Issue by ryancole** [rackt/react-router#1274]
Hi all, I've been following the 1.0 release pull request, and keeping an eye out for patches to master that might address the static transition hooks and the inability to access props from within them.

I'm using Flummox, which does not use singletons for stores. Instead it passes stores and state in as props. I'm needing to add some basic route authorization that prevents users from accessing certain routes if one of my flummox stores says the user is not signed in.

What is the recommended way of handling this in the meantime, until the 1.0 rework lands? I've seen that there is a fork that adds the ability to add state to the router, I think. Are there other options? Am I able to use the `next` branch at the moment, or is it not in a usable state?

Thanks!

**Comment by DelvarWorld** [comment]
See https://github.com/rackt/react-router/pull/590 - you can use his fork to access context in a willTransitionTo. Specifically I'm using someone else's fork which fixes an es6 issue:

    "react-router": "git://github.com/bobpace/react-router.git#transitionContext",

then

     var Router = require('react-router/build/npm');

Server side working with fluxible and this pattern.

**Comment by erosenberg** [comment]
I would also love to know more about this. 

Do we really need to pass it to a function called requireAuth that returns a class?

**Comment by ryancole** [comment]
@DelvarWorld alright cool, im using the branch now. thanks. instead of requiring that build path though, i cloned the branch locally (not as a dependency to my project), and then used `npm link` to add it to my project. that way its just a drop in replacement without having to change the imports.

**Comment by ryanflorence** [comment]
You'll have a few options in 1.0, we're working our butts off to ship a beta this week, I'll make sure to update this thread with what it will look like.

**Comment by ryancole** [comment]
Thanks for all the hard work, @ryanflorence. I'll def help test out the beta as soon as ya'll post it.

**Comment by gcanti** [comment]
>  I'll def help test out the beta as soon as ya'll post it.

Me too. Thanks for working on this guys

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/pull/590#issuecomment-111910388

**Comment by ryancole** [comment]
I love it. Thanks a ton!
