### ISSUE TITLE
willTransitionFrom Does not fire on transitions between nested routes

### ISSUE THREAD

**Issue by nhsiehgit** [rackt/react-router#1278]
say I have a routes file
```
<Route name="app" path="/" handler={Application}>
  <Route name="settingsWrapper" path="settings/" handler={SettingsPageWrapper} >

    <Route name="profileSettings" path="profile/" handler={ProfileSettings} />
    <Route name="billingSettings" path="billing/" handler={BillingSettings} />
    <Route name="addCard" path="billing/addCard/" handler={AddCard} />

  </Route>
  <Route name="UserProfile" path="profile/" handler={ProfilePage} />
</Route>
```

If I add the static `willTransitionFrom` to either the `BillingSettings` or the `profileSettings` component, it does not fire, though if I add the static to the `settingsWrapper` or the `UserProfile` component, it will fire.

Is this by design or is there some way to get transitions from these routes to fire?

*edit:

~~I just noticed that if I add the static to a parent component like `SettingsPageWrapper` it will fire on some of the children component transitions, but not on others and i'm not sure whats causing it to fire sometimes and not others (maybe fires when there's queries but not when there arent?)~~

`willTransitionTo` is still called when transitioning from say `billingSettings` to `addCard` i'm assuming since the path lengths are different, but won't be called when moving from `profileSettings` to `billingSettings`.

**Comment by ryanflorence** [comment]
you've got two routes with the path `profile/` so I don't think you're transitioning from where you think you are.

**Comment by hackhat** [comment]
Anyway this is still an issue

**Comment by nhsiehgit** [comment]
I think with 1.0.0, the `routerWillLeave` method will resolves this issue.
