### ISSUE TITLE
add a way to have a more strict `isActive`

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1279]
Basically what I'm looking for is an exact match. Say I have the following routes:

`/`
`/questions/`
`/questions/123`

and I want to know if `/questions` is active but not `/questions/123`. I don't think this functionality exists, but it would be nice to have.

**Comment by mjackson** [comment]
The whole point of `isActive` is to be able to match any route in the hierarchy that is currently active. If you only want to match the leaf route, just compare the pathname of the URL directly with your href.
