### ISSUE TITLE
this.context.router undefined in IE10

### ISSUE THREAD

**Issue by bsbeeks** [rackt/react-router#1281]
We're currently running version 0.13.3 and are using the State Mixins to access `.getParams()` throughout the our app. Specifically we are calling the method in `componentDidMount` and `componentWillReceiveProps`.

When running the app in IE10, we get the error `Unable to get property 'getCurrentParams' of undefined or null reference`, which is being traced back to the `getParams` method of the `State` object:

![screenshot 2015-06-10 11 38 30](https://cloud.githubusercontent.com/assets/714084/8089471/496b739a-0f65-11e5-8eec-d7b36488c5e2.png)

I should also note that we're using Webpack and the Babel loader.

**Comment by bsbeeks** [comment]
Did a little more digging and it looks like the `this.context` object doesn't have `router` defined at all. I was also curious if using the method in `componentDidMount` or `componentWillReceiveProps` was the issue. But, I get the same error if it's used in `render`.

**Comment by gaearon** [comment]
So this only happens in IE? That's very weird. Can you make sure you're testing the exact same code in IE and other browsers?

**Comment by bsbeeks** [comment]
Yeah, definitely weird. I've verified that the same code is being ran in IE, Chrome, and Firefox. The same code also works fine in IE11.

**Comment by mjackson** [comment]
A failing test case would be great here. @bsbeeks You up for it?

**Comment by bsbeeks** [comment]
@mjackson would love to. Newbie question...by a "failing test case", are you just looking for some code that you can run in IE10 that produces this error?

**Comment by ryanflorence** [comment]
that, or an actual test in the __tests__ directory

**Comment by bsbeeks** [comment]
Thanks Ryan! Told ya it was a newbie question ;). I'll get one written this week.

**Comment by bsbeeks** [comment]
I finally got some time to dig into this, and it looks like there is already a test written that should capture this use case:

https://github.com/rackt/react-router/blob/4e2ca3c14d077b1b5aa46bda6c66bbd330de03b0/modules/__tests__/URLUtils-test.js#L36

The catch is you have to run the tests in IE10. It looks like Karma has an IE launcher (https://github.com/karma-runner/karma-ie-launcher) where you can specify the version of IE by adding the following to the config:
```
customLaunchers: {
  IE10: {
    base: 'IE',
    'x-ua-compatible': 'IE=IE10'
  }
}
```

**Comment by taurose** [comment]
All the test from 0.13.3  are passing for me with W7 IE10 VM (modern.ie). Are you sure this happens only with IE10, and did you check if the same code gets called in another browser?

**Comment by bsbeeks** [comment]
@taurose From what I can tell it only happens in IE10 on Windows 7. I've tested the same code in Firefox, Chrome, Safari, and IE11 and don't get the error mentioned above. I'll see if I can get more details on it.

**Comment by dipdipdip84** [comment]
I am having the same issue.

**Comment by steida** [comment]
Maybe related to http://babeljs.io/docs/advanced/caveats/#classes-10-and-below-

**Comment by coryvirok** [comment]
I'm seeing this as well. 

I was able to fix it by specifying the `contextTypes` attribute in my RouteHandler, described here: https://github.com/rackt/react-router/blob/v0.13.3/docs/guides/overview.md#dynamic-segments

react-router 0.13.3
Webpack + babel-loader
Google Chrome	43.0.2357.124 (Official Build) (64-bit)
Revision	d49eb48dfb64b379fdc61282ceca602acbc9065d-refs/branch-heads/2357@{#467}
OS	Mac OS X 
Blink	537.36 (@196519)
JavaScript	V8 4.3.61.27

**Comment by bsbeeks** [comment]
Thanks @coryvirok, I'll give that a shot.

**Comment by bsbeeks** [comment]
Specifying the `contextTypes` didn't work for me. But, using the approach of passing the params through the RouteHandlers as props DID resolve any issues with using the `getParams` method. Neither method fixed the errors I was seeing with `isActive()`. That method is returning the same errors that `getParams()` did.

**Comment by bsbeeks** [comment]
To summarize:

## getParams()
Defining `contextTypes` appeared to have fixed any issues in IE10 for @coryvirok. However, it did not work for me. Instead I had to implement the params through the RouteHandler props as outlined in the docs (https://github.com/rackt/react-router/blob/v0.13.3/docs/guides/overview.md#dynamic-segments):
```javascript
Router.run(routes, function (Handler, state) {
  var params = state.params;
  React.render(<Handler params={params}/>, document.body);
});

// and then pass the params down to every use of `<RouteHandler/>`
<RouteHandler {...this.props}/>

// Inbox ends up looking like this
var Inbox = React.createClass({
  render: function () {
    return (
      <div>
        <Toolbar/>
        <Messages/>
        <RouteHandler {...this.props}/>
      </div>
    );
  }
});

// and Message changes to:
var Message = React.createClass({
  render: function () {
    return (
      <div>{this.props.params.messageId}</div>
    );
  }
});
```


## isActive()
If you are using this method and need compatibility in IE10, you will need to implement a custom method to handle this. I decided to create a Router Utils that housed this method:
```javascript
isActive (pathParts) {
  const path = window.location.hash;
  const routes = path.split('/').filter(string => {
    return string.length && string !== '#';
  });

  const isActive = pathParts.filter(route => {
    return routes.indexOf(route) < 0;
  });

  return !isActive.length;
}
```
Though it's not the best fix, it did resolve any issues with IE10. The downside to this approach is you don't have access to the route names. Instead you have to target parts of the url. This isn't a big issue for me since my route names and paths are consistent. An added bonus to this approach is I can check if a child route belongs to a parent route by passing in the parent route path:
```javascript
// if my current path is /myparent/children/:id
// then within my children components I can run:
RouterUtils.isActive(['myparent']); // returns true
```

I haven't tested other methods that utilize `this.context.router`, but I'm assuming you'll run into similar issues in IE10.

**Comment by vn38minhtran** [comment]
I confirm issue. Please view my screencast https://youtu.be/7X-bEp_M-BA. @gaearon @mjackson @ryanflorence. Thanks!

**Comment by leonid-shevtsov** [comment]
I want to add that this is caused by Babel classes inheritance not entirely supported in IE<11, and can be fixed by adding an additional Babel transformer.

https://babeljs.io/docs/advanced/caveats/#classes-10-and-below-
