### ISSUE TITLE
componentDidMount not called when expected. bug or feature?

### ISSUE THREAD

**Issue by stopachka** [rackt/react-router#1284]
````
  render() {
     return <RouteHandler />
  }
```

```
// Handler for path A
  ..
  componentDidMount() { console.log("mounted A"); }

// handler for path B

  ..
  componentDidMount() { console.log("mounted B"); }

```

Now, if we 

1) Go to path A -> console.log happens
2) Go to path B -> console.log happens
3) Go back to path A -> *no console.log happens*

is this intended?

**Comment by stopachka** [comment]
oof, nevermind -- false alarm

**Comment by beeant** [comment]
this is actually happening to me. what makes you think it's a false alarm?

**Comment by stopachka** [comment]
I don't quite remember how I solved this -- but would take a look at your paths -- what do they look like, and which of them are not updating as you expect?

**Comment by beeant** [comment]
I found the problem. it was because I had <script> tag on my JSX template

**Comment by hozefaj** [comment]
I am facing the same issue in that `componentDidMount` is not getting called when coming from another route.
