### ISSUE TITLE
transitionTo with params

### ISSUE THREAD

**Issue by Akudrevatykh** [rackt/react-router#1285]
I am using "react-router": "^0.13.2" and "react": "^0.13.3"

I am trying to transition to a page and pass some parameters to it like this: `RouterContainer.get().transitionTo('/next', {id: 5}, {q: 3});`

Unfortunately in the component `this.props.params` returns `{}` while `this.props.query` returns `{q: 3}` as expected.

Am I missing something? How can I pass parameters to my component?

**Comment by Akudrevatykh** [comment]
Here is a fiddle https://jsfiddle.net/91e1xa5v/

**Comment by Akudrevatykh** [comment]
Here is a fiddle https://jsfiddle.net/47fkbow9/

**Comment by ppiekarczyk** [comment]
have you tried `this.getParams()`

**Comment by Akudrevatykh** [comment]
@ppiekarczyk it returns an empty object as well

**Comment by mjackson** [comment]
In order to interpolate params in the 0.13.x API your path needs to have a segment for that param to occupy. So, instead of using a path of `/next` use a path of `/next/:id`.

**Comment by Akudrevatykh** [comment]
@mjackson Thank you for you answer. 
So if I set my Route path to `/next/:id` then:
- `transitionTo('/next', {id: 5}, {q: 3});` doesn't work
- `transitionTo('/next/6', {id: 5}, {q: 3});` this.props.params returns `6` ignoring `{id: 5}`

Is this expected behaviour? Should I be appending params to the path in order to pass them to a component? Here is a modified fiddle https://jsfiddle.net/47fkbow9/1/

Also it would be great if you could update the documentation, since it doesn't mention this requirement:
http://rackt.github.io/react-router/#Navigation one of the Examples: `this.transitionTo('user', {id: 10}, {showAge: true});`

**Comment by Akudrevatykh** [comment]
Actually I found an answer to my question in the 1.0.0 beta documentation. transitionTo interface indeed will no longer take params as an argument:
`transitionTo(pathname, query, state)`

http://rackt.github.io/react-router/tags/v1.0.0-beta1.html#Router
