### ISSUE TITLE
how to get previous path using Link 

### ISSUE THREAD

**Issue by otarim** [rackt/react-router#1287]
sorry for my poor English..my question is,when i use `<Link />` to change current route into next route,how i can  get  previous path in the next route's handler? here is some code

	// route config 
	<Route handler={Route2} name="route2" path="route2" />

	// eg: current location is #/route1?key=value
	<Link to="route2">click to jump to route2</Link>

	// route2
	var Route2 = React.createClass({
		componentDidMount: function() {
			// how i can get previous path '#/route1?key=value'
		},
		render: function() {
			return (
				<div />
			)
		}
	})

thx ~ :-)

**Comment by ryanflorence** [comment]
we should probably add `location.referrer`, but right now there's no way to know this.

you could set up your own `hashchange` listener and store your own stack of urls.

**Comment by ryanflorence** [comment]
Can you explain your use-case?
