### ISSUE TITLE
transitionTo not changing the url

### ISSUE THREAD

**Issue by barbalex** [rackt/react-router#1298]
I am using transitionTo to transition after having set state when a node in a tree was clicked.
This works in two views.
But in two others it does not.
What happens is that the view that is getting called by the handler fires it's getInitialState. It is not shown though. And the URL never changes.
Although the URL does not change, the history seems to be changed, because the back butten goes through all the views/URL's that were not shown!

This is my router:

    import React from 'react'
    import Router from 'react-router'
    import Home from './components/home.js'
    import Objekt from './components/main/object/object.js'
    import FourOhFour from './components/main/fourOhFour.js'
    import Empty from './components/main/empty.js'
    import S1 from './components/menu/tree/s1.js'
    import S2 from './components/menu/tree/s2.js'
    import S3 from './components/menu/tree/s3.js'
    import S4 from './components/menu/tree/s4.js'

    const DefaultRoute = Router.DefaultRoute
    const NotFoundRoute = Router.NotFoundRoute
    const Route = Router.Route
    const RouteHandler = Router.RouteHandler

    export default function () {

      const routes = (
        <Route name='home' path='/' handler={Home}>
          <Route name='s1' path='/:s1' handler={S1}/>
          <Route name='s2' path='/:s1/:s2' handler={S2}/>
          <Route name='s3' path='/:s1/:s2/:s3' handler={S3}/>
          <Route name='s4' path='/:s1/:s2/:s3/:s4' handler={S4}/>
          <Route name='s5' path='/:s1/:s2/:s3/:s4/:s5' handler={Objekt}/>
          <RouteHandler/>
          <DefaultRoute handler={Empty}/>
          <NotFoundRoute handler={FourOhFour}/>
        </Route>
      )

      const router = Router.create({
        routes: routes,
        location: Router.HistoryLocation
      })

      router.run(function (Handler, state) {
        React.render(<Handler/>, document.body)
        // app.Actions.transition(state.params)
      })

      window.router = router
    }

This is the Home handler:

    import React from 'react'
    import Menu from './menu/menu.js'
    import FaviconImage from '../../img/aster_144.png'
    import Favicon from 'react-favicon'

    export default React.createClass({
      displayName: 'Home',

      render () {
        return (
          <div>
            <Favicon url={[FaviconImage]}/>
            <Menu/>
          </div>
        )
      }
    })

and this is the view where transitionTo does not work:

    import app from 'ampersand-app'
    import React from 'react'
    import { State, Navigation } from 'react-router'
    import { ListenerMixin } from 'reflux'
    import _ from 'lodash'
    import S3 from './s3.js'

    export default React.createClass({
      displayName: 'TreeLevel2',

      mixins: [ListenerMixin, State, Navigation],

      propTypes: {
        loading: React.PropTypes.bool,
        items: React.PropTypes.object,
        s1: React.PropTypes.string,
        s2: React.PropTypes.string,
        s3: React.PropTypes.string
      },

      getInitialState () {
        console.log('s2 getInitialState called')
        const params = this.getParams()
        return {
          loading: !window.faunaStore.loaded,
          items: window.faunaStore.getInitialState(),
          s1: params.s1,
          s2: params.s2,
          s3: params.s3
        }
      },

      componentDidMount () {
        const params = this.getParams()
        switch (params.s1) {
        case 'Fauna':
          this.listenTo(window.faunaStore, this.onStoreChange)
          // loadFaunaStore if necessary
          if (!window.faunaStore.loaded) app.Actions.loadFaunaStore()
          break
        }
      },

      onStoreChange (items) {
        this.setState({
          loading: false,
          items: items
        })
      },

      onClickNode (s3) {
        this.setState({s3: s3})
        const url = `/${this.state.s1}/${this.state.s2}/${s3}`
        window.router.transitionTo(url)
      },

      render () {
        let nodes
        const that = this
        const items = this.state.items
        const s2 = this.state.s2
        const s3 = this.state.s3

        // items nach S2 filtern (in Fauna: Klasse)
        const itemsWithS2 = _.pick(items, function (item) {
          if (item.Taxonomie && item.Taxonomie.Eigenschaften && item.Taxonomie.Eigenschaften.Klasse && item.Taxonomie.Eigenschaften.Klasse === s2) {
            return true
          }
        })

        nodes = _.chain(itemsWithS2)
          // make an object {ordnung1: num, ordnung2: num}
          .countBy(function (item) {
            if (item.Taxonomie.Eigenschaften.Ordnung) {
              return item.Taxonomie.Eigenschaften.Ordnung
            }
          })
          // convert to array of arrays so it can be sorted
          .pairs()
          .sortBy(function (pair) {
            return pair[0]
          })
          // map to needed elements
          // div arount Text is for interacting wich the li element
          .map(function (pair) {
            return (
              <li key={pair[0]} onClick={that.onClickNode.bind(that, pair[0])}>
                <div>{pair[0]} ({pair[1]})</div>
                {pair[0] === s3 ? <S3/> : null}
              </li>
            )
          })
          .value()

        return (
          <ul className='level2'>
            {nodes}
          </ul>
        )
      }
    })

**Comment by ryanflorence** [comment]
RouteHandlers don't belong inside of your route config, what are you hoping that does?

**Comment by barbalex** [comment]
noob alarm!

Thanks for pointing this out.

To be honest: that is not obvious for a complete react noob. It might help if the docs were a little more explicit. But let's not forget: Thanks a LOT for this great tool!

Anyway, I finally found the reason why transitionTo was not changing my url: The onClick handler is situated in a tree view. All the onClick handlers of parent LI elements were called to. After applying event.preventDefault() the issue is solved.
