### ISSUE TITLE
Changing path from a RefluxJS Store

### ISSUE THREAD

**Issue by sergelerner** [rackt/react-router#1300]
Hi, In my application I use RefluxJS, and one of my Stores need to figure out the path and than change it. Reflux lets you to use mixins within Sotres just like React Classes, so I've tried to add the Navigation Mixin - all the methods there.
Later in one of the Stores function I run `this.transitionTo("Foo");` but I get an error "Uncaught TypeError: Cannot read property 'router' of undefined".

Any Ideas how to work this?

**Comment by srph** [comment]
`this.transitionTo` is probably accessing the `router` property through contexts (`this.context.router`) which do not exists in RefluxJS stores.

**Comment by sergelerner** [comment]
@srph Any idea how can I change the path from the store ?

**Comment by ryanflorence** [comment]
I don't know anything about, but the `Navigation` mixin looks up things from `context`. Since this is a question and not an issue I'm closing, but feel free to post some more of your code and I can take a look.

**Comment by sergelerner** [comment]
I understand that using the `Navigation` mixin like this wont work because of the `context` as you said. Nevertheless I need help to figure out how one changes a path from a different javascript module... There must be a way after all : ) 

Here is an example of my Code:

```
// routes.js
//////////////////////////////////////////////////////////
var Router  = require('react-router');
var Route   = Router.Route; 

var App       = require('./app')
var Comp    = require('./components/comp');

var routes = (
	<Route path='/' handler={App}>		
		<Route name='Foo' path='/foo' handler={Comp}/>				
	</Route>
);

module.exports = routes;

// main.js
//////////////////////////////////////////////////////////
var React   = require('react');
var routes  = require('./Routes');

var appElement = document.createElement("div");

Router.run(routes, Router.HistoryLocation, function(Root, state) {
	Actions.pathChange({path: state.path});
	React.render(<Root params={state.params} query={state.query} />, appElement);
});

// comp.js
//////////////////////////////////////////////////////////
var React          = require("react");
var Reflux         = require("reflux");
var Actions        = require("../actions/actions.js");
var SomeStore  = require("../stores/some-store.js");

var Comp = React.createClass({

    render: function() {
        return (
        	<h1>Hello World</h1>	
        );
    }
});

module.exports = Comp;

// store.js
//////////////////////////////////////////////////////////
var SomeStore = Reflux.createStore({	

	onSomeAction: function() {
		// CHANGE ROUTER PATH HERE TO /foo
	}

});

module.exports = SomeStore;
```

Any help will be appreciated !!!
