### ISSUE TITLE
1.0.0 changes break context for everyone else

### ISSUE THREAD

**Issue by patrick-jones** [rackt/react-router#1301]
Given a route hierarchy like this (from the docs):

```js
React.render((
  <Router history={HashHistory}>
    <Route path="/" component={App}>
      <Route path="about" component={About}/>
      <Route path="inbox" component={Inbox}/>
    </Route>
  </Router>
), document.body);
```

Using the pre-1.0.0 method of `Router.run` and the `RouteHandler` tag, the `App` component could use the React context to provide context properties to `About` and `Inbox`.

In 1.0.0alpha2, the new way of injecting child route components as props means that `About` and `Inbox` are no longer considered children of `App` (as far as context goes). These two nested route components will look at `context` expecting to find the properties set by `App` (say, for example, the  [current material UI theme](http://material-ui.com/#/customization/themes)), and will instead find nothing but the `router` property set by the top-level `Router` component.

I understand on a technical level why this is happening, and I can probably even hack my way around it, but this strikes me as Very Bad:

- It makes using other libraries that assume the use of context (e.g., [Material UI](https://github.com/callemall/material-ui)) difficult.
- It severs the parent-child hierarchy of my own components, making it awkward for me to use context in my own components.
- In my mind, it breaks the principal of least surprise; doing something in react-router suddenly doesn't work the same way it would work in "ordinary" React.

**Comment by gaearon** [comment]
In React 0.14, context will switch to parent tree so `Inbox` will get `App`'s context.

Before 0.14, you should be able to put `Router` into some other component whose context every handler will get:

```js
class AppContainer {
  static childContextTypes = { ... }

  getChildContext() { ... }

  render() {
    return (
      <Router>
        <Route path="/" component={App}>
          <Route path="about" component={About}/>
          <Route path="inbox" component={Inbox}/>
        </Route>
      </Router>
    );;
  }
}
```

I don't think this is any more difficult than what we have now, and in fact it's slightly cleaner because context lives completely outside the router now. (And as I said, it will “just work” in 0.14.)

**Comment by patrick-jones** [comment]
That was the workaround I had in mind.  Unfortunately it only works if your have some global context that you want passed down to all descendants.  If you have a structure like this:

```js
<Router>
    <Route path="/" component={App}>
        <Route path="/a" component={A}>
            <Route path="/one" component={AOne} />
            <Route path="/two" component={ATwo} />
        </Route>
        <Route path="/b" component={B}>
            <Route path="/one" component={BOne} />
            <Route path="/two" component={BTwo} />
        </Route>
      </Router>
```

...and you want `A` to pass certain content down to `AOne` and `ATwo`, and you want `B` to pass a _different_ context to its child paths, this will not work.

Given that this _will_ work in React 0.14, there is no good reason to change it. But I do think it's worth documenting somewhere.

**Comment by ryanflorence** [comment]
I think this issue is probably documentation enough, since React itself still doesn't document context. Thanks :)
