### ISSUE TITLE
React Router Examples and the use of `component` ?

### ISSUE THREAD

**Issue by sergelerner** [rackt/react-router#1302]
I can't seem to find anything in the documentation regarding the use of the `component` attribute instead of the `handler`... 

Code from the sidebar example: 

```javascript
var App = React.createClass({
  render() {
    return (
      <div>
        <div className="Sidebar">
          {this.props.sidebar || <IndexSidebar/>}
        </div>
        <div className="Content">
          {this.props.content || <Index/>}
        </div>
      </div>
    );
  }
});

React.render((
  <Router history={HashHistory}>
    <Route path="/" component={App}>
      <Route path="category/:category" components={{content: Category, sidebar: CategorySidebar}}>
        <Route path=":item" component={Item}/>
      </Route>
    </Route>
  </Router>
), document.getElementById('example'));
```

All of the examples follow the same pattern, few key notes:

1. extended use of the  `{this.props.children}` instead of `<RouteHandler/>`.
2. multiple components with `components={{content: Category, sidebar: CategorySidebar}}`

What is considered to be best practice in light of those examples? 
What are the differences?

**Comment by gaearon** [comment]
You're looking at `master` which is 1.0 (currently released as alpha).
The last officially released version is 0.13, so the docs match it.

See 0.13 examples instead: https://github.com/rackt/react-router/tree/v0.13.3/examples

**Comment by sergelerner** [comment]
Off course!  Brilliant Answer : ) Anyone knows how long until this alpha becomes stable ?

**Comment by gaearon** [comment]
A week or so. (I keep giving this answer...)

**Comment by sergelerner** [comment]
Thanks!
