### ISSUE TITLE
Load a number of components on a given path ?

### ISSUE THREAD

**Issue by sergelerner** [rackt/react-router#1303]
Is there a way for me to load any given number of different components for a certain path?
Something in the lines of:
```
<Route name="Foo" path='/foo' handler={comp1 comp2 comp3}/>
```
Or should I always create Views with Components and then load the Views? 
With Views it feels a little bit redundant sometimes. Aspecially if a certain Components moves to a different path - than I need to make the change also in the Views...

I guess Im looking both for a correct approach and a way to load multiple Comps.

Thanx!

**Comment by mjackson** [comment]
Yes, in the 1.0 API (current master) you can specify an object of components to load.

```js
<Route component={App}/>
  <Route ... components={{ header: Header, sidebar: Sidebar }}/>
</Route>
```

Then, in `App#render` use `this.props.header`/`this.props.sidebar` to access the element created using that component class.
