### ISSUE TITLE
Mixins should be suffixed with 'Mixin'

### ISSUE THREAD

**Issue by stevenpetryk** [rackt/react-router#1309]
React's own mixins follow the naming convention `SomeSillyMixin`, but the two mixins in this project, `Navigation` and `State`, lack the `Mixin` suffix.

**Comment by mjackson** [comment]
AFAICT React only actually ships one mixin as part of their public API, `PureRenderMixin`. I don't believe this actually qualifies as a naming convention since there's only one instance of it, but I'd be open to discussing it further if more examples emerge in the future.

**Comment by stevenpetryk** [comment]
Don't forget `LinkedStateMixin`! Thanks for the consideration.
