### ISSUE TITLE
Nested routes should be rendered inside parent's RouteHandler if inside parent RouteHandler isn't used. 

### ISSUE THREAD

**Issue by deser** [rackt/react-router#1310]
Imagine such kind of routes:

```jsx
<Route name='viewport' path='/' handler={require(`${pagePath}/Viewport.react`)}>
    <Route name='screen' path='/screen/:itemId' handler={require(`${pagePath}/ScreenDesigner.react`)} >
        <Route name='grid_popup' path='grid_popup/:gridId' handler=  {require(`${pagePath}/GridPopupDesigner.react`)} />
     </Route>
 </Route>
```
Let's say I have viewport inside which there is RouteHanlder:
```jsx
<div>
                <Header />
                <div className='view md-padding'>
                    <RouteHandler />
                </div>
            </div>
```

And I want child page 'screen/<screen_id>/grid_popup/<group_id>' to be rendered instead of parent page 'screen/<screen_id>' inside RouteHandler of Viewport.
How can I do that? 
Thanks in advance :)

**Comment by deser** [comment]
It seems that I found solution:
path='/parent1/child1/:itemId/child2/:itemId/child3/:itemId/child4/:itemId' but it looks ugly.

**Comment by ryanflorence** [comment]
if you'd like some more help, make a demo we can look at, but the nesting is working as designed, sorry you're having trouble.
