### ISSUE TITLE
@1.0.0-beta1: history.location invariant failure (BrowserHistory)

### ISSUE THREAD

**Issue by bwhitty** [rackt/react-router#1313]
In my main file I have
```js
import {Router, Route, Link} from "react-router";
import {BrowserHistory} from 'react-router/lib/BrowserHistory';

...

React.render(
	<Router history={BrowserHistory}>
		<Route path="x/y/z.php/channel/:channelId" component={App} />
	</Router>,
	document.getElementById("id")
);
```
which is then built using Browserify.

When I run this in the browser using the react-router UMD library supplied in your Bower build (and React 0.13), I get the following: ```Warning: Failed propType: Invalid prop `history` supplied to `Router`, expected instance of `History````.

I can see in the `Router.componentWillMount` at https://github.com/rackt/react-router/blob/master/modules/Router.js#L228 that `history.location` is passed to `setState`, but in my instance that property is undefined, and an invariant fails: ```Uncaught Error: Invariant Violation: A <Router> needs a valid Location```.

Any idea of what could be causing this?

**Comment by taurose** [comment]
I believe you have to write `import BrowserHistory from 'react-router/lib/BrowserHistory';` without the braces.

**Comment by bwhitty** [comment]
Ahh I believe you are right... rookie mistake here. I'll reopen if this doesn't solve the issue. Thanks!

**Comment by dominataa** [comment]
I was having this exact problem. Turns out the problem was `instanceof` checks as I had managed to get react-router in my app and vendor bundles and the checks where failing... Not easy to realise.

**Comment by hanai** [comment]
I have this problem too
