### ISSUE TITLE
Specifying a tag name for Link

### ISSUE THREAD

**Issue by jdmaurer** [rackt/react-router#1314]
I'd assume this would be basic functionality, but I can't seem to find a solution. Is there a way to specify the tag used for Link? Something like ```<Link tagName="li" to="..." />```? I don't always want to use an "a" tag for the generated links. I understand there are workarounds, but I don't want to go to the trouble of creating my own mixin, messing with state, etc. just to get this basic functionality.

**Comment by mjackson** [comment]
`<Link>` is a router-aware `<a>` tag. It's accessible, responds to things like ctrl+click, etc. It is **the** element for navigating around the web. If we allowed you to put whatever tag you want in there, it would no longer be accessible, and we're not interested in helping you create sites that are not accessible. :)

**Comment by jdmaurer** [comment]
Yeah, you're right... I guess I've never bothered to nest ```<a>``` tags inside other tags when it was just for internal navigation (such as tabs). But I really should use ```<a>``` tags for what they're meant to be used for. Thanks for the quick response!
