### ISSUE TITLE
Default route in 1.0.0

### ISSUE THREAD

**Issue by thesbros** [rackt/react-router#1315]
How do you set a route as the default route in 1.0.0-beta1?

**Comment by freshdried** [comment]
There is no more default route. You can emulate one like this, however:

```javascript
...
render() {
    return <div>
        {this.props.children || "This is the default text"}
    </div>
}
...
```

**Comment by thesbros** [comment]
Yes but my default route is very complicated, so it would be pretty unorganized to put it there.

**Comment by srph** [comment]
Like? `{this.props.children || <MyComponent />}` won't work?

**Comment by thesbros** [comment]
Yep that works. Don't know why I didn't think of that..

**Comment by omerts** [comment]
Personally I find this to be a bad solution. It is close to what react-router is coming to solve, which is using a switch. Using an || is almost like a switch.

**Comment by omerts** [comment]
ok just came across the right solution, in case anyone gets here (taken from one of the examples):
```javascript
 <Router history={history}>
    <Route component={App}>
      <Route path="/" component={Index}/>
      <Route path="contact/new" component={NewContact}/>
      <Route path="contact/:id" component={Contact}/>
      <Route path="*" component={NotFound}/>
    </Route>
  </Router>
```

**Comment by thesbros** [comment]
Nice, that's a cleaner way of doing it.
