### ISSUE TITLE
babel-loader: unknown-plugin 'object-assign' on 1.0.0-beta1

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#1318]
Using webpack with the babel-loader.

Seems like its trying to find the plugin thats in the babelrc file within the react-router project.

possible solution: ignore babelrc file in npmignore.

removing the babelrc file within react-router did fix this issue.

![1__tmux](https://cloud.githubusercontent.com/assets/6775919/8176229/f740c132-13ac-11e5-8932-fb06940f1fca.png)

**Comment by gaearon** [comment]
You should scope `babel-loader` to only process your application's files. You can do that with `include` (or `exclude`) option in your Webpack config.

**Comment by gaearon** [comment]
Example:

```js
    loaders: [{
      test: /\.jsx?$/,
      loaders: ['babel'],
      include: path.join(__dirname, 'src')
    }]
```

**Comment by ryanflorence** [comment]
Hmm ... did we accidentally require people to have `Object.assign` polyfilled for their apps?

**Comment by BerkeleyTrue** [comment]
@gaearon Thanks! I was not aware of that. Switching over from Browserify. Is that the standard practice for all loaders?

@ryanflorence It is indeed being polyfilled in a couple of files.

Should I close the PR as well?

**Comment by ryanflorence** [comment]
when you `require('react-router')` it should be looking in `lib` not modules, where Object.assign is polyfilled. let me know if you can identify it working differently.

**Comment by BerkeleyTrue** [comment]
its looking at the right directory. The issue is with babel-loader for webpack recursively picking up babelrc files. It then sees that react-router's babelrc requires object-assign plugin which isn't installed because it is a dev dependency. I implemented @gaearon suggestions but haven't tested it out against a fresh install. I removed the file in my node_modules/react-router directory.

**Comment by ryanflorence** [comment]
We should npm ignore it

**Comment by BerkeleyTrue** [comment]
Some very handsome gentleman and scholar went ahead and created a PR to do that very thing: #1320

**Comment by ryanflorence** [comment]
Indubitably!
