### ISSUE TITLE
'warning' is not defined in beta1 build of Route component.

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#1319]
`warning` is never imported in the Route component. Seems like this one snuck through in the beta1 release.
![developer_tools_-_http___localhost_3333_](https://cloud.githubusercontent.com/assets/6775919/8176769/97589d70-13b2-11e5-8a1e-e705fe281c22.png)

**Comment by ryanflorence** [comment]
thanks, its there now though https://github.com/rackt/react-router/commit/4f4e991774a076a865ceb321f28ab70b3f033bfd
