### ISSUE TITLE
context.router.transitionTo report: Invariant Violation: Missing "xx" parameter

### ISSUE THREAD

**Issue by ustccjw** [rackt/react-router#1321]
`this.context.router.transitionTo('/yuheng/stat/so:01')`   is ok, but  `this.context.router.transitionTo('/yuheng/stat/so:DX')` is error,  Invariant Violation: Missing "DX" parameter

I use encodeURIComponent consume 'so:DX', then is ok. So, it's a feature or bug ?

**Comment by mjackson** [comment]
@ustccjw I added a test that passes, so I was unable to reproduce this issue. If you can get the test to fail, please do. It would help us nail down the cause of the bug, if there is one.

**Comment by ustccjw** [comment]
@mjackson is v0.13.3 ?
