### ISSUE TITLE
Object.defineProperty IE8 compatibility issue 1.0.0-beta1

### ISSUE THREAD

**Issue by cateland** [rackt/react-router#1325]
Hello

I noticed that in the packaged version of react-router 1.0.0-beta1, there is still an 
```javascript
	Object.defineProperty(exports, 'createRoutesFromReactChildren', {
	  enumerable: true,
	  get: function get() {
	    return _RouteUtils.createRoutesFromReactChildren;
	  }
	});
```

wich cause IE8 to loose his mind since Object.defineProperty can only be used on DOM object and cannot be polyfilled.

It look like its generated by babel, https://babeljs.io/docs/advanced/loose/

i mitigated this problem on my own lib by using this configuration 
```javascript
    {
      test: /\.jsx$/,
      exclude: /node_modules/,
      loader: 'babel-loader',
      query: {
        loose: true
      }
    }
```

**Comment by ryanflorence** [comment]
thanks @cateland
