### ISSUE TITLE
Context problems with react-router, webpack

### ISSUE THREAD

**Issue by prayerslayer** [rackt/react-router#1326]
Hi there!

I spent the whole day investigating an issue I had with `react-router`. `Link`s in unit tests just could not receive a router via mocked context. Along the way I was suspecting `TestUtils.renderIntoDocument` to be the culprit but ultimately concluded that it has to be `webpack`.

Because it would take WAY too long to explain my setup I [made a repo](https://github.com/prayerslayer/react-router-test) that reproduces the problem.

* Run `npm run-script mocha` and everything works. This script uses mocha with babel compiler directly.
* Run `npm run-script webpack` and the tests break because `Link` has no context. But note that the component where it's contained in—the owner *and* parent, to my understanding—**has** a mocked router in context.

This is the error:

~~~
Warning: Failed Context Types: Required context `router` was not specified in `Link`.
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function () {}`) for key (router) while mounting Link (see: http://fb.me/react-context-by-parent)
TypeError: Cannot read property 'makeHref' of undefined
    at Link.getHref (webpack:///./~/react-router/lib/components/Link.js?:90:33)
    at Link.render (webpack:///./~/react-router/lib/components/Link.js?:115:20)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/npiccolotto/Projects/prayerslayer/react-router-test/node_modules/react/lib/ReactCompositeComponent.js:789:34)
...
~~~

Why am I opening an issue here? I figured you guys have probably more knowledge about React contexts than the webpack maintainer(s).

Anyways, is this something you know the reason and hopefully also a solution for? Because I’m completely stuck.

Thanks very much!

**Comment by prayerslayer** [comment]
Okay, after another two hours of poking around with the webpack configuration I finally figured it out.

The solution is to externalize `react` and `react-router` in global variables:

**webpack.config.js**
~~~
externals: {
  react: 'var React',
  'react-router': 'var ReactRouter'
}
~~~

**mocha-globals.js**
~~~
global.React = require('react/addons');
global.ReactRouter = require('react-router');
~~~

Maybe you can explain what’s going on here?

**Comment by taurose** [comment]
I'd say the problem is that you were loading two different instances of react and react-router: one got bundled by webpack and one was imported normally from `node_modules` by `mocha-global.js`. With your solution, you made `mocha-globals.js` share its instances with the webpack bundle.

**Comment by mjackson** [comment]
It sounds like you're loading two different instances of both React and React Router, as @taurose suggests. I'm sorry, but we don't have time to look into your build and fix it for you.

**Comment by prayerslayer** [comment]
@taurose Thanks, that actually makes sense after some sleep. I didn’t think of it because my tests worked before using `react-router`. It’s sufficient to not bundle `react` alone.
