### ISSUE TITLE
Cannot find module 'react-router/lib/HashHistory'

### ISSUE THREAD

**Issue by shangsunset** [rackt/react-router#1327]
Hi,

I installed react-router via `npm install react-router`, but when i tried: `import HashHistory from 'react-router/lib/HashHistory';` I got a error said: Browserify Failed!: Cannot find module 'react-router/lib/HashHistory'.

I looked in the node_modules/raect-router/lib/ dir, and couldnt find HashHistory.js nor BrowserHistory.js. What am i missing here? Thanks.

**Comment by ryanflorence** [comment]
Docs on master are for code on master, look at the docs for v0.13.3
