### ISSUE TITLE
Export Location and BrowserHistory etc from index

### ISSUE THREAD

**Issue by dominataa** [rackt/react-router#1331]
`import foo from 'react-router/lib/foo` is causing pain with browserify.
If you are using an external vendor bundle making `react-router` external, its still getting included in the main bundle I guess due to the `lib/foo` import. Making explicitly all of the `react-router/lib/*` imports external also does not work. You could say this is an issue with browserify but it feels a bit non standard to have to do this. And a problem I've not run into before.
The issue is all of your instanceof checks then fail and its really hard to track down what's going wrong.

#1313

**Comment by mjackson** [comment]
The history implementations are the one part of our public API that not everyone will use. For example, if you're using `BrowserHistory` but we also `export HashHistory` from index.js then your bundle will always contain `HashHistory`, despite the fact that you'll never use it.

I'm just trying to keep the bundle size as small as possible.

**Comment by dominataa** [comment]
OK seems like sound enough logic. I've managed to solve the browserify issue. Not sure what I was doing before but requiring `react-router/lib/Location` etc into my vendor bundle does work. I also had to disable `fullpaths` in browserify for some reason.
I wouldn't be surprised if others run into this issue in the future. Maybe worth adding a note into the docs about this `instanceof` gotcha.

**Comment by insin** [comment]
Should the various history implementations be bundled and exported for the UMD/global build? It won't be usable otherwise.

**Comment by i4got10** [comment]
Faced the same problem. If mark ```react-router``` as external in ```browserify```, ```react-router/lib/BrowserHistory``` will be bundled with application code and this error occurs

    Warning: Failed propType: Invalid prop `history` supplied to `Router`, expected instance of `History`.  Check the render method of `Root`.
