### ISSUE TITLE
Error: A <Router> needs a valid Location 

### ISSUE THREAD

**Issue by sergelerner** [rackt/react-router#1332]
Decided to try 1.0 and The following code throws an error:
**"Uncaught Error: Invariant Violation: A `<Router>` needs a valid Location"**
```
var ReactRouter    = require('react-router');
var Router         = ReactRouter.Router;
var Route          = ReactRouter.Route;
var HashHistory    = require('react-router/lib/HashHistory');

var App            = require('./components/app');

React.render((
  <Router history={HashHistory}>
    <Route path="/" component={App}>
      
    </Route>
  </Router>
), document.getElementById('main'));
```

**Comment by mjackson** [comment]
@sergelerner Are you running from master or from the npm build? If you're running `1.0.0-beta1` you should be fine. If master, [you need to use `new HashHistory`](https://github.com/rackt/react-router/pull/1323) instead of just using the `HashHistory` object directly.

**Comment by mjackson** [comment]
Oh, wait. I think I misspoke :P 

If you're using CommonJS in version beta1, you need to do

```js
var HashHistory = require('react-router/lib/HashHistory').default;
```

In the final version you'll do

```js
var HashHistory = require('react-router/lib/HashHistory');

React.render((
  <Router history={new HashHistory}>
    // ...
  </Router>
), document.getElementById('main'));
```

That was the reason for #1323 :)

**Comment by sergelerner** [comment]
@mjackson thanks 4 the quick reply and the later catch! And yes I am using npm. I assume the upgrade guide will be released after the version becomes stable ?

**Comment by mjackson** [comment]
@sergelerner Ya, it's a bit tricky since we're switching to ES6 modules in this release as well.

**Comment by jjvattamattom** [comment]
I use gulp, browserify and npm (with ES5 of course) and I ran in circles before finding this. This is what worked for me:

```javascript
var HashHistory = require('react-router/lib/HashHistory').default
```
Although as a student of Udemy's 'Build Web Apps with React JS and Flux', I was assured this works:

```javascript
var HashHistory = require('react-router/lib/hashhistory')
```

And the overview in Github(to translate the ES6): 

```javascript
var HashHistory = require('react-router/lib/HashHistory')
```

I use 1.0.0-beta2. I wish you had a self-contained example in ES5. This would be helpful to JS newbs like me and increase adoption of your awesome library.

**Comment by pandeiro** [comment]
I'd just like to :+1: this. For apps requiring IE8, react-router 0.13.3 is not usable (see #1040) so using 1.0.0-beta3 is an immediate need.

I've hit the error mentioned in this issue using the JSX syntax, but really I'd like to maintain what worked (outside IE8) with 0.13.3:

```
Router.run(routes, function (Handler, state) {
  React.render(<Handler routerState={state}/>, container);
});
```

Unfortunately I cannot find anywhere documenting how to do that.

**Comment by marcus** [comment]
I'm using webpack with 1.0.0-beta3 and following this example: https://github.com/quangbuule/redux-example/tree/redux%40v1.0.0-rc but have been banging my head on this for too long.  This seems like about the most simple example, but it is not working:
```
import React from 'react';
import { Router, Route } from 'react-router';
import routes from '../routes';
import History from 'react-router/lib/BrowserHistory';
import HomePageContainer from '../containers/HomePageContainer'

class AppRouter extends React.Component {
  render() {
    return (
      <Router history={new History}>
        <Route component={HomePageContainer} path="/" />
      </Router>
    );
  }
}

export default AppRouter;
```
This continually gives me the error:
```
Warning: Failed propType: Invalid prop `history` supplied to `Router`, expected instance of `History`. Check the render method of `AppRouter`.
... node_modules/react-router/node_modules/invari…:44 Uncaught Error: Invariant Violation: A <Router> needs a valid Location
```
When I log the instance, it's an instanceof History and looks fine. Any suggestions are much appreciated.
