### ISSUE TITLE
Default Routes in 1.0.0-beta1

### ISSUE THREAD

**Issue by haustraliaer** [rackt/react-router#1333]
I've been playing with the beta and trying to find a way of reproducing the behaviour of `<DefaultRoute />`'s. Ryan mentioned briefly in the Reactiflux slack that `<Route component={handler} indexComponent={defaultHandler} />` was what I needed...

But I can't seem to figure out how to use it, or know if it's even implemented yet.

In any case to be clear, the behaviour I'm looking for is as follows...

Given something like:

```js
const App = React.createClass({
  render() {
    return (
      <div className="App">
        <SomeAppWideLayout /> {/* eg a banner or something */}
       {this.props.children}
      </div>
    )
  }
});

React.render((
  <Router history={HashHistory}>
    <Route path="/" component={App} indexComponent={DefaultView}>
      <Route path='/eg1' component={View1} />
      <Route path='/eg2' component={View2} />
    </Route>
  </Router>
), document.body)
```

- If the user navigates to `/` then I want the App to load `<DefaultView />` into `{this.props.children}`. 
- If they navigate to any of the other routes (`/eg1`, or `/eg2`) then it should be replaced by `<View1 />`, or `<View2 />`.

Currently this behaves as expected in `0.13.3` with the `<DefaultRoute />` sitting nested under `/`. Is this something you'll be carrying across?

**Comment by ryanflorence** [comment]
default/index routes *might actually* completely disappear with our new matching algorithm, we realized (last night on the subway to the airport) that aren't necessary:

Paths have a lot more meaning now and matching is more predictable. If you omit a path, we search the children for a match, so `DefaultRoute` is no longer a concept, you simply omit the path from the parent wrapper and put it on the child, and now its a child just like all of its siblings. Not a different concept anymore, and super simple!

(Kind of unintuitive at first for people who have been using the router before though)

```js
<Router>
  <Route component={App}>
    <Route path="/" component={DefaultView}/>
    <Route path="/eg1" component={View1}/>
    {/* ... */}
  </Route>
</Router>
```

**Comment by haustraliaer** [comment]
Ah fantastic, thanks for all the hard work - can't wait for a release!

**Comment by frankwallis** [comment]
I am seeing an issue with the example above, related to links:

```
<ul className="nav-site">
  <li key="home">
    <Link to="/">Home</Link>
  </li>
  <li key="eg1">
    <Link to="/eg1">Example1</Link>
  </li>
</ul>
```

When I navigate to route /eg1 then both links are marked as 'active'.
