### ISSUE TITLE
Server-side rendering - Warning: You should not use a static location in a DOM environment because the router will not be kept in sync with the current URL

### ISSUE THREAD

**Issue by Nic128** [rackt/react-router#1335]
From the docs:
```javascript
// Server rendering
// callback is called once, immediately.
Router.run(routes, '/some/path', callback);
```

I try to to run it through a middleware:
```javascript
app.use(function(req, res, next) {
  Router.run(routes, req.url, function(Handler, state) {});
});
```

This warning always happens each page refresh on node's side:

```javascript
Warning: You should not use a static location in a DOM environment because the router will not be kept in sync with the current URL
```

If I am following the docs, what's wrong with my implementation? 

If I look at this example, my implementation is similar: https://github.com/rackt/react-router-mega-demo/blob/master/app/server.js 

What could be the problem? Previous ticket with jest. #1106

**Comment by mjackson** [comment]
It sounds like your node implementation is running in a DOM environment?

**Comment by Nic128** [comment]
You are right. I had a jsdom setup lying around for no reason. Deleted it. Fixed the problem.

Thanks
