### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by cve** [rackt/react-router#1337]
Hi, 

I want to try out examples, so I clone a repo and try to npm install but the result is:

![react-router-npm-install-problem](https://cloud.githubusercontent.com/assets/594384/8219096/f3b43ebc-1547-11e5-9e81-85b0195ddaed.png)

**Comment by ryanflorence** [comment]
that's strange, the install works fine for me, and the `build.sh` script is pointing to the right files.

have you ever used `sudo npm install` before?

If so, then some of your files might be owned by root and so now when you `npm install` in react router you don't have permission. If so, `rm -rf` your node_modules and your global node_modules, and never use sudo again.

**Comment by ryanflorence** [comment]
oh man, such a shame we didn't take advantage of the ticket number on this for the 1.0 release D:

**Comment by mjackson** [comment]
@cve It sounds like an issue with your environment. If I were you I'd:

```
$ rm -rf ~/.npm
$ cd ~/www/react-router
$ rm -rf node_modules
$ npm install
```

That will clear any locally cached npm packages and install everything from scratch.

**Comment by cve** [comment]
It helped, thanks guys :)
