### ISSUE TITLE
Nested UI on 0.13.3

### ISSUE THREAD

**Issue by SohumB** [rackt/react-router#1340]
This is my router:

```jsx
<Route handler={App}>
  <Route name="org" handler={Org} path="org">
    <Route name="org.terminal" handler={Terminal} path="terminal" />
  </Route>
</Route>
```

When I go to the path `/org/terminal`, only the `Org` component seems to be rendered. The render function of the `Terminal` component doesn't even get called.

It's clear to me that I must be missing something, but it's less clear to me what it is. 

Thanks!

**Comment by message** [comment]
Do you have `RouteHandler` in `Org` component where `Terminal` will be rendered?

**Comment by SohumB** [comment]
No; I thought the `<RouteHandler />` exists in the top level component, so `App` here.

And I just tried adding it to `Org`, and no, it doesn't help.

**Comment by ryanflorence** [comment]
`App` needs to render a `RouteHandler` and `Org` does too.

**Comment by SohumB** [comment]
If that's the case, this is at least a documentation bug, as nothing in the documentation suggests that.

I just tried it again, and my apologies; that does work; I'd mistested the behaviour last night. Thanks for the help!
