### ISSUE TITLE
Question: intercept all makeHref and href in Link components?

### ISSUE THREAD

**Issue by ericfong** [rackt/react-router#1341]
We are use ```Custom Location``` to handle routing between subdomains

In order to do one to one mapping, we want to intercept all href that output from ```makeHref``` or ```Link``` components

Any way to do that?

**Comment by dominataa** [comment]
I was going to suggest just wrapping the `makePath` function, this works but it wont work for the initial render.

```
let router = React.render(<Router />);
let makePath = router.makePath;
router.makePath = function (pathname, query) {
  return makePath(pathname, query); // or whatever you like
}
```

You would need to wrap the function on the component prototype to get the initial render calls, but it seems that the Router component is created with `React.createClass` which has a closure around the original method and you cant change it.

**Comment by ryanflorence** [comment]
Make your own Link?

**Comment by ericfong** [comment]
OK. wrap the makePath is good.

Just want to check, do we have any standard way to do it. 

Thanks
