### ISSUE TITLE
react-router's {this.props.children} seems disabled its original context.

### ISSUE THREAD

**Issue by ustccjw** [rackt/react-router#1343]
https://github.com/gaearon/redux/issues/136

**Comment by ustccjw** [comment]
I use react-router v1.0-beta2, I found when I use {this.props.children} to use 'component of redux', @connect, then will report error: Failed Context Types: Required context 'redux' was not specified in 'Connector'. Check the render method of 'Connector(DashboardApp)'

It seems react-router disabled the 'redux' context, so what should I do ?

**Comment by ryanflorence** [comment]
@gaearon has the solution on the redux issue
