### ISSUE TITLE
Documentation inaccurate for TestLocation 

### ISSUE THREAD

**Issue by gregbenner** [rackt/react-router#1347]
I know this component is under construction but it mentions to check the tests in the main repo.
There are none, so maybe the wording could be changed to reflect that. http://rackt.github.io/react-router/#TestLocation

**Comment by ryanflorence** [comment]
we now have a `MemoryLocation` on master.

**Comment by gregbenner** [comment]
Well the bug is wrong documentation... as it points to something that doesn't exist it's worse then having no documentation at all.

"Useful for testing your app. Check out the tests in the git repo to see how its used (more docs soon? PRs welcome after you figure it out!)"
