### ISSUE TITLE
1.0.0-beta - Histories no longer being exported or placed in lib/.

### ISSUE THREAD

**Issue by BenjaminMalley** [rackt/react-router#1348]
Forgive me if I'm missing something, but I cannot get the current beta examples to run because the various history implementations (```BrowserHistory```, etc.) are no longer making it into ```lib/```. It looks like they were removed from top-level exports as of this commit, https://github.com/rackt/react-router/commit/c80d865453a66d08277273568b148234067253d6 , but the current build script doesn't pack them back into lib. Is this expected? Am I not supposed to be using them after all?

**Comment by ryanflorence** [comment]
they should be in lib, you just have to call them with `new` now.

**Comment by BenjaminMalley** [comment]
As far as I can tell, it really does not contain them. I am specifying 1.0.0-beta1 as a dependency, like so  ```"react-router": "git://github.com/rackt/react-router.git#v1.0.0-beta1" ```. The resulting ```lib/``` looks like:
```
lgml-bmalley:drake bmalley$ tree node_modules/react-router/lib/                                                                                                                                           
node_modules/react-router/lib/
└── umd
    ├── ReactRouter.js
    └── ReactRouter.min.js
```

Importing 'react-router' a la the README examples fails, I think because package.json points to ```lib/index.js```, which doesn't exist. I can fix that, but none of the ```BrowserHistory```, ```HashHistory``` stuff appears to be in there at all. I am going to assume that I'm missing something obvious here and am throwing myself at your mercy to show me what it is.

Thanks!

**Comment by gaearon** [comment]
@BenjaminMalley I'm not sure RR really supports installing from git, can you using `react-router@alpha` NPM tag instead?

**Comment by gaearon** [comment]
Oh, I meant `react-router@beta`, whoops.

**Comment by BenjaminMalley** [comment]
I see, thanks!
