### ISSUE TITLE
Recommended Branch for Production Use

### ISSUE THREAD

**Issue by AlanBreck** [rackt/react-router#1350]
Hi there,

Is it safe to assume that since 0.13.3 is the latest version on npm that 0.13.3 is the wisest release to use in a production environment?

**Comment by gaearon** [comment]
0.13 is more stable at the moment but I'd suggest giving 1.0 beta a try. It's going to be out really soon and it's somewhat different (and much more powerful).

**Comment by AlanBreck** [comment]
Will the stable release of 1.0 be very different from the beta, or simply working out bugs? How soon do you expect it to be out?

**Comment by mjackson** [comment]
@AlanBreck 1.0 stable will ship within the next few weeks. The `beta2` version is already fairly stable.

**Comment by mjackson** [comment]
Also, in the future please ask questions like this in the #react-router channel on [reactiflux](http://www.reactiflux.com) so we can keep GH issues clear for actual bugs and feature requests. Thanks! :)

**Comment by mjackson** [comment]
Also, in the future please ask questions like this in the #react-router channel on [reactiflux](http://www.reactiflux.com) so we can keep GH issues clear for actual bugs and feature requests. Thanks! :)

**Comment by AlanBreck** [comment]
Thank you both so much for your answers! I will definitely ask future questions like this in the Slack channel (sorry for cluttering this feed up).
