### ISSUE TITLE
add `location.referrer`

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#1353]
then anybody that gets a `location` object also knows the previous location

**Comment by jvanaert** [comment]
+1

**Comment by canfie1d** [comment]
+1

**Comment by ryanflorence** [comment]
we have ways to know this throughout the api now, most notably route components get `location` as a prop, so it can know in `componentDidUpdate` if its different.

**Comment by Noitidart** [comment]
Hi there, is there a referer solution in v4?

I have this:

```
class Routes extends Component {
    referrer = document.referrer;
    componentWillUpdate(nextProps) {
        let { location } = this.props;
        let { nextLocation } = nextProps;

        let url = location.pathname + location.search;
        let nextUrl = nextLocation.pathname + nextLocation.search;

        if (url != nextUrl) {
            this.referrer = url;
        }
    }
    render() {
        let { location } = this.props;

        let { referrer } = this; // how to get this passed to component without render={()=><Blah referrer={referrer}} />

        return (
            <CSSTransitionGroup component="div" {...getTrans('pagefade')}>
                <Switch key={location.key} location={location}>
                    <Route exact path='/blah' component={Blah} key='blah' />
                    <Route exact path='/foo' component={Foo} key='foo' />
                </Switch>
            </CSSTransitionGroup>
        )
    }
}
```

I am trying to get `referrer` to my `Blah` and `Foo` components without using `render={()=><Blah referrer={referrer} />`, is this possible?

**Comment by ryanflorence** [comment]
That's exactly what the "render" prop is for 😋

**Comment by Noitidart** [comment]
Oooh thanks @ryanflorence I did some studying and I was forcing myself to use `component` because I thought it was more performant. But I think I was wrong, I'm still not totally sure about the performance differences between the two, but I think it's ok from the studying I did.
