### ISSUE TITLE
Fix scroll management test on TravisCI

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1357]
[This scroll management test](https://github.com/rackt/react-router/blob/5d674c9515aa628b644c223b2e3f43bb28ac24bc/modules/__tests__/scrollManagement-test.js#L42-L78) fails on Travis for some reason, but passes on my local machine. Anybody know why? Should we just skip it on CI?

**Comment by ryanflorence** [comment]
Yeah skip until we figure it out

**Comment by mjackson** [comment]
This is fixed in #1363
