### ISSUE TITLE
Track session history length

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1358]
In order to provide a reliable `canGo(n)` implementation in browsers, we need to know the length of the current session history. This would also allow us to return a boolean value from `go(n)` so callers could know if the navigation actually succeeded or not.

The way to do this would be to keep a `current` value in session state. I think we could reliably do this if we [refactored `BrowserHistory` to use `sessionStorage`](https://github.com/rackt/react-router/blob/5d674c9515aa628b644c223b2e3f43bb28ac24bc/modules/__tests__/scrollManagement-test.js#L42-L78) the same way that `HashHistory` does.

**Comment by taurose** [comment]
So pretty much #843 ?

**Comment by mjackson** [comment]
@taurose Yes, exactly. Sorry, when you submitted #843 I wasn't yet capable of understanding everything that was going on there. I needed a little time to think over the problem myself so I could get it.

If you're up for it, I'd definitely welcome that functionality now. Maybe we could roll it into #1376?

**Comment by knowbody** [comment]
I believe this is resolved in #1376
