### ISSUE TITLE
Routing fails if query parameter contains a dot

### ISSUE THREAD

**Issue by inyono** [rackt/react-router#1360]
Configuration:

```
<Route name="app" path='/' handler={App}>
  // ...
  <Route name="deploy" handler={DeployPage}/>
  // ...
</Route>
```

If `http://localhost:3000/deploy?url=github.com` is called directly, routing fails:
```
Cannot GET /deploy?url=github.com
```

while `http://localhost:3000/deploy?url=github%2Ecom` works.

**Comment by knowbody** [comment]
I double checked it and it works fine:

<img width="898" alt="screen shot 2015-09-09 at 15 03 56" src="https://cloud.githubusercontent.com/assets/3802023/9763925/1a6e3456-5704-11e5-91e4-77038260d156.png">

**Comment by kalmanb** [comment]
I had the same issue proved to be webpack dev server with history-api-fallback enabled failed to pass these urls to the react app. Hacked webpack config to pass these to react with:
