### ISSUE TITLE
react-router 1.0.0 and Navigation Mixin with ES6 classes

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1364]
I'm giving 1.0.0-beta2 a try and I'm confused about how to get access to either the Router context, or use the Navigation mixin with ES6 classes.

This doesn't work:

```
import {Component} from 'react';
import {Router} from 'react-router';
export default class MyComponent extends Component {
	static contextTypes = {
		router:		Router.PropTypes.router.isRequired
	}
}

=> Cannot read property 'router' of undefined
```

And since classes don't support mixins I don't see how I can use the Navigation Mixin either...

The React-Router documentation seems inconsistent. Most of the pages uses classes, but the docs for the Mixins all use ES5 React.createClass() definitions.

**Comment by globexdesigns** [comment]
Nevermind. I see decorators are on their way in https://github.com/rackt/react-router/issues/1173

**Comment by appshore** [comment]
This ES6 solution found on SO: http://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router works. No need to import Router.

import React from 'react';

export default class Authentication extends React.Component {
  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(e) {
    e.preventDefault();

    this.context.router.transitionTo('/');
  }

  render(){
    return (<div onClick={this.handleClick}>Click me!</div>);
  }
}

Authentication.contextTypes = {
  router: React.PropTypes.func.isRequired
};

**Comment by mauron85** [comment]
@appshore I've tried above method with react 0.14 and react-router 1.0.0-rc4 but I get warning:

```
Warning: Failed Context Types: Required context `router` was not specified in `LoginPage`. Check the render method of `App`.
```

**Comment by knowbody** [comment]
@mauron85 `router` is no longer in the `context`. You should use `history` module: `this.history.pushState(null, '/somePath')`. Check the docs and upgrade guide.

We made the issue tracker for bugs and feature request only. Let's follow up on Discord or StackOverflow.

**Comment by Download** [comment]
@knowbody Wondering about this myself. Where did the discussion move to?

**Comment by knowbody** [comment]
@Download 

https://github.com/rackt/react-router/blob/893bc3e9625977442ecb1fe44bcaa3a6eb977131/CHANGES.md#state-mixin

or check my playground example https://github.com/knowbody/react-router-playground/blob/master/src/Main.js

or ask on Reactiflux

**Comment by Download** [comment]
@knowbody Thanks for the quick response!

**Comment by knowbody** [comment]
@Download you're welcome :+1:

**Comment by Download** [comment]
Is there also an example for doing this with ES6 class syntax i.s.o `React.createClass`?

(didn't see a way to comment there, sorry)

**Comment by knowbody** [comment]
@Download let's continue that on Discord, ping me there

**Comment by Download** [comment]
@knowbody Sorry I don't get it. Is there a link to this `Discord` thing somewhere? I have no idea how to ping you there.

**Comment by knowbody** [comment]
https://discordapp.com/invite/0ZcbPKXt5bYaNQ46

**Comment by zachcarroll** [comment]
@Download @knowbody can one of you guys post the solution for es6 classes with history here? i can't find it in the discussion on discordapp

**Comment by Download** [comment]
```js
import React from 'react';
import {  Link } from 'react-router';

export default class App extends React.Component {
	render() {
		return (
			<div>
				<ul>
					<li><Link to="/">Home</Link></li>
					<li><Link to="/bar">Bar</Link></li>
					<li><Link to="/baz">Baz</Link></li>
				</ul>
				<div className="content">
					{this.props.children}
				</div>
			</div>
		);
	}
}

App.contextTypes = {
	history: React.PropTypes.object
};
```

The key is in the last part. You assign directly to a property on the class.

**Comment by Download** [comment]
I have to warn that I never fully completed my research into this topic as I was distracted with other, more pressing matters. But I do think this was the correct syntax.

**Comment by knowbody** [comment]
Guys again we made the issue tracker for bugs and feature requests only. Please ask all "how to" questions on SO or Discord.

**Comment by SimenB** [comment]
@knowbody I picked a randon thread for this, felt like creating an issue on it is overkill. When you ask people to ask on discord or SO (which I think is great, btw), could you extend the template you use (of course_not_ used in this thread) to also provide a link to the posted question? I don't know if discord supports it (probably, but it's blocked at my workplace, so I haven't bothered with it), but SO of course works great. 

GitHub issues are always high on google results. Finding an issue related to the problem your having, only for the answer to be somewhere else you'll have to dig up is sorta sad.

**Comment by knowbody** [comment]
> GitHub issues are always high on google results. It's also really easy to search and always at least get results regarding the correct project, and not have to filter through broader google/so-results. Finding an issue related to the problem your having, only for the answer to be somewhere else you'll have to dig up is sorta sad.

We made an issue tracker a tool for people who contribute and work on React Router. It helps us - contributors - to make this library better and it keeps us focused on what we've got to build (new feature) or fix (bugs), hence we are happy when people submit feature requests and report bugs here.

If we get stormed by "how to" questions, it makes it very difficult for us to keep track on what we are actually working on. Being around React Router for a while now I can say that most of the questions people ask are already answered in the docs.

**Comment by SimenB** [comment]
Yes, I'm very much with you that GH issues (on projects above a certain size) becomes unmanageable, I'd just like to see the link to the question posted elsewhere. This thread has the SO question linked, so a bad example I suppose.

What I meant is if you add a paragraph underneath your template (https://github.com/rackt/react-router/issues/2591#issuecomment-158892461) with something like

> Please post a link to the question asked on another forum in the OP the help discoverability

Or something like that :smile: I do think you should keep forwarding users to SO, but being able to follow it there easily would be nice

**Comment by knowbody** [comment]
The key point of that is for us to not to need to post those answers and for people to read the README which states to not to create issues with the "how to" questions.
