### ISSUE TITLE
Let's improve documentation to clarify ambiguity about names/paths

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1366]
I've had lingering confusion due to fact that routes can have separate names and paths, and going back through the documentation didn't really clarify it for me.

For example...

- If I don't specify a name for a route, does it remain nameless, or does it use the path for the name? (for example, how would I `Link` or `transitionTo()` it?

- Can I make a Link to a path instead of a name?
  - and especially, can I make a Link to a relative path?  I get the impression the answer is no, though I think such a feature would be handy in some scenarios.

- can I `transitionTo()` a relative path?
  - Or a path relative to the site root, if not a full URL?
  - can I put params/query in the path argument string, if need be?

- `transitionTo()` accepts a `routeNameOrPath` argument.  How exactly is potential ambiguity in this resolved?  For example if I have the following routes (contrived example for the sake of clarification):
```
    <Route name="foo" path="bar" ... />
    <Route name="bar" path="foo" ... />
```
and I `transitionTo('foo')`, which route will it pick?

**Comment by ryanflorence** [comment]
I agree :)

In 1.0 there are no more named routes, only paths.

**Comment by jedwards1211** [comment]
ahhhhh glad to hear it.  How stable is 1.0 beta?  If it's pretty stable now I'll switch to it for my company project.
