### ISSUE TITLE
Where did DefaultRoute go in 1.0.0-beta2 ?

### ISSUE THREAD

**Issue by duro** [rackt/react-router#1368]
Component does not appear to be in the lib any more. Is there an equivalent?

**Comment by duro** [comment]
This also applies to `NotFoundRoute`

**Comment by ryanflorence** [comment]
Not found is just. Route with path "*", still figuring out default route for the new marching algorithm. For now you can move the path from the parent to a child and that's your default route

**Comment by ryanflorence** [comment]
Holy cow, lots of typos on my phone, "marching" is cracking me up.
