### ISSUE TITLE
Getting an error when using the BrowserHistory class in 1.0.0-beta2

### ISSUE THREAD

**Issue by duro** [rackt/react-router#1370]
I seem to be getting the following error thrown client side:

```
DOMHistory.js:9 Uncaught TypeError: Super expression must either be null or a function, not object
```

Last function of mine that is in the stack is my `React.render` method. Here is what it looks like:

```
import React from 'react';
import Marty from 'marty';
import Application from './app';
import { Router } from 'react-router';
import BrowserHistory from 'react-router/lib/BrowserHistory';
import {ApplicationContainer} from 'marty';
import routes from './routes'

global.React = React; // For React Developer Tools
global.Marty = Marty; // For Marty Developer Tools

React.initializeTouchEvents(true);

if (process.env.NODE_ENV !== 'test') {

  let app = new Application();

  app.rehydrate();

  React.render((
    <ApplicationContainer app={app}>
      <Router routes={routes} history={new BrowserHistory} />
    </ApplicationContainer>
  ), document.getElementById('app'));
}
```

**Comment by mjackson** [comment]
I've only seen this error before when the super class was `undefined` or otherwise not a valid class. It looks like this error is being thrown in `BrowserHistory#constructor`, but I'm not sure what the core issue could be. Is your `BrowserHistory.js` unable to `import History` for some strange reason? Are you doing some path magic in your build step that could cause this problem?

**Comment by duro** [comment]
I am certain no path magic happening. All other modules can find each other
no problem.

**Comment by mjackson** [comment]
Try `var History = require('react-router/lib/History')` in a console or something. What happens?

**Comment by ozelen** [comment]
having similar issue.
```new BrowserHistory``` (when ``` react-router/lib/History) ``` throws ``` Uncaught TypeError: object is not a function ```.

Using it w/o ```new``` operator throws

```
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
warning.js:48Warning: Only functions or strings can be mounted as React components.
ReactDefaultInjection.js:53Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```

Code:
```
import React from 'react';
import BrowserHistory from 'react-router/lib/History';
import { Router, Route, Link } from 'react-router';
class AppRouter extends React.Component {
  render() {
    return (
      <Router history={new BrowserHistory()}>
          <Route path="about" component={About} />
      </Router>
    );
  }
}

class About extends React.Component {
  render() {
    return <h1>About</h1>;
  }
}

React.render(
  <AppRouter />,
  document.body
);
```

**Comment by richardaday** [comment]
I was experiencing the same issue mentioned in this issue using the 1.0.0-alpha2 release.  After some testing, I was able to get the router to work.

To resolve this issue, I changed
`<Router history={new BrowserHistory()>`
to:
`<Router history={BrowserHistory}>`

Is this a documentation bug or should we really be needing to instantiate a new instance of BrowserHistory?

**Comment by sehmaschine** [comment]
Same here ...

```
var BrowserHistory = require('react-router/lib/BrowserHistory');

var App = React.createClass({
    render: function() {
        return (
            <div>xxx</div>
        );
    }
});

React.render((
    <Router history={BrowserHistory}>
        <Route path="/" component={App} />
    </Router>
), document.body);
```

This throws ... type.toUpperCase is not a function.
When I change to ```{new BrowserHistory}```, the error is: object is not a function.

**Comment by gaearon** [comment]
@sehmaschine 

If you're using `require` directly (not ES6 `import`), you'll need to explicitly ask for `default`:

```js
var BrowserHistory = require('react-router/lib/BrowserHistory').default;
```

That's the way ES6 modules work. Because more than one thing can be exported, you need to be more specific.

In ES6 you can just

```js
import BrowserHistory from 'react-router/lib/BrowserHistory';
```

because if you don't use curly braces, it will take the default export.

**Comment by ozelen** [comment]
Alright... My problem was in in my misunderstanding. Repo homepage describes v.1.0beta, while v.0.3 was installed by default. It had its own readme.md doc, which didn't work for me either :). Anyhow, update to beta helped and now it works fine.

**Comment by duro** [comment]
After a re-build of the Docker image I am using for my app, and subsequently a re-install of all npm modules, this seems to be working on my end.
