### ISSUE TITLE
Slider component: add check on percent in getInitialState (min=0, max=1)

### ISSUE THREAD

**Issue by hilkeheremans** [rackt/react-router#1373]
When the value prop provided to a slider is outside the bounds defined by the max and min props, the percent calculation in getInitialState() will be calculated < or > than 100%. Because of this, the width of the Slider will go beyond the bounds of the parent element, resulting in visually unpleasant rendering.

For your reference, at this time, the percent is currently calculated as follows:
```javascript
    var percent = (value - this.props.min) / (this.props.max - this.props.min);
```

I would propose we either:
- cap this at 0 and 1 respectively in order to prevent this behavior
and/or
- log a warning when this occurs

Let me know what you think. 

Discovered this due to my own stupidity, of course. 

Absolutely great work by the way! I'll be happy to contribute more directly (PRs) as time permits.

**Comment by WRidder** [comment]
I suppose this is a material-ui issue? :)

**Comment by ryanflorence** [comment]
?

**Comment by hilkeheremans** [comment]
Absolutely - this should be an issue in a totally different project. My apologies for the mixup!

**Comment by futurefeeling** [comment]
@hilkeheremans do you have a solved case with react-router in your slider component? I also have a requirement in slider component, but I don't have any idea about how to do this with react-router
