### ISSUE TITLE
Proposal: Add custom activeClassName matcher to Link

### ISSUE THREAD

**Issue by dferber90** [rackt/react-router#1374]
Sometimes links should appear active even when they are not the current route. An example for this is nested navigation, where the top-navigation should be highlighted when the user is on a sub-route.

Example:
```
Help            (/help)
Help -> General (/help/general)
Help -> Contact (/help/contact)
```
For the imagined application, the link to `/help` should be active, even if the user is on `/help/general` or `/help/contact`.

I propose adding a property to Link called `activeMatcher` which is a function. It gets called with the current path (or maybe location?). If it returns true, the value stored in `activeClassName` will get appended. If `activeMatcher` is set, it overwrites the default `router.isActive(to, query)` behavior.

Example usage:
```js
// in render() {..} of a component

return (
  <Link
    to="/dashboard/help"
    className="iconlink"
    activeClassName="-active"

    // overwrite default activeClass matcher behavior
    activeMatcher={(path) => /^\/help/.test(path)}
  >
    Help
  </Link>
)
```

I currently have got this as its own component. I could send a PR to add the functionality to the Link component itself.
Do you think this should be part of react-router?

**Comment by ryanflorence** [comment]
Just have a parent route that simply renders the child route handler and
you'll have it.

**Comment by dferber90** [comment]
I knew there was an easier way. Awesome, thank you :clap: 

I initially had my routes like this, that's why it wouldn't work. I'm using v1.0.0-beta2.
```html
<Route path="help" component={Help}>
  <Route path="general" component={General}/>
  <Route path="contact" component={Contact}/>
</Route>
```

Now I have them like this and it works like you said.
```html
<Route component={Help}>
  <Route path="help/general" component={General}/>
  <Route path="help/contact" component={Contact}/>
</Route>
```

Leaving it here for anyone running into the same issue.
I started using the Router today and it has been great so far!
