### ISSUE TITLE
Simple redirect Example

### ISSUE THREAD

**Issue by basiclaser** [rackt/react-router#1375]
I couldn't find a simple workable example of transferring a user to a different page from within a normal function. I can do it in the routes declaration like   `<Redirect from="here" to="index" />`
and with a link anywhere else using the `<Link to="index"><i>lets go!</i> </Link> `. 

However now id like to direct to "index" just from within a function like: 
```
  onDelete: function(){
    var answer = prompt("type yes if you want to delete this note");
    if(answer == "yes") {
      localStorage.removeItem(this.props.route);
      REDIRECT BACK TO INDEX
    }
  }
```
Thanks for your help! I'm sure its an available method, I just couldn't find it

**Comment by Nickman87** [comment]
Have you seen this? http://rackt.github.io/react-router/#Navigation

Just add in the Navigation mixin en you can go: this.transitionTo(routename, params, query);
whenever you want in the component.

**Comment by scoarescoare** [comment]
What's the difference between [redirect](http://rackt.github.io/react-router/#Transition) and transitionTo?

**Comment by Nickman87** [comment]
The redirect method is specified on the Transition object which you get in the transition hooks.

For example if you add the `willTransitionTo` static [lifecycle method](http://rackt.github.io/react-router/#Route Handler), you will get a `Transition` object and you could intercept the default transition and _redirect_ it to another route.

The `transitionTo` method can be used anywhere else in your logic to trigger a route change.

**Comment by scoarescoare** [comment]
Ah, ok. Thanks!
