### ISSUE TITLE
BrowserHistory is missing

### ISSUE THREAD

**Issue by tleunen** [rackt/react-router#1377]
The readme example has a mention of `BrowserHistory`, but it seems this lib is totally missing from the npm module
```javascript
import BrowserHistory from 'react-router/lib/BrowserHistory';
```

**Comment by tleunen** [comment]
Ok that's because the master is more up to date than what is really on npm

**Comment by taurose** [comment]
Yeah, see http://rackt.github.io/react-router/tags/v0.13.3.html for current docs.
