### ISSUE TITLE
Form element support

### ISSUE THREAD

**Issue by framp** [rackt/react-router#1379]
Now that additional state is in (thank you guys!), is there any plan to integrate the great job made by @insin with [react-router-form] (https://github.com/insin/react-router-form)?

Having a Form element which behaves like Link does is a great feature and makes working with React Router and React a breeze.

**Comment by ryanflorence** [comment]
I can imagine making a form element part of the project, but no plans right
now.

**Comment by framp** [comment]
Thanks for the quick reply.
Sounds great!

I'll be back with a PR asap

**Comment by taion** [comment]
react-router-form seems to be quite functional/good as-is. Since we've been looking to pull things out of this package, I think it's probably best for now for that to live as a separate package.
