### ISSUE TITLE
Nested RouteHandler(s) should render on each transition?

### ISSUE THREAD

**Issue by Nickman87** [rackt/react-router#1384]
I have an application with nested Routes and thus nested RouteHandler components. These RouteHandler components are not directly nested in eachother instead they load wrapped components to resolve data handling.

A simple pseudo example:
```javascript
var routes = <Route name="a" handler="A">
    <Route name="b" handler="B_">
        <Route name="c" handler="C">
            <Route name="d" handler="D">
            </Route>
        </Route>
    </Route>
</Route>

var A = A - <RouteHandler />
var B = B - <RouteHandler />
var B_ = <B data={data} /> //B_ will just render B but with some additional logic to fetch the 'data'
var C = C - <RouteHandler />
var D = D - <RouteHandler />

Router.run(routes, Router.HashLocation, (Root) => {
  React.render(<Root/>, document.body);
});
```

Now, when changing routes, A will always get an update, because of the callback given in Router.run. B_ will be updated because it is a direct child of A.

B however is a child of B_, which doesn't necessarily change in this route switch, so the render method of B_ might not be executed, causing B to never receive an update. This will cause C and D to also skip an update.

Is it possible to force the Router to also update all child handlers that have not yet been updated? Or am I doing something completely wrong causing this behaviour?

**Comment by taurose** [comment]
When you call `React.render(<Root />, ..);`, your whole React tree will be rerendered top-down; it doesn't matter if you have a handler like `_B` that doesn't directly render `<RouteHandler>`. The only way to prevent nested routes from rerendering is to use `shouldComponentUpdate`.

**Comment by Nickman87** [comment]
It seems that I have completely overlooked the fact that I do have a ```shouldComponentUpdate``` implemented which prevented updates from propagating.
Disabling it causes the app to respond correctly to route changes. I will have to revise the ```shouldComponentUpdate``` method to see if it is still needed and how it should be adjusted.

Thanks!
