### ISSUE TITLE
Where have static life cycle method gone in 1.0.0-beta2

### ISSUE THREAD

**Issue by ryanzec** [rackt/react-router#1385]
I noticed in the documentation that the static life cycle methods (`willTransitionTo`  / `willTransitionFrom`) no longer seem to exist and this is a pretty big problem for me.  I see there is a regular life cycle method of `routerWillLeave` which I guess could replace the `willTransitionFrom` but I use `willTransitionTo` pretty heavily.  My main use case for using `willTransitionTo` so that before I loading the page component, I want to try to load the data from the API.  If the API returns an error or something, I can in the `willTransitionTo` method abort that transition and do what is needed.

Is there a new way of doing this type of functionality that I am not seeing?

Also since 1.0.0 is in beta2 I am assuming that the API is pretty much locked down at this point so it would probably be really helpful to at least have an upgrade guide for the 1.0.0 beta's to help with these type of issues (the documentation does seem pretty different compared to 0.13.x).

**Comment by johann-sonntagbauer** [comment]
related to #1388

**Comment by aphillipo** [comment]
I don't understand this change.  The old way was very clear and worked really well.  Seems like one of the few things in 1.0 that don't actually improve react-router.

**Comment by knowbody** [comment]
closing as it's related to #1388
