### ISSUE TITLE
Router.run vs Router.match - what is a difference?

### ISSUE THREAD

**Issue by alekbarszczewski** [rackt/react-router#1386]
In `1.0.0-beta2` documentation I found two examples:

```javascript
...
var location = new Location(req.path, req.query)
Router.run(routes, location, (error, initialState, transition) => {
    var html = React.renderToString(<Router history={history} {...initialState}/>)
})
```

```javascript
...
var history = new ServerHistory(req.path)
Router.match(routes, history, (err, initialState) => {
  React.renderToString(<Router children={routes} history={history} {...initialState}/>);
})
```

One is using `Location` and `Router.run`, the other is using `ServerHistory` and `Router.match`. Which of those approaches is "valid"? What are differences? Maybe this is only a mess in docs?

**Comment by mjackson** [comment]
`Router.match` is not a thing in beta2. Use `Router.run`. This has already been updated in master.

**Comment by alekbarszczewski** [comment]
Ok, thanks. Just remember to update beta2 docs:
![screen shot 2015-06-26 at 10 12 22](https://cloud.githubusercontent.com/assets/2742373/8373313/03754026-1bec-11e5-94fa-0e53e5af6255.png)
