### ISSUE TITLE
Bug in runTransition when transition.abort been called in 1.0.0-beta2

### ISSUE THREAD

**Issue by pucka** [rackt/react-router#1390]
When calling transition.abort from transition events like onEnter an error occur because handleAbort is called with a faulty variable https://github.com/rackt/react-router/blob/master/modules/Router.js#L141. I guess it should be transition.abortReason instead.

`this.handleAbort(transition.abortReason);`

**Comment by ryanflorence** [comment]
transitions are very different now that we're built on top of `history`.
