### ISSUE TITLE
Dynamic Redirects

### ISSUE THREAD

**Issue by dropfen** [rackt/react-router#1391]
Hello is it possible to redirect from a dynamic path to a parametrized path with dynamic params?

Let's say
````
<Route path="profile/:userId/about-me" handler={..} />
<Route path="profile/:userId/albums" handler={..} />
<Redirect from="profile/me/:page" to="profile/:userId/:page" params={{userId: SESSION.userId, page: ':page' }}  />
````
I guess the above is bullshit, but anyway. How could I do something like this?
With 0.13.3 ?

I looks like there are huge improvements in this direction on the master branch, but I'm not sure if it's the right moment to switch from stable

**Comment by Nickman87** [comment]
Hi @dropfen, you could try using a custom route handler like this:

```javascript
var RedirectTo = function(destination) {
	return React.createClass({
		statics: {
			willTransitionTo: function (transition, params, query) {
				transition.redirect(destination, _.extend(params, this.props.params), query);
			}
		},
		render: function () {}
	});
};

var routes = (
	<Route>
		<Route path="profile/:userId/about-me" handler={..} />
		<Route path="profile/:userId/albums" handler={..} />
		<Route path="profile/me/:page" params={{userId: SESSION.userId}} handler={RedirectTo("profile/:userId/:page")} />
	</Route>
);
```

It adds an extra indirection, but you shouldn't notice this when navigating trough your app
