### ISSUE TITLE
replaceWith and transitionTo are not redirecting with 1.x

### ISSUE THREAD

**Issue by mhahn** [rackt/react-router#1392]
I have something like the following:

```
    componentWillReceiveProps(nextProps) {
        const loggedIn = this.props.flux
            .getStore('AuthStore')
            .isLoggedIn();

        if (loggedIn) {
            this.transitionTo(this.props.location.nextPathname || 'feed');
        }
    }
```
this seems to update the browser state, the path is correctly set to "/feed" but the page doesn't transition and stays on the login page.

routes are very simple:

```
    const loginOnce = (nextState, transition) => {
        if (flux.getStore('AuthStore').isLoggedIn()) {
            transition.to('feed');
        }
    };

    const requireAuth = (nextState, transition) => {
        if (!flux.getStore('AuthStore').isLoggedIn()) {
            transition.to('login', null, {nextPathname: nextState.location.pathname});
        }
    };

    return (
        <Route path="/" component={require('./components/App')}>
            <Route
                path="login"
                onEnter={loginOnce}
                component={require('./pages/Login')} />
            <Route
                path="feed"
                onEnter={requireAuth}
                component={require('./components/ProfileFeed')} />
        </Route>
    );
```

the onEnter transitions are working perfectly, seems to just be an issue when redirecting within the component.

My only thought is that calling `replaceWith` or `transitionTo` needs to happen somewhere specific in the component lifecycle.

**Comment by mhahn** [comment]
Closing because this has nothing to do with react-router.

The way I have it set up, the transition within `componentWillReceiveProps` if the user is logged is the result of a cascading dispatch which react errors out on.

Wrapping it in a `setTimeout` works since it will happen outside of the current action context, but is a hack. It would be great to have a more flushed out auth example outlining the best way to handle this within flux.

**Comment by Shachar16290** [comment]
@mhahn Can you explain?
