### ISSUE TITLE
Readme.md are not actual and  makes user confused.

### ISSUE THREAD

**Issue by serjout** [rackt/react-router#1397]
import { Router, Route, Link } from 'react-router';
Router is undefined

import BrowserHistory from 'react-router/lib/BrowserHistory';
BrowserHistory is undefined

**Comment by alekbarszczewski** [comment]
Same applies to `v1.0.0-beta1` and `v1.0.0-beta2`
```
import { BrowserHistory } from 'react-router'; // BrowserHistory = undefined
import BrowserHistory from 'react-router/lib/BrowserHistory' // undefined as @serjout mentioned
```

**Comment by mjackson** [comment]
The README on master is for the code on master. For other versions, please use http://rackt.github.io/react-router/
