### ISSUE TITLE
Browser back/forward buttons not working (Firefox)

### ISSUE THREAD

**Issue by mkotsbak** [rackt/react-router#1399]
Assuming the documentation page (http://rackt.github.io/react-router/) is written using react-router, it fails to support back-button in the browser. The URL updates, but not the content.

It should work with back/forward like this page: https://japgolly.github.io/scalajs-react/#examples/product-table

**Comment by mkotsbak** [comment]
Hmm, or it looks like you are not dogfooding the router?

**Comment by djanosik** [comment]
I use `BrowserHistory` and have exactly the same problem. @mkotsbak did you found a solution?
