### ISSUE TITLE
[Question] how to install 1.0.0-beta?

### ISSUE THREAD

**Issue by goncalvesjoao** [rackt/react-router#1401]
Hi guys,

Sorry for my ignorance, but I tried to "npm install https://github.com/rackt/react-router.git --save-dev" everything went well, but when I start my app, it says:
"ERROR in ./app/js/app.js
Module not found: Error: Cannot resolve module 'react-router' in /Users/goncalvesjoao/projects/lcfe/sandboxes/project/app/js
 @ ./app/js/app.js 5:16-39"

webpack can't find react-router module, although I see it in my node_modules folder.

How can I correctly install this new 1.0.0 beta?

Thanks in advance.

**Comment by tmbtech** [comment]
`npm install react-router@beta --save`

**Comment by goncalvesjoao** [comment]
Thanks @tmbtech !
