### ISSUE TITLE
Will accessing router via context be deprecated at some point?

### ISSUE THREAD

**Issue by duro** [rackt/react-router#1405]
I am wondering, because I am doing a conversion to 1.x and I can still access it by adding this to my component:

```
contextTypes: {
  router: React.PropTypes.object
}
```

And this is very handy, as my Flux implementation `Marty` allows me to use that to get access to the router in it's `Container` object, which wraps the component.

My question is, are there plans to deprecate that in the future?

**Comment by mjackson** [comment]
Nope.
