### ISSUE TITLE
Better error message when Link fails invariant

### ISSUE THREAD

**Issue by arasmussen** [rackt/react-router#1407]
When a Link fails an invariant (eg. because it's missing params) the warning message I get is:

ReactRouter.min.js:6 Uncaught Error: Invariant Violation: Missing "id" parameter for path "/foo"

Which makes it incredibly hard to tell where in my application the link that I need to fix is. I pretty much have to search for everywhere I Link to "/foo" and then identify which one is missing the parameter.

I've noticed a bunch of other people have posted being stuck with this message. It'd be a lot cleaner if it said something like:

MyComponent.js:77 Link to "/foo" is missing parameter "id".

**Comment by arasmussen** [comment]
Or also if you have a <Link /> with no "to" field then the error message I get is "Uncaught TypeError: Cannot read property 'charAt' of undefined"

**Comment by ryanflorence** [comment]
yeah we could have better error messages all around, we'll get back to this after 1.0 unless you want to take a stab at a pull request :)

**Comment by taion** [comment]
`to` is required now and `params` are gone, so there's nothing to revisit here.
