### ISSUE TITLE
Get query in willTransitionTo

### ISSUE THREAD

**Issue by Philmod** [rackt/react-router#1410]
Hey guys,

Is it possible to get the query parameters during `willTransitionTo`?

Thanks!

**Comment by taurose** [comment]
It's the third parameter

`willTransitionTo(transition, params, query, callback)`


[http://rackt.github.io/react-router/tags/v0.13.3.html#Route Handler](http://rackt.github.io/react-router/tags/v0.13.3.html#Route Handler)

**Comment by Philmod** [comment]
Wow, thanks.
