### ISSUE TITLE
Is DefaultRoute deprecated for 1.0.0? 

### ISSUE THREAD

**Issue by olegakbarov** [rackt/react-router#1414]
Not sure how to handle redirect from gibberish routes.
Any suggestions?

**Comment by eugene1g** [comment]
Until there is an official guidance, I did it inside the app wrapper like so -
```
render()
{
///....
return (
            <div>
                <Header isAdmin={isAdmin}/>
                <main>{this.props.children ? this.props.children : <DefaultSection/> }</main>
            </div>
        );
}

**Comment by tmbtech** [comment]
> Not sure how to handle redirect from gibberish routes.

Do you mean 404 `not found` route?

try this using `path="*"` for the 404 route.
```
<Route component={Application}>
   <Route path="/" component={Index} />
   <Route path="*" component={NotFound} />
</Route>
```

**Comment by Schniz** [comment]
I think that 404 routes shouldn't be a normal route - if you render it in the server side you'd like to know if you actually hit a real page or some rendered content for the `404`, and respond with a correct HTTP header.

**Comment by ElessarWebb** [comment]
+1

**Comment by srph** [comment]
Is this in the docs? :smile:

**Comment by tmbtech** [comment]
I don't think so, I found the example here. https://github.com/rackt/react-router/blob/master/examples/master-detail/app.js

**Comment by iest** [comment]
In case anyone might find it useful, heres how I' m handling 404s (working on server):

```js
// Routes.js
<Route component={App}>
  {/* other routes first */}
  <Route path="*" component={NotFound}/>
</Route>
```

```js
// NotFound.js component
export default class NotFound {
  render() {
    return <h1>Oh Noes! 404!</h1>;
  }
}

// Manually add this prop so we can easily check for it in server render
NotFound.isNotFound = true;
```

```js
// Server-rendering middleware (using koa in my case)
const notFound = initialState.components
  .filter(component => component.isNotFound)
  .length > 0;

if (notFound) {
  if (this.accepts('html')) {
    this.status = 404;
  } else {
    return null;
  }
}
```

**Comment by Schniz** [comment]
@iest, it looks really good, but IMO it should be something as easy as `initialState.isNotFound` or `initialState.isFound`

**Comment by iest** [comment]
@Schniz not sure what ideas the router guys have for this, but it certainly seems like they've gone for a much more flexible (less opinionated) approach with the 1.0. Don't hold your breath for `intialState.isNotFound`!

**Comment by BerkeleyTrue** [comment]
If no route is matching, initialState will be null. You can just filter for initialState existence.

[here](https://github.com/FreeCodeCamp/freecodecamp/blob/new-challenges/server/boot/a-react.js) is how I am filter 404's
```js
// after Router run
if (!initialState) {
  debug('react tried to find %s but got 404', location.pathname);
  // using express we call the next callback. Now express tries to match the route to other endpoints, eventually hitting the 404 handler if nothing matches
  return next();
}
```

Not sure yet how to translate this to client side so the router hits the server on unknown route. I like @iest  approach as well.

I'm converting an express app to Universal React in stages and cannot have a 404 component in production until all of the app is done.

**Comment by ryanflorence** [comment]
No, we brought it back as `<IndexRoute/>` will have docs soon

**Comment by srph** [comment]
Nice! Thanks!

**Comment by christophediprima** [comment]
How can we handle this kind of routes ? As I want that '/' is redirected to '/teams' ?

```
<Route component={App} path="/">
      <DefaultRoute component={Teams} path="teams" />
      <Route component={ApiProviders} path="apis" />
      <Route component={Profile} path="profile" />
      <Route component={Proxies} path="proxies" />
      <Route component={NotFound} path="*" />
    </Route>
```

**Comment by srph** [comment]
Use `<IndexRoute />`

**Comment by christophediprima** [comment]
But IndexRoute wont take any path parameter and I need to go to "/teams" when user goes to "/"...

**Comment by knowbody** [comment]
@christophediprima then use `Redirect`

**Comment by christophediprima** [comment]
@knowbody then how should my routes look like?

I tried something like this, but then it never uses my root app component...

```javascript
  <Route>
      <Redirect path="/" to="/teams"/>
      <Route component={App} path="/">
        <IndexRoute component={Teams} />
        <Route component={ApiProviders} path="apis" />
        <Route component={Firewall} path="firewall" />
        <Route component={Profile} path="profile" />
        <Route component={Proxies} path="proxies" />
        <Route component={Services} path="services" />
        <Route component={Teams} path="teams" />
        <Route component={NotFound} path="*" />
      </Route>
    </Route>
````

I need to redirect '/' to '/teams', but I also need '/services' and so on to work and a root app component.

I tried moving the app component to the first empty Route component but it doesnt work...

**Comment by srph** [comment]
How about:
```es6 
  <Route path="/">
      <Redirect path="/" to="/teams"/>
      <Route component={App}>
        <IndexRoute component={Teams} />
        <Route component={ApiProviders} path="apis" />
        <Route component={Firewall} path="firewall" />
        <Route component={Profile} path="profile" />
        <Route component={Proxies} path="proxies" />
        <Route component={Services} path="services" />
        <Route component={Teams} path="teams" />
        <Route component={NotFound} path="*" />
      </Route>
    </Route>
```

I always set the path of top-route to `/` because it always seem to work.

**Comment by taion** [comment]
Then use `<IndexRedirect>`.

**Comment by ryanflorence** [comment]
@srph 

```js
<Route path="/" component={App}>
  <IndexRedirect to="/teams"/>
  <Route component={Teams} path="teams" />
  <Route component={ApiProviders} path="apis" />
  <Route component={Firewall} path="firewall" />
  <Route component={Profile} path="profile" />
  <Route component={Proxies} path="proxies" />
  <Route component={Services} path="services" />
  <Route component={NotFound} path="*" />
</Route>
```

If you want the user to see the `Teams` component when they visit `/`, but also have the url say `/teams`.

If you want the `Teams` UI to render at `/`

```js
<Route path="/" component={App}>
  <IndexRoute component={Teams} />
  <Route component={ApiProviders} path="apis" />
  <Route component={Firewall} path="firewall" />
  <Route component={Profile} path="profile" />
  <Route component={Proxies} path="proxies" />
  <Route component={Services} path="services" />
  <Route component={NotFound} path="*" />
</Route>
```

I'm not sure why you've got all that extra stuff.

**Comment by christophediprima** [comment]
Thanks @ryanflorence ! Thats was exactly what is was looking for ! :dancers:
