### ISSUE TITLE
Router is not "accepting" Browser/Hash history?

### ISSUE THREAD

**Issue by alekbarszczewski** [rackt/react-router#1419]
I'am trying to set up react router using `v1.0.0-beta2`. I've installed it via npm by using `npm install react-router@beta` and built by running `./scripts/build.sh`. My code looks like this:

```coffeescript
React = require 'react'
{Router, Route} = require 'react-router'
BrowserHistory = require 'react-router/lib/BrowserHistory'
routes = require './../shared/routes
router =
  <Router history={BrowserHistory} children={routes} />
React.render(router, document.getElementById('app-container'))
```

and I get following error:
```
Warning: Failed propType: Invalid prop `history` supplied to `Router`, expected instance of `History`.
browser.js:42 Uncaught Error: Invariant Violation: A <Router> needs a valid Location
```

So I thought that maybe I should pass instance of `BrowserHistory` to the router:

```coffeescript
React = require 'react'
{Router, Route} = require 'react-router'
BrowserHistory = require 'react-router/lib/BrowserHistory'
routes = require './../shared/routes
router = # now passing instance!
  <Router history={new BrowserHistory} children={routes} />
React.render(router, document.getElementById('app-container'))
```

And I get same error again. Same is happening with `HashHistory`. What I am doing wrong?

**Comment by taurose** [comment]
The second code should work I think. Maybe you're somehow loading two instances of react-router? What does your build system look like?

**Comment by alekbarszczewski** [comment]
You were right - my bad. I am using browserify to split code into `app.js` and `vendor.js` and forgot to add `'react-router/lib/BrowserHistory'` as vendor lib

```coffeescript
vendorLibs = [
  'react'
  'react-router'
  'react-router/lib/BrowserHistory'  
]
```
