### ISSUE TITLE
v1.0.0-beta2 Docs Missing "new" Operator for HashHistory

### ISSUE THREAD

**Issue by AlanBreck** [rackt/react-router#1423]
In the ReactRouter example under the "Overview" section of the v1.0.0-beta2 docs, the `<Router>` component says `history={HashHistory}` instead of `history={new HashHistory}`. The error appears to already be fixed in the docs on master, but the change is not yet reflected on the GH page for v1.0.0-beta2.

**Comment by mjackson** [comment]
The docs are already updated in master and will update on the website with the next release.
