### ISSUE TITLE
two routers in one big app

### ISSUE THREAD

**Issue by shangsunset** [rackt/react-router#1424]
Hi i have a site built in php/laravel and want to use react/react-router partially for the site. is it possible to have two routers working on the same website? 

i already used react and react-router to render UI for for our admin panel on the website with a router. when requested url hits `/admin/{whatever}`, i render a view has the document id.

```php
Route::get( 'admin/{catchall}', function() {
  return view('admin.panel');
})->where('catchall', '(.*)');
```
and then in assets/admin/app.js, all the routes are handled by react-router like so:
```javascript
var App = React.createClass({

  render() {
    return (
      <div>
        <RouteHandler />
      </div>
    )
  }
})

var routes = (
  <Route handler={App}>
    <Route path="/admin/panel" handler={AdminPanel} />

    <Route handler={PageApp}>
      <Route path="/admin/pages" handler={Pages} />
    </Route>

    <Route handler={UserApp}>
      <Route path="/admin/users" handler={Users} />
      <Route path="/admin/users/create" handler={Registration} />
      <Route path="/admin/users/:userId" handler={ViewUser} />
    </Route>
  </Route>
);

Router.run(routes, Router.HistoryLocation, function (Handler) {  
  React.render(<Handler />, document.getElementById('app'));
});
```

so now i want to rewrite the view for under `/users/{whatever}` on the site with react/react-router. can i make another route in backend like this to return another different view and render react component when url is `/users/{whatever}`?
```php
Route::get('users/{catchall}', function() {
  return view('users.welcome');
})->where('catchall', '(.*)');
```
and make anther router to handle  `/users/{whatever}`?  this is what i tried but not working. and i get `Invariant Violation: _registerComponent(...): Target container is not a DOM element.` when i visit /admin/{whatever}` routes(it's working without the the second router).

in assets/users/app.js:

```javascript
var App = React.createClass({

  render() {
    return (
      <div>
        <RouteHandler />
      </div>
    )
  }
})

var Welcome = React.createClass({
  render () {
    return (
      <h1>welcome</h1>
    )
  }
})

var routes = (
  <Route handler={App}>
    <Route path="/users/welcome" handler={Welcome} />
  </Route>
);

Router.run(routes, Router.HistoryLocation, function (Handler) {  
  React.render(<Handler />, document.getElementById('user-app'));
});
```
if having two routers is not possible, how should i go about handling an issue like this? i hope my question makes sense. thanks!

**Comment by taurose** [comment]
Not sure if I understand you correctly. What do you mean by `project` exactly? Running multiple routers at the same time is not supported (also, I don't think that's what you want). If you want to serve two apps from a single server I'd say you have two options:

1. Use a single client-side app with a single router by using different routes. This would allow you to share code more easily, and seamlessly link from one part of the app to the other. You'd have to setup your serve to serve the same script for both `/users` and `/admin`.

  ```js
  var routes = (
     <Route handler={App}>
       <Route path="/users/welcome" handler={Welcome} />
       <Route path="/admin">
          {/* admin routes here */}
       </Route>
     </Route>
  );
  ```

2. Use two different entry points each running its own router. This would isolate each of your apps, and you wouldn't be able to transition from one "app" to the other without a server round trip. You'd have to setup your server so that it serves different scripts for `/users` and `/admin`. And for linking to the other app, you'd have to use the normal `<a href>` instead of `<Link to>`.

**Comment by shangsunset** [comment]
Hi @taurose, thanks for your solutions. option 1 is working for me for now. i dont really get option 2 though. how to have a router for each entry point in your case? i think this was what i was trying to do but failed. thanks.

**Comment by taurose** [comment]
Not sure if I can help you there; it's more of an backend and build system issue and I've never used laravel.

Basically you need to make sure that you're serving two different html pages with different script tags, for example

GET /users/*

```html
<html>
<head>
<script src="/common.js"></script>
<script src="/users.js"></script>
<body>..</body>
</html>
```

GET /admin/*

```html
<html>
<head>
<script src="/common.js"></script>
<script src="/admin.js"></script>
<body>..</body>
</html>
```

* `common.js`: for sharing some code and caching (optional)
* `users.js`: starts the router with `/user` routes
* `admin.js`: starts the router with `/admin` routes

**Comment by shangsunset** [comment]
I see. Thanks!
