### ISSUE TITLE
Use routes with createFactory-ed components

### ISSUE THREAD

**Issue by togakangaroo** [rackt/react-router#1425]
I don't use jsx and prefer for all my components to be wrapped in `createFactory` so they're easy to instantiate. Unfortunately it seems like I can't just pass the factory-ed component to `Route` as I get errors

```js
var component = React.createFactory(React.createClass({
    ...
});
```
I can't do

```js
React.createElement(Route, {path: 'foo', component})
```

Seems like a really easy fix unless there's some specific reason to avoid this

**Comment by taurose** [comment]
As far as I know it's bad practice to just wrap all your components within `createFactory`. You should use it on the consumer side, i.e

```js
// App.js
module.exports = App; // no createFactory

// index.js
var App = require('./App');
var route = React.createElement(Route, {component:App}); // this will work now

// somewhere else 
var App = React.createFactory(require('./App'));

**Comment by togakangaroo** [comment]
Whats the reasoning for it being bad practice? It seems so clean...

**Comment by taurose** [comment]
Interoperability and reusability I'd say. As you already noticed, factories and component classes aren't compatible (one expects to be invoked, the other needs to be passed to `createElement`). So if you're importing other third-party components, you need to be aware of which component exports what.

There's also other components that expect component classes via their props. So even if we made it work with factories, you'd probably soon run into the next library asking for factory support.

I think it's one of the nice things about react that everything is a component and can be handled the same way. By using  factories like this, you're giving up on that and make things more complex than they need to be. 

Finally, if you every wanted to get rid of `createFactory`, you could change one component at a time without any surprises. With your approach, you'd have to change every consumer as well.

**Comment by mjackson** [comment]
We do not have any plans to support plain functions in the `component` prop. Only actual component classes.
