### ISSUE TITLE
HashLocation doesn't add # in front of Link urls

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#1428]
also, I'm in a training right now and it's embarrassing.

**Comment by ryanflorence** [comment]
+1

**Comment by taurose** [comment]
Was fixed in https://github.com/rackt/react-router/commit/178efc34f80c4483dedc7c8d79b114823eed3072 , wasn't it?

**Comment by mjackson** [comment]
@taurose yup.

@ryanflorence What's `HashLocation`? :P
