### ISSUE TITLE
<Link /> Basic active path

### ISSUE THREAD

**Issue by srph** [rackt/react-router#1430]
I'm not sure if this is in the docs. I'd like my Link to be active only when it is in the exact route, but not for children routes.

Is this possible at the moment?

**Comment by gbezyuk** [comment]
It seems to be the only existing behaviour available. At least I'm trying to get the opposite result and mark my parent route's links active, with no success.

**Comment by srph** [comment]
Just leave this here: https://github.com/rackt/react-router/blob/master/docs/API.md#indexlink
