### ISSUE TITLE
partial-app-loading for an isomorphic app

### ISSUE THREAD

**Issue by YoussefTaghlabi** [rackt/react-router#1435]
Looking at the [partial-app-loading](https://github.com/rackt/react-router/blob/latest/examples/partial-app-loading/app.js) example, it seems it will work only for client side: 

```js
var PreDashboard = React.createClass({
  mixins: [ AsyncElement ],
  bundle: require('bundle?lazy!./dashboard.js'),
  preRender: function () {
    return <div>Loading dashboard...</div>;
  }
});
```
In an isomorphic environment, I get the following error when I run it Server side:

```Error: Cannot find module 'bundle?lazy!./dashboard.js'```

It seems that ```bundle-loader``` doesn't recognize the module server side.

**Comment by anatomic** [comment]
In the node enviroment, the `require` function doesn't have any notion of loaders unless you are bundling your code with webpack for use on the sever.  Are you producing a client side bundle and a server side bundle?

**Comment by YoussefTaghlabi** [comment]
My environment is Isomoprhic. Server side, there is no bundle, I'm just running the provided component through ```React.renderTostring```, but webpack chocks on ```require('bundle?lazy!./dashboard.js')``` stating that it can't find the module.
If I change the require to be just: ```require('./dashboard.js')``` it works just fine.
So in summary:
Server side: ```require('bundle?lazy!./dashboard.js')``` Doesn't work.
Client side: ```require('bundle?lazy!./dashboard.js')``` Works.
So I can't lazy load my components in an isomorphic environment.

**Comment by anatomic** [comment]
Ok, so I'd advise you switch to using require.ensure on the client side and a synchronous polyfill on the server.

Something like:
```javaScript
if( typeof require.ensure !== "function") {
    require.ensure = function(deps, callback) {
        callback(require);
    }
}
```

Your code would then also need changing from `require('bundle?lazy'...` to something more like:

```javaScript
var PreDashboard = React.createClass({
  mixins: [ AsyncElement ],
  bundle: function(cb) {
      require.ensure([], function(require) {
          cb(require('./dashboard.js'));
      });
  },
  preRender: function () {
    return <div>Loading dashboard...</div>;
  }
});

// Or using ES6 fat arrow functions

var PreDashboard = React.createClass({
  mixins: [ AsyncElement ],
  bundle: (cb) => {
      require.ensure([], (require) => {
          cb(require('./dashboard.js'));
      });
  },
  preRender: function () {
    return <div>Loading dashboard...</div>;
  }
});
```

This will still use the `load` function from `AsyncElement` and should replicate the functionality you had previously with the bundle-loader. Let me know if it works!

**Comment by quirinpa** [comment]
@anatomic but if we want to lazy load a route to provide to react-router 1.0, how would we?

**Comment by anatomic** [comment]
@quirinpa Sorry, I've not being playing with this recently but I think the best way to lazy load with 1.0 is to use the more formal route definition style (not JSX) and include functions for`getChildRoutes` and `getComponents` which include the `require.ensure` calls. Have a look at https://github.com/rackt/react-router/blob/master/examples/huge-apps/routes/Course/index.js

**Comment by ryanflorence** [comment]
you just shim require.ensure in node-land to be synchronous and then it can work. I haven't done it yet, but there will eventually be a demo.
