### ISSUE TITLE
Outdated examples?

### ISSUE THREAD

**Issue by ewal** [rackt/react-router#1436]
I'm trying out the examples in the README and the Overview example (https://github.com/rackt/react-router/blob/master/doc/00%20Guides/0%20Overview.md) but neither BrowserHistory or HashHistory exist in the npm module. Where can I find a working example?

**Comment by gaearon** [comment]
Master docs point to the 1.0 beta.
You're looking for the stable docs: rackt.github.io/react-router

**Comment by ewal** [comment]
:+1:

**Comment by frg** [comment]
How can I clone the 0.13 version @gaearon ?

**Comment by gaearon** [comment]
@frg 

```
git clone https://github.com/rackt/react-router.git#v0.13.3
```

should probably work.

https://github.com/rackt/react-router/tree/v0.13.3

also you can just `npm install react-router`, it will install stable version.

**Comment by frg** [comment]
Thanks for the quick reply!
But I'm getting this error when I try cloning

```
Cloning into 'C:/temp/react-router.git#v0.13.3'...
fatal: https://github.com/rackt/react-router.git#v0.13.3/info/refs not valid: is this a git repository?
```

**Comment by gaearon** [comment]
Sorry, I'm being dumb.
You need to clone the repo normally but then do `git checkout v0.13.3`.

**Comment by frg** [comment]
Awesome! worked. Thanks @gaearon
