### ISSUE TITLE
How to impliment a Landing page with React-router?

### ISSUE THREAD

**Issue by rahul1346** [rackt/react-router#1437]
I have an app that has a static nav-bar which routes the different views. However, I want to create a landing page for the app but don't quite understand how to impliment it with the react-router. Further, if the state of the app needs to change of the nav-bar needs to change, how do I impliment that? Do you create a new nav-bar all together?

Here is is what the routes.js look like:

'''
// React
var React = require("react");
var Router = require("react-router");
var Route = Router.Route;
var NotFoundRoute = Router.NotFoundRoute;
var DefaultRoute = Router.DefaultRoute;

var App = require('./components/App.js');
var About = require('./components/About.js');
var Concat = require('./components/Concat.js');
var Home = require('./components/Home.js');
var Login = require('./components/Login.js');
var Search = require('./components/Search');
var Signup = require('./components/Signup');

var routes = (
  <Route path="/" handler={App}>
  	<DefaultRoute handler={Home} />
    <Route name="about" handler={About}/>
    <Route name="concat" handler={Concat}/>
    <Route name="home" handler={Home}/>
    <Route name="login" handler={Login}/>
    <Route name="search" handler={Search}/> 
    <Route name="signup" handler={Signup}/>       
  </Route>
);

module.exports = routes;
'''

this is the app.js page

'''var React  = require('react');
var Navbar = require('./Navbar.js');
var Router = require('react-router');
var RouteHandler = Router.RouteHandler;

var App = React.createClass({
  render: function () {
    return (
      <div className="app-wrapper">
        <Navbar />
        <RouteHandler />
      </div>
    );
  }
});

module.exports = App;
'''

and the navbar.js

'''var React  = require('react');
var Router = require('react-router');
var Link = Router.Link;

var Navbar = React.createClass({
  render: function () {
    return (
      <div className="navbar navbar-default navbar-static-top">
        <div className="container">
          <div className="navbar-header">
            <button type="button" className="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span className="icon-bar">test</span>
              <span className="icon-bar"></span>
              <span className="icon-bar"></span>
            </button>
          </div>
          <div className="collapse navbar-collapse">
            <ul className="nav navbar-nav">
              <li className="active"><Link to="home">Jobletics</Link></li>
              <li><Link to="concat">Create a Listing</Link></li>
              <li><Link to="search">Search Jobs</Link></li>
              <li><Link to="about">About</Link></li>
            </ul>
            <ul className="nav navbar-nav navbar-right">
              <li><Link to="login">Log in</Link></li>
              <li><Link to="signup">Sign up</Link></li>
            </ul>
          </div>
        </div>
      </div>
    );
  }
});

module.exports = Navbar;
'''

If I wanted to have the landing page at default route (Home), how do I route the App from there? Ie., Home own navbar?

**Comment by mjackson** [comment]
@rahul1346 I'm sorry but we can't provide support for these kinds of questions here. Please ask us in the [`#react-router` channel on reactiflux](http://www.reactiflux.com/).
