### ISSUE TITLE
huge-apps example fails on loading?

### ISSUE THREAD

**Issue by 35leukothea** [rackt/react-router#1438]
![screen shot 2015-06-28 at 12 08 29 pm](https://cloud.githubusercontent.com/assets/1948683/8397840/74cdc614-1d8e-11e5-8f69-104ffa53a619.png)

All I got is 'Loading...' and this error in the Console. Other examples are fine.

**Comment by goldensunliu** [comment]
+1

**Comment by i-have-no-name** [comment]
Try to remove line https://github.com/rackt/react-router/blob/master/examples/huge-apps/app.js#L32, it  helped me

**Comment by shenrenguo** [comment]
+1

**Comment by kashoutinsb** [comment]
+1
example does not work...

**Comment by baodang** [comment]
I have the same problem here, other examples work fine. Can someone please have a look?

**Comment by baodang** [comment]
Seems like this commit 9dd8258d2eea7eff394dfde3c06ef847af7807eb makes it not working. If I reset to the previous commit 5bd62b5d46ac63279ba183e7eaed85e0e998466e, everything is fine.

**Comment by jonathandelgado** [comment]
upgrade your local react version to `0.14.0-beta1`

**Comment by knowbody** [comment]
all of the examples work fine now
