### ISSUE TITLE
Confusing Tutorial Section

### ISSUE THREAD

**Issue by AdamBrodzinski** [rackt/react-router#1440]
I'm brand new to React-Router and have been using React for about a week now. I tried to go through the tutorial and got hung up when I couldn't figure out why my `Message` view was not rendering. I didn't even realize that the router had nested UI rendering.

Re-reading several times I noticed a subtle hint that these UI's might nest like the App did after reading *"First we'll make a new Message component and then we'll add the route under inbox so that the UI will nest."*.

Searching on Google pulled up this [SO post](http://stackoverflow.com/questions/27612765/nested-routes-in-react-router) that confirmed that and shed some light that I needed to use `RouterHandler`.

It would be nice if something was added to let you know that the UI is nested and needs that `RouterHandler` to work.

I just wanted to let you know since I realize it can be tough to catch when you're so deep in the code.

**Comment by gaearon** [comment]
I wonder why @ryanflorence or @mjackson don't add a link to http://rackt.github.io/react-router/ in the project description. *That's* the docs for the current version on NPM. It mentions `RouteHandler` many times.

The docs in the master are referring to 1.0 which doesn't have `RouteHandler`. That's why you didn't see it.

**Comment by AdamBrodzinski** [comment]
Ah that makes sense. Also I read the the master readme first and then started reading the docs linked above. However I didn't *fully* read through the docs before writing a hello world app. I realize that's my fault, but if a user is going through step by step, adding in `RouterHandler` to Inbox is skipped. Not a huge deal but perhaps it should be fixed to have the best onboarding experience.

> Adding more UI

> Alright, now we're ready to nest the inbox messages inside the inbox UI. First we'll make a new Message component and then we'll add the route under inbox so that the UI will nest.


```js
var Message = React.createClass({
  render () {
    return <h3>Message</h3>;
  }
});

var routes = (
  <Route handler={App}>
    <Route path="about" handler={About}/>
    <Route path="inbox" handler={Inbox}>
      <Route path="messages/:id" handler={Message}/>
    </Route>
  </Route>
);
```

> Now visits to urls like inbox/messages/Jkei3c32 will match the new route and nest the UI branch of App -> Inbox -> Message.

However it only matches the router and doesn't update the UI. It only shows the Inbox heading unless you change `Inbox` to:

```js
var Inbox = React.createClass({
  render: function () {
    return <div>
      <h2>Inbox</h2>
      <RouteHandler/>
    </div>
  }
});
```

**Comment by mjackson** [comment]
I just added a link to http://rackt.github.io/react-router/ to the project description on GitHub.

@AdamBrodzinski Anything more we can do to help people in the future not be confused?

**Comment by AdamBrodzinski** [comment]
Looks good to me. 

In general I thought the guide was a really great start to get it going.
The first guide/tutorial still assumes that you change/use `<RouteHandler/>` for the nested UI in the inbox  template but I think if you read the guide all the way through before doing it than it's pretty apparent.

**Comment by theartoflogic** [comment]
I'm going through the docs today and I had the same question as @AdamBrodzinski. I assumed that I had to add `<RouteHandler/>` to the parent UI to render the child UI, but it never actually showed that in the docs (except at the root level for the main `<App />` route handler), which left me questioning whether my assumption was correct or if I was missing something.

I think it would make it clearer if you take @AdamBrodzinski's suggestion in his comment above (https://github.com/rackt/react-router/issues/1440#issuecomment-116361984) and show the updated parent UI that clearly shows that you have to embed a `<RouteHandler/>` to the UI for the child to render.

After confirming that that is how it works, reading the description of that makes more sense. Seeing an example of it would have been much more clear for me, however.

**Comment by knowbody** [comment]
this should be resolved now. also the new awesome docs are coming soon
