### ISSUE TITLE
False positives for active Links

### ISSUE THREAD

**Issue by insin** [rackt/react-router#1441]
The current implementation of `pathnameIsActive` gives false positives for what I'd expect to be a fairly common case: numbers in path parameters.

Just hit this in v1.0.0-beta2 in an app which is using the index of some items in an array as a parameter. Once you start hitting double-digit numbers, you get false positives from single-digit numbers.

![rr-false-positives](https://cloud.githubusercontent.com/assets/226692/8398974/348f996a-1dfc-11e5-8087-12eadbed2e7a.png)

In this example, the URL is `/1/10` and links for both `/1/1` and `/1/10` are marked active.

**Comment by mjackson** [comment]
Yes, [the `isActive` implementation in beta2 is incomplete](https://github.com/rackt/react-router/blob/86b3bb48457e899375b48f2cfaab4890e11ce9c0/modules/RouterContextMixin.js#L7-L16). It also gives false positives in the situation where one URL looks like the beginning of another. We definitely need to fix this before 1.0.

**Comment by insin** [comment]
It seems like ensuring there are slashes on the end of the URLs being compared would eliminate at least one class of false positives (`/1/10/` does not start with `/1/1/`).

Do you have a set of test data in mind which covers other scenarios the implementation of `isActive` needs to address?

**Comment by gonsfx** [comment]
+1

Should take route hierarchy into account, e.g.

```jsx
<Router history={new BrowserHistory}>
  <Route component={App}>
    <Route path="/" component={HomePage}>
      <Route path="nested" component={NestedPage}>
        <Route path="nested" component={NestedPage} />
      </Route>
      <Route path="nest" component={NestPage} />
    </Route>
    <Route path="some" component={SomePage} />
    <Route path="other" component={OtherPage} />
  </Route>
</Router>
```

**Comment by gonsfx** [comment]
When should links actually be active? Looking at the routes from my previous comment, i'd propose this:

Any Opinions?

Link | URL `/` | URL `/nested` | URL `/nested/nested` | URL `/nest` | URL `/some`
--- | :---: | :---: | :---: | :---: | :---:
`/` | ✔ | ✔ | ✔ | ✔ |
`/nested` | | ✔ | ✔ | |
`/nested/nested` | | | ✔ | |
`/nest` | | | | ✔ |
`/some` | | | | | ✔

Theres a few more complicated options regarding edge cases like nested paths starting with slashes, the `absoluteChildPaths`option and others yet unknown to me.

**Comment by Schniz** [comment]
@gonsfx seems best to me

**Comment by johanneslumpe** [comment]
@gonsfx I'm not quite sure I like the fact that you nest `/root` below the `/` path, but then don't want that one to be marked as active. Feels a bit counter intuitive to me. Since there really is no difference between `/nested` and `/root`. Or am I missing something significant here?

**Comment by Schniz** [comment]
@johanneslumpe I missed it! if you nest `/root` under `/`, then `/` is active on `/root`.

**Comment by gonsfx** [comment]
@Schniz Thats what it's like atm.
I'd rather discuss what we want the new, bugfixed version of active links to look like.

@johanneslumpe It's for use-cases where you'd want to nest Components, but not nest the URL path structure.

**Comment by johanneslumpe** [comment]
@gonsfx I might be wrong but that does seem like a very tiny edge-case to me. If you don't want to nest urls, then don't nest them. You could add them to a different wrapper route. I know this would lead to a duplication of the container route, but I feel that the desired might be confusing to users. I'm not super against it I just think that it should be evaluated whether this desired functionality is useful for most users or whether it makes things more complicated to understand for them.

**Comment by gonsfx** [comment]
@johanneslumpe I'm with you on this and as of now not a contributor to this repo. What i need to even think about starting to work on this issue is a clear, understandable ruleset of how nesting of routes does and doesn't work with all edge-cases either eliminated or defined.

**Comment by gonsfx** [comment]
@mjackson @ryanflorence Can you help clarifying?

**Comment by ryanflorence** [comment]
When a route is active, it, and all of its parents, are also active, it has nothing to do with the URL. Routes can be nested, even if the urls are not.

```js
<Route path="/">
  <Route path="users">
    <Route path=":user_id"/>
    <Route path="/profile/:user_id"/> {/* <-- not a nested url, but a nested route with an absolute path */}
  </Route>
</Route>
```

So when the users hits `/profile/123` the parent routes with paths `/users` and `/` will be active, even though their URLs don't "match".

We haven't completely tackled handling these kinds of urls in the code on master yet, it might be possible already with `route.getChildRoutes`.

So, to reiterate, if a route's path is matched exactly, it is active and so are all of its parent routes.

On master, the only difference right now should be that we don't declaratively support "absolute paths"

**Comment by gonsfx** [comment]
Works fine in the `render` method of a `Link` - except when it encounters absolute URLs or path patterns:

```javascript
if (router) {
  // ignore if rendered outside of the context of a router, simplifies unit testing
  _RoutingUtils.getState(router.routes, router.state.location, function (error, state) {
    let toPaths = (res, branch) => {
      if (branch.path) {
        res.push([
          (res[res.length - 1] || '').replace(/\/$/, ''),
          branch.path.replace(/^\//, '')
        ].join('/'));
      }
      return res;
    };

    if (state.branch.reduce(toPaths, []).indexOf(to) > -1) {
      if (props.activeClassName)
        props.className += (props.className !== '' ? ' ' : '') + props.activeClassName;
      if (props.activeStyle)
        props.style = _extends({}, props.style, props.activeStyle);
    }
  });
}
```

**Comment by mjackson** [comment]
This should be fixed in master [with a bunch of tests as well](https://github.com/rackt/react-router/blob/c9ae5e0d4cd9a405c5bf478e9d86547bcc964098/modules/__tests__/Link-test.js#L78-L226).

@gonsfx @insin If you'd like to add some more tests just to make sure we don't regress here, that would be great.

**Comment by gonsfx** [comment]
It doesn't work good enough as far as i'm concerned. It's not working with route params and not absolute URLs. I'm not familiar enough with all the internals yet, just wanted to give a starting point for someone.

**Comment by gonsfx** [comment]
See #1561 and #1800

**Comment by knowbody** [comment]
I started working on that, should send a PR soon, hope not overlapping on this with anyone

**Comment by jedwards1211** [comment]
Given that I've often wanted to have route structures like this, where `Home` links only appear active when the user is at `/` and not `/about`:

```
<Route component={App}>
  <Route path="/about" component={About}/>
  <Route path="/" component={Home}/>
</Route>
```

I think a separate built-in concept of "deepest active route" (or whatever term the community decides is clearest) would be very useful.  Then we could keep `activeClassName` as people are discussing here, but I could write: `<Link to="/" deepestActiveClassName="active">Home</Link>`.

**Comment by ryanflorence** [comment]
I think #1842, `<IndexRoute/>` and `<IndexLink/>` address almost everything here.

Only think missing is "I am active only when I'm the deepest active route", would love for somebody to create a `<ExactLink/>` or `<Link to="/wherever" exact/>` or something.

**Comment by jedwards1211** [comment]
Are `<IndexRoute/>` and `<IndexLink/>` documented anywhere?

**Comment by jedwards1211** [comment]
Nevermind, easy enough to find in the code

**Comment by jedwards1211** [comment]
I take it back again...I'm not sure I grok from the terminology or the code what `<IndexRoute/>` and `<IndexLink/>` mean?

**Comment by gonsfx** [comment]
What's the reasoning behind having multiple Components for that? Wouldn't it be possible to do all of this with a simple `Link` component just by parsing the Route Tree?

**Comment by ryanflorence** [comment]
`<IndexRoute/>` is exactly like `<DefaultRoute/>` from 0.13.

In 0.13 you could link to a route by name, in 1.0 we have no more route names, therefore ...

```js
<Route path="/" component={App}>
  <IndexRoute component={Index}/>
  <Route path="about" component={About}/>
</Route>
```

How do you create a link to `Index` that isn't active **all the time**.

`<Link to="/">Index?</Link>` will be active **always**

In 0.13 we could name the route and link to it and then it would only be active if you were actually rendering the `Index` component.

So for 1.0, we need a way to create a link to `/` that is only active when the `IndexRoute` at that location is active.  We though of either `<IndexLink to="/" />` or `<Link to="/" index />`.

Without route names, `IndexLink` or an option for `Link` there is no amount of sophistication to know when you want that link to be "active" or not.

**Comment by jedwards1211** [comment]
Ah, cool, that makes perfect sense.

**Comment by th0r** [comment]
@ryanflorence Another argument to bring route names back ;)

**Comment by gonsfx** [comment]
@ryanflorence whats the difference between the route snippet you posted above and this one:

```
<Route component={App}>
  <Route path="/" component={Index}/>
  <Route path="about" component={About}/>
</Route>
```

If it is basically the same (except the `isActive` of Links pointing to the `Index` component) - wouldn't it be possible to get the desired behaviour by looking at the route tree and their paths alone?

**Comment by taion** [comment]
`IndexLink` in RC4 actually does behave like the `ExactLink` described above - there wasn't an easy way to get it to work otherwise.
