### ISSUE TITLE
Bug: reason is not defined in Router.js

### ISSUE THREAD

**Issue by juhaelee** [rackt/react-router#1442]
https://github.com/rackt/react-router/blob/v1.0.0-beta1/modules/Router.js#L141

@mjackson Should this line be: 
```javascript
this.handleAbort(transition.abortReason)
``` 
?

**Comment by mjackson** [comment]
This is [already fixed in master](https://github.com/rackt/react-router/blob/9dd8258d2eea7eff394dfde3c06ef847af7807eb/modules/Router.js#L141).
