### ISSUE TITLE
Re-render child routes/pass children as function?

### ISSUE THREAD

**Issue by matthewwithanm** [rackt/react-router#1444]
Currently, react-router composes the component hierarchy by pre-rendering children and passing the resulting elements to their parent's route component. If I'm understanding right, that means that components higher up in the tree can't trigger re-renders of those below them (for example, by calling `forceUpdate()`). Instead, the router itself needs to be re-rendered.

We came across this issue while attempting to give a Flummox Flux instance access to the router:

```
<Router>
  <Route component={FluxContext}>
    <Route ... />
    <Route ... />
  </Route>
</Route>
```

FluxContext is a component that creates a Flummox instance and adds it its child context; when one of the stores changes, we want to re-render the app. However, calling `forceUpdate` won't work because the children are already rendered.

My apologies if I'm misunderstanding something, or there's a rationale behind this I'm just not getting but it seems like this would be a useful feature. One possibility would be to pass a child factory instead of pre-rendered elements. This could definitely impact performance adversely but it would restore the normal order of things (parents deciding when to render children), and be optimizable with the normal techniques (`shouldComponentUpdate`).

Thanks!

**Comment by taurose** [comment]
> If I'm understanding right, that means that components higher up in the tree can't trigger re-renders of those below them (for example, by calling forceUpdate()).

I don't think that's the case. You should still be able to re-render child components using `setState` or `forceUpdate` (`shouldComponentUpdate` aside). You just can't change child props as easily anymore (you have to use `React.cloneElement` for that).

Looking at your code, there could be some problems with passing down context though, since `FluxContext` isn't the *owner* of the child handler anymore, but only its *parent*. I think this will be fixed in React 0.14. Until then, using `React.cloneElement` on `this.props.children` in `FluxContext` should fix it.

**Comment by matthewwithanm** [comment]
Sorry, I should've mentioned that I'm using 0.14 (specifically to avoid that) so that's not an issue.

Cloning the element will re-render that one, but it's not "deep," so the children (passed in as props) don't get re-rendered.

**Comment by taurose** [comment]
I'm not sure I understand your issue. The way I see it, you're still in control of the rendering itself, and route components will  be re-rendered with their parents in the sense that their lifecycle methods will be called. All the router does is create the ReactElements (descriptors) and pass them as ReactNodes (renderables) to your components.

**Comment by lettertwo** [comment]
[Here's a pen][1] that illustrates the problem. It's not related to context, but when things are re-rendered so, while the example uses React 0.13, it behaves the same in 0.14. The pen shows a bunch of different methods of composing elements, including the one used by RR, and how they affect re-rendering.

[1]: http://codepen.io/anon/pen/rVpXJa?editors=001

**Comment by taurose** [comment]
Interesting. Thanks for putting that up! Looks like this is an optimization described in detail here https://github.com/facebook/react/issues/4067#issuecomment-110792425 .

Not sure what to do about it. Sounds like `shouldUpdateChildContext` or "sideways data-loading"  in React would be the best solution for this use case. 

What seems to work now is to use the `createElement` hook:

```js
var createElement = (Comp, props) => {
  // root has to be normal element
  if (Comp === FluxContext) {
    return <Comp {...props} />;
  }

  return {
    createChildren: (extraProps) => <Comp {...props} {...extraProps} />;
  };
};

// start router
<Router createElement={createElement}>..</Router>

// route components
render() {
  return this.props.createChildren();
}
```

**Comment by ryanflorence** [comment]
^ this is what `createElement` is for, thanks @taurose :)
