### ISSUE TITLE
Cannot read property 'makeHref' of undefined error when rendering <Link> component

### ISSUE THREAD

**Issue by brti** [rackt/react-router#1446]
I'm getting the `Cannot read property 'makeHref' of undefined` error when I'm trying to render the `<Link />` component. My component which is rendering the `<Link />` component:

    import { Router, Link } from 'react-router';

    class RoomList extends React.Component {
	    constructor(props) {
		    super(props);
	    }
	
	    render() {
		    var roomNodes = this.props.rooms.map(function(room) {
			    return (
				    <div key={room.id} className="room-item">
					    <Link to='room' params={{ id: room.id }}>{room.name}</Link>
				    </div>
			    );
		    });
		
		    return (<div className="room-list">{roomNodes}</div>);
	    }
    }

    export default RoomList;

Any ideas what could be causing this?

**Comment by mjackson** [comment]
It sounds like you're using beta2. This issue has already been fixed in master.

**Comment by Peege151** [comment]
I'm getting this error in 0.13.3

**Comment by MinThaMie** [comment]
I get the same error, also using 0.13.3. Would be awesome if this could be fixed!

**Comment by pedrodelgallego** [comment]
same error using 0.13.3

**Comment by airwin** [comment]
https://github.com/rackt/react-router/issues/982#issuecomment-86065078 
Works~!

**Comment by labs00** [comment]
0.13.4....
