### ISSUE TITLE
[1.0.0-beta2] Are nested routes with leading slashes still concatenated?

### ISSUE THREAD

**Issue by doctyper** [rackt/react-router#1450]
In react-router 1.0.0-beta2, nesting routes with leading slashes does not reflect the documentation here: http://rackt.github.io/react-router/tags/v1.0.0-beta2.html#-path- .

For me, the routes are still concatenated. Is there something I'm doing wrong?

```jsx
<Route path="/example" component={Example}>
    <Route path="/nested-example" component={NestedExample} />
</Route>
```

**Result:** `Example`'s route is `/example`, `NestedExample`'s route is `/example/nested-example`
**Expected:** `Example`'s route to be `/example`, `NestedExample`'s route to be `/nested-example`

**Comment by ryanflorence** [comment]
master now behaves like 0.13, nesting is inherited, absolute (start with `/`) are not nested.
