### ISSUE TITLE
How to do anchor aka "hash" links?

### ISSUE THREAD

**Issue by benknight** [rackt/react-router#1454]
Say I have some `<div id="my-section"> ... </div>`, how do I link to this section of the page?  This is a really useful feature of the web.

**Comment by mouhsinelonly** [comment]
+1

**Comment by benknight** [comment]
I can't remember if I closed this because I found a duplicate issue or if I actually figured out how to do it.  Anybody know the status of this feature?

**Comment by igl** [comment]
+1

I use history locations only and want the original behavior for hashlinks back!

**Comment by davis** [comment]
how do you do this?

**Comment by zdavis** [comment]
+1

**Comment by pratyushmittal** [comment]
@darobin Can you please provide details about how did you fix the normal anchor links? Using `a[href="#some_id"]` still calls `createBrowserHistory()` leading to a full React re-render.

**Comment by darobin** [comment]
@pratyushmittal I haven't checked but I believe in my case it is also still re-rendering. After all, it does change the route. But it works: the browser navigates to the hash, which is the desired behaviour. In my case the re-render isn't an issue, the route only affects topmost components, the rest won't see the change.

**Comment by Agalla81** [comment]
I do see as problematic that the re-render is triggered, since navigating within sections on the same page then causes an unnecessary performance overhead.

Is there any supported way to prevent re-rendering while using named anchors to sections on the same page?

**Comment by chrisdobler** [comment]
+1

**Comment by pepavesely** [comment]
Any progress on this subject? I wonder why the issue is closed. React is still re-rendering pages.

**Comment by nujhong** [comment]
As a workaround, I think you can respond to `LOCATION_CHANGE` and perform reconciliation based on the `hash` property of the payload.

**Comment by akhilaudable** [comment]
Any progress here? If there is duplicate issue, can anyone please provide URL of that issue?
