### ISSUE TITLE
Passing Data though Routes

### ISSUE THREAD

**Issue by Oyed** [rackt/react-router#1458]
Hey there,

I think the ability to pass data through Routes, without having the Data as a parameter, would be great. For example, if I wanted to pass through which Template I'd like different pages to use:

```
<Route path="/" handler={ App }>
	<DefaultRoute handler={ Dashboard } data={{ template: 'panel' }} />

	<Route name="welcome" handler={ Splash } data={{ template: 'splash' }} />
</Route>
```

Am I blind and there is a way of doing something like this? I couldn't find anything in the Docs.

**Comment by tmbtech** [comment]
Route doesn't pass props like that, try creating a factory function that will return a react element. 
```
<Route name="Welcome" handler={SplashFactory({foo:bar})} />
```

```
export default (data) => {
 return <Splash data={data} />
}
```

**Comment by ryanflorence** [comment]
master branch (1.0) lets you add whatever meta data you want to your routes and it will be available where you've got a handle on the route
