### ISSUE TITLE
How to upgrade unit tests dependent on TestLocation?

### ISSUE THREAD

**Issue by kevzettler** [rackt/react-router#1460]
I have some unit tests dependent on :
`TestLocation = require('react-router/lib/locations/TestLocation');`

I'm trying to upgrade to 1.0.0 beta and see that this is `TestLocation` no longer in the repo.

Whats the upgrade path here?

**Comment by taion** [comment]
I just had the same question. Looks like the answer is `MemoryHistory`.

**Comment by kevzettler** [comment]
:+1: will close once confirmed

**Comment by knowbody** [comment]
for that use `createMemoryHistory` from [History](https://github.com/rackt/history)

It's also included in [Getting started](https://github.com/rackt/history/blob/002a0443a653f24d4f21ad4ee4e308f91ccea46b/docs/GettingStarted.md#getting-started) docs
