### ISSUE TITLE
transition.to with nextPathname does not work

### ISSUE THREAD

**Issue by lancetw** [rackt/react-router#1467]
nextPathname is not working like v0.13.x nextPath, I've already tried v1.0.0-beta3.

ref: react-router/examples/auth-flow
```
transition.to('/login', null, { nextPathname: nextState.location.pathname })
```

It does not work well when `onEnter`.

**Comment by lancetw** [comment]
I noticed it must work with `this.replaceWith`, Sorry for the noise.

**Comment by Shachar16290** [comment]
'I noticed it must work with location.state.nextPathname and this.replaceWith, Sorry for the noise.'

@lancetw  Can you explain?
