### ISSUE TITLE
./routes file is missing from Server Rendering Guide

### ISSUE THREAD

**Issue by weisjohn** [rackt/react-router#1468]
On https://github.com/rackt/react-router/blob/master/doc/00%20Guides/Server%20Rendering.md, both the client and server import something from a `./routes` file, but there's no example of what `./routes` exports.

**Comment by nadav-dav** [comment]
just a temp solution, the `./routes` is an array of the routes you have.
```
[
        <Route path="/" component={Main}>
          <Route path="home" component={Home}/>
          <Route path="about" component={About}/>
        </Route>,
        <Redirect from="*" to="home"/>
]
```

**Comment by ryanflorence** [comment]
its just your route config, as used everywhere else:

```js
var routes = (
  <Route>
    <Route/>
    <Route/>
  </Route>
)
```
