### ISSUE TITLE
Change hash or history inside iframe context

### ISSUE THREAD

**Issue by ryanseddon** [rackt/react-router#1469]
I want to be able to use react router with my [frame-component](https://github.com/ryanseddon/react-frame-component) and have contents render in the frame, that bit works fine. 

Switching routes from within the iframe effects the host pages location as the code assumes you always want to change the window object that the script is loaded in.

I hacked it into the `Link` component doing the following:

```js
this.context.router.transitionTo(this.props.to, this.props.query, this.props.state, this.getDOMNode().ownerDocument.defaultView);
```

In `HashHistory.js` the argument is passed in and window is the right context. This works for my contrived demo and the route updates `location.hash` of the iframe.

```js
pushState(state, path, window) {
  //...
  window.location.hash = path;
}
```

Any thoughts on how this could be implemented in a nicer fashion? Would love to contribute a PR just not sure if it's possible to get the right `window` everywhere it's used.

**Comment by darkyen** [comment]
Same here !

**Comment by ryanflorence** [comment]
sounds interesting, please holler when the 1.0 dust settles

**Comment by taion** [comment]
Re-file this against `history` if it's still a concern - probably should be using `ownerDocument` or `ownerWindow` there as appropriate.
