### ISSUE TITLE
1.0.0-beta3 - best approach for DefaultRoute functionality?

### ISSUE THREAD

**Issue by MandarinConLaBarba** [rackt/react-router#1470]
I'm trying to implement something like `<DefaultRoute/>`, which doesn't appear to exist in `1.0.0-beta3`. I have this working w/ a `<Redirect/>`, but is there a recommended approach for this?

Example:

```
<Route path="dash" component={...}/>
<Route path="/some/other/page" component={...}/>
<Redirect from="*" to="dash"/>
```

**Comment by modernserf** [comment]
There are a couple of approaches: 

 #1315 suggests handling the default in the parent's render method:
```
render() {
    return <div>
        {this.props.children || "This is the default text"}
    </div>
}
```
#1333 suggests no path on the parent; the index and detail are siblings.
```
 <Route component={App}>
    <Route path="/" component={DefaultView}/>
    <Route path="/eg1" component={View1}/>
    {/* ... */}
</Route>
```

I'm not sure which one is to be preferred. I've been doing the latter, but it gets a little unwieldy if you have nested default views for something like <Route path="/foo/:group/:id/:section" />

**Comment by MandarinConLaBarba** [comment]
Cool thanks!

**Comment by goncalvesjoao** [comment]
Hi guys, I've being using both of these examples [#1474](https://github.com/rackt/react-router/issues/1474) but I'm getting a warning using the
```
{this.props.children || "This is the default text"}
```
approach and the
```
<Route path="/" component={DefaultView}/>
```
doesn't work for nested routes.

Do you guys, have any suggestions to avoid that warning?

**Comment by MandarinConLaBarba** [comment]
In my initial question I mentioned I'm doing this:

`<Redirect from="*" to="dash"/>`

Which actually works fine for me. Probably some would consider this an abuse, but logically I see this as, "anything that didn't get matched by more specific rules, go to 'dash'"...so I'm not too broken up about this. Remains to be seen if I'll run into issues w/ this down the road..

**Comment by aluksidadi** [comment]
Hi im also looking for an elegant solution to this matter..

I have several mini apps that runs on different root path
```
<Route path='app1' component={App1}>
  <Route component=App1Dashboard>
  ...
</Route>
<Route path='app2' component={App2}>
  <Route component=App2Dashboard>
  ...
</Route>
```

i cant seem to make `/app1` and `/app2` to work
the child routes work though. e.g.: `/app1/blah`, etc..

**Comment by itszero** [comment]
I ended up need to implement my own DefaultRoute that override onEnter to do so. I'm curious to see if there's a better solution to this.
