### ISSUE TITLE
How to handle components that receive props in 1.0?

### ISSUE THREAD

**Issue by togakangaroo** [rackt/react-router#1472]
I think this is more an issue of documentation than anything but I'm pretty confused about what the intended workflow is.

Let's say I have a menu system where clicking on each item uses react-router to navigate to an area which pulls some data from the server.

```
url: yoursite/#/lists/countries
----------------------------
Billing Codes | <<Countries>> | Inventory Types 
---------------------------------------------------------
Countries:
---------------
Afghanistan
Azerbaijan
Belarus
```

with routes something like

```
Route #/lists component: Lists
   Route billing-codes component: BillingCodes
   Route countries component: Countries
   Route inventory-types component: InventoryTypes
```

I don't want to preload data from the server until an area is navigated to, so in my `Countries` component's on `componentWillMount` I fire an event (I'm using reflux but...whatever) that triggers a store to do an ajax request and update itself with the current list of countries.

Now the `Countries` component reacts to that change in state by updating the countries in its props. Except - reasonably - that generates an invariant error because I shouldn't be updating props on a child component, I should update it at the top level. But the top level is the router itself so now I'm just lost - where *am* I supposed to listen to changes and update props from?

**Comment by Sinewyk** [comment]
I would suggest you start implementing the Container/Component separation. It makes everything easier.

link: https://medium.com/@learnreact/container-components-c0e67432e005.

Then all your routers handlers should be Containers, implementing fetching logic, and dispatching it to components who are all similar to pure functions.

**Comment by taurose** [comment]
> Now the Countries component reacts to that change in state by updating the countries in its props. Except - reasonably - that generates an invariant error because I shouldn't be updating props on a child component, I should update it at the top level. But the top level is the router itself so now I'm just lost - where am I supposed to listen to changes and update props from?

Not sure what you're saying here. Parent components updating their children by changing their props is a normal thing. In your case, `Countries` could submit the action to fetch countries as you said, and then call `setState({countries: store.countries})` when the data arrives (not `setProps` if that's what you did). Then, inside `render()`, you could pass `this.state.countries` to child components as props.

**Comment by togakangaroo** [comment]
Yeah - ok, so that maybe gets to the heart of it @taurose as that's what I've seen in the few samples I was able to find. Is the intended workflow to always use state and not props here?

**Comment by knowbody** [comment]
Yes, the correct workflow is the one @taurose suggested.
