### ISSUE TITLE
How to save current route status when browser refresh?

### ISSUE THREAD

**Issue by chenmnkken** [rackt/react-router#1473]
Hello, I use HistroyLocation running some routes, when link to `/path-a`, the router is work, like a real page. But now, I refresh current page, this `/path-a` status is lost, can not save current route status.

How can i do for this problem? Please help me, thanks.

**Comment by suryagaddipati** [comment]
i am not sure what you mean by  `status is lost` . Can you link me to what `route status ` is .

**Comment by chenmnkken** [comment]
If i link to `/path-a`, now I use browser refresh, the page is 404.

**Comment by chenmnkken** [comment]
Oh, i find `HistoryLocation` detail api docs, i need config my server.
Just like:

```
app.get('*', function (req, res) {
  res.render('index');
});
```
