### ISSUE TITLE
React-Router v0.13.3 when using es5 Shim / Sham (v4.1.7) and V 0.13.3 of React always throws the error ERR_ACCESSORS_NOT_SUPPORTED in IE8 

### ISSUE THREAD

**Issue by hufeng** [rackt/react-router#1475]
React-Router v0.13.3 when using es5 Shim / Sham (v4.1.7) and V 0.13.3 of React always throws the error ERR_ACCESSORS_NOT_SUPPORTED in IE8

**Comment by cateland** [comment]
Since react router 1.0 will be released soon i don't know if it is intended to maintain legacy branch. Anyway you can fork the project and update the webpack config file with babel --loose option
```javascript
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel?loose=all' }
    ]
  },
```
it should be enought

**Comment by hufeng** [comment]
@cateland thank you. i try it 

Warning: Failed Context Types: Required context `routeDepth` was not specified in `RouteHandler`. Check the render method of `App`.
2015-07-04 15:43:40.393bundle.js:8168 Warning: Failed Context Types: Required context `router` was not specified in `RouteHandler`. Check the render method of `App`.
in chrome.

**Comment by hufeng** [comment]
it's ok. #1143 

browser-polyfill.js is needed.
