### ISSUE TITLE
Errors while trying to run examples

### ISSUE THREAD

**Issue by alekbarszczewski** [rackt/react-router#1479]
I am trying to run examples. I followed instructions from [here](https://github.com/rackt/react-router/blob/master/examples/README.md).

* In console (after running `npm run examples`) I get following error:

![screen shot 2015-07-04 at 10 25 50](https://cloud.githubusercontent.com/assets/2742373/8507189/b6233a9c-2237-11e5-9960-ca5da573eb2d.png)

* When I visit `localhost:8080` and click a link to any of the examples, then I see this in browser console:

![screen shot 2015-07-04 at 10 26 12](https://cloud.githubusercontent.com/assets/2742373/8507199/df0e0018-2237-11e5-8805-e9b880f41e8b.png)

Any idea what might be wrong? (I am using node v0.10.32 on Mac OS)

**Comment by knowbody** [comment]
Are you sure `npm install` did not fail? It works fine for me, maybe try removing `node_modules` and install them again.
