### ISSUE TITLE
Inconsistent documentation on how to bootstrap react-router

### ISSUE THREAD

**Issue by apoco** [rackt/react-router#1481]
In `README.md`, a `Router` component is used to created a routed application:

```javascript
React.render((
  <Router history={history}>
    <Route path="/" component={App}>
      <Route path="about" component={About}/>
      <Route path="users" component={Users}>
        <Route path="/user/:userId" component={User}/>
      </Route>
      <Route path="*" component={NoMatch}/>
    </Route>
  </Router>
), document.body);
```

However, the homepage documentation has this:

```javascript
Router.run(routes, Router.HashLocation, (Root) => {
  React.render(<Root/>, document.body);
});
```

It's unclear due to these differing bootstrapping instructions whether one set of documentation is out of date or if both are supported since `README.md` doesn't mention `Router.run` and the homepage documentation doesn't even mention the `Router` component.

**Comment by cateland** [comment]
Router.run is meant to be used in 0.13.3

when React.render is meant to be used in the upcoming 1.0.0 version.

So the readme.md on the master branch show instruction for 1.0.0 beta-3 when the root of the documentation page show instruction for the stable 0.13.3 version.

Maybe a big version number on both readme.md and documentation page would do the trick ?

**Comment by gonsfx** [comment]
That or having the upcoming versions in version branches and having the current npm release in `master`.

**Comment by reduxdj** [comment]
+1 - this repo is driving me crazy, i don't understand.

**Comment by skaapgif** [comment]
Also struggled to get react-router running and found many unanswered stackoverflow questions with the same problem. Version branches would greatly simplify this.

**Comment by gonsfx** [comment]
From my experience it was actually quite hard to get it running for a project with a user-base this large and so much documentation available.

I think this might be a serious problem for new users.

**Comment by SirCmpwn** [comment]
Super confused right now. WTF?

**Comment by hiddentao** [comment]
Yep, I'm really struggling here too. I got `1.0.0-beta3` and was confused to find that `Router.run` doesn't even exist.

**Comment by gaearon** [comment]
Hopefully this helps: https://github.com/rackt/react-router/commit/44a1692d97b95cd4f1cf995d97a55eb2da7dcd86.

Please don't look into repo for documentation.
The repo reflects a work in progress (it's `master` after all).

There's a website that reflects the stable version: http://rackt.github.io/react-router
By default it reflects `react-router@0.13.3` which is what you get when you `npm install react-router`.

There's also a combobox there that lets you choose the version you want to see the docs for.

**Comment by apoco** [comment]
The note at https://github.com/rackt/react-router/commit/44a1692d97b95cd4f1cf995d97a55eb2da7dcd86 helps, but it ought to be on the root `README.md` to more quickly dispel confusion.

**Comment by gonsfx** [comment]
This is a first step, but still misleading.

In the software projects i've worked on, the `master` always had the current, stable version and works in progress were either in their own respective branches or tagged in a development branch.

@gaearon When linking to GitHub from the docs - would you mind always linking the version of the code the documentation is referring to? After all, the `examples` directory in the sources is as much help to some people as is the documentation. Getting directed to `examples` that don't reflect the doc state is what happened to me.

**Comment by gaearon** [comment]
I added a note to README: https://github.com/rackt/react-router/commit/50c9a232e25e30c6f1f9cb015f141020b51b61aa.

>In the software projects i've worked on, the master always had the current, stable version and works in progress were either in their own respective branches or tagged in a development branch.

That's how it used to be here, too. But 1.0 took way longer to polish than expected after the merge of a long-running branch into master. Sorry for the inconvenience it caused.
