### ISSUE TITLE
HistoryLocation with Rails route

### ISSUE THREAD

**Issue by jmca** [rackt/react-router#1484]
I'm trying to integrate react-router with a Rails backend. The current Rails for the SPA is:
```
get '/*path' => redirect('/')
```

Here is my current client route structure:
```
<ReactRouter.Route name="index" path="/" handler={HzAppComponent}>
  ...
    <ReactRouter.Route name="about" path="about" handler={AboutPageComponent}/>
</ReactRouter.Route>

...

ReactRouter.run(routes, ReactRouter.HistoryLocation, function (Root) {
    React.render(<Root/>, document.body);       
});
```

What is the correct way to set up a Rails route to render the url `....com/about/`?  Right now it always leads to the root route.

**Comment by jakobdamjensen** [comment]
@jmca does this help? http://stackoverflow.com/questions/12116804/what-should-my-rails-routes-look-like-to-work-with-pushstate-ember-js-routes ?

From what I can tell your route isn't hooked up to any controller... I'm a bit rusty in the Rails world... hope it helps

**Comment by jmca** [comment]
@jakobdamjensen Thanks for the tip, I was banging my head against the wall. I guess I can't use a normal redirect so I tried your suggestion:
```
class ReactController < ApplicationController
    def index
        render :file => 'public/index.html', :layout => false
    end
end
```
and added the route:
```
get '/*path' => 'react#index'
```
And things seem to be working.

**Comment by jakobdamjensen** [comment]
@jmca great... remember to close the issue then so the hard working react-router maintainers don't have to look into this :)
