### ISSUE TITLE
How to build a navigation controller?

### ISSUE THREAD

**Issue by ccorcos** [rackt/react-router#1485]
This router is really cool! I love the way it abstracts your layout along with the routes. 

I've been trying to build the concept of a [UINavigationController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationController_Class/) and [UITabBarController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITabBarController_Class/) for React. This router looks pretty neat and I think it would be really cool to use a similar pattern to this router but I'm struggling to come up with something...

Have you guys thought much about this? 

For example, imagine you have a simple social app like Twitter or Instagram. You can keep clicking through nested User / Post views forever and back out of them in order. But you can't just use browser history because there is a different navigation controller of each tab.

Imagine you have 3 tabs: profile, feed, and search. 

```jsx
<Router history={history}>
  <Route component={App}>
    <Route path="profile" nav={profileNavController} component={Profile}/>
    <Route path="feed" nav={feedNavController} component={Feed}/>
    <Route path="search" nav={searchNavController} component={Search}>
    <Route path="post/:id" component={Post}/>
    <Route path="user/:id" component={User}/>
  </Route>
</Router>
```

Each has its own navigation controller passed as props. So perhaps for linking, we could do something like this:

```jsx
<Link to={'/user/' + id} push={this.props.navController}>{username}</Link>
```
 
Still trying to figure this out. But is this something of interest to anyone?

**Comment by zdespolit** [comment]
Am I understanding it right that a) you want to have a component that allows to have some standard navigation between views (with that pretty right to left transitions maybe) and b) that navigation between this views should not write to history (or at least be optionated)? 

If it's true then I see at as you should create your own Component which will handle this stuff. As for me this is not direct responsibility of the routing library but I'm nobody here. 

Do you already have something on this?

**Comment by ccorcos** [comment]
Yeah, its probably not the best to do with the router actually, but perhaps there could be some way. Imagine an app like Instagram. There are multiple Tabs which each have their own Nav history. Right now I'm building it much like the React Native NavigatorIOS API. This means lots of function callbacks, etc. but I really like how this Router somehow gets away with laying things out more declaratively.
