### ISSUE TITLE
1.0.0-beta3: Router Run client side

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#1486]
First, I'm all about Universal JavaScript.

While I think the move to make Router a component is an awesome idea, it doesn't work that great when you are working server side with apps where some routes are react and some are not. It also breaks the symmetry that I like when building universal apps.

While server side Router Run works great and everything renders correctly, client side Router Component expects something different and fails.

It seems like it runs the exact same code that Router run goes when given a history object instead of a location object. 

I think there is a pretty simple solution:
```
if (history) {
  if (components and branch and params) {
    return setState({ components, branch, params })
  }
  // make componets from children
```
I'll be forming a PR soon if no one disagrees as I need this functionality to move forward. I'd like to open a discussion here and see if this is something RR team would like to support.

**Comment by ryanflorence** [comment]
closing in favor of conversation on the PR
