### ISSUE TITLE
Same component mount after route change

### ISSUE THREAD

**Issue by theaqua** [rackt/react-router#1487]
Hi!

I have that definition:

      <Route handler={PropertiesView} name="properties" path=":dealKind" />

In `PropertiesView` I have `constructor` and `componentDidMount` handler. In both I trying catch (with `console.log(this.props.params)` new `dealKind` (`sale` or `rent`, for example), but it works only in `render`. Why component doesn't unmount after params change?

**Comment by taurose** [comment]
When only the params change and the same handler is rendered, the handler won't remount; it'll only be rerendered, just like children in React won't be remounted by changing their props (except key). So you don't get `componentDidMount`, but `componentWillReceiveProps`.

**Comment by theaqua** [comment]
Well, `componentWillReceiveProps` works great, you're right. Thanks!

**Comment by BernhardBezdek** [comment]
Hi @theaqua  your comment helped me a lot initially but I ran into a further problem when using ``componentWillReceiveProps``

My problem is that when ``componentWillReceiveProps`` is executed there are still the old (previous ) properties (``this.props.params``) present..

I was able to write a 'dirty' workaround using timeout.

```
 componentWillReceiveProps() {
     setTimeout(function () {
         this.toApiUrl(this.props.params);
     }.bind(this), 1);
 }
```

Do you have any suggestions how to get it?

**Comment by calmdev** [comment]
@BernhardBezdek  you need to look at `nextProps`.

```javascript
componentWillReceiveProps(nextProps) { ... }
```

http://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops

**Comment by L3V147H4N** [comment]
is there a way to remount manually?

**Comment by ferggren** [comment]
For me, that worked
```
  getInitialState(props) {
    props = props || this.props;

    return {
      //...
    }  
  },
  componentWillReceiveProps(nextProps) {
    this.setState(this.getInitialState(nextProps));
    this.componentDidMount();
  },
```

**Comment by boblauer** [comment]
There is a cleaner way to remount manually:

```jsx
<Router exactly path="/whatever/:value" component={withRemounting(MyComponent)} />

// ...

function withRemounting(Component) {
  return props => <Component key={props.location.key} {...props} />
}
```

React treats the `key` prop differently in that it remounts the component when it changes.  `props.location.key` changes every time we change the url via React Router. Therefore, we can combine those two things to always remount our component, even if just the route parameter has changed.
