### ISSUE TITLE
Router <Redirect /> not working properly

### ISSUE THREAD

**Issue by dgrana** [rackt/react-router#1489]
Hi there,

I'm making a redirect from one url to another:
<Redirect from="/news" to="/careers" />

This works for all links on the site who links to /news, however it won't work if i manually type /news on the URL.

**Comment by goldensunliu** [comment]
@dgrana could you add a bit of code for people to look at?

**Comment by BerkeleyTrue** [comment]
If you manually type `/news` the browser hits your server. Are you using (RR) React-Router on the server as well?
If so, do you have an end point that intercepts `/new` and hands control to RR?

**Comment by Spy-Seth** [comment]
I've the same issue.

On my route definitions, I've this:
```
 <Redirect from="/:lang" to="signup-page" />
 <Route name="signup-page" path="/:lang/welcome" handler={SignUpPage} />
```


When I go on `/fr`, I'm redirected on `/signup-page`, not on `/fr/welcome` has expected.

**Comment by dgrana** [comment]
```    
    <Route path="news/page/:page" name="newsLanding" component={ require('./components/News/Landing') } />
    <Route path="news/:slug" name="newsDetail" component={ require('./components/News/NewsDetail') } />
    <Redirect from="/news" to="/news/page/1" />
```

**Comment by kpaxqin** [comment]
here are my routes run with HashLocation. 
```
<Route name='home' path='/'>
    <Route name='foo'>
      <Route name='bar'></Route>
      <Redirect from='/' to='bar'></Redirect>
    </Route>
    <Redirect from='/' to='foo'></Redirect>
  </Route>
```
when visiting `localhost` or `localhost#/foo/` it can be redirect to `localhost#/foo/bar` properly
But `localhost#/foo`, which should just be equal to `localhost#/foo/`, didn't work as expected,  the redirect seems not working when the last slash is missing.
The version of react-router is 0.13.3

**Comment by ryanflorence** [comment]
@kpaxqin 0.13 cares about the trailing slash, do `path="foo/?"` in your route config to make it optional

@dgrana I can't reproduce, if you could provide a failing test case we can take a closer look, but that's pretty basic functionality.
