### ISSUE TITLE
Error: Cannot find module 'react-router/lib/BrowserHistory'

### ISSUE THREAD

**Issue by xcatliu** [rackt/react-router#1492]
`README.md` told me to use `react-router/lib/BrowserHistory`, but I cannot found it.

**Comment by bmathews** [comment]
@xcatliu README.me is for version 1.0.0@beta3. Are you following the right docs for the version you're using? See http://rackt.github.io/react-router/ for v0.13.3

**Comment by sbussard** [comment]
Thank you @bmathews

**Comment by xcatliu** [comment]
@bmathews Thanks!
