### ISSUE TITLE
Accessing the history stack

### ISSUE THREAD

**Issue by jimmed** [rackt/react-router#1496]
Essentially, I have a 'settings' page, which is composed of a few tabs (`Link`s), a pane to display the active tab (the `RouteHandler`), and a close button.

When the close button is hit, the desired behavior is to go back to the route that was active before the settings page, but for each tab we click on this page, an additional route is added to the history stack.

Is there a way to access the history stack in its entirety, so that I can achieve the desired result?

**Comment by dipdipdip84** [comment]
Hi @jimmed 
I am also trying to implement something like this. Making a pile of history points and transitionTo and shift the last entry when the context back button is clicked.

So I created a navigation store that as a backHistory array where I push the history index when needed.

```javascript
import {History} from 'react-router';
import * as navigationActions from '../navigation/actions';

class ListPage extends Component {
  componentWillMount(){
    this.setState({
      history: History.length  // Should use History.state
    });
  }
  componentWillUnmount(){
    navigationActions.onAddBackHistory(this.state.history);
  }
  ...
```

```javascript
import {History} from 'react-router';
import * as navigationActions from '../navigation/actions';

class ItemPage extends Component {
  backToLastHistory(e,backHistory){
    e.preventDefault();
    const lastBackHistoryRecord = backHistory.last();
    const currentHistoryIndex = History.length; // Should use History.state

    navigationActions.onShiftBackHistory();
    
    window.history.go(-(currentHistoryIndex - lastBackHistoryRecord)); // Should use Navigation.transitionTo();
  }
  render() {
    const {navigation} = this.props;

    const items = navigation.get('menu').get('items');
    const backHistory = navigation.get('backHistory');

    return (
        <div className={'page ' + this.props.routeName} style={this.props.pageStyle}>
          <header>
            { backHistory.size !== 0 &&
              <a onClick={(e)=>this.backToLastHistory(e, backHistory)}>Back</a>
            }
            <Menu items={items} />
            ...
```

The lack I found if I am not missing something, is the ability to History.state and the ability to History.transitionGo().

**Comment by dipdipdip84** [comment]
https://github.com/rackt/react-router/issues/767

**Comment by taion** [comment]
- `history` is a separate project now
- This is essentially a requirement for what we're discussing w/r/t RN support, so better to consolidate discussion there at https://github.com/rackt/react-router/issues/743
