### ISSUE TITLE
is there a navigating method for the router

### ISSUE THREAD

**Issue by linghuaj** [rackt/react-router#1497]
Hi,

Is there a navigating method like this.router.navigate("/path")?
for instance, when click a button, other than direct link to the path, i want to do something first, then navigate to '/path' by triggering the call. 

Thanks a lot

**Comment by bmathews** [comment]
@vanessachem Use the navigation mixin: http://rackt.github.io/react-router/#Navigation

**Comment by eriknyk** [comment]
What is the alternative to TransitionHook mixin for ES6 classes, where mixins are deprecated?

Regards.

**Comment by BabakMN** [comment]
I'm also interested in what @eriknyk is asking

**Comment by bmathews** [comment]
Take a look at the navigation mixin source: https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/modules/Navigation.js

Add

```
contextTypes: {
    router: PropTypes.router.isRequired
  },
```

then do:
```
this.context.router.transitionTo(to, params, query);
```

**Comment by bmathews** [comment]
@eriknyk @BabakMN v1.0.0 TransitionHooks can be managed through `this.context.router`. Look at https://github.com/rackt/react-router/blob/master/modules/TransitionHook.js. 

If you want to use the mixins with es6 classes, look at https://github.com/brigand/react-mixin or follow the discussion on https://github.com/rackt/react-router/issues/1173

**Comment by eriknyk** [comment]
Thank you @bmathews !!

**Comment by vanessachem** [comment]
cool, thanks @bmathews!

**Comment by BabakMN** [comment]
@bmathews thanks I tried it (also see #1499) but ```this.context.router``` is coming out as undefined (in constructor, or in ```componentDidMount```).

**Comment by BabakMN** [comment]
@bmathews Nevermind, solved the problem. For anyone else with a similar problem, refer to #1499.
