### ISSUE TITLE
Possible to have a different animation for forward/back buttons?

### ISSUE THREAD

**Issue by Wildhoney** [rackt/react-router#1498]
In the [following somewhat outdated React module](https://github.com/andreypopp/react-router-page-transition) they have a [`popStateTransitionName`](https://github.com/andreypopp/react-router-page-transition/blob/master/index.js#L46) that is used for <kbd>forward</kbd> / <kbd>back</kbd> buttons, whereas by default they'll use the `transitionName` property as we do in the typical React `TransitionGroup` component.

I have the animation setup just fine for transitioning between pages:

```javascript
<TransitionGroup component="div" transitionName="page-transition">
    <RouteHandler key={name} />
</TransitionGroup>
```

However, when the user clicks their native <kbd>back</kbd> button on their phone/browser, I want to apply a different animation &ndash; essentially instead of moving right-to-left, the animation will move left-to-right.

Is something like this possible with React Router and `TransitionGroup`?

**Comment by taurose** [comment]
You can check if it's browser back or forward with `isPopEvent = state.action === 'pop'`. It doesn't seem like there's a mixin for this, so you have to pass it down manually.

```js
Router.run(routes, function (Handler, state) {
  var isPop = state.action === 'pop';
  React.render(<Handler isPop={isPop}/>, document.getElementById('example'));
});

var App = React.createClass({
  mixins: [State],
  render: function () {
    var name = this.getPath();
    return (
        <TransitionGroup component="div" transitionName={this.props.isPop ? 'example' : 'moveUp'}>
          <RouteHandler key={name}/>
        </TransitionGroup>
    );
  }
});
```

**Comment by Wildhoney** [comment]
Thanks @taurose Perfect! :+1:

**Comment by thomasboyt** [comment]
It looks like this doesn't work in the current version of `history` used by `react-router@2.x` - going _forward_ is also considered a "POP" action, so it plays the same animation for back or forward.
