### ISSUE TITLE
TransitionHook alternative to be used with ES6 classes

### ISSUE THREAD

**Issue by eriknyk** [rackt/react-router#1499]
Please can you tell me how I can use TransitionHook with ES6 classes, since mixins are deprecated
for ES6 classes.

Regards.

**Comment by taurose** [comment]
Looking at https://github.com/rackt/react-router/blob/master/modules/TransitionHook.js it should work like this:

```js
class RouteComponent extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.routerWillLeave = this.routerWillLeave.bind(this);
  }

  componentDidMount() {
    this.context.router.addTransitionHook(this.routerWillLeave);
  }

  componentWillUnmount() {
      this.context.router.removeTransitionHook(this.routerWillLeave);
  }

  routerWillLeave (nextState, router) {

  }
}

RouteComponent.contextTypes = {
  router: React.PropTypes.object.isRequired
}
```

**Comment by BabakMN** [comment]
@taurose have you achieved this successfully in ES6? For me ```this.context.router``` is undefined.

**Comment by BabakMN** [comment]
Nevermind I worked it out. I was trying to have ```contextTypes``` inside the class definition, doing it as @taurose has demonstrated works.

**Comment by jedrichards** [comment]
I think it should work with ES7 static property initialisers too.

```
class RouteComponent extends React.Component {
  static contextTypes = {
    router: React.PropTypes.object.isRequired
  };
}
```

**Comment by eriknyk** [comment]
thank you to everybody!

**Comment by bbb324** [comment]
@BabakMN any code to show how to do it ?
