### ISSUE TITLE
DefaultRoute not rendering as expected

### ISSUE THREAD

**Issue by alexanderbanks** [rackt/react-router#1503]
This issue was closed but I am still having the problem: https://github.com/rackt/react-router/issues/1107

My code:

````javascript
var routes = (
    <Route path="/" handler={App}>
        <DefaultRoute handler={LoginForm} />
    </Route>
);

Router.run(routes, function(Handler) {
    React.render(<Handler />, document.body);
})
````

My understanding was that App would render, and then LoginForm would render, but currently only App renders. According to the documentation I've read, this seems to be the correct implementation of DefaultRoute(?). There are no errors, just LoginForm does not render.

**Comment by taurose** [comment]
Maybe you forgot to render `<RouteHandler />` inside `App`?

**Comment by Davorak** [comment]
@alexanderbanks - Building off of [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate) I built a small example showing the DefaultRoute working as I expect it to and with the behavior I think you desire:
https://github.com/Davorak/experiments/tree/master/examples/defaultRouteBug

router:
```
var routes = (
    <Route path="/" handler={App}>
        <DefaultRoute handler={DefaultApp} />
    </Route>
);
```

Renders how I expect:
![image](https://cloud.githubusercontent.com/assets/810921/8739374/8dd9bf5c-2c00-11e5-98ea-c4e07a35b519.png)
To start the server on localhost:3000
```
npm i
npm start
```
Inline some code for convenance:
App:
```
export default class App extends Component {
  render() {
    return (
      <div>
        <h1>Hello, world.</h1>
        <RouteHandler />
      </div>
    );
  }
}
```

DefaultApp:
```
export default class App extends Component {
  render() {
    return (
      <h1>Default App</h1>
    );
  }
}
```

**Comment by levithomason** [comment]
Two oddities:

When used aside a dynamic set of routes, DefaultRoute doesn't work:

```jsx
// does not work
var routes = (
  <Route handler={Root}>

    <DefaultRoute handler={Login}/>
    {publicRoutes} {/* <= Login route is in this array */}

    <Route handler={LoggedIn}>
      {protectedRoutes}
    </Route>
  </Route>
);
```

**Comment by ryanflorence** [comment]
can't reproduce on master
