### ISSUE TITLE
No way to reload a page (call willTransitionTo again)

### ISSUE THREAD

**Issue by DelvarWorld** [rackt/react-router#1504]
I think this would have addressed this issue: https://github.com/rackt/react-router/pull/1031

I have the use case when a user logs in, the current page should "refresh," as in the API call (action) triggered in `willTransitionTo` should be called again. In the `willTransitionTo` hook I trigger an action that makes an API call to load user "things". When you log in, the API call returns different data (it shows private things). So I need to make the API call again when the user logs in.

I can't "listen" to the response from the user login action and fire the api call again from the store, obviously. I also don't want to hard code routes into the login action creator to do specific API calls again on a successful login. I want to just reload the view.

`transitionTo( samePath )` doesn't do anything. `window.location.reload()` does a full page reload.

I'm trying to hack a solution by manually hooking into the router callback function, but it would be very handy to have a simple way to reload a page, even just `router.reload()`.

**Comment by DelvarWorld** [comment]
Here's a little more detail and the solution I've come up with:

On my user profile page, I have a `willTranstionTo` that **blocks rendering** until the data is properly fetched, by waiting action to complete before calling the callback:

    statics: {
        willTransitionTo: function( transition, params, query, callback ) {
            this.context.executeAction(
                getProfileThings, { username: params.username }, callback
            )
        }
    }

The underlying issue here is that if the user is **logged out**, the `getProfileThings` returns only public things. If the user is **logged in**, the `getProfileThings` returns both public and private things. So when the user logs in, I **need to call call** `getProfileThings` **again** to get new data. If there was a refresh mechanism of the router, I would just have to refresh the current route, the `willTransitionTo` would again correctly call and correctly block rendering/mounting/etc until the new data is fetched. So, that's basically what I did. I added this API:

    statics: {
        postAuthRefresh: true, // My own custom flag
        willTransitionTo: ...

And then in my signup action:

    export function login( context, params ) {
        Utils.ajax( '/api/login', 'post', params ).then( function( res ) {
            context.dispatch( 'USER_SIGNED_IN', res );

            Utils.checkForPostAuthCallback( context );

Now when the user logs in, I have a **route independent**, abstract way to check if any routes should refresh:

    checkForPostAuthCallback( context ) {
        let routes = routeParams.routes;
        _.each( routes, ( route ) => {

            // Check for static postAuthRefresh here...
            if( route.handler.postAuthRefresh ) {

                // Here is where I fake the transition
                route.handler.willTransitionTo(
                    {},
                    router.getCurrentParams(),
                    router.getCurrentQuery(),
                    function() {}
                );

The only odd thing is that the `transition` is passed to `willTransitionTo` as an empty object, because it's not actually a page transition. If `react-router` made a page transition on a refresh / navigation to the same route (the original ticket), this wouldn't be a problem. This isn't a problem for me, because as you can see in the `willTransitionTo`, in my case I don't do anything with the `transition`.

**Comment by DelvarWorld** [comment]
Finally figured out a much cleaner hack:

`router.transitionTo( router.getCurrentPath(), null, { forceRefresh: new Date() } );`

The router will accept any number of "params" even if the route doesn't accept any. You can pass in throwaway params. It looks like if any one of the arguments change ( url, query, or params ), even if they aren't used, react-router will reload the page.

**Comment by hackhat** [comment]
It doesn't work with 0.13.3

**Comment by jaxxreal** [comment]
Great idea! I need this functionality too.

**Comment by ryanflorence** [comment]
on master a transition to the same path will cause a rerender with a new entry in the history

**Comment by DelvarWorld** [comment]
When you click refresh in your browser it doesn't create a history entry. Why would react-router create one if the path is exactly the same?

**Comment by th0r** [comment]
@ryanflorence Agree with @DelvarWorld here. Why should it add another history entry?

**Comment by ryanflorence** [comment]
Because that's exactly how browsers work.

Click a link with or without react router to exactly where you are, the browser adds a history entry.

Click refresh with or without react router, the browser does not add a new entry.

Isn't this the exactly behavior the issue is asking for?

**Comment by jaxxreal** [comment]
@ryanflorence How I understood this topic about no way to make route refresh (remount routeHandler with all effects) programmaticaly. Do react-router have necessary API?

**Comment by DelvarWorld** [comment]
I created this ticket in the hopes of a `location.refresh()` for a route, to avoid a hack around re-calling all the transition functions manually.

**Comment by jaxxreal** [comment]
@DelvarWorld  yeah! I need that too. By my mind, it's basic thing for a router lib.

**Comment by th0r** [comment]
> Click a link with or without react router to exactly where you are, the browser adds a history entry.
Hmmm, in which browser do you have this behavior? I've just tried that in Chrome and Firefox and they don't add any history entries in this case.

**Comment by oxbambooxo** [comment]
: [10-clean-urls](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/10-clean-urls)

    import { Router, hashHistory } from 'react-router'
    <Router history={hashHistory}>

when i use the `hashHistory` can get the feature!

**Comment by jaxxreal** [comment]
In my SPA, I implemented this feature just remount route component on demand (via actions, I use flux architecture). It's simple and works.
