### ISSUE TITLE
1.0.0-beta3 "Warning: Failed propType"

### ISSUE THREAD

**Issue by vkrol** [rackt/react-router#1505]
Hello!

I encounter a problem with the latest react-router beta. I created the repository with the example code https://github.com/vkrol/react-router-failed-prop-type
The problem is in the "Warning: Failed propType: Required prop `someProp` was not specified in `Child`. Check the render method of `Router`.". But everything with rendering is ok. 

Thanks.

**Comment by taurose** [comment]
Hi,

looks like this is a side effect of replacing `<RouteHandler>` with `this.props.children`. React validates the props when the element is first created by the router without `someProp`. I don't think you can do much about it, except using `getDefaultProps` or removing `.isRequired`. If you needed to pass that prop to all route handlers (e.g. a flux instance), you could inject it with `<Router createElement>` instead.

**Comment by globexdesigns** [comment]
I'm having the same issue. Here's the full trace stack:

```
Warning: Failed propType: Required prop `user` was not specified in `SettingsProfile`. Check the render method of `Router`.warning @ warning.js:45checkPropTypes @ ReactElementValidator.js:239validatePropTypes @ ReactElementValidator.js:258ReactElementValidator.createElement @ ReactElementValidator.js:284React.createElement @ index.js:172createElement @ AsyncProps.js:192_createElement @ Router.js:284(anonymous function) @ Router.js:320render @ Router.js:298ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:546ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:566ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:519ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:503ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:432ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:380ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:103runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactPerf.measure.wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:62(anonymous function) @ Router.js:177(anonymous function) @ Router.js:77done @ AsyncUtils.js:51(anonymous function) @ AsyncUtils.js:57(anonymous function) @ main.js:64(anonymous function) @ app.3.2.0.js:109webpackJsonpCallback @ app.3.2.0.js:19(anonymous function) @ 13.app.3.2.0.js:1
```

**Comment by ryanflorence** [comment]
yeah, thats a tradeoff we knew about, react validates in createElement but not cloneElement.

**Comment by ryanflorence** [comment]
https://github.com/facebook/react/issues/4494

**Comment by globexdesigns** [comment]
Given that that facebook/react#4494 is a closed issue that will not be resolved, what is the correct way to handle this in React Router 1.0?

**Comment by steida** [comment]
I am also curious if this is going to be fixed or leaved as is?

**Comment by YourDeveloperFriend** [comment]
> Given that that facebook/react#4494 is a closed issue that will not be resolved, what is the correct way to handle this in React Router 1.0?

Bump.

**Comment by taion** [comment]
This is a wontfix. See the notes at https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#routehandler.

**Comment by AlastairTaft** [comment]
Found this confusing, seeing all the warnings in the console made me deconstruct my code piece by piece trying to get to the bottom of it. Understood that this is a won't fix, but will cause a few headaches for people that don't yet know about this side affect. 

Possibly consider updating docs to make the problem more well known.

**Comment by taion** [comment]
We updated the documentation here: https://github.com/rackt/react-router/blob/master/CHANGES.md#routehandler

**Comment by AlastairTaft** [comment]
Cheers, I actually remember reading that a while back and still didn't twig
