### ISSUE TITLE
<Link> requiring two clicks to navigate

### ISSUE THREAD

**Issue by clintandrewhall** [rackt/react-router#1506]
In 1.0.0-beta3, for some reason, when I click the first link in a list of links, it navigates correctly, but every subsequent link click of the same route requires two clicks.  The first changes the browser URL, but doesn't change the content, and the second changes the content:

    import { history } from 'react-router/lib/HashHistory';
    <Router history={history}>
      <Route name="app" path="/" component={App}>
        <Route name="activity" path="/activity/:sourceID" component={ActivityPanel} />
      </Route>
    </Router>
    ....
    <Link to={'/activity/' + activity.sourceID}>{activity.sourceID}</Link>

Is this a KP?  Should I be using a different history implementation?

**Comment by bmathews** [comment]
@clintandrewhall Haven't ran into an issue like that with beta3 using HashHistory and Links. Can you share some more code? Any errors?

**Comment by knowbody** [comment]
could you please provide more explanation. I've tried to reproduce it but don't have any problems with it. Closing for now, will reopen if it's still an issue.
