### ISSUE TITLE
use transitionTo with external links

### ISSUE THREAD

**Issue by theverything** [rackt/react-router#1508]
I have a `willTransitionFrom` handler on a component that checks to see if the form on the page has unsaved data. This works great when clicking on a link that navigates to a page within the app, but when clicking on an external link (like google.com) the page instantly loads the new page and `willTransitionFrom` never gets called.

I understand why this is the way it is, but I was wondering if there is a way one could trigger the transition with an external link with the `transitionTo` method or if any one else has run into this issue, how they handled it.

**Comment by ryanflorence** [comment]
the history package that we're built on has the option to use onBeforeUnload for transition hooks too: https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md#the-beforeunload-event

you can pass in your own history (that uses beforeunload) to `<Router history={myHistory}/>`
