### ISSUE TITLE
ES6 import statement confusion

### ISSUE THREAD

**Issue by rn2dy** [rackt/react-router#1509]
If I do `import Router, {Route} from 'react-router'` it works, but if I do `import {Router, Route} from 'react-router'` it does not import Router at all. So I guess it means Router is the default export from react-router module, if that is the case why the README says `import {Router, Route} from 'react-router'`.

**Comment by tmbtech** [comment]
Which version are you running? 
In 1.x 
`import {Router, Route} from "react-router"`
https://github.com/rackt/react-router/blob/master/modules/index.js#L2

version 0.13.x
`import Router, {Route} from "react-router";`

**Comment by rn2dy** [comment]
I see, I am using 0.13.3
