### ISSUE TITLE
Some thing wrong when i use `AsyncProps`

### ISSUE THREAD

**Issue by rayqian** [rackt/react-router#1511]
`Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (asyncProps) while mounting RouteComponentWrapper (see: http://fb.me/react-context-by-parent)`

`Uncaught TypeError: Cannot read property 'componentsArray' of undefined`

How can i fix these error and warning.

**Comment by rayqian** [comment]
Just use 

`npm install react@0.14.0-beta1` 
`npm install react-dom@0.14.0-beta1`

to fix these issues.

**Comment by globexdesigns** [comment]
I'm having the same issue, but I don't want to upgrade to 0.14 just yet. The react-router package.json still defines react as 0.13... So there's got to be a way to make this work with 0.13 somehow.

**Comment by bdcwq** [comment]
1.0.0-beta3 repeat

**Comment by jonlong** [comment]
Anyone had success squashing this error without upgrading to 0.14? I'm getting the same message and having some trouble tracking it down.
