### ISSUE TITLE
Removal of <Route name> in 1.0

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1514]
In ReactRouter `0.13`, the following was supported:
```javascript
router.makeHref('emails', {label: labelId});
```
```javascript
<Link to="emails" {label: labelId}>
```

React router would do a reverse lookup on the route structure and generate a URL that looks like this:
```
/labels/12345/emails
```

It looks like this functionality (which is common to most routers) was dropped in `v1.0`. Now the following is required, which is much more brittle:

```javascript
<Link to={"labels/" + urlEscape(labelId) + "/emails"}>
```

Are there plans to restore this capability before releasing `1.0`?

**Comment by alekbarszczewski** [comment]
:+1:  - very often client wants to change route path (e.g. from `/users` to `/members`). If it would be possible to link to named route then it would be easier to make such change (instead of changing path in each `<Link ...>` it would be enough to change only "path" in `<Route>` component).

**Comment by chrisdrackett** [comment]
I'm also concerned about this. being able to use names so URL's are only defined in a single place seems like a huge win and I would hate to lose this.

**Comment by oas89** [comment]
Well, I was wondered there is no more url reversing in 1.x.x branch. I have an application that can be served with different url prefixes depending on configuration, for example, production version served from `my.app.com` and there is admin preview version served from `admin.my.app.com/preview/`.
In 0.13.x I have all my routes wrapped in `Route path={config.prefix}`, where `config.prefix` is either `/` or `/preview`, and I have resolved all the links automatically when use reversing by name.
In 1.x.x I should use something like
 ```<Link to={prefix("labels" + urlEscape(labelId) + "/emails")}>```
i.e. explicitly wrap every link with prefix - looks ugly for me.

**Comment by th0r** [comment]
Wow! How did I miss that... As I understand it's made because of `getChildRoutes` can be async? But guys, it's a pain!

**Comment by Nickman87** [comment]
I'm experiencing the same issues, but with navigateTo. Is 0.13.x I can use navigateTo with the name of a path but in 1.x.x this results in the router adding the pathname to my URL instead of the associated path.
This functionality should definately be kept from 0.13.x as we want to reference our routes by name and not by path. If the consequence is that all the routes have to be loaded during this lookup, this is acceptable to me. If you don't want this to happen, you can switch over to path based routing instead of name based.

**Comment by chrisdrackett** [comment]
This may or may not be related, but in 0.13` it was possible to have something like the following:

    <Route name="index" path="/" handler={Index}>
        <DefaultRoute name="dashboard" handler={Dashboard}/>
    </Route>

and if you used a `Link` to `dashboard` it would only be active if you were at `/` in 1.0 I've updated it to be the following:

    <Route component={Index}>
       <Route name="dashboard" path="/" component={Dashboard}/>
    </Route>

however now the `Link` to `dashboard` ( `to="/"` ) is set to active on 100% of my site.

**Comment by chrisdrackett** [comment]
sorry to be posting a lot of comments, but just ran into another issue here. In 0.13 I had the following:

    <Redirect from="questions" to="questions/all"/>
    <Route name="questions" handler={QuestionBase}>
      <Route name="question_detail" path="/question/:id" handler={QuestionDetail}/>
      <Route name="question_list_nav" path="/questions" handler={QuestionListNav}>
        <Route name="question_list" path=":filter" handler={QuestionList}/>
      </Route>
    </Route>

so no matter where you were (`/questions`, `/question/1`) the `Link` to the `questions` route (used in the navigation) would always be active. In 1.0 I think I have to do the following:

      <Redirect from="questions" to="questions/all"/>
      <Route component={QuestionBase}>
        <Route path="/question/:id" component={QuestionDetail}/>
        <Route path="/questions" component={QuestionListNav}>
          <Route path=":filter" component={QuestionList}/>
        </Route>
      </Route>

however, now when you are on a question detail the sidebar item for `questions` is no longer active.

**Comment by mjackson** [comment]
We removed `<Route name>` because it's an anti-pattern, for a few reasons:

- It obscures the URL. Any time you `<Link to="aRouteName">` you can't actually see what params that URL path accepts. So you end up having to go look at your routes definition to see what the actual URL looks like.
- It makes it easy to change URLs, but you shouldn't be changing your URLs. Use a `<Redirect>` instead.

@chrisdrackett `isActive` will work the same way in 1.0 as it did in 0.13. The 1.0 implementation just isn't complete yet, but we're working on it.

**Comment by chrisdrackett** [comment]
I agree that you shouldn't be changing URL's once a site is launched, but during development it can be pretty useful to be able to move pages around without having to do a lot of find-replace. Obviously not a deal breaker and I'm biases as I've been living in a django world for the last 10 years so I'm really used to named urls.

**Comment by alekbarszczewski** [comment]
I agree with @chrisdrackett - I guess I will end up wrapping urls with some global function like
```
<Link to="{routePath(...)}">
```

**Comment by aldendaniels** [comment]
@mjackson - Agreed that the route name is a bit of an anti-pattern, but manually constructing URLs is hardly a good solution either. During early development, we DO change our URLs. Having to update all links each time is painful.

An idea - mimick django's [reverse()](https://docs.djangoproject.com/en/1.8/ref/urlresolvers/) method:

```javascript
<Link to={Component} params={{userId; 123}}>
```

In most cases, a target handler component and a set of params will uniquely a route, allowing React router to do a reverse-lookup and construct the URL.

In rare cases where multiple routes resolve to the same _component+params_ combination, then the current approach (hard-coding the URL) could be used instead.

**Comment by mjackson** [comment]
@chrisdrackett Using a helper function as @alekbarszczewski suggests is a really easy solution to this problem.

> An idea - mimick django's reverse() method

That's exactly how named routes work in 0.13, @aldendaniels. Problem is, now you have to `require` your route handler components (which can significantly increase the size of your bundle) just so you can `<Link to>` them. This isn't a problem on smaller sites, but can be a deal-breaker in really large sites.

If manually updating your `<Link>`s in dev is really painful for you, I'd suggest you construct a simple function to do what @alekbarszczewski suggests.

```js
function makePath(Component, params) {
  var template = Component.pathTemplate;
  // do your interpolation here
}

var UserProfilePage = React.createClass({
  statics: {
    pathTemplate: '/users/:id'
  }
});

<Link to={makePath(UserProfilePage, user)}>{user.name}</Link>
```

**Comment by chrisdrackett** [comment]
:+1:

**Comment by jquense** [comment]
The removal of this feature is becoming a big dealbreaker for for us. We rely heavily on named routes, to manage and reduce bugs in our app. The helper function solution doesn't seem to be helpful...how does it deal with nested routes?

```js
<Route path='/app' component={App}>
  <Route name='thing' path='thing/:id' component={Thing} />
</Route>
```

How am I supposed to use a helper function to get `'/app/thing/4'` in a helper function without keeping a hash of all possible urls and their children? What If I use the `Thing` component in two different routes?

Either I need to reimplement the path matching logic in my app to build urls or I need to make sure that I never use the Component in more then one spot in my routes both seem like terrible solutions...

**Comment by taurose** [comment]
> That's exactly how named routes work in 0.13, @aldendaniels. Problem is, now you have to require your route handler components (which can significantly increase the size of your bundle) just so you can <Link to> them.

Isn't this already (largely) addressed by loading just the components async though?

**Comment by th0r** [comment]
@taurose +1
What is the purpose for async routes configuration if we already have async route components?

**Comment by aldendaniels** [comment]
@mjackson - :+1: thanks for the explanation. I hadn't thought of the split-bundles issue. It's also a fair point that URL changes should be kept to a minimum. Since the "RL" in URL stands for "Resource Locator", I guess using URLs to locate routes makes pretty good sense. :)

@taurose - no, my idea would break for async routes since you can't link to `{ComponentHandler}` unless the handler class is available. As a result, if a loaded component wants to link to a non-loaded async route, you'll have issues.

**Comment by mjackson** [comment]
@jquense My guess is that you're not using code-splitting in your app. That's the whole reason for this change: so that we don't have a "global" name for your route.

If we really, really wanted to get named routes working with code splitting we could maybe have some sort of integration with the webpack/browserify tools. But that level of integration would be outside of the scope of this project.

Another solution might be to have some sort of pluggable config, so you could say, for example, "I know I'm not doing code splitting in this app. Use this thing to look up all my routes by name." But that seems to be more hassle than it's worth given the rationale I've already described above.

> Isn't this already (largely) addressed by loading just the components async though?

@taurose @th0r Yes, it is, and that's a great point to consider. We've had feedback from a few very large users that have told us they can't increase the initial page bundle size when more routes are added to the app. These are companies that are extremely sensitive to web performance and loading all their routes up front would be a deal-breaker for them. So, e.g. a developer working on some new feature shouldn't be able to modify the size of the initial page bundle.

The `getChildRoutes` feature is designed to let you decide when those routes are loaded. Using webpack's `require` and `require.ensure` (or similar functionality in another code-splitting tool) you can decide as you build your app exactly which code is loaded when.

**Comment by jquense** [comment]
@mjackson I see how code splitting makes global name lookups hard, but I'm not sure why requires that the feature be killed for those of us who aren't those few giant users. 

It looks like I _can_ handle this myself by creating a custom `createRouter` functioning and tracking a hash of route names to urls. Cursory glance says that you could even do this with code splitting, provided routes that specify a `getChildRoutes` property also provide something like a `providesUrls` property to go with it. 

The main issue here is I need to write all the reverse path interpolation code, whereas it was provided for me until now. I realize you folks are really busy and are working hard, but perhaps this situation can be mitigated by:

1. making sure routes can still be named (ie. the router doesn't strip the prop from the config/component)
2. expose an analog to the `injectParams` helper that was in 0.13 that works with the new optional param syntax

At least then we have the basic tools for building the feature back in without much trouble (or cost to you folks)

**Comment by mjackson** [comment]
> making sure routes can still be named (ie. the router doesn't strip the prop from the config/component)

You already have this. [We don't strip any props from your route object](https://github.com/rackt/react-router/blob/9483867fe0cdeb64482802201d50d84e7c53cfb0/modules/RouteUtils.js#L25-L38). We also give you `this.props.route` in your route handler components, so you can read whatever props you want from your original route object there.

> expose an analog to the injectParams helper that was in 0.13 that works with the new optional param syntax

[You already have this too](https://github.com/rackt/react-router/blob/9483867fe0cdeb64482802201d50d84e7c53cfb0/modules/URLUtils.js#L156-L203).

**Comment by jquense** [comment]
Bah missed I `formatPattern` when I was poking around the source. Great :) as long as ya'll don't plain on removing that stuff I am satisfied. thanks!

**Comment by th0r** [comment]
@mjackson But why just don't leave the `0.13` behavior? Those few giants could still load their routes configs async and construct urls themselves without using route names. We can even warn users at runtime that if they use async route config then they can't use route names.

**Comment by ngokevin** [comment]
I disagree that named routes are an anti-pattern. I don't feel they encourage users to change their routes often, but it does encourage DRY. Hardcoding URLs is bad in my books. FWIW, I think they should be added back.

**Comment by unodgs** [comment]
I started porting my app to react-router 1.0 and I was really surprised than names were gone. The problem I have now is path in <Route> is a Polish name but name of route is English. Now I'm forced to use Polish names in <Link/> as well. IMO removing names was a really bad idea. I hope you'll get them back before 1.0 final.

**Comment by le0nik** [comment]
+1, removing named routes is a very bad idea. 0.13 API was much better.

**Comment by lixiaoyan** [comment]
+1

**Comment by svecon** [comment]
+1

**Comment by maslianok** [comment]
+1

**Comment by eXon** [comment]
-1 route names is an unnecessary abstraction, url are already there to name things

**Comment by maslianok** [comment]
I've written a simple helper to get route by name:

```javascript
//URLUtils.js
import {formatPattern} from 'react-router/lib/URLUtils';

export function getUrlByRouteName(routes, name, params, parentPath = '') {
  for (let i = 0; i < routes.length; i++) {
    let route = routes[i];
    let currentPath = parentPath + (route.path || '/');

    if (name == route.name) {
      return formatPattern(currentPath, params);
    };

    if (route.childRoutes) {
      let url = getUrlByRouteName(route.childRoutes, name, params, currentPath);
      if (url) {
        return url;
      }
    }
  };

  if (!parentPath) {
    console.log(`Can't find route with name ${name}`);
  }
};

//usage
import {getUrlByRouteName} from './path/to/URLUtils';
<Link to={getUrlByRouteName(this.context.router.routes, routeName, routeParams)} />

```
It works fine for me...

**Comment by jumoel** [comment]
+1

**Comment by jhicken** [comment]
+1

**Comment by jhicken** [comment]
I also agree with @ngokevin I don't think they are an anti-pattern. I think named routes make your code cleaner and more understandable.

ex1
```
this.transitionTo(
  'worker--tails',
  this.props.params
)
```

ex2
```
this.transitionTo(`company/${this.props.params.company}/workers/${this.props.params.worker}/tails/${this.props.params.tail}`)
```

Point 1:
ex1 feels much cleaner to me than ex2.
ex2 is also much more brittle.

Point 2:
I do agree that you shouldn't be changing urls in your application much. It still happens though.

Point 3:
I think most people would agree with me that magic strings are a bad practice and using flat urls everywhere is basically a bunch of magic strings.

Point 4:
If your not super familiar with the application your working on you need to dig through your stacked routes in your router to assemble your URLs. As opposed to just looking up the name of the one route you actually want to transition to. 

Point 5:
Consider UI-Routers $state.includes http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state
If you would like to check if your route contains one of the "Routes" in your current route tree... Having named routes make this really easy. You can simply check the route name of all your currently active routes. If not you have to come up with a special way to check that the url string contains a unique match to the route in question.


I get that named routes are hard to implement with code splitting. But I don't feel that is a good enough reason to remove them. I truly feel like that would be a step backward.

**Comment by aldendaniels** [comment]
@jhicken - To @mjackson's point, you can reduce the pain here with a `makePath()` helper.

For example, you could do something like this:

```javascript
let route = 'company/:companId/workers/:worker/tails/:tail';
transitionTo(makePath(route, this.props.params));
```

Personally, I'd like to be able to do:

```javascript
transitionTo('company/:companId/workers/:worker/tails/:tail', this.props.params);
```

...and have React Router do the substitution for me, but writing my own helper is no big deal.

**Comment by ngokevin** [comment]
Just to counterpont @eXon, who said ```-1 route names is an unnecessary abstraction, url are already there to name things```, that's kind of like saying "string variables are an unnecessary abstraction, strings are already there to represent values". DRY is good practice, and the old ```to="myRouteName"``` was very elegant

**Comment by eXon** [comment]
@ngokevin Comparing URLs and route names has honestly not one thing in common with string variables.

I agree with @jhicken that naming routes was very convivial. I am using the 0.13 router every day and I agree it would be a pain in the ass to do string concatenation because of the params.

Having used a lot of routers in different frameworks, naming routes is a feature most people are expecting and save time with. You don't have to use it if you don't want to, but most people obviously want to be able to.

+1

**Comment by ngokevin** [comment]
Route names are to variable names as URLs are to string values. 

But anyways, I'm glad you changed your mind.

**Comment by jhicken** [comment]
@aldendaniels
I get it. However It seems like a bandaid for something we already had a great solution too. (named routes) And it doesn't solve the problems that I pointed out above. Thanks though.

@mjackson 
Is there a direction forward on this? Is the plan to leave it the way it is? If not I would be happy to try and put something together for re-adding named routes.

I think this issue should be something we should get figured out. Since its the most commented on issue on the project.

**Comment by aldendaniels** [comment]
To get back named routes in a way that doesn't break for async route loading, I think React Router would need to stop supporting `getChildRoutes()`, requiring users to defined the whole route hierarchy up-front. Async behavior could still be accomplished using `getComponents()`.

Knowing the whole route hierarchy up-front might have other advantages, like the ability to show a `Page Not Found` handler instantly instead of having to first async-load other routes before realizing that no matching route exits.

**Comment by tomatau** [comment]
I disagree that route names are an anti pattern:

1. The path hold too much implementation detail.

2. It isn't a problem checking your route definitions when you need to use them - and you still need to check the definition to see the path structure.

3. When adding or modifying optional route params for new features, you may now need to go and update all the links pointing to it even though they don't use the optional params... Names separate this concern. Sure, you can use queryStrings... but I use queryStrings and params for different semantic behaviours and optional params are a valid use case.

4. Names remove code goop.Especially if you want to add a `/?` on the end of every path. Too much implementation detail.

5. Names make the OP feature easy to implement.

6. Names make the reason to use `to` instead of `href` more clear.

**Comment by ryanflorence** [comment]
Even if we don't bring them back, somebody (maybe even us?) could make a `<Link>` that works with named routes just like the old one, all the pieces are still there.

**Comment by jhicken** [comment]
@ryanflorence are you advocating for something like a named route extension for react router?

Places where I would like to see named routes working are.

1. ```<Link>```
2. transitionTo()
3. replaceWith()
4. isActive()

**Comment by th0r** [comment]
@ryanflorence But why can't we just leave it in the core? Why do you want to remove it so much?

**Comment by JedWatson** [comment]
@th0r If I understood correctly, part of the motivation was to remove the dependency on the main `react-router` package for generating paths, to remove a blocker for bundle splitting - see @mjackson's comments above. Based on that, this would be much better as a tiny, separate package (`react-router-link` or `react-named-routes` perhaps?)

I'm personally a fan of named routes but if there's a separate package that implements them, I don't think that's really a problem, especially if it's "blessed" in the main docs.

It also opens the door for innovation (i.e. multiple packages) around the best way to implement your site routes structure - something better than a "built-in" solution that's effectively a side-effect of using react-router will likely emerge, as we've seen happen with different Flux implementations with that being separate from React itself.

Unless I'm mistaken, using a separate library for named route management resolves all the issues @tomatau mentions, as a separate concern from react-router itself (which in turn makes the router a more flexible, universal tool). It's also where you'd implement something like the `Page Not Found` handler @aldendaniels mentions.

**Comment by vojtatranta** [comment]
+1 for bringing them back, it is absolute must-have feature.
I cannot imagine doing bigger project (lots of URLs) without it.
Or there must be possibility for url reversion. Cannot hard code urls every time, that's antipattern for me :))

**Comment by ngokevin** [comment]
I followed @JedWatson's comments and went out to make a separate library for route reversal in react-router@1.x.x. It's still being put through its strides so issues and pull requests very welcome.

https://github.com/ngokevin/react-router-reverse

**Comment by Nickman87** [comment]
this commit b8c69a058705331850a91bcabac95f31b349c4f5 broke the methods used here for named lookup as the router is no longer available on the context. Are there alternatives to getting this to work?

I just made my own mixin implementation borrowing some code from the previous answers, but now I cannot access the router context anymore in the latest version:

```javascript
define(['lodash', 'react-router/lib/PatternUtils'], function(_, PatternUtils) {

    function assemblePathFromNodes(currentRouteNodes) {
        let finalPath = '';
        for (let ii = 0; ii < currentRouteNodes.length; ii++) {
            if ( currentRouteNodes[ii].path && currentRouteNodes[ii].path !== '/') {
                if (currentRouteNodes[ii].path[0] === '/') {
                    finalPath += currentRouteNodes[ii].path;
                }else {
                    finalPath += ('/' + currentRouteNodes[ii].path);
                }
            }
        }
        return finalPath;
    }

    function getRouteByName(nodes, routes, currentRouteNodes = []) {
        var node = nodes.shift();

        for (let i = 0; i < routes.length; i++) {
            let route = routes[i];

            //A route without name or undefined is always a candidate
            var unnamedRoute = (!route.name || route.name === '');

            if (unnamedRoute || route.name === node) {
                //Try the next step, prepare state
                if (unnamedRoute) {
                    nodes.unshift(node);
                }
                currentRouteNodes.push(route);

                var result = undefined;
                if (nodes.length === 0) {
                    //Route has been found!
                    return currentRouteNodes;
                } else if (route.childRoutes) {
                    //Route has not been found, but there are still child routes!
                    result = getRouteByName(nodes, route.childRoutes, currentRouteNodes);
                }

                if (result) {
                    return result;
                } else {
                    //Match not found, return state
                    currentRouteNodes.pop();
                    if (unnamedRoute) {
                        nodes.shift();
                    }
                }
            }
            //Else no match, just try the next route
        }

        return undefined;
    }

    return {
        getUrlByRouteName: function(name, params)
        {
            var routeNodes = getRouteByName(name.split('.'), this.context.router.routes);

            if (routeNodes) {
                return URLUtils.formatPattern(assemblePathFromNodes(routeNodes), params)
            }

            throw new Error('route \''+ nodes.join('.') +'\' not found');
        }
    }

});
```

**Comment by mjackson** [comment]
Please see [my comment here as well](https://github.com/rackt/react-router/issues/1791#issuecomment-138326828). Closing this issue for now, but let's follow up post 1.0 in #1840

**Comment by adamziel** [comment]
Since a lot of people agrees that react-router was better off with named routes, I created this almost drop-in package to restore support for them: https://github.com/adamziel/react-router-named-routes
