### ISSUE TITLE
Browser back/forward button triggers 3 route state changes in v1.0

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1517]
In my root route handler, I log `nextProps.location`:

```javascript
componentWillReceiveProps(nextProps) {
  console.log(nextProps.location);
}
```

When I hit the browser "back" button, this is what I see:
<img width="535" alt="screen shot 2015-07-10 at 5 52 35 pm" src="https://cloud.githubusercontent.com/assets/4658558/8622586/84bf2a20-272c-11e5-8ce2-ae0771b7c5d5.png">

The 1st entry is a bogus "push" to the old location. The next two are duplicates.

**Comment by tomatau** [comment]
I'm finding the same behaviour - also required params for the routes aren't being supplied.

**Comment by subpopular** [comment]
The change from `nextProps.isTransitioning` from `true` to `false` is triggers the last two. Not sure if that intended or not...but I see the same thing.

**Comment by ryanflorence** [comment]
intended behavior, but its not in master anymore, might come back, if it does, don't worry about it unless its slowing down your app (which it probably isn't) and then use `shouldComponentUpdate` to bail
