### ISSUE TITLE
"You cannot modify a static location" when using componentWillMount

### ISSUE THREAD

**Issue by e-monson** [rackt/react-router#1518]
I have an isomorphic app using react-router. If I include a componentWillMount method in any of my components, I get this error:
>Error: Invariant Violation: You cannot modify a static location

What does this mean? I haven't been able to find this error referenced anywhere. Is there some sort of workaround?

**Comment by jakedowns** [comment]
Are you perhaps calling a transitionTo inside your componentWillMount method?

I ran into this today, and that's what was causing it.

changing to componentDidMount fixed the error, but resulted in an undesirable flash of the page that I was trying to block access to, so I ended up moving the redirect to the server routing level (in my case, koa-router)

Found this issue while looking for a solution, so thought I'd post this for anyone else who might stumble in here.

**Comment by e-monson** [comment]
Yes, that was the issue! Only transitionTo and replaceWith cause this error. I was afraid that I just couldn't use componentWillMount at all. Thanks!
