### ISSUE TITLE
1.0.0-b3 Redirect not working as per the docs

### ISSUE THREAD

**Issue by mattapperson** [rackt/react-router#1519]
In the docs it says the following:
``` xml
<Route path="course/:courseId">
  <Route path="dashboard"/>
  <Redirect from="home" to="dashboard" />
</Route>
```
Should result in 
```
 /course/123/home -> /course/123/dashboard
```

However this is not the case, it results in:
```
 /course/123/home -> /dashboard
```

**Comment by FAQinghere** [comment]
I put all of my `Redirect` elements at the top level, just under the `'/'` path. The redirect on the root '/' path does not work, however. It did work fine under v13.x

**Comment by knowbody** [comment]
related to #1658
