### ISSUE TITLE
Link query will erroneously encode all ready encoded URI components

### ISSUE THREAD

**Issue by pjjanak** [rackt/react-router#1520]
In my app I have a requirement that a returnURL must be passed around the app as an query string. So, when using ReactRouter I am creating Links that look something like this:

`<Link to='Profile' query={{returnUrl: 'http%3A%2F%2Fwww.google.com'}}/>`

The anchor tag that ReactRouter then creates looks something like this:

`<a href="/Profile?returnUrl=http%253A%252F%252Fwww.google.com">...</a>`

As I've all ready gone through the trouble of escaping the string, I think it would make sense for ReactRouter to not do it again. It might be nice if there just was a way to disable escaping all together for query parameters.

**Comment by ryanflorence** [comment]
you can implement your own query parsing , we use `qs` which is the most popular javascript query parser.

https://github.com/rackt/react-router/blob/master/docs/Router.md#stringifyqueryqueryobject

One might say you are erroneously parsing it yourself first :)
