### ISSUE TITLE
App inside folder with v1.0.0-beta3

### ISSUE THREAD

**Issue by gerherz** [rackt/react-router#1522]
I'm trying the new version on an app that works inside a folder. This is what I've got:
```javascript
class App extends React.Component {
  render() {
    return <Link to="login">Login</Link>
  }
}

React.render((
  <Router history={history}>
    <Route path="/app/" component={App}>
      <Route path="login" component={LoginForm}/>
    </Route>
  </Router>
), document.getElementById('root'));
```

When I load /app, it renders the link correctly. It links to /app/login, but after clicking on it I get the following warning message:
> Warning: Location "login" did not match any routes

**Comment by gerherz** [comment]
Changing the link to absolute path made it work:
```javascript
class App extends React.Component {
  render() {
    return <Link to="/app/login">Login</Link>
  }
}
```
However, it only works if I click on the link. If I write /app/login on the address bar, I get a 404.

**Comment by gerherz** [comment]
Ok, it seems that to achieve this I should:
- redirect in the server every call to /app* to /app
- use HashHistory instead of BrowserHistory

Is this correct? If so, this should be specified somehow in the docs.

**Comment by ryanflorence** [comment]
correct, I'd go with option 1.
