### ISSUE TITLE
The website docs default to 0.13.3 docs instead of the latest version

### ISSUE THREAD

**Issue by israelidanny** [rackt/react-router#1525]
This actually has been a source of confusion to me, because it makes 0.13.3 somehow look (illogically so) like the latest version

**Comment by bmathews** [comment]
@israelidanny 0.13.3 is the latest stable version. 1.0.0 is still in beta and has bugs.

**Comment by gaearon** [comment]
0.13.3 is what you get when installing `react-router` on NPM, so it *is* the latest stable version.
