### ISSUE TITLE
ie8 error

### ISSUE THREAD

**Issue by lvasilev** [rackt/react-router#1526]
this._currentElement.props      is NULL

var es5shim = require('es5-shim');
var es5sham = require('../../../node_modules/es5-shim/es5-sham.js');
var React = require('react');
var Router = require('react-router');
var routes = require('./config/routes');

Router.run(routes, function(Root){
  React.render(<Root />, document.getElementById('app'));
});
var React = require('react');
var Main = require('../components/Main');
var Org = require('../components/Org');
var Profile = require('../components/Profile');
var Router = require('react-router');
var Route = Router.Route;
var DefaultRoute = Router.DefaultRoute;

module.exports =  (
  <Route name="app" path="/" handler={Main}>
    <Route name="employees" path="employees/:id" handler={Profile} />
     <Route name="departments" path="departments/:id" handler={Org} /> 
    <DefaultRoute handler={Org} />
  </Route>
);
![1](https://cloud.githubusercontent.com/assets/11041941/8635487/f6d4876c-282c-11e5-9127-9a791d3480f2.png)
![2](https://cloud.githubusercontent.com/assets/11041941/8635488/f9ae8230-282c-11e5-9a86-3d787ac4630a.png)

**Comment by pandeiro** [comment]
@lvasilev: Any update on this?

**Comment by lvasilev** [comment]
It works now with  webpack only, not browserify.
