### ISSUE TITLE
Always set location.query

### ISSUE THREAD

**Issue by timoxley** [rackt/react-router#1529]
In 1.0.0-beta3 `this.params.location.query` is set to `null` if there's no query string. Currently whenever you need to check if a query property exists, they also need to check whether `this.params.location.query` exists before checking `this.params.location.query.somekey` or risk hitting a "cannot call somekey on null" error whenever there's no query.

Perhaps it would be cleaner if "no query" is represented by a simple empty object `{}`. This change would make it more terse to use the `query` object checking the existence and value of particular query properties; I imagine this is the most common use case for accessing `query`. Currently, the api is optimised for those scenarios when one needs to switch based on the very existence of a query string, which IMO seems rare.

**Comment by ryanflorence** [comment]
hmm, `window.location.search` always returns a string, and I agree this is nicer

**Comment by ryanflorence** [comment]
ah, this is the current behavior on master :)
