### ISSUE TITLE
Base URL for `router.transitionTo`

### ISSUE THREAD

**Issue by vjpr** [rackt/react-router#1530]
Is there a way to specify a base url such that when I call `this.context.router.transitionTo`, I don't require knowledge of the base url or namespace of my collection of routes.

E.g. If my app is at the endpoint `/app` with routes such as `/app/login`, `app/home`, etc. I would like to only have to write `this.context.router.transitionTo('home')`, etc.

Same with `<Link>`. Eg. `<Link to='home'/>`

Before named routes were removed in 1.0 this was not a problem.

**Comment by 5h1rU** [comment]
you can add `path="/"` on your `<Route></Route>` tag

`<Route path="/" handler={App}> ... </Route>`

**Comment by vjpr** [comment]
@5h1rU This did not work. The `/app` base url is a namespace to separate it from other endpoints on the server when using server-side rendering. I want to be able to change the name of this namespace and not update all the links in my app.

**Comment by taurose** [comment]
> Before named routes were removed in 1.0 this was not a problem.

Yeah, I think you'd have to wrap all your `<Link>`s and `transitionTo` etc. in addition to changing the route config. Monkey patching [Router.makePath](https://github.com/rackt/react-router/blob/master/modules/RouterContextMixin.js#L57) might work, too.

Seems like a reasonable feature to add to me with named routes being gone.

**Comment by vjpr** [comment]
I think I will just create a module with functions to return appropriate links depending on the route config, similar to Rails' [UrlHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html).

**Comment by taion** [comment]
This is actually just `useBasename`/`basename` on the history.
