### ISSUE TITLE
transferring props to children in 1.0.0

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1531]
Hey,

I am now migrating our code from 0.13.3. I really think that using (taking from a closed issue):
```javascript
React.cloneElement(this.props.children, { appState: this.state });
```
To transfer props to children, is an anti-pattern. I mean, this is really not the way to transfer props using React. I find that using RouteHandler is much simpler, and readable.

**Comment by taurose** [comment]
`RouteHandler` had its own problems though. With react-router, your route handlers are controlled by the router itself, so imo a route component shouldn't need to know about its child and which props it requires, just where to render it.

The new API gives you `createElement` to hook into the router and decide which props to pass to your components. In your example, `appState` seems like a good candidate to pass directly to all route handlers, instead of passing it manually from route component to route component.

**Comment by omerts** [comment]
@taurose looks like a good point, and a good solution. Thank you :)

**Comment by omerts** [comment]
@taurose coming to implement your solution, it looks like I need a switch case to handle which props to inject, which seems like I might as well just use this switch case to decide which components to render (which is exactly what react-router wants to help us avoid). I have looked into AsynProps, but I don't want every component with props, to have to know my AppStore. I know the above example is injecting the whole state for which createElement will be good, but I have cases where I transfer to the RouteHandler just something out of the state.

**Comment by giltig** [comment]
+1 to what @omerts said It's harder to move the props down the chain like that.
Parent always need to know what it supposed to pass on to its children (in functional paradigm)

**Comment by omerts** [comment]
By the way there is another problem using createElement, when the parent re-renders using setState, createElement isn't called

**Comment by J12D** [comment]
@taurose `createElement` would only work when I want to pass down something from within the module in which I set up the router, would it?
I'm currently trying to pass some actions from within the router's main component to `this.props.children` for the child to call:
```
export default class App extends React.Component {
  render() {
    const { dispatch } = this.props;
    const actions = bindActionCreators(Actions, dispatch); // <-- actions
    return (
      <div>
        {this.props.children} // <-- feed me actions
      </div>
    )
  }
}
```
My current line of thought: The main component (and not the router) is the correct place for these actions to be passed down — would this imply that I have to use @omerts code from the first post?

**Comment by joewood** [comment]
I have a similar problem and want to explicitly set the properties for child components based on each route. I suggested in #1857 to use the route map for this.  Using a function for the handler that returns a React component would allow the properties to be set explicitly and avoid a switch/case. Something like:
```jsx
<Route path="/inbox" handler={ (props,state) => <Inbox user={props.users} />}>
    <Route path=":messageId" handler={ (props,state,params) => <Message messageId={params.messageId}/> }/>
    <Route path="*" handler={InboxStats}/>
</Route>
<Route path="/calendar" handler={ (props,state) => <Calendar user={props.user} timezone={props.timezone} />} />
```

**Comment by ryanflorence** [comment]
`React.cloneElement` is public API, route handlers should be thought of as entry points into your app and you should rarely need to clone the children, it should be pretty opaque.

We measured the tradeoffs and find `this.props.children` to give us the best benefit,

**Comment by aybmab** [comment]
I'm sorry, I think I missed the conclusion. How do you pass props to children using 1.0??

Thanks in advance!

**Comment by joewood** [comment]
@aybmab - you may find this ticket helpful: #1857 
Plus this page helped with the use of createElement: https://github.com/rackt/react-router/blob/3891ee7fcf4e780aa54ce1f68f271f419d2cd1b1/docs/api/Router.md

**Comment by aybmab** [comment]
@joewood thanks! That definitely helped.

**Comment by BrandesEric** [comment]
I just wanted to add my voice to this.   I am server side rendering and I need to pass a few properties in to the component that's going to be rendered, but I need to do it per request - having a single createElement override is not helpful.  I really want to be able to pass additional properties in to `RouteContext` and have them filter down in to my components.  Is there some way to do this that I'm missing?

**Comment by SpainTrain** [comment]
@BrandesEric 

Not recommended, but you could you do something like `cloneElement(this.props.children, `[_.omit](https://lodash.com/docs#omit)`(this.props, 'children'))`

You may want to step back and consider what you are ultimately trying to accomplish.  Generally if you are providing different data for different requests, you'd do something like:

* Get the data for that request (which you already have)
* Hydrate some store with that data (store in the flux-y sense)
* Connect that store to the relevant [container component](https://medium.com/@learnreact/container-components-c0e67432e005) (optionally you just connect the store to whatever component needs the data)

Does your use case fit this pattern?

**Comment by BrandesEric** [comment]
Yeah, I'm struggling with the right Flux impl.  I prefer Reflux because it's so simple, but it's not great on the server.  I've looked at a few of the isomorphic ones and they look overly complicated.

**Comment by joewood** [comment]
I think I'm having problem with property propagation when it comes to sub-routes of nested components. These sit under the same container component, so this makes it very difficult to selectively propagate properties from a container down to those child components. Sending a reference to the entire store just doesn't feel like a good separation of concerns.

**Comment by SpainTrain** [comment]
I can commiserate with that struggle.  FWIW, I used a couple flux-ish libraries and eventually chose Redux.  Its use of a single state tree (store) where containers use "selectors" to propagate only the data their children need eases the messiness @joewood mentioned.  Selectors seem pretty effective at decoupling store/state tree from components.

There are many resources, but a couple I found helpful:

* https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4
* https://github.com/erikras/react-redux-universal-hot-example

**Comment by anjdreas** [comment]
I've been browsing related issues for some time and only now did I start to grasp how to properly do this in 1.0.0-rc1. Let me know if I've made a mistake, this is fresh knowledge and not thoroughly tested.

## Passing props to routes 
Route used for all examples below.
```jsx
React.render((
  <Router>
	<Route path="/" component={RootComp} myprop="foo">
	    <Route path="foo" component={FooComp}>
	       <Route path="bar" component={BarComp} />
	    </Route>
	</Route>
  </Router>
), document.getElementById('example'));
```

### Option 1) With route attributes
`this.props.route.myprop` is accessible in `RootComp`, but not in any of the child routes. The only workaround is to access `this.props.routes[0].myprop`, but I consider that hacky.

```javascript
class RootComp extends React.Component {
    render: {
        this.props.route.myprop // == "foo"
    }
}
```

### Option 2) To first level children with React.cloneElement()
Read `this.props.route.myprop` in `RootComp`, then pass down as extra property to its rendered children with `React.cloneElement()`.
**Note**: I can only seem to access `this.props.myprop` from `FooComp`, but **not** in `BarComp`. I was puzzled by this, so it seems to only pass to first-level children. Not sure if this is a bug or intended behavior?

```javascript
class RootComp extends React.Component {
    render: {
        React.cloneElement(this.props.children, {myprop: this.route.myprop})
    }
}

class FooComp extends React.Component {
    render: {
        this.props.myprop // == "foo"
    }
}

class BarComp extends React.Component {
    render: {
        this.props.myprop // == undefined
    }
}

```

### Option 3) To all route components with Router.createElement
Source: https://github.com/rackt/react-router/blob/master/docs/API.md#createelementcomponent-props

Add `this.props.myprop` to all route components with `createElement`. Useful for things like data stores.

```jsx
<Router createElement={createElement} />
```
```javascript
function createElement(Component, props) {
   // Add myprop to props for all route components
    _.extend(props, {myprop: "foo"})
  return <Component {...props}/>
}
```

**Comment by stevenleeg** [comment]
@anjdreas 
> Note: I can only seem to access this.props.myprop from FooComp, but not in BarComp. I was puzzled by this, so it seems to only pass to first-level children. Not sure if this is a bug or intended behavior?

I think this is intended behavior, as `RootComp`'s `this.props.children` consists of `[FooComp]`. `FooComp` gets passed the property (since `RootComp` is cloning it and passing it down) while `BarComp` isn't getting anything because `FooComp` isn't cloning/injecting the props for its `this.props.children` (which consists of `[BarComp]`).

Hopefully that makes sense, but I believe that's what's causing the injected props to only go one level deep.

**Comment by taion** [comment]
That's just how props work in React. Otherwise you can use context.

**Comment by anjdreas** [comment]
Thanks for the clarification. I think the main thing I've come to realize after using nested routes more lately is that you need to do this type of pattern in all route components that has child routes:

```js
class FooComp extends React.Component {
render() {
  // URL points to a child route component of FooComp, so render children
  if (this.props.children) {
    return this.props.children
  }

  // URL points to FooComp, so render FooComp
}
```

After realizing this, it's just a matter of repeatedly doing this to keep passing on `myprop` in solution 2, but I still don't like that pattern.

```js
  return React.cloneElement(this.props.children, {myprop: this.route.myprop})
```

**Comment by taion** [comment]
If you need to pass something down deeply, I recommend using React context. At this point this discussion doesn't really touch on React Router any more, though. Let's stop commenting on this issue unless there's something new to add regarding the original problem.

**Comment by dnutels** [comment]
Wouldn't named components solve this? 

The thinking is - route components are supposed to be route-driven - that is, should be able to restore their "state" by using route and routeParams (and params) only.

For cases where you must to pass some sort of configuration (because it should be used for data, that's your controller component's job to bring in) from parent route to child route - you opt in using named components:

```
<Route component={Parent}>
            <Route components={{child: Child}}/>
</Route>
```

and in `Parent`:

```
export class Parent extends React.Component {
    render() {
        const myProp = 1000;
        const Child = this.props.child.type;
        return (
            <main className="app-content dashboard">
                <Child someProp={myProp}/>
            </main>
        );
    }
}
```

Now, you should add some defensive code around it, in case no one passed named component in, but this seems like a cleaner workaround.

**Comment by taion** [comment]
No, that's wrong - use `cloneElement`, that's what it's for.

**Comment by dnutels** [comment]
@taion 

Wrong how? 

1. named components - ?
2. using named components inside route - ?
3. passing props to components - ?

I am missing something here and, frankly, it puzzles me that you'd say that purely React-esque way of doing this is wrong, but using this abomination (pardon my language) is right:

```
React.cloneElement(this.props.children, {myprop: this.route.myprop})
```

Can you perhaps elaborate a little?

**Comment by taion** [comment]
The `cloneElement` pattern is exactly how you inject new props into another component in React.

**Comment by dnutels** [comment]
@taion 

While this might be true (and I think that using `cloneElement` in such a way is code stink, on React part), it still doesn't explain why you think my suggested solution is wrong.

**Comment by taion** [comment]
You lose all the route props the routing context has injected into that component (`params`, &c.).

There are probably also nasty edge cases there if the child is e.g. a stateless component or something.

Anyway, I'm locking this issue for now, since it doesn't seem like there's any more meaningful discussion. I encourage everyone involved to learn more about standard React patterns.
