### ISSUE TITLE
How to config <Redirect /> programmatically ?

### ISSUE THREAD

**Issue by eriknyk** [rackt/react-router#1532]
Hi,
Somebody can help me,
I'm using v1.0.0-beta3 and I have routes defined programmatically: like
  
```javascript
export const routes = [
    {
        path: 'login',
        component: require('./components/Login.jsx')
    }, {
        path: '*',
        component: require('./components/NotFound.jsx')
    }
];

```

How can I define a [Redirect] (https://github.com/rackt/react-router/blob/master/doc/01%20Route%20Configuration/Redirect.md) programmatically?, I can't find examples for it,..
I'm trying to use it since <DefaultRoute ... seems is deprecated,..

Best Regards.

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/pull/1736#issuecomment-138982036
