### ISSUE TITLE
Possible redirect bug (1.0.0-beta3)

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1533]
Using 1.0.0-beta3, I tried to do this:

```
<Route component={require('./appview')} path="/">
    <Route component={require('./views/dashboard')} path="d" />
    // When users visit /, I want them to automatically redirect to /d. But this isn't working.
    <Redirect from="*" to="d" />
</Route>
```

But that didn't work. However, when I removed the `path="/"` prop off the top `<Route>` element -- the redirect started working correct again.

```
<Route component={require('./appview')}>
    <Route component={require('./views/dashboard')} path="d" />
    // Yay! Now this works.
    <Redirect from="*" to="d" />
</Route>
```

Is this a bug, or is this intentional behavior? It wasn't immediately obvious to me.

**Comment by qimingweng** [comment]
I think I'm having a similar issue with Redirect in `1.0.0-beta3`.

```
<Route path="main" component={Main}>
  <Route path="sub" component={Sub}/>
  <Redirect from="blah" to="sub"/>
</Route>
```

Going to `/main/blah` redirects to `/sub` instead of `/main/sub`.

**Comment by knowbody** [comment]
for now use absolute path, the error is being thrown if you don't. The [docs are here](https://github.com/rackt/react-router/blob/master/docs/Redirect.md) and let's continue the discussion about the enhancement in #1658
