### ISSUE TITLE
Set query without changing path

### ISSUE THREAD

**Issue by modernserf** [rackt/react-router#1535]
I work on a data visualization app that uses the query for search parameters, e.g. date range, keywords, etc. There are a number of places where I'd like to set _just_ the query parameters without altering the path. 

The way this works now (with either Link or transitionTo) requires me to have the current pathname. `<Link query={{foo: "bar"}} />` treats the empty `to` prop as "undefined", though its classic HTML equivalent `<a href="?foo=bar"/> ` works as a relative link. 

Is there a way I can set the query without getting the current path from the router or digging into the context?

**Comment by ryanflorence** [comment]
not yet:

https://github.com/rackt/react-router/issues/1828
