### ISSUE TITLE
Suggestion for multiple components extension/change

### ISSUE THREAD

**Issue by Nickman87** [rackt/react-router#1537]
Hi,

I would like to propose an extension to the multiple components system as well as a change to the current system. Currently I'm working on implementing both changes in my own fork accompanied with tests.

**Change to current system**
Currently it is possible to give a Route multiple components by using the `components` prop. When a multi-component route has child routes defined, these children will be passed to all components defined in the multi-component route.

ex:
```Javascript
<Router history={new MemoryHistory('/')}>
	<Route name="root" component={MultiParent}>
		<Route components={{first: Parent, second: Parent}}>
			<Route path="/" component={Child} />
		</Route>
	</Route>
</Router>	
```

This will result in a React Tree:
```XML
<MultiParent>
	<first:Parent>
		<Child />
	</first:Parent>
	<second:Parent>
		<Child />
	</second:Parent>
</MultiParent>
```

I believe this is not really useful behaviour as all child nodes would be duplicated from then on out. What I propose is to make the multiple component Route act as a "child collector" for its parent. This means that it will collect both the specified components AND the child component(s) and pass them on to its parent, just as it does with its own components.

This would result in the following React tree (depending on the specification of the MultiParent render method of course):
```XML
<MultiParent>
	<first:Parent>
	</first:Parent>
	<second:Parent>
	</second:Parent>
	<Child />
</MultiParent>
```

This way, no duplication is present and you get a more consistent way to work with nested routes.

**Extension to current routes**
In our application we have a use-case where a nested route should have an influence on one of its parent routes by adding an extra component to it. Therefore I propose to introduce the additional syntax of `parent_components`.

This property houses an object of which the keys reference a named route. The values in this object should be objects of which the keys represent the property names of the matching route and will be merged with the already present "components" property. These object can contain multiple levels to support the passing of properties to already defined components.

A sample test I've written to clarify what I mean:
```javascript
var Parent = React.createClass({
    render() {
        return <div>parent{this.props.children}</div>;
    }
});

var MultiParent = React.createClass({
    render() {
        return <div>-{this.props.first} - {this.props.children} - {this.props.second} - </div>;
    }
});

var Child = React.createClass({
    render() {
        return <div>child</div>;
    }
});

it('renders nested parent_components compositions', function(done) {
    render((
		<Router history={new MemoryHistory('/')}>
			<Route name="root" component={MultiParent}>
				<Route components={{first: Parent}}>
					<Route component={Parent}>
						<Route path="/" component={Child} parent_components={{root: {second:Child}}}/>
					</Route>
				</Route>
			</Route>
        </Router>	
    ), div, function() {
        expect(div.textContent.trim()).toEqual('-parent-parentchild-child-');
        done();
    });
});
```

This could get more complex by adding an extra child route for example with the following parent_components: `{{root: {second: {extra: Child}}}`. This will set the "extra" property of the "second" component in the "root" Route.

I'd love to get some feedback on the suggested changes as well as possible implementation concerns!

**Comment by ryanflorence** [comment]
`first` and `second` need to decide who renders the child, if you want to keep nesting, you need to specifiy `components` on child and let `first` render one and `second` render the other

```
<Router>
    <Route name="root" component={MultiParent}>
        <Route components={{first: Parent1, second: Parent2}}>
            <Route path="/" components={first: Child1, second: Child2} />
        </Route>
    </Route>
</Router> 
```

Then `Parent1` renders `this.props.children.first` and `Parent2` renders `this.props.children.second`.
