### ISSUE TITLE
How to access the Router.State if context is not set

### ISSUE THREAD

**Issue by filipmotum** [rackt/react-router#1538]
Hi,

My app consists of two parts that are fitted in an existing template : the main content and a menu-structure.

I am using the React router to define which Component must be loaded in the main content.
But I also want to be able to check the active route in my menu, to check visualize the Active menu-item.

Problem is that my MenuComponent has no router set on its context.
The rendering is done as follows in my App : 

```javascript
Router.run(routes, Router.HashLocation, (Root) => {
  React.render(<Root/>, document.getElementById('content'));
});

React.render(<Menu/>, document.getElementById('menu'));
```
Any ideas ?

**Comment by omerts** [comment]
I am assuming you are using v0.13.3
You could look at the sidebar example to get some ideas (https://github.com/rackt/react-router/tree/v0.13.3/examples/sidebar). You should probably have some type of a container component that will have the menu, and a RouteHandler as a place holder for different routes.

If you need to stay with your current solution
```javascript 
Router.run(routes, Router.HashLocation, (Root, routerState) => {
  React.render(<Root/>, document.getElementById('content'));
  // routerState will look like have:
  // action, path, pathname, query, routes
  React.render(<Menu routes={routerState.routes} />, document.getElementById('menu'));
});
```
