### ISSUE TITLE
Pass the router, or state, on Router's onUpdate method

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1539]
It will be great if we get some info about the router, and state, when the onUpdate callback is raised. Also, it is impossible to use the addTransitionHook, before, or during, the React.render(<Router...).

**Comment by cesarandreu** [comment]
+1

I'm trying to implement a router store for `v1.0.0-beta3` so I can replicate [fluxible-router](https://github.com/yahoo/fluxible-router/)'s behavior (so it's just a HOC, store, and an action), but it's proven to be tricky.

**Comment by faergeek** [comment]
You can get info about router state from `this`.
Something like:
```javascript
        <Router
          history={history}
          routes={routes}

          onUpdate={function() {
            store.dispatch(routerStateChange(this.state));
          }}
        />
```

**Comment by omerts** [comment]
@faergeek That works, thank you!

**Comment by klaasman** [comment]
What's the reason for not passing on information through arguments?
Now it is potentially an issue whenever someone (like me, currently) would like to have access to both the scope of the component as the scope of the `onUpdate` handler.

```javascript
export default class App extends React.Component {

  handleUpdate () {
    // now it's impossible to access the `this` scope of the `onUpdate`-handler, 
    // which means no reference to the state of the router
  }  

  render () {
    return (
      <Provider store={store}>
        {() => <Router
                 history={history}
                 children={routes}
                 // bind the handler to another scope
                 onUpdate={this.handleUpdate.bind(this)} 
               />
        }
      </Provider>
    )
  }
}

**Comment by faergeek** [comment]
Good question.

/cc @mjackson @ryanflorence

**Comment by lennerd** [comment]
:+1: for more information about not having arguments like the current route state on the onUpdate callback.
