### ISSUE TITLE
Readme example and rackt.github.io docs contradict

### ISSUE THREAD

**Issue by skfd** [rackt/react-router#1540]
Readme says you must do:

    <Route path="about" component={About}/>

While rackt.github.io tells the proper way to do it:

    <Route path="about" handler={About}/>

Can somebody remove or fix Readme example?

**Comment by vramana** [comment]
@skfd The former will be default way to do from `react-router@1.0.0` but if you are using `react-router@0.13.3` latter is the way to do.  

Look at this http://rackt.github.io/react-router/tags/v1.0.0-beta3.html for more documentation on `react-router@1.0.0`. I think you can close this issue.

**Comment by skfd** [comment]
I got it! `master` branch is for version 1, sorry.
