### ISSUE TITLE
Child Routes Help

### ISSUE THREAD

**Issue by chrismcv** [rackt/react-router#1541]
Hi, 
I'm using a "tab" control in my routes, and am passing a tab parameter in to select the active tab.

I've 3 tabs, "Contacts, Businesses, Patients", and an add button for each.

Ideally I want the following routes...
```
/contacts/patients
/contacts/patients/add
/contacts/businesses
/contacts/businesses/add
/contacts/contacts
/contacts/contacts/add
```

The add routes all have different handlers... but the outer tab control hander is the same route.

The add route is a dialog, and I would like it to overlay on the correct tab in the parent, so I've a `RouteHandler` in the tab control.  However, I can't seem to find routes that work.

```
<Route path="contacts/:tab"  handler={ContactTabs}>
      <Route path="/contacts/patients/add"  handler={PatientDialog} />
      <Route path="/contacts/contacts/add" handler={ContactDialog} />,
      <Route path="/contacts/businesses/add" handler={GroupDialog} />
    </Route>
```

Can you please advise on how I might be able to make this workable?

Thanks,
Chris

**Comment by aldendaniels** [comment]
It's an odd URL configuration, but this is how you'd do it:

```javascript
<Route path="/contacts"  handler={ContactTabs}>
  <Route path="/patients/add"  handler={PatientDialog} />
  <Route path="/contacts/add" handler={ContactDialog} />,
  <Route path="/businesses/add" handler={GroupDialog} />
</Route>
```

**Comment by knowbody** [comment]
yep, as @aldendaniels you should use `isActive` manage what tab is active
