### ISSUE TITLE
transition do not remount component

### ISSUE THREAD

**Issue by kindlejiang** [rackt/react-router#1542]
go back from detail comp to list comp will remount the list ,could Route add a prop to tell router just set comp's visibility hidden or visible,like
`<Route name="post" handler="Post" nounmount>`

**Comment by jedwards1211** [comment]
I'd love a feature like this too.  I want to preserve the transient state in a google map that's part of my home view.

**Comment by ryanflorence** [comment]
look at the pinterest example or ideas on how to keep old views around
