### ISSUE TITLE
using transition.to('/path') does not work with server-side rendering

### ISSUE THREAD

**Issue by lionng429** [rackt/react-router#1543]
I tried `v1.0.0-beta1` and `v1.0.0-beta2`

I did this `onEnter`
```
function(nextState, transition, done) {
  transition.to('/sign-in', null, { nextPathname: nextState.location.pathname });
  done();
}
```

and this to do server-side rendering
```
Router.run(routes, location, (error, initialState, transition) => {
  res.send(...)
}
```

I found that the initialState is always null after calling `transition.to` method, so Invariant Violation occurred

`Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need`

P.S. `onEnter` works well on client side

**Comment by alexfedoseev** [comment]
Just faced the same issue. I guess it should be smth like this:

```javascript
// on the server
Router.run(routes, location, (error, initialState, transition) => {

  if (transition.isCancelled) {
    return res.redirect(302, transition.redirectInfo.pathname);
  }

  /* ... */

}
```

**Comment by lionng429** [comment]
@alexfedoseev you're right, in react-router/modules/Router.js

```
loopAsync(transitionHooks.length, (index, next, done) => {
        transitionHooks[index](nextState, transition, (error) => {
          if (error || transition.isCancelled) {
            done(error); // No need to continue.
          } else {
            next();
          }
        });
      }
```

unlike client side, it will not do updateState to re-run the transition.

btw, any idea for persisting the query and state after `res.redirect`?

**Comment by alexfedoseev** [comment]
> btw, any idea for persisting the query and state after res.redirect?

They are available in `transition.redirectInfo` object.

**Comment by choonkending** [comment]
@alexfedoseev Thanks. Your solution solved my problem!

**Comment by alexfedoseev** [comment]
@choonkending :+1:

**Comment by omerts** [comment]
@alexfedoseev Thanks, saved me a lot of time.

**Comment by ryanflorence** [comment]
still baking server side rendering, it'll look something like this: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

**Comment by houssemFat** [comment]
thank you, saved my day !!
