### ISSUE TITLE
Question about animations (preserve components from unmounting during route transition)

### ISSUE THREAD

**Issue by schovi** [rackt/react-router#1544]
In our current project we use effect like accordion for few content pages. (example: open https://domena.redesignum.cz/search/hello%20github click on any domain and then in bottom right corner on "pokračovat"). As you can see. When you go on another page, there is animation which shrink first page and second page appear.

In my current solution I am using your "Without React Router" solution from react-routes doc.

Simplified code
```
render() {
  if(this.props.route == "/search/my-domain") {
    <div className="wrapper">
      <ContentTransition key="search" width="100%">
        <div className="search">
          <div>Search content</div>
        </div>
      </ContentTransition>
      <ContentTransition key="domains" width={0}>
        <div className="domains">
          <div>Domain content</div>
        </div>
      </ContentTransition>
    </div>
  } else if(this.props.route == "/domains") {
    <div className="wrapper">
      <ContentTransition key="search" width={100}>
        <div className="search">
          <div>Search content</div>
        </div>
      </ContentTransition>
      <ContentTransition key="domains" width={this.props.windowWidth - 100}>
        <div className="domains">
          <div>Domain content</div>
        </div>
      </ContentTransition>
    </div>
  }
}
```
Only change between pages are properties for ContentTransition component.
ContentTransition is my component which works same way as react Css Transitions, but animating engine is Greensock.

Point of this is that components are kept in dom and animations can works correctly.

When I tried to refactor into react-router (1.0.0.beta3 but same problem with 0.13.3) i split this if/else into separate components (pages) and applied them to react router.

```
<Route component={App}>
  <Route path="/search/:name" component={SearchPage} />
  <Route path="/domains" component={DomainsPage} />
</Route>

// SearchPage component
render() {
  <div className="wrapper">
    <ContentTransition width="100%">
      <div className="search">
        <div>Search content</div>
      </div>
    </ContentTransition>
    <ContentTransition width={0}>
      <div className="domains">
        <div>Domain content</div>
      </div>
    </ContentTransition>
  </div>
}

// DomainPage component
render() {
  <div className="wrapper">
    <ContentTransition width="100%">
      <div className="search">
        <div>Search content</div>
      </div>
    </ContentTransition>
    <ContentTransition width={0}>
      <div className="domains">
        <div>Domain content</div>
      </div>
    </ContentTransition>
  </div>
}
```

Animation there can't work correctly because on every route transitions the page component is replaced with another and child components too. This break animations.

Is there any solution or best practicies for this problem?

**Comment by jedwards1211** [comment]
I'm not exactly sure how `ContentTransition` works.  But you could wrap the child components of a route handler in a `ReactCSSTransitionGroup`, which keeps removed children mounted until their transitions have finished.  Just to forewarn you though -- `ReactCSSTransitionGroup` is unreliable when children are added/removed before transitions finish.  There are workarounds though.  Let me know if you decide to go that way and I'll dig up the React issue about CSSTransitionGroup.

**Comment by jedwards1211** [comment]
For react-router devs who are listening, I'm having similar difficulties deciding how handle routing in my app.   Not only do I want animations between routes, I want the home component to always stay mounted but hidden while other routes are active, so that a google map I have in it doesn't lose its transient state.

**Comment by ryanflorence** [comment]
animating components is no different with react router than anything else in react, please see this doc to maybe help think about how the router is really working and then try out ReactCSSTransitionGroup

https://github.com/rackt/react-router/blob/master/docs/ComponentLifecycleWhenRouting.md
