### ISSUE TITLE
Beta3 Router Will Leave.

### ISSUE THREAD

**Issue by aphillipo** [rackt/react-router#1545]
Hi Guys,

I'm having to do this in my form that is embedded in more than one place because in one area transition hook is not needed and context is not available.  It's horrible and it seems like the old way was better?  Maybe I'm doing it wrong:

    // above is asset form .....

    export default AssetForm;
    
    var addTransitionHook = function (Component) {
        return React.createClass({
            mixins: [ TransitionHook ],
            contextTypes: {
                router: React.PropTypes.object.isRequired
            },
            routerWillLeave: Component.routerWillLeave,
            render: function() {
                return <Component {...this.props} />
            }
        });
    };
    
    
    export var TransitionableAssetForm = addTransitionHook(AssetForm);

Thoughts?

**Comment by 0x80** [comment]
Have you figured it out yet? I'm in the same boat

**Comment by aphillipo** [comment]
Still doing that horrible stuff above...

**Comment by ryanflorence** [comment]
check out the Lifecycle mixin on master https://github.com/rackt/react-router/blob/master/docs/Lifecycle.md
