### ISSUE TITLE
setState doesn't raise createElement

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1546]
I have a route handler called App, which has sub-routes. 
My render method looks like  this:
```javascript
render() {  
    return (
      <AppCanvas predefinedLayout={1}>
        {this.props.children}
      </AppCanvas>
    );
  }
```
I am injecting props to children through the Router's createElement method. 
I don't want to use React.cloneElement bcs imho it is an antipattern, and is not the way to transfer props to children.
If I call setState from inside my App, createElement isn't raised.

**Comment by giltig** [comment]
I agree the above, we should think of a better and cleaner way to pass the props

**Comment by Shachar16290** [comment]
Agree.

**Comment by batazor** [comment]
:+1:

**Comment by gaearon** [comment]
Can you please post a full example so it's easier to reproduce and understand?

**Comment by omerts** [comment]
```javascript 
import React, { findDOMNode } from 'react';
import { Router, Route, Link, Navigation, TransitionHook } from 'react-router';
import {history} from 'react-router/lib/BrowserHistory';

var App = React.createClass({
  rerenderMe() {
    this.forceUpdate();
  },  
  render() {
    console.log('App has rendered.');
    return (
      <div>
        <button onClick={this.rerenderMe} type="button">
          Click me to re-render
        </button>
        {this.props.children}
      </div>
    );
  }
});

var Dashboard = React.createClass({
  renderCounter: 0,
  // Just in case
  shouldComponentUpdate(nextProps, nextState) {
    return true;
  },
  render() {
    console.log('Dashboard has rendered.');
    this.renderCounter++;
    return <h1>Dashboard (render count: {this.renderCounter})</h1>;
  }
});

function createElement(Component, props) {
  console.log('Create element has been called.');

  return <Component {...props} />;
}

React.render((
  <Router createElement={createElement} history={history}>
    <Route component={App}>
      <Route path="/" component={Dashboard}/>
    </Route>
  </Router>
), document.getElementById('example'));
```

Instead of setState, I am using forceUpdate in the example.

**Comment by gaearon** [comment]
Why do you think it's reasonable to have `createElement` called again in this case? The changes are happening down the tree. Why should the parent care about them?

**Comment by taurose** [comment]
I think he's just looking for a way to pass state down from one handler to the next, i.e. `<RouteHandler someProp={this.state.something} />` without using `cloneElement`. IIRC I suggested using `createElement` hook since I thought the state was managed outside.

I can't think of any simple solution. Ideally, I think, you should pull that state out of React (or at least `<Router>`)  into a flux store or a simple observable, and then pass actions and the subscription method using `createElement`. Instead of subscribing, it might be better to just pass the data and rerender `<Router>` on change (which could be implemented as a React component if you don't care about server rendering), but I'm not sure if the current API is up for that.

**Comment by gaearon** [comment]
I think this is correct. Either use `setState` and `cloneElement`, or inject something via `createElement`, but then either subscribe inside, or re-render from outside on every change.

**Comment by omerts** [comment]
@taurose, @gaearon  Don't you think this is kind of forcing a certain architecture? I am not saying whether it is better or not, imho the library should allow users freedom of choice (especially when it was like that before), maybe by simply leaving RouteHandler intact.

**Comment by ryanflorence** [comment]
`React.cloneElement` is public API and designed specifically for cases where you get an element you didn't create, and you don't care much about and need to add more stuff to it.

RouteHandler had way too many issues, the only issue with `children` is people thinking its "not the react way" when it is indeed public API.
