### ISSUE TITLE
1.0.0-b3 - NotFoundRoute no longer supported

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1547]
What's the correct way to provide a route not found component?

**Comment by faergeek** [comment]
```javascript
<Route path="*" component={GenericNotFound} />
```
Or:
```javascript
<Route path="/post/*" component={PostNotFound} />
```

**Comment by aldendaniels** [comment]
Thanks! I didn't know wildcard syntax was supported. Will be helpful once the path matching stuff is documented.

Closing since finishing the docs is a known TODO.
