### ISSUE TITLE
Indicate that github is ahead of stable/npm version

### ISSUE THREAD

**Issue by Lokeh** [rackt/react-router#1549]
Can we put some sort of indication in the README that the version on github (and all related examples/guides/etc) is for version 1.0.0-beta, and not for the official npm/stable version (0.13.3)?

This was very confusing as I tried to follow the instructions on github

**Comment by gaearon** [comment]
Hopefully fixed by https://github.com/rackt/react-router/commit/44a1692d97b95cd4f1cf995d97a55eb2da7dcd86.

;-)
