### ISSUE TITLE
Best hook for loading a fluxible module

### ISSUE THREAD

**Issue by jorge-pascual** [rackt/react-router#1550]
I'm working with Fluxible and trying to implement a pattern where react-router loads a "module" dynamically. 

A "Fluxible module" for me is something like this:

 `./modules/invoiceCreate`
```javascript
export default {
  path: 'view/:customerId',
  component: component,
  module: {
    stores: [ component.stores ],
    setup: component.setup    
  }
}
``` 
and this "module" is used as a route that is dynamically loaded in react-router... something like this:

```javascript
var childRoutes = [{
	  path: 'invoice',
	  getChildRoutes (state, cb) {
		    require.ensure([], (require) => {
		      cb(null, [
		        require('./modules/invoiceCreate')
		      ])
		    })
	  }			  	
  }];
```

I need to find a hook where I can do a "module load & set-up". The load is done by `require.ensure`. However, after that I need to initialise the module... and the initialisation logic is basically to register the stores and launch the `setup` action.

I've seen some interesting hooks... 

a) `router.TransitionHook`
This is the same that `routerWillLeave`. The problem is that (I suppose) the dynamic route hasn't been loaded at this point yet. So, I don't know the module stores and actions (setup).

b) `router onUpdate`
This is called as a callback of `router.setState(newstate, onUpdate)`. It could be a hook. However onUpdate doesn't have route information (maybe it is possible to pass router as a parameter... but I've tried it with no luck).

c) `createElement`
I could make a custom `createElement` that react-router calls every time it does a render. The problem here is performance. (I think) it is "very expensive" to do "heavy" things in each render. Moreover, a lot of logic would be executed even there aren't changes in routes.

Do anyone have any idea of what the best hook could be?

Thank you!

**Comment by ryanflorence** [comment]
use create element, subscribe to your stores or whatever in componentDidMount, send down as props in render, there is nothing non-performant about it unless you're doing zany things in render, which you shouldn't.
