### ISSUE TITLE
goBack in 1.0

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1551]
should `goBack` still return a boolean as described in #825? I'm getting undefined after upgrading to 1.0beta3, which breaks some of my back buttons that check first for `this.goBack()` before either going back or using a `transitionTo` to a default.

**Comment by ryanflorence** [comment]
We've not been able to nail down a reliable `canGo` implementation, maybe in the future though, until then we can't return anything of value in goBack.

https://github.com/rackt/react-router/pull/1376#issuecomment-118185067
