### ISSUE TITLE
How to handle against a route without component?

### ISSUE THREAD

**Issue by chiefGui** [rackt/react-router#1553]
I want to log out my user through `/logout/` url, but there doesn't exist any component available—just a JavaScript function such as `user.logout()`.

**Comment by knowbody** [comment]
why do you need a route for that? why not just use:

```jsx
<button onClick={this.handleLogout}>Logout</button>
```

**Comment by chiefGui** [comment]
Yeah, I went for that approach. Thanks! :+1:
