### ISSUE TITLE
Separating Route Components.

### ISSUE THREAD

**Issue by oliverbenns** [rackt/react-router#1554]
Hi there, I've got [this Gist](https://gist.github.com/oliverbenns/fe9830676d800122702e) and was just wondering why this doesn't seem to be working? If I manually add it to the router render it's fine but not as a separate file. It seems that doing this approach it doesn't pick up the /zones route.

I don't get any console or build errors. Running 1.0.0-beta3 .

**Comment by lionng429** [comment]
@oliverbenns what about in zone.js, instead of rendering the Route, return the Route component itself
```
return (
  <Route path="zones" component={ Zones } />
)
```

by the way, making up all routes in one file provides you the whole picture of your site (like a site map).

**Comment by knowbody** [comment]
the reason it does not work is because you are rendering single route. As @lionng429 said what you want to do is return a ReactElement instead.
