### ISSUE TITLE
Routes should still have names

### ISSUE THREAD

**Issue by ryancole** [rackt/react-router#1555]
`Route`  has been stripped of its `name` property. Currently, in version 1.0.0+, to use `Link` to link to a route handler, you have to provide the actual URL path. I think this is an oversight, because now if I want to just simply adjust my `Router` tree and give a `Route` a new URL, I have to go throughout my code and adjust my `Link`s. Previously, with a `name` property, I didn't have to do this at all. I was free to adjust the `path` of my `Route` and as long as the `name` stayed the same, my `Link`s worked. I think this ability to `Link` to a `Route` by name, and not URL, was like the main most compelling purpose of `Link`.

**Comment by Nickman87** [comment]
Related to: https://github.com/rackt/react-router/issues/1514

**Comment by mjackson** [comment]
Please see https://github.com/rackt/react-router/issues/1514#issuecomment-122011215
