### ISSUE TITLE
API is not working per example 

### ISSUE THREAD

**Issue by GurpreetSran** [rackt/react-router#1559]
Many users having this issue. Please update documentation or API.  

http://stackoverflow.com/questions/30990726/react-router-uncaught-typeerror-cannot-read-property-touppercase-of-undefined/31461467#31461467

**Comment by Agamennon** [comment]
wow!,  please do, i lost o lot of time trying to upgrade my stuff based on the documentation!

**Comment by gaearon** [comment]
Does this help?

https://github.com/rackt/react-router/commit/44a1692d97b95cd4f1cf995d97a55eb2da7dcd86
https://github.com/rackt/react-router/commit/50c9a232e25e30c6f1f9cb015f141020b51b61aa

Use the stable docs with the stable version:

http://rackt.github.io/react-router

**Comment by Agamennon** [comment]
Thanks Dan!

**Comment by GurpreetSran** [comment]
Thanks!
