### ISSUE TITLE
Using wrong route name in Link may cause: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by ElessarWebb** [rackt/react-router#1560]
I've seen better errors for non existent route names, but just encountered this one where I wrote

    <Link className="action" to="forum-post-detail-page" params={{..omitted}} />

where I should've written (note the name)

    <Link className="action" to="forum-thread-detail-page" params={{..omitted}} />

Chrome gives: Cannot read property '_currentElement' of null

Firefox is a bit more precise with a `internalInstance is null` in `unmountComponent`

This is react 0.13.3 with react-router 0.13.3

**Comment by ryanflorence** [comment]
better error messages would be great, will revisit them in #1407
