### ISSUE TITLE
How to getPathname(), getQuery() in 1.0.0?

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1562]
I had some code like the following using router v0.13:

```
  onGaugeClick(blockId) {
    this.transitionTo(this.getPathname(), {}, {editBlock: blockId});
  },
```

The idea being that if I change the route to this particular component, it won't break this method.

Why were `getPathname()` and `getQuery()` removed from the `State` mixin in 1.0.0?  Did some kind of philosophical opposition to these develop?

It's very convenient to be able to code up components that can modify the query in a route-agnostic way.

**Comment by taurose** [comment]
See https://github.com/rackt/react-router/issues/1502

**Comment by knowbody** [comment]
related to #1502, closing
