### ISSUE TITLE
Confused about order of operations for AsyncProps, onEnter and getChildRoutes in 1.0

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-router#1563]
I'm confused on the order of operations for AsyncProps, onEnter, and getChildRoutes in 1.0.

Consider the following Router code:

```
<Router createElement={AsyncProps.createElement} history={history}>
	<Route component={AsyncProps} renderInitialLoad={spinner}>
		<Route component={require('./appview')}>
			<Route component={require('./views/dashboard')} getChildRoutes={(cb) => cb(null, [])} onEnter={Auth.onEnter} path="d">
				<Route component={require('./views/inner')} path="inner" />
			</Route>
			<Route component={require('./views/login')} path="login" />
		</Route>
	</Route>
</Router>
```

My expectation here is that when I navigate to `/d/inner` I have this order of operations:

```
Spinner Shows
  -> loadProps for AppView fires
  -> loadProps for Dashboard fires
  -> onEnter for Dashboard fires
  -> getChildRoutes for Dashboard fires
  -> Dashboard component is loaded
```

However, what currently happens is this:

```
getChildRoutes for Dashboard fires
  -> Spinner Shows
  -> onEnter for Dashboard fires
  -> loadProps for AppView fires
  -> loadProps for Dashboard fires
  -> Dashboard component is loaded
```

1) Why does `getChildRoutes` fire as the very first thing? This means I don't see the App spinner until that function is processed and I can't make use of any of the data fetching I've setup in the `AsyncProps` for the App. In my app, I don't know what the child routes will be until I've had a chance to ask the API some information first.
2) Why does `onEnter` fire before `loadProps`? This means I can't use the props I fetched in `loadProps` to handle redirects inside `onEnter`. The most common example of this is something like this: Request /posts/123 -> AsyncProps does a check to see if 123 is a valid post -> onEnter fires and if 123 is invalid, redirects to a 404 page. However, because onEnter fires first, there's no way to do the async validation.

**Comment by itsmepetrov** [comment]
+1

**Comment by ryanflorence** [comment]
AsyncProps is experimental, can't provide support right now for it, but I'll revive it after 1.0 ships.
