### ISSUE TITLE
Optimizing re-bundle time for react-router in webpack

### ISSUE THREAD

**Issue by balanceiskey** [rackt/react-router#1564]
Hi dudes,

I'm working on decreasing my re-bundle time when working with webpack and react-router using the noParse/alias strategy outlined here:

https://christianalfoni.github.io/react-webpack-cookbook/Optimizing-development

And while I've got it bundling faster now, it's not quite functional because of bundling against UMD:

https://github.com/christianalfoni/react-webpack-cookbook/issues/30

Anyone have any idea on how to accomplish this?

**Comment by taurose** [comment]
Not sure why the UMD build doesn't work like this. But to me using noParse with react-router for faster rebuilds sounds like overkill. React-router isn't that big, so it shouldn't make that much of a difference anyway.

Also, to reduce **re-**bundling speed have you tried generating a separate vendor chunk instead? It's described in the [cookbook](https://christianalfoni.github.io/react-webpack-cookbook/Split-app-and-vendors.html), but you can also make it more dynamic like described [here](https://stackoverflow.com/questions/26603499/simple-solution-to-share-modules-loaded-via-npm-across-multiple-browserify-or-we) or use a [plugin](https://github.com/BohdanTkachenko/webpack-split-by-path).

**Comment by gaearon** [comment]
Adding `imports?React=react` fixes UMD build with `noParse`. I'm not sure if there's anything we can (or should) fix on our end though: https://github.com/christianalfoni/react-webpack-cookbook/issues/30#issuecomment-122449738.

**Comment by balanceiskey** [comment]
@gaearon's got it, closing this one.
