### ISSUE TITLE
Nested Routes higher Rendering priority than unnested DefaultRoute

### ISSUE THREAD

**Issue by Davorak** [rackt/react-router#1565]
edit - this is with version 0.13.3 from npm 

# Nested empty route takes priority over unnested `DefaultRoute`

```
var routes = (
  <Route path="/" handler={App}>
    <DefaultRoute handler={DefaultApp} />
    <Route handler={DefaultApp} path="hi" />
    <Route handler={LoggedIn}>
      <Route handler={NotDefaultApp} path="hi" />
    </Route>
  </Route>
);
```

When going to `localhost:3000` I would expect to see `App` and `DefaultApp` to render.  Instead I see `App` and `LoggedIn` render.

![image](https://cloud.githubusercontent.com/assets/810921/8742247/f7080114-2c28-11e5-9e25-62a1ee00d3a8.png)

# Nested `DefaultRoute` takes priority over unnested `DefaultRoute`

```
var routes = (
  <Route path="/" handler={App}>
    <DefaultRoute handler={DefaultApp} />
    <Route handler={DefaultApp} path="hi" />
    <Route handler={LoggedIn}>
      <DefaultRoute handler={NotDefaultApp} />
      <Route handler={NotDefaultApp} path="hi" />
    </Route>
  </Route>
);
```
![image](https://cloud.githubusercontent.com/assets/810921/8742278/5709f55e-2c29-11e5-93cf-5a2103c91d8a.png)

The order of the `DefaultRoutes` does not matter, I would expect the first `DefaultRoute` to render since this is what happens with non-default routes.

Using:
```
var routes = (
  <Route path="/" handler={App}>
    <DefaultRoute handler={DefaultApp} />
    <Route handler={DefaultApp} path="hi" />
    <Route handler={LoggedIn}>
      <DefaultRoute handler={NotDefaultApp} />
      <Route handler={NotDefaultApp} path="hi" />
    </Route>
  </Route>
);
```
![image](https://cloud.githubusercontent.com/assets/810921/8742375/4cf11f88-2c2a-11e5-8672-12277adfd4f1.png)

Now switch the order of the routes to `hi`:
```
var routes = (
  <Route path="/" handler={App}>
    <DefaultRoute handler={DefaultApp} />
    <Route handler={LoggedIn}>
      <DefaultRoute handler={NotDefaultApp} />
      <Route handler={NotDefaultApp} path="hi" />
    </Route>
    <Route handler={DefaultApp} path="hi" />
  </Route>
);
```
![image](https://cloud.githubusercontent.com/assets/810921/8742389/634d3032-2c2a-11e5-8109-d634767316c8.png)

# `DefaultRoutes` nested at the a same get their priority from there order

This is what I would expect.

Using:
```
var routes = (
  <Route path="/" handler={App}>
    <Route handler={LoggedIn}>
      <DefaultRoute handler={DefaultApp} />
    </Route>
    <Route handler={LoggedIn}>
      <DefaultRoute handler={NotDefaultApp} />
    </Route>
  </Route>
);
```
The `DefaultApp` renders:
![image](https://cloud.githubusercontent.com/assets/810921/8742429/e0adfa3e-2c2a-11e5-9e5d-0807b0a85470.png)

Nesting the `DefaultRouter` works around my initial issue, but in order to use the `DefaultRoute` functionality I have to know how deeply nested the sibling routes are. Require this context awareness seems to break easy composition.

**Comment by Davorak** [comment]
Better work around that achieves less context aware routes:

```
var routes = (
  <Route path="/" handler={App}>
    <Route path="" handler={DefaultApp} />
    <Route handler={LoggedIn}>
      <Route path="" handler={NotDefaultApp} />
      <Route path="hi" handler={NotDefaultApp} />
    </Route>
  </Route>
);
```

With the routes above `App` and `DefaultApp` will render and when removing the first `DefaultApp` Route:

```
var routes = (
  <Route path="/" handler={App}>
    <Route handler={LoggedIn}>
      <Route path="" handler={NotDefaultApp} />
      <Route path="hi" handler={NotDefaultApp} />
    </Route>
  </Route>
);
```

`App`, `LoggedIn`, and `NotDefaultApp` will render.

**Comment by ryanflorence** [comment]
they have the same path, this only happens if you've got a route config that doesn't make sense. Flesh out your paths for a real app and see if we still have a problem.

**Comment by Davorak** [comment]
> Flesh out your paths for a real app and see if we still have a problem.

I encountered this problem while working on application under development.  I then simplified the code for presentation here.

I have not been using DefaultRoute component as of yet because expect I would run into this issue again.
