### ISSUE TITLE
Unbind/Stop Router Documentation

### ISSUE THREAD

**Issue by agilgur5** [rackt/react-router#1567]
Other routers, such as [page.js](https://github.com/visionmedia/page.js), have support for entirely unbinding the router (stopping it completely), and after searching around quite a bit, I haven't quite found a clear way to do this with React-Router.

For my specific use case, I'm currently migrating a Backbone App to a full React/Flux App; to be as gradual as possible, currently part of the user flow is in React-Router before eventually being pushed into the Backbone App seamlessly. This requires me to at some point fully unbind React-Router and instead bind Backbone's Router to the routes.

**Comment by agilgur5** [comment]
Well after searching some different keywords and scrolling down a bit, I did find `router.stop` from #742. That being said, this isn't listed in the docs at all it would seem (Ctrl+F finds neither "unbind" nor "stop") although it should be under Top-Level API. Can this be added in the docs there (preferably using the verb unbind as well as stop)? I can make a PR for this :)

**Comment by gaearon** [comment]
It's going to be possible in 1.0, see the relevant part of [Ryan's talk](https://youtu.be/BF58ZJ1ZQxY?t=23m59s).

**Comment by ryanflorence** [comment]
to stop the router you simply unmount the component.

in 1.0 you'll have a "pure router" that doesn't listen the url, you feed it locations from your old app and it renders.

providing "stop" and "start" will only lead to bugs, so I don't think we'll have that as public api.
