### ISSUE TITLE
Enable Radium hover styles on <Link/>

### ISSUE THREAD

**Issue by danieldunderfelt** [rackt/react-router#1568]
Hi!

I noticed that I can't apply Radium hover styles on a link element, as the `<Link />` component doesn't seem to be Radium-aware enough. When I apply a Radium style and inspect the `<a>` element, the `':hover'` key is inlined in the style prop and the styles just show up as our old friend `[object Object]`.

I realise that, due to react-router being at the center of apps and the countless other React libraries people use, accommodating everything is very difficult. If you do not want to implement some kind of Radium fix, I totally understand. However, Radium is a very convenient way to add hover styles, which are crucial for links. Especially if it's already in your stack.

Thanks!

**Comment by taurose** [comment]
I don't think there's much react-router can or should do about that. From what I can tell, in order to make `<Link>` radium-aware, it would need to become a dependency and affect all users, whether they use radium or not.

Also, it seems like you can just do 

```js
import {Link} from 'react-router';
import Radium from 'radium';

var RadiumLink = Radium(Link);
```

**Comment by danieldunderfelt** [comment]
Oh, nice! I tried something like that, but it didn't work. I'll try this now. Thanks!

**Comment by vidjuheffex** [comment]
import {Link} from 'react-router';
import Radium from 'radium';

var RadiumLink = Radium(Link);

does not work (anymore?)

My links will receive interactive styling, but will no longer lead anywhere when clicked.
