### ISSUE TITLE
Path not injected into Route Handler

### ISSUE THREAD

**Issue by willdady** [rackt/react-router#1569]
According to the docs the current application path should be injected into each Route Handler component. Properties params, query and path are expected however only query and params is present. Path property is not injected.

v0.13.3

**Comment by tarikakyol** [comment]
same here

```javascript
<Route handler={App} path='/'>
    <Route handler={Search} path='/assets' name='assets'/>
</Route>

var App = React.createClass({
  render: function() {
    // this.props.path ==> undefined
    return (
      <RouteHandler {...this.props}/>
    );
  }
});
```

**Comment by chrisfinch** [comment]
Any movement on this one?

**Comment by taurose** [comment]
Seems to be an error in the docs.

You can either pass `path` down from the [Router.run](http://rackt.github.io/react-router/#Router.run) callback

```js
Router.run(function(Root, state) {
  React.render(<Root path={state.path}  />, ...);
});
```

or use the [State](http://rackt.github.io/react-router/#State) mixin

```js
var Component = React.createClass({
  mixins: [ Router.State ],

  render: function () {
    var path = this.getPath();
    ...
  }
});
```

**Comment by chrisfinch** [comment]
@taurose Thanks! Your first suggestion worked great for me.

**Comment by ryanflorence** [comment]
it used to a long time ago, then didn't, now it does on master via `this.props.location`
