### ISSUE TITLE
[1.0.0-beta3] Nested Route with path="/" being matched, but this.props.children is undefined

### ISSUE THREAD

**Issue by ryancole** [rackt/react-router#1570]
I'm using version 1.0.0-beta3, and have the following `Router` ...

```
export default (
  <Router history={history}>
    <Route component={reduxRouteComponent(store)}>
      <Route path="/" component={ApplicationView}>
        <Route path="auth">
          <Route path="signin" component={AuthenticationSigninView} />
          <Route path="signup" component={AuthenticationSignupView} />
          <Route path="signout" component={AuthenticationSignoutView} />
        </Route>
        <Route path="replay">
          <Route path="/" component={ReplayIndexView} onEnter={handleOnEnter} />
          <Route path=":id" component={ReplayDetailView} onEnter={handleOnEnter} />
        </Route>
      </Route>
    </Route>
  </Router>
);
```

When I navigate to `/replay`, I get no warnings about no matching routes, which means it's matching something. But, `this.props.children`, in `ApplicationView`, is `undefined`. So, `ReplayIndexView` is never created and rendered.

Any ideas?

**Comment by cgmgraphics** [comment]
@ryancole I ran with same issue the component was there but accessible from `this.props[0]` when going to the nested route with path="/" in my case, not sure why it is not set to `this.props.children`.

Note that all remaining routes components are properly accessible on `this.props.children`

**Comment by jptaylor** [comment]
Having the same issue, also using Redux: 

```
const routes = {
  path: `/${__APPLY_ROOT__}/`,
  component: Apply,
  childRoutes: [
    { path: '/account', component: AccountForm }
  ]
};


/*
 * Create the Root application
 */
class Root extends React.Component {
  render() {
    return (
      <div>
        <Provider store={store}>
          {() =>
            <Router history={history} children={routes} />
          }
        </Provider>
      </div>
    );
  }
}
```

**Comment by ryancole** [comment]
@cgmgraphics hmm, not sure what you mean by using `this.props[0]`. in my application, the component that owns the children to be rendered (the nested react router `Route` components in this case) has other props, including the various react-router-injected props. doing `this.props[0]` doesn't seem to do the correct thing in that case.

in the event where the nested route works (for example, auth related routes all work, because none use a `path="/"`), `this.props.children`, within the owning component, looks like this ...

![working](https://cloud.githubusercontent.com/assets/484801/8791768/dcac0320-2f24-11e5-9f59-0c78e6b07df8.png)

when accessing the nested route with the `path="/"`, `this.props.children` is undefined.

this is likely an unintended bug in one direction or the other. either the scenario above, with my auth routes, should not work because the parent `Route` component has no `component` prop. or, the other direction being this nested route with the `path="/"` should work and does not.

**Comment by cgmgraphics** [comment]
@ryancole This is how my this.props looks like on the container component rendering the view with 
`path="/"` 
![screen shot 2015-07-21 at 10 37 14 am](https://cloud.githubusercontent.com/assets/1799386/8803407/c1f4c07e-2f94-11e5-8b1a-76ba5517fdc9.png)

It doesnt make sense to me either that this.props[0] have my component either. Main difference though is that I am lazy loading the child component with `path="/"` and the route configuration as well. 

```javascript
export default {
    path: '/',
    getComponents (cb) {
        require.ensure([], (require) => {
            cb(null, require('./Dashboard'))
        }, "signedin")
    }
};
```

**Comment by ryancole** [comment]
hmm, must be something to do with the async nature of your routes. mine don't look like that. weird.

**Comment by ryancole** [comment]
I added some tests that I think target my scenario.

**Comment by ryanflorence** [comment]
`<DefaultRoute/>` is back as `<IndexRoute/>`
