### ISSUE TITLE
Default Route in nested routes in 1.0.0

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1571]
Hey, 

I know that default routes are now deprecated, and I have seen issue #1333, on how to have a default route. My problem is that the solution in #1333 is not working in nested inner routes. 
This is my routes config: 
```javascript
<Route component={App}>
    <Route path="/" component={FeedPage}/>
    <Route name="person" path="persons/:id" component={PersonPage}>
      <Route name="personDashBoard" path="dashboard" component={PersonDashBoard}/>
      <Route name="personData" path="data/:dataId" component={PersonData}/>
      <Route name="info" path="/" component={PersonInfo}/>
    </Route>
</Route>
```

FeedPage as a default handler is working perfect. PersonInfo as a default handler is not working. I don't want to remove the path from the person route handler, bcs all sub-routes need it in their urls.

**Comment by aphillipo** [comment]
I think you'll be able to just remove path="/" from <Route path="/" component={FeedPage}/> ??  At least that works for me.

**Comment by omerts** [comment]
@aphillipo thanks for the answer. The FeedPage, is working fine, my problem is with the indder PersonInfo route which isn't working.

**Comment by srph** [comment]
Same issue here

Maybe we could use `{this.props.children || <PersonInfo {...this.props />}` as a *workaround*. Not so cool, though.

**Comment by omerts** [comment]
@srph thanks

**Comment by BerkeleyTrue** [comment]
> Maybe we could use {this.props.children || <PersonInfo {...this.props />} 

That is actually the recommend way.

**Comment by srph** [comment]
Recommended, but not so convenient, sadly. :disappointed:

Mind closing this issue, @omerts? :smile:

**Comment by omerts** [comment]
Another way that isn't so convenient is to add the base route to all children as such:
```javascript
<Route component={App}>
    <Route path="/" component={FeedPage}/>
    <Route name="person" component={PersonPage}>
      <Route name="personDashBoard" path="persons/:id/dashboard" component={PersonDashBoard}/>
      <Route name="personData" path="persons/:id/data/:dataId" component={PersonData}/>
      <Route name="info" path="persons/:id" component={PersonInfo}/>
    </Route>
</Route>
```

**Comment by BerkeleyTrue** [comment]
> Recommended, but not so convenient, sadly. 

Why is that not convenient? That is the react way. The whole point of 1.0.0 is to reduce the opinionated React-router stuff.

**Comment by srph** [comment]
Kind of hides stuff. I was so used to checking `routes.js`, and know about the entire application.
