### ISSUE TITLE
Invariant (red herring) error is hiding other real error

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1572]
For errors such as favicon not found, and other inner errors, it looks like the invariant error is catching them, and just showing:
```
 Invariant Violation: Server-side <Router>s need location, branch, params, and components props.
```
This makes it hard to fix errors.

**Comment by ryanflorence** [comment]
server side routing is still baking in 1.0, but the block of code throwing that error is not capable of catching other errors, especially errors in your server side app https://github.com/rackt/react-router/blob/v1.0.0-beta3/modules/Router.js#L204-L226

**Comment by omerts** [comment]
Errors in server side rendering throws the above exception, you could also see this issue: https://github.com/rackt/react-router/issues/1361 which got this error because the browser was trying to get a favicon.

**Comment by omerts** [comment]
For example,  in the following code when going to home page (ie /), instead of getting a route doesn't exist, I get the invariant error:
```javascript 
import express from 'express';
import React from 'react';
import { Router, Route, Link } from 'react-router';
import Location from 'react-router/lib/Location';
import { history } from 'react-router/lib/HashHistory';

const app = express();

const App = React.createClass({
  render() {   
    return (
      <div>
        <ul>          
          <li><Link to="/form">Form</Link></li>
        </ul>
        {this.props.children}
      </div>
    );
  }
});

const routes = <Route path="/" component={App} />;     

function render(req, res) {
  let location = new Location(req.path, req.query);

  Router.run(routes, location, (error, initialState, transition) => {
    if (error) {
      res.status(500).send('Something broke!');
    }
      
    let appContent = React.renderToString(<Router {...initialState} />);  
    
    res.status(200).send(appContent);         
  });
}

// To avoid favicon throwing an error
app.get('/favicon.ico', (req, res, next) => {
  let icon = '';

  res.writeHead(200, {
   'Content-Type': 'image/png',
   'Content-Length': icon.length
  });

  res.end(icon); 
});

app.get('*', (req, res, next) => {
  return render(req, res);
});

let server = app.listen(8080, () => {
  var host = server.address().address;
  var port = server.address().port;

  console.log(`Server started listening at ${host}:${port}`);
});
```

**Comment by ryanflorence** [comment]
yes exactly, you have to handle static files, like favicon, with your server side router before you hand the path off to react router.

> it looks like the invariant error is catching them

This is not possible, our code is not capable of catching your server side errors.

I don't know why your'e getting the error, what you did looks correct. Since building on top of the history package we had to rework server rendering, and its still baking on the master branch, some code should be landing today or tomorrow.

**Comment by bdefore** [comment]
I'm getting this error too, and it's unrelated to a `favicon.ico` and I'm not sure what it could be related to
