### ISSUE TITLE
use duck-typing instead of `instanceof`

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#1573]
I would advocate to @mjackson or @ryanflorence react-router use duck-typing instead of relying on `instanceof`.

Using duck-typing instead of `instanceof` guarantees that as long as the object has the correct shape it will be accepted. It looks like history objects only requires a few methods. 

I'm be down to submit a PR for this.

ref #1455

**Comment by ryanflorence** [comment]
with the new history package that the router is built on, we don't do instanceof checks anymore, thanks ;)
