### ISSUE TITLE
[1.0.0-beta3] Url Parameters are getting decoded once per nesting

### ISSUE THREAD

**Issue by dozoisch** [rackt/react-router#1574]
Using React-Router 1.0.0-beta3

Let's say I have an URL like `point/:some_token`

Where some_token is encoded in base64, so it may contain a `+` sign. I encoded it using encodeURIComponent and got something like `aaa%2Bbbb`.

When I hit the url I can see from a console log that https://github.com/rackt/react-router/blob/master/modules/URLUtils.js#L118-L121 is getting hit twice with the URL. First time where v equals the whole url `/point/aaa%2Bbbb` (which gives `/point/aaa+bbb`, and then a second time with only the token but with the `+` sign already decoded once `aaa+bbb` => `aaa bbb`.  Which is no longer the valid token anymore.

---

My routes look like

```js
<Router>
  <Route component={ApplicationWrapper}>
    <Route path="point/:some_token" component={MyComponent} />
  </Route> 
</Router>
```

If I put the route as top level (no wrapper), it works eg:

```js
<Router>
  <Route path="point/:some_token" component={MyComponent} />
</Router>
```

**Comment by dozoisch** [comment]
This is still an issue. My current workaround is to use a query param.

**Comment by keyanzhang** [comment]
+1

**Comment by ryanflorence** [comment]
added a test case that passes on master: 13f948b29d6fc1a0811e0ae6932880130cfd7c85

**Comment by dozoisch** [comment]
I should've have been clearer! It has to be nested route, I'll put up a PR with a failing test
