### ISSUE TITLE
child route component can't be rendered

### ISSUE THREAD

**Issue by hon** [rackt/react-router#1575]
I am using child router in my project:
```javascript
import React from 'react/addons';
import { Router, Route} from 'react-router'
import HashHistory from 'react-router/lib/HashHistory';
import Pages from './pages/';

let router = (
  <Router history={new HashHistory}>
    <Route path="/" component={Pages.HomePage} />
    <Route path="shop" name="shopList" component={Pages.ShopPage}>
      <Route path=":shopId" name="shopDetail" component={Pages.ShopDetail} />
    </Route>
  </Router>
);


React.render(router, document.body);
```
```/#/``` Pages.HomePage is rendered,
```/#/shop``` Pages.ShopPage is rendered,
but,
``` /#/shop/123``` still render Pages.ShopPage
is there something wrong?

**Comment by taurose** [comment]
It's how the router works: given a route config and a path, it will first find the matching routes, in your case:

```js
<Route path="shop" name="shopList" component={Pages.ShopPage}>
    <Route path=":shopId" name="shopDetail" component={Pages.ShopDetail} />
</Route>
```

And then create and render the react tree:

```js
<Page.ShopPage>
  <Pages.ShopDetail />
</Pages.ShopPage>
```

So `<Pages.ShopDetail />` will be passed to `<Pages.ShopPage />` as `props.children`.

If you don't want that, you can keep your route config flat:

```js
let router = (
  <Router history={new HashHistory}>
    <Route path="/" component={Pages.HomePage} />
    <Route path="/shop" name="shopList" component={Pages.ShopPage} />
    <Route path="/shop/:shopId" name="shopDetail" component={Pages.ShopDetail} />
  </Router>
);
```

**Comment by hon** [comment]
Thank you. I'v tried and it works.
But, what are the differences between the nest way and non-nest way?

**Comment by joshblack** [comment]
As the previous commenter said, when the router matches a path that points to a nested component, then the nested component will be rendered by the parent route through `this.props.children`. If you keep the route config flat then the router will instead just render the component you give it as the top level component for the path.

**Comment by hon** [comment]
ok, thank you.
