### ISSUE TITLE
Coffeescript in documentation

### ISSUE THREAD

**Issue by Narven** [rackt/react-router#1579]
In [http://rackt.github.io/react-router/](http://rackt.github.io/react-router/) in the documentation where is some coffeescript language in the middle of all javascript.

`
Router.run(routes, Router.HashLocation, (Root) => {
  React.render(<Root/>, document.body);
});
`

I think it should be something  like:

`
Router.run(routes, Router.HashLocation, function(Root){
  React.render(<Root/>, document.body);
});
`

**Comment by michalkvasnicak** [comment]
It isn't coffeescript but [ECMAScript 6 fat arrow function syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by BerkeleyTrue** [comment]
yes, indeed it is standard javascript now.

**Comment by Narven** [comment]
Ok, but why is that code diferent from all the rest?

And at least it could be something that browsers could understand.

thanks

**Comment by agilgur5** [comment]
Chrome and Firefox can already "understand" it :) Most people use Babel to transpile down to ES5 anyway. As it's already part of the next version of ES, I don't think this is the documenter's problem to address, and rather, something that users should learn to understand.

At the same time, I've seen a few sites have docs/examples in both ES5 and ES6 (in a tabbed manner).
The documentation should be standardized to use either ES5 or ES6 syntax though; there's at least a few places where things differ like `render () {` vs. `render: function () {` for no particular reason.

**Comment by BerkeleyTrue** [comment]
es6 is javascript now. I don't think we need to choose to use object literal shorthand or not. It would be the same as saying we should not use semicolons in the documentation or saying we should always use named function.

We should stick to javascript and arrows/objectLiteralShorthand/const/let are all javascript now.

**Comment by Narven** [comment]
@BerkeleyTrue  `es6 is javascript now.`

It will be when it works on browsers by default and by standard. Till then... is just another "plugin" that you can use. And to use other 20 other plugins and libs to make it work.

At least this is my option.
Thanks

**Comment by Narven** [comment]
@agilgur5 `(At the same time, I've seen a few sites have docs/examples in both ES5 and ES6 using tabs).`

Completly agree with that.

**Comment by moretti** [comment]
I agree with @narven, it's confusing for people not familiar with ES6 features.

This code, for example:
```.js
var Settings = React.createClass({
  statics: {
    willTransitionTo: function (transition, params, query, callback) {
      auth.isLoggedIn((isLoggedIn) => {
        transition.abort();
        callback();
      });
    },

    willTransitionFrom: function (transition, component) {
      if (component.formHasUnsavedData()) {
        if (!confirm('You have unsaved information,'+
                     'are you sure you want to leave this page?')) {
          transition.abort();
        }
      }
    }
  }
});
```
should either be completely in ES6:
```.js
class Settings extends React.Component {
  willTransitionFrom(transition, component) {
    if (component.formHasUnsavedData()) {
      if (!confirm('You have unsaved information,' +
                   'are you sure you want to leave this page?')) {
        transition.abort();
      }
    }
  }
}

Settings.willTransitionTo = (transition, params, query, callback) => {
  auth.isLoggedIn((isLoggedIn) => {
    transition.abort();
    callback();
  });
};
```

or completely in ES5:
```.js
var Settings = React.createClass({
  statics: {
    willTransitionTo: function (transition, params, query, callback) {
      auth.isLoggedIn(function (isLoggedIn) {
        transition.abort();
        callback();
      });
    },

    willTransitionFrom: function (transition, component) {
      if (component.formHasUnsavedData()) {
        if (!confirm('You have unsaved information,'+
                     'are you sure you want to leave this page?')) {
          transition.abort();
        }
      }
    }
  }
});
```

Ideally, it would nice if we could support both, like the excellent docs of [`react-dnd`](http://gaearon.github.io/react-dnd/). 
I'd be glad to help out.

**Comment by ryanflorence** [comment]
Our docs don't use anything that isn't a final part of EcmaScript 2015 (except JSX, of course), which includes arrow functions and destructuring. Browser support is irrelevant now that babel is the official JSX transformer, which is pretty much a dependency for React.

Enjoy ES 2015 :D
