### ISSUE TITLE
Documentation missing import for DefaultRouter

### ISSUE THREAD

**Issue by Narven** [rackt/react-router#1580]
in [http://rackt.github.io/react-router/#DefaultRoute](http://rackt.github.io/react-router/#DefaultRoute)

To use DefaultRoute its missing `var DefaultRoute = Router.DefaultRoute;` in documentation

**Comment by knowbody** [comment]
the imports are skipped in the examples, but I'll make sure that in the new docs we make it clear and/or we just add imports
