### ISSUE TITLE
Allow override of arrayFormat: 'brackets' in PathUtils#withQuery

### ISSUE THREAD

**Issue by tmoitie** [rackt/react-router#1585]
I am trying to run a transitionTo with a query object of shape `{tags: [{name: 'Red', id: 1}, {name: 'Blue', id: 2}]}`.

QS is creating a query string `tags[][name]=Red&tags[][id]=1&tags[][name]=Blue&tags[][id]=2` which when I run `getCurrentQuery()` comes out as `{tags: [{ name: ['Red', 'Blue'], id: [1, 2] }] }`.

If we could pass the default arrayFormat argument to `qs.stringify` this would enable me to return the same object that I passed in.

**Comment by tmoitie** [comment]
Ah this might be a bug with qs.parse.

**Comment by tmoitie** [comment]
Also a note to anyone who comes across this, to workaround I converted the array to an object using lodash shortly before passing through transitionTo, and it came out as an array on the other side:

```let dataObject = _.indexBy(data, (item, key) => { return key; });```

**Comment by iam4x** [comment]
Went through this as well... bump!

**Comment by knowbody** [comment]
closing, I think @nlf explained it well in [hapijs/qs#103](https://github.com/hapijs/qs/issues/103#issuecomment-123399156)

**Comment by tmoitie** [comment]
Hi @knowbody. Their explanation means that react-router now has to live with this ambiguity, with no means of overriding it. I am currently having to using a fork of react-router that sets `arrayFormat` explicitly to the default behaviour.

**Comment by knowbody** [comment]
ok, sorry I reopen it then. any idea how to solve it. care to submit the PR?

**Comment by tmoitie** [comment]
In #1092 it's mentioned that there is an undocumented override to the query/stringify parsing in 1.0.0. Would that be portable to 0.13.x or is development on that branch now ended?

**Comment by knowbody** [comment]
we are pushing as much as we can to release 1.0 soon so those things will be available, so my main focus is on 1.0 release

**Comment by ryanflorence** [comment]
We wont' be backporting anything, but this is supported in 1.0

 https://github.com/rackt/react-router/blob/master/docs/Router.md#stringifyqueryqueryobject

**Comment by kblcuk** [comment]
For those bumped into this issue -- current docs would be [somewhere here](https://github.com/rackt/react-router/blob/master/docs/API.md#stringifyqueryqueryobject).
