### ISSUE TITLE
willTransition events not firing on parent when leaving/entering child route.

### ISSUE THREAD

**Issue by constellates** [rackt/react-router#1588]
I have an application with nested routes.

	<Route name="app" path="/" handler={Index}>
		<Route name="signIn" path="sign-in" handler={Signin}/>
		<Route name="dashboard" path="dashboard"  handler={Dashboard} >
			<Route name="notifications" path="notifications" handler={Notifications}/>
			<Route name="profile" path="profile" handler={Profile}/>
		</Route>
		<Route name="home"   path="home"    handler={Home}/>
	</Route>

I would like to use the willTransitionFrom hook on my parent (dashboard) route in order to prevent users from leaving it at certain times. This hook is not firing if I place it on the Dashboard component and transition from one of it's children to a different parent level component (for example Notifications --> Home)

I can put the hook on each child route but would like to avoid repeating this on each child route. Is it possible to do this?

**Comment by ryanflorence** [comment]
ah that's a bug, we're focused on the master branch code for our 1.0 release, so I don't think we'll be fixing this on 0.13, if somebody else does though we can merge it and cut a release since that's pretty basic stuff.

a failing test case would help somebody implement it.
