### ISSUE TITLE
Worst case 3 rerenders for transition?

### ISSUE THREAD

**Issue by pstoica** [rackt/react-router#1589]
I was trying to track down why the base handler was getting so many re-renders and I noticed these lines were causing them:

![screen shot 2015-07-21 at 5 53 04 pm](https://cloud.githubusercontent.com/assets/1060689/8815118/b995a31e-2fe2-11e5-8ea0-87b6876cf51c.png)

It doesn't happen on the initial render.. maybe just from transitioning?

Is this expected? I'm particularly surprised about the last two not being batched, but it might be from the onUpdate callback.

**Comment by ryanflorence** [comment]
Matching routes can be async, so we let your app know the router is transitioning.

Also, quit worrying about render being called :)
