### ISSUE TITLE
Update input box from url route

### ISSUE THREAD

**Issue by kevhou** [rackt/react-router#1591]
I've been having this problem for days. How do i update my input search box whenever my route :parameter changes. One way i found is to set value={this.props.params.parameter} however this does not allow you to edit the input box. 

Pleasseeeee helllpp!!!

**Comment by bmathews** [comment]
Read the react forms documentation on how to handle binding input values:

https://facebook.github.io/react/docs/forms.html

**Comment by strivemag** [comment]
@kevhou hey, Did you find solution ?
