### ISSUE TITLE
Error: Invariant Violation: You cannot modify a static location

### ISSUE THREAD

**Issue by maximilianschmitt** [rackt/react-router#1593]
Hi, I'm trying to make a redirect outside of a willTransition hook. If I call `router.transitionTo`, I get:

```
Error: Invariant Violation: You cannot modify a static location
```

Here is how I constructed my router (on the server):

```javascript
  const router = Router.create({
    routes,
    location: req.path,
    onAbort: reason => console.log('abort', reason)
  });
```

`reason => console.log('abort', reason)` never gets called. I suspect the problem is that `req.path` is a *static location*? What is the proper way to make a redirect (on the server) outside of a `willTransition` hook? Thank you!

**Comment by maximilianschmitt** [comment]
I found a workaround that seems to work for me, see: https://gist.github.com/maximilianschmitt/3a14dffd6645dd4529f6

It's not the cleanest piece of code so I welcome any suggestions on how to improve it.

**Comment by ryanflorence** [comment]
we're still baking the 1.0 server side rendering story but you will be able to transition and get a redirectInfo result, I'm glad you found a workaround for 0.13, sorry about that :(
