### ISSUE TITLE
canGoBack method

### ISSUE THREAD

**Issue by clementdubois** [rackt/react-router#1594]
I want to create two different components based on the possibility to goBack or not but there is no way to know if a goBack is possible without having to calling it.

Is there a way to do this ?

Thank you

**Comment by nicolashery** [comment]
I've had the same use-case. I "solved" it by using the `History` object. It's undocumented though, and I don't know what it will become in `1.0` (I'm using `0.13.3`).

My "back" link looks something like this now:

```javascript
import {History} from 'react-router';

// ...
renderBackLink() {
  var canGoBack = (History.length > 1);
  var handleClick = (e) => {
    e.preventDefault();
    if (canGoBack) {
      this.goBack();
    } else {
      this.transitionTo('dashboard');
    }
  };
  var text = canGoBack ? 'Back' : 'To dashboard';

  return (
    <a href="" onClick={handleClick}>{text}</a>
  );
}
```

**Comment by clementdubois** [comment]
Thank you @nicolashery,
 that's the solution I use for now but it bother me because I can't mock the History.length in test as it is not a function.

**Comment by nicolashery** [comment]
Are you using CommonJS? If so, you could try something like [proxyquire](https://github.com/thlorenz/proxyquire) for mocking?

But anyway, I still worry about using something that's not part of the public API of `react-router`...

**Comment by nicolashery** [comment]
After upgrading to `1.0-beta3`, I'm now using `canGoBack = (window.history.length > 1)` as a check.

Still a hack :( Maybe we need a `getLength()` method to the `History` interface. Or a `false` returned from `goBack()` as mentioned in https://github.com/rackt/react-router/issues/1551.

I don't see anything mentioned about this in @mjackson's new https://github.com/rackt/history implementation though...

**Comment by knowbody** [comment]
as we use [History](https://github.com/rackt/history), maybe it will be worth to open this issue there? @nicolashery

**Comment by ryanflorence** [comment]
We haven't yet been able to nail down a solid `canGo` method, here's some history on the topic:

https://github.com/rackt/react-router/pull/1376
https://github.com/rackt/react-router/pull/843

Maybe one day ...

**Comment by fernandopasik** [comment]
Is there any way now to achieve this?
