### ISSUE TITLE
Uncaught TypeError: Cannot read property 'makeHref' of undefined

### ISSUE THREAD

**Issue by MinThaMie** [rackt/react-router#1595]
I've checked my code multiple times and I can't find the reason for this Error.

**Comment by KaneCohen** [comment]
Same here.

In 1.0.0-beta3 `this.context.router` has `undefined` at least in the Link component during render().

Still trying to figure out what's happening in the code, so can't provide any additional details.

**Comment by KaneCohen** [comment]
@MinThaMie hi, since you've closed the issue - did you figure out what lead to this error message?

Thanks.

**Comment by MinThaMie** [comment]
I think the problem was that there were two routers working in the same component. Now I'm using one central router.

**Comment by KaneCohen** [comment]
OK, thank you for the pointer.
