### ISSUE TITLE
Pass state params to childrens routes as in the 0.13 version in Route Handler

### ISSUE THREAD

**Issue by LucaColonnello** [rackt/react-router#1596]
I have one question about version 1.0.0.
In the previous version we could pass state parameters to Handler in router.run,
and then pass to childrens routes with RouteHandler.

````
// router run
router.run( function( Handler, state ) {
	React.render( (
	    <Handler {...state} />
	), document.body );
} );
````

````
// component
return
<div>
   <RouteHandler {...this.props} />
</div>;
````

How can we do this with new version that use this.props.children to print childrens routes?

Thank in advice

**Comment by jackmoore** [comment]
I'd like to know this as well.  Is there an alternative to this.props.children that enables passing of props?

**Comment by jackmoore** [comment]
Found one possible solution in #1531

```
React.cloneElement(this.props.children, this.props);
```

**Comment by LucaColonnello** [comment]
Many thanks!!!

Il mercoledì 29 luglio 2015, Jack Moore <notifications@github.com> ha
scritto:

> Found one possible solution in #1531
> <https://github.com/rackt/react-router/issues/1531>
>
> React.cloneElement(this.props.children, this.props);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackt/react-router/issues/1596#issuecomment-125784081>
> .
>


-- 
Luca Colonnello
+39 345 8948718
luca.colonnello91@gmail.com

**Comment by knowbody** [comment]
closing this issue, let's discuss it in #1531 as they both related
