### ISSUE TITLE
Expose component functions on RouteHandler

### ISSUE THREAD

**Issue by arasmussen** [rackt/react-router#1597]
I don't think component functions are being exposed to parents when they're wrapped in a RouteHandler.

http://stackoverflow.com/questions/31570309/react-router-call-component-function-on-routehandler-ref

**Comment by arasmussen** [comment]
Looks like I can do `this.refs[REF].refs['__routeHandler__'].blah()` but that's using a private, unsupported API.

Would be great if:

```javascript
var wrapper = this.refs[REF];
var child = this.refs[REF].refs['__routeHandler__'];
wrapper.blah = child.blah.bind(child);
```

**Comment by gaearon** [comment]
Not saying that your use case is invalid but consider this discussion: https://github.com/jsstyles/react-jss/issues/15. Instance methods on React components are an anti-pattern and can always be avoided.

**Comment by arasmussen** [comment]
Hey @gaearon, thanks for your response!

I'm using component functions to tell various components throughout my tree to reload their data. It sounds like if I want to avoid it I'd pass the data in as props instead and fetch it in one place near the root component, which would mean rewriting all my data fetching code and I'm hoping to avoid doing that until Relay is open sourced.

In the meantime I'll probably use the __routeHandler__ hack but would still love this feature in RouteHandler. We used component functions occasionally at Facebook IIRC and I still feel that there are cases where using props instead is hackier. (Specifically in the case when you want a component to do something after an event triggers in its parent or another component).

**Comment by gaearon** [comment]
Fair enough. :-)

**Comment by gaearon** [comment]
`RouteHandler` is actually going away in RR 1.0 (including the latest beta you can try), so you'll just have `this.props.children` at your disposal and you can clone them with refs.

**Comment by arasmussen** [comment]
Oh good to know, that's a pretty good reason not to support this at all. I'll take a look.

Feel free to close this, thanks!
