### ISSUE TITLE
Pass custom props to parent components

### ISSUE THREAD

**Issue by dapetcu21** [rackt/react-router#1599]
Let's say I have
```jsx
<Router history={history}>
  <Route path='/' component={RootView}>
    <Route path='subview1' component={SubView1}/>
    <Route path='subview2' component={SubView2}/>
  </Route>
</Router>
```

In `RootView`, `this.props.children` will get to be either `<SubView1/>`, `<SubView2/>` or `undefined`, but I have no additional sense of context which of these would it be (apart from importing `SubView1`, `SubView2` and dumbly comparing them).

I propose something like
```jsx
<Route path='subview1' component={SubView1} parentProps={{ childrenKey: 'subview1' }}/>
```
That would give custom props like `this.props.childrenKey` to `RootView` in addition to giving it a `this.props.children`. It's in a sense similar to `components`, but for non-component values.

There might be stuff I don't fully understand about react-router, so correct me if there's actually a way of doing this.

**Comment by nivekmai** [comment]
Could you use [this](https://facebook.github.io/react/tips/expose-component-functions.html) to give the children a function that simply returns their name?

**Comment by taurose** [comment]
In your route components you get `this.props.route` and `this.props.branch` among other things. `route` is the corresponding route element including `.children` and any custom props; `branch` is an array of all active routes.

Implementing `parentProps` this way could be tricky but it should be feasible. You can easily do something like `globalProps` though: 
`branch.reduce((all, route) => ({...all, ...route.globalProps}), {});`

**Comment by dapetcu21** [comment]
Thanks. Didn't know about `this.props.route`. Access to the route could actually be enough for what I'm doing.
