### ISSUE TITLE
Router.run returns a Transition, what to do with it?

### ISSUE THREAD

**Issue by hmeerlo** [rackt/react-router#1600]
Hi,

this is my code to perform isomorphic routing:

```javascript
import Router from 'react-router';
import routes from './routes/routes';
import { Provider } from 'react-redux';

export default function universalRouter(location, history, store) {
  return new Promise((resolve, reject) => {
    Router.run(routes(store), location, (error, initialState, transition) => {
      if (error) {
        reject(error);
      } else {
        if(transition){
          //What to do here?
        }else{
          if (history) {  // only on client side
            initialState.history = history;
          }
          resolve(<Provider store={store} key="provider">
            {() => <Router {...initialState} children={routes}/>}
          </Provider>);
        }
      }
    });
  });
}
```

As you can see, I'm using the Router.run path and the callback can receive a transition object because the onEnter of one of the routes performs a redirect. I would have expected this redirect to be handled by react-router but instead I get the transition object. What should I do with it from this point on?

Regards,
Herman

**Comment by BerkeleyTrue** [comment]
Interesting! Can you try doing a 302 redirect on the server? I also have transition in a Universal App and was not sure what to do. I had totally overlooked transition object as a possible point to redirect.

**Comment by hmeerlo** [comment]
That's what I'm doing now, I call reject(transition) and the server code then does a res.redirect. That part works but now I'm wondering how to handle this on the client...

**Comment by BerkeleyTrue** [comment]
It seems like internally react-router calls [replaceWith](https://github.com/rackt/react-router/blob/master/modules/Router.js#L134) when that happens. Its very frustrating that the react-router team did not think people would want to use Router.run client side. I will have to update https://github.com/rackt/react-router/pull/1490 to account for the transition object.

**Comment by BerkeleyTrue** [comment]
If you handle redirects server-side, should you ever get a redirect using router.run client side?

**Comment by hmeerlo** [comment]
Yes I would get it client side as well because in the onEnter I verify whether the user is authenticated. So if the user tries to navigate to an authenticated page after the client app has been downloaded the router will still issue the redirect.

**Comment by BerkeleyTrue** [comment]
I see the dilemma.

**Comment by ryanflorence** [comment]
server rendering is still baking for 1.0, its going to look like this: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md
