### ISSUE TITLE
Request: a robust way to animate inactive components out of view but keep them mounted

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1603]
I was experimenting with a hack to do this, but I get the following error:
```
Warning: <Home /> is being rendered by both Router and App using the same key (null) in the same place. Currently, this means that they don't preserve state.
```
Not only that, it's remounting when I change routes.  Preserving state is exactly what I want to accomplish, because I have a `<GoogleMap>` in `<Home />` that I don't want to reload every time I switch back to it.

If there was merely a way to assign a `key` to the `component` of a `Route`, then this would be pretty easy to implement.  However, I'm not sure what to do besides my own routing.

Here is the hack I tried to use.  Can anyone think of any other workarounds?

```
  render() {
    var child = React.Children.only(this.props.children);
    return <div className="app">
      <NavBar />
      <div className="body">
        {child.type === Home ? <div>{child}</div> : <div><Home hidden={true}/>{child}</div>}
```

```
var routes = <Router history={history}>
  <Route component={App}>
    <Route path="/home" component={Home} key="home"/>
    <Route path="/alerts" component={Alerts}/>
    <Redirect from="/*" to="/home"/>
  </Route>
</Router>
```

**Comment by jedwards1211** [comment]
Actually I wasn't thinking, I can just always stick a key on the Home from the router using `cloneElement`.    That's working for me.  Creating a more systematic solution (e.g. something like ReactCSSTransitionGroup that doesn't remove any or some children) would require a bit more work...

**Comment by jedwards1211** [comment]
I figure enough users will want to animate transitions between routes -- is any kind of official way of performing transitions planned?

**Comment by taurose** [comment]
IIRC allowing transition animations is a priority of the project owners. Note sure about their exact plans though. Anyway, since you get `this.props.children`, you can do transitions by holding on to the old child whenever the route changes. I think it's what `CSSTransitionGroup` does under the hood as well.

I'm not sure why you want to hold on to `<Home />`. Imo you shouldn't do this just for the sake of preserving state (React is only your view layer after all). I'd rather manage that state outside of react then.

**Comment by jedwards1211** [comment]
Yes, I understand and I normally don't try to preserve state that way,
but React doesn't have control of the embedded Google Map, you see?  I
can store the viewed position outside the map but it still ends up
reloading all the imagery if it remounts, which I'd like to prevent by
keeping it mounted.  Yes, CSSTransitionGroup holds onto children under
the hood too, the only difference is I was talking about holding on to
<Home/> permanently in this case -- even after it's transitioned to
invisible state.

On Fri, Jul 24, 2015, at 04:13 PM, Alexander Gundermann wrote:
> IIRC allowing transition animations is a priority of the project
> owners. Note sure about their exact plans though. Anyway, since you
> get this.props.children, you can do transitions by holding on to the
> old child whenever the route changes. I think it's what
> CSSTransitionGroup does under the hood as well.


> I'm not sure why you want to hold on to <Home />. Imo you shouldn't do
> this just for the sake of preserving state (React is only your view
> layer after all). I'd rather manage that state outside of react then.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/rackt/react-router/issues/1603#issuecomment-124726074

**Comment by jedwards1211** [comment]
@taurose Do you have any idea how to hold onto old children in 0.13.3?  Since children are injected via `<RouteHandler/>` I'm not sure how to do it.

**Comment by ryanflorence** [comment]
this is one reason why we did `this.props.children` in 1.0, in 0.13.3 you can use the `RouteHandlerMixin` to make your own route handler that you can add animation hooks too.

**Comment by jedwards1211** [comment]
@ryanflorence okay, cool.  Thanks!
