### ISSUE TITLE
Query with '/' in the url

### ISSUE THREAD

**Issue by kevhou** [rackt/react-router#1604]
Say i have:

```html
<Route path="/q=:search" handler={SearchResult}>
```

How can i hit that route when i visit `www.example.com/q=test/test`? I want it to treat the '/' (slash) as part of the query.

**Comment by taurose** [comment]
You could try using a [splat](https://github.com/rackt/react-router/blob/v0.13.3/docs/guides/path-matching.md#splats).

**Comment by ryanflorence** [comment]
yep, `/` is a special character for the router, you'll need to use a splat.
