### ISSUE TITLE
Can not visit nested url directly with HistoryLocation

### ISSUE THREAD

**Issue by zhaoyao91** [rackt/react-router#1605]
Following your guide, I created two pages(components), home and about. With HashLocation, I can visit `http://localhost:8080/#/` and `http://localhost:8080/#/about` directly, but after I switch to HistoryLocation, I can't visit `http://localhost:8080/about` directly, only can I click a link to jump to this page.

Maybe I have missed something but, how to fix it? Thank you.

**Comment by zhaoyao91** [comment]
some related code:

      // declare our routes and their hierarchy
      var routes = (
          <Route path="/" handler={App}>
              <DefaultRoute handler={Home}/>
              <Route path="about" handler={About}/>
              <Route path="about/company" handler={Company}/>
              <Route path="inbox" handler={Inbox}/>
              <NotFoundRoute handler={NotFound}/>
          </Route>
      );

      Router.run(routes, Router.HistoryLocation, (Root) => {
          React.render(<Root/>, document.body);
      });

**Comment by ericf89** [comment]
Can you post your server code as well?  You probably need to adjust it so that `/about` on the server also renders the same page as `/`.  You're basically handling all the routing on the frontend, and the servers only job is to spit out the page that holds your single page app.

**Comment by zhaoyao91** [comment]
I don't have any server code actually... I use webpack-dev-server for development by this time

**Comment by jedwards1211** [comment]
Hopefully they'll have a note about some of these things in an upgrade guide.

Try this:
```
      <Route handler={App}>
          <Route path="/" handler={Home}/>
          <Route path="/about" handler={About}/>
          <Route path="/about/company" handler={Company}/>
          <Route path="/inbox" handler={Inbox}/>
          <Route path="/*" handler={NotFound}/>
      </Route>
```
I'm not sure if the not found `/*` will work, I wonder if it will be ambiguous with the `/` route.  If it doesn't work try getting rid of the `/*` route temporarily...and then maybe we could find a solution for not found

**Comment by jedwards1211** [comment]
whoops sorry, I thought this question was about the beta, deleting my previous comment

**Comment by syarul** [comment]
Your server need to support HTML5 PushState or you can use [this](https://github.com/scottcorgan/pushstate-server)

**Comment by zhaoyao91** [comment]
thanks @syarul
