### ISSUE TITLE
JWT Cookie, Flux, Authentification & SSR

### ISSUE THREAD

**Issue by LucMerceron** [rackt/react-router#1606]
### Hello react router team !

First of all, thank you all for the great work :)

My application background is a bit complex but I feel like my problem isn't. 
So I have a debut of application which consist of Sign Up / Log In and a Private component. 

```
// routes.js
function requireAuth(nextState, transition) {
  if (!LoginStore.isLoggedIn()) {
  	transition.to('/login', null, { nextPathname: nextState.location.pathname });
  }
}
<Route component={require('./components/App')} >
		<Route path="/" component={require('./components/Home')} />
		<Route path="/login" component={require('./components/LogIn')} />
		<Route path="/signup" component={require('./components/SignUp')} />
		<Route path="/private" component={require('./components/Private')} onEnter={requireAuth}/>
</Route>
```

Log In component retrieve from an API a JWT, store it in a LoginStore component (Flux design) and in a Cookie in order to have access to the Private component without re-login later on.
The whole is working correctly as when I'm logged, I have access to the Private component and I can access it when refreshing (thanks to the cookie). 

My problem comes from the fact that I am also rendering this solution of the server and when I try to access directly to /private (by directly I mean my first call on the application is /private),  I am redirected to /login and then I can access to /private. I would like to fall on /private at the first call.

```
// server.js
var location = new Location(req.path, req.query);
  Router.run(routes, location, (error, initialState, transition) => {
    console.log(initialState);
      if (transition.isCancelled) {
        return res.redirect(302, transition.redirectInfo.pathname);
      } else {
        var html = React.renderToString(<Router {...initialState}/>);
        res.send(renderFullPage(html));
      }
  });
```
My LoginStore should retrieve the cookie from the request and allow the access to the Private component but he doesn't success in doing it because the bundle.js isn't even retrieve before the redirection
```
GET http://localhost/private [HTTP/1.1 302 Moved Temporarily 30ms]
GET http://localhost/login [HTTP/1.1 200 OK 51ms]
GET http://localhost/bundle.js [HTTP/1.1 200 OK 30ms]
```

I feel like I should send req.headers.cookie in location in the server.js and retrieve it to feed my LoginStore.but I don't know much about how to do it. I would really appreciate help on this case ^^

Thanks you in advance.

**Comment by xpepermint** [comment]
+1 & [stackoverflow](http://stackoverflow.com/questions/31948159/react-router-jwt-cookie-flux-authentification-ssr/31953391#31953391), https://github.com/rackt/react-router/issues/1629

**Comment by ryanflorence** [comment]
we hope to have a great ssr example after the 1.0 release
