### ISSUE TITLE
Path Resolve error: no link named "..." under ...

### ISSUE THREAD

**Issue by davidhq** [rackt/react-router#1607]
I use RR `1.0.0-beta3` on this project: https://github.com/ralph-pichler/metastarter... everything works but when I go for example to 

`http://localhost:8080/ipfs/QmSKMSMoAr2Hj2QBwgAD2KC624sapnskhszypQrsvjPWTM/etherstarter/0x4221672d5684547100357b65ffa1c8a3ed115b801e8cb97df55307705cb2ca86` directly (or if I refresh the page), I get:

`Path Resolve error: no link named "etherstarter" under QmSKMSMoAr2Hj2QBwgAD2KC624sapnskhszypQrsvjPWTM`

How could that be that clicking around works but not when refreshing the page. Did I do something wrong? Cannot find anything about this error online..

PS: this is IPFS system serving static assets, probably doesn't matter...

thank you
david

**Comment by taurose** [comment]
Never seen that error; seems to be coming from [ifps](https://github.com/ipfs/go-ipfs/blob/8143d381c1d123bfef714463543dee3dd743d59a/path/resolver.go#L30) though. I wasn't able to run your project locally since contracts.json is missing and webpack dev server started complaining about distroot.

**Comment by davidhq** [comment]
Thank you for the comment, indeed it's IPFS related... we now use HashHistory
