### ISSUE TITLE
AsyncProps _loadAsyncProps without any loadProps() components never calls its callback

### ISSUE THREAD

**Issue by insin** [rackt/react-router#1609]
`_loadAsyncProps` never calls its callback if the current set of components being rendered doesn't contain any with a static `loadProps()` property. 

There's a `.length` check in `componentWillMount` which ultimately skips calling it, but there are other ways to end up calling it and get into this situation (e.g. using `AsyncProps.hydrate()` when performing an initial render on the server).

**Comment by jonathandelgado** [comment]
+1

**Comment by ryanflorence** [comment]
its just experimental, sorry I have to just close issues on AsyncProps until we actually work on it (after rr 1.0)
