### ISSUE TITLE
willTransitionFrom() called infinitely when transition.abort() called

### ISSUE THREAD

**Issue by mindjuice** [rackt/react-router#1613]
I have a pretty standard ``willTransitionFrom()`` in one of my components as below:

    statics: {
      willTransitionFrom: function(transition, component) {
        if (component.state.dirty) {
          if (!window.confirm('You have unsaved changes.  If you continue, you will lose your changes.')) {
            transition.abort();
          }
        }
      }
    },

I also have a Cancel button that calls ``this.goBack()``.  Clicking the button causes my ``willTransitionFrom()`` to be called as expected.  If I click the Cancel button in the system dialog though to stay on the page, instead of just leaving me on the page, ``willTransitionFrom()`` gets called again and shows the dialog again.  Clicking Cancel always brings the dialog back up in an infinite loop.

Clicking OK allows the transition to continue as expected, but makes the dialog rather pointless.

Tracing down, I see that react-router ends up calling ``window.history.back()``, which triggers ``onPopState`` again, which ends up calling my ``willTransitionFrom()`` again.

Is this a bug or am I missing something in my code?

**Comment by mindjuice** [comment]
This is with react-router version 0.13.3.

**Comment by mindjuice** [comment]
So this was not actually an infinite loop, but it did end up going all the way back through my history before it stopped.

The problem is that in ``willTransitionFrom()``, it doesn't make sense to "go back" when you cancel the operation.

The right thing for the router to do is nothing at all.  The undocumented ``transition.cancel()`` causes the correct behavior though, so I've gotten around this bug for now.

The function names ``cancel()`` and ``abort()`` are very similar in meaning.  It would be much better to standardize on ``abort()`` and have it know whether it is being aborted from a ``willTransitionFrom()`` or elsewhere, so the correct action could be taken instead of requiring the developer to choose between two confusingly similar names.

**Comment by mindjuice** [comment]
OK, so I was wrong.  Calling ``cancel()`` doesn't quite work right either.  It seems that the route has already been set back to the previous path by the time my ``willTransitionFrom()`` hook is called, so "doing nothing" results in my component still being in edit mode, but the URL being the previous one, which was for the view mode.  Continuing the investigation...

**Comment by mindjuice** [comment]
Unless I've missed something, it looks like calling ``transition.redirect()`` inside ``willTransitionFrom()`` with the same route and params as my current route seems to leave me in the same state without unmounting the component.  Technically though, at this point it's not the "current route" anymore, since the history already popped it off, but my component still have enough information for me to reconstruct the route and params.

I can't imagine that this is the intended behavior though.  Can someone confirm that ``transition.abort()`` should work as I originally expected?  Does this issue perhaps disappear or become moot in V1.0?

**Comment by mindjuice** [comment]
Sigh...so ``redirect()`` has a similar side effect to ``cancel()``.

If my history was A, B, C, D and I hit Cancel, D gets popped off, and C becomes the current route.  Then my ``willTransitionFrom()`` hook is called, which calls ``redirect(D)``, so D replaces C.  The history becomes A, B, D instead of A, B, C, D.

Doing this over and over eventually will clear the history.

I think ``transition.abort()`` just needs to be fixed, but I'm not sure what to do at this point to fix it.  Cancel doesn't work.  Redirect doesn't work.  Doing nothing doesn't work.  Essentially it needs to push back whatever it popped (or avoid popping it in the first place), but that info doesn't seem to be available anymore.

Could the code be changed to call ``willTransitionFrom()`` before popping the current entry?  The having ``handleAbort()`` just do nothing would be correct.

**Comment by mlennon3** [comment]
+1 We're seeing this too.

**Comment by ryanflorence** [comment]
sorry for all the trouble. can you try 0.13.1?

**Comment by ryanflorence** [comment]
seems like there are a few bugs around transitions in 0.13.x, the codebase has moved pretty far from that release, but if folks want to fix bugs instead of upgrade to 1.0 when its released (very soon) then we can merge changes into the 0.13 branch and make some releases with bug fixes.

**Comment by mindjuice** [comment]
I'll give 0.13.1 a try this weekend to see if it's better.  I'm planning to upgrade to 1.0 though once it's out, so I don't need to have the fixes back ported.

Thanks.
