### ISSUE TITLE
Nested route issue?

### ISSUE THREAD

**Issue by kkotwal94** [rackt/react-router#1615]
I have my routes set up like this, however whenever I hit the singlereports (/reports/:id) route the rendering does not change but the url does, even though the handler is ReportView, however if i remove it as a nested route and just place it under that route or anywhere withing dashboard it works fine and the handler component is rendered. The handler Report holds all my data I pull asynchronously and then I draw a table in my front end and display it there. If a user wants to see that specific report it hits a View Link, which is just 
```
<Link to = "singlereports" params = {report._id}>View</Link>
```
```
<Route>
 <Route name ="dash" path="/dashboard" handler={App}>
    <Route name ="dashboard" path="/dashboard" handler={Dashboard}/>
    <Route name ="reports" path="/reports" handler={Report}>
    <Route name ="singlereports" path="/reports/:id" handler={ReportView}/>
    </Route>
    <Route name ="employees" path="/employees" handler={Employees}/>
      <Route name ="MyEmployees" path="/MEmployees" handler={MyEmployees}/>
      <Route name ="AllEmployees" path="/AEmployees" handler={AllEmployees}/>
      <Route name ="Profile" path="/profile" handler={Profile}/>
      <Route name ="reportstocomplete" path="/reportsc" handler={ReportsToComplete}/>
    <Route name ="addReport" path="/addReport" handler={AddReports}/>
    <Route name ="readme" path="/readme" handler={Readme}/>
    <Route name ="statistics" path="/statistics" handler={Stats}/>
    <Route name ="signup" path="/signup" handler={Signup} />
    <Route name ="login" path="/" handler={Login} />
    <Route name ="newreport" path="/newreport" handler={NewReport}/>
    <Route name ="templatereport" path="/templatereport" handler={TemplateReport}/>
 </Route>
</Route>
```

**Comment by gbezyuk** [comment]
Any path starting with an "/" symbol is considered absolute and does not inherit any path higher in the hierarchy. So, it's not a bug but a feature, RTFM =)
Plainly speaking, just remove starting slashes from your paths.

**Comment by kkotwal94** [comment]
So its just going to be dashboard for path, etc?
