### ISSUE TITLE
BrowserHistory.handlePopState is being fired when clicking on a <a href='#' onClick={...}/> tag

### ISSUE THREAD

**Issue by vjpr** [rackt/react-router#1616]
```
BrowserHistory.prototype.handlePopState = function handlePopState(event) {
  if (event.state === undefined) return; // Ignore extraneous popstate events in WebKit.
  ...
}
```

When this happens, `event.state` is `null`, and it is being checked for `undefined`.

Running Chrome `Version 46.0.2462.0 canary (64-bit)`

**Comment by ryanflorence** [comment]
Yeah, you need to preventDefault that click, you're getting a new history entry.

http://stackoverflow.com/questions/9948510/hashchange-firing-popstate

If I'm wrong, please make some noise :)
