### ISSUE TITLE
waiting for transitionTo to be done

### ISSUE THREAD

**Issue by tmcw** [rackt/react-router#1617]
I'm working on an application that has a method like:

```js
onDelete() {
    this.transitionTo('styles-layers', {
      styleId: this.getParams().styleId
    }, R.omit(['view'], this.props.query));
    actions.layer.destroy(this.getLayerIds().toJS());
  },
```

So when a user clicks a "delete" button, the component initiates a transition away from a detail view and then deletes the data that view is showing.

It appears that transitionTo [is async](https://github.com/rackt/react-router/issues/43) but doesn't have a method to return success, and methods to do so, like componentDidUpdate or Router.dispatch, are at a much higher level than this component and are called by much more than this one transitionTo call.

The problem I'm running into is that the deletion happens _before_ the transition and the detail view is re-rendered with no data _before_ it is removed from the page. I could patch around this by making sure the detail view no-ops if it doesn't have data, but that seems like a hack and makes this code a little harder to read, because there's an async call without much indication of that fact.

**Comment by ryanflorence** [comment]
interesting ... which version? 0.13?
