### ISSUE TITLE
Why does Router duplicate?

### ISSUE THREAD

**Issue by aspyatkin** [rackt/react-router#1618]
Hello, I was recently playing with React (v0.13.3) and React-router (v0.13.3), and I found a strange problem.
Here is the code:
1. HTML page
```html
<!DOCTYPE html!>
<html>
    ...
    <body>
        <div id="app">
        </div>
        <script src="/assets/js/bundle.js"></script>
    </body>
</html>
```
2. Bundle script (built with Gulp & Browserify & Babel)
```javascript
import React from 'react'
import Router, { Route, DefaultRoute, NotFoundRoute, Link, RouteHandler } from 'react-router'

class IndexPage extends React.Component {
    render() {
        return <h2>Index</h2>
    }
}

class ScoreboardPage extends React.Component {
    render() {
        return <h2>Scoreboard</h2>
    }
}

class App extends React.Component {
    render() {
        return (
            <div>
                <nav>
                    <Link to="main">Main</Link>
                    <Link to="scoreboard">Scoreboard</Link>
                </nav>
                <main>
                        <RouteHandler/>
                </main>
            </div>
        )
    }
}

var routes = (
    <Route handler={App}>
        <DefaultRoute name="main" handler={IndexPage}/>
        <Route name="scoreboard" path="scoreboard" handler={ScoreboardPage}/>
    </Route>
)

function render() {
    Router.run(routes, Router.HistoryLocation, (Root) => {
        React.render(<Root/>, document.getElementById('app'))
    })
}

render()
```

Routing works fine. But I get several warnings in console (Google Chrome on Mac OS X) while navigating from index page to `/scoreboard` using the `Link` in `nav`:
`Warning: ReactMount: Root element has been removed from its original container. New container:`
I have installed React devtools, and I see the same state:
```
<Top Level>
  <Router>...</Router>
  <Router>...</Router>
</Top Level>
```

I have found a related discussion on [StackOverflow](http://stackoverflow.com/questions/30620827/router-is-duplicating-when-clicking-a-link-element) along with #1255. I render `App` in a div inside body, I don't use jQuery.ready or `DOMContentLoaded`.

I can't figure out whether I'm doing something wrong. Is something special need to be done to make this work?

**Comment by aspyatkin** [comment]
Finally I have found that problem isn't on `react-router`'s side. I was trying to use `material-design-lite`  along with `React` and `react-router`. If you use extra scripts modifying the DOM, such as `material-design-life` in my case, you can run into the same problem.

**Comment by bnenu** [comment]
Hi,

I have the same problem. Any ideas on how to deal with that?

**Comment by aspyatkin** [comment]
I had no luck trying to get [material-design-lite](https://github.com/google/material-design-lite) work in my application and finally found [material-ui](https://github.com/callemall/material-ui), which has far better integration with [React](https://github.com/callemall/material-ui) and [ReactRouter](https://github.com/rackt/react-router).

**Comment by bnenu** [comment]
Thanks for reply. In the mean time I dug a little deeper and found some ideas. 
I managed to escape the warning about the 'ReactMount' by wrapping my top level div( the one with "mdl-layout mdl-js-layout" classes in another div element. It seems that mdl does some DOM manipulation that does not go well with React. I still have the 'Uncaught TypeError: Cannot read property 'insertBefore' of undefined' error for whatever reason though.

My main component is rendering now this:
     <div> {/* do not remove this DIV wrapper. MDL changes the DOM and React doesn't like it */}
        <div className ="app-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
          <Drawer />
          <main className="mdl-layout__content mdl-color--grey-100">
            <RouteHandler />
          </main>
        </div>
      </div>

**Comment by bnenu** [comment]
<div> {/* do not remove this DIV wrapper. MDL changes the DOM and React doesn't like it */}
        <div className ="app-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
          <Drawer />
          <main className="mdl-layout__content mdl-color--grey-100">
            <RouteHandler />
          </main>
        </div>
      </div>
