### ISSUE TITLE
1.0.0-beta3 complains of SSR when I'm running in the browser

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1622]
I'm getting this:

`Uncaught Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need`

But I'm running react-router 1.0.0-beta3 in the browser:

`React.render(routes, document.getElementById('root'));`

My code was previously working, but then I did a fresh clone/npm install of the project and everything blew up.

**Comment by jedwards1211** [comment]
I still got this even when I copied in my entire `node_modules` folder in from the old working project.  I don't understand what's causing such nondeterministic behavior.

**Comment by dozoisch** [comment]
How are you defining your routes?

1.0 has a different way of specifying the router.

**Comment by jedwards1211** [comment]
Yes, I know, I followed the examples in the `1.0.0-beta3` documentation, and like I said, it worked until I tried a fresh clone of the project.

Here's my `routes.jsx`:
```
import React from 'react';

import { Router, Route, Redirect } from 'react-router';
import { history } from 'react-router/lib/History';

import App from './App';
import Home from './routes/Home';
import Alerts from './routes/Alerts';

var routes = <Router history={history}>
  <Route component={App}>
    <Route path="/home" component={Home} key="home"/>
    <Route path="/alerts" component={Alerts}/>
    <Redirect from="/*" to="/home"/>
  </Route>
  {/*
  <Route path="/*" component={App}/>
  */}
</Router>;

export default routes;
```

And my `index.js`:

```
import React from 'react';
import routes from './routes';

window.webpackBundleLoaded = true;

var prevOnload = window.onload;
window.onload = function() {
  if (prevOnload) prevOnload();
  React.render(routes, document.getElementById('root'));
};
```

**Comment by eXon** [comment]
@jedwards1211 

You should replace:

`import { history } from 'react-router/lib/History';`

by

`import { history } from 'react-router/lib/BrowserHistory';`

**Comment by eXon** [comment]
@jedwards1211 On the server you should use this instead:

```javascript
import url from 'url';
import Location from 'react-router/lib/Location';
// ...

const parsedUrl = url.parse(req.url, true);
const history = new Location(parsedUrl.pathname, parsedUrl.query);
```

**Comment by ericclemmons** [comment]
You may also be getting this when a route _isn't_ matched, as `initialState` will be `null`.

For example, `GET /favicon.ico` could easily cause this.

**Comment by knowbody** [comment]
@jedwards1211 is this resolved?

**Comment by jedwards1211** [comment]
Sorry, I had been busy using version 0.13.3.  Sounds like @eXon's suggestions will help, I'll try them out.

**Comment by jedwards1211** [comment]
I'm sorry, I thought I would be able to pull up this old project setup and get it working easily, but it's more involved than I thought, and I have too many other things I'm trying to get done at the moment.

**Comment by jedwards1211** [comment]
Okay, nevermind, I decided it would be a good idea to set up some skeleton projects so I can check stuff like this in the future, and I got it working with `react-router/lib/HashHistory`.  Thank you guys!
