### ISSUE TITLE
How do I use async props with flux instances?

### ISSUE THREAD

**Issue by TimothyKrell** [rackt/react-router#1623]
I was testing out async props with Redux, but the fact that the `loadProps` function on the component is a static poses a problem. I want to fire off actions inside `loadProps`, but I don't have access to the redux instance.

Perhaps we need something like this:
```js
<Provider redux={redux}>
  <Router history={history}>
    <Route component={AsyncProps} renderInitialLoad={() => <Spinner />} expose={{redux}}>
       //...
    </Route>
  </Router>
</Provider>

// in component
statics: {
  loadProps: (params, cb, { redux }) {...}
}
```

Is there a simple way to do this that I'm missing?

**Comment by ryanflorence** [comment]
AsyncProps is just experimental, so your'e on your own until we get the time to really work on it, sorry :|
