### ISSUE TITLE
Nesting routes in 1.0.0-beta3

### ISSUE THREAD

**Issue by jackmoore** [rackt/react-router#1625]
In 0.13.3 I could do the following:

```
<Route path='/' handler={Root}>
	<Route path='about' handler={About}></Route>
	<Route handler={Home}></Route>
</Route>
```

Here, the `Root` component has the site header and footer, with `Route.RouteHandler` in between to render the child route component.  `Root` would use `Home` as a the `RouteHandler` if nothing else matched.  I can't figure out an equivalent in 1.0, without rewriting things so that `About` and `Home` include the header/footer themselves.  Any suggestions?

**Comment by jedwards1211** [comment]
The following should work.  However be advised that if you're at `/about`, then `State.isActive('/')` and `State.isActive('/about')` will both return `true`.
```
  <Route component={Root}>
    <Route path="/" component={Home}/>
    <Route path="/about" component={About}/>
  </Route>
```

**Comment by jackmoore** [comment]
@jedwards1211 Thanks, I see now where Ryan previously made the same suggestion (https://github.com/rackt/react-router/issues/1333#issuecomment-113165238z).  In my testing this doesn't render the root component (the App component in Ryan's example).  Using 1.0.0-beta3.

**Comment by jedwards1211** [comment]
That's too bad, this method had worked for me before...but maybe there are still issues to be worked out?

**Comment by jedwards1211** [comment]
So what do you see, if not the root component?  Does it render anything else?

**Comment by jackmoore** [comment]
@jedwards1211 Whoops, my mistake, the Root component does render.  Thank you.

**Comment by jackmoore** [comment]
@jedwards1211 I spent a lot of time trying to figure that out, I really appreciate you taking the time to help.

**Comment by jedwards1211** [comment]
Yeah, I had burned some time on that too, didn't want you have to suffer the same difficulty!
