### ISSUE TITLE
Should react be devDependancy?

### ISSUE THREAD

**Issue by KamilSzot** [rackt/react-router#1626]
I wanted to play a bit with react-router, namely enhace getComponents handling to actually pass the state there, as the docs say.

I created new project with react in node_modules.
Then I cloned your repo into node_module/react-router and ran npm install inside and built it with scripts/build.sh

What happened was, when I tried to webpack my project it used react from node_module/react-router/node_modules/react (not from node_module/react).

This caused error very hard to debug, which root cause was having two reacts in one app. Error message looked like this:
```
Uncaught TypeError: Cannot read property '_currentElement' of nullReactCompositeComponentMixin._updateRenderedComponent @ 
Um.js:11903ReactCompositeComponentMixin._performComponentUpdate @ 
Um.js:11885ReactCompositeComponentMixin.updateComponent @ 
Um.js:11801ReactPerf.measure.wrapper @ 
Um.js:3587ReactCompositeComponentMixin.performUpdateIfNecessary @ Um.js:11698
...
```

One way I could get rid of this bug was to wrap
```
  this.setState({ isTransitioning: true });

    runTransition(this.sta....
```
inside ```Router._updateState()``` in ```setTimeout(..., 0)```

The other way was to delete node_module/react-router/node_modules/react

I'm not sure if there's any way to prevent all this. I'm sure tests use this devDependancies react. Maybe just me trying to build react-router inside my app node_modules was stupid idea.

**Comment by knowbody** [comment]
I've just checked it and it works fine for me. Instead of copying the react-router repo to node_modules of your app and running build.sh I would recommend just specifying the path to your local react-router in the `package.json` of you app like this:

```json
"react-router": "file:PATH_TO_YOUR_LOCAL_VERSION"
```

[Here](https://docs.npmjs.com/files/package.json#local-paths) are more options on how to do it.

**Comment by loopmode** [comment]
Using npm link should work as well

**Comment by KamilSzot** [comment]
Thanks for the advice!
