### ISSUE TITLE
willTransitionTo does not run when navigating from child route to parent route

### ISSUE THREAD

**Issue by farism** [rackt/react-router#1630]
If I have three pages (`/about`, `/about/team`, and `/contact`) and I try to navigate from `/about` to `/contact`, or from `/about` to `/about/team`, the `willTransitionTo` hook fires. But if I'm on `/about/team`, and navigate to `/about`, the hook does not fire.

example repo

click the 'about' link, you will be redirected to `/about/team`. Then click the about link again.. it allows you to navigate there because the `willTransitionTo` hook does not fire.

https://github.com/farism/rr-willtransitionto

**Comment by hackhat** [comment]
+1

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/issues/1778#issuecomment-139098269
