### ISSUE TITLE
1.0.0-beta3 wrong componentWillReceiveProps calls 

### ISSUE THREAD

**Issue by lvasilev** [rackt/react-router#1636]
I use componentWillReceiveProps to retrieve data on conditions. 
But I get this
1. componentWillReceiveProps fires on first component render
2. componentWillReceiveProps fires in every components with routes on any route change events

**Comment by knowbody** [comment]
could you make your issue more precise? not sure if I understand what you mean

**Comment by lvasilev** [comment]
1. componentWillReceiveProps fires when a component first mounted
 2.when any route changed it causes componentWillReceiveProps fires on all components that handle  routes

**Comment by ryanflorence** [comment]
Please see

https://github.com/rackt/react-router/blob/master/docs/ComponentLifecycleWhenRouting.md

Now, the router may, at times, set state after the initial mount of components and cause a rerender, but your code shouldn't care if its checking that parameters/location changed before initializing a data fetch. You can't just fetch data every time you get new props, you need to be more specific about what changes to props should cause a new fetch.
