### ISSUE TITLE
Issue replicating "huge-apps" example on latest beta3

### ISSUE THREAD

**Issue by pbreah** [rackt/react-router#1642]
I have been trying to replicate the huge-apps example but it fails when require.ensure gets called with this error:

**TypeError: require.ensure is not a function**

I checked the code and "ensure" is undefined.

I have loaded the polyfills with: 
```
<script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>
```
But not making any difference.

I moved from using browserify to webpack and having different issues:

**Unexpected reserved word
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import { history } from 'react-router/lib/BrowserHistory';
| import { Router } from 'react-router';**

This is the code that fails using browserify:
```
module.exports = {
    path: 'my-path',

    getComponents (cb) {
        require.ensure([], (require) => {
            cb(null, require('./components/MyComponent'))
        })
    }
}
```
Would appreciate any tip to fix this problem.

Thanks

**Comment by pbreah** [comment]
For anyone having the same issue, this was the solution using webpack on laravel:

```
var elixir = require('laravel-elixir');
require("laravel-elixir-webpack");

elixir(function(mix) {
    mix.webpack('main.js', {
        module: {
            loaders: [
                { test: /\.js$/, loader: "babel-loader" }, // use this loader
            ]
        },
        outputDir: "public/js",
        output: {
            filename: "main.js",
            publicPath: '/js/'        // Don't forget this path, this is the base path to load files from the public folder
        },
        resolve: {
            extensions: ["", ".js"] // use this extension, with any other you have
        }
    });
});
```

**Comment by rstormsf** [comment]
Docs in beta3 link is broken: 
https://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Advanced Usage
https://rackt.github.io/examples/huge-apps
