### ISSUE TITLE
Route name (1.0.0-beta3)

### ISSUE THREAD

**Issue by maslianok** [rackt/react-router#1643]
Is there any ability to get route by name? 
I mean 
``this.makeHref(routeName, routeParams, routeQuery)`` or  ``this.isActive(routeName, routeParams, routeQuery)``

And, if you have removed this functionality in React Router 1.x, what is the best way to implement it? Can I take a plain list of routes somewhere?

**Comment by th0r** [comment]
@maslianok Join us here #1514 with `+1`)

**Comment by ryanflorence** [comment]
route names will not return, but hopefully we (or somebody) can make a lib on top to use them, I'll have an explanation of why in the release notes.
