### ISSUE TITLE
Missing call to super() in derived class constructors throws error in examples

### ISSUE THREAD

**Issue by ivarni** [rackt/react-router#1644]
Webpack throws errors when running the examples

> ERROR in ./examples/auth-flow/app.js
Module build failed: SyntaxError: /home/ivarni/workspace/react-router/examples/auth-flow/app.js: Line 7: 'this' is not allowed before super()

Adding a `super()` call in `App` and `Login` and takes care of the errors and the examples work fine. See https://github.com/ivarni/react-router/commit/e7472d028e3abd7d1bf5006c6f47f4761c75042e

**Comment by choonkending** [comment]
Same error running with examples. Fixed it the same way as @ivarni did!

**Comment by mjackson** [comment]
This is fixed in master.
