### ISSUE TITLE
Update karma to 0.13.2 or higher

### ISSUE THREAD

**Issue by ivarni** [rackt/react-router#1645]
Currently on master the tests fail in the browser due to [this](https://github.com/karma-runner/karma/issues/1497) issue.
(webpack preprocessor doesn't get loaded)

Updating karma to at least 0.13.2 makes the tests happy again.

**Comment by mjackson** [comment]
:+1:

**Comment by mjackson** [comment]
Done in e61958ac59fbfb388673ea92ac99931b1ae1bab0.
