### ISSUE TITLE
Restoring scroll position when data is loaded async

### ISSUE THREAD

**Issue by antonholmquist** [rackt/react-router#1646]
This is one basic thing I haven't been able to find a solution too.

Let's say we have these two pages:

A. list of items
B. item details

This is my use case: 

1. Page A is loaded, and the list of items is fetched on componentDidMount
2. The user scrolls down on the page, selects an item and is taken to page B
3. The user now clicks the browser back button to go back to page A
4. Page A is loaded (at first without any items, since it takes a short while to re-fetch the data). Due to this delay, the router is unable to restore the scroll position to where it was before and instead stays at the top. This can be really annoying for the user, especially if the list is long.

I have looked into `willTransitionTo` to pre-fetch the data, but I haven't been able to find a way that works. I also have found a few other issues addressing the same thing, but no working solution so far.

What is the current status on this? Is it a real issue being addressed, or am I just missing something?

Thanks!

**Comment by antonholmquist** [comment]
Instead of pre-fetching props before a component is mounted, maybe it would be even better to just have the ability to manually select when the actual scroll position is restored, like `this.restoreScrollPosition()`. It would then be called right the initial data is fetched.

**Comment by ryanflorence** [comment]
cache data so the page can restore scroll position
