### ISSUE TITLE
Static methods doesn't working together to ES2015 classes

### ISSUE THREAD

**Issue by chiefGui** [rackt/react-router#1649]
This **doesn't** work:

```js
import React, { Component } from 'react'
import Router from 'react-router'

export default class extends Component {
  static willTransitionTo() {
    console.log('hi');
  }

  static willTransitionFrom() {
    console.log('bye');
  }

  render() {
    return <div>hello!</div>
  }
}
```

But this do:

```js
import React, { Component } from 'react'
import Router from 'react-router'

export default React.createClass({
  statics: {
    willTransitionTo() {
      console.log('hi');
    },

    willTransitionFrom() {
      console.log('bye');
    }
  },

  render() {
    return <div>hello!</div>
  }
})
```

Just to clarify, what's happening is that `willTransitionTo` and `willTransitionFrom` are being triggered when written in es5 way; otherwise, they doesn't trigger. What is the syntax difference? Ideias?

**Comment by chiefGui** [comment]
Actually, this seems to be a problem of [alt](https://github.com/goatslacker/alt/)—I really thought it couldn't be related, but for my surprise it is our pitfall.

Check it out: https://github.com/goatslacker/alt/issues/432

**Comment by mjackson** [comment]
It appears the linked issue has been resolved.
