### ISSUE TITLE
1.0.0 Beta 3, Passing flux to routes with {this.props.children}

### ISSUE THREAD

**Issue by michaelryancaputo** [rackt/react-router#1654]
Not sure how to achieve this, I am a bit new with React. It seems using `<RouteHandler flux={flux}/>` has been deprecated in this upcoming version, however I can't seem to find a way to pass flux to my components using `{this.props.children}`.

**Comment by nlutterman** [comment]
@michaelryancaputo Hey Michael, you closed this without providing any further information.  Was your issue actually solved?  Did you find the information that you needed?

Was [this](https://github.com/rackt/react-router/issues/1691#issuecomment-129994235) possibly the solution?
