### ISSUE TITLE
Scroll Spy

### ISSUE THREAD

**Issue by timsuchanek** [rackt/react-router#1656]
If I want to create a Scroll Spy, that updates the URL when scrolling, how to accomplish that with react-router?

Didn't find anything for that use case.
Thanks!

**Comment by qimingweng** [comment]
@timsuchanek You could add an onScroll callback and update some kind of query parameter in the router with transitionTo, and then update your views accordingly. This seems like an odd use case though, could you elaborate?

**Comment by timsuchanek** [comment]
Hey, thanks @qimingweng for the answer. I now got it. I use a custom `onClick` Handler for the `Link`s and just scroll to that position. Now I just use a :id in the router and it works fine.
