### ISSUE TITLE
Equivalent of DefaultRoute functionality in 1.0.0-beta3

### ISSUE THREAD

**Issue by qimingweng** [rackt/react-router#1657]
I'm trying to get functionality similar to DefaultRoute, i.e., if my path matches exactly my parent, insert me as the child.

These configurations don't seem to work.

```
const routes = {
  path: '/main',
  component: Main,
  childRoutes: [
    {
      path: '*',
      component: Default
    }
  ]
};
```

I have also tried, `path: ''`, `path: '/'`, and no path at all.

**Comment by confiks** [comment]
I was also struck by the absence of DefaultRoute. It was apparently deleted in revision 776348b, along with a changelog line: `[removed] <DefaultRoute>, branch on this.props.children in render instead`.

What was the idea behind this change? DefaultRoute is often used when you have some container component that needs to display some default content, such as a dashboard or a summary. The full route definition then conveniently describes all possible container/children states that are chosen based on the route.

**Comment by cpsubrian** [comment]
IMO an empty path or `./` would be most expressive. Such that you could do:

```jsx
<Router history={history}>
  <Route path='/' component={App}>
    <Route path='' component={Home}/>
    <Route path='users' component={Users}>
      <Route path='' component={UsersList}/>
      <Route path=':id' component={User}>
        <Route path='' component={UserProfile}/>
        <Route path='friends' component={UserFriends}/>
        <Route path='settings' component={UserSettings/>}
      </Route>
    </Route>
    <Route path='*' component={NotFound}/>
  </Route>
</Router>
```

Currently, you could do the following (I think), but I don't like all the absolute paths and repetition required...

```jsx
<Router history={history}>
  <Route component={App}>
    <Route path='/' component={Home}/>
    <Route component={Users}>
      <Route path='/users' component={UsersList}/>
      <Route component={User}>
        <Route path='/users/:id' component={UserProfile}/>
        <Route path='/users/:id/friends' component={UserFriends}/>
        <Route path='/users/:id/settings' component={UserSettings/>}
      </Route>
    </Route>
    <Route path='*' component={NotFound}/>
  </Route>
</Router>
```

**Comment by cpsubrian** [comment]
Although, I'll admit that after staring at it for a minute, you can much more quickly pick out a particular route and figure out the component hierarchy .. so, pros and cons.

**Comment by qimingweng** [comment]
@cpsubrian can you point out which route is default one?

**Comment by qimingweng** [comment]
Oh, I think I get it but I just want to confirm. That's interesting, I forget 1.0 you can just arbitrarily stack components together...

**Comment by cpsubrian** [comment]
Ok, after further thinking about this (and thinking about how I'd convert some code I have) ... there is a major problem with my 2nd example above, and thats introspection.

With some component such as a `<Breadcrumb/>`, you really need the path split out between the hierarchy, like my first example. This allows you to build up the pieces of the breadcrumb by looking at the paths along the way and using a custom prop (or static prop) for the link 'label'. There really is no way to do that in my second example (that I can think of atm).

**Comment by cpsubrian** [comment]
@qimingweng In my 1st example the ones with empty strings for paths would be the 'default' routes. In the 2nd example there really are no default routes, just a hierarchy of wrapper components around absolutely defined routes.

**Comment by taion** [comment]
It's actually still there under a different name: https://github.com/rackt/react-router/blob/v1.0.0-beta3/examples/pinterest/app.js#L118

Not really elegantly usable from JSX though - you'd have to do something like:

```jsx
<Route
  path="/" component={Foo}
  indexRoute={{component: Bar}}
/>
```

**Comment by ryanflorence** [comment]
`<Route indexRoute={<Route/>}/>` right now, will probably bring `DefaultRoute` back to JSX config as `IndexRoute`

**Comment by taion** [comment]
Not quite, right? The `Route` doesn't get converted from JSX, so you need to specify `{component: Bar}` instead of `<Route component={Bar} />`, no?
