### ISSUE TITLE
Support relative redirects

### ISSUE THREAD

**Issue by qimingweng** [rackt/react-router#1658]
I have this setup in 1.0.0-beta3.

```
<Router history={history}>
  <Route path="app" component={App}>
    <Route path="main" component={Main}/>
    <Redirect from="blah" to="main"/>
  </Route>
</Router>
```

Going to `/app/blah` redirects to `/main` instead of `/app/main`.

**Comment by zoilorys** [comment]
Having similar issue, but with trasitionTo() - when i transition from <code>/super/parser</code> to <code>/login</code> it transitions well, but it creates odd <code>/super/login</code> URL, that doesn't actually exist in my routes

**Comment by ryanflorence** [comment]
#1675

**Comment by mjackson** [comment]
There's already [a TODO](https://github.com/rackt/react-router/blob/3c9cc45fe5f8b22e3a3e4f779636e0646d55f818/modules/Redirect.js#L29) about this...

**Comment by mjackson** [comment]
I'm removing the "bug" label because I don't believe we've ever supported this.

**Comment by ryanflorence** [comment]
it seemed like we supported this because you redirected from named routes, not paths.

**Comment by qimingweng** [comment]
@mjackson @ryanflorence in the 1.0.0-beta3 documentation, under the redirect examples, there's a section that reads:

```
<Route path="course/:courseId">
  <Route path="dashboard"/>
  {/* /course/123/home -> /course/123/dashboard */}
  <Redirect from="home" to="dashboard" />
</Route>
```

**Comment by mjackson** [comment]
Care to submit a PR that changes that, @qimingweng?

**Comment by qimingweng** [comment]
@mjackson I created a PR here #1773

**Comment by knowbody** [comment]
closing for now, the error message is added and docs are updated by #1773

**Comment by mjackson** [comment]
Let's follow up in #1905 with the actual feature implementation.

**Comment by taion** [comment]
Was resolved by https://github.com/rackt/react-router/pull/2030.
