### ISSUE TITLE
1.0.0-beta3 Update query string on current route

### ISSUE THREAD

**Issue by duro** [rackt/react-router#1659]
I am trying to update the query string on the current route I am on.

For example, I am on route `/test`

When the user clicks a button on that page, I want the route to be `/test?query=123`

I have tried this:

```
contextTypes: {
  router: React.PropTypes.object
},

changeQuery() {
  this.context.router.transitionTo('/test', null, {
    query: Math.floor((Math.random() * 10000) + 1)
  })
},
```

It seems to re-render the component, but the URL in the browser does not update.

Any guidance would be appreciated.

**Comment by agilgur5** [comment]
+1

After a bit of testing, I'm almost positive that in 1.0.0-beta3 transitionTo does not handle any of its arguments after the first one (neither queries nor state). That's a pretty important function to be lacking functionality even for a beta version...

**Comment by duro** [comment]
I'd love to find out if there is some kind of work around for this. We have
some critical functionality that relies on this.

**Comment by TimothyKrell** [comment]
I was trying the beta, but I think I'm going to have to roll back until this is fixed. This is a pretty import part of the workflow of my app.

**Comment by TimothyKrell** [comment]
@duro @agilgur5 I think the problem may be that the signature for the `transitionTo` method has changed. Check [here](https://rackt.github.io/react-router/tags/v1.0.0-beta3.html#-transitionto-pathname-query-state-). The query and state arguments are now flipped. Swapping the arguments is working for me. Perhaps this is your problem too?

@duro Your example should look like this now, I think:
```js
contextTypes: {
  router: React.PropTypes.object
},

changeQuery() {
  this.context.router.transitionTo('/test', { // <-- no `null` here anymore
    query: Math.floor((Math.random() * 10000) + 1)
  })
},
```

**Comment by duro** [comment]
Yes this seems to be working for us.

**Comment by agilgur5** [comment]
Hmm... I thought that was the problem initially, but it didn't seem to work on my end :/ I also have a static query param and tried using `this.context.router.transitionTo('/path?query=param')`, yet that didn't seem to update the URL for me... Guess I should try again? Can you guys let me know if the static version in URL (vs object notation) works for you if you have the time?

**Comment by max-mykhailenko** [comment]
Guys, how I can access to method `transitionTo` without context?
Ex.
```
import Router from 'react-router';
Router.transitionTo(arguments)
```

**Comment by ryanflorence** [comment]
yeah we jumped the gun on the beta tag, don't use it until we ship it if you don't want to be scratching your head a lot :)

(or just drop a debugger in and step into the code to figure it out)

**Comment by ryanflorence** [comment]
> Guys, how I can access to method transitionTo without context?

Navigation mixin

> yeah but ES6 classes

Dont' use them

> but I heard they are were cool

Then use context

> but I heard that was bad

Sorry.

:P

**Comment by max-mykhailenko** [comment]
@ryanflorence mixins in the store?
