### ISSUE TITLE
Warning: Failed Context Types: Required context `router` was not specified in `Link`.

### ISSUE THREAD

**Issue by crowdwave** [rackt/react-router#1660]
Hello

I am wondering what this means?

Warning: Failed Context Types: Required context `router` was not specified in `Link`.
react.js:19762 Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if ("production" !== process.env.NODE_ENV) {
        ("production" !== process.env.NODE_ENV ? warning(
          this instanceof Constructor,
          'Something is calling a React component directly. Use a factory or ' +
          'JSX instead. See: https://fb.me/react-legacyfactory'
        ) : null);
      }

      // Wire up auto-binding
      if (this.__reactAutoBindMap) {
        bindAutoBindMethods(this);
      }

      this.props = props;
      this.context = context;
      this.state = null;

      // ReactClasses doesn't have constructors. Instead, they use the
      // getInitialState and componentWillMount methods for initialization.

      var initialState = this.getInitialState ? this.getInitialState() : null;
      if ("production" !== process.env.NODE_ENV) {
        // We allow auto-mocks to proceed as if they're returning null.
        if (typeof initialState === 'undefined' &&
            this.getInitialState._isMockFunction) {
          // This is probably bad practice. Consider warning here and
          // deprecating this convenience.
          initialState = null;
        }
      }
      ("production" !== process.env.NODE_ENV ? invariant(
        typeof initialState === 'object' && !Array.isArray(initialState),
        '%s.getInitialState(): must return an object or null',
        Constructor.displayName || 'ReactCompositeComponent'
      ) : invariant(typeof initialState === 'object' && !Array.isArray(initialState)));

      this.state = initialState;
    }`) for key (router) while mounting Link (see: http://fb.me/react-context-by-parent)
dev.js:15319 Uncaught TypeError: Cannot read property 'makeHref' of undefined

**Comment by canvaskisa** [comment]
Ran into this issue too

**Comment by codeviking** [comment]
We're also encountering this issue when using a `<Link>` element in a nested `<RouteHandler>` with version `0.13.2`.  Any ideas?

**Comment by wuct** [comment]
Also ran into this issue with 0.13.3. Currently use `<a>` to bypass it.

**Comment by johnomalley** [comment]
I was only seeing this in test cases - and [this article](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/testing.md) resolved the issue.

**Comment by thomasboyt** [comment]
Ran into this issue in 0.13.3 doing server-side rendering, unsure what the fix is.

**Comment by ryanflorence** [comment]
If you render a Link outside the context of a Router then you'll get this error, but not on master anymore, we just ignore if there is a router on context.

**Comment by Download** [comment]
Having this same problem... Is anybody able to explain what we should do to fix it? @ryanflorence can you elaborate maybe?

**Comment by Download** [comment]
For me, the problem was that I was missing this piece of code:
```javascript
Router.run(routes, function (Handler) {  
	React.render(<Handler/>, document.body);
});
```
I just had the `React.render(<App/>, document.body);` line.

**Comment by SOSANA** [comment]
anyone using  "react-router": "1.0.0-beta2" with react-engine? curious as well what others are using

**Comment by mcmunder** [comment]
I am aware this issue is quite old, but...

I ran into the same issue with `react-router-dom` and `create-react-app`. Problem was I was using this standard create-react-app test: 

```js
it('renders without crashing', () => {
  const div = document.createElement('div')
  ReactDOM.render(<Home />, div)
})
```

where `Home` is a component containing a `Link` and is normally nested in a `Router` component. The test above takes`Home` out of the router context...

All I had to do to make the test pass was wrapping `Home` in a `MemoryRouter`:

```js
it('renders without crashing', () => {
  const div = document.createElement('div')
  ReactDOM.render(
    <MemoryRouter>
      <Home />
    </MemoryRouter>,
    div
  )
})
```

Hope this makes sense and helps!

**Comment by ryanflorence** [comment]
Thanks, also there's a guide now too: https://reacttraining.com/react-router/web/guides/testing

**Comment by giedrius-timinskis** [comment]
What about cases where I need to access the component directly, bypassing the Router wrapper?

For instance, if I need to access the state, I'd have to find my component in the wrapping Router, and Enzyme only allows getting state of the root:

`
const wrapper = mount(<StaticRouter context={{}}><Component /></StaticRouter>);
wrapper.find(Component).state()); // ReactWrapper::state() can only be called on the root
`
