### ISSUE TITLE
sessionStorage.setItem fails in Safari private window

### ISSUE THREAD

**Issue by maisano** [rackt/react-router#1661]
Using `HashHistory` with a `queryKey` while in a Safari private window will fail because of `sessionStorage` quota being set to 0.

It's also a bit strange that a queryKey is required for HashHistory–do you have any thoughts regarding the removal of the warnings?

**Comment by mjackson** [comment]
@maisano You can use `queryKey: false` to disable state persistence, but it isn't recommended.

**Comment by pstoica** [comment]
Hey, it's still worth adding a try/catch if queryKey has a default value. react-router will not work in private Safari out of the box.

**Comment by mjackson** [comment]
@pstoica Can you make a PR?

**Comment by pstoica** [comment]
Will do.
