### ISSUE TITLE
Question - have nested routes ignore browser back/forward buttons?

### ISSUE THREAD

**Issue by mwilliams-change** [rackt/react-router#1662]
Given an app with some nested routes like so:

```
/parent/child1
/parent/child2
/parent/child3
```

Where the child components correspond to tabs in the parent component UI.

Clicking on the tabs has the nice effect of leaving the parent component alone while rendering the child component in `{this.props.children}`.

The drawback is that clicking the browser back button will remember the order I clicked the tabs and traverse backwards through that history.

Is there a straightforward way to make the browser history only apply to navigation at the level of `parent`? i.e. have it ignore tab clicks?

(I'm using 1.0.0-beta3)

**Comment by ryanflorence** [comment]
Add a click handler to the links and call `replaceWith`
