### ISSUE TITLE
1.0.0-beta3 Handle transition in Router.run (server side)

### ISSUE THREAD

**Issue by themouette** [rackt/react-router#1664]
I have  a universal application I just upgraded to **react@0.14.0-beta1** and **react-router@1.0.0-beta3**

When I hit a react-router transition server side, I want to redirect at HTTP level but I cannot convert transition route name into a full path.

Server side, I use `Router.run` to get initial state and load data required from routes:

``` javascript
const location = new Location(req.path, req.query);
Router.run(routes, location, (error, initialState, transition) => {
  // error management
  if (error) return next(error);
  if (transition.isCancelled && transition.abortReason) return next(transition.abortReason);
  // handle redirection
  if (transition.isCancelled && transition.redirectInfo) {
    const { to, query, state } = transition.redirectInfo;
    // How can I transform route name into a url?
    // Because obviously I cannot access router's instance
    const url = router.makePath(to, query);
    return res.redirect(url);
  }

  // Do some store initialization
  // then...
  return res.send(ReactDOMServer.renderToString(
    <Router {...initialState} onError={next} />
  ));
});
```

I used to create a router instance with **react-router@0.13.3** and use the `onAbort` event as advised in #1290 or [here](https://github.com/dazld/react-router-fetch-data-demo/blob/master/server/index.js#L40-L44) but `Router.createElement` now throws an error.

What did I miss?

**Comment by ryanflorence** [comment]
might be a docs issue, might be an oversight in the rewrite

**Comment by ryanflorence** [comment]
still baking SSR, this is what it will look like, and redirects should be really easy https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

**Comment by themouette** [comment]
Thanks a lot !

**Comment by devrchancay** [comment]
This is the correct link :runner: 

https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md
