### ISSUE TITLE
Accessing Root(RouterHandler) static properties

### ISSUE THREAD

**Issue by poluyanov** [rackt/react-router#1670]
Hi!
Is any way to access static methods of my React.Component classes within ReactRouter.run()?

I need something like this:
ReactRouter.run(routes, req.path, function (Root) { Root.myStaticMethod() })

but Root is instance of react-router, not my component

Thanks a lot

**Comment by taurose** [comment]
You can get them with the second argument (`state`):

```js
Router.run(routes, path, function(Root, state) {
  // just the root
  state.routes[0].handler.myStaticMethod(); 

  // all 
  state.routes.forEach(function(route) {
    route.handler.myStaticMethod();
  });
});
```

**Comment by poluyanov** [comment]
Thanks
