### ISSUE TITLE
Animation problem when coding for ES6

### ISSUE THREAD

**Issue by johnnyreilly** [rackt/react-router#1673]
Hullo folks,

Thanks for your mighty fine router - it's been a joy to use!  I've just happened upon a slight problem when I've tried to use the animation features though. 

I'm using 0.13.3 versions of react and react-router and I'm writing using ES6 and compiling to ES5 using Babel.  I tried to take the [animation example](https://github.com/rackt/react-router/tree/0.13.x/examples/animations) and port that across to ES6.  

I lifted the css `example` related classes wholesale and amended my own `App.js` as follows:

```js
import React from 'react';
import TransitionGroup from 'react/lib/ReactCSSTransitionGroup';
import { RouteHandler } from 'react-router';
import ConnectionStateStore from '../stores/ConnectionStateStore';
import NavigationBar from './navigation/NavigationBar';
import Login from './login/Login';

class App extends React.Component {
  constructor(props) {
    super(props);
    this._onChange = this._onChange.bind(this);
    this.state = this._getStateFromStores();
  }

  componentWillMount() {
    ConnectionStateStore.addChangeListener(this._onChange);
  }

  componentWillUnmount() {
    ConnectionStateStore.removeChangeListener(this._onChange);
  }

  render() {
    const { isLoggedIn } = this.state;
    return (
      <div>
        <NavigationBar isLoggedIn={ isLoggedIn } />
        <TransitionGroup component="div" transitionName="example">
          { this._renderContent(isLoggedIn) }
        </TransitionGroup>
      </div>
    );
  }

  _renderContent(isLoggedIn) {
    if (isLoggedIn) {
      return <RouteHandler />;
    }
    return <Login />;
  }

  _onChange() {
    this.setState(this._getStateFromStores());
  }

  _getStateFromStores() {
    return ConnectionStateStore.getConnectionState();
  }
}

App.contextTypes = {
  router: React.PropTypes.func.isRequired
};

export default App;
```

However, I have no animation to show for my efforts and only this bitter, bitter message in the Chrome Dev Tools:

> Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

Is there some special incantation required to use animation with React Router when coding ES6?  This feels like it ought to work... but it doesn't. Any help greatly appreciated.

**Comment by taurose** [comment]
Are you bundling multiple versions of React perhaps? As in https://github.com/rackt/react-router/issues/1003

**Comment by johnnyreilly** [comment]
Perhaps - I use Browserify. What's the advice on how to only use 1 version of React when using that?  Perhaps I should only have 1 import:

`
import TransitionGroup from 'react/lib/ReactCSSTransitionGroup';`

And lose this one?

`import React from 'react';`

Is there a working Browserify example out there to see?

**Comment by mjackson** [comment]
Not sure about Browserify, but I've never had this problem when using webpack. There's [some discussion](https://github.com/facebook/react/issues/2402) about it.

**Comment by johnnyreilly** [comment]
Thanks for the link - I'll have a read.  Very frustrating.

**Comment by johnnyreilly** [comment]
For others also struggling this codepen is invaluable: http://codepen.io/luisrudge/pen/QbEeOR

**Comment by jason-zhai** [comment]
Hi @johnnyreilly ,
did you ever find a solution for es6 import pulling react in twice from addons?
<img width="595" alt="screenshot_8_13_16__11_35_am" src="https://cloud.githubusercontent.com/assets/13140380/17644910/2ffab6c2-614a-11e6-928a-72224a512476.png">

struggling with this.. would much appriciate the help!

**Comment by johnnyreilly** [comment]
I'd forgotten all about this! I'm not having a problem now but my setup is different. I moved to WebPack and I abandoned animations (at the time there were issues with React animations). I've got no issues with my setup now. Maybe try doing the same?

**Comment by jason-zhai** [comment]
got it.
Thanks~
