### ISSUE TITLE
Bug with redirect from root path "/"

### ISSUE THREAD

**Issue by nicolashery** [rackt/react-router#1675]
Using `react-router@1.0.0-beta3`.

```javascript
// redirect doesn't work
const routes = (
  <Router history={history}>
    <Route component={Layout} path="/">
      <Route component={Dashboard} path="dashboard"/>
      <Route component={Profile} path="profile"/>
    </Route>
    <Redirect from="/" to="dashboard"/>
  </Router>
); 

// redirect works
const routes = (
  <Router history={history}>
    <Route component={Layout}> // removed "path" prop
      <Route component={Dashboard} path="dashboard"/>
      <Route component={Profile} path="profile"/>
    </Route>
    <Redirect from="/" to="dashboard"/>
  </Router>
); 
```

Discussed with @ryanflorence and @luisrudge on Slack channel.

**Comment by luisrudge** [comment]
Thanks for posting!

**Comment by marioatlp** [comment]
I also was trying to do something similar but where the base route component also had a path(eg. /app)

**Comment by mattybow** [comment]
I thought this was the designed behavior?  Reference: https://github.com/rackt/react-router/issues/1333#issuecomment-113165238

Using beta3, when the Router goes to path match '/' in the first example where you have path set on the Route with Layout, it finds that Route first and stops searching the tree so it never reaches the `<Redirect/>`
```
// first example where redirect is not hit on "/"
const routes = (
  <Router history={history}>
    <Route component={Layout} path="/">
      <Route component={Dashboard} path="dashboard"/>
      <Route component={Profile} path="profile"/>
    </Route>
    <Redirect from="/" to="dashboard"/>
  </Router>
); 
```

In the second example, none of the routes' paths match "/" until you get to the `<Redirect/>` which then sends you to the dashboard route.


The first example would work if you put the `<Redirect/>` before the `path="/"` like so:
```
const routes = (
  <Router history={history}>
    <Redirect from="/" to="dashboard"/>
    <Route component={Layout} path="/">
      <Route component={Dashboard} path="dashboard"/>
      <Route component={Profile} path="profile"/>
    </Route>
  </Router>
); 
```

**Comment by luisrudge** [comment]
@mattybow this makes lots of sense. THanks for the explanation

**Comment by ryanflorence** [comment]
failing test would be amazing

**Comment by mjackson** [comment]
What @mattybow [said](https://github.com/rackt/react-router/issues/1675#issuecomment-128584903).

Oh, and BTW, you should be careful about the value you use inside `<Redirect to>`. A relative path is currently ambiguous, but I'd [like to be able to handle them](https://github.com/rackt/react-router/blob/3c9cc45fe5f8b22e3a3e4f779636e0646d55f818/modules/Redirect.js#L29) eventually. For now, you should use `<Redirect from="/" to="/dashboard" />`.

**Comment by cristiancho29** [comment]
Just use <Route exact path="/" component={AnyComponent}/>
