### ISSUE TITLE
Confusion around react-router 0.x and 1.x

### ISSUE THREAD

**Issue by enzolamzo** [rackt/react-router#1676]
The new library is still in beta so what is the recommended version to use in production? Do you have an ETA in mind?

**Comment by DenisIzmaylov** [comment]
+1

**Comment by mjackson** [comment]
0.13.x is stable right now. It is the default branch on GitHub, the version that you get when you `npm install react-router`, and the version of the docs you see when you go to http://rackt.github.io/react-router/. 1.0 is in the works. No ETA on a release date.
