### ISSUE TITLE
Routes definition priority causing some routes to not work.

### ISSUE THREAD

**Issue by TamerShlash** [rackt/react-router#1677]
This code works fine:

```
  <Route component={Main}>
    <Route path='/' component={Home} />
    <Route path='/items' component={Items} />
    <Route path='/:team' component={Home} />
    <Route path='/:team/users' component={Users} />
    <Route path='/:team/users/:id' component={User} />
  </Route>
```

(Although any undefined URL will show the Home component).

However, in this code:

```
  <Route component={Main}>
    <Route path='/' component={Home} />
    <Route path='/:team' component={Home} />
    <Route path='/:team/users' component={Users} />
    <Route path='/:team/users/:id' component={User} />
    <Route path='/items' component={Items} />
  </Route>
```

The `/items` URL also leads to the Home component, no the Items one.

I'm not sure if this is a bug or it's supposed to work like that. If so, is there any place where I can learn more about the routes definition priority?

**Comment by karantin2020** [comment]
Hi. I din't want to open new issue. Is that correct?
```
var routes = (
    <Route path="/" name="app" handler={App}>
        <DefaultRoute name="home" handler={Home} />
        <Route path="/home" handler={Home} />
        <Route path="/home" handler={AnyOther} />
        <NotFoundRoute name="notFound" handler={NotFound} />

        <Route path="/home/settings" name="settings" handler={Settings} />
    </Route>
);
```
It is the app bug with two ```path="/home"```. But why does not lib check it?

**Comment by mjackson** [comment]
The router tries to match your routes in the order they are defined, top to bottom, @TamerShlash. So in your case defining the `/items` route before the `/:team` route will fix your problem.
