### ISSUE TITLE
Bug report: error in pathnameIsActive, basepath is undefined

### ISSUE THREAD

**Issue by yongxu** [rackt/react-router#1678]
basepath is not initialized here, which raise error when route.path is empty.
This bug is related to #1675
This bug appears in commit c9ae5e0d4cd9a405c5bf478e9d86547bcc964098
![ea5b4ad6-09bb-408b-b19f-48bc07fecb62](https://cloud.githubusercontent.com/assets/1932255/9137526/e7961a4c-3ce3-11e5-920e-b50465feee48.png)

**Comment by ryanflorence** [comment]
fixed in 71574917
