### ISSUE TITLE
React Router parent “.active” class not active when child router loaded

### ISSUE THREAD

**Issue by Martastico** [rackt/react-router#1684]
This is how the routes are set up:

```javascript
var RRoutes = (
<Route handler={App}>

    <Route name="home" path="/" handler={Page} />

    <Route name="portfolio" path="portfolio">
        <DefaultRoute handler={Page} />
        <Route name="portfolio.items" path=":page" handler={test} />
    </Route>

    <Route name="pages" path=":page" handler={Page} />


</Route>
);
```

When "/portfolio" page is loaded the link gets active. If the child route "portfolio.items" is loaded, the parent active link disappears.. Any suggestions how to get this to work? Is the problem because of the dynamic path?

Question asked here as well: http://stackoverflow.com/questions/31902524/react-router-parent-active-class-not-active-when-child-router-loaded

**Comment by taurose** [comment]
How does your link look like? Using a full path for the `to` param will only set it active if path matches exactly; using a name will set it active when the corresponding route is active (doesn't need to be the innermost matched route).

So I guess you're using `<Link to="/portfolio" />` but you're looking for `<Link to="portfolio" />`

**Comment by Martastico** [comment]
Oh wow, this fixed the problem. I spent hours trying many different things but never though of that.. Many thanks!

**Comment by ryanflorence** [comment]
we need to document isActive way better.

**Comment by mdpedersen** [comment]
I have the same problem, but in version 1+ where named routes have been removed. I noticed a discussion where this issue is raised:

https://github.com/rackt/react-router/issues/1514

The answer, by mjackson, is as follows:

*isActive will work the same way in 1.0 as it did in 0.13. The 1.0 implementation just isn't complete yet, but we're working on it.*

However, in 1.0.3 (which I'm currently using), this still isn't working: for child routes, the link active state disappears. So, is the conclusion that this implementation still isn't complete? If so, is there a workaround?

Thanks!
Michael

**Comment by taion** [comment]
@mdpedersen Check the active state example – by default `<Link>`s show as active on the matched route or any of its descendants.

**Comment by mdpedersen** [comment]
@taion, thank you for the quick reply and for the pointer to the example!

For anybody else coming across this: the problem in my case was that I defined a route on the form:

```xml
<Route path="main/:tab" component={...}/>
```

in which case Link active state does NOT work for nested routes. Instead, as per the examples, I had to rewrite this as:

```xml
<Route path="main">
    <Route path=":tab" component={...}/>
</Route>
```

which then works as expected.

**Comment by lucidlemon** [comment]
Man I wish there was something like reddit gold here on github, thanks a ton @mdpedersen. This helped me a thousand times.

And yes, I have to agree with @ryanflorence, there is practically no documentation about the active class, or at least its nowhere easy to be found. This little issue here is the best part of all.

**Comment by geclos** [comment]
Hi,

having the same issue here. I have the following routes:

```
<Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/" name="login" component={Login}/>
      <Route path="/home" onEnter={requireAuth} component={App}>
        <IndexRoute name="home" component={Home}/>
      </Route>
    </Router>
  </Provider>
```

And the following links inside the App component

```
        <li className="nav-item">
          <Link className="nav-link" to="home">Home</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="attributes">Attributes</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="vision">Vision</Link>
        </li>
```
I would expect the Home link to be active be it is not. I look through the documentation and cannot see what I'm doing wrong.

**Comment by lucidlemon** [comment]
which version of react-router are you using @geclos?

**Comment by geclos** [comment]
1.0.3, soz I forgot to mention.

**Comment by lucidlemon** [comment]
@geclos No problem :)
with v 1.0 they changed the activeClassName, you now have to pass it with every link. Documentation for this is here: https://github.com/rackt/react-router/blob/master/upgrade-guides/v1.0.0.md#active-class

So in your case you just have to do this:

```
        <li className="nav-item">
          <Link className="nav-link" to="home" activeClassName="active">Home</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="attributes" activeClassName="active">Attributes</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="vision" activeClassName="active">Vision</Link>
        </li>
```

and the links will get the class `active` when they are.. well.. active :)

Greetings to Barca, have some tapas for me.

**Comment by geclos** [comment]
You, my friend, rock. thanks.

I'll have some tapas for you :smile:

**Comment by iErik** [comment]
Can't we just have named routes back? It was a retarded decision to remove it, any decent router must have some sort of named routes system.

**Comment by savovs** [comment]
Trying to solve this, but no cigar, does anyone see what I'm doing wrong? (using version 2.8.1)

Routes:
```
	<Route path="/" component={App}>
		<IndexRoute component={MainPageContainer} />
		<Route path="venues">
			<IndexRoute component={VenuesPage} />
		</Route>
	</Route>

Links:
```

<IndexLink to="/" activeClassName="active">
					<h6>Feed</h6>
				</IndexLink>


				<Link to="/venues" activeClassName="active">
					<h6>Venues</h6>
				</Link>
```

**Comment by okbel** [comment]
I'm getting the same as @savovs 👎

**Comment by raidenz** [comment]
`<Link onlyActiveOnIndex activeClassName="active" to='/'>Home</Link>`
@savovs use onlyActiveOnIndex  will solve your problem

**Comment by chandlervdw** [comment]
@taion @mdpedersen what about the scenario where you want to link to a route/subroute/:id? In my scenario we list products at `/shop/products?foo=bar`, and then the path to be pushed upon clicking a product is `/shop/product/:productId`. 

We call a helper function to calculate it like so: `this.props.router.push({ pathname: toProduct(ProductId), state: { modal: true } });`

```
const getUrl = (value = 'main', props = {}) => {
  const route = routes.hasOwnProperty(value) ? routes[value] : value;
  return Object.keys(props).reduce((newRoute, key) => {
    if (newRoute.indexOf(key)) return newRoute.replace(key, props[key]);
    return newRoute;
  }, route);
};

export const toProduct = (productId) => {
  return getUrl(routes.product, { ':productId': productId });
};
```

But when I navigate to the product details page, `isActive` is no longer true, even though the URL includes `/shop` at the top level. Any ideas?

**Comment by kiya69** [comment]
Hi guys, I 'm pretty new to react and recently came across this issue, too.
I have a parent page that was linked from a navigation menu that always stay on the page. 
This parent page has 3 links that links to a submodule
The parent page's link is something like: http://localhost:3000/:id
and the child page is http://localhost:3000/:id/:childId
While I'm on the child page the active class is not there in the navigation menu.

Here's my routing code:
```
<Router history={browserHistory}>
      <Route component={SiteContainer} data={data}>
          <Route path="/" component={HomePage}/>
          <Route path=":id" component={TemplateContainer} data={data} />
          <Route path=":id/:classId" component={ClassTemplateContainer} data={otherData}/>
      </Route>
  </Router>
```
I tried 
```
          <Route path=":id" component={TemplateContainer} data={data} >
               <Route path=":classId" component={ClassTemplateContainer} data={otherData}/>
          </Route>
```
But I think because both routes have their own components so it didn't work.
Since I'm fairly new, I think there should be a way to achieve this but not sure where should I look into?
Any help would be really appreciated. Thanks!

**Comment by hkjpotato** [comment]
Hi @chandlervdw Are u using react-router v4 or are u using v3 with a separate routes.js file. I think it might be sth related to your routes setup. The route with params is not regarded as a child of parent route.
