### ISSUE TITLE
Bad request when retrieving pointer data

### ISSUE THREAD

**Issue by nerijusgood** [rackt/react-router#1685]
Hi, 

I am querying a class via pointer data, but i always receive `POST https://api.parse.com/1/classes/Image 400 (Bad Request)`.

I am passing the ID (in image class it points to another table) via URL params. I get it via `getCurrentParams().id` and it logs correct in console, however when I put it query it does not work (above error 400).

Query:

```
observe() {
    return {
      image: (new Parse.Query('Image'))
        .equalTo('challenge', this.context.router.getCurrentParams().id).ascending('createdAt')
		};
  }
```

In class IMAGE there are several rows with 'challenge' column which has that exact ID. What could be the problem?

**Comment by taurose** [comment]
> it logs correct in console, however when I put it query it does not work (above error 400)

Sounds like the issue isn't really related to react-router then, but rather to parse.  Have you tried hardcoding the id? Have you checked your browser dev tools to figure out why you get 400 exactly?

**Comment by nerijusgood** [comment]
Yup, I tried hardcoding it, but still no luck. How can browser dev tools help me?
