### ISSUE TITLE
Restore scroll position

### ISSUE THREAD

**Issue by jjvattamattom** [rackt/react-router#1686]
I want behaviour similar to what the browser offers. If I scrolled down a long page, opened a new page and immediately went back, it would load the previous page at the same scroll position. React Router always re-renders the view and resets scroll, when we go back. How do I get the 'save scroll' with React Router?

**Comment by mjackson** [comment]
Yes, we have plans to automatically let you restore the scroll position as you navigate back to pages you've already visited. We already have [the functionality in master](https://github.com/rackt/react-router/blob/260401bd17d4130a552963be9f76889db4d13a2f/modules/ScrollManagementMixin.js), but we need https://github.com/rackt/history/issues/17 to be fixed first.

**Comment by jjvattamattom** [comment]
Does it **cache** previously rendered DOM and then restore scroll position? Or is the component mounted again? I would expect scroll position to be meaningless if the component renders differently.

**Comment by gaearon** [comment]
It can't (and shouldn't) cache the DOM, after all we're in React's paradigm. Yes, it's up to you to render your components the same way. For example if you don't cache the data locally, there's nothing router can do to restore your position. But that's how browser's default behavior works, too, we're just trying to emulate it.

**Comment by antonholmquist** [comment]
How is this planned to work with async loading of data?

Often the view that you navigate back to will be initially empty, waiting for content to load. As soon as the data is loaded, you typically want to reset the scroll position. (Or is there a way to pre-fetch data and feed into the view before mount?)

**Comment by ryanflorence** [comment]
> How is this planned to work with async loading of data?

YOu need to cache it so when the back button is clicked you get a synchronous render w/ all the data.

**Comment by th0r** [comment]
@ryanflorence That's a bad news. Can't we restore scroll position only after rendering?

**Comment by gaearon** [comment]
@th0r The router can't know when your data is ready.

**Comment by antonholmquist** [comment]
@gaearon If you tell the router, it would now. 

I tried Ryan's advice on caching and restoring the data to get the scroll position to restore correctly. Seems to work well.

**Comment by th0r** [comment]
@gaearon The router knows, when I render something (it means, a already have all the data I need) and it knows it's current state.

**Comment by th0r** [comment]
@antonholmquist What if user goes 5 pages back?

**Comment by vinceprofeta** [comment]
@mjackson is there a solution for this? If so where can I find the docs?

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/73e6c85f427c48f90bae0bb0e9745b6b48536e2f/CHANGES.md#scrolling

**Comment by jackyon** [comment]
also waiting a solution for async loading, any news?

I have tried scroll-behavior, seems this not support async loading, the scrolling position were wrong after I pressed back button.

**Comment by KODerFunk** [comment]
I have a problem, correlated with this issue. Help me please! http://stackoverflow.com/questions/36088020/keep-react-router-routed-components-for-all-history-states

**Comment by jackyon** [comment]
loos like this issue was solved after I upgrade to the new version of react simple router, now it change the name to "react-router-redux".

the position now can be remembered

**Comment by KODerFunk** [comment]
Scroll position is only one effect, i need render whole history steps.

**Comment by richburdon** [comment]
Hi @mjackson, can you point me to any information on how to use ScrollManagementMixin? 
(I can see the code in the repo, but no examples or docs). Thanks.

**Comment by Alfrex92** [comment]
Is the "save scroll" feature already implemented?

**Comment by zhangolve** [comment]
@Alfrex92  maybe you should read this  docs https://reacttraining.com/react-router/web/guides/scroll-restoration
In one word ,React-Router doesn't think it is a bug and want someone else to do the work.

**Comment by morcuswade** [comment]
I'm trying a solution involving using history.replaceState() and window.onpopstate() to track window position and deal with reload.
