### ISSUE TITLE
Publish beta4 to NPM

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#1688]
In **master**, `history` has been moved into a separate module and (somewhat) refactored: https://github.com/rackt/history.

I'd like to build on the new history API for data-loading purposes. Is this stable enough to publish current master as `beta4` on NPM?

**Comment by ryanflorence** [comment]
SLOW DOWN TEX

(but yeah, its coming shortly)

**Comment by aldendaniels** [comment]
:)

**Comment by xpepermint** [comment]
+1
