### ISSUE TITLE
ES6 transitionTo with 0.13.3 (undefined context)

### ISSUE THREAD

**Issue by catalinfeier** [rackt/react-router#1689]
Maybe i got really confused by the recent changes with the handling of ES6, but how are we supposed to manage the transition in ES6?
I have the following:
```javascript
//Register.js
class Register extends React.Component {
    constructor(props, context){
        super(props);
    }
    gotoLogin() {
        event.preventDefault();
        this.context.router.transitionTo('/login');
    }
    render() {
        return (            
                    <div >
                        <button onClick={this.gotoLogin}>Login</button>
                    </div> 
        );
    }
}

Register.contextTypes = {
    router: React.PropTypes.func.isRequired
};

//Routes.js
<Route name="app" path="/" handler={ App }>
    <Route name="register" handler={ Register } />
    <Route name="login" handler={ Login } />
</Route>
```
And this gives me an "Uncaught TypeError: Cannot read property 'context' of undefined".
So basically, i want to make the transition from a function, not with a link, using ES6 syntax. Any pointers?

**Comment by dozoisch** [comment]
You need to bind your function. See https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes

Eg: `<button onClick={() => this.gotoLogin()}>Login</button>`

**Comment by catalinfeier** [comment]
Awesome, it works. Thanks alot. I didn't expect it to be that easy.
