### ISSUE TITLE
Bogus transition object returned for not-found routes in Router.run

### ISSUE THREAD

**Issue by wonnage** [rackt/react-router#1690]
Given the following routes:

```
    <Route>
      <Route path='/found'/>
    </Route>
```

Calling Router.run(routes, '/missing' (error, initialState, transition) => {...}) provides a surprising set of arguments to the callback. 
`error` is undefined, which maybe makes sense. 
`initialState` is null, makes sense. 
`transition` is this object: `Transition{isCancelled: false, redirectInfo: null, abortReason: null}`

IMO `transition` should be null as well, since there's no transition happening here. This makes it harder to distinguish redirects from not-found (`initialState == null && transition.redirectInfo == null` vs. just `initialState == null`, or checking for `error`).

**Comment by ryanflorence** [comment]
SSR rendering is still baking, this is what it will look like when done, hopefully a lot less bogus than this :P

https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md
