### ISSUE TITLE
1.0.0-beta3 How to add props in  this.props.children

### ISSUE THREAD

**Issue by Passerby** [rackt/react-router#1691]
in 0.13.3, I use RouteHandler
```
<div>
  <RouteHandler loadCartCount={this.loadCartCount} />
</div>
```

but 1.0.0-beta3 
```
<div>
  {this.props.children}
</div>
```

how to add loadCartCount function in children props?

**Comment by biernacki** [comment]
You could use cloneElement, see the docs - https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement and also https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html

```
<div>
  {React.cloneElement(this.props.children, {
    loadCartCount: this.loadCartCount
  })}
</div>
```

**Comment by Passerby** [comment]
@biernacki thx, it's a solution. But I think react router might think about it.
