### ISSUE TITLE
Using composition to extend <Route/>'s functionality

### ISSUE THREAD

**Issue by TimDaub** [rackt/react-router#1692]
Hi,

so I wanted to use composition to dynamically choose a handler in my own custom <Route/> component.
What I did was:

```
let CustomRoute = React.createClass({
    chooseHandler() {
        let handler;
        // custom logic to choose a handler

        return handler;
    },

    render() {
        console.log('Hello world'); // not called
        return (
            <Route
                name={this.props.name}
                path={this.props.path}
                ignoreScrollBehavior={this.props.ignoreScrollBehavior}
                handler={this.chooseHandler()}>
                {this.props.children}
            </Route>
        );
    }
});
```

I want to do this for now as we want to support whitelabel pages that display different handlers depending on the subdomain a user currently is on.

However, the render function of my custom component is not called.

Any tips?

**Comment by taurose** [comment]
`<Route>`s are never rendered, they're just used for configuration as a nicer alternative to plain JS objects (which will be supported in the next version as well).

In your case (different handlers depending on subdomain), it seems sufficient to generate the route config dynamically upfront, e.g.

```js
var routes = null;
if (subdomain1) {
  routes = ...;
} elseif (subdomain2) {
  routes = ...;
}
```
It's just JS, so you can get more creative if you want to: 


```js
function createProps(name, path) {
  return {
    name: name,
    path: path,
    handler: ....
  };
}

var routes = <Route {...createProps('root', '/')}>
  <Route {...createProps('foo', 'foo')} />
  <Route {...createProps('bar', 'bar')} />
</Route>
```

Or you could delegate this task to your route handlers, i.e. render different components depending on the subdomain.
