### ISSUE TITLE
0.13.3 - Changing RouteHandler mount-point depending on route

### ISSUE THREAD

**Issue by agon-shabi** [rackt/react-router#1693]
I'm trying to create a scenario not dissimilar to the following:

The main page/handler is defined:
```
<Header {...headerProps} />
<RouteHandler /> // for 'public' routes
<Footer {...footerProps} />
<Modal>
  <RouteHandler /> // for 'private' routes
</Modal>
```

All 'public' routes are rendered in the middle section (e.g. '/bicycles', '/bicycle/:bicycleId', '/events', '/locations', etc), and all 'private' routes (e.g. '/accountInfo', '/friends', '/inbox') are rendered in a separate section, which is animated into view when the route is active. When the 'private' section is visible, the last visible 'public' route should still be visible in the background.

I've tried adding some logic to the main handler to dynamically change where the `<RouteHandler/>` is located at render-time, and declaring some 'pseudo-routes' to wrap all public and private routes separately, with their `willTransitionTo` and `willTransitionFrom` hooks toggling CSS classes to animate the 'private-area' modal in/out of view, but am not getting the desired behaviour, as the 'public' section will immediately unmount.

Does anyone have any experience with trying to do something like this?

**Comment by nickclaw** [comment]
I'm doing a similar thing using the current beta. It's not working perfectly yet, but something like this might work for you too.

```javascript
import {createHashHistory, createHistory} from 'history';

const privateRoutes = (
    <Router history={createHashHistory()}>
        // ...
    </Router>
);

const app = React.createClass({
    render() {
        return (
            <div>
                 <div>
                     // ....
                 </div>
                 {privateRoutes}
            </div>
        );
    }
});

const publicRoutes = (
    <Router history={createHistory()}>
        <Route path="/" component={App}>
            // ...
        </Route>
    </Router>
);
```

**Comment by agon-shabi** [comment]
Would this mean that certain routes use the History API, and others use the hash location method?

I'm looking for a solution that is either entirely hash-based, or (ideally) one that will lend itself nicely to an isomorphic deployment strategy.

**Comment by nickclaw** [comment]
I see, probably not the best fit for you then.

**Comment by ryanflorence** [comment]
This is basically a "nested" router where you can mount a bunch of routes dynamically at any previous url, public/private isn't really relevant I don't think.

**Comment by ryanflorence** [comment]
check out the new pinterest example on master and #1808 its pretty easy now :)
