### ISSUE TITLE
1.0.0-beta-3 'react-router/lib/BrowserHistory' does not exist

### ISSUE THREAD

**Issue by cheapsteak** [rackt/react-router#1695]
The examples show history being required from react-router (e.g. https://github.com/rackt/react-router/blob/master/examples/animations/app.js)
```js
import createHistory from 'history/lib/createHashHistory';
```
Should this either be exported again by the library or list history as a peer dependency?

**Comment by theolampert** [comment]
@cheapsteak I think now you can simply write:
```javascript
import { history } from 'react-router/lib/HashHistory';
```

then:
```javascript
<Router history={history}>
	<Route path="/" component={someComponent}>
	</Route>
</Router>
```

**Comment by dozoisch** [comment]
This is because in the next beta history will be extracted from react-router
