### ISSUE TITLE
transitionTo parsing route name instead of URL first

### ISSUE THREAD

**Issue by subsumo** [rackt/react-router#1697]
Given  
this.transitionTo('http://xxx.local/downtown/'); 
Results in
Uncaught Error: Invariant Violation: Cannot find a route named "http://xxx.local/downtown/"

But should navigate client-side and attempt to match a route. How can I fix this?

J

**Comment by taurose** [comment]
You can't use full URLs with `transitionTo` or `replaceWith`.

Change it to `this.transitionTo('/downtown/'); `.

**Comment by subsumo** [comment]
Thanks.

Might want to change this in the docs:

Examples

this.transitionTo('user', {id: 10}, {showAge: true});
this.transitionTo('about');
this.transitionTo('/users/10?showAge=true');
this.transitionTo('http://example.com/users/10?showAge=true');

**Comment by ryanflorence** [comment]
new docs don't have this, thanks :)
