### ISSUE TITLE
Capture clicks to links

### ISSUE THREAD

**Issue by jjvattamattom** [rackt/react-router#1698]
I have raw HTML that contains links to links within app and outside. I want to capture clicks to links and

1. Route them via React Router if the path matches(absolute or relative)
2. Load the page if its external

Is there a built-in feature? Else whats the best way?

```
Please refer <a href="/link/in/app">this</a> and <a href="tumblr.com/article">this</a>
```

**Comment by taurose** [comment]
There's no built-in feature for this. You could try to capture the clicks yourself and then use `router.transitionTo(path)` with a path such as `/link/in/app`.

**Comment by ryanflorence** [comment]
You can do this yourself if you'd like, but then you won't know that a link is active or not and be able to style it differently.

Whats wrong with using Link?

**Comment by prettynatty** [comment]
In my case I am rendering markdown via `dangerouslySetInnerHTML`, I can't use `Link` inside such HTML.

**Comment by sassanh** [comment]
Same problem here, rendering html via `dangerouslySetInnerHTML`, I can't capture click on anchors nor use `Link` I need a kind of wrapper like this: http://strml.viewdocs.io/react-router-component/a-elements/

**Comment by tiemevanveen** [comment]
Thanks for the idea! I used this onClick method as an example for such an onClick handler on my parent element :)

https://github.com/STRML/react-router-component/blob/e453e24342c12a2fcfd7d7ba797be18415f9a497/lib/CaptureClicks.js#L39

**Comment by Nathan22Miles** [comment]
I must be missing something. When I put an event handler in the parent I get a click event. Unfortunately the target attribute comes back null so I have no idea what was clicked.

    render() {
        return (
          <div onClick={this.onClick.bind(this)}
               dangerouslySetInnerHTML={{__html: content}} />
       )}

**Comment by aravindfantain** [comment]
Solved exactly the same thing. In the onClick function, you will get event as the only parameter, and event.target will give you the href details. Hope this helps.
