### ISSUE TITLE
1.0.0-beta3 - 'query' format not consistent between server render and client client render

### ISSUE THREAD

**Issue by fantasy8-me** [rackt/react-router#1699]
Accessing url like `http://localhost:4545/post?param1=value1&param2=value2`

And try to get the query string from `this.props.location.query'

```
console.log('this.props.location.query', this.props.location.query);
```
In server side, the output is a string
![image](https://cloud.githubusercontent.com/assets/5283413/9219705/5aab900a-410f-11e5-91fc-c04e349a2e99.png)

While in client side, the query string is parsed and stored as an object
![image](https://cloud.githubusercontent.com/assets/5283413/9219684/27540e08-410f-11e5-9fbb-6d181b1d2634.png)

And this inconsistent behaviour might lead to below warning from react 

>warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:

**Comment by ryanflorence** [comment]
we're not sure where pluggable query parsing is going to land in the API, but in beta3 its a prop to Router

`<Router parseQueryString={fn} stringifyQuery={fn}/>`

use that to get your server and client in sync.
