### ISSUE TITLE
Unhandled aborted transition Error 

### ISSUE THREAD

**Issue by praveen-ti** [rackt/react-router#1702]
I have a react component like this;

export default class Customsurvey extends React.Component {
// body
}

and I added ES6 hook for that component like;

Customsurvey.willTransitionTo = function (transition, params, query) {
if(!AuthStore.getState().isLoggedIn) {
transition.redirect('/login');
}
};

It is working fine for me when AuthStore.getState().isLoggedIn has false value (not logged in).
The problem is when isLoggedIn is to set to true (logged in now), and if I refresh the same page then I got errors like this;

Unhandled aborted transition! Reason: [object Object]

Any idea what cause this issue?

**Comment by dmerc** [comment]
I was getting same error message and found the solution in #612, which was to specify 'onAbort' function for react-router on the server-side.
