### ISSUE TITLE
getQuery() value after applying replaceWith()

### ISSUE THREAD

**Issue by AskhatOmarov** [rackt/react-router#1704]
Hi there, I'm applying `replaceWith()` function to change url in address bar with new query string (I'm still on the same route). `replaceWith()` works perfectly, however when I'm trying to get query string with `getQuery()` function it shows old query string. Is it a bug or how should I retrieve the actual query string?

**Comment by ryanflorence** [comment]
that sounds like a bug, you can pass query down as props from the top and it should be accurate:

```js
// 0.13.x
Router.run(function(Handler, state) {
  React.render(<Handler query={state.query}/>);
})
// and then to handlers
<RouterHandler query={this.props.query}/>
```

We use props for this stuff on master, so I don't thikn its a bug anymore.
