### ISSUE TITLE
1.0.0: Configure Router before Router.run

### ISSUE THREAD

**Issue by xpepermint** [rackt/react-router#1706]
I don't see that the `Router` could be configured before running `Router.run`. This is critical for server-side rendering. I need to pass cookies data into Router (server side) before executing `Router.run`. I check if user is authenticated inside `onEnter` thus Router must be configured before `Router.run`. I would like to initialize the value of `this.context.router.accessToken`. What can we do about it?

**Comment by ryanflorence** [comment]
you can make your own component that renders `<Router/>` and put that stuff on context yourself.

**Comment by xpepermint** [comment]
@ryanflorence Thanks for the hint but I'm not sure I understand. Are you saying that I should ignore `Router.run` command on the server? I'm still trying to solve this https://github.com/rackt/react-router/issues/1629. Can you paste a link to an example where onEnter would work with your proposal?
