### ISSUE TITLE
Scope support / class names replacement

### ISSUE THREAD

**Issue by cusspvz** [rackt/react-router#1711]
Is there a way to provide an object with classnames?

We will gonna need to apply different versions of styling, which will require us to use `css-loader` [scope feature](https://github.com/webpack/css-loader#local-scope).

As so, is there a way to configure classes being used by this module on `require`?

**Comment by cusspvz** [comment]
cc @teresamorais

**Comment by ryanflorence** [comment]
I don't know what we're talking about here... routers don't have classnames, and Link fully supports them.

**Comment by cusspvz** [comment]
Sorry @ryanflorence , wrong repo! :/
