### ISSUE TITLE
Relay RootContainer integration

### ISSUE THREAD

**Issue by taion** [rackt/react-router#1714]
Summarizing a discussion w/@cpojer, @dzannotti, and @RickWong on Reactiflux, apologies in advance if I misstated something:

Facebook's own router doesn't have nested routes, and each route has its own associated Relay route/query root, allowing them to use a single `RootContainer`.

With nested routes in React Router, this isn't so much possible. One way to address this would be to have each `Route` work as something like a "stem container" that just defines a query root, while these get aggregated at the `Router` level into something usable for a single `RootContainer`.

The alternative would be to have one `RootContainer` per route, but this is unattractive because it means that there is no longer a single hook for fetch lifecycle.

Possibly something to put in a `react-router-relay` package once the v1.0 API stabilizes.

**Comment by ryanflorence** [comment]
yeah, we've had some discussions w/ the relay team about this, and eventually we'll have AsyncProps as an example for integrating with stuff like relay. I'll leave this open until then.

**Comment by taion** [comment]
Compare https://github.com/devknoll/relay-nested-routes - cc @devknoll

**Comment by taion** [comment]
I'm going to close this for now - relay-nested-routes now pretty much does exactly what I need, so there isn't anything further that's actionable.

**Comment by devknoll** [comment]
Actually, @ryanflorence @mjackson do you mind if we rename `relay-nested-routes` to `react-router-relay`? Seems like a better name.

**Comment by taion** [comment]
:+1: to that - I think it'd be a clearer name.
