### ISSUE TITLE
How can I get a router instance in 1.0.0-beta3

### ISSUE THREAD

**Issue by TaichiHo** [rackt/react-router#1720]
There is a Router.create method in 0.13.3, but I can't find anything similar in 1.0.0-beta3. I want to pass around the router instance in order to call transitionTo.

**Comment by ryanflorence** [comment]
No different than anything else in react:

```
var component = React.render(<Router/>, el);
```

or if inside a render method put a ref on it.

**Comment by mars** [comment]
I had a hard time getting refs to work for the Router when wrapped with a Redux Provider.

Ended up pulling it from context in the top-level Route and passing it down to the children https://gist.github.com/mars/2f70f79066fa78f33801

**Comment by gaearon** [comment]
>I had a hard time getting refs to work for the Router when wrapped with a Redux Provider.

Render `<Provider>` and `<Router>` from a React component (like [`<Root>` in this example](https://github.com/rackt/redux/blob/master/examples/real-world/containers/Root.js)) and give `Router` a `ref`.

**Comment by mars** [comment]
Yes, I tried giving `Router` a `ref`. Still didn't work.

Later, realized that I was trying to use `this.refs.router` during `render()`, which is [listed as a no-no](http://facebook.github.io/react/docs/more-about-refs.html#cautions).
