### ISSUE TITLE
is-frozen.js:2Uncaught TypeError: Cannot read property 'isFrozen' of undefined

### ISSUE THREAD

**Issue by ericntd** [rackt/react-router#1721]
I'm trying to use this with React Router Bootstrap.

Full stack trace is as follows:
```
Uncaught TypeError: Cannot read property 'isFrozen' of undefined113.../../modules/$.core @ is-frozen.js:2s @ _prelude.js:1(anonymous function) @ _prelude.js:1103.core-js/library/fn/object/is-frozen @ is-frozen.js:1s @ _prelude.js:1(anonymous function) @ _prelude.js:153../Fade @ Modal.js:8s @ _prelude.js:1(anonymous function) @ _prelude.js:187../Accordion @ index.js:177s @ _prelude.js:1(anonymous function) @ _prelude.js:11../app/RouterContainer @ app.jsx:3s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
```

**Comment by ryanflorence** [comment]
no idea what this is but its not us

**Comment by wkerswell** [comment]
Let me know if you find out what it is as I have the same error.

**Comment by wkerswell** [comment]
Just to add some more detail I am not using react-router on the page although I do have the package install and am using is else where. I am using browserify and babelify to transcode the es6. @ericntd could you let me know if you are using the same and if you found a solution to your problem.

**Comment by wkerswell** [comment]
Ok seems to have found that another node module was conflicting with it in some way. It was bundle-collapser. Removing the module sorted my problem.
