### ISSUE TITLE
Default route / default handler / root handler in 1.0.0 (again)

### ISSUE THREAD

**Issue by rpominov** [rackt/react-router#1730]
Hi!

I've seen #1333 and #1571, but still cant figure out how to properly define a default route.

Here how my config looks like:

```
import Router from 'react-router'
import {history} from 'react-router/lib/BrowserHistory'

import Layout from './Layout'
import Dashboard from './Dashboard'
import About from './About'
import NotFound from './NotFound'

const routes = {path: '/admin', component: Layout, childRoutes: [
  {path: '/', component: Dashboard},
  {path: '/about', component: About},
  {path: '*', component: NotFound}
]}

<Router routes={routes} history={history} />
```

I want `Dashboard` to be default handler for `/admin`, but the code above doesn't work. It works though if I remove `path: '/admin'`, but I need `/admin` to be base path.

Recommended solution from #1571 is to use `this.props.children || <Dashboard/>` in `Layout`, but it doesn't seem right to me. I don't want layout to know about default handler, it's just a layout, it doesn't supposed to know about `<Dashboard/>`.

I'd really appreciate if the code above just worked.

**Comment by taion** [comment]
See https://github.com/rackt/react-router/issues/1657.

**Comment by rpominov** [comment]
Sorry, didn't found this one. 

`indexRoute` works, but from discussions seems like it might not be the final API. Also couldn't find it in the docs.

Also while following works fine:

```js
routes = {path: '/admin', component: Layout, indexRoute: {component: Dashboard}, childRoutes: [
  {path: '/about', component: About},
  {path: '*', component: _NotFound}
]}
```

This doesn't:

```js
routes = {component: Layout, indexRoute: {component: Dashboard}, childRoutes: [
  {path: '/about', component: About},
  {path: '*', component: _NotFound}
]}
```

And unfortunately `path: '/admin'` (the base path) is configurable in my case, and might be either present or not. So complete bulletproof code looks like this:

```js
routes = {component: Layout, indexRoute: {component: Dashboard}, childRoutes: [
  {path: '/', component: Dashboard},
  {path: '/about', component: About},
  {path: '*', component: _NotFound}
]}

routes = addBasePathMaybe(routes)
```

**Comment by TaichiHo** [comment]
I figured the default route for child route in the following way:
```
            <Redirect from="child" to="child/default"/>
            <Route path="child" component={childComponent}>
                <Route path="default" component={defaultComponent}/>
                <Route path="others" component={otherComponent}/>
            </Route>
```
Hope it helps!

**Comment by ryanflorence** [comment]
<IndexRoute/> is back in.
