### ISSUE TITLE
Relative paths in v1.0.0-beta3

### ISSUE THREAD

**Issue by jackmoore** [rackt/react-router#1731]
The router is failing to understand relative links when transitioning using the `Link` component.  For example:

```
<Route path='/' component={'./Root'}>
	<Route path='one/' component={require('./One')}>
		<Route path='two/' component={require('./Two')}></Route>
	</Route>
	<Route path='*' component={require('./Error404')}></Route>
</Route>
```

If I use the following in the `One` component (http://localhost/one/), then the router transitions me to the correct URL (http://localhost/two/), but gives the `Error404` component:

```
<Link to='two/'>Two</Link>
```

If I refresh the page, then the `Two` component correctly renders.  Same URL in the address bar, but depending if I navigated there directly, or transitioned there using `Link` impacts which component gets rendered.

**Comment by grbspltt** [comment]
I know this isn't correct and they said not to do it,  however I had the same issue and solved it by adding a leading '/' to my routes.  Worth a shot.

**Comment by ryanflorence** [comment]
Three things might be in play

1. A bug in relative paths in route config. Route config paths should inherit their parent if there is no leading slash, which I just confirmed on master is working fine from the examples and there's these tests that have relative paths in route config: https://github.com/rackt/react-router/blob/master/modules/__tests__/matchRoutes-test.js

2. Relative "to" path in a  `Link` does not work like anchors (yet anyway) see https://github.com/rackt/react-router/issues/1828

3. Putting a trailing `/` might be screwing things up, can remove it and see what happens?

**Comment by jackmoore** [comment]
I guess relative paths are not supported: https://github.com/rackt/react-router/issues/1826

**Comment by yiluxin** [comment]
I met the same problem, if simply using the < a > ，relative path is work, don't know why reactRouter can not use a relative path, is with any other consideration?

**Comment by ryanflorence** [comment]
@yiluxin :point_right: #2172
