### ISSUE TITLE
Failed Context Types: Required context `routeDepth` was not specified in `RouteHandler`.

### ISSUE THREAD

**Issue by Gooseware** [rackt/react-router#1734]
I have checked and I do not have React being instantiated more than once;

Using react-router v0.13.3
I don't think this would be very easy to reproduce. But I was wondering if you could give some suggestions on how to debug this particular error.

```javascript
var { Route, Redirect, RouteHandler, Link } = Router;

var App =  React.createClass({
    render: function () {
        return (
            <div id="main">
                <header>
                    <div id="navigation">
                    </div>
                </header>
                <RouteHandler/>
                <footer>
                    <div id="footer"></div>
                </footer>
            </div>
        );
    }
});
```

**Comment by ryanflorence** [comment]
probably means your app is not being rendered with the `Handler` that v0.13 gives you. Please check the examples and make sure your'e rendering your app correctly: https://github.com/rackt/react-router/blob/0.13.x/examples/dynamic-segments/app.js#L67-L69
