### ISSUE TITLE
I tried to goto /xyz path but api call from / path is getting called. why is this ?

### ISSUE THREAD

**Issue by TonyFrancis** [rackt/react-router#1735]
```jsx
  <Route path="/" component={Mail}>
    <Route path="mail/:id" component={MailID} />
    <Route path="calendar" component={calendar}/>
    <Route path="request" component={request} />
  </Route>
```

I tried to goto directly ``` /request```  but in network tab I saw  api from Mail component is getting called. How is  / path api getting called is it because I put api call in ```componentWillMount``` ??? 

![react router](https://cloud.githubusercontent.com/assets/12655203/9352836/c396ef34-4681-11e5-947e-8dc8eaafb028.png)

**Comment by jabjab** [comment]
> is it because I put api call in `componentWillMount`?

That seems most likely. Going to `/request` will render `Mail` along with the `request` component, which will indeed result in `Mail`'s `componentWillMount` being called. If you only want it to happen when `/` is the route, make a component to use with `DefaultRoute` instead and put your API call there.
