### ISSUE TITLE
Partial App Loading Example ES6 Classes

### ISSUE THREAD

**Issue by arb** [rackt/react-router#1737]
Looking at https://github.com/rackt/react-router/tree/0.13.x/examples/partial-app-loading gives you a good idea of how to do the dynamic component loading controlled by the router. However, this uses the "old style" `React.createClass()` style and not ES6 classes.

Does anyone have an example of doing the same feature but using ES6 classes? I haven't been able to get it to work.

**Comment by dferber90** [comment]
You can check out https://github.com/dferber90/webapp-starter-pack. It’s WIP, but I already have the code splitting part partially done. Should be good enough as an example.

**Comment by arb** [comment]
I should have specified I wanted to use react-router 0.13.x. It's hard to get sign-off on beta versions of modules in a corporation. Also, this was more a comment on updating documentation and providing a simple example.

Thanks for the link though, I will check it out.
