### ISSUE TITLE
Extended pinterest example

### ISSUE THREAD

**Issue by khakulov** [rackt/react-router#1739]
I like pinterest example. But in pinterest you can see a picture from many routes. Not only from root route. You can also navigate to picture from search page, or profile page (not only fromFeed). In fact you can navigate to picture from any route, and the background does not changes.

Please provide an extended example, where you can open the picture modal from any route.

**Comment by Pendla** [comment]
+1

**Comment by puzzfuzz** [comment]
Agreed. I'd love an example of using a route to launch a modal.

**Comment by ryanflorence** [comment]
see comments on #1808
