### ISSUE TITLE
@connectToStores does not work with onEnter onLeave

### ISSUE THREAD

**Issue by tony99nyr** [rackt/react-router#1741]
I am using the connectToStores decorator
```
@connectToStores
export default class User extends React.Component {
    ...
    static willTransitionTo() {
        console.log('willTransitionTo');
    }
    ....
}
```

Inside `createRoutesFromReactChildren.js` the `handler` object is an instance of `StoreConnection` and the static function `willTransitionTo` is not visible and thus the onEnter function is not set properly.  

```
if (handler) {
    options.onEnter = handler.willTransitionTo;
    options.onLeave = handler.willTransitionFrom;
  }
```

Using the connectToStores decorator makes it impossible (let me know if there is another way) to add `onEnter` and `onLeave` event handlers.

**Comment by koulmomo** [comment]
what `@connectToStores` decorator implementation are you using? It will have to be modified to hoist non-react statics, see: https://github.com/yahoo/fluxible/pull/176 as an example.

**Comment by tony99nyr** [comment]
I am using alt's: alt/utils/connectToStores
https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js

Awesome, looks like this was already solved.  I will move this issue over to alt and request they hoist the statics the same way fluxible did.

Thanks!
