### ISSUE TITLE
Dynamic Header

### ISSUE THREAD

**Issue by razagill** [rackt/react-router#1742]
Hi,
I'm sure somebody has asked this in a different way before but in any case. I have a `header` component that display different titles based on which `view` component is loaded. For now, this `header` component is placed in every `view` component and the title is being passed as `props`. I wanted to know if there is a better way where I can placed the `header` component in my entry file above the `<RouteHandler/>` and have it dynamic (can get the title from the `view` component that is being loaded)?
My entry file looks like this.
```
export default class Admin extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <RouteHandler />
      </div>
    );
  }
}
```

I would like to do something like this:
```
export default class TPPAdmin extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <Header />
        <RouteHandler />
      </div>
    );
  }
}
```

**Comment by ryanflorence** [comment]
on master you can provide multiple components to a route, so all parts of your app can participate in the routing. https://github.com/rackt/react-router/blob/master/docs/Route.md#components

**Comment by joaomilho** [comment]
The link is broken.

**Comment by mxstbr** [comment]
https://github.com/reactjs/react-router/blob/master/docs/API.md#components-1

**Comment by joaomilho** [comment]
Danke!

**Comment by joaomilho** [comment]
The docs are still using the older syntax. I'll check how to do it in the new one (plain old object) and send a PR.

**Comment by davidthornton** [comment]
Both links are broken
