### ISSUE TITLE
How do you get a ref to a rendered component in 1.0.0-beta3?

### ISSUE THREAD

**Issue by yanivtal** [rackt/react-router#1743]
I'm trying to write unit tests for React Router and it's not a piece of cake. I can React.render(<Router />) and get the HTML but I want to work with refs in my tests.

In v0.13 we could call router.run() and get the RouteHandler and render that using TestUtils and get a ref to the component. In 1.0.0-beta3 we have to render Router directly but then I can't get a ref to my component.

Setup:
```
class ComponentToTest extends Component {
  render() {
    return (
      <Navbar links={links} ref='componentRef'/>
    );
  }
}

let location = createLocation('/');
let routes = [
  {
    path: '/',
    component: ComponentToTest
  }
];

describe('Navbar', () => {
  before((done) => {
    Router.run(routes, location, (error, state) => {

      let router = TestUtils.renderIntoDocument(
        <Router {...state} />
      );

      // Should be able to access router.refs.componentRef but I can't
      done();
    });
  });
});
```

How do I get a ref to componentRef? I'd greatly appreciate any help.

**Comment by oliverwoodings** [comment]
In your example you actually shouldn't be able to access `router.refs.componentRef`. Refs belong to the render function in which they are returned from. In this case, `componentRef` belongs to the render function of `ComponentToTest`. In order to access `ComponentToTest`, react-router would need to place a ref on the component inside it's own render function.

**Comment by oliverwoodings** [comment]
@ryanflorence @mjackson would be very interested in working with you guys to solve this since at the moment it is basically impossible to use react-router v1.0 with [react-test-tree](https://github.com/QubitProducts/react-test-tree).

**Comment by yanivtal** [comment]
Yes you're right. Since they're rendering the component they have to include the ref. That's the problem! Is this a use case for React's ref as a function?

**Comment by oliverwoodings** [comment]
Got a solution for you!

```jsx
var TestComponent = React.createClass({
  render: function () {
    return <div ref='wooo'>Hello!</div>;
  }
});

var location = createLocation('/');
var history = new MemoryHistory(['/']);

var tree = testRouterTree(
  <Router history={history} location={location}>
    <Route path='/' component={TestComponent} />
  </Router>
);

tree.wooo; // woooooo!

function testRouterTree (router) {
  var oldRenderFn = router.type.prototype.render;
  router.type.innerComponentRef = 'innerComponent';
  router.type.prototype.render = function () {
    var renderTree = oldRenderFn.apply(this, arguments);
    return React.cloneElement(renderTree, {
      ref: 'innerComponent'
    });
  };
  return testTree(router);
}
```

**Comment by oliverwoodings** [comment]
I've sent in a PR with a proper solution to this.

**Comment by yanivtal** [comment]
Woo!

**Comment by yanivtal** [comment]
Btw, I noticed that redux wanted the inner component ref to be wrappedInstance and here we're doing innerComponent (which I prefer). Just gonna have to live with the inconsistency?

**Comment by oliverwoodings** [comment]
Where do they say they want it to be wrappedInstance? BTW i've created a temporary fix for you in the react-test-tree issue.

**Comment by yanivtal** [comment]
I maybe confusing some things. I was referring to this conversation https://github.com/rackt/react-redux/pull/35. But inspecting the code here https://github.com/rackt/react-redux/blob/04cdc36671c3e329a161dc83dbf0f111c3712095/src/components/createConnect.js they name their inner component ref "wrappedInstance". Also, I was referring to react-redux, not redux.

**Comment by oliverwoodings** [comment]
Ah ok I see, didn't realise you were talking about react-redux. Will see what they say, doesn't matter if they rename it to wrappedInstance. test-tree don't give no fucks :stuck_out_tongue:

**Comment by taurose** [comment]
I'm not sure if it works with react-test-tree, but what you could try is using `<Router createElement>` to add `ref` props to your components. Those can  be functions to get the ref yourself. Alternatively, cloning and adding `ref` should work as well, except for the very first component.

**Comment by oliverwoodings** [comment]
@taurose thanks for this, createElement will definitely work. @yanivtal can you close this? I'll update the test-tree docs with the solution.

**Comment by yanivtal** [comment]
np thanks for driving

**Comment by PixelsCommander** [comment]
createElement solution does not seem to work for v2.0rc5 . Any suggestions?
