### ISSUE TITLE
Get reference to router without context?

### ISSUE THREAD

**Issue by togakangaroo** [rackt/react-router#1754]
Hi, I've seen #1059, #1497, and #1499 and am still confused about how I'm supposed to use router without mixins.

I'm *not* using es6 classes, opting instead for straightforward react components. This means that as far as I know I don't get `context` passed in a second parameter in the constructor (as there isn't a constructor).

In addition, I'm not happy with the solution of using mixins or any reliance at all on this.context since that throws errors when unit testing components in isolation.

Is there a way to get a reference to the router and just pass it in normally via props (which is far easier to stub out in tests)?

**Comment by taurose** [comment]
I don't think there's a great way to do this in 0.13.3. If your main concern is not having to stub context for testing route handlers, perhaps you could use a HoC for grabbing `router` from context, and then pass it to your actual handlers as a normal prop. You'd have to delegate calls to `willTransitionTo` and `willTransitionFrom` though, if you want to use them. And you'd have to write your own `<Link>`s (or create a HoC that injects context from props, i.e the reverse of what the aforementioned HoC for handlers would do).

In 1.0, some usages of context will probably be replaced by passing props directly to your route handlers. It's still needed for easy to use `<Link>`s though. However, you might be able to pass the router instance to all route components by using `createElement` so you wouldn't need a HoC for that.

Of course you could always create a global router "container", i.e. `require('./router-container').router = Router.create(..);`, but I assume you don't want that.

**Comment by togakangaroo** [comment]
I should have specified - I'm using beta3, Links are not an issue honestly - this is a sizable app with lots of custom stuff going on, I can't see myself using *"just"* a link very often. 

I was thinking I could just do `transitionTo` in my top-level component and pass down callbacks via props but since the top level component is now `Router` I can't actually set props anymore huh?

**Comment by taurose** [comment]
`router-container` was meant as a module you'd create yourself which would simply act as a globally accessible object.

```js
// router-container.js
module.exports = {router:null};

// main.js
var router = ...; 
require('./router-container').router = router;

// SomeRouterComponent.js
var routerContainer = require('./router-container');
var Component = React.createClass({
  someMethod() {
    routerContainer.router.transitionTo(..);
  }
});
```

`Router.create` is part of the old API. In beta3, the router instance is the same as the component instance, which you can only get from the return value of `React.render` or via context. Hopefully that'll change in the future so you could use `createElement` to pass the router instance to route components as a prop yourself. Until then, I think  the best way would be to use a HoC like I suggested for 0.13.3:

```js
var routerAsProp = function(Component) {
  return React.createClass({
    contextTypes: {
      router: React.PropTypes.object.isRequired
    },
    render: function() {
      return <Component {...this.props} router={this.context.router} />; 
    }
  });
}

var routes = <Route component={routerAsProp(RouteComponent)} ... />;
...
```

**Comment by ryanflorence** [comment]
We will probably ship with HoCs for every mixin that we've got. But for now you either use mixins, or use context directly (though note that the stuff in context is not public API).

> In addition, I'm not happy with the solution of using mixins or any reliance at all on this.context since that throws errors when unit testing components in isolation.

What errors are you running into? Link no longer throws, just warns if rendered out of context, and if its a unit test you won't be needing to transition anywhere in the app.

If for some reason you do need to test that some interaction eventually transition places on the router, you can do two things:

1. Use a default prop that handles the transitioning and then in your unit test pass in a prop
2. Stub out context just like you would stub out props
