### ISSUE TITLE
Handle all 404s with NotFoundRoute

### ISSUE THREAD

**Issue by alicoding** [rackt/react-router#1756]
Currently I'm using react-router client-side, but also using it to precompile all my index.html for all routes defined in routes.jsx

``` typescript
var routes = (
  <Route>
    <Route name="home" path="/en-US/"/>
    <Route name.../>
     <Route name.../>
    <NotFoundRoute .... />
  </Route>
);
```

Because I'm using Hapi, so there is a limitation in term of handling any 404s. What I used to be able in other Hapi app is just let a single `index.html` file handles any 404s pure client side, but this application is not possible because of how we setup our app, but Hapi is kind enough to allow me to use `onPreResponse` to catch any 404s any return a file.

``` js
server.ext('onPreResponse', function(request, reply) {
  if(request.response.output && request.response.output.statusCode === 404) {
    console.log(request.url.pathname)
    return reply.redirect('/?pathname=' + request.url.pathname);
  }
  return reply.continue();
});
```

Now I'm able to send 404 and preserve the route that it was requesting and let the client process there.

I was trying `willTransitionTo` to process what's coming there, but it doesn't seem to be the right approach or maybe I don't know what I'm doing here, but I can't seem to use `<NotFoundRoute/>` to handle any 404 pages at all?

What would be the best solution to handle 404s in this case?

Sorry if it's a bit confusing since it is a large code base and I'm trying to extract the most relevant bits to not confused people even more here.

**Comment by ryanflorence** [comment]
in v0.13.x I handled it like this here: `https://github.com/rackt/react-router-mega-demo/blob/master/app/server.js#L33`

we'll have decent docs for this in 1.0.
