### ISSUE TITLE
ScrollToTopBehavior with new API

### ISSUE THREAD

**Issue by gerherz** [rackt/react-router#1758]
I'm using v1.0.0-beta3 and HashHistory in my app. Everytime I click on a Link, it transitions to its URL but it then scrolls to the Link's position (similar to the browser's behavior when clicking on a link with a hash). How can I configure things in a way that, after transitioning, the browser scrolls to the top of the page?

I searched the code and docs and found ScrollToTopBehavior that's supposed to do something like this, but seems to be deprecated on the new API.

**Comment by gerherz** [comment]
I found out that if I place a breakpoint in the updateWindowScrollPosition() function, it works fine. I mean, after hitting play on the browser it scrolls to the top.

**Comment by patrickhaug** [comment]
I got the exact problem. But for me it appears, that after refresh first hit of a link works fine. Then go back, hit link again it stays on that position.

**Comment by ryanflorence** [comment]
We want to build a way smarter scroll behavior (remember individual element scroll positions, like the browser does) and that we can build it independent of the router (now that we have location state and key). We'll get to it, but for now you can get scroll to top behavior really easily:

```
let App = React.createClass({
  componentDidUpdate (prevProps) {
    if (prevProps.location.key !== this.props.location.key) {
      window.scrollTo(0, 0)
    }
  }
})

<Router>
  <Route component={ScrollTop}>
    {/* all your other routes */}
  </Route>
</Router>
```

**Comment by erosenberg** [comment]
@ryanflorence - doing this throws off all of my routes and structure of my app. Is there any way around this? Or should I add that ScrollTop component to each route?

**Comment by gaearon** [comment]
What do you mean by “throws off all of my routes and structure of my app”? All it does is wraps your routes in one extra route. Or you can even do this in your top-level route's component.

**Comment by erosenberg** [comment]
Right now I'm looping through all of my routes, and when there's another level there it throws off the looping.

```
let cloned_pages = routes.props.children.map((route, i) => {
  return React.cloneElement(route, {
      onEnter: this.handlePageTransition,
      key: 'route' + i,
   });
});
```

**Comment by gaearon** [comment]
Then wrap after looping?
