### ISSUE TITLE
Allow url path contain colon?

### ISSUE THREAD

**Issue by luodaxu** [rackt/react-router#1759]
I am using react-router for ui navigation, but in my web app, url may  contain colon for namespace structure, like http://hostname:port/app/ns1:ns2:n3.../policy
but the result turns out 
Missing "xxxx" parameter for path "/fishbowl:xxxx/policy" ,here fishbowl:xxxx is a namaspace structure
I think the react-router regards xxxxx as a parameter actually it isn't, can someone help me?

**Comment by stremlenye** [comment]
Probably you could encode colones like `dddd:tttt => dddd%3Atttt`.

**Comment by ryanflorence** [comment]
you might have to encode the colons, are there colons in your route config?

**Comment by ryanflorence** [comment]
looks good on master as you can see from the test on 408506b
