### ISSUE TITLE
Nested route rendering

### ISSUE THREAD

**Issue by omerman** [rackt/react-router#1760]
``` javascript
export default
class AppRouter extends React.Component {
	render() {
		return (
			<Router history={history}>
				<Route path="/" component={R1}>
					<Route path="/r2" component={R2}>
						<Route path="/r3" component={R3}>
							<Route path="/r4" component={R4}/>
						</Route>
					</Route>
				</Route>
			</Router>
		);
	}
}
```

v1.0.0 beta3

1) User navigates to /r2/r3 
    *(R1 is rendered then R2 and then R3 which is fine.)

2) User then navigates to /r2/r3/r4.
    *(I've noticed that the whole chain of routes is rendered again! not just R3, R4 , although they are the    only components that are about to be changed. 
Meaning that the router will call render method for R1 & R2 components as well..)

Is this the desired behavior?

**Comment by taurose** [comment]
> Is this the desired behavior?

Yeah, if a route component (and all its parents) is the same between pages, it'll be re-rendered. You need this if your render output depends on route params, pathname or other active routes.

Think of the router component as a React component that first renders `<R1><R2><R3 /></R2></R1>` and then changes its state in response to a URL change to render `<R1><R2><R3><R4 /></R3></R2></R1>`. The resulting behavior is the same.

**Comment by omerman** [comment]
First of all thank you for your answer :).
I understand what you are saying, but I must say I still don't see it as the best approach on this case.

I'll explain:

Suppose I'm on a given route A/B/C/123
lets say A needs to know about the url param change down below in the route chain.

if the route changes to A/B/C/12345,
I can't see how re-render by default A component is the solution, <b>rather then</b> agreeing on a function (callback) that can be set up on a component,
the callback would then be fired(if exists) on A & B & C(not necessarily in that order :P) and A will change it's state and if needed be re-rendered.

```javascript
class A extends React.Component{
//will be fired when a route involving A as a component is changed.
    onRouteChanged(): {
        if(...) {
            this.setState(..)
        }
    }
}
```

***I might be totally wrong here, I did just start working with react about a month ago, but for the chance my thoughts about this matter are making sense, here they are :)

**Comment by ryanflorence** [comment]
This is the entire selling point of react, "always rerender" when data changes and quit worrying about render getting called.
