### ISSUE TITLE
Documentation request -- preferred way to destroy a react router app

### ISSUE THREAD

**Issue by sthzg** [rackt/react-router#1762]
I realize this is somewhere between a question and an issue. Feel free to close it as inappropriate.

In my opinion the docs would benefit from a section describing on how to destroy a react-router component on a page (routes and render tree). On the object returned by `Router.run()` there is an undocumented method `clearAllRoutes()`, so would the following dummy code be okay to remove everything?

```javascript
var myApp = Router.run(routes, (Root) => {
  React.render(<Root/>, document.getElementById('app-container'));
});

myApp.clearAllRoutes();
React.unmountComponentAtNode(document.getElementById('app-container'))
```

**Comment by taurose** [comment]
You're looking for `myApp.stop()`. I agree that this should be documented.

`clearAllRoutes()` simply removes all routes without stopping the router. It's used by `replaceRoutes(newRoutes)` which should be used for that purpose instead.

**Comment by sthzg** [comment]
That's great, thanks. As I see [here](https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/modules/createRouter.js#L541) `stop()` is called when `<Root />` is unmounted. In that sense calling `unmountComponentAtNode(myRoot)` should be enough when the use case is to remove everything, I guess.

**Comment by taurose** [comment]
Right, I forgot about that ;)
