### ISSUE TITLE
Documentation error causing fail on iOS

### ISSUE THREAD

**Issue by slimjim777** [rackt/react-router#1763]
The example on the docs site [1] fails on iOS (both Safari and Chrome).
```
var App = React.createClass({
  render () {
    return (
      <div>
        <h1>App</h1>
        <RouteHandler/>
      </div>
    )
  }
});
```

should be

```
var App = React.createClass({
  render: function () {
    return (
      <div>
        <h1>App</h1>
        <RouteHandler/>
      </div>
    )
  }
});
```

[1] https://rackt.github.io/react-router/

**Comment by gaearon** [comment]
The docs use [ES6 concise method syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions).
You can use [Babel](http://babeljs.io) to transpile ES6 and JSX to ES5 that browsers understand.

**Comment by slimjim777** [comment]
Thanks for the explanation.

Whilst I understand what your saying, I think the use of the ES6 concise method syntax in that one class is going to trip up other newbie users. The docs page does not mention ES6 or Babel, and there is only that single class that uses the concise approach.

For the sake of consistency, I think that it would help newbie users to use a single approach throughout the code examples. Also, removing the need for Babel to get up-and-running would help new users trying out react-router.
