### ISSUE TITLE
Global transition event handler?

### ISSUE THREAD

**Issue by benvinegar** [rackt/react-router#1764]
Something like:

```js
var router = require('react-router');

router.onTransition(function (transition, component) {
  if (sessionExpired)
    transition.redirect('/login');
});
```

The closest example of achieving this is from [the react-router auth example](https://github.com/rackt/react-router/blob/0.13.x/examples/auth-flow/app.js), which uses inheritance to reuse a `willTransitionFrom` declaration on every routed component.

**Comment by stremlenye** [comment]
In the `beta-x` versions there are `onEnter` hook which could be applied for any `Route` component, for example:
```jsx
<Route component={ApplicationContainer} onEnter={requireAuth}>
  <Route componen={HomePage} path="/home" />
  …
</Route>
```
Thats probably what you want.
http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Route

**Comment by ryanflorence** [comment]
in `v0.13.3` your change handler is just `Router.run(routes, changeHandler`.

On master its `<Router onUpdate={fn}/>`
