### ISSUE TITLE
matchPattern doesn't handle params with % very well

### ISSUE THREAD

**Issue by mfrye** [rackt/react-router#1766]
The app I'm building has a lot of company names with unfriendly url params. I didn't choose to do this, I'm just working with what was given to me...

Ex. of company names and final urls
- Name: "CADENCE DESIGN SYSTEM INC NOTE 2.625% 60"
    - Encode Url: /company/CADENCE%20DESIGN%20SYSTEM%20INC%20NOTE%202.625%25%2060
- Name: "TRULIA INC NOTE 2.750%121 ADDED"
    - Encoded Url: /company/TRULIA%20INC%20NOTE%202.750%25121%20ADDED

These are valid encoded urls, but once decodeURIComponent is run several times on it, it eventually breaks. This line is the problem https://github.com/rackt/react-router/blob/master/modules/PatternUtils.js#L94. 

It tries to decode an already decode string, "company/CADENCE DESIGN SYSTEM INC NOTE 2.625% 60", which throws a uri malformed error.

I spent some time going through the code, but I'm not sure of the best way to fix this.

**Comment by ryanflorence** [comment]
looks good on master 9fe8abf
