### ISSUE TITLE
Make route render each time

### ISSUE THREAD

**Issue by jjvattamattom** [rackt/react-router#1767]
Heres what I want: I click the link to /messages, it calls messages from server and renders it. When I click the link again, it again calls messages from server.

Is there a way to notify the component so that it can "reload" stuff?

I want to retain the static HTML behavior that clicking /foo while at /foo reloads it.

**Comment by ryanflorence** [comment]
This exactly what happens on master.

When at `/messages`, click a link to `/messages` and ``componentWillReceiveProps` gets called on the route component there.
