### ISSUE TITLE
Info for npm package (v0.13.3) shows README from master (v1.0.0-beta3)

### ISSUE THREAD

**Issue by jsayol** [rackt/react-router#1770]
This can cause some confusion because the "What's it look like?" section has an example using 'react-router/lib/BroserHistory'.

    $ npm v react-router version
    0.13.3
    $ npm v react-router readme|grep BrowserHistory
    import { history } from 'react-router/lib/BrowserHistory';

Or just check https://www.npmjs.com/package/react-router

**Comment by jsayol** [comment]
This is probably why so many people have been complaining about the missing BrowserHistory, by the way.

**Comment by ryanflorence** [comment]
we broke from our conventions with the 1.0 branch, we'll get this stuff resolved and not make the mistake of a long-lived branch again.
