### ISSUE TITLE
Can't navigate to routes with encodeURIComponent encoded slashes with if using nested routes

### ISSUE THREAD

**Issue by timoxley** [rackt/react-router#1771]
On beta3, consider the following route structure:

```js
    <Route component={Parent}>
      <Route path='/app/:name' component={Child} />
    </Route>
```
Using this then navigating to `/apple%2Fbanana`, i.e.

```js
'/' + encodeURIComponent('apple/banana')
```
You will get `Warning: Location "/apple%2Fbanana" did not match any routes`

![image](https://cloud.githubusercontent.com/assets/43438/9520901/c45b967c-4cfd-11e5-9483-25e40b156303.png)

BUT if one removes the nesting, it will work as expected

```js
      <Route path='/app/:name' component={Child} />
```

Note it appears to work with other encoded chararcters, just not with a url-encoded `/`.

----

Full example code:
```js
import React from 'react'
import Router, { Route } from 'react-router'

import BrowserHistory from 'react-router/lib/BrowserHistory'

class Parent extends React.Component {
  render() {
    return <div> {this.props.children} </div>
  }
}

class Child extends React.Component {
  render() {
    const {params} = this.props
    return <h1>{params.name}</h1>
  }
}

React.render(
  <Router history={new BrowserHistory()}>
    <Route component={Parent}>
      <Route path='/app/:name' component={Child} />
    </Route>
  </Router>
, document.getElementById('root'))
```

edit: I removed the `/` route from the example as it isn't required to trigger the bug

**Comment by ericlynnpeterson** [comment]
In your example, are you expecting to run `<Route path="/" component={Child} />`?  If that's the case, maybe you could set it up as a default route using `<Route path="*" component={Child} />`?

**Comment by timoxley** [comment]
@elpete oh no, I only put that in because of "should always have a default route". I guess I should pull it out of the example as it's not required for triggering the bug.

**Comment by elpete** [comment]
So, to clarify, what route are you expecting to run when you navigate to `/apple%2Fbanana`?

**Comment by ryanflorence** [comment]
Ignoring your route is `app/:name` not `apple/:name`

```js
// should not match because encoded slashes are treated differently on purpose (so people can have dynamic segments with slashes, iirc)
'/' + encodeURIComponent('apple/banana')`

// should match
'/apple/banana'
```

Working as designed unless @mjackson knows something I don't.
