### ISSUE TITLE
Active link is not updating

### ISSUE THREAD

**Issue by roundrobin** [rackt/react-router#1772]
I used the Link component in my app along with the `activeClass` property. 

After clicking a couple of links, the `activeClass` class is not updating anymore. 

Can you think of a reason why that could happen?

**Comment by gaearon** [comment]
Maybe because of https://github.com/rackt/react-router/issues/470?

**Comment by mjackson** [comment]
I believe this is fixed by #1821

**Comment by chcald** [comment]
I put this in my nav component and it worked

export default connect(mapStateToProps, null, null, {
pure: false
})(TodoApp)
