### ISSUE TITLE
Dynamic nested Routes generation ?

### ISSUE THREAD

**Issue by iroy2000** [rackt/react-router#1774]
Hi all,

I have a question about generating nested routes on the fly.  I'm able to generate routes on the fly if it is not nested. 

Let's look at the following example -

```js
var routes = [
    {
        name: 'about',
        path: '/about',
        handler: './pages/test/index.jsx',

        // this is a nested routes
        routes: [
            {
                name: 'me',
                path: 'me',
                handler: './pages/test/me'
            },
            {
                name: 'you',
                path: 'you',
                handler: './pages/test/you'
            }
        ]
    }
];
```

And I try to do the followings -

```js
var ExtraRoutes =  [];

_.each(routes, function(route) {
    ExtraRoutes.push(<Route name={route.name} path={route.path} handler={require(route.handler)} addHandlerKey={true} >);

        _.each(route.routes, function(route) {
            ExtraRoutes.push(<Route name={route.name} path={route.path} handler={require(route.handler)} addHandlerKey={true} />)
        });

        ExtraRoutes.push(</Route>);
});
```

But looks like my syntax is not correct ...  So how to inject those nested routes into the parent route ?

And my end goal is to generate the following

```js
<Route name="about" handler={require('./pages/test')}>
          <Route name="me" handler={require('./pages/test/me')}/>
          <Route name="you" handler={require('./pages/test/you')}/>
</Route>
```

Any help would be appreciated, thanks.

**Comment by ryanflorence** [comment]
in 0.13 there is an `addRoutes` method on your router.

**Comment by iroy2000** [comment]
Do you have an example I can reference to ?  I don't see this documented in http://rackt.github.io/react-router/

**Comment by knowbody** [comment]
seems like there are no docs about it but you can have a look [here](https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/build/lib/createRouter.js#L159-L168) on what to pass to the `addRoutes`
