### ISSUE TITLE
Router.match just got scraped?

### ISSUE THREAD

**Issue by coodoo** [rackt/react-router#1775]
I was wondering if there's a way to know that a request will be matched by one of react-router's rule, from document there's this method named `Router.match()` doing just that, but judging from the latest bit in the `1.0-beta3` branch, it's gone.

So what's the official way to do that? Thanks.

**Comment by ryanflorence** [comment]
give us a couple days and we'll have this: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md
