### ISSUE TITLE
Run Router on server synchronously

### ISSUE THREAD

**Issue by alexfedoseev** [rackt/react-router#1777]
Hi @mjackson & @ryanflorence,

@justin808 and I are working on [gem for Rails](https://github.com/shakacode/react_on_rails) which implements server-side rendering. It works with React & Redux already, but I faced the problem with React Router integration (`1.0.0-beta3`). The issue is actually with limitations of ExecJS. Here is what I have:

```js
// This function should return React Component 
// to render it to string on server
export default (path, query, routes) => {
  const location = new Location(path, query);

  Router.run(routes, location, (error, state, transition) => {
    // Only here we can start rendering something on server
    // Inside Node we handle it like this:
    const html = React.renderToString(<Router location={location} {...state} />);
    res.send(html);
  });

  // But I need to return Router Component synchronously 
  // Is there any chance to get the sync API method to make it this way?
  const routerRunResults = Router.runSync(routes, location);
  const { error, state, transition } = routerRunResults;
  return (
    <Router location={location} {...state} />
  );
}
```

**Comment by ryanflorence** [comment]
The api will shift a bit in the next couple days around server rendering (https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md).

After it does we'd accept a `matchSync` pull request.

**Comment by alexfedoseev** [comment]
Great, thanks!

/cc: @justin808

**Comment by alexfedoseev** [comment]
@ryanflorence Is it safe to start this PR with `1.0.0-rc3` or there might be some changes in server-side API?

**Comment by taion** [comment]
I wonder if this needs to be part of RR specifically though? Having to match synchronously seems like a very specific thing to have to do.

Would it make more sense to build this on top of `match` in your library?

**Comment by alexfedoseev** [comment]
@taion Well, it would be perfect, but I have no idea how to achieve it in ExecJS environment. I can't use `async/await` / `generators`, Event Loop is not supported, and I see no way to get matched data from async api in synchronous environment. If you can give me some direction / idea on this, I'd prefer to keep it inside lib and don't touch `react-router`'s api.

**Comment by taion** [comment]
All of the stuff we do is fully Zalgo-fied. If you're not using async routes, `match` should invoke its callback synchronously, so you can do:

```js
let results;
match(foo, bar => results = bar);
renderWith(results);
```

**Comment by alexfedoseev** [comment]
@taion Thanks, I'll try it this weekend!

**Comment by knowbody** [comment]
any luck with this PR? let us know if you need help @alexfedoseev

**Comment by alexfedoseev** [comment]
@taion @knowbody It worked, thanks a lot for help!
