### ISSUE TITLE
Documentation/Missing feature for nested components and static.willTransitionTo

### ISSUE THREAD

**Issue by hackhat** [rackt/react-router#1778]
I have this nested structure:

 - App
   - Page/:page handler=Page
   - Other

And both App, and Page have static.willTransitionTo then:

 A) The first time I arrive to the page both App and Page static.willTransitionTo will be called;
 B) Now when I move from Page/1 to Page/2 only the Page static.willTransitionTo will be called;
 C) If I change from Page/2 to Other both App and Page static.willTransitionTo will be called;

I would expect in scenario (B) the App's static.willTransitionTo to be called too because of (C) and also because that is what the docs says:

> Called when a handler is about to render, giving you the opportunity to abort or redirect the transition. You can pause the transition while you do some asynchonous work and call callback(error) when you're done, or omit the callback in your argument list and it will be called for you.

Now the question is what is the expected behavior and the documentation should include this information too.

Thanks

Related to: https://github.com/rackt/react-router/issues/1630

**Comment by ryanflorence** [comment]
which version?

**Comment by hackhat** [comment]
v0.13.3

**Comment by ryanflorence** [comment]
every route component that was not already mounted should get willTransitionTo, and every route component that was mounted but is no longer mounted should get a willTransitionFrom.

the code base has moved a long way from this so I need to close it, but if you feel like digging into the 0.13.x branch to fix anything you might find we can merge and cut a release.
