### ISSUE TITLE
this.context.router undefined in IE10 on extended class in 1.0.0-beta3

### ISSUE THREAD

**Issue by MattDiMu** [rackt/react-router#1779]
This issue seems related to the already close #1281. I'm using ES6-Syntax and fail to access this.context.router, but only in IE10 and IE9.

My code looks like this

basePage.jsx
```js
export default class BasePage extends React.Component {
...
}
React.Component.contextTypes = {
	router: React.PropTypes.object.isRequired
};
```

searchPage.jsx
```js
export default class SearchPage extends BasePage {
...
  render() {
    console.log(this.context.router); //this.context is undefined
  }
}

```

**Comment by piratus** [comment]
This is IE10 and below issue, not react-router's.
You can read about it here: http://babeljs.io/docs/advanced/caveats/#classes-10-and-below-

**Comment by MattDiMu** [comment]
thx, you're right!

**Comment by fdidron** [comment]
Looks like th link is broken, @MattDiMu can you share pointers on who you fixed this issue ? Thanks !

**Comment by MattDiMu** [comment]
@fdidron The page has moved to: https://babeljs.algolia.com/docs/advanced/caveats/

Basically it says that the transpiled code won't work in IE10 and below, so you should avoid extending or use https://babeljs.algolia.com/docs/advanced/transformers/spec/proto-to-assign/ as workaround

**Comment by fdidron** [comment]
Many thanks !
On Thu, Feb 25, 2016 at 11:25 PM Matthias Müller <notifications@github.com>
wrote:

> @fdidron <https://github.com/fdidron> The page has moved to:
> https://babeljs.algolia.com/docs/advanced/caveats/
>
> Basically it says that the transpiled code won't work in IE10 and below,
> so you should avoid extending or use
> https://babeljs.algolia.com/docs/advanced/transformers/spec/proto-to-assign/
> as workaround
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactjs/react-router/issues/1779#issuecomment-188806958>
> .
>
-- 
Kind regards,

*Florian Didron*
Nakabayashi bldg 2F, 2-11 Kandatacho, Chiyoda-ku,
Tokyo 101-0046, Japan http://www.111studio.jp
Tel: +81-(0)50-5830-7183 Fax: +81(0)50-3488-7768

**Comment by ShirleyWang822** [comment]
It seems the link is broken, @MattDiMu can you help me with the same issue above, thanks a lot.
