### ISSUE TITLE
Install v1.0.0-beta3 but get beta2 version

### ISSUE THREAD

**Issue by tachang** [rackt/react-router#1780]
npm install https://github.com/rackt/react-router.git#v1.0.0-beta3 --save

cat package.json gives me:

```
  "name": "react-router",
  "version": "1.0.0-beta2",
```

**Comment by tachang** [comment]
Would this issue result in not being able to require the library?

**Comment by igl** [comment]
You should have beta3 even if the package.json doesn't say so.
It seems like the package.json is just not correct at this tag: https://github.com/rackt/react-router/blob/v1.0.0-beta3/package.json

**Comment by ryanflorence** [comment]
npm install react-router@beta should get you the latest.
