### ISSUE TITLE
Is there an API for getting the current route object based on the state?

### ISSUE THREAD

**Issue by Teaflavored** [rackt/react-router#1781]
I'm trying to grab the current route (React Object) from the state object so I can perform the necessary data fetching on the server side. Right now the state object contains an array of 2 routes whenever I access an url. The first index is always the top level route, and the second index contains the current route. I'm wondering if there's another way to access the current route without using state.routes[1]. The context behind grabbing the route is that I've defined static loadActions on the handler objects. This is how my server looks right now

```
server.js
ReactRouter.run(routes, req.path, function (Root, state) {
    var currentHandler  = state.routes[1].handler;
    var renderReactToString = function () {
         //renders react component as string and insert into html
    }
    if (currentHandler.loadAction) {
         //async fetch data -> renderReactToString()
    } else {
          renderReactToString();
    }
}
```

**Comment by taurose** [comment]
> I'm wondering if there's another way to access the current route without using state.routes[1]

There is no *single* active route object. The router always derives a set of routes from the URL and your route config. Instead of `state.routes[1]` which will only work with routes on the second level, you can do `state.routes[state.routes.length - 1]` to always get the innermost route, or loop over it to take all active route objects into account:

```js
var loadActions = state.routes.reduce((all, route) => {
  if(route.handler.loadAction) 
    all.push(route.handler.loadAction);
  return all;
}, []);

if(loadActions.length > 0) {
  // execute loadActions however you want (parallel, series)
} else {
  renderToString();
}
```

**Comment by Teaflavored** [comment]
I see, thanks, I'll take some time to read the source code too, been just trying it out and hacking something together.
