### ISSUE TITLE
1.0.0-beta3: History back/forward always render 3 times

### ISSUE THREAD

**Issue by xpepermint** [rackt/react-router#1782]
Basic example:

```js
import React from 'react';
import ReactDom from 'react-dom';
import Router from 'react-router';
import BrowserHistory from 'react-router/lib/BrowserHistory';
import routes from './routes';

ReactDom.render(<Router history={new BrowserHistory} children={routes}/>, document.getElementById('html'));
```
```js
import React from 'react';
import {Link} from 'react-router';

class App extends React.Component { // MAIN ROUTE
  render() {
    console.log('location', this.props.location); // THIS
    return (
      <div>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/stats">Stats</Link></li>
          <li><Link to="/login">Login</Link> | <Link to="/logout">Logout</Link></li>
          <li><Link to="/projects">Projects</Link></li>
        </ul>
      </div>
    );
  }
}

export default App;
```

When using browser `back` and `forward` buttons `console.log('location', this.props.location);` is always rendered 3 times but navigation with `<Link>` elements shows only one.

**Comment by ryanflorence** [comment]
on master I see multiple renders depending on which route you're going to, but usually just one. With a static route config this seems unnecessary, but digging into the code might reveal otherwise. Mind creating a failing test?

**Comment by ryanflorence** [comment]
this was caused by `isTransitioning` prop that got rendered down, we don't do that anymore, but we may again in the future, it shouldn't be anything to worry about, "always rerender".

If we bring it back, and there's evidence that "always rerender" is not okay for the router (meaning its noticeable in the UI), we can worry about it.

**Comment by xpepermint** [comment]
ok, cool
