### ISSUE TITLE
Upgrde Guide / What makes 1.0 better than 0.13?

### ISSUE THREAD

**Issue by AsaAyers** [rackt/react-router#1784]
Coming from 0.13 I see there are many changes, but it's not always obvious how these changes are improving things.

Specifically in 1.0 we lose route names and `<Link to="route_name" params={{ ... }} />`. I trust this was done for a reason, but from here it just looks like losing functionality.

I see `<RouteHandler />` has been removed in favor of passing the children down as props. I'm not sure how you would convert existing code that might have passed additional props to `<RouteHandler />`

**Comment by SpainTrain** [comment]
@AsaAyers For your 2nd question, see the discussion at https://github.com/rackt/react-router/issues/1531

**Comment by bunkat** [comment]
An update the upgrade guide would be very helpful.  I'm starting to go through the conversion process from 0.13 to 1.0 and it isn't clear if I'm following best/expected practices.  Also, is there a replacement for the mixins yet?  I didn't see any information about that.

**Comment by loopmode** [comment]
Maybe i just misunderstood something, but it seems to me as if beta4 forces us into using mixin, not providing any context property anymore - is this assumption correct?

**Comment by JEGardner** [comment]
If so, means we can't use ES6 classes properly...

**Comment by gaearon** [comment]
Why 1.0: https://github.com/rackt/react-router/pull/1158 (rather outdated)
Why no named routes: https://github.com/rackt/react-router/issues/1514
Transferring props to `children`: https://github.com/rackt/react-router/issues/1531

**Comment by gaearon** [comment]
>If so, means we can't use ES6 classes properly...

>Maybe i just misunderstood something, but it seems to me as if beta4 forces us into using mixin, not providing any context property anymore - is this assumption correct?

Context can't go away—it's what makes the mixin work in the first place.
The context property just changed from `router` to `history`.
[See here.](https://github.com/rackt/react-router/blob/d1b1e247d22f42f1cf1d4e9a8a91fd21631db65a/modules/Navigation.js#L26-L40)

**Comment by loopmode** [comment]
@gaearon ah, thanks!

**Comment by globexdesigns** [comment]
For what it's worth I've started a migrate doc here: https://github.com/rackt/react-router/pull/1601

**Comment by ryanflorence** [comment]
Sorry for not having clean explanations for this stuff, we will have a grand upgrading guide for 0.13 -> 1.0 but have focused our energy on the code, not docs until then. Stick with 0.13 until then if you don't feel like code diving :P
