### ISSUE TITLE
Link Component in version 1.0.0 beta 3 not working

### ISSUE THREAD

**Issue by meonam1712** [rackt/react-router#1786]
I am using react-router 0.13.3 for my web project. Now i want to convert my codes to react-router 1.0.0 beta 3. And i meet many problems when changing.
One of those problems is using Link component
 < Link to ="route-name" params={} />  
When i click on it, it throw errors :Warning: Location "route-name" did not match any routes
But i make sure that the "route-name" already exists in my routes.jsx
What happened ? Please help me!

**Comment by chentsulin** [comment]
Route's `name` prop is removed. Use `path` as Link's `to` value instead.

**Comment by josebalius** [comment]
@chentsulin if i may ask, why was did this change? I always thought it was a good feature to link to routes by name in case the path changed later on.

**Comment by chentsulin** [comment]
See some disuss [here](https://github.com/rackt/react-router/issues/1514#issuecomment-122011215)
