### ISSUE TITLE
What happened to Location.js?

### ISSUE THREAD

**Issue by fingermark** [rackt/react-router#1789]
What happened to https://github.com/rackt/react-router/blob/v1.0.0-beta3/modules/Location.js in beta4?

It was being used in a lot of places because of http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Server%20Rendering

**Comment by chentsulin** [comment]
it was moved to independent module https://github.com/rackt/history

https://github.com/rackt/history/blob/master/modules/createLocation.js#L19

**Comment by fingermark** [comment]
Thanks, maybe we can use this ticket to track the doc updates.

**Comment by SpainTrain** [comment]
> Thanks, maybe we can use this ticket to track the doc updates.

:+1:

**Comment by lancetw** [comment]
@chentsulin createLocation is incompatible with original Location.js :(

**Comment by mjackson** [comment]
Thanks for the link, @chentsulin ! :)

**Comment by AlexHandy1** [comment]
This is still a problem for me following this basic intro tutorial >> https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4 

Tried to refactor and use history module but getting an "TypeError: undefined is not a function" error from the below server.jsx set-up. It is all npm installed correctly (e.g. I get a [Function: createLocation] when console.log the createLocation imported).
Unclear to me what the correct parameters are that I need to pass in to the function

````
import express from 'express'
import React      from 'react';
import { Router } from 'react-router';

import createLocation from 'history/lib/createLocation'
import routes from 'routes';

const app = express();

app.use((req,res) => {
  let location = createLocation('/', { the: 'state' })  // const location = createLocation(req.path, req.query);
  Router.run(routes, location, (err, routeState) => {
    if (err) return console.error(err);
    if (!routeState) return res.status(404).end('404');


    const InitialComponent =(
      <Router {...routeState}/>
    );

    const componentHTML = React.renderToString(InitialComponent);

    const HTML = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Isomorphic Redux Demo</title>
      </head>
      <body>
        <div id="react-view">${componentHTML}</div>
        <script type="application/javascript" src="/bundle.js"></script>
      </body>
    </html>
    `;

    res.end(HTML);
  });
});

export default app;
````

**Comment by knowbody** [comment]
@AlexHandy1 Ryan wrote [Server Rendering](https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md) docs yesterday, have a look there.

**Comment by ayhoung** [comment]
@AlexHandy1 were you able to refactor successfully in the end? @knowbody your link points to a 404

**Comment by chentsulin** [comment]
Server Rendering doc has been moved to here: https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md

**Comment by AlexHandy1** [comment]
@ayhoung - thanks for following up, I didn't get round to refactoring as decided to go back to an earlier version of react-router and just work from that given it was an experimental app.

**Comment by knowbody** [comment]
@chentsulin thanks for the new link

**Comment by halt-hammerzeit** [comment]
still 404, lol
so, what's the easy fix?

**Comment by jitchavan** [comment]
@knowbody  we are previously using 1.0.0-beta3. we are now trying to upgrade to 2.0.0-rc4 in which browserHistory and hashHistory are again introduced. is this  right way to use  browserHistory and hashHistory from  2.0.0-rc4 for 1.0.0-beta3 's  BrowserHistory and HashHistory.

can we use below code 
```
import BrowserHistory from 'react-router/lib/browserHistory';
import HashHistory from 'react-router/lib/hashHistory';
```
instead of this :   
```
import BrowserHistory from 'react-router/lib/BrowserHistory';
import HashHistory from 'react-router/lib/HashHistory';
```
but we are still facing below issue.
```
Error: Cannot find module 'react-router/lib/Location'
```
for below code.
```
var Location = require('react-router/lib/Location');
  var location = new Location(req.path, req.query);

  try {
    Router.run(routes(), location, function(e, i, t) {
      var str = React.renderToString(
                  React.createElement(Router, i));

      if(isRTL) {
        res.send(rtl.replace(new RegExp('{container}', 'g'), str));
      } else {
        res.send(ltr.replace(new RegExp('{container}', 'g'), str));
      }
    });
  } catch(e) {
    return next();
  }
```

didn't find any way to make it work.

**Comment by knowbody** [comment]
@jitchavan please have a look at the [2.0 upgrade guide](https://github.com/rackt/react-router/blob/95a0237b7f43d981128a60c2477acffad12b4034/upgrade-guides/v2.0.0.md#using-history-with-router) and also at the [Histories](https://github.com/rackt/react-router/blob/b9b21cbb32e6fbbf0e703360d0c7eaea2db41770/docs/guides/basics/Histories.md#histories) docs.
