### ISSUE TITLE
RouteNotFound in version 1.0 beta 3

### ISSUE THREAD

**Issue by davidlashlee** [rackt/react-router#1790]
is there a way of handling when users input an incorrect path to redirect to a default 404 page?

RouteNotFound seems to be avaliable in 0.13.0 but I see no mention of it in the 1.0 beta documentation

**Comment by eXtreme** [comment]
Just write `<Route path="*" component={NotFound} />` as last route and it will catch all non-existing routes and render your 404 component. But yea, it is missing from the docs, I found it in examples: https://github.com/rackt/react-router/blob/master/examples/master-detail/app.js#L157

**Comment by mjackson** [comment]
Thanks for the comment here, @eXtreme ! :)
