### ISSUE TITLE
[1.0.0-beta4] Server Rendering: `useRoutes` does not accept jsx routes

### ISSUE THREAD

**Issue by SpainTrain** [rackt/react-router#1793]
The new approach for server side rendering is using `useRoutes` (https://github.com/rackt/react-router/blob/v1.0.0-beta4/modules/__tests__/serverRendering-test.js#L32).  However, the `routes` property of the options only accepts the plain object type of the routes config, not the jsx type.  For me at least, this violated "least surprise".  It seems reasonable that `useRoutes` would accept any valid type of route config.

For anyone encountering this issue, here's how to handle it:

```js
...
import {createRoutes} from 'react-router/lib/RouteUtils';
import myJsxRoutes from './routes';
let routes = createRoutes(myJsxRoutes);
...
// The rest of the code is just like https://github.com/rackt/react-router/blob/v1.0.0-beta4/modules/__tests__/serverRendering-test.js
let history = useRoutes(createHistory)({ routes });
let location = createLocation('/');

history.match(location, function (error, state) {
    let string = React.renderToString(
        <RoutingContext history={history} {...state} />
    );
```

**Comment by MoOx** [comment]
Got the same "bad" surprise.

**Comment by MoOx** [comment]
Also, it seems that `useRoutes` doesn't handle:

- nested routes (which is convenient to wrap some routes by a component, for layout purpose)
- glob path

This is very confusing and looks like a regression from beta3 (cause Router.run() where able to consume any common `<Router><Route>` structure, but this new way doesn't at all). Have to get back to beta 3 because 2h trying to make my previous setup with beta 4 wasn't enough. Or maybe I am missing something _obvious_...

**Comment by SpainTrain** [comment]
@MoOx want to share your route config?  My nested routes appear to be working, but I am not using glob path.  Perhaps the issue lies in using both?

**Comment by timdorr** [comment]
It looks like `routes` is [expected to be an array](https://github.com/rackt/react-router/blob/master/modules/matchRoutes.js#L110) ([also here](https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L72)). Are you sure you don't just have to `return [<Route>];` from your routes file?

**Comment by timdorr** [comment]
Oh wait, my bad. It used to [run `createRoutes` for you](https://github.com/rackt/react-router/blob/v1.0.0-beta3/modules/RoutingUtils.js#L93), which would convert it automatically. 

Looks like you can just [use `createRoutesFromReactChildren`](https://github.com/rackt/react-router/blob/master/modules/RouteUtils.js#L90-L91) to get the same result.

**Comment by dlwalsh** [comment]
Using `createRoutesFromReactChildren` works for me, but I'm finding it doesn't populate the active classes in the nav.

**Comment by SpainTrain** [comment]
> Looks like you can just use createRoutesFromReactChildren to get the same result.

I think `createRoutes` is better because if for some reason you change your routes file to export a plain object type it will continue to work.  `createRoutes` accepts any valid type of route config.

As shown in the example it's certainly possible to use these utility functions to get server side rendering working.  It's just my opinion that having some bits of the public API accept the jsx type and some not violates [least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

> the classes get populated client side, but not server side.

Sounds like a definite candidate for its own issue.  That's almost certainly a bug.

**Comment by dlwalsh** [comment]
Thanks. I'll create a new issue.

**Comment by timdorr** [comment]
Just as a hint for others, here's what I'm doing server side without any problems. I've got these imports:
```js
import createHistory from 'history/lib/createMemoryHistory';
import createLocation from 'history/lib/createLocation';
import Router from 'react-router';
```
and later on in my request handler:
```js
const location = createLocation(req.originalUrl);
const history = createHistory({entries: [location]});
const routes = createRoutes();
const router = <Router history={history} children={routes} />;

res.render(template, {
  content: ReactDOM.renderToString(router)
});
```
I haven't yet gotten to handling redirects, but it should just be a matter of setting up the right transition hooks. I'll update whenever I get to that.

**Comment by SpainTrain** [comment]
@timdorr is there a benefit to that approach rather than the way the [server rendering test](https://github.com/rackt/react-router/blob/v1.0.0-beta4/modules/__tests__/serverRendering-test.js#L35) works?

**Comment by timdorr** [comment]
Yes, because `Router` [does a lot of the heavy lifting for you](https://github.com/rackt/react-router/blob/master/modules/Router.js#L48-L62). Also, it's a lot cleaner (two props are needed, that's it) and makes use of only public APIs. `RouterContext` is arguably private because it's [not exported](https://github.com/rackt/react-router/blob/master/modules/index.js).

**Comment by SpainTrain** [comment]
Makes sense, thanks.  I may have to update my code.

Follow on q: Is the `createRoutes` you are calling `RouteUtils.createRoutes`?  Was it meant to be given a route object?

**Comment by timdorr** [comment]
It's my own route creation function so I can shove them in their own file. It just returns some `Route` JSX.

**Comment by SpainTrain** [comment]
Seems reasonable, so perhaps this is just a documentation issue.

**Comment by ryanflorence** [comment]
Server rendering is going to look like this, but the code isn't there. Will be this week.: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

**Comment by MoOx** [comment]
@ryanflorence any issue we can track ?
