### ISSUE TITLE
active class is set twice, although it should just be set once

### ISSUE THREAD

**Issue by cglantschnig** [rackt/react-router#1794]
Problem is if I have 2 routes, where one route has the same route like another one just with some letters more and when I navigate to that one, both routes get the active class set.
Here in code:

First the place I define the routes
```javascript
React.render((
  <Router history={history}>
      ...
      <Route path="portfolio/product" component={ Product } />
      <Route path="portfolio/productname" component={ Productname } />
      ...
  </Router>
), document.getElementById('app-container'));
```
and next the place I have a navigation, made with the Link Component
```javascript
<Link to="portfolio/product">Product</Link>
<Link to="portfolio/productname">Productname</Link>
```

Since this are product names, I cant change the names there. Currently when I click on product only product gets the active class, but when I click on productname I get product and productname set as active

**Comment by mjackson** [comment]
This is fixed in beta4.
