### ISSUE TITLE
The Link component should allow onTouchTap to be used as well as onClick

### ISSUE THREAD

**Issue by ccapndave** [rackt/react-router#1795]
This allows you to circumvent the 300ms delay on iOS

**Comment by ryanflorence** [comment]
onTouchTap isn't an even the DOM or React understand. You can build your own link that works with whatever plugin you've got going on

**Comment by ccapndave** [comment]
As I understand it this event is going to be included in React 1.0 via a plugin (and is currently implemented by https://github.com/zilverline/react-tap-event-plugin).  Certainly I could make a custom component, but since it would be a carbon copy of Link just with onClick changed to onTouchTap I thought it might be nice if it was configurable.

**Comment by ccapndave** [comment]
In case anyone else needs this functionality there is an updated `Link` component at https://github.com/ccapndave/react-router-link
