### ISSUE TITLE
_k parameter in route on v1.0.0-beta4

### ISSUE THREAD

**Issue by filiptc** [rackt/react-router#1797]
We just updated to beta4 and the param _k=6wznho corresponding to the location.key shows appears to show up in every route.

Is this a bug or is there a to-be-documented feature to disable this?

**Comment by malte-wessel** [comment]
react-router now uses [rackt/history](https://github.com/rackt/history) under the hood, have a look here [Hash History Caveats](http://rackt.github.io/history/stable/HashHistoryCaveats.html).

**Comment by jdelight** [comment]
@filiptc I solved this by switching to browser history, something like:

```
import createHistory from 'history/lib/createBrowserHistory';
...
ReactDOM.render(<Router children={routes} history={createHistory()}/>, document.getElementById('b-main'));
```

**Comment by mjackson** [comment]
Thanks for the link to the docs, @malte-wessel :)

**Comment by broberts4** [comment]
Could you please elaborate on what's required to use BrowserHistory?

I've been trying various ways to get this w/o success.

**Comment by broberts4** [comment]
I'm guessing that my confusion was mainly from the [doc](https://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Overview) showing an import of 'react-router/lib/HashHistory'. The comment above that line indicates importing only the function needed, which makes more sense (i.e., 'history/lib/createBrowserHistory' in my case.

**Comment by Download** [comment]
[1.0 docs](https://github.com/rackt/react-router/blob/v1.0.0/docs/guides/basics/Histories.md) for future reference (this issue ranks high in Google)
