### ISSUE TITLE
[1.0.0-beta4] How to use transitionTo?

### ISSUE THREAD

**Issue by olivere** [rackt/react-router#1798]
Hi!

First, thanks for react-router!

I'm struggling with `transitionTo`. In [1.0.0-beta3](http://rackt.github.io/react-router/tags/v1.0.0-beta3.html) it used to have the signature:

```js
transitionTo(pathname, query, state)
```

As far as I can see, this has changed in 1.0.0-beta4 to:

```js
transitionTo(nextLocation)
```

What is the correct way to pass e.g. query and state now with beta4?

Cheers,
Oliver

**Comment by olivere** [comment]
Is [this](http://rackt.github.io/history/stable/QuerySupport.html) the way to go?

**Comment by jdelight** [comment]
@olivere where are you seeing `transitionTo(nextLocation)`? Looks the same as in 1.0.0-beta3 to me:
https://github.com/rackt/react-router/blob/master/modules/Navigation.js#L32

**Comment by olivere** [comment]
@jdelight Whoops. Okay, here's what happened. I'm using ES6 classes and use `contextTypes` to get access to `history`(formerly `router`). So I looked there and found [`transitionTo(nextLocation)`](https://github.com/rackt/history/blob/master/modules/createHistory.js#L130). And this is the `transitionTo(...)` method is exposed via `context`. I didn't recognize that `transitionTo` is also available in `Navigation.js` as well--which isn't quite accessible with ES6 classes. Am I the only one who finds this confusing?

**Comment by chentsulin** [comment]
Now, I use below to get this work:

```
history.pushState(null, path);
```

some source as reference: https://github.com/rackt/history/blob/master/modules/createHistory.js#L157

**Comment by olivere** [comment]
@chentsulin Thanks. Yes, that's what I'm using now, too. Works fine, and I'll be okay with it. Question is: Is this the way react-router wants me to handle transitions? With 1.0.0 on the horizon, I think it's time to push for stability.

**Comment by jdelight** [comment]
@olivere makes sense - I used mixins and specifically the Navigation mixin if a component needs access to `transitionTo`. Most components are using ES6 Classes but I revert to `React.createClass` when needed - sounds like your approach and @chentsulin allows you to stay with Classes though.

**Comment by ryanflorence** [comment]
the stuff on context isn't public API, so be careful :)

**Comment by zwily** [comment]
@ryanflorence - what's the right way to use transitionTo when using ES6 classes then?

**Comment by robotvert** [comment]
+1 , what's the correct way to use such functions using ES6 classes?
`v1.0.0-rc1` here, renamed `router` to `history` and having the same issue here.

**Comment by cabhishek** [comment]
@richardsabow What was your solution to get it working? I am getting the same error with `ES6, react-router 2.3 and react 15.0.1`.
