### ISSUE TITLE
isActive method check for homepage which path is "/"

### ISSUE THREAD

**Issue by web2style** [rackt/react-router#1800]
How can I check for active homepage route:

```
<Route path="/" component={Home} />
```

`this.context.router.isActive('/')` returns `true` for any route.

**Comment by gonsfx** [comment]
Same problem here.

```
  <Router history={new BrowserHistory}>
    <Route component={App}>
      <Route path="/" component={Shop} />
      <Route path="cart" component={Cart} />
      <Redirect from="*" to="/" />
    </Route>
  </Router>
```

URL `/`: Links to `/` are active.
URL `/cart`: Links to both `/` and `/cart` are active.

**Comment by ryanflorence** [comment]
Need index routes, I'll write up some docs this week.

**Comment by jackmoore** [comment]
@ryanflorence I use the IndexRoute component (instead of `path="/"`), and this is an issue I'm experiencing as well.  Not sure if that's what you meant.

**Comment by ryanflorence** [comment]
I believe #1842 fixes this, in addition to `<IndexRoute/>` and `<IndexLink/>` which don't have docs yet.

**Comment by gonsfx** [comment]
@ryanflorence Whats the difference between an `IndexRoute` or `IndexLink` compared to a normal `Route` or `Link`?

**Comment by ryanflorence** [comment]
the docs that I will write today will reveal all :mag:

**Comment by janpieterz** [comment]
@gonsfx if you're just as curious as I am, this link should give you some insight: https://github.com/rackt/react-router/blob/master/modules/IndexLink.js

The property already works on the npm version.

**Comment by gonsfx** [comment]
@janpieterz I'm not convinced. Do we really need this?

Shouldn't it be possible to get the desired behaviour by looking at the route tree and their paths alone without having to introduce differente route and link components?

**Comment by janpieterz** [comment]
@gonsfx I'm not able to give you any more insight in to if/why we really need this!
@ryanflorence will probably be able!

**Comment by jackmoore** [comment]
@gonsfx You don't need a different link component, the only thing that IndexLink does is add `onlyActiveOnIndex={true}` to a regular Link component, which is what I use instead of IndexLink.  I'm glad to see this as a option, because there are definitely have need for both behaviors (active on exact, and active on exact + descendent paths).  However, the behavior for it still seems buggy.

**Comment by gonsfx** [comment]
I don't even understand what `onlyActiveOnIndex` is supposed to say. After all, each Link points to a path so it should be obvious if it is active or not?

**Comment by nlutterman** [comment]
@gonsfx Perhaps the thought about the behavior is that all paths are technically decedent from the root path, so it will always be active.  These separate options are to perhaps allow that behavior, as well as having each path only be active when the developer wants it to be.

[The docs note that here](https://github.com/rackt/react-router/blob/master/docs/guides/basics/IndexRoutes.md#index-links)

**Comment by dyyylan** [comment]
Is there a fix for this if you aren't trying to use the actual <Link>'s active prop? I have a wrapper component that I am using to put an active class on an <li> and I still don't see a way to determine if the current route is active, without it also being true for all of its parent routes, using `this.context.history.isActive`.

**Comment by musbaig** [comment]
Running into the same issue as @dyyylan

**Comment by mjackson** [comment]
@gonsfx The whole idea of "active" doesn't have anything to do with paths/URLs. It's about *routes*. A route is said to be "active" if it is in the current render tree. The `onlyActiveOnIndex` property restricts a link to being active only if we are at an index route. Try checking out [the tests for `IndexLink`](https://github.com/rackt/react-router/blob/master/modules/__tests__/IndexLink-test.js). They should make it very clear how everything works.

@dyyylan @musbaig Sounds like you guys are using Bootstrap. We have discussed this topic ad nauseam in other issues. Please try a search.

**Comment by musbaig** [comment]
@mjackson don't get me wrong, I think you guys are doing an awesome job with react-router. 

I decided to comment only after a lot of searching, since the example discussed here https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query was not working for IndexLinks as `history.isActive` always returned true since "/" was always in the render tree.
 
As a result, although, I'm not using bootstrap, sadly, I am in the same boat as @dyyylan

**Comment by mjackson** [comment]
@musbaig Could you create a failing test that shows me what you'd like to do, but can't?

**Comment by dyyylan** [comment]
@musbaig Have you tried making the root route an `IndexRoute` and passing `onlyActiveOnIndex = true` into the `history.isActive`? That's what I ended up doing to solve my particular use case.

**Comment by dyyylan** [comment]
@mjackson The `onlyActiveOnIndex` argument works for my use case, the only case I haven't solved is for the root route `"/"` which will always be active, and you cannot use the `onlyActiveOnIndex` argument, since it cannot be an `IndexRoute`.

**Comment by taion** [comment]
Why can't it be an `IndexRoute`? You just do

```js
<Route path="/" component={Foo}>
  <IndexRoute component={Bar} />
  {/* ... */}
</Route>
```

**Comment by dyyylan** [comment]
But the top level route cannot, not can an IndexRoute have children.

**Comment by taion** [comment]
Can you elaborate? The pattern I have above does in fact work.

**Comment by dyyylan** [comment]
Let's say you have this structure:
```
<Router>
    <Route path="/" component={App}>
        <IndexRoute component={Home} />

        <Route path="about" component={About}>
            <IndexRoute component={AboutLandingPage} />
            <Route path="foo" component={SomeOtherAboutPage} />
        </Route>
    </Route>
</Router>
```

If you have a navbar with a link to "home" and a link to "about", when you are on the about route, the "home" link will always be active, even if you use `onlyActiveOnIndex`, because you *are* currently on an IndexRoute at `/about`.

**Comment by musbaig** [comment]
Thanks @dyyylan for the example. 
My situation is simpler though, no nested `IndexRoute`s. Instead, I have the following setup (stripping out `require`s): https://gist.github.com/musbaig/933dc63f81876735b1df
The problem is here https://gist.github.com/musbaig/933dc63f81876735b1df#file-react-router-index-link-js-L53 where `this.history.isActive` will return true even if you're on a non-index route, thus, making it difficult to dynamically add styles based on active route. Maybe it's an easy fix and I'm simply missing something.
Thanks again!

**Comment by taion** [comment]
@dyyylan That's not what `onlyActiveOnIndex` means. It means it's only active on the index route corresponding to the path you've specified.

**Comment by musbaig** [comment]
I feel this issue should be reopened as `this.history.isActive('/')` always returns true even if you're _not_ on an `IndexRoute`, as demonstrated by the gist I posted earlier.

**Comment by taion** [comment]
You're aware that `isActive` takes additional arguments, right? https://github.com/rackt/react-router/blob/v1.0.0-rc3/modules/useRoutes.js#L27

**Comment by dyyylan** [comment]
Yes, you can pass in the additional parameter so that it is only active on an index route. Unfortunately, the "/" index route will always be active if you are on a *different* index route anywhere in the app.

**Comment by taion** [comment]
That's simply not correct. I am using this exact pattern on my page right now, and I have an `IndexLink` to `"/"` that is, as desired, only active when I am on `/`.

**Comment by dyyylan** [comment]
I'm not using IndexLink. I'm using `history.isActive`.

If you are in `/some/deep/indexRoute`, `history.isActive('/', query, true)` returns `true`

**Comment by taion** [comment]
Do you have an example of this behavior taking place? `IndexLink` just calls into that logic. I'm looking at my app right now, and I am not seeing the behavior that you describe, when checking whether the root route is active, while on a deeply nested index route.

**Comment by musbaig** [comment]
@taion actually I was not aware of that additional param, I was going by the docs here https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query, guess I should've just peeked at the source, my bad. Thank you soo much for that tip!!

**Comment by knowbody** [comment]
@musbaig I added it to docs https://github.com/rackt/react-router/commit/3a0bd6075cc9e3834d0899a1da1dccdb8fe8298f, thanks!
