### ISSUE TITLE
1.0.0-beta4 ServerSide rendering problem: Router.run is undefined. 

### ISSUE THREAD

**Issue by aulizko** [rackt/react-router#1806]
So what is the **right** way to use react-router for the SSR now? 
[This](https://github.com/rackt/react-router/blob/master/modules/__tests__/serverRendering-test.js) example seems a bit weird for me ;)

**Comment by ameensol** [comment]
Just ran into this also. Tried to implement the example but only got this error:
```js
TypeError: Cannot read property 'length' of undefined at Object.matchRoutes [as default] 
```
which I'm guessing is because I passed my JSX Route component hierarchy as ``Routes`` to ``useRoutes`` instead of an array of objects with path and component attributes.

**Comment by aulizko** [comment]
Figured out how it works:
instead of 
```javascript
Router.run(routes, location, (err, initialState) => {
    // send response to client
}
```
used
```javascript
const markup = ReactDOM.renderToString(
    <Application>
        <Router history={history} location={location} routes={routes} />
    </Application>
);
// send markup to client
```

Here is the gist: https://gist.github.com/aulizko/1dbe1bef0cdd79e8fef2

**Comment by ameensol** [comment]
Thank you! This seems to be working!

**Comment by ami44** [comment]
I search an example without JSX, as plain javascript (like http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Plain Route).

with 0.13.3, i write
````
            Router.run(routes, this.request.url, Handler => {
                let contentHtml = React.renderToString(React.createElement(Handler));

            });

```

**Comment by chentsulin** [comment]
I don't think that @aulizko provided is a right solution: 
```
const markup = ReactDOM.renderToString(
    <Application>
        <Router history={history} location={location} routes={routes} />
    </Application>
);
```
Router even does not accept a `location` as props: 
https://github.com/rackt/react-router/blob/master/modules/Router.js#L17

So maybe we should do `history.match` like lines of code in the test ?

**Comment by aulizko** [comment]
@chentsulin Yup, you're right. Stil, I doesn't like variant with history.match. It is a little weirdo in my taste. 
I myself switched to this variant:

```javascript
import createHistory from 'history/lib/createMemoryHistory';
import createLocation from 'history/lib/createLocation';
import Router from 'react-router';
import routes from './routes';

const location = createLocation(req.originalUrl);
const history = createHistory({entries: [location]}); // this !!!
const router = <Router history={history} children={routes} />;
```

**Comment by shovon** [comment]
Does it actually work? I'm getting a `ReferenceError: document is not defined`, when attempting this:

```javascript
const location = createLocation('/something');
const history = createHistory({ entries: [location] });

console.log(ReactDOM.renderToString(
  <div>
    <Router history={history} children={routes} />
  </div>
));
```

**Comment by shovon** [comment]
And, in my last comment, `routes` is defined as this:

```javascript
function createRouter(store) {
  return (
    <Route component={Container}>
      <Route path='/login' />
      <Route component={RequireLogin} onEnter={RequireLogin.onEnter(store)}>
        <Route path='/' component={App} />
        <Route path='/active' component={App} />
        <Route path='/completed' component={App} />
      </Route>
      <Route path='*' component={NotFound} />
    </Route>
  );
}

const routes = createRouter({});
```

**Comment by chentsulin** [comment]
@shovon Make sure that you use `react-dom/server'` instead of `react-dom` in v0.14

```
var React = require('react');
var ReactDOMServer = require('react-dom/server');
 
class MyComponent extends React.Component {
  render() {
    return <div>Hello World</div>;
  }
}
 
ReactDOMServer.renderToString(<MyComponent />);
```

see [here](https://www.npmjs.com/package/react-dom)

And no anything global `document` usage in all your components

**Comment by shovon** [comment]
@chensulin I've been doing that all along. I'm guessing it's a problem in my configuration somewhere.

**Comment by chentsulin** [comment]
Provide more detail debug messages maybe helpful. For example, which file and which line cause the Exception `ReferenceError: document is not defined`

**Comment by mjw56** [comment]
Any idea how to grab the ```initialState``` with this new setup?

Like before we could grab it via the cb.

```js
Router.run(routes, location, (err, initialState) => {
  // use initialState here
});
```

**Comment by timdorr** [comment]
@mjw56 What were you using that state for?

**Comment by mjw56** [comment]
I was using it to access a static field on the initial route container to fetch it's data dependencies. I'm not sure what the best practices are for server rendering and data fetching.

**Comment by ryanflorence** [comment]
the new (and awesome) history abstraction kind of messed up the server rendering story, but its going to look like this, the code just isn't there yet:

https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

Should have a release in the next few days with that API working.

**Comment by firstdoit** [comment]
Anxious to see this, beta4 breaks some awesome tutorials like https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4

**Comment by knowbody** [comment]
@firstdoit it's still a beta. We all do our best to ship 1.0 as soon as we can. @acdlite is doing great work on redux-react-router so all works well together. Router should be working fine with redux. Check [redux-react-router#26](https://github.com/acdlite/redux-react-router/issues/26#issuecomment-138776071) for more details.

**Comment by firstdoit** [comment]
Sure, I'm definitely not complaning! Just anxious for more of this great work to come out :star2:

**Comment by mjw56** [comment]
Awesome, this worked! Thank you @ryanflorence and team!

**Comment by debjeet-sarkar** [comment]
I am doing ReactDOM.renderToString(MyComponent) where MyComponent is in form : 
                                            <Router>
					    <Route path ='/' component ={component}/>
					    </Router>
How do I send the props from ReactDOM.renderToString(MyComponent) to MyComponent so that it is available as props ?
