### ISSUE TITLE
willTransitionTo of DefaultRoute runs while it's not supposed to

### ISSUE THREAD

**Issue by arian-hosseinzadeh** [rackt/react-router#1809]
Let's assume that I'm using the following structure for routes : 

    var routes = (
        <Route name="app" path="/" handler={App}>
            <Route path="about" name="about" handler={About} />
            <DefaultRoute name="home" handler={Home} />
        </Route>
    );

And `home` component looks like this : 

    var React = require('react');
    var loginStore = require('../stores/LoginStore');
    var Home = React.createClass({

    displayName: 'Home',

    propTypes: {},

    statics: {
        willTransitionTo(transition) {
           console.log('HEREEEEEEEE');
            if (!loginStore.isLoggedIn()) {
                loginStore.setTransitionPath(transition.path);
                transition.redirect('login');
            }
        }
    },
    render: function() {
        return (<div>
        </div>);
    }
    });

    module.exports = Home;

Let's assume that I want to route to `/about` , although that we expect `home` not to come into action , we get the `console.log` result in the screen which means `willTransitionTo` of `home` is running. Is it a bug or I'm missing something ?

**Comment by ryanflorence** [comment]
seems weird, you sure you've got your module requires correct and aren't accidentally configuring the routes wrong?

**Comment by ryanflorence** [comment]
comments [here](https://github.com/rackt/react-router/issues/1778#issuecomment-139098269) apply to this issue too.

**Comment by arian-hosseinzadeh** [comment]
@ryanflorence : I read the comment , but I don't know how it solves this issue.

**Comment by ryanflorence** [comment]
```
    <Route name="app" path="/" handler={App}>
        <Route path="about" name="about" handler={About} />
        <DefaultRoute name="home" handler={Home} />
    </Route>
```

initial load at `/`, `App`, `Home` get mounted so should get `willTransitionTo` called

navigate to `/about`, `Home` gets unmounted so should get `willTransitionFrom` and `About` gets mounted so `willTransitionTo`, App was already mounted, and was not unmounted, so nothing should happen.

**Comment by arian-hosseinzadeh** [comment]
@ryanflorence : `navigate to /about, Home gets unmounted so should get willTransitionFrom` this makes sense , but the problem is that `willTransitionTo` of this component gets called , not the `willTransitionFrom`
