### ISSUE TITLE
Endless loop when routes object changes between renders

### ISSUE THREAD

**Issue by omerts** [rackt/react-router#1813]
Hello,

We have a component that loads data on a transition:
```javascript
constructor(props, context) {
    super(props);

    context.router.addTransitionHook(this._loadActiveData);
  }

  _loadActiveData(nextState, router, cb) {    
    AppStore.loadActiveData(nextState.location.pathname, cb);
  }
```

When new data loads, we re-render the entire app, in order to transfer the right props through the router's createElement handler:
```javascript
function renderApp(sessionId) {    
  React.render(<Router history={history} children={routes(sessionId)} createElement={createElement} />,
                 document.getElementById('app'), () => {
                  console.timeEnd('app render on route change');
                });
}

AppStore.addChangeListener(renderApp);
```

On every renderApp, the routes function returns a new routes object, which most of the time is the same exact object (made sure of it deep comaring the objects). The problem is, that passing a new routes object reference, causes an endless loop, since every time we call React.render the _loadActiveData function is recalled, which in turn calls React.render, and so on.  
Maybe this is by design, but imho if the routes are exactly the same why would the router recall the callback on the transition hook?

**Comment by ryanflorence** [comment]
small test case would be great

**Comment by ryanflorence** [comment]
this was not public API and code has shifted around regarding transitions, but changing the routes underneath probably shouldn't mess anything up.

Instead of this approach though, I'd recommend you put a data component up top:

```js
React.render((
  <Router>
    <Route component={AppDataFetcher}>
      // the rest of your routes
    </Route>
  </Router>
), el);

// ...

let AppDataFetcher = React.createClass({
  getInitialState () {
    return { fetching: false }
  },

  componentWillMount () {
    this.fetch(this.props.location)
  },

  componentWillReceiveProps (nextProps) {
    let routeChanged = nextProps.location !== this.props.location
    if (routeChanged)
      this.fetch(nextProps.location)
  },

  shouldComponentUpdate () {
    return !this.state.fetching
  },

  fetch (location) {
    this.setState({ fetching: true })
    AppStore.loadActiveData(location.pathname, () => {
      this.setState({ fetching: false })
    });
  },

  render () {
    return this.props.children
  }

})
```

**Comment by omerts** [comment]
@ryanflorence, thanks for the answer a wrapper data loader component is what we did, but it just loads the data, and doesn't set the state (it is set from outside).

Here is an example code for reproducing the problem, you need to hit Dashboard link twich (did it this way to it doesn't get stuck right away), you can look at the console to see the renders:
```javascript
import React, { findDOMNode } from 'react';
import { Router, Route, Link, Navigation, TransitionHook } from 'react-router';
import { history } from 'react-router/lib/HashHistory';

let initialRender = true;

function _getRoutes() {
  return <Route path="/" component={App}>
          <Route path="dashboard" component={Dashboard}/>
         </Route>;
}

// COMMENT THIS IF YOU WANT IT TO WORK, AND UNCOMMENT CODE IN BOTTOM
function renderApp() {
  React.render((
    <Router history={history} children={_getRoutes()} />  
  ), document.getElementById('example'));
}

var App = React.createClass({
  mixins: [ TransitionHook ],

  routerWillLeave(nextState, transition) {
    if (!initialRender) {
      renderApp();
    }
  },

  render() {
    console.log('render');
    return (
      <div>
        <ul>
          <li><Link to="/dashboard">Dashboard</Link></li>
        </ul>
        {this.props.children}
      </div>
    );
  }
});

var Home = React.createClass({
  render() {
    return <h1>Home</h1>;
  }
});

var Dashboard = React.createClass({
  render() {
    initialRender = false;
    return <h1>Dashboard</h1>;
  }
});

// UNCOMMENT THIS IF YOU WANT IT TO WORK
/*const routes = <Route path="/" component={App}>
                  <Route path="dashboard" component={Dashboard}/>
                </Route>;

function renderApp() {  
  React.render((
    <Router history={history} children={routes} />  
  ), document.getElementById('example'));
}*/

renderApp();
```

**Comment by ryanflorence** [comment]
I don't understand why you're trying ot render the app when routes are **exited**, it means you're already in a new render cycle.

Somebody clicked a link, your route is being **exited** and then you're telling the app to rerender, I don't understand why, but the only point of the transition hook is to cancel the transition, literally nothing else should be done in that hook: check the state of the app/component and then allow or don't allow the transition.
