### ISSUE TITLE
[1.0.0-beta4] infinite loop with onEnter and redirectTo

### ISSUE THREAD

**Issue by jdelight** [rackt/react-router#1814]
I have my routes like below and __always__ want to redirect from `/` to `/child`. 

```js
export default {
    path: '/',
    component: App,
    onEnter: (nextState, redirectTo) => {
        redirectTo('/child');
    },
    childRoutes: [{
        path: '/child',
        component: ChildComponent
    }]
}
```
The above method feels like it should be the correct way to do this. However it results in an infinite loop. I'm assuming because the redirect causes the base route `/` to be entered again.

So I solved that with this change:
```js
    onEnter: (nextState, redirectTo) => {
        if (nextState.location.pathName === '/') { // only redirect if we're about to go to `/`
            redirectTo('/child');
        }
    },
```
which prevents the infinite loop but feels wrong to me because ideally this check could be internal (i.e. the router never performs a redirect to the current route) 

The fix also raises a bunch of warnings about propTypes - exactly the warnings seen here  #1796

So what's the best way to redirect from  `/` to `/something`? - perhaps there could be an example created for this as it's a fairly common thing to do.

I've tried adding router contextTypes to the App component and that didn't remove the warnings.

**Comment by ryanflorence** [comment]
You want the redirect on an `<IndexRoute/>`, if you make an example we'll merge :)

```
export default {
    path: '/',
    component: App,
    indexRoute: {
      onEnter: (nextState, redirectTo) => {
        redirectTo('/child');
      },
    },
    childRoutes: [{
        path: '/child',
        component: ChildComponent
    }]
}

**Comment by jdelight** [comment]
Thanks - works great! Opened a PR with example.

**Comment by ziziermao** [comment]
hey guys, I tried to use `replaceWith`, and it works.
But I want to base on a backend call's result to decide which path to go to. When I tried to pass replaceWith to a callback function, it gives no error, but there's no effect. Could anyone suggest?

**Comment by PierBover** [comment]
Hey @ziziermao it seems the API was changed and now there are 3 arguments `onEnter`. after calling the second argument you also have to call the third:

```
const userIsInATeam = (nextState, replace, callback) => {
  fetch(...)
    .then(response = response.json())
    .then(userTeams => {
      if (userTeams.length === 0) {
        replace(`/users/${nextState.params.userId}/teams/new`)
      }
      callback();
    })
    .catch(error => {
      // do some error handling here
      callback(error);
    })
}

<Route path="/users/:userId/teams" onEnter={userIsInATeam} />
```

https://github.com/reactjs/react-router/blob/master/docs/API.md
