### ISSUE TITLE
Will 1.x have replaceRoutes()?

### ISSUE THREAD

**Issue by dminkovsky** [rackt/react-router#1815]
I'm using the currently undocumented [`replaceRoutes()`](https://github.com/rackt/react-router/pull/658) to transition between "logged in" and "logged out" routes. 

Looking at the 1.x branch, I'm not seeing this functionality. Will it be included?

**Comment by mjackson** [comment]
No.

**Comment by dminkovsky** [comment]
Is there some idiomatic way to handle "logged in" vs "logged out" state, then? 

"logged out" looks like this:

```
<Route name='root' path='/' handler={LoginPage}>
    <Route name='login' path='login' handler={LoginForm} />
    <Route name='join' path='join' handler={JoinForm} />
    <Redirect from='/' to='login' />
    <Redirect from='*' to='login' />                                                                                                                                                                        </Route>
```

"logged in" looks like a bunch or normal application routes.

**Comment by dminkovsky** [comment]
@gaearon 

you added `replaceRoutes()`—do you have any ideas on this?

thank you.

**Comment by dminkovsky** [comment]
I'm guessing the idiomatic way is to be found in the auth-flow example https://github.com/rackt/react-router/blob/master/examples/auth-flow/

**Comment by dminkovsky** [comment]
The feature I was looking for is described in the [shared root example](https://github.com/rackt/react-router/blob/2ceb9eb23efa1f63dcfbc53808f4a0812c26237d/examples/shared-root/app.js#L74-L80).
