### ISSUE TITLE
Link with back path

### ISSUE THREAD

**Issue by gyzerok** [rackt/react-router#1818]
Is there a way to create Link with back path?
```javascript
<Link to="back" />
```

**Comment by alopes** [comment]
this.goBack();
http://rackt.github.io/react-router/#Navigation

**Comment by gyzerok** [comment]
@alopes Is there a way to use it with ES6 class syntax? I'm using 1.0.0-beta3

**Comment by chentsulin** [comment]
Should work with context router

https://github.com/rackt/react-router/blob/v1.0.0-beta3/modules/RouterContextMixin.js#L129

**Comment by silvenon** [comment]
It would be cool if `<Link />` had a `go` property, then we wouldn't have to create a callback.

**Comment by taion** [comment]
That doesn't really make sense - `goBack` is not like an `href`, and doing something like opening a "back" link in a new tab would be... bizarre.

**Comment by silvenon** [comment]
I agree, it's weird.

**Comment by shakedlokits** [comment]
@taion 
I agree, who ever uses two dots to denote going backwards on an directed tree.. (:

**Comment by shakedlokits** [comment]
@taion I agree, because who ever uses two dots to denote going backwards on a directed tree(:
