### ISSUE TITLE
List all breaking changes between v1.0.0-beta3 and v1.0.0-beta4

### ISSUE THREAD

**Issue by chentsulin** [rackt/react-router#1820]
So many people already using `v1.0.0-beta3` in their examples including [redux/examples/real-world](https://github.com/rackt/redux/blob/master/examples/real-world/package.json#L24).

And some of them assign `^1.0.0-beta3` as react-router's version in their package.json.

```json
"dependencies": {
    "react-router": "^1.0.0-beta3"
},
```

Now, It will install `1.0.0-beta4` and burn the whole project.

It's good to let more people know that there is a huge breaking change between this two versions. Maybe a well-known opening issue or some note on document and README.

And We have some discusses on breaking changes here:
https://github.com/tomchentw/redux-universal/pull/4#issuecomment-137644934

Let's try to avoid frustrating and confusion for people from `v1.0.0-beta3`

**Comment by globexdesigns** [comment]
I'm getting these warnings after moving from `beta3` to `beta4`. Still not sure what the cause. Would really like to see the answer included in the list:

```
Failed propType: Required prop `location` was not specified in `RoutingContext`. Check the render method of `Router`.
Failed propType: Required prop `routes` was not specified in `RoutingContext`. Check the render method of `Router`.
Failed propType: Required prop `params` was not specified in `RoutingContext`. Check the render method of `Router`.
Failed propType: Required prop `components` was not specified in `RoutingContext`. Check the render method of `Router`.
Failed Context Types: Required child context `location` was not specified in `RoutingContext`. Check the render method of `Router`.
```

**Comment by igl** [comment]
Breaking changes are `alpha` business and a bit unexpected from beta-3 to beta-4. However... one should expect some fireworks from `beta` software too.

I always remove the `^` from my package.json to avoid surprises from sem-ver villains. (`npm-check-updates` is nice)

**Comment by matth3wga0** [comment]
@globexdesigns It's maybe caused by `getComponents`. https://github.com/rackt/react-router/issues/1796

**Comment by mjackson** [comment]
Please do not consider our 1.0.0-beta* releases to be stable. AFAICT semver does not specify that breaking changes may not occur between beta releases.

**Comment by quirinpa** [comment]
I want to be on the bleeding edge :P how can do i get around this?
