### ISSUE TITLE
A way to create modified <Route> element - v1.0.0.

### ISSUE THREAD

**Issue by kasperekt** [rackt/react-router#1822]
I found myself in need of creating few Routes with the same `onEnter` parameters. It basically checked if user was logged in, and if not, router redirects to `/login` screen.

I wanted to do something like this:

```jsx
<AuthRoute path="..." component={SomeComponent} /> 
```

which basically would be:

```jsx
<Route path="..." component={SomeComponent} onEnter={authorizeFn} />
```

But It didn't work. Tried few things like `React.cloneElement` but neither worked.
Wouldn't it be nice to make it possible to create such elements? It can be written differently, but I think it is more elegant.

**Comment by KnutHelland** [comment]
Do you need to have routes that the user is not authorized to show? There are multiple other ways to solve this, but I've done it like this:
```
function makeRoutes(user) {
	return (
		<Route path="/" handler={App}>
			{ [

				// Routes for both autenticated and not authenticated users
				<Redirect path="about" to="https://example.com" key="about" />,

			].concat(user.authenticated ? [

				// Routes for users that are logged in
				<Redirect from="/" to="dashboard" key="redirect_dashboard" />,
				<Route name="/mySecretModule" handler={MySecretModule} key="secret_module" />

			] : [

				// Routes for unauthenticated users
				<DefaultRoute handler={Login} key="loginDefault" />,
				<Route name="login" handler={Login} key="login" />,

			]) }
		</Route>
	);
}
```

And I rerender the router everytime the user model changes:

```
// From init.jsx
const render = () => {
	run(makeRoutes(auth.getUser()), HistoryLocation, (Root, ...args) => {
		React.render(<Root />, mountPoint);
	});
};

render();
auth.onChange(render);
```
I haven't used ReactRouter for anything serious yet, so I'm not saying that this example is the best. But I really like the idea of a dynamic router where I always can rerender a router that fits the users current permissions.

I don't think you need to redirect to `/login` at all. `login` can be the default route when the user is not logged in, and when he gets logged in, the router will rerender and the user will get the page he requested.

**Comment by kasperekt** [comment]
Yes, I know that there are multiple ways achieve this. I've already solved that.

I'm just giving an idea. In my opinion that would be lot more elegant.

**Comment by ryanflorence** [comment]
we don't actually render the routes so normal react composition doesn't apply :\

you can use plain objects instead and use javascript to compose however you'd like.

also, keep in mind if a parent is protected, all children are too, I've found in my apps this is enough:

```js
<Router>
  <Route component={Public}>
    {/* public routes */}
  </Route>
  <Route component={SignedIn} onEnter={requireAuth}>
    {/* all routes are protected here, they don't need their own requireAuth */}
  </Route>
</Router>
```

**Comment by rstormsf** [comment]
I've just started to use react-router and also need to implement that.
Question @ryanflorence : in your `requireAuth` function - how do u get a user state in there? how can I pass a session token to check it out?

Sorry if it's very newbie question - I'm learning react as I go.

Also what is your favorite flux implementation? I'm looking at `redux` as my first time flux lib
