### ISSUE TITLE
Get async data just for matching route

### ISSUE THREAD

**Issue by Dharmoslap** [rackt/react-router#1823]
I'd like to get async data just for certain one route. In the async example (https://github.com/rackt/react-router/tree/0.13.x/examples/async-data) the async data are being fetch for all the routes. Is there a way how to achieve this in 0.13.x, or is it already possible in 1.0.0?

**Comment by ryanflorence** [comment]
only have one route define the hook

**Comment by Dharmoslap** [comment]
Which hook do you mean?
