### ISSUE TITLE
How do you redirect to a route name in v1?

### ISSUE THREAD

**Issue by hackhat** [rackt/react-router#1824]
Hy!

I'm using the beta version and I've noticed that you don't have names in the routes anymore.

Given this routing config:

    <Route name='myRoute' path='aaa/:xxx/:yyy/some/:a'/>

How can I redirect properly to this route?

In the previous version I could just do this:

    transition.redirect('myRoute', {xxx: 0, yyy: 0, a: 0});

But now it seems that there are no names in the route, so this would not work:

    transition.to('myRoute', {xxx: 0, yyy: 0, a: 0});

So the only way to make it work would be to:

    transition.to('/aaa/0/0/some/0');

Which is pretty bad...

**Comment by globexdesigns** [comment]
`transition.to('/aaa/0/0/some/0');` is the right way to do it in 1.0.  There's a long discussion about it here: https://github.com/rackt/react-router/issues/1514
