### ISSUE TITLE
v1.0.0-beta4 - Path only matches on app refresh

### ISSUE THREAD

**Issue by bclinkinbeard** [rackt/react-router#1826]
I have this route definition:

```js
<Route path="user/:username" component={User}>
  <Route path=":id" component={Gist}/>
</Route>
```

If I load http://localhost:3000/user/bclinkinbeard/6e52ddd directly, everything works as expected. If I use a `Link` to navigate to the same URL, I get a `Location "6e52ddd" did not match any routes` error.

**Comment by timdorr** [comment]
What's in the `to` on your `Link`?

**Comment by bclinkinbeard** [comment]
`<Link to={gist.id}>{gist.description || gist.id}</Link>`, where `gist.id` is the last fragment of the URL, like `6e52ddd`

**Comment by timdorr** [comment]
The `to` needs to be a absolute path. It's [passed back into `history` via pushState](https://github.com/rackt/react-router/blob/v1.0.0-beta4/modules/Link.js#L73), which only accepts absolute paths. 

From the `history` [Getting Started](https://github.com/rackt/history/blob/master/docs/GettingStarted.md) guide: 

> The path argument to pushState and replaceState represents a complete URL path, including the query string.

**Comment by bclinkinbeard** [comment]
Doesn't that make it a lot harder to build self contained components? Or is there an easy way to pass the current URL down that I'm not aware of? Seems like a real burden, especially if you're several levels below root.

**Comment by timdorr** [comment]
You could build a decorated Link component that reads the current `window.location` and builds absolute URLs from relative ones. `RelLink` or something like that.

A neat project would be a `Route` generator that also builds URL helpers, much like Rails does with ActionView. Then you could reference them by name and pass in whatever params you need.

**Comment by bclinkinbeard** [comment]
"reads the current window.location and builds absolute URLs from relative ones"
I'm confused as to why that isn't the default behavior.

**Comment by timdorr** [comment]
To be honest, I am too. @mjackson has said [`history.pushState` is not supposed to mirror the behavior of `window.history.pushState`](https://github.com/rackt/history/issues/32#issuecomment-132892425). But by choosing a similar name, the association is implied.

I guess we just have to accept that for what it is and hope history 2.0 adds a clearer API :)

**Comment by ryanflorence** [comment]
I've wanted relative link paths since the beginning, we've just not done it yet.

**Comment by ryanflorence** [comment]
here was some earlier work before the "rewrite" https://github.com/rackt/react-router/pull/773

**Comment by ryanflorence** [comment]
would love a pull request #1828
