### ISSUE TITLE
make relative transition paths work like real anchors and pushState

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#1828]
Right now we require absolute paths everywhere for links, transitions, etc.

Anchors and `pushState` understand relative urls, we should too. This is especially useful for query strings.

Current workaround is to use `this.props.location.pathname` that comes in to route components.

**Comment by ryanflorence** [comment]
earlier work done here #773, and I know there's been discussions in many other tickets since the beginning.

**Comment by bclinkinbeard** [comment]
Just to be clear, this needs to happen in https://github.com/rackt/history/blob/master/modules/createHistory.js#L199, right?

**Comment by ryanflorence** [comment]
I think so, I haven't been involved in the code much these days, just API discussions.

**Comment by knowbody** [comment]
yeah, let's continue the discussion in [History](https://github.com/rackt/history) repo as it's now separate
