### ISSUE TITLE
Multiple child routes

### ISSUE THREAD

**Issue by tvogels** [rackt/react-router#1829]
I am new to `react-router`, so please forgive me if this a stupid question. I am trying to implement a router where a Route has two parallel/independent sub-routes and I wonder if this is possible with `react-router`. The image below illustrates what I want to achieve. It represents an event-editor with two components: (1) the viewing component and (2) the editing component. I think their states should both be part of the URL somehow.

![illustration](https://cloud.githubusercontent.com/assets/840825/9702964/e9c80f1c-5473-11e5-80e0-aab5b244f6fc.png)

One extra constraint: `[child1]` should be aware of the state of `[child2]`, since it needs to show the item that is currently edited in a different color or so. 

If this is not possible with `react-router`, how would you guys implement this? Thanks!

**Comment by ryanflorence** [comment]
on the master branch, yes: https://github.com/rackt/react-router/blob/master/docs/Route.md#components
