### ISSUE TITLE
Examples "missing script: start"

### ISSUE THREAD

**Issue by diffractometer** [rackt/react-router#1830]
When I try to `npm start` to checkout the examples I get the following error:

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! missing script: start

**Comment by olegakbarov** [comment]
You can launch the dev server with examples by running `npm run examples`. Also always you can check out the list of available scripts in `package.json`.

**Comment by diffractometer** [comment]
Yes, realized that after I posed the issue. Someone may want to update the documentation.
