### ISSUE TITLE
Possible Race Condition With Hashes In URLS

### ISSUE THREAD

**Issue by chadhietala** [rackt/react-router#1831]
Noticed what appears to be a race condition when URLS contain a hash in them.

__Repro__

1. Visit http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Advanced Usage
2. Hit command + R repeatedly
3. Witness that sometimes you are placed at the anchor and other times at the top of the document

**Comment by ryanflorence** [comment]
that page doesn't use react router, its just static html.
