### ISSUE TITLE
react-router-global typescript definition needed

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#1832]
The [current typescript definition](https://github.com/borisyankov/DefinitelyTyped/blob/master/react-router/react-router.d.ts) does not play well with `react-global.d.ts`.

There should be a separate `react-router-global.d.ts` file that uses `react-global.d.ts`

**Comment by ryanflorence** [comment]
I believe this issue should be somewhere else. We don't maintain anything like this.
