### ISSUE TITLE
isTransitioning on beta4

### ISSUE THREAD

**Issue by gerherz** [rackt/react-router#1834]
I see isTransitioning isn't part of the props anymore. Where can I find it now?

**Comment by ryanflorence** [comment]
it is probably coming back, otherwise I can't think of a way to notify the user when some dynamic code loading is taking too long, if not, we'll discuss here after 1.0

**Comment by coodoo** [comment]
@ryanflorence Just wondering is `isTransitioning` ever coming back? There's pretty solid needs for such information so that we can display loading messages while waiting for data to load, thought?

**Comment by coodoo** [comment]
bump?

**Comment by vladar** [comment]
+1. Is there a workaround for now?

**Comment by taion** [comment]
Per @ryanflorence on Discord I think we're recommending `listenBefore` for this - otherwise you get unnecessary re-renders as the router enters the `isTransitioning` state.
