### ISSUE TITLE
Animate individual components before changing page

### ISSUE THREAD

**Issue by ghosthoughts** [rackt/react-router#1835]
I have a slightly different usecase. When the app is loaded, it displays an _EntryPage_ which has a button in the middle and two image grids - one on left half and one on right half. Clicking on the button would fade the button, and the two grids will slide out of the page in their respective screen edges.
I applied `ReactCSSTransitionGroup` individually on the button and on the two grids, and the animations work happily.
Now, after the transition, the _HomePage_ should be rendered for which I employed _react-router_. However, I lose the individual animations of the exiting _EntryPage_.
While the use cases show that a full-page transitions are possible, I haven't read or missed about __component-specific transistions on the exiting page__.

Is there are solution for this? Otherwise, I would have to consider the _EntryPage_ elements as part of the _HomePage_ elements, similar to your 'Without React Router' example.

**Comment by ryanflorence** [comment]
try to ignore the router and think about whats happening: the parent component is getting unmounted. If you can figure out how to do this w/o the router, the solution shouldn't be any different. You'll need your own `ReactTransitionGroup` (not `ReactCSSTransitionGroup` with your own `willLeave` `willEnter` animation hooks that get into the details of the animation).

**Comment by ghosthoughts** [comment]
Ok. I have realized that using `ReactTransitionGroup` and `componentWillLeave`, a parent component can order its child elements using `ref` to animate differently.
Now I am facing another problem: _react-router_ brings in the second page while the first page components are animating. Is there a hook to stall the loading of next page till the animations are complete?
For reference, I am using *react-router* from the master branch, which I suppose is `1.0b4`. [Here is a jsfiddle](https://jsfiddle.net/reactjs/69z2wepo/) to understand the problem. Clicking on *hello* followed by clicking on *world* will animate the child component of HelloPage, but World already appears in the meantime.
I profusely apologise for posting this after you closed the issue, but I feel the current problem I face has something to do with react-router, and this is my 2nd day with *React*!

**Comment by ghosthoughts** [comment]
I managed to solve this after wading through the latest as well as the outdated docs, which actually helped me a lot in understanding the functions of *React* as well as *ReactRouter*. [Here is the solution](http://codepen.io/ghosthoughts/pen/wKMPEM/?editors=011) in case anyone else needs it.
