### ISSUE TITLE
Keep the base URL

### ISSUE THREAD

**Issue by SebT** [rackt/react-router#1836]
Hi,

I've search but found nothing, is it possible to always keep the URL in the browser the same and keep navigation state in JS only?

For instance: I go to `http://localhost:3000/` and click on a button that calls `transitionTo` to a route named 'item'. Currently, that would change the browser URL to `http://localhost:3000/items` and load the items page. 

**So my question is**: Is it possible to have the exact same behavior without updating the browser URL? The goal is to make sure that users ALWAYS come from the website's (actually it's a cordova app) home page.

If this isn't possible, is there a way to detect with what URL the app was first load and redirect to the home page before rendering anything?

**Comment by SpainTrain** [comment]
`MemoryHistory` may be for you - https://rackt.github.io/react-router/tags/v1.0.0-beta3.html#MemoryHistory

**Comment by SebT** [comment]
I guess this is exactly what I want, but unfortunately I need a stable version of react-router.

Any idea on how to redirect to the home page with v0.13 when the user accesses the site from other page than home (`/`) ?

**Comment by timdorr** [comment]
You can do that server side. Just set up a wildcard route that redirects back to your index.

**Comment by SebT** [comment]
As this is a cordova app I don't have a server, files are served from file system.

I develop using BrowserSync so that I don't have to deploy the app all day long, I guess I could find a way but this doesn't seem to be an out-of-the-box feature and I lack time.

I guess I'll just wait for react 1.0.0 for now, thanks for the help.

**Comment by timdorr** [comment]
I'd start with beta4 then. It's the beginning of finalizing the 1.0.0 API and will give you the least migration pain whenever that lands. I would expect there to be another beta (or two) and then an RC that will give you a stable API to work against. But beta4 already has the memory history, which will do what you're looking to do.

**Comment by ryanflorence** [comment]
Bbring in `TestLocation` from 0.13 for your app, it could have just as easily been named `MemoryLocation`

https://github.com/rackt/react-router/blob/0.13.x/modules/locations/TestLocation.js

Its not part of the global build, so if you aren't using a module bundler like browserify/webpack then you'll need to copy/paste that code into your app.

**Comment by SebT** [comment]
Thanks for your help.

Actually I thought of a very simple solution earlier:

```javascript
// Do this before the Router.run call
location.href = location.href.replace(/\/#\/.+/, '/#/');
```

This way the URL updates fine but when the user tries to access the app from the browser URL bar (when there is a server call), the current anchor tag is reset to root, therefore the home page loads.

I don't know why this didn't come to me sooner.
