### ISSUE TITLE
willTransition methods in 0.14-beta-3

### ISSUE THREAD

**Issue by web2style** [rackt/react-router#1838]
It seems willTransitionTo ans willTransitionFrom are missing in 0.14-beta-3. What are the substitutes for them? Didn't find anything about it in the docs.

**Comment by ryanflorence** [comment]
transitions were broken in beta3, beta4 has the `Lifecycle` mixin for `willTransitionFrom`: https://github.com/rackt/react-router/blob/master/docs/ConfirmingNavigation.md, and routes have `onEnter` and `onLeave`.

**Comment by dmr** [comment]
@ryanflorence The links you posted return 404s here.
How can I "confirm navigation" in 1.0.0?

**Comment by knowbody** [comment]
Here you go:
- all the docs can be found here: [DOCS](https://github.com/rackt/react-router/blob/master/docs) you can very easily navigate through them using ToC

The links Ryan suggested are here:
- [Confirming Navigation](https://github.com/rackt/react-router/blob/master/docs/advanced/ConfirmingNavigation.md)
- [Route#onEnter(nextState, replaceState)](https://github.com/rackt/react-router/blob/master/docs/api/Route.md#onenternextstate-replacestate)

**Comment by dmr** [comment]
Thank you @knowbody!
