### ISSUE TITLE
Calling `transitionTo` fails with: 'location.search.substring is not a function'

### ISSUE THREAD

**Issue by richardsabow** [rackt/react-router#1841]
When i call `this.props.history.transitionTo('/')` in a component on button click, i get the error message above. After that, this error occurs `Location "/undefinedfunction search() { [native code] }" did not match any routes`, because it tries to change location to `undefinedfunction search() { [native code] }`.
I am using `react 0.13.3` and `react-router 1.0.0-beta4`.

**Comment by ryanflorence** [comment]
pretty sure you're sending a function not `/`

here's the code that handles that, drop a debugger in and let me know what you find out. 

https://github.com/rackt/react-router/blob/0.13.x/modules/createRouter.js#L247-L256

**Comment by richardsabow** [comment]
Sorry, but i'm using the `1.0.0-beta4` version from the `router`, not the `0.13.x`. I try to give only a constant `string`, not a `var`, so the problem is not with parameter of `transitionTo`.
The error `Uncaught TypeError: location.search.substring is not a function` occurs in `useQueries.js:39`, when i debug it, the current `location` parameter in `history.listene`s callback is just a `string`, not an `object`. 
Any idea?

**Comment by quirinpa** [comment]
+1

**Comment by robotvert** [comment]
Looks like a dupe of #1798

**Comment by chentsulin** [comment]
You should use `this.props.history.pushState(null, '/')` instead. `transitionTo` accept a location plain object as parameter.

**Comment by richardsabow** [comment]
Thanks, i've already found this solution! I just saw the old version API in the docs...

**Comment by cabhishek** [comment]
@richardsabow What was your solution to get it working? I am getting the same error with `ES6, react-router 2.3 and react 15.0.1`. 

`this.context.router.transitionTo('/')`

**Comment by robotvert** [comment]
@cabhishek have you read the comment from @chentsulin ? 
also, you're referencing an issue closed more than half a year ago, about version 1.x when you're using version 2.x, there's a chance the given solution is not valid anymore.

**Comment by cabhishek** [comment]
@robotvert I did and it didn't work. Gave this error instead
`
[react-router] props.history and context.history are deprecated. Please use context.router`

So I tried `this.context.router.push('/')` and it worked. But as per docs I should be using `transitionTo` which still fails `this.context.router.transitionTo('/')`

**Comment by robotvert** [comment]
> But as per docs I should be using transitionTo which still fails this.context.router.transitionTo('/')

Can you share the URL of those docs saying so?


Simply using `push` seems to be OK according to the [v2 upgrade guide](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#programmatic-navigation). If you go v2.4.0 you can [use a HoC](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md).

**Comment by cabhishek** [comment]
So not quite sure how I landed on a branch (old) but I read this 

https://github.com/reactjs/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/doc/06%20Mixins/Navigation.md
