### ISSUE TITLE
Generate sitemaps from react-router

### ISSUE THREAD

**Issue by ieow** [rackt/react-router#1843]
Hi, 

I use react-router for SPA site but to have better SEO or google search, sitemaps seems like required.
Is library to generate sitemaps from react-router ? Or is there any other way for google crawler to notice react-router?

Thanks.

**Comment by knowbody** [comment]
I'm not sure if something like it already exists, but might be useful to have such a tool. I just quickly hacked something together which gives the results you want. **The code is not tested and probably there is a much better way of doing it.**

```js
render() {
    JSON.flatten = function(data) {
      var result = {};
      function recurse (cur, prop) {
          if (Object(cur) !== cur) {
              result[prop] = cur;
          } else if (Array.isArray(cur)) {
               for(var i=0, l=cur.length; i<l; i++)
                   recurse(cur[i], prop + '[' + i + ']');
              if (l == 0)
                  result[prop] = [];
          } else {
              var isEmpty = true;
              for (var p in cur) {
                  isEmpty = false;
                  recurse(cur[p], prop ? prop+'.'+p : p);
              }
              if (isEmpty && prop)
                  result[prop] = {};
          }
      }
      recurse(data, '');
      return result;
    }

    let flattenObj = JSON.flatten(this.props.route.childRoutes);

    Object.keys(flattenObj).map(key => {
      if (key.indexOf('path') !== -1) {
        console.log(flattenObj[key]); // path to each route
      }
    });
}
```

`JSON.flatten` just flattens down all the childRoutes, and then just logging all the paths.

If you place the above code in the render method of your `App` component it should give you some kind of a sitemap. In my example gives something like:
```
about
inbox
messages/:id
/about-us
```

and these are my routes:
```jsx
      <Router>
        <Route path='/' component={App}>
          <Route path='about' component={About} />
          <Route path='inbox' component={Inbox}>
            <Route path='messages/:id' component={Message} />
          </Route>
          <Redirect from="/about-us" to="/about" />
        </Route>
      </Router>
```

**Comment by ryanflorence** [comment]
the route config is yours, you can iterate over it yourself.

**Comment by ieow** [comment]
@knowbody - thanks for the hack.
@ryanflorence - I am wondering if there is any library could generate based on the react-router so that it will sitemap will always in sync with react-router (in case forgot to update either one) .

**Comment by knowbody** [comment]
@ieow I don't have much time today, but I will do some work on that tomorrow - keep an eye on https://github.com/knowbody/react-router-sitemap and feel free to contribute as well

**Comment by bbnnt** [comment]
don't you need to know about the content to build a sitemap ?
feels serverside

**Comment by DanielHeath** [comment]
@bbnnt react-router works well server-side

**Comment by bbnnt** [comment]
@danielheath react's at large absolutely not tied to the data. Server/client. Sitemaps about what's in your database arent't they ? Or are we talking about small apps having only static pages right here ?

**Comment by carkod** [comment]
If you use create-react-app with react router, create-react-app generates a bundle with static files into a build folder, so you do not require server to serve the files. Therefore, you don't need the server to generate a sitemap, it's a bunch of static html, css and js files. However if you write a script to build the routes into a sitemap, you will need a server.
