### ISSUE TITLE
componentWillReceiveProps doesn't always get called?

### ISSUE THREAD

**Issue by israelidanny** [rackt/react-router#1854]
I'm trying to check some stuff upon every navigation into a certain View. The recommendation was to use `componentWillReceiveProps`, which I tried - but it seems not to fire upon the route change. 

Is there any way to constantly be able to run code upon entry into the View? This seems like it should be trivial, but became insanely hard.

**Comment by ryanflorence** [comment]
This comes up a lot so I just wrote a guide on it, hope it helps :)

https://github.com/rackt/react-router/blob/master/docs/ComponentLifecycleWhenRouting.md
