### ISSUE TITLE
Using beta4 on IE 8~10 - Map is not defined

### ISSUE THREAD

**Issue by fhelwanger** [rackt/react-router#1859]
Hey,

From what I read on #66, react-router supports IE8+.

But while trying 1.0.0-beta4 on IE10, I got a 'Map is not defined' error. The error occours in this line: https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L30.

Will this be fixed or should I use a polyfill?

**Comment by knowbody** [comment]
this is temporarily fixed by #1862 we're working on that
