### ISSUE TITLE
Path matching problem

### ISSUE THREAD

**Issue by jacklenox** [rackt/react-router#1860]
Apologies if this isn't an issue as such, but I'm not sure where else to post.

Let's say I'm using a link structure like WordPress':

**/2015/09/09/:name/**
Which takes me to a post. I'll want to use the name param to fetch the correct post from a REST API.

However, this:

**/2015/09/**
Would show me all posts in an archive from September 2015. So actually: **/:y/:m/**

And:

**/2015/**
Would show me all posts in an archive from 2015. So actually: **/:y/**

However, for the first one I'd need something like: **/*/:name**

And something like that would invalidate the other routes.

Is this a structure that React Router can deal with? It feels like I need regular expressions. But as far as I can see React Router doesn't currently support them.

Any help much appreciated.

**Comment by ryanflorence** [comment]
`getChildRoutes` can dynamically return whichever routes you want.

```js
<Route getChildRoutes={(nextLocation, cb) => cb(doYourRegexFooHereAndCallBackWithRoutes())}/>
```
