### ISSUE TITLE
urlEncoded slash not treated as part of param data

### ISSUE THREAD

**Issue by timoxley** [rackt/react-router#1865]
I submitted an [incoherent version](https://github.com/rackt/react-router/issues/1771) of this issue previously. My apologies.

## Scenario

1. Given a route like: `/:name`
2. Navigate to `/apple%2Fbanana`
3. Print value of `this.props.params.name`

Note the above url contains a url-encoded forward-slash `/` as `%2F`.

Tested on beta3.

### Expected

`this.props.params.name` === `'apple/banana'`

### Actual

An Error with the following message:

```
Location "/apple%2Fbanana" did not match any routes
```
It appears `react-router` can't differentiate between `%2F` and `/`.

### Problem only manifests when "nesting"

This issue only occurs if a `<Route>` is nested inside another `<Route>`, see comment in example code below.

### Example Code
```js
import React from 'react'
import Router, { Route } from 'react-router'

import BrowserHistory from 'react-router/lib/BrowserHistory'

class Parent extends React.Component {
  render() {
    return <div>{this.props.children} </div>
  }
}

class Child extends React.Component {
  render() {
    const {params} = this.props
    return <h1>{params.name}</h1>
  }
}

// Without the  {Parent} Route, {params.name} will be 'apple/banana' when rendered.
React.render(
  <Router history={new BrowserHistory()}>
    <Route component={Parent}>
      <Route path='/:name' component={Child} />
    </Route>
  </Router>
, document.getElementById('root'))
```

**Comment by ryanflorence** [comment]
looks like this is fixed on master, I added a test case here 634c095
