### ISSUE TITLE
1.0.0-beta4, QuotaExceededError in Safari incognito mode. 

### ISSUE THREAD

**Issue by AndreasHogstrom** [rackt/react-router#1867]
When using safari in incognito mode, navigation fails with the following exception:

```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
```
Safari denies usage of local/session storages when in incognito mode, and raises this error when you try to.

I am using the BrowserHistory history and it seems like the error stems from history/DOMStateStorage.

**Comment by mjackson** [comment]
Can you please open an issue for this in [rackt/history](https://github.com/rackt/history)? Sounds like the bug is with that library, not with the router.

**Comment by jackmoore** [comment]
Opening the ticket there probably shouldn't close the ticket here because this is an unresolved issue.  Any site using react-router for navigation is completely broken in Safari's private mode.

**Comment by knowbody** [comment]
@jackmoore react-router and history has been separated into two different repos, this is why @mjackson asked you to open an issue there because it is related to the history not to react-router itself hence does not need to open here.
