### ISSUE TITLE
Run examples using HTML5 history

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1868]
In order to get the best URLs we should run the examples using HTML5 history. `webpack-dev-server` has a `--history-api-fallback` flag that we should be able to use to do this. We're [already using it in the `history` library](https://github.com/rackt/history/blob/15811a02cafc7b3a777f2e63d7fe1cc99f64f902/package.json#L15).

**Comment by taurose** [comment]
:+1:

I've set this up locally a couple of times, but it requires changing `<Link>` paths and adding a root path to the route config. We could solve this by adding a `basePath`; IIRC this has been requested before.

Running one example at a time shouldn't be an issue though.

**Comment by ryanflorence** [comment]
I'm sure `basePath` will show up real quick once this is done. Like my dad, never fixing the dishwasher until my mom was at the hospital for a couple weeks, then suddenly the dishwasher needed to be fixed.

**Comment by gaearon** [comment]
There'll be no more Github Pages examples then, right?

**Comment by cirocosta** [comment]
There could be if a server rendering step for each page were added
