### ISSUE TITLE
Blank page on mobile

### ISSUE THREAD

**Issue by adaojunior** [rackt/react-router#1869]
I'm building my first react app and I'm trying to test it on mobile but unfortunately I'm having issues with the router, it works fine on desktop browser but I get a blank page on mobile (chrome and safari).
Right now I can't debug on mobile so I can't get more information about the error.

`"react-router": "^1.0.0-beta4"`

```
import React from 'react';
import { Router, Route } from 'react-router';

var App = React.createClass({
  render () {
    return (
      <div>
        {this.props.children}
      </div>
    );
  }
});

var Page = React.createClass({
  render () {
    return (
        <div>
          PATH: {this.props.location.pathname}
        </div>
    );
  }
});

React.render((
    <Router>
      <Route component={App}>
          <Route path="/" component={Page}/>
          <Route path="users" component={Page}/>
      </Route>
    </Router>
), document.getElementById('root'));
```

I also tried https://github.com/gaearon/flux-react-router-example but the same error happens.

**Comment by mjackson** [comment]
It's impossible to tell what's going wrong without more information. If you can provide us a stack trace, we can take a closer look.
