### ISSUE TITLE
Router.History.back() goes back in browser history, not app history

### ISSUE THREAD

**Issue by mlunoe** [rackt/react-router#1874]
We have an iframe within the page, that contains a close button, that will trigger a `Router.History.back()`.
Because it is possible to navigate within the iframe, it will add to the browser history, but not change the path. Calling `Router.History.back()` will therefore go back in browser history (including iframe history), in stead of only the history captured by our app.
I would expect `Router.History.back()` to only navigate the history of the app, but it does this:
https://github.com/rackt/react-router/blob/0.13.x/modules/History.js#L26

**Comment by mjackson** [comment]
We made a lot of fixes to the way we handle history in browsers in the master branch. All of our history handling is now in the [rackt/history](https://github.com/rackt/history) project, which has much better test coverage and better handling of edge cases like this. I'd encourage you to upgrade to 1.0.0-beta4 and try that out.

**Comment by salmanm** [comment]
@mjackson I'm using `v1.0.0-rc3` and still I think I am bitten by a similar issue.

I have an `iframe` inside my component which has a form that is getting auto `submit`ted on load. But when i `history.goBack()`, I have to do twice to go to the previous application state. The back button is in the app, not in the `iframe`, then why does the app history gets affected by `iframe`s history?

Any idea?

**Comment by mlunoe** [comment]
I haven't tried this solution, maybe that will work for you @salmanm:
http://stackoverflow.com/a/30938949/1008519

**Comment by mlunoe** [comment]
Created a fiddle with the problem still existing in React Router v1.0.0-rc1 (latest one I could find available in cdn) and React v0.14.0: https://jsfiddle.net/mlunoe/kwg1da3a/

Could we get this re-opened: @mjackson?

**Comment by taion** [comment]
If you're still having problems, please open an issue on the history repo.

**Comment by annguyen0505** [comment]
when listening history action i saw when history.goBack() method executed, browser will go to root url of my app before it reach previous page! ex. root: "/", current page: "/devices/details": previous:/devices:
from current /devices/details, it go to root "/", then reach the previous page "/devices"
