### ISSUE TITLE
Warning when passing multiple components in a keyed object to a route

### ISSUE THREAD

**Issue by ilyabo** [rackt/react-router#1880]
Specifying multiple components in a route as below:
```
let rootRoute = {
    component: 'div',
    childRoutes: [{
      path: '/',
      components: {
          navbar: "div",
          dashboard: "div"
      }
    }]

  }
```
causes this annoying warning:
```
Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.
```

Same when passing components in an array instead of an object.

I am using `beta4` and `react 0.13.3`.

**Comment by ryanflorence** [comment]
don't render `{this.props.children}`, render them individually `{this.props.children.navbar}`.

**Comment by ilyabo** [comment]
well, that's what i am doing and still get the error

**Comment by ilyabo** [comment]
ok, no, seems that I have a level of indirection causing this, that is, a component which passes the children through

**Comment by ilyabo** [comment]
i think i nailed it down. thanks for your help!
