### ISSUE TITLE
Auth flow issue

### ISSUE THREAD

**Issue by konpa** [rackt/react-router#1881]
Hello,

I'm trying to implement your [auth flow](https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js) in my app but it's not working. The ```requireAuth``` does not seem to be triggered ```onEnter```. If I add the parentheses ```onEnter={requireAuth()}```, it's triggered but I get a undefined errors for ```nextState``` and "not a function" for ```redirectTo```.

I know this can be a dumb question but I'm new to React and I tried a lot of different things before deciding to open an issue on your repo (and read a lot of articles talking about restricted access).

Thanks in advance!

**Comment by malte-wessel** [comment]
`onEnter={requireAuth}` (without `()`) should work

**Comment by konpa** [comment]
No, this was my first attempt. And nothing happened. It is not triggered. In fact, I dont understand why it should be triggered because it's a function. Do I need to add some dependancies? I tried to add all the one that are used in the demo but it's the same...

**Comment by malte-wessel** [comment]
Could you provide some code?

**Comment by konpa** [comment]
Sure.

Here is app.jsx:
```javascript
$.auth.configure({
  apiUrl: 'http://localhost:8000'
});

var React = require('react');
var Router = require('react-router');
var routes = require('./routes.jsx');

Router.run(routes, function (Handler) {
  React.render(<Handler/>, document.getElementById('react'));
});
```

And here is routes.jsx:
```javascript
var React = require('react/addons');
var Router = require('react-router');
var Route = Router.Route;

var appContainer = require('./components/appContainer.react.jsx');
var LoginPage = require('./components/session/LoginPage.react.jsx');
var SignupPage = require('./components/session/SignupPage.react.jsx');
var HomePage = require('./components/dashboard/HomePage.react.jsx');

function requireAuth(nextState, redirectTo) {
  if (!$.auth.user.signedIn)
    redirectTo('/login', null, { nextPathname: nextState.location.pathname });
}

var routes = (
  <Route handler={appContainer} path="/">
    <Route name="login" path="login/" handler={LoginPage} />
    <Route name="signup" path="signup/" handler={SignupPage} />
    <Route name="dashboard" path="dashboard/" handler={HomePage} onEnter={requireAuth} />
  </Route>
);

module.exports = routes;
```

Thanks for your help!

**Comment by konpa** [comment]
I know that I miss something, espacially with the requireAuth parameters but the odd thing is I don't have any errors because requireAuth is not triggered. And this is the first thing that I try to understand...

**Comment by malte-wessel** [comment]
which version of react-router do you use?

**Comment by konpa** [comment]
0.13.3

**Comment by malte-wessel** [comment]
Not sure how `onEnter` hooks in 0.13.x work. But: you were referring to the 1.0 example. The 0.13.x example uses a different pattern to implement auth flow. Have a look here: https://github.com/rackt/react-router/blob/0.13.x/examples/auth-flow/app.js

Hope this helps...

**Comment by konpa** [comment]
Yes, it helps! Thanks. I did not see that I was not on the same versions.

Now I'm trying to understand the syntax of this one...

**Comment by knowbody** [comment]
I believe this is now resolved. If not please reopen
