### ISSUE TITLE
Keep a route rendered?

### ISSUE THREAD

**Issue by geritol** [rackt/react-router#1883]
Is there a way to make somehow a route permanent?
I mean I have a route that is rendered very often, and could I somehow set this route to not re render every time (like keep it in the background when navigating to other routes).
Thanks a lot!

**Comment by knowbody** [comment]
This is the whole point of React - "stop worrying about rerendering"

**Comment by stremlenye** [comment]
Take a look here http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Route
at the `components` section. That probably what you want.

**Comment by geritol** [comment]
Okay. I have images, and i dont want to redownload them every time the route get rendered.
The link is not working for me.

**Comment by stremlenye** [comment]
Aren't images cached or you download them by hands?

**Comment by geritol** [comment]
Yup i just simply get them by url.
