### ISSUE TITLE
Docs site now redirects to github.com repo.

### ISSUE THREAD

**Issue by adalgleish** [rackt/react-router#1884]
**rackt.github.io/react-router** now renders **github.com/rackt/react-router**

Initial request is returning this html:

```html
<html>
<head>
<script>
window.location = 'https://github.com/rackt/react-router';
</script>
</head>
<body>
Redirecting to <a href='https://github.com/rackt/react-router'>https://github.com/rackt/react-router</a>...
</body>
</html>
```

**Comment by knowbody** [comment]
that's there on purpose. all of the docs will be now on GitHub. we removed the website. this is due to the 1.0 release which is coming very soon

**Comment by adalgleish** [comment]
OK thanks - I guess the "Docs" link in README.md could link to **docs/guides/overview.md** or something.
