### ISSUE TITLE
Use const/let instead of var

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1888]
I've been bitten one too many times by `var`. Let's use `const`/`let` instead.

**Comment by oguzbilgic** [comment]
This sounds like good [first-timer](https://medium.com/@kentcdodds/first-timers-only-78281ea47455). I can give this a try if no one else is working on it.

**Comment by knowbody** [comment]
that's great @oguzbilgic, thanks!

**Comment by mjackson** [comment]
Ooops, sorry @oguzbilgic! I didn't see your comment until after I had already done the work. :(

Let's make a `first-timer` label so it'll be easy for people to find them in the future.
