### ISSUE TITLE
Server-side authentication

### ISSUE THREAD

**Issue by xpepermint** [rackt/react-router#1893]
I'm excited to finally see the version `1.0.0` ready for action. It looks really cool so thank you all for all the efforts! 

Maybe this is the right time to ask about the server-side authentication concepts when using `react-router`? I've been struggling on this for months and none of the solutions feel like the right way to do it. If the matching process would be `synchronous` I would use the `react-cookie` package as here https://github.com/rackt/react-router/issues/1629. The main question is how to initialize the router environment before the `match` function so i could manipulate with session/cookies inside `onEnter` and so the `match` function will allow/restrict based on that (putting this into location.state?). This part is straight forward when doing it only on the client side but on the server side I feels like I would need to pass data/request into the `match` function or smth. 

Would someone be so kind and show the `how-to` on this? Thanks!

**Comment by knowbody** [comment]
I will try to put more examples and guides probably tomorrow, I'm AFK today. But we definitely will have much more examples :smile:

**Comment by xpepermint** [comment]
Thanks @knowbody!

**Comment by xpepermint** [comment]
@knowbody Any success on that?

**Comment by knowbody** [comment]
been a bit busy lately, I put them tonight! Promise :pray:

**Comment by xpepermint** [comment]
Hehe, thanks man :).

**Comment by magnusheino** [comment]
Any progress on this issue? I need to do the same thing. Users are pre authenticated and credentials are passes as request headers.

**Comment by taion** [comment]
I think this is heavily dependent on how you do data modeling.

In general the approach you want to take is to just populate the relevant store with information from the cookies (i.e. make this part of the code potentially not be strictly isomorphic).

I'm not sure how helpful it'd be to add a minimal example, when in practice our users most likely would be using Redux or another Flux framework with a potentially different API.

Perhaps this is better suited for a more full-fledged example, e.g. one that shows isoversal rendering with Redux? @gaearon thoughts?

**Comment by magnusheino** [comment]
I do use redux. I templated my application from 
https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/server.js

Should i dispatch a redux action to login the user right after the store is created in server.js above?

Thanks!

**Comment by taion** [comment]
I have no idea what's idiomatic for Redux, sorry.

**Comment by magnusheino** [comment]
Well, you managed to help me anyway :)

I check for my headers, if they are present i dispatch a pre-authenticated-user action to my store that changes state as if the user has logged in. react-routes then checks for logged in users in onEnter. It's all  working...

Great :)

/Magnus
