### ISSUE TITLE
how to inject context to a Route Handler?

### ISSUE THREAD

**Issue by nikhedonia** [rackt/react-router#1897]
I'd like to inject additional context to a Route-Handler, but a wrapped Handler seems to only react once on historyLocationChange. Can someone explain why the following wrappers produces this behaviour?

```js
    Router.run(routes, Router.HistoryLocation, (Handler,State)=>{
      class Wrapper1 extends Component{
        //static childContextTypes = {...}
        //getChildContext(){...}
        render(){
          return <Handler {...State} />;
        }
      }
      React.render( <Wrapper1/> , document.body );

     //or

      class Wrapper2 extends Handler{
        //static childContextTypes = {...}
        //getChildContext(){...}
      }
      React.render( <Wrapper2 {...State} /> , document.body );
    });

```

**Comment by nikhedonia** [comment]
any particular reason why it got closed ?

**Comment by gaearon** [comment]
I can't speak for @ryanflorence but it would help if you expanded the question to include:

1. What you've tried (full runnable example)
2. Expected behavior
3. Actual behavior

**Comment by taurose** [comment]
I could be wrong, but I think it's the same issue as #1769.

You probably don't want to create the `Wrapper` within `Router.run`, since that will remount all dom nodes and react components including the router itself, which triggers `router.stop()`.

Off the top of my head, creating a context wrapper for `<Handler />` should look like this:

```js
class Wrapper extends React.Component {
    // static childContextTypes = {...}
    // getChildContext(){...}
    render() {
      return this.props.children(); // react 0.13
      // return this.props.children; // react 0.14
    }
}

Router.run(routes, Router.HistoryLocation, (Handler, state) => {
  React.render(<Wrapper>{() => <Handler {...state} />}</Wrapper>, el); // 0.13
  // React.render(<Wrapper><Handler {...state} /></Wrapper>, el); // 0.14
}
```

**Comment by nikhedonia** [comment]
@taurose, yes seems like it.
I now switched to react-router v1.0 and solved my problem.

**Comment by ESTEBANMURUZABAL** [comment]
Hi @nikhedonia, Could you show me how did you upgrade your react-router code please? I am trying to do the same like this: 
Router.run(app.getComponent(), req.originalUrl, async function (Handler, state) {
to 
ReactDOM.render(app.getComponent(), req.originalUrl, async function (Handler, state) {

but I am getting this error: Target container is not a DOM element.
Could you point me out please what I am doing wrong?
