### ISSUE TITLE
Scroll behaviour in 1.0

### ISSUE THREAD

**Issue by marcelpanse** [rackt/react-router#1898]
Since upgrading to 1.0 the browser stopped scrolling to the top on a page change. I can't find anything about it in the upgrade guide or the docs, except for the link 'ScrollManagmentMixin' in the documentation, but that points to a 404 page :-(

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/blob/f61724c011d73454c5ac8ce5507709d458eb1828/UPGRADE_GUIDE.md#scrolling
