### ISSUE TITLE
Server Rendering in NodeJS

### ISSUE THREAD

**Issue by bernardhamann** [rackt/react-router#1908]
Hi, I just tried out the server rendering as described here:
https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md

And it is giving me this and other similar errors:
Failed propType: Required prop `history` was not specified in `RoutingContext`.

Im not sure how to get the props into the RoutingContext:

In the past I used this:

Router.run(routes, req.path, function (Root, state) {
       
        // This is just to get the data before rendering
        var pathString = state.routes[1].path.substr(1);
        var data = {};

        function renderPage (data){
            var html = React.renderToStaticMarkup(React.createElement(Root, state, data));
            var fullHtml = '<!doctype html>'  + html;
            res.send(fullHtml);
        }

        // This is the function that is called from the promise after the data returns
        renderPage(data)
    });

Any help will be appreciated

**Comment by michaelchance** [comment]
From what I understand, you should be using a MemoryHistory 
https://github.com/rackt/react-router/blob/master/docs/basics/Histories.md.  Also note that the 1.0.0 release candidate came out (I think) sometime today, so not all the docs are up to snuff, so you might check back in a couple days.

**Comment by bernardhamann** [comment]
thanks for the reply @michaelchance 

Im not sure if that is the only issue, it also give the following error messages:

Warning: Failed propType: Required prop `location` was not specified in `RoutingContext`.
Warning: Failed propType: Required prop `routes` was not specified in `RoutingContext`.
Warning: Failed propType: Required prop `params` was not specified in `RoutingContext`.
Warning: Failed propType: Required prop `components` was not specified in `RoutingContext`.

I think there might be a way that react-router can add all that stuff to the routing context, I just cant seem to figure it out.

**Comment by mjackson** [comment]
You're probably not matching any routes, so your `renderProps` are `null`.

> not all the docs are up to snuff

[The server rendering docs](https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md) are accurate.

**Comment by bernardhamann** [comment]
Thanks, will try again, maybe i missed something.

**Comment by haustraliaer** [comment]
Did you figuer this out @bernardhamann ?

I'm also playing around with server rendering of the new router API and have come up against the same problem. I can't quite figure out how to get `renderProps` to be anything but `null`.

Using the [server rendering docs](https://github.com/rackt/react-router/blob/master/docs/advanced/ServerRendering.md) example...

For `match({ routes, location }...` I've got location set to:
```
{ 
  pathname: '/',
  search: '',
  hash: '',
  state: { prop: 'something' },
  action: 'POP',
  key: null 
}
```

And `routes` looks like this:
```
import React from 'react'
import { Router, Route } from 'react-router'
import Main from './Main.js'

export default React.createClass({
  render() {
    return (
      <Router history={this.props.history}>
        <Route path='/' component={Main} />
      </Router>
    )
  }
})
```

Perhaps that's the problem?

**Comment by haustraliaer** [comment]
Ok I fixed my issue - it _was_ to do with the `routes` object.

Got my wires crossed exporting the routes as a "React" component.

So my new routes file look like:

```
import React from 'react'
import { Route } from 'react-router'
import Main from './Main.js'
import Test from './Test.js'

export default (
  <Route path='/' component={Main}>
    <Route path='test' component={Test} />
  </Route>
)
```

And now I can see my pre-rendered templates!

**Comment by bernardhamann** [comment]
Thanks! @haustraliaer , did not have a chance to look at this again. But will look at it later
