### ISSUE TITLE
IndexLink usage throwing error "React.createElement: type should not be null or undefined"

### ISSUE THREAD

**Issue by michaelchance** [rackt/react-router#1909]
I'm using es6 syntax, `import {IndexLink} from 'react-router';`.  I looked at the file in /modules and it seems like it should be working, so maybe it's a problem with the build?

**Comment by michaelchance** [comment]
Oh- for the moment I'm using the workaround of just using a <Link> component with `onlyActiveOnIndex={true}` as a prop, so no big deal.  Just wanted to make the powers that be aware.

**Comment by mjackson** [comment]
This is already [fixed in master](69a92404d1479f24d1db704e67a585ca2d1f0105). Please take a moment to verify that stuff isn't already fixed before opening an issue. Thanks! :)

**Comment by michaelchance** [comment]
Sorry about that!

**Comment by colllin** [comment]
@mjackson Are you sure it's fixed?  I'm seeing this in v1.0.0-rc3, which was published last week.

@michaelchance Thank you for the workaround.

**Comment by colllin** [comment]
My mistake, I was attempting to `import {IndexLink} from 'react-router-relay';`
It should be `import {IndexLink} from 'react-router';`

I'm sorry for the unnecessary notification, mjackson.

**Comment by chardskarth** [comment]
In case someone goes through this now in react-router@v4, I think `IndexLink` is [now missing](https://reacttraining.com/react-router/web/api). 
I've used `Link` instead imported from `react-router-dom`

```
import { Link } from 'react-router-dom';
```
