### ISSUE TITLE
Links with onlyActiveOnIndex set to true fail to be active using HashHistory due to _k query parameter

### ISSUE THREAD

**Issue by michaelchance** [rackt/react-router#1910]
See title.

**Comment by mjackson** [comment]
Can you please provide a failing test?

**Comment by ryanflorence** [comment]
might be what's going on: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#active-class

**Comment by mjackson** [comment]
Ya, that's probably what's going on.

You don't get "active" behavior for free anymore, @michaelchance. You need to opt-in by providing `<Link activeClassName>` or `<Link activeStyle>`.

**Comment by michaelchance** [comment]
My bad, it seems to be working.  A bit overzealous in my report!
