### ISSUE TITLE
No router in context

### ISSUE THREAD

**Issue by LookLikeAPro** [rackt/react-router#1911]
Doing this returns a blank object in my code:

    constructor(props, context){
        super(props);
        console.log(context);
    }

I am expecting to see the router object in there so I can use the `transitionTo` method.

It was mentioned [here](https://github.com/rackt/react-router/issues/1059) that "in the 1.0 API you don't need to ask for the router off of context." 

So is the solution to wait for 1.0 release, or can I somehow get router in context now?

**Comment by LookLikeAPro** [comment]
OK, I did not get the context because I forgot to put this, my bad!!

    static contextTypes = {
		router: PropTypes.func
	};

However I still want to know if this is getting deprecated for the "no context" approach

**Comment by michaelchance** [comment]
As far as I can tell this was deprecated, though not well documented.  I'm currently using the History Mixin with this.history.pushState(); as an alternative to this.context.router.transitionTo().

**Comment by LookLikeAPro** [comment]
Thanks that's good to know. Is there a ES6 way that doesn't use mixins?

**Comment by mjackson** [comment]
Use `this.context.history` as you can see [in the source](https://github.com/rackt/react-router/blob/c26aee0cd70f3455f070aa3a740ee012a9112a8c/modules/History.js#L5).

**Comment by halt-hammerzeit** [comment]
@mjackson `this.context.router` had `addTransitionHook`and `removeTransitionHook`
Is it now replaced by some kind of `var unlisten = this.context.history.listen(); unlisten()`?
Is it how the migration should be done?

**Comment by Neta-Alon** [comment]
Seems like the docs are outdated. As seen [here](http://stackoverflow.com/questions/33454456/this-context-history-undefined-while-using-link-on-child-component) and also tested by me, the `history` object isn't found in the `context`, but in the regular `props`.

Example:
```javascript
constructor(props, context) {
  super(props, context);
  console.log(props);
  console.log(context);
}
```

Props:
`Object {history: Object, location: Object, params: Object, route: Object, routeParams: Object…}`

Context:
`Object {}`

So one would use:
```javascript
this.props.history.pushState(null, '/');
```
(Don't forget to `.bind(this)` your functions in the constructor if using `props` outside of it)

**Comment by taion** [comment]
It's in both for route components.

**Comment by Neta-Alon** [comment]
That's weird because the component I used was App.
My routes:
```javascript
<Route component={App}>
    <Route path='/' component={Home} />
    <Route path='/login' component={Login} />
  </Route>
```

**Comment by omerts** [comment]
Any updates about using a callback with the history.listen?
