### ISSUE TITLE
Router and context in 1.0.0-rc1 and react 0.14.0-rc1

### ISSUE THREAD

**Issue by bkniffler** [rackt/react-router#1913]
Hey,
I'm using said versions of react-router and react plus redux and would not find an instance of `router` in `this.context` as I used to. Did anything related change?
```
ReactDOM.render(<Provider store={store} key="provider">
     <Router location={location} history={history} onError={(err)=>console.error(err)}>
          {routes}
     </Router>
</Provider>, container);
```

I'm missing the router for `router.transitionTo(...)` and the current `router.state`.

**Comment by bkniffler** [comment]
Okay, looks like we got `history` and `location` now instead.
```
   static contextTypes = {
      history: PropTypes.object.isRequired,
      location: PropTypes.object.isRequired
   };
```

**Comment by bkniffler** [comment]
There's something else I'm missing: how do I access the currently active branches and the current params? These were accessible via router.state, but are not present in location.

**Comment by bkniffler** [comment]
Okay, looks like the current params are injected as props into the active route component. I couldn't find a possibility to access the active branches, but I found I didn't really need that.

**Comment by johnnyreilly** [comment]
Hi @bkniffler,

Would you have an example repo to share - I'm attempting the port and crashing and burning.  I just discovered this as I was looking into [my issue](https://github.com/rackt/react-router/issues/2121).  Unfortunately I haven't been able to find a good example to refer to...

**Comment by bkniffler** [comment]
Hey, I gave up on react 0.14.0-rc1 and react-router 1.0.0-rc1 for now, until everything is more stable and other libraries adopt these new versions. I'm having great success with 0.13.3 and router 1.0.0-beta2.
