### ISSUE TITLE
IsActive Mixin undefined

### ISSUE THREAD

**Issue by kib357** [rackt/react-router#1914]
I`m trying to upgrade to rc1 from beta-3. In docs i see new mixin - IsActive:
import { Link, IsActive } from 'react-router';
but it returns undefined.

**Comment by kib357** [comment]
I noticed that IsActive mixin not exported from index.js...
Stable release on NPM? Seriously?

**Comment by mjackson** [comment]
Is the plan for people to use the `History` mixin instead, @ryanflorence ?

**Comment by ryanflorence** [comment]
woops, missed that in the upgrade guide, just added it, check out the table at the end: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#state-mixin
