### ISSUE TITLE
Documentation says query params are in `this.props.query`

### ISSUE THREAD

**Issue by trotzig** [rackt/react-router#1915]
The documentation around where query params are located in props is a bit confusing. [The README](https://github.com/rackt/react-router#whats-it-look-like) mentions `// route components are rendered with useful information, like URL params` and then right below there's a line using `this.props.userId`. The UPGRADE_GUIDE documentation mentions `this.props.query` (inferred from the table in the ["State mixin" section](https://github.com/rackt/react-router/blob/dcc7f6c94b56370c872a32cd7f80b2401601aa0f/UPGRADE_GUIDE.md#state-mixin)). The ["query-params" example](https://github.com/rackt/react-router/blob/master/examples/query-params/app.js) uses `this.props.location.query` to locate params. And so I'm pretty sure that's what I need to use. 

It would be good to get some better documentation around how to use query params. It's also likely I've missed something in the docs. The google index is probably not completely up to date given that v1.0.0 is fairly new.

**Comment by ryanflorence** [comment]
its `this.props.location.query`, go ahead and click "edit" on that doc in github, make some changes, send the pull request and we'll merge it.

**Comment by ryanflorence** [comment]
but yes, a query string guide would be awesome.

**Comment by trotzig** [comment]
I added a short section to the Introduction guide as well. Forgot to cross-reference the issue in the commit message though, so here's a link: https://github.com/trotzig/react-router/pull/2

**Comment by trotzig** [comment]
What would be a good place for a more thorough guide? I could add one, but I'm not sure where to put it.

**Comment by knowbody** [comment]
@trotzig I think you could put it in Recipes. I like the Introduction part, I can merge it but you need to send a PR.

**Comment by trotzig** [comment]
Ah, I got confused by editing these files directly from the web. I'll send a combined PR in a bit, just need to install git on this (borrowed) laptop.

**Comment by trotzig** [comment]
Here's the PR: https://github.com/rackt/react-router/pull/1928

**Comment by knowbody** [comment]
thanks :+1:

**Comment by rubencodes** [comment]
Hey guys, so I'm on R-R 1.0, and I'm trying to use query params; I've used `this.history.pushState(null, "/mypage", { param: "my param" })` which worked to successfully move me to the new page with the query param, but when I try to access `this.props` from within an event handler function defined in the react class, it's an empty object, so `this.props.location` is null. I've imported History and have the History mixin and everything...What could be wrong?
