### ISSUE TITLE
IndexRoute for childRoutes

### ISSUE THREAD

**Issue by zettadam** [rackt/react-router#1917]
I was wondering if there was a chance to add support for `indexRoute` inside a child route configuration in the same way `indexRoute` can be specified for root route configuration. For example:

```javascript
const rootRoutes = {
  path: '/',
  childRoutes: [ ... ],
  ...
  indexRoute: { component: Dashboard }
}
```

would render the `Dashboard` container for '/' path.

Would it be possible to provide the same or similar functionality for each child `Route`? I don't think it is possible at the moment.

**Comment by ryanflorence** [comment]
IndexRoute works for any route but an indexRoute. Did you try it and it didn't work?
