### ISSUE TITLE
rc1: cannot read property query of null.

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#1919]
https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L214 calls `listener` with the first argument of null and a state object as the second argument. 

`listener` in this case expects to be called with a location object as the first argument. https://github.com/rackt/history/blob/master/modules/useQueries.js#L28

**Comment by ryanflorence** [comment]
and here: https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L206 it gets the location from the history it wraps. They aren't subclasses so don't need to "keep the parent contract". The histories that `useRoutes` builds upon don't ever have an error case, but useRoutes does, so the arguments to `listen` are different.

That said, you're obviously seeing an issue, what does your code look like?

**Comment by BerkeleyTrue** [comment]
Yeah I see that the api for the two are different. Not sure why one is being called by the other.

Code is here https://github.com/freecodecamp/freecodecamp/tree/feature/jobs

**Comment by BerkeleyTrue** [comment]
![developer_tools_-_http___localhost_3000_jobs](https://cloud.githubusercontent.com/assets/6775919/9842119/4a423f1c-5a5e-11e5-8278-4bd327d941a8.png)

It seems somehow useQueries history object is calling `listen` method of the history object associated with useRoutes.

**Comment by BerkeleyTrue** [comment]
It could be that I am using `match` method client side.

**Comment by mjackson** [comment]
@BerkeleyTrue Can you give us a more specific link so we don't have to look through your codebase to find your route config?

**Comment by BerkeleyTrue** [comment]
using `match` [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/feature/jobs/common/app/app-stream.jsx)
using `Router` [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/feature/jobs/client/index.js)
using `RoutingContext` [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/feature/jobs/server/boot/a-react.js)

**Comment by BerkeleyTrue** [comment]
Alright, so I've figured it out. I am using `match` client side in an attempt to preserve symmetry that was present in 0.13 with `Router.run`. What I wasn't aware of is that `match` wraps the `history` object and returns its own. I was using the returned history object, feeding it to `Router` which in-turn wraps the history object again not realizing that the history object that it is wrapping is already wrapped.

The fix (more of a hack really) is to override the history object on the return value from `match` with the original one history object when used client side. 

If using `match` client side is something that is to be supported, maybe adding a flag to the wrapped history objects so that they are not rewrapped accidentally is in order?

**Comment by mjackson** [comment]
`match` was never intended to be used on the client (we only ever mention it in our server rendering docs).

Why don't you tell us what you're trying to accomplish and maybe we can suggest a better way?

**Comment by BerkeleyTrue** [comment]
I'm trying to capture the symmetry that was available in RR 0.13 in Universal Apps that came with using Router.run api. I was hoping that `match` would be equivalent to `Router.run`.

**Comment by halt-hammerzeit** [comment]
I was having this error too:

```
function addQuery(location) {
	      if (location.query == null) 
```

`TypeError: Cannot read property 'query' of null`

Your solution worked.
I was having the error because of using `<Route history={history} ...` before `match()` on the server. 
I fixed the error by removing the `history` attribute from the root `Route` and by moving history to `rendered_props` in
```
match({ routes, history, location }, (error, redirect_location, render_props) =>
{
			// used only on client for <Router history={history} ...>
			if (history)
			{
				render_props.history = history
			}
}
```

**Comment by BerkeleyTrue** [comment]
@rackt/owners this seems to be a common issue. Any chances of duct typing history in `match` to prevent double history wrap?

**Comment by Dattaya** [comment]
`react-router` 2.0 is soon to be released; have you guys figured something out regarding SSR? I would like to use `match` on the server and on the client for a better and simpler error handling, identical for both (an ability to return, say, page 401 access denied and 404 for all other action errors). 
Do I still need to use that hack that @BerkeleyTrue suggested:
```javascript
match({ location, history, routes }, (err, nextLocation, props) => {
  // props already has a history object
  // unfortunately this history object is wrapped by match, and Router will attempt to wrap it again
  // which will give you headaches. So here we override that history object with the first.
  // not a clean solution but it is the only solution at the moment.
  props.history = history;
...
```

**Comment by timdorr** [comment]
@Dattaya Yes, in 2.0.0 we are introducing the concept of a "transition manager", which encapsulates all the previous modification we did do history and now leaves it untouched.

**Comment by Dattaya** [comment]
Thank you, @timdorr, for your answer! I'll be waiting for the new react-router.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by Dattaya** [comment]
@BerkeleyTrue did you manage to build a lib with the same `match` for the client and for the server? This is my take on it: [gist](https://gist.github.com/Dattaya/d4d09eb3449c3f0e146e), [integrated into a simple boilerplate](https://github.com/Dattaya/isomorphic-redux-plus/tree/universal-router-context-decorators). It seems to be working fine but I don't know if it's safe to use `RouterContext` this way client-side instead of `Router`.
