### ISSUE TITLE
Bug: Redirect needs to be placed in correct order to work

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#1921]
The redirect here will *not* work

```
export const routes:ReactRouter.Route = (
  <ReactRouter.Route path="/" component={topNav.TopNavbar}>
     <ReactRouter.Route path="comments" component={cbox.CommentBox}/>
     <ReactRouter.Route path="comments2" component={redditView}/>
     <ReactRouter.Redirect from="/comments" to="/comments2" />
  </ReactRouter.Route>
);
```

However, if placed above the `comments` route, it will

```
export const routes:ReactRouter.Route = (
  <ReactRouter.Route path="/" component={topNav.TopNavbar}>
     <ReactRouter.Redirect from="/comments" to="/comments2" />
     <ReactRouter.Route path="comments" component={cbox.CommentBox}/>
     <ReactRouter.Route path="comments2" component={redditView}/>
  </ReactRouter.Route>
);
```

This goes against the documentation which says that the redirect can be put anywhere.

Also this means there is no place to put a redirect on the '/`, since there is no higher level element to place it on. This is demonstrated in #1920.

**Comment by pdeva** [comment]
So far the only way I have found to redirect is to do something like this:

```
export const routes:ReactRouter.Route = (
  <div>
    <ReactRouter.Redirect from="/" to="/comments"/>
    <ReactRouter.Route path="/" component={topNav.TopNavbar}>
       <ReactRouter.Route path="comments" component={cbox.CommentBox}/>
       <ReactRouter.Route path="comments2" component={redditView}/>
    </ReactRouter.Route>
  </div>
);
```

not sure if enclosing the routes in a `div` is supposed to be correct or not, but it works...

**Comment by mjackson** [comment]
This is a bug in your route configuration. Routes (and redirects) are matched in the order they are defined. I'll push an update to the docs. Also, we should probably warn (see #1923).

> not sure if enclosing the routes in a div is supposed to be correct or not, but it works

No, this is not correct. How did you get the idea that this is how our API works?

**Comment by pdeva** [comment]
i got the idea, cause it actually does work...

what is then the correct way to redirect `'/`` since it is the top level component?

**Comment by ryanflorence** [comment]
Don't put that path on the top level component

**Comment by pdeva** [comment]
umm isnt a path required?
if so then what path should i put in there, if not `'/'`?

**Comment by diegoaguilar** [comment]
Was this fixed? What what the workaround u had to do @pdeva?
