### ISSUE TITLE
Accessing route params from a component.

### ISSUE THREAD

**Issue by poeticninja** [rackt/react-router#1922]
First of all... the newest version of React Router is just awesome sauce. My server rendering never felt so smooth. Great job guys! :smile:

I did notice that you are no longer able to access the params or the query from the context (https://github.com/rackt/react-router/blob/master/modules/RoutingContext.js#L33). I do see they are being passed down as immediate props to the routes but I am needing to access the params multiple levels deep and passing props all the way down is not very efficient. Is there another way to access the route params further down?

**Comment by mjackson** [comment]
> Great job guys!

Thanks!

> Is there another way to access the route params further down?

No, there isn't. Once we hand the props to your route component our job is done. I supposed you could put them on context yourself if you wanted to.

**Comment by poeticninja** [comment]
It is very common for developers to use the router query and params for logic in applications. Consider dynamic authorization where you would hide or show elements based on a query or param. You would have to place the context on every route component just to provide this type of power in your whole application for your team to use.

I do think that if react router is already providing stuff to the context it would make sense to provide query and params. These are just too valuable for developers not to have easy access to.

Also developers will not be able to write shareable/open source components that rely on the react router query or params unless they layout in detail to the end user (other programmers using their shared code) that they would need to wrap every route component in a context wrapper just to pass down the query and params.

I feel by not giving the query and params as context it is only hurting instead of helping.

**Comment by taurose** [comment]
Keep in mind that *every* route component gets them as props, so it should be easy to pass them down as normal props.

In my mind, a component that defines those things as propTypes is much cleaner than one that expects them in context and uses a magic mixin. It'll be easier to test and reuse.

**Comment by poeticninja** [comment]
I am also noticing that the query and params are not on a route's onEnter method (https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#willtransitionto-and-willtransitionfrom). It has location but you are not able to do any logic for auth or redirecting based on params passed into that route from the router. This is not available even as props.

**Comment by poeticninja** [comment]
In regards to my last comment I am sorry for the confusion because the params are available in the onEnter method. The params are on the location object. This is a different location object then the one that is passed into context and had me confused. I expected them to be the same. This doesn't solve my original issue though.

**Comment by knowbody** [comment]
It seems like @mjackson and @taurose answered your question. If there is something what is still unclear, let me know and I try to help and reopen the issue.
