### ISSUE TITLE
What is  the correct way to Redirect '/'

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#1924]
I currently have code like this

```
export const routes:ReactRouter.Route = (
  <ReactRouter.Route path="/" component={topNav.TopNavbar}>
     <ReactRouter.Route path="comments" component={cbox.CommentBox}/>
     <ReactRouter.Route path="comments2" component={redditView}/>
     <ReactRouter.Redirect from="/" to="/comments2" />
  </ReactRouter.Route>
);
```

also since I am using `redux-react-router`, my render function is like this:

```
React.render((
      <Provider store={reduxStore}>
        {()=><ReduxRouter/>}
      </Provider>
) , document.getElementById('content'));
```

Since as described in #1921 and #1923  the current redirect of `'/'` needs to be above the `'/'` route, where do i put it, since it is already the top level component. Can someone describe what the correct code for above will look like?

**Comment by mjackson** [comment]
Have you tried

```js
  <Route component={topNav.TopNavbar}>
     <Redirect from="/" to="/comments2" />
     <Route path="/comments" component={cbox.CommentBox}/>
     <Route path="/comments2" component={redditView}/>
  </Route>
```

?

**Comment by pdeva** [comment]
hmm yes, that does seem to work.
however, assuming '/' is assumed the default path for the top most level route, doesn't it kinda work contrary to what is described in #1923 . I really think this behavior deserves some special note atleast in the documentation you plan for #1923 .
