### ISSUE TITLE
1.0.0-rc1 Documentation for DynamicRouting incorrect

### ISSUE THREAD

**Issue by jamiehill** [rackt/react-router#1927]
The documentation for 1.0.0-rc1 - DynamicRouting, incorrectly states the following signature is used for declaring async routes:

```
getComponents(callback) {
    require.ensure([], function (require) {
      callback(null, require('./components/Course'))
    })
  }
```

Looking at `getComponents.js`, the supplied arguments should be `location` then `callback`

```
....
} else if (route.getComponents) {
    route.getComponents(location, callback);
}
....

**Comment by ponty96** [comment]
yeah, thats true. I think that should be changed

**Comment by knowbody** [comment]
thank you @jamiehill. mind submitting a PR with a fix?

**Comment by jamiehill** [comment]
Sure thing ...

**Comment by ryanflorence** [comment]
closing in lieu of a pull request, github makes it really easy with the "edit" button on the page, thanks for helping out :)
