### ISSUE TITLE
Statics & willTransitionTo stopped working

### ISSUE THREAD

**Issue by pmatev** [rackt/react-router#1931]
Just upgraded to 1.0.0-rc1, and it seems that the old 

    statics: {
        willTransitionTo: function(transition, params, query, callback) {
            // do stuff...
            callback();
        }
    },

doesn't work any more. Can anyone confirm this issue or give a guide as to the new api for doing this?

**Comment by gpbmike** [comment]
Is this what you're looking for? [routerWillLeave](https://github.com/rackt/react-router/blob/v1.0.0-rc1/docs/api/Lifecycle.md#routerwillleavenextlocation)

Example: [Confirming navigation](https://github.com/rackt/react-router/blob/v1.0.0-rc1/docs/advanced/ConfirmingNavigation.md)

```js
import { Lifecycle } from 'react-router';

var Home = React.createClass({

  // Assuming Home is a route component, it may use the
  // Lifecycle mixin to get a routerWillLeave method.
  mixins: [ Lifecycle ],

  routerWillLeave(nextLocation) {
    if (!this.state.isSaved)
      return 'Your work is not saved! Are you sure you want to leave?';
  },

  // ...

});
```

**Comment by pmatev** [comment]
Not quite... I need to opposite, where the function will be fired just before entering the component. So I guess the equivalent of a `routerWillEnter()` if there is such a thing.

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#willtransitionto-and-willtransitionfrom

**Comment by pmatev** [comment]
Thank you! :)
