### ISSUE TITLE
PushState being ignored

### ISSUE THREAD

**Issue by jeremejevs** [rackt/react-router#1940]
I have a setup looking like this:

```javascript
export const history = createBrowserHistory(); // history@1.9.0
// ...
<Router history={ history }> // react-router@1.0.0-rc1
```

When I click a `<Link to='/somepage'>` or navigate there manually (either by typing the URL or pressing back / forward) - the URL changes and the router displays the component associated with `/somepage`.

However, if I import the `history` object elsewhere, and try `history.pushState(null, '/somepage')`, or I open up the console in my browser and do `window.history.pushState(null, null, '/somepage')`, the URL changes, but nothing else happens. If I navigate back and then forward with the browser, then it works as expected.

My setup is much more elaborate than in the snippet above, but I've triple-checked the essentials, and I'm fairly certain that I'm using the correct `history` object in all places that matter. Please, help me troubleshoot this and/or confirm that this is a bug.

**Comment by mjackson** [comment]
May be a dup of #1930

**Comment by jeremejevs** [comment]
Yeah, seen it, certainly looks similar, but wasn't sure.

**Comment by knowbody** [comment]
let's discuss it in #1930
