### ISSUE TITLE
1.0.0-rc1 Shared Index

### ISSUE THREAD

**Issue by jrouleau** [rackt/react-router#1941]
```json
  "react": "0.14.0-rc1",
  "react-dom": "0.14.0-rc1",
  "react-router": "v1.0.0-rc1"
```

I'm attempting to create a shared index. Think facebook.com or twitter.com. If you're not logged in, `path="/"` takes you to a landing page, but if you are logged in, it takes you to the main page of the dashboard / app.

Most importantly, I want to do this with code splitting / lazy loading. Going to `path="/"` while not logged in should not downloaded the chunks for the dashboard and vice versa.

I have tried this numerous ways. The closest I've come is nesting a two route `memoryHistory` router (`/landing` and `/dashboard`) on the `IndexRoute` of my main `browserHistory` router and setting the `memoryHistory` route  from my  `auth.onChange` cb. Works fairly well. Encountered a minor issue where the history context was wrong (for `Link`, etc.), but fixed that by overriding it with the `createElement` prop. At this point it is functional for single components, but I want to be able to nest routes under my dashboard (nav, tabs, etc.). If I do that now, they'll be nested under the `memoryHistory` router and not the `browserHistory` router.

Is there something I'm missing? Can this be done with the current API?

I'm thinking it could be solved with some sort of `<SplitIndexRoute/>` that would match based on some state/variable instead of a path.

Here's some pseudo code of what I'm thinking
```html
<Router>
  <Route path="/" component={App}>
    <SplitIndexRoute
        state={auth.isLoggedIn}
        value={true}
        onFail={redirectToLogin}
        component={Dashboard}>
      <IndexRoute component={Feed}/>
      <Route path="users/:id" component={Users}/>
      <!-- etc. -->
    </SplitIndexRoute>
    <SplitIndexRoute
        state={auth.isLoggedIn}
        value={false}
        component={Landing}/>
    <Route path="logout" onEntry={logout}/>
    <Route path="login" component={Login}/>
    <Route path="signup" component={Signup}/>
  </Route>
</Router>
```

The idea behind `onFail` would be to handle the situation where we match a nested route (absolute or relative) but fail the check. Useful for redirecting to a login page, etc. I envision it as similar to the onEntry trigger.

Let me know what you think. Can this be done with the current API? If not, would this functionality even be possible with the current system?

**Comment by elpete** [comment]
Not sure about using jsx, but I believe this should be possible using the plain object config:

```js
const routeConfig = [
  { path: '/',
    component: App,
    indexRoute: { component: isLoggedIn ? Dashboard : Landing }
  }
];
```

**Comment by elpete** [comment]
Oh, and I would guess the jsx syntax would be:

```js
<Router>
  <Route path="/" component={App}>
      <IndexRoute component={auth.isLoggedIn ? Dashboard : Landing} />
  </Route>
</Router>
```

**Comment by jrouleau** [comment]
Using object form here.

Although surprisingly simple, and I didn't even think of trying it, it doesn't entirely work. The ternary condition is calculated when the routes are loaded so logging in or out doesn't update the route without a page refresh.

If we can find a way to recalculate the component logic from an `auth.onChange` cb, this might work.

**Comment by jrouleau** [comment]
@elpete Thank you for pushing me in the right direction!

Had to reorder my routes a bit, but it's fully working now!

* Fully lazy: no components are loaded unless they're being displayed
* Root path (could be any path really) is fully shareable between 2+ components. Multiple sets of child routes might be possible with `getChildRoutes`. Not sure. Haven't tried.
* Can use `indexRoute` to dynamically load a default child for one or more components
* Stateful redirects
* Clean and no hacky workarounds

https://gist.github.com/jrouleau/3849f5432123af746b22

I'll see to putting an example together.

**Comment by ryanflorence** [comment]
you can also use `getChildRoutes` and return different routes based on whether or not you're authorized.
