### ISSUE TITLE
Multiple IndexRoutes cause IndexLink to be active incorrectly

### ISSUE THREAD

**Issue by khaledh** [rackt/react-router#1945]
Given this router setup:

```jsx
<Router>
  <Route path="/" component={App}>
    <Route path=":blogName" component={Blog}>
      <IndexRoute component={Home} />
      <Route path="posts">
        <IndexRoute component={PostList} />
        <Route path=":postId" component={PostDetail} />
      </Route>
    </Route>
  </Route>
</Router>
```
And somewhere in `<Blog>`:

```jsx
  <IndexLink to={`/${blogName}`}>Home</IndexLink>
  <Link to={`/${blogName}/posts`}>Posts</Link>
```

I get the following:

location | active links
------------ | -------------
`/myblog` | `Home`
`/myblog/posts` | `Home` and `Posts`
`/myblog/posts/5` | `Posts`

The first and third cases are expected, but I expect that in the second case that only `Posts` would be active. Is this a bug, or is there supposed to be a single `IndexRoute` in the route hierarchy?

**Comment by elpete** [comment]
Have you tried using `<IndexLink to={`/${blogName}/posts`}>Posts</IndexLink>` instead since it is also an IndexRoute?

**Comment by khaledh** [comment]
If I do that I get the following:

location | active links
------------ | -------------
`/myblog` | `Home`
`/myblog/posts` | `Home` and `Posts`
`/myblog/posts/5` | none

Which makes sense, since I'm telling react-router to make the `Posts` link active only when the location is at the index route itself, which in the third case is not true.

I think the problem is that `IndexLink` makes the link active when the current location is _any_ index route, not a specific one. That's why it's active both at `Home` and `Posts`. To make this work may require changing IndexLink to target the specific route specifed in its `to` attribute.

**Comment by khaledh** [comment]
I managed to work around the issue by flattening my route structure a bit:

```jsx
<Router>
  <Route path="/" component={App}>
    <Route path=":blogName" component={Blog}>
      <IndexRoute component={Home} />
      <Route path="posts" component={PostList} />
      <Route path="posts/:postId" component={PostDetail} />
    </Route>
  </Route>
</Router>
```
It worked in my case because `<PostList>` and `<PostDetail>` do not have a dedicated parent component under `<Blog>`. Had there been, e.g., a `<PostsHome>` as a parent to those two components, I wouldn't be able to flatten it like that. Also I feel that excessive flattening makes things less DRY in terms of defining the application structure/hierarchy.

**Comment by ryanflorence** [comment]
having a route w/o a component and only a path is kind of unexpected, but I've added a failing test case for an expected route config at #1957
