### ISSUE TITLE
Cann't load HashHistory in rc-1

### ISSUE THREAD

**Issue by hon** [rackt/react-router#1949]
I just upgrade react-router 1.0.0-beta2 to react-router 1.0.0-rc-1

```javascript
import HashHistory from 'react-router/lib/HashHistory';
```
This works well in 1.0.0-beta2, but in 1.0.0-rc-1, the loader throws:

Potentially unhandled rejection [3] Error loading "npm:react-router@1.0.0-rc1/lib/HashHistory" at http://localhost:9000/jspm_packages/npm/react-router@1.0.0-rc1/lib/HashHistory.js
Error loading "npm:react-router@1.0.0-rc1/lib/HashHistory" from "app" at http://localhost:9000/dist/app.js
Not Found: http://localhost:9000/jspm_packages/npm/react-router@1.0.0-rc1/lib/HashHistory.js (WARNING: non-Error used)

what's wrong with this.
Thanks.

**Comment by hon** [comment]
I found 'react-router@1.0.0-rc1/lib/HashHistory.js' is removed in this version.

**Comment by knowbody** [comment]
Hey the [History](https://github.com/rackt/history) has been separated from React Router, please have a look in the [docs](https://github.com/rackt/react-router/blob/master/docs/basics/Histories.md#histories)
