### ISSUE TITLE
location.pathname different if page refresh or transition

### ISSUE THREAD

**Issue by ioRekz** [rackt/react-router#1951]
Hello,

I'm relying on location.pathname to disable some elements in my menu bar based on the active route.
I'm not even sure this is the advised way but I manage to do what I want.

I've noticed that when I transition via Link, location.pathname will be 'name' and if I refresh the page I will have '/name'

Is this a bug ? Am I doing this the right way ?

**Comment by erosenberg** [comment]
I believe I'm having a similar problem.

**Comment by juhaelee** [comment]
Are you getting location from props?

**Comment by mjackson** [comment]
This sounds like a bug. Can you make a minimal, failing test case @ioRekz?

**Comment by knowbody** [comment]
I've just checked it and either through `this.props.location.pathname` or through `this.context.location.pathname` regarding the transition via `Link` or on the page refresh the paths are both the same. Closing for now, if this is an issue please submit the failing test case.

At least I couldn't reproduce it. I assume you are using React Router 1.0.0-rc1

**Comment by Jerry-Lau** [comment]
this.props.location.pathname
