### ISSUE TITLE
Rare Url, _k query ????

### ISSUE THREAD

**Issue by rodriguezivanb** [rackt/react-router#1952]
What is this?, How I can remove it?

![captura de pantalla de 2015-09-15 08 13 22](https://cloud.githubusercontent.com/assets/7519305/9877388/38e1bc1e-5b82-11e5-8730-a086ff1bb6f7.png)

**Comment by jakubsikora** [comment]
https://github.com/rackt/react-router/blob/master/docs/basics/Histories.md#createhashhistory

**Comment by rodriguezivanb** [comment]
Is there any way to hide ?

**Comment by jakubsikora** [comment]
You can use
https://github.com/rackt/react-router/blob/master/docs/basics/Histories.md#createbrowserhistory as per document.

`npm install history`

then in your router file

```
import createBrowserHistory from 'history/lib/createBrowserHistory';
...

<Router history={createBrowserHistory()}>
```
