### ISSUE TITLE
Jest throws Link warning

### ISSUE THREAD

**Issue by liviuignat** [rackt/react-router#1953]
Does somebody have any idea why testing a component with Link inside throws this warning in Jest? "Warning: A <Link> should not be rendered outside the context of history; some features including real hrefs, active styling, and navigation will not function correctly"

Thanks.

**Comment by ryanflorence** [comment]
Because your Link is not being rendered in the context of a `<Router/>`

**Comment by liviuignat** [comment]
Then how would you recommend to disable this warning? By mocking the Link component maybe?
