### ISSUE TITLE
Flux action firing with 1.0?

### ISSUE THREAD

**Issue by message** [rackt/react-router#1954]
How to support old action firing behaviour for flux with 1.0? 
```
	Router.run(function(Handler, state) {
		RoutingActionCreators.changeRoute(state);
		React.render(<Handler />, element);
	});
```

**Comment by ryanflorence** [comment]
we'd like to get some docs on this, but don't yet.  You'll use a combination of `match` and `RoutingContext` and set up your own `histon.listen` to own the routing action.
