### ISSUE TITLE
Warning: Location "/app/" did not match any routes

### ISSUE THREAD

**Issue by mjw56** [rackt/react-router#1955]
Hi guys,

I guess I have more of a question about hosting my app. I tried looking around the docs, I'm thinking maybe it has to do with [pattern matching](https://github.com/rackt/react-router/blob/master/docs/basics/RouteMatching.md)? I'm using 1.0.0-rc1.

I would like to use webpack bundle my app to a dist folder, and then use IIS to host the application (I'm on a windows machine and need to share the app on an internal network)

My routes look something like this:

```js
import React from 'react';
import { Route } from 'react-router';
import Root from './containers/Root';
import Feed from './containers/Feed';
import App from './containers/App';

export default (
  <Route component={Root} path="/">
    <Route component={App} path="app" />
    <Route component={Feed} path="feed" />
  </Route>
);
```

I bundle the application with webpack normally and use the output bundle in the index.html file.

I browse to the application on my local box:

http://my.machine.name/app

but then I get this error message in the console: 

```
Warning: Location "/app/" did not match any routes
```

If I change the routes file to do something like this:

```js
export default (
  <Route component={Root} path="*">
    <Route component={App} path="app" />
    <Route component={Feed} path="feed" />
  </Route>
);
```

it will work, but then no routes will load properly after that.

Is there some pattern matching magic I can do to make this work? Thanks.

**Comment by ryanflorence** [comment]
`<Route component={Root} path="/app">{/* ... */}</Route>`

**Comment by ryanflorence** [comment]
hmm, sorry but this looks like some pretty basic functionality that is well tested and all the examples are working, I can reopen if you find a bug somewhere.

**Comment by danmartinez101** [comment]
When you get that error, is there actually a trailing / in the address bar? Might be a long shot, but IIS sometimes does weird things when missing a trailing /

You might also want to try using [https://www.npmjs.com/package/serve](serve) temporarily to host the app without IIS while troubleshooting.

**Comment by Aourin** [comment]
What routes are you trying to load after that?

**Comment by mjw56** [comment]
@Aourin any child routes

@danmartinez101 yes, I do notice that it appends a '/' to the end of the route. Is that what is causing the issue?

When I run the above app with something like webpack dev server it will run fine with no issues.

The thing with IIS, as you probably know, is that it requires an alias at which you will navigate to to run your app. So, '/', is no longer the main route in a sense, but really could be anything... '/home', '/app', '/foobar' etc. When navigating to 'http://my.machine.name/app' I don't have my routes setup to handle /app, only '/'.

This is probably more SO content, so I can take it over there, but I couldn't tell by the docs if there was a way to handle this scenario.

**Comment by danmartinez101** [comment]
You will probably have better luck on SO but one last thing I can recommend trying is instead of a '/' path for your root component, make your root components path = "/app/" or "/app" if that is truly the base path from IIS. Otherwise, maybe someone on SO will have had similar experience and has a solution.

**Comment by mjw56** [comment]
Thanks @danmartinez101. If I set the root component path to '/app' and the IIS base url to '/app' everything works fine.

**Comment by danmartinez101** [comment]
excellent :D Glad that worked out for you
