### ISSUE TITLE
When back button is hit, the page stays at scrolled position instead of top of page.

### ISSUE THREAD

**Issue by erosenberg** [rackt/react-router#1958]
I saw this was a thing in previous versions, but it's important that I can do this in 1.0. Every component in my routes should automatically load at the top of the page, and it doesn't seem like 'ignoreScrollBehavior' is a thing anymore.

Is this an issue that ya'll are already working on?

**Comment by nick** [comment]
There's a comment about this in the upgrade guide:

https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#scrolling

**Comment by erosenberg** [comment]
Oh - I must've been reading the upgrade guide incorrectly. I thought the 'Scrolling' section ended before willTransitionTo and willTransitionFrom. Can I apply these to every route in a nested route? I tried to before and it didn't work.

**Comment by erosenberg** [comment]
well onEnter doesn't seem to trigger when transitioning between pages. Am I doing something wrong?

**Comment by prattsj** [comment]
@erosenberg: can you post some code? it would make it easier to help. :)

**Comment by erosenberg** [comment]
Unfortunately I can't post too much since I'm using it for work, but essentially, I'm creating routes in one file, and then in my main entry file, I'm cloning each route and adding the 'onEnter' function to each.

```
let cloned_pages = routes.props.children.map((route, i) => {
      return React.cloneElement(route, {
          onEnter: this.handlePageTransition,
          key: 'route' + i,
      });
});

// Create new root Route with newly sprinkled children
let cloned_routes = React.cloneElement(routes, routes.props, cloned_pages);
let history = new BrowserHistory();

React.render((
  <Router
        createElement={ createElement }
        history={ history }
        children={ cloned_routes } />
  ), document.getElementById('content'));
```

**Comment by taurose** [comment]
> it doesn't seem like 'ignoreScrollBehavior' is a thing anymore.

`ignoreScrollBehavior` allowed you to opt of the router's built-in scrolling behavior for certain routes. Since scrolling isn't implemented yet, `ignoreScrollBehavior` is actually the default ;) I think you're looking for `ScrollToTopBehavior`.

I don't see how `onEnter` helps here. It's only fired when the route changes from inactive to active, not when it remains active after a URL change.

There's `<Router onUpdate />` which I think you could use until there's a built-in solution:

```js
<Router onUpate={() => window.scrollTo(0, 0)} ... />
```

**Comment by erosenberg** [comment]
Hmm - this doesn't appear to work more than once. Is there a reason for that or could it just be the way I have my app configured?

This is my router instance:

```
React.render((
       <Router
           createElement={ createElement }
           history={ history }
           children={ cloned_routes }
           onUpdate={() => window.scrollTo(0, 0)}
        />
 ), document.getElementById('content'));
```

**Comment by erosenberg** [comment]
Currently I'm testing by manually adding a function to scroll to the top in each component's proper lifecycle methods. it scrolls to the top after all the data is loaded, but I want this to happen before.
Am I using the wrong lifecycle method?

**Comment by knowbody** [comment]
the solution provided by @taurose is definitely working, and it's something what is suggested at the moment.

**Comment by vitalybe** [comment]
> `<Router onUpate={() => window.scrollTo(0, 0)} ... />`

Note that there is a typo in @taurose comment. Should be **onUpdate**.

**Comment by jhalaa** [comment]
Maybe this is because of the browser window's history object? History object has a property scrollRestoration which was set to auto in my case.Setting this to manual solved my problem.

```
function scrollToTop() {
    window.scrollTo(0, 0)
    if ('scrollRestoration' in history) {
        history.scrollRestoration = 'manual';
    }
}

<Router onUpdate= {scrollToTop} history={browserHistory}>
....
</Router>
```
