### ISSUE TITLE
createHistory() (via history) fails when the base route is not the domain root

### ISSUE THREAD

**Issue by itsthatguy** [rackt/react-router#1960]
When using nginx to serve your application at a url such as, `http://mydomain.com/some/base` `createHistory()` cannot determine the application root url.

You get the following error when trying to visit your application: 

```
Warning: Location "/some/base" did not match any routes
```

**Comment by itsthatguy** [comment]
My guess is that this is something that needs to be handled in nginx

**Comment by knowbody** [comment]
there is no point to open two the same issues, this issue is related to History so I'm closing this one, let's discuss it in [rackt/history#58](https://github.com/rackt/history/issues/58).

**Comment by itsthatguy** [comment]
You've both closed the issue, can you please reopen the issue?

**Comment by itsthatguy** [comment]
@knowbody You've both closed the issue, can you please reopen the issue?

**Comment by knowbody** [comment]
sure

**Comment by mjackson** [comment]
Fixed (see https://github.com/rackt/history/issues/58)

**Comment by knowbody** [comment]
thanks Michael!

**Comment by itsthatguy** [comment]
That'll do ;)
