### ISSUE TITLE
what happened to the http://rackt.github.io/react-router/ docs page?

### ISSUE THREAD

**Issue by hugotox** [rackt/react-router#1963]
That page was really nice to read and find things. GH pages are an usability pain, please put that page back :)

**Comment by prattsj** [comment]
Docs are now available right here in github alongside the code. Find updated links and a table of contents in the 0.13.x branch's README. :)

https://github.com/rackt/react-router/tree/0.13.x

**Comment by hugotox** [comment]
Yes, I see the docs. But It's extremely hard to find things, I was wondering if you guys have plans to get the docs page back

**Comment by knowbody** [comment]
@hugotox see #1999

**Comment by benknight** [comment]
Hey look, more people who think this is really inconvenient!

**Comment by earthdan** [comment]
http://rackt.github.io/react-router/ was really nice. I miss the dark theme verymuch
