### ISSUE TITLE
IndexRedirect component

### ISSUE THREAD

**Issue by taion** [rackt/react-router#1966]
The pattern from https://github.com/rackt/react-router/blob/v1.0.0-rc1/examples/redirect-using-index/app.js#L44 should be pulled out into a separate `IndexRedirect` component. It seems like a sufficiently common use case that it shouldn't just be a cookbook recipe from an example.

**Comment by knowbody** [comment]
if that is a common use case, it might be worth merging it, thoughts @ryanflorence @mjackson ?

**Comment by taion** [comment]
I feel like for something relatively simple like this, it's better to have it as a component than as a recipe in an example. I definitely use this pattern.

**Comment by chentsulin** [comment]
+1 for this, very simple to use and understand.
