### ISSUE TITLE
Using <Route components={ obj } /> breaks React.Children.map

### ISSUE THREAD

**Issue by richardfickling** [rackt/react-router#1968]
`React.Children.map` assumes `this.props.children` is either a single child or an array (https://facebook.github.io/react/tips/children-props-type.html). This utility function is used by many libraries (for example, Radium) and is broken by the latest release of react-router, because `<Route components={ obj }/>` turns `this.props.children` into a keyed object.

**Comment by mjackson** [comment]
This is an intentional API decision that lets you use [multiple components as named children](https://github.com/rackt/react-router/blob/master/docs/api/Route.md#components) in a single route component.

`this.props.children` is an opaque type that is being used by many different React libraries to mean something other than just node, array, or `null`. In [react-motion](https://github.com/chenglou/react-motion)'s `<Spring>` component, for example, `this.props.children` is a function.

**Comment by jinroh** [comment]
From the React v0.14 Release Candidate breaking changes notes :

> Plain objects are no longer supported as React children; arrays should be used instead. You can use the createFragment helper to migrate, which now returns an array.

Isn't this going to cause problems ?

**Comment by gaearon** [comment]
On the opposite, it's going to make things easier: you'll no longer pass `this.props.children` by mistake and expect it to work. To clarify, when you received named `children` in router, you're not supposed to just put them into `render`: you should do something like

```js
render() {
  return (
    <div>
      {this.props.children.sidebar}
      {this.props.children.content}
    </div>
  )
}
```

It was never the intention for them to be used as `this.props.children` as an object map, so it's actually good that 0.14 doesn't support this anymore.

**Comment by th0r** [comment]
So maybe rename it to `routeComponents` or something?

**Comment by richardfickling** [comment]
Can anyone chime in on https://github.com/FormidableLabs/radium/issues/358?

**Comment by ianobermiller** [comment]
Why was the decision made to keep this in `children`, and not pass them as props instead?

As I mentioned in https://github.com/FormidableLabs/radium/issues/358#issuecomment-140833140:

> This is not the same as `react-motion`, where they've created a component that *accepts* a different type for `children`. `react-router` is *passing* a different type for `children` to normal components, one that is not inline with the rest of React.

**Comment by mjackson** [comment]
I think @ianobermiller is right in this case. We should probably give people a `children` object that looks like other `children` objects. Accepting a different kind of `children` as a prop is a different discussion.

**Comment by ianobermiller** [comment]
@mjackson thanks for following up. Will you go with children as props instead?

**Comment by mjackson** [comment]
@ianobermiller Ya, that's probably what we'll do. Not 100% sure yet.

**Comment by taion** [comment]
Another option might be not to use children at all, and just use props with the specified names, i.e. `this.props.sidebar` and `this.props.content`.

**Comment by ianobermiller** [comment]
@taion that is exactly what I meant by "children as props"

**Comment by taion** [comment]
:+1:  solid plan

**Comment by panayi** [comment]
+1

```
<Route component={Page}>
```

would just be a shortcut for:

```
<Route components={{ main: Page }}>
```

and the component is available in `this.props.main`. Although IMO it shouldn't be at the root: 

```
const {main, someOtherPartial } = this.props.outlets
