### ISSUE TITLE
How to pass init data with server rending in rc-1

### ISSUE THREAD

**Issue by Yixi** [rackt/react-router#1969]
````javascript``
match({routes,location}, (error, redirectLocation, renderProps) => {

        //var locales = 'zh-CN';
        var locales = "en-US";

        var injectData = {
            initData: {
                userInfo: {
                    username: req.params.name
                },
                bookmarks:API.bookmarks.getInitBookmarks()

            },
            locales:locales,
            messages:i18n[locales]
        };

        var newProps = assign({},renderProps,injectData);

        console.log(newProps);

        if(redirectLocation){

        }else if(error){

        }else if(renderProps == null){

        }else{
            res.render('default',{
                markup:React.renderToString(<RoutingContext {...newProps}/>),
                inject:'window.__INJECTED = ' +JSON.stringify(injectData)
            });
        }
    });

```

I use like this ,but I can't my inject data in component with this.props

**Comment by nightwolfz** [comment]
I'd like to know this as well. Currently I'm doing it in a very hacky way:

```
var routes = function(store){
    return (
        <Route component={App} store={store}>
            <Route path="/" component={Main}/>
        </Route>
    )
};
export default routes;
```

"store" is what I'm injecting into props.

```
match({routes: routes(store), location}, (error, isRedirect, renderProps) => {
    return new Promise((resolve, reject) => {
                return resolve({
                    renderProps: renderProps,
                    isRedirect: isRedirect
                }); // used by ReactDOMServer.renderToString(<RoutingContext {...renderProps}/>),
            });
});
```

And then I use it like this in my App component
```
this.props.route.store
```

This seems very wrong but it works. Can anyone help us out here?

**Comment by nightwolfz** [comment]
Try the following, it should work :)

```
return new Promise((resolve, reject) => {
    ...
    match({routes, location}, (error, isRedirect, renderProps) => {

        function createElement(Component, props){
            return <Component {...props} {...store} />;
        }

        return resolve({
            renderProps: <RoutingContext {...renderProps} createElement={createElement}/>,
        });
    });
    ...
});
```

**Comment by Yixi** [comment]
The RoutingContext source code 
https://github.com/rackt/react-router/blob/master/modules/RoutingContext.js#L55L77

It does't pass the customize props to the Router,  only the React-router pre-define props. I tried merge the inject data to the this.props.params like this:

```javascript
assign(renderProps.params,injectData);
```
but I think this is a wrong way too.

**Comment by coma** [comment]
This is my current approach:
```javascript
import React from 'react';

class DataWrapper extends React.Component {

    getChildContext () {

        return {
            data: this.props.data
        };
    }

    render () {

        return this.props.children;
    }
}

DataWrapper.childContextTypes = {
    data: React.PropTypes.object.isRequired
};

export default DataWrapper;
```
so you can use it on the server like:
```javascript
// data is fetched from mongo or whatever
ReactDOMServer.renderToString(<DataWrapper data={ data }><RoutingContext {...renderProps}/></DataWrapper>)
```
or on the browser like:
```javascript
var data    = JSON.parse(document.getElementById('data').innerHTML),
    history = createBrowserHistory();

ReactDOM.render(<DataWrapper data={ data }><Router history={ history }>{ routes }</Router></DataWrapper>, document.getElementById('app'));
```

What do you think?

**Comment by nightwolfz** [comment]
How are you passing the props from DataWrapper to the routed components?

**Comment by coma** [comment]
Using context like:
```javascript
class SomeRoutedComponent extends React.Component {

    constructor (props, context) {

        super(props, context);
        this.state = context.data.someData;
    }
}

SomeRoutedComponent.contextTypes = {
    data: React.PropTypes.object.isRequired
};

export default SomeRoutedComponent;
```

**Comment by nightwolfz** [comment]
@coma Thanks! Works wonderfully!

**Comment by knowbody** [comment]
Thanks for answering @coma

**Comment by brickyang** [comment]
@coma where is the `id="data"` element? Since it's `var data    = JSON.parse(document.getElementById('data').innerHTML)`

**Comment by coma** [comment]
@brickyang it's present in my index.html!

My approach is slightly different now that I'm using https://github.com/rackt/react-redux, but the store rehydration on the client side looks pretty similar to the example above.

**Comment by brickyang** [comment]
@coma Thx for replying. Can you give me more hint about the `id="data"` element? Sorry I am a newer. 

My `routes.js` is `ReactDOM.render(<DataWrapper data={data}><Router history = {history}>{routes}</Router></DataWrapper>, document.querySelector('#app'));`

and my html templat is

`<body>`
  `<div id="app">{{ content|safe }}</div>`
  `<script src="http://localhost:8080/js/app.js"></script>`
`</body>`

and my root route js file is

`export default class Admin extends React.Component {`
  `render() {`
`    return (`
`      <div className="wrap">`
`        // children elements`
`      </div>`
`    );`
`  }`
`}`

where the `id="data"` element should be supposed to present?

**Comment by brickyang** [comment]
@coma Got it. Thx!

**Comment by jwietelmann** [comment]
Does it feel wrong to anyone else that this should be closed because you can hack around the issue using an experimental React feature that's likely to break in future releases? Is there a downside to just allowing arbitrary props to be passed down instead, so that @nightwolfz's `createElement` method would work?
