### ISSUE TITLE
Link not showing as active

### ISSUE THREAD

**Issue by chrisdrackett** [rackt/react-router#1974]
do I need to do anything special for a Link to use its active class? I can verify the URL matches, but my link isn't getting an active className.

**Comment by prattsj** [comment]
You'll need to actually supply the active class name (or the styles you'd like to apply directly). There's a demonstration of this feature in the Animations example: https://github.com/rackt/react-router/tree/master/examples/animations.

:)

**Comment by prattsj** [comment]
Documentation:
https://github.com/rackt/react-router/blob/master/docs/api/Link.md#activeclassname

**Comment by chrisdrackett** [comment]
Glad to see the docs have been updated!

**Comment by prattsj** [comment]
Yeah, looks like it was previously only in the upgrade guide. :/ Good catch. :)

**Comment by lanwin** [comment]
https://github.com/rackt/react-router/issues/1974

**Comment by lanwin** [comment]
Is there a reasion why activeClassName has no default anymore? active as default seems to make sens.

**Comment by gaearon** [comment]
Yes, please see https://github.com/rackt/react-router/issues/1873.
