### ISSUE TITLE
v1.0.0 planning

### ISSUE THREAD

**Issue by Spy-Seth** [rackt/react-router#1976]
I've a lot to rework to do close to the react-router in my application. And I'm asking myself should I update now the react-router to use the RC1? I do not want to take the risk to have a too early version of react-version in production and do not want to be block by this. 

Do you have planned the path to release the v1.0.0? release candidate planning? estimated date?

**Comment by knowbody** [comment]
@Spy-Seth I would say you can start migrating now. There shouldn't be any breaking changes between 1.0.0RC and 1.0

The 1.0 should be released in upcoming weeks
