### ISSUE TITLE
routerWillLeave is not confirmable

### ISSUE THREAD

**Issue by G3z** [rackt/react-router#1979]
this is my component
```javascript
import React from 'react';

import {Link, Lifecycle } from 'react-router';

const secret = 'supersecretpassword';

const Admin = React.createClass({
	mixins: [ Lifecycle ],
	getInitialState: function() {
		return {
			password: ''
		};
	},

	routerWillLeave(nextLocation) {
		if (nextLocation.pathname === '/wifi' && this.state.password !== secret ) {
			return false;
		}
	},

	render() {
		return (
			<div className="container adminContainer">
				<Link className="confirmButton" to="/wifi"/>
			</div>
		);
	}
});

export default Admin;

```

if I try to open `/wifi` with the wrong state I'm correctly blocked otherwise I can see the location update in the browser but not the view.
if I remove the mixin i can navigate but obviously i have no pass check

Am I doing something wrong ?

**Comment by G3z** [comment]
Routing table
```javascript
export default (
	<Route path="/" component={App} >
		<IndexRoute component={Home}/>
		<Route path="pin" component={Pin}/>
		<Route path="print" component={Print}/>
		<Route path="admin" component={Admin}/>
		<Route path="wifi" component={Wifi}/>
	</Route>
);
```

**Comment by namjul** [comment]
I am experiencing the same situation.

**Comment by knowbody** [comment]
mind sending PR with minimal failing test?

**Comment by mjackson** [comment]
You should be using the `onEnter` hook for auth. `routerWillLeave` is for preventing navigation *away* from a page. `onEnter` can prevent unauthorized navigation *to* a page.

**Comment by namjul** [comment]
Update to master resolved it.

**Comment by WilfredGreyling** [comment]
Ignoring the security issue in the OPs question, I am also unable to navigate to a new page if routerWillLeave method exits in a component. Even a blank method blocks navigation. Returning true has no effect. On 1.0.0-rc1. What should the routerWillLeave function return to allow moving along?
