### ISSUE TITLE
Problem with animation if you keep router state in redux store

### ISSUE THREAD

**Issue by HriBB** [rackt/react-router#1981]
Hey

I've been asking around on Reactiflux without success.

I have a problem when doing router css transition animations with redux-react-router. Some of my redux selectors depend on router params to extract the right data and there is a problem when navigating away from the view. When animation starts, router params are different, my selector returns undefined data and I have to show a blankpage, or I get an error.

Is there a way to somehow prevent render() of route component when animating leave? Maybe I'm missing something really obvious here ...

This is my redux selector
```
function select(state) {
  const data = state.locationsBySlug;
  const slug = state.router.params.location;
  const location = data.locations[slug] || null;
  return {
    loading: data.loading,
    error: data.error,
    cblocation: location
  };
}
```

**Comment by knowbody** [comment]
did you solve this issue? I think you should just return `null` if you don't have a data and then render the component once you have it. Not sure if I understood your problem correctly.

If this is still an issue, let me know and we reopen.
