### ISSUE TITLE
history.isActive

### ISSUE THREAD

**Issue by apucacao** [rackt/react-router#1984]
Hey folks,

I just upgraded to RC1 and things are generally working great. Thank you :)

I have a question about `isActive`. I am using classes, and am trying to follow the suggestion [History mixin docs](https://github.com/rackt/react-router/blob/master/docs/api/History.md) and [this page](https://github.com/rackt/react-router/blob/master/docs/advanced/NavigatingOutsideOfComponents.md).

However it looks like the `history` object from that I'm creating doesn't have a `isActive` method. I took a look at the source code the router and it seems that `isActive` is added by the router itself.

If that's the case and is meant to be that way, then I'm curious about what others are doing.

Thanks,

Alexis

**Comment by prattsj** [comment]
Mixins don't work with ES6 classes. You'll need to either revert to using `React.createClass()` for defining components in which you *really* need to use a mixin, or use some alternative method for making mixins work with ES6 classes.

Useful resources:
- [React docs](https://facebook.github.io/react/docs/reusable-components.html#mixins)
- [react-router discussion](https://github.com/rackt/react-router/issues/659)

**Comment by halt-hammerzeit** [comment]
Well, it says for me: `TypeError: history.isActive is not a function`

Here: https://github.com/rackt/react-router/blob/master/modules/Link.js#L103
