### ISSUE TITLE
Programmatic redirect in 1.x?

### ISSUE THREAD

**Issue by theogravity** [rackt/react-router#1986]
I'm trying to upgrade to 1.x, but am having problems trying to find a substitute for programmatically doing a redirect.

I used to have named routes and would pass the `router` down the context. I would sometimes have events that fire that would trigger something like this:

`this.context.router.replaceWith('<route_name>')`

What's the equiv for 1.x? I couldn't find anything in the upgrade documentation.

**Comment by theogravity** [comment]
From the `react-router` Slack room:

`this.props.history.replaceState(null, <path>)`

like

`this.props.history.replaceState({}, '/manage/card/12')`

**Comment by sheltonial** [comment]
@theogravity you don't happen to have a server side example of programmatically redirecting also?

**Comment by wizawu** [comment]
:white_check_mark:
