### ISSUE TITLE
Problem: ReactCSSTransitionGroup transitionLeave css being called after the this.history.pushState has rendered the new page

### ISSUE THREAD

**Issue by trevorbernard** [rackt/react-router#1987]
I have a DrawerComponent that used to close immediately in react-router 0.13.x when using the Navigation mixin and this.transitionTo but no longer the case with 1.0.0-rc1

**Comment by mjackson** [comment]
Have you followed the steps in [the upgrade guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md) for upgrading from 0.13 to 1.0? You have to give us more information in order for us to help you.

**Comment by trevorbernard** [comment]
@mjackson I did follow the upgrade guide. What other information do you need?
