### ISSUE TITLE
Using old history

### ISSUE THREAD

**Issue by Mosho1** [rackt/react-router#1988]
Is there a way to use 1.0.0 with the way 0.13.3 handled history? I have a pretty fragile setup (angular app mixed with react, with both routers as we transition to react) and something breaks history when I try to upgrade. 

I need async loading, else I would stay with 0.13.3. It's either solve history or figure out another way to load async routes.

**Comment by knowbody** [comment]
Can you be more specific? What do you mean *something* breaks the history? some code or error stack trace would be helpful

**Comment by mjackson** [comment]
Sorry, @Mosho1. The 1.0 API breaks compatibility with 0.13 in numerous ways. However, it's also much more flexible in terms of managing page history. If you can give us an idea of what you're trying to do we might be able to help.
