### ISSUE TITLE
Single page of docs please

### ISSUE THREAD

**Issue by benknight** [rackt/react-router#1999]
I can't easily read the docs now that it's been fragmented up into several pages.  It was much better before!

**Comment by jamischarles** [comment]
I he the exact same issue. Discoverability is very poor. I was searching for something last night and had to click through 4 or 5 different sections. I gave up after 15 min or so.

**Comment by knowbody** [comment]
For now the docs are as they are on Github, I think you can navigate through them pretty easily. If you having problems finding something you can use Github search. As soon as we find more time we will work on the website. If you can suggest particular places in the docs which are missing something or are confusing I'd appreciate the feedback and I'm happy to refactor those parts

**Comment by jamischarles** [comment]
@knowbody Couldn't find how to trigger a route change from JS (either inside a component or outside). I'm migrating an app that's using BB Router to React Router. The most useful thing I could find was in the upgrade guide.

**Comment by benknight** [comment]
> I think you can navigate through them pretty easily.

Sadly not true.  I've had to resort to using Google's cached version of the old docs.  Being able to use the browser "Find in page" feature on a full page of docs is much more efficient than having to guess which section something is in.

**Comment by jamischarles** [comment]
> Being able to use the browser "Find in page" feature on a full page of docs is much more efficient than having to guess which section something is in.

100% agree with this. I was wishing for that.

**Comment by prattsj** [comment]
Hey guys, talked with @knowbody, and we hear ya. We want to make it easy to understand and use the router, so we're going to put all the docs into a single page. Thanks for the feedback; we appreciate it!

**Comment by jamischarles** [comment]
:tada: yay

**Comment by mjackson** [comment]
@prattsj :+1:

**Comment by mjackson** [comment]
@benknight @jamischarles Either of you are welcome to submit a PR for this. You don't have to wait for us to do it! :)

**Comment by knowbody** [comment]
Thanks to @prattsj! Solved in #2012
