### ISSUE TITLE
Refresh browser occur error: "Error in event handler for (unknown): TypeError: Cannot read property 'data' of null",

### ISSUE THREAD

**Issue by xushao0305** [rackt/react-router#2002]
I follow the react-router examples huge-apps to write a sample example. But occur a error every refresh the browser.the error tree:
   

![image](https://cloud.githubusercontent.com/assets/6148159/9956608/b1d91cb4-5e2c-11e5-8a04-1ae11b9c8292.png)

my code:

  
![code](https://cloud.githubusercontent.com/assets/6148159/9956636/d8f15690-5e2c-11e5-8fe0-d4cebbb312b5.png)

react version:^0.13.3
react-router： 1.0.0-rc1

How can I fix this error?

thanks

**Comment by taurose** [comment]
The error is caused by a chrome extension ([json-handle](https://chrome.google.com/webstore/detail/json-handle/iahnhfdhidomcpggpaimmmahffihkfnj?hl=zh-CN)). Try again without it.

**Comment by xushao0305** [comment]
@taurose .Thanks. It works fine after remove json-handle.
