### ISSUE TITLE
stringifyQuery cannot be overridden

### ISSUE THREAD

**Issue by smashercosmo** [rackt/react-router#2003]
Here is a demo [repo](https://github.com/smashercosmo/react-router-stringify-query-issue). As you see custom stringifyQuery method is never being called.

**Comment by taurose** [comment]
`useQueries` is [applied internally](https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L32) by the router. The router component `<Router>` [passes the query configuration](https://github.com/rackt/react-router/blob/master/modules/Router.js#L51-L55) from its props.

In other words, don't use `useQueries` with `<Router>`, but pass your custom `parseQueryString` and `stringifyQuery` as props: `<Router parseQueryString={..} stringifyQuery={...} />`
