### ISSUE TITLE
How handle optional prefix in routes

### ISSUE THREAD

**Issue by Bloomca** [rackt/react-router#2004]
Hi!

I have a problem – I have an optional prefix for any route which looks like "/ca/en/english".
But I have to parse it and treat *only* if it will succeed my regex (something like /\/[a-z]{2]\/[a-z]{2}\/[^/]+\//). So, what is the best approach to make it possible with react router?

I saw [this one](https://github.com/rackt/react-router/issues/929), but, to be honest, this approach seems like the invention of my own router.

Any ideas?

Thanks!

**Comment by mjackson** [comment]
See https://github.com/rackt/history/issues/61
