### ISSUE TITLE
Async transition hooks gone in v1.0?

### ISSUE THREAD

**Issue by erikras** [rackt/react-router#2006]
One of the things I loved about react-router was that I could fetch the data that my route needed _before_ the route switch occurred, so there would never be any flicker of an unloaded page. This has been one of the central goals of [my universal project](https://github.com/erikras/react-redux-universal-hot-example).

From what I can tell from the docs, in v1.0, there is no longer any way to pause a route transition until an asynchronous action is complete. Is this true?

If it is, I would be very sad to see this useful functionality discarded.

**Comment by timdorr** [comment]
It's async-compatible both in [`react-router`](https://github.com/rackt/react-router/blob/master/modules/TransitionUtils.js#L47-L55) and [`history`](https://github.com/rackt/history/blob/master/modules/createHistory.js#L109-L125). Where are you having difficulties?

**Comment by erikras** [comment]
Oh, good. So there are still `hooks`. It wasn't obvious to me how to apply a common hook to all routes, like what [used to be](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/helpers/universalRouter.js#L32) the third param to `Router.run()`. Can you point me in that direction?

**Comment by timdorr** [comment]
Luckily, I've been following your project :smile: 

You're going to have to use some combination of the `history` transition hooks and a HoC similar to [`Lifecycle`](https://github.com/rackt/react-router/blob/master/modules/Lifecycle.js).  

I'm actually looking at accomplishing this via [`react-resolver`](https://github.com/ericclemmons/react-resolver). It certainly seems like a promising library. It's sort of a Relay/Falcor Lite.

**Comment by halt-hammerzeit** [comment]
@timdorr I looked at the `Lifecycle` code and looks like RC1 transition hooks are synchronous and not asynchronous:
https://github.com/rackt/react-router/blob/713c2b0d2f1e0dae06456e0f74a34d32a175d7a5/modules/useRoutes.js#L128

Therefore they won't be usable for pausing routing until data fetches.
I think there should not be any pause, one should display a spinner instead.
With such approach transition hook can still be synchronous.
But how can we call `fetchData` on the page being routed to?
The hook is only called like this: `result = hooks[i](location)`
Just the new(?) location, not the new component or whatever.
And the exact component instance is needed.

**Comment by timdorr** [comment]
@halt-hammerzeit Those hooks are called within [an async-compatible loop in `matchRoutes`](https://github.com/rackt/react-router/blob/713c2b0d2f1e0dae06456e0f74a34d32a175d7a5/modules/matchRoutes.js#L115-L123). 

Even then, I'm not seeing where the `transitionHook` function is used. It's not exported in the enhanced history object. It looks like dead code to me.
