### ISSUE TITLE
Best Pattern for fetching async data on route begin

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#2008]
I think the one thing the current router lacks is fetching async data when a route is hit, and showing a loading spinner while that happens.

While i saw mention of react-router-async-props in places, it seems that project is no longer active.

Here is how I currently do this in my application. Wondering if someone can tell me if there is a better way to achieve this:

I am using redux along with react-router.

On hitting a url like `/profile`, in the React component's `componentWillMount()` method, I have something like:

```
componentWillMount()
{
  dispatch(action("FETCH"));
  $.get("/myprofile"). then( 
         (data) => dispatch(action("UPDATE")(data)));
}
```
my reducer is like this:

```
function initialState() {
        return { loading: true, data: null };
    }

function reducer(state =initialState(), action) {
        if (action.type === ("FETCH" ))
            return initialState();
        else if (action.type === ("UPDATE" ))
            return { loading: false, data: action.payload };
        return state;
    };
```

In my component, I just check for the reducer's `loading` field to display a spinner or the content.

The downside of this approach is that the data fetched now resides in the store even after we navigate to a different route and the component is no longer present.

Wondering if there are better ways to accomplish the above, that also clear the fetched data on component destruction.

**Comment by blairanderson** [comment]
this Is an architecture/data issue, not specific to router. 

 Different people bootstrap data differently. You components will always have extra knowledge to know if data is existent/stale/loading/etc.

**Comment by vojtatranta** [comment]
I posted comment here #2101 where you might some clue.
As @blairanderson this goes beyond react-router and depends or architecture.

**Comment by knowbody** [comment]
yep, this goes beyond the React Router, but there are couple of good discussions going on, please look at similar issues. Also this one seems interesting #2101
