### ISSUE TITLE
RC as latest version in npm

### ISSUE THREAD

**Issue by Lysholm** [rackt/react-router#2010]
Is the 1.0.0-rc1 release actually a stable release? If not wouldn't it be better to hold back on updating the version field? Currently you unexpectedly get a rc version showing up when doing  "npm install react-router" and "npm outdated". Not been that long with node and npm, if beta packages were showing up as default in my distros package manager i'd be worried.

Others are releasing "stable" semversion releases with it as peerDependancies (react-router-bootstrap), so it gets even more confusing.

**Comment by mjackson** [comment]
Yes, 1.0.0-rc1 is the latest stable release.
