### ISSUE TITLE
Need to colocate routes under the same parent in a single file outside of the parent.

### ISSUE THREAD

**Issue by Tlvenn** [rackt/react-router#2013]
Hi,

The huge app examples sows how we can decouple our routes but each slicing bring up only one child into the parent. How can we bring up many childs at once from a given file ?

Example:

```
const rootRoute = {
  path: '/',
  component: require('./components/App.jsx'),
  childRoutes: [
    require('./features/user')
  ]
};
```

In the above, I would like for the user module to be able to publish more than 1 route under the `App` parent. Right now the module export a single route. Could we return an array and then have React Router add each element to the childRoutes of the parent ?

Thanks !

**Comment by Tlvenn** [comment]
I should mention that the above can easily be implemented like that by the end user:

```
const rootRoute = {
  path: '/',
  component: require('./components/App.jsx'),
  childRoutes: _.flatten([
    require('./features/user')
  ])
};
```

But I somehow feels the Router should take care of that if possible.

**Comment by taurose** [comment]
Have you considered exporting a route with children? Instead of `export default [route1, route2];`:

```js
export default {
  childRoutes: [route1, route2]
};
```

I'm not 100% sure if this will result in the same path matching behavior though.

**Comment by Tlvenn** [comment]
but that would limit the childs i can add to a single require where I actually want to be able to do that:

```
const rootRoute = {
  path: '/',
  component: require('./components/App.jsx'),
  childRoutes: _.flatten([
    require('./features/foo'),
    require('./features/bar')
  ])
};
```

where `foo` and `bar`are exporting a set of routes.

**Comment by taurose** [comment]
Perhaps I'm not understanding you right, but with what I proposed you could do that

```js
// root
const rootRoute = {
  path: '/',
  component: require('./components/App.jsx'),
  childRoutes: [
    require('./features/foo'),
    require('./features/bar')
  ]
};

// features/foo (multiple routes)
const routeFoo1 = ...;
const routeFoo2 = ...;

export default {
  childRoutes: [routeFoo1, routeFoo2]
};

// features/bar (single route)
const routeBar = ...;
export default routeBar;
```

**Comment by Tlvenn** [comment]
Ha yes indeed that would work as well. Thanks for the tip, didnt think about having a path less route to hold further routes.

**Comment by Tlvenn** [comment]
As much as i like cleanup up issues and closing them fast, is the solution provided by @taurose intuitive or does it feel more like a hack ? For me it's a hack, it works but it's not elegant and it feels weird to introduce an empty shell route just for the purpose of holding some childs.

Shouldn't it be better for clarity and code readability if the router would just flatten the childRoutes in the manner outlined above transparently ?

**Comment by Tlvenn** [comment]
@mjackson any thoughts ?
