### ISSUE TITLE
Why createHistory() defaults to a parser and createLocation() is not

### ISSUE THREAD

**Issue by igl** [rackt/react-router#2015]
I am trying to fill up some input fields with data from the query-string.
On the server this fails because location.query is not set:

```js
    componentDidMount () {
        const { location, distance } = this.props.location.query
        this.refs.searchInput.value    = location
        this.refs.searchDistance.value = distance
    }
```

My workaround is currently parsing the qs with express and appending it to the location object before passing it to the router.

```js
    router.use(function (req, res) {
        const location = createLocation(req.url);
        location.query = req.query
        match({ routes, location }, function (error, redirectLocation, renderProps) {
        ...
```

So. With a qs parser infront of react-router this is not really an issue.
It would be nicer to have a more transparent API for server and client or have this described somewhere with server-side rendering. Maybe this is an Issue with `history.createLocation`? Am i missing something?

**Comment by mikhail-riabokon** [comment]
Same problem https://github.com/rackt/history/issues/60

**Comment by grrowl** [comment]
Cross-posted from the other issue, I'm also having this issue on the server with `match`:

```jsx
  let location = createLocation(req.url),
      history = useQueries(createHistory)();

  // First we match our location to our route
  // <https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md>
  match({ routes, history, location }, (error, redirectLocation, renderProps) => {
    // renderProps won't ever have a "query" property, as useQueries should have set
    invariant(typeof renderProps.query !=== 'undefined', 'renderProps.query not defined');
  });
```

**Comment by igl** [comment]
Since query parsing can be done in different ways i thought this should totally be pluggable!
Then I found [this](https://github.com/rackt/history/blob/master/docs/QuerySupport.md)... so that is already the case!

It all makes sense to me now and issue could be reduced to "Why `createHistory()` defaults to a parser and `createLocation()` is not".

Probably because it's unnecessary in a server environment where you very likely already have one in place and unlikely that you do in the client.

I would be happy with this being documented better in the server-rendering docs.

**Comment by mjackson** [comment]
This issue should be resolved by https://github.com/rackt/history/pull/79

That PR makes `createLocation` an instance method of `history` objects. So whatever history enhancers you use have a chance to modify the `location` object. Let's follow up in that PR.

**Comment by lancetw** [comment]
@mjackson https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md
Server Rendering will be broken after upgrade.
