### ISSUE TITLE
Nesting "/" with "*" won't work

### ISSUE THREAD

**Issue by TCMiranda** [rackt/react-router#2017]
Hello,

I have just upgraded my app with react-router 1.0, but I can't reproduce the same pattern I was using before:

That's my final guess:

```jsx
<Route path="/" component={ App }>

    {/* Internal routes, logged in, app ui */}
    <Route path="app" component={ Internal }>

        <IndexRoute component={ Dashboard }/>

    </Route>

    {/* External routes, not logged in */}
    <Route path="*" component={ External }>

        <IndexRoute component={ Home }/>

    </Route>
</Route>
```

The `<Route path="*" >` is not working for me..

Thanks!

**Comment by onemanstartup** [comment]
I think it's something to with webpack or server. Having the same issue.

**Comment by TCMiranda** [comment]
I am also using webpack, with source-map, and babel.

index
```
    React.render((
        <Router history={history}>
            { routes }
        </Router>
    ), ...);
```

And `{routes}` is imported from the snippet above.

With webpack 1.12

Thanks

**Comment by onemanstartup** [comment]
@TCMiranda do you have `this.props.children` in App? Try to insert this in render function.

**Comment by TCMiranda** [comment]
Yes, I do, the `<Route path="app" component={ Internal }>` route is working normally

**Comment by knowbody** [comment]
@TCMiranda what do you mean by "it's not working for me"? Do you get any errors?

I've made a quick example of what you were trying to do and it works fine for me:

```js
import React, { PropTypes, Component } from 'react';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import { Router, Route, Link, Redirect, IndexRoute } from 'react-router';

class Navigation extends Component {
  render() {
    return (
      <div>
        <ul>
          <li><Link to='/'>Main</Link></li>
          <li><Link to='/app'>Internal</Link></li>
          <li><Link to='/someExternalRoute'>External</Link></li>
        </ul>
      </div>
    );
  }
};

class Internal extends Component {
  render() {
    return (
      <div>
        Internal component
        {this.props.children}
      </div>
    );
  }
}

class Dashboard extends Component {
  render() { return <div>Dashboard</div>; }
}

class External extends Component {
  render() {
    return (
      <div>
        External component
        {this.props.children}
      </div>
    );
  }
}

class Home extends Component {
  render() { return <div>Home</div>; }
}

class App extends Component {
  render() {
    return (
      <div>
        <h1>App</h1>
        <Navigation />
        {this.props.children}
      </div>
    );
  }
}

export default class Root extends Component {
  render() {
    return (
      <Router history={createBrowserHistory()}>
        <Route path='/' component={App}>
          <Route path='app' component={Internal}>
            <IndexRoute component={Dashboard}/>
          </Route>
          <Route path='*' component={External}>
            <IndexRoute component={Home}/>
          </Route>
        </Route>
      </Router>
    );
  }
}
```

**Comment by jackmoore** [comment]
@TCMiranda Did you get this problem worked out?  I'm experiencing a similar issue.

@knowbody My application is setup similar to your example, but for me the `External` component isn't being passed any children.  `this.props.children` is undefined, which leaves me unable to render `Home`.

**Comment by knowbody** [comment]
@jackmoore if you can setup the app I can play with with this issue I'll try to help. I don't know how to reproduce your issue

**Comment by jackmoore** [comment]
@knowbody Before I go through setting something up, did you try on your own example to see what happens when you visit the `/` path?

**Comment by knowbody** [comment]
what do you expect to happen?

**Comment by jackmoore** [comment]
That if the path is `/` then the `App` component's this.props.children would be the `External` component, rather than undefined.

**Comment by knowbody** [comment]
no, why should it have `External` component. When you navigate to `/` it mounts `App` Component. If you want to have some other component mounted together with `App` then use `IndexRoute`.

The `*` is matched on everything besides `/`

**Comment by jackmoore** [comment]
@knowbody Oh ok, I see what you are saying.  You can disregard my comments then.  I assumed from your example that `/` should render the `Home` component.

**Comment by knowbody** [comment]
@jackmoore  So do you want everything with `/app` to take you to `Internal` component and all the rest to `External` component?

**Comment by TCMiranda** [comment]
@knowbody Thank you, thats what I was expecting also @jackmoore. 

The problem is that the upgrading wiki says:

>NotFound route

>Not found really confused people, mistaking not finding resources from your API for not matching a route. We've removed it completely since it's simple with a * path.

>// v0.13.x
><NotFoundRoute handler={NoMatch}/>

>// v1.0
><Route path="*" component={NoMatch}/>

Which is not true, because `<Route path="*"` does not match empty.

**Comment by knowbody** [comment]
@TCMiranda you're welcome. and it does if `/` is not defined before

**Comment by TCMiranda** [comment]
Ok, that makes sense... 

Thanks for clarifying!
