### ISSUE TITLE
Can't get index route working.

### ISSUE THREAD

**Issue by Industrial** [rackt/react-router#2018]
Hi.

These are my routes: https://github.com/Industrial/test-loopback/blob/e17666584f39d71282ef9255ffc7cc667bad4ca2/src/client/js/Router.js#L48

The public index route isn't found at all. I don't see my component constructor getting called. Why? :-)

**Comment by dyyylan** [comment]
This is what the `<IndexRoute>` component is for. You can just replace the child `<Route path="/" components={components} />` with `<IndexRoute components={components} />`

**Comment by Industrial** [comment]
I've tried `<IndexRoute>` now but I get the same result: https://github.com/Industrial/test-loopback/blob/92008a272f5841827b70566dfe2332ec984bf849/src/client/js/Router.js#L50

**Comment by dyyylan** [comment]
You're missing an `<IndexRoute>` component on line 49 as well.

I was able to reproduce your problem in my app by switching my working `<IndexRoute>` to `<Route path="/">` like you have. You should only have one `<Route path="/">` at the root level.

**Comment by knowbody** [comment]
thanks for answering this question @dyyylan
