### ISSUE TITLE
Need a means of preventing scroll to top on a pre-route basis

### ISSUE THREAD

**Issue by kloots** [rackt/react-router#2020]
@ryanflorence, I saw your comment in issue #1898 that you're redesigning scroll behavior in advance of the 1.0 release. I wanted to ask if this includes the ability to prevent scrolling to top on a per-route basis?

Our use case: if a user action triggers a modal, the scroll position of the underlying page should be preserved. We're on 1.0 Beta 3 and if a user action triggers a modal the page scrolls to the top before the modal is rendered.

**Comment by mjackson** [comment]
We need to re-introduce scroll management functionality post 1.0, but yes. When we do it will include the ability to control scroll behavior on a per-route basis.

**Comment by chadoh** [comment]
Does this exist now? It's not mentioned in the docs, as far as I can see. It makes for a pretty frustrating user experience, to not have this!
