### ISSUE TITLE
Verify 3 code examples in API.md doc: component instead of components prop?

### ISSUE THREAD

**Issue by pedrottimark** [rackt/react-router#2022]
1. https://github.com/rackt/react-router/blob/master/docs/API.md#components-1
component={Profile} ?
Because of the capitalization, I assumed that Profile is a component class.

```js
// So with the router it looks like this:
const routes = (
  <Route component={App}>
    <Route path="groups" components={{main: Groups, sidebar: GroupsSidebar}}/>
    <Route path="users" components={{main: Users, sidebar: UsersSidebar}}>
      <Route path="users/:userId" components={Profile}/>
    </Route>
  </Route>
)
```

2. https://github.com/rackt/react-router/blob/master/docs/API.md#example-1
component={Groups} ?
component={Users} ?
Because of the capitalization and previous examples, I assumed that Groups and Users are component classes, not objects of name:component pairs.

```js
React.render((
  <Router history={history}>
    <Route path="/" component={App}>
      <Route path="groups" components={Groups} />
      <Route path="users" components={Users} />
    </Route>
  </Router>
), node)
```

3. https://github.com/rackt/react-router/blob/master/docs/API.md#example-2
Because of the capitalization, I assumed that Profile is a component class. Similar to item 1 above.

```js
React.render((
  <Router>
    <Route path="/" component={App}>
      <Route path="groups" components={{main: Groups, sidebar: GroupsSidebar}} />
      <Route path="users" components={{main: Users, sidebar: UsersSidebar}}>
        <Route path="users/:userId" components={Profile} />
      </Route>
    </Route>
  </Router>
), node)
```

**Comment by knowbody** [comment]
thanks, fixed in https://github.com/rackt/react-router/commit/67eddacb9ecc278e91064f9ebd16dc6c255b556a
