### ISSUE TITLE
Failed proType while running webpack on server side

### ISSUE THREAD

**Issue by orenykb** [rackt/react-router#2023]
While generating server side bundle (using webpack) im getting this error:
"Warning: Failed propType: Invalid prop `location` supplied to `Router`, expected instance of `Location`. Check the render method of `Provider`."

This is not happening if i use the code without bundling.

Any ideas?
```
const location = new Location(req.path, req.query);
        const reducer  = combineReducers(reducers);
        const store    = applyMiddleware(promiseMiddleware)(createStore)(reducer);

        Router.run(routes, location, (err, routeState) => {
            if (err) return console.error(err);

            if (!routeState) return res.status(404).end('404');
            //function renderView() {
                const InitialView = (
                    <Provider store={store}>
                      {() =>
                          <Router {...routeState} />
                      }
                    </Provider>
                );
                const componentHTML = React.renderToString(InitialView);

```

**Comment by prattsj** [comment]
For one thing, it looks like you're mixing 1.0.x API with 0.13.x API.

`Router.run()` is from the old API. You don't need to use it if you're using the `<Router>` JSX component from 1.0. Just pass your Router component into `React.render()`.

1.0 Server Rendering Docs:
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md

0.13 Server Rendering Docs:
https://github.com/rackt/react-router/blob/0.13.x/docs/guides/server-rendering.md
