### ISSUE TITLE
Cannot resolve module 'history'

### ISSUE THREAD

**Issue by nicolashery** [rackt/react-router#2024]
If I want to create my own history object to pass to `<Router>` I need to use the [history](https://github.com/rackt/history) module as explained in the docs, but since it is installed nested under `react-router/node_modules`, it cannot be found by Webpack or Node.js.

A workaround is needed, either by using `import history from 'react-router/node_modules/history'` (the solution I'm using), or by `npm install --save history` (but that means I would be bundling 2 different `history` modules).

Should `history` be definied as `peerDependency` (don't know if that is still a thing with the newest versions of `npm`), or should it be exposed by `react-router`?

**Comment by mjackson** [comment]
It looks like [peer dependencies won't automatically be installed](http://blog.npmjs.org/post/110924823920/npm-weekly-5) in npm 3. Instead, you'll get a warning about needing to install the other package.

For now I'd just recommend installing `history` yourself and not worrying too much about the duplicate copy. npm 3 is going to have a much flatter `node_modules` directory anyway, so you may not actually end up with 2 copies.
