### ISSUE TITLE
Custom query string parse/stringify passed to "Router" and not "history"?

### ISSUE THREAD

**Issue by nicolashery** [rackt/react-router#2025]
This isn't necessarily a bug, but it took me a while to figure out what was going on, so I want to make sure that this is what's expected :)

I had this (`Qs` is my custom query string module):

```javascript
var history = useQueries(createHashHistory)({
  parseQueryString: Qs.parse.bind(Qs),
  stringifyQuery: Qs.stringify.bind(Qs)
});

var routes = (
  <Router history={history}>
    //...
  </Router>
);
```

And I couldn't understand why it wasn't working. After a while, I finally figured it out (I hadn't seen the [Router API docs](https://github.com/rackt/react-router/blob/master/docs/API.md#router)):

```javascript
var history = createHashHistory();

var routes = (
  <Router history={history} parseQueryString={Qs.parse.bind(Qs)} stringifyQuery={Qs.stringify.bind(Qs)}>
    //...
  </Router>
);
```

My questions are:

- Is there a reason `Router` is overriding the `parseQueryString` and `stringifyQuery` of the `history` object passed to it?
- If the answer to above is "yes", maybe adding a note about that in [guides/basics/Histories](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md) could help avoid confusion?

**Comment by iMoses** [comment]
Took me awhile as well to figure it out, the router's `useQueries` has overwritten my `history` configuration, causing a flow in which my local history's `createPath` will never be executed with a query since the query will always be interpreted in the router's history first.

**Comment by mjackson** [comment]
I think the best solution here would be to just remove the `parseQueryString` and `stringifyQuery` props entirely and suggest that people who want custom query string handling learn how to roll their own history objects.

**Comment by nicolashery** [comment]
This was closed without any explanation :(

From the API docs, I see that `parseQueryString` and `stringifyQuery` are still props to the `Router`. Is that there to stay then?
