### ISSUE TITLE
Router.run() doesn't exist

### ISSUE THREAD

**Issue by halt-hammerzeit** [rackt/react-router#2027]
The `.run()` method seems to be removed from the `Router` class
https://github.com/rackt/react-router/blob/master/modules/Router.js

**Comment by prattsj** [comment]
Please read the docs for version 1.0, which has many breaking API changes from 0.13.
https://github.com/rackt/react-router/tree/master/docs

**Comment by prattsj** [comment]
There's also an upgrade guide as noted in the README.
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md

**Comment by halt-hammerzeit** [comment]
@prattsj oh, thx
