### ISSUE TITLE
1.0.0rc not compatible with react-engine

### ISSUE THREAD

**Issue by Dindaleon** [rackt/react-router#2028]
Hello,

I am getting the following when trying tp update react-router to 1.0.0rc from 0.13.3

    npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-engine@2.0.0 wants react-router@~0

https://github.com/paypal/react-engine/issues/88

**Comment by chrisirhc** [comment]
This seems like something that react-engine needs to resolve, rather than any action needed on this repository.

**Comment by gaearon** [comment]
This means `react-engine` doesn't support `react-router@1.x`.
Please file this with `react-engine`.
