### ISSUE TITLE
No more transition hooks in RC1. How to pause routing for data fetching?

### ISSUE THREAD

**Issue by halt-hammerzeit** [rackt/react-router#2033]
On the server side, rendering is done through transition hooks (`addTransitionHook`) which check if a component has a `fetchData` method and then it calls it (for each matched route).
After all the data is fetched it calls the `callback`.

How can be server side rendering done with the new RC1?

**Comment by mikhail-riabokon** [comment]
You can reach an example of transition hooks in this (repo)[https://github.com/mikhail-riabokon/redux-form-universal-example]. It's an example of isomorphic redux-form.

**Comment by halt-hammerzeit** [comment]
@mikhail-riabokon thanks, I'll copy & paste your tricks into my project.
as for pausing routing, i guess, in RC1 it's no longer possible and noone should do that?

**Comment by mikhail-riabokon** [comment]
Some transitions hooks are already some kind of pausing, or that do you mean?

**Comment by halt-hammerzeit** [comment]
I meant the older methods `addTransitionHook` where it seemed that one could pause routing from inside React components.
Anyway, I guess, the older methods aren't needed, so I'll close the issue for now.
Maybe I'll reopen it, we'll see

**Comment by halt-hammerzeit** [comment]
@mikhail-riabokon Mihail, I copy pasted your code and it works for server-side rendering. But what about client side rendering?

In you example you have a single route:

```
export default (
  <Route path="/" component={App}/>
);
```

What if an application has several routes: how then are you gonna call asynchronous page preloading methods?
Theoretically, you could call them in `componentDidMount` of a page.
But, then you should prevent this code in `componentDidMount` from being called on the server.
This introduces an undesired "if-else" in all page components.
Previously one could `addTransitionHook` and call preloading methods there.
Now there'll be another way.
So, I guess, your `redux-form-universal-example` works for a single-route application but doesn't work for a real application.

**Comment by mikhail-riabokon** [comment]
In v1.0.0-rc1, I did not find another way. ```componentDidMount``` [does not work on server](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount)

For server rendering you can use transitions hooks, for client ```componentDidMount```, wherewre how much routes you have.

And it's just an example of how I am trying to solve this problem. Agree, that two different methods for the same action (fetching data for example) it's not perfect solution, but it's better than nothing.

**Comment by halt-hammerzeit** [comment]
Yes, i guess, that will do for a solution for this case. Thanks for
assistance.
