### ISSUE TITLE
Consider splitting `history` Router prop into `historyOptions` and `historyProvider` (or something)

### ISSUE THREAD

**Issue by jedd-ahyoung** [rackt/react-router#2035]
It looks as though there have been a few closed issues pertaining to the state object in the browser's querystring. Looking through these issues, I saw that there's a bit of documentation on the subject in the docs folder (and a lot of broken links in the closed issues). It looks as though it's necessary to install a dependency that's already used by the library in order to opt out of the query key.

Originally, I was going to suggest a quick and dirty solution - add a  `queryKey` prop, to easily opt out of this behavior. However, looking further, I think there's a better solution.

Since the library depends upon a specific implementation, let us pass the function directly, and the configuration in a separate property. This allows us to avoid having to explicitly declare the dependency if we only need to use the default `createHashHistory` strategy.

An example might look like this:

	import React from 'react';
	import ReactDOM from 'react-dom';
	import { Router, Route } from 'react-router';
	import { App } from './components/app.js!jsx';

	ReactDOM.render((
		<Router historyOptions={{ queryKey: false }}>
			<Route path="/" component={App} >
				<Route path="/child" component={Child} />
			</Route>
		</Router>
	), document.getElementById('app'));

If we wanted to change the strategy, we could do something like this:

	<Router historyProvider={createBrowserHistory} historyOptions={{ queryKey: false }}>

I don't know about the names - I'm sure they could be improved - perhaps "historyStrategy" and "historyConfig" or something, no idea. (I'm terrible at naming things.) However, I think the concept is sound, and could work well with a minimal change to the codebase - looks like only the Router element would need to be changed.

What do you guys think? Any thoughts?

**Comment by mjackson** [comment]
I think I'd like to enforce a more strict separation of history from the router codebase, rather than include `historyOptions` as a `<Router>` prop. When I try to introduce convenience props like these, I just end up with bugs (see #2025). :/
