### ISSUE TITLE
set children to IndexRoute 

### ISSUE THREAD

**Issue by flocks** [rackt/react-router#2037]
Hello guys.

I upgraded react-router from 0.13.3 to 1.0.0  today and I'm experiencing the following issue : 

Previously, I was doing something like this to define my routes.

```javascript
<Route handler={App} name="app" path="/">
    <DefaultRoute handler={Home} />
    <Route handler={Home} name="home" path="/">
            <Route handler={subHome1} name="subHome1" path="/" />
            <Route handler={subHome2} name="subHome2" path="/subHome2" />
            <Route handler={subHome3} name="subHome3" path="/subHome3" />
            <Route handler={subHome4} name="subHome4" path="/subHome4" />
      </Route>
      <Route handler={OtherPage1} name="OtherPage1" path="/otherPage1" />
       <Route handler={OtherPage2} name="otherPage2" path="/otherPage2" />
                    ...etc...
```

So as you may understand, when the user entered / , the SubHome1 was rendered.

But I struggle trying to reproduce the same behaviour with v1.0.0. I tried to do something like

```javascript
<Route component={App} history={history} path="/">
          <IndexRoute component={Home}>
                <IndexRoute component={subHome1}  />
               
                <Route component={subHome2} path="subHome2" />
                <Route component={subHome3}  path="subHome3" />
                <Route component={subHome4} path="subHome4" />
           </IndexRoute>

            <Route component={OtherPage1} path="OtherPage1" />
            <Route handler={OtherPage2} name="otherPage2" path="/otherPage2" />
                    ...etc...
```

But it seems it's not possible to define  sub routes into IndexRoute. The only way I found to make this work is to set a different path to SubHome1. But it's not the behaviour I want to implement.

May be I'm too tired today to see the obvious solution :)

I hope I didn't create a doublon, and that I made myself clear :)

**Comment by TCMiranda** [comment]
Related to https://github.com/rackt/react-router/issues/2017

I Tried to workaround with `<Route path="*" ` but didn't worked.

**Comment by flocks** [comment]
Thx pour referencing the issues @TCMiranda :)

**Comment by knowbody** [comment]
please see https://github.com/rackt/react-router/issues/1950
