### ISSUE TITLE
Version without npm install is broken

### ISSUE THREAD

**Issue by Eagllus** [rackt/react-router#2043]
I want to use react-router without having to install npm.
I have found a few version besides the CDN version.

They all have the same issue.
```
import React from 'react'
import { Router, Route, Link } from 'react-router'

console.log(Router, Route, Link);
```

Output: `undefined`, `function e(){r(this,e),null!=t&&t.apply(this,arguments)}`, `function e(){i(this,e),null!=t&&t.apply(this,arguments)}`

So it seems `Router` is not defined but `Route` and `Link` work fine.

**Comment by knowbody** [comment]
could you point me to the CDN version you were trying?

**Comment by Eagllus** [comment]
Yes the same from your readme
`https://cdnjs.com/libraries/react-router`
I used `https://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.3/ReactRouter.js`

**Comment by knowbody** [comment]
then this is how you would import it:

```js
import Router, { Route, Link } from 'react-router'

console.log(Router, Route, Link);
```

**Comment by Eagllus** [comment]
Thanks for the update.
Related to the readme.md source want me to create a pull request updating the README.md?

**Comment by knowbody** [comment]
sure, go for it
