### ISSUE TITLE
transition back to a component

### ISSUE THREAD

**Issue by hojberg** [rackt/react-router#2047]
Perhaps i just suck at reading the docs, but i can't figure out how i know that you've transitioned back to a component.

Imagine this scenario

* /foo renders <Foo /> and Foo.componentDidMount triggers and data is loaded
* user navigates to /bar and <Bar /> renders and Bar.componentDidMount is triggered
* user navigates back to /foo and <Foo /> is displayed but Foo.componentDidMount is no longer called

Is there something that I can key off of for re-entering a route? (this is with 1.0.0-rc1)

**Comment by knowbody** [comment]
if you could show some of your code would be easier to tell what might be wrong, in the meantime I'v put together quick example of what you are trying to do and it works just fine:

```js
import React, { Component } from 'react';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import { Router, Route, Link } from 'react-router';

class Navigation extends Component {
  render() {
    return (
      <div>
        <ul>
          <li><Link to='/foo'>Foo</Link></li>
          <li><Link to='/bar'>Bar</Link></li>
        </ul>
      </div>
    );
  }
};

class Foo extends Component {
  componentDidMount() {
    console.log('Foo component did mount');
  }

  render() {
    return <div>Foo</div>;
  }
}

class Bar extends Component {
  componentDidMount() {
    console.log('Bar component did mount');
  }

  render() {
    return <div>Bar</div>;
  }
}

class App extends Component {
  render() {
    return (
      <div>
        <h1>App</h1>
        <Navigation />
        {this.props.children}
      </div>
    );
  }
}

export default class Root extends Component {
  render() {
    return (
      <Router history={createBrowserHistory()}>
        <Route path='/' component={App}>
          <Route path='foo' component={Foo} />
          <Route path='bar' component={Bar} />
        </Route>
      </Router>
    );
  }
}
```

**Comment by hojberg** [comment]
I figured this to be designed that way.
So you're saying I should expect componentDidMount to be called everytime a route is triggered?

**Comment by knowbody** [comment]
yes

**Comment by hojberg** [comment]
I figured out why this is happening

If you have a `routerWillLeave` function that doesn't return anything the url will change, but the component with the `routerWillLeave` function will actually be re-rendered instead of the new component for the new url.

@knowbody this seems like a bug to me. I can't seem to be able to navigate away when `routerWillLeave` exists - should I return `true`? (that doesn't work either)

Should I create a separate issue for this?

**Comment by knowbody** [comment]
could you make a PR with the failing test for that?
