### ISSUE TITLE
react-router transitively requires react-dom

### ISSUE THREAD

**Issue by steveorsomethin** [rackt/react-router#2048]
See https://github.com/facebook/react/issues/4938

As mentioned there, there was some informal discussion (I think via twitter, I can dig it up) about evaluating react-router around a React implementation, and just defaulting to react-dom. That was rejected since we were expecting 0.14 to fully separate core from dom. Is parameterizing an implementation something you'd be willing to take a PR on? I don't expect it would affect the public interface at all, and would enable react-native to work as well.

**Comment by mjackson** [comment]
Looks like there's already a PR in #2031. Let's discuss there.
