### ISSUE TITLE
TypeError: history.isActive is not a function

### ISSUE THREAD

**Issue by halt-hammerzeit** [rackt/react-router#2049]
This code tries to call `history.isActive`
https://github.com/rackt/react-router/blob/master/modules/Link.js#L103

In `history` module there is no method `isActive`
https://github.com/rackt/history/

**Comment by knowbody** [comment]
Can you give more details?
Also have a look at the [`isActive` docs](https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query)

If you are using ES6 classes you should check [this part](https://github.com/rackt/react-router/blob/master/docs/API.md#but-im-using-classes)

**Comment by halt-hammerzeit** [comment]
I'm instantiating history with `history/lib/createBrowserHistory` and then passing it into `react-router`.
The history object created has only these methods and there is no "isActive" method (because `history` module has no)

```
 Object {}createHref: createHref(path)createKey: createKey()createPath: createPath(path)go: go(n)goBack: goBack()goForward: goForward()listen: listen(listener)pushState: pushState(state, path)registerTransitionHook: registerTransitionHook(hook)replaceState: replaceState(state, path)setState: setState(state)transitionTo: transitionTo(nextLocation)unregisterTransitionHook: unregisterTransitionHook(hook)
```

Am I doing it right?

**Comment by knowbody** [comment]
can you post the part where you calling `isActive`? I'm not sure if I understand what you mean

**Comment by halt-hammerzeit** [comment]
I'm not calling `isActive`, the Link class does:
https://github.com/rackt/react-router/blob/master/modules/Link.js#L103

**Comment by knowbody** [comment]
this is how you would the browser history in the router:

```js
import React from 'react';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import {Router, Route, IndexRoute} from 'react-router';
import App from '../components/App';
import Home from '../components/Home';
import About from '../components/About';
import Features from '../components/Features';

React.render(
  <Router history={createBrowserHistory()}>
    <Route path='/' component={App}>
      <IndexRoute component={Home} />
      <Route path='about' component={About} />
      <Route path='features' component={Features} />
    </Route>
  </Router>,
  document.getElementById('app')
);
```

I don't get any errors with that. Let me know how I can reproduce your error and I'll try to help

**Comment by halt-hammerzeit** [comment]
@knowbody okay, thanks for the help.
This currently surpasses my understanding of react-router and I'll figure that out in the following weeks.
For now, I'm closing the issue - seems that my code is doing something that's not intended.

**Comment by halt-hammerzeit** [comment]
@knowbody oh, by the way, your advice fixed my issue: seems that I didn't pass history as a prop to Router.
don't know why `this.context.history` wasn't null then, but that's another story, unrelated.

**Comment by knowbody** [comment]
I'm here to help, feel free to post some code and we will try to solve it

**Comment by halt-hammerzeit** [comment]
@knowbody Thanks
