### ISSUE TITLE
Too many Link elements are deemed active

### ISSUE THREAD

**Issue by jumoel** [rackt/react-router#2050]
I have the following routes:

```jsx
<Router history={createBrowserHistory()}>
	<Route path='/' component={App} >

		<Route path='subroute'>
			<Route path=':id' component={SpecificSubComponent} />

			<IndexRoute component={SubComponents}  />
		</Route>

		<IndexRoute component={Frontpage} />
	</Route>
</Router>
```

With the following `<Link>`'s:

```jsx
<Link to='/' onlyActiveOnIndex={true} activeStyle={{color: 'red' }}>
	Root
</Link>
<Link to='/subroute' onlyActiveOnIndex={true} activeStyle={{color: 'red' }}>
	Subroute
</Link>
```

When the URL is `/`, only the first `Link` element is red.

When the URL is `/subroute`, both `Link` elements are red.

Have I misunderstood something or is it a bug?

**Comment by jumoel** [comment]
I can see that it is already known:

https://github.com/rackt/react-router/issues/1945

**Comment by knowbody** [comment]
closing as we have open PR with the failing tests for that #1957
