### ISSUE TITLE
implementaton of 1.0.0-rc1 shows error

### ISSUE THREAD

**Issue by rosnk** [rackt/react-router#2052]
Trying to implement react-router in my project and i am getting following errors: 

1) Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
2) Warning: Only functions or strings can be mounted as React components.
3) Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

routes.js file: 

```
var React = require('react');
var ReactRouter = require('react-router');
var Router = ReactRouter.Router;
var Route = ReactRouter.Route;

var Home = require('./components/home.js');
var Jobs = require('./components/jobs.js');
var JobDetail = require('./components/jobDetail');
var App = require('./components/app.js');
var About = require('./components/about.js');
var NotFoundPage = require('./components/notfoundpage.js');

var routes = (<Router>
    	<Route path="/" component={App}>
    		<Route path="jobs" component={Jobs}>
    			<Route path="jobs-detail" component={JobDetail} />
    		</Route>
    		<Route path="*" component={NotFoundPage} />
    	</Route>
  	</Router>);

module.exports = routes; 
```

app.js file: 

```
var React = require('react');
var ReactRouter = require('react-router');
var Router = ReactRouter.Router;
var routes = require('./routes');

React.render(<Router>{routes}</Router>, document.body);

```

**Comment by jeongsd** [comment]
+1

**Comment by chentsulin** [comment]
You should not put nested `<Router>` in your `<Router>`:

```js
<Router>
    <Router>
       <Route>
    </Router>
</Router>
```

Must remove `<Router>` from your `routes`

**Comment by cliche7** [comment]
I encountered the same issue with this:
```
import React from 'react'
import { Router, Route, IndexRoute } from 'react-router'
import createBrowserHistory from 'react-router/node_modules/history/lib/createBrowserHistory'
export class App extends React.Component {
	render() {
        let history = createBrowserHistory()
        return (
            <Router history={history}>
                <Route path="/" component={Index}>
                    <Route path="" component={Home} />
                    <Route path="indeks-permohonan" component={TableRequest} />
                    <Route path="indeks-work-order" component={TableEngineer} />
                    <Route path="*" component={NotFound} />
                </Route>
            </Router>
            )
	}
}
```

**Comment by knowbody** [comment]
@rosnk as @chentsulin mentioned you wrapped Router inside Router which is not correct.

@cliche7 first of all use the [History](https://github.com/rackt/history) ([how to use it](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#createbrowserhistory)). The second thing is, your route: `<Route path="" component={Home} />` has no path, you should use [`IndexRoute`](https://github.com/rackt/react-router/blob/master/docs/guides/basics/IndexRoutes.md#index-routes).

**Comment by datnq201088** [comment]
I has the same issue

**Comment by rosnk** [comment]
@datnq201088 ,I finally manage to make it work. If you are still facing this problem this might help beside this post: 

http://stackoverflow.com/questions/32730518/basic-implementaton-of-react-router-1-0-0-rc1-shows-error/32779523#32779523
