### ISSUE TITLE
nextState not passed to getComponent(s)

### ISSUE THREAD

**Issue by jmheik** [rackt/react-router#2054]
On getComponents.js only `location` property of `nextState`is passed to functions `getComponent` and `getComponents`. Would it be good idea to pass the whole `nextState` to be consistent with onEnter hooks? It would allow more flexibility on `getComponent` functions, especially `nextState.params` being available would be useful.

**Comment by mjackson** [comment]
Can you describe what you're trying to accomplish at a higher level?

**Comment by jmheik** [comment]
Sure. Some of the routes in my app are same pattern but needs to be rendered with different components. `getComponent` function seems the right place to implement logic for this. However, I have to fetch data corresponding the route from server before I know which component to use, and this is where `nextState` object would've been helpful as it contains params readily parsed from the route.

As my routes were simple I already solved the case by parsing the relevant data from `location.pathname`.

**Comment by vojtatranta** [comment]
I would use higher-order component that would render different components base on props.
Where you might put something like:
```js
getComponentToRender(props) {
  if (props.this == 'something') {
    return ThisComponent
  } else {
    return ThatComponent
  }
},

render() {
return (
   {this.getComponentToRender(this.props)}
)
}

I would use this way because decision which component should be render is not based on url (route) therefore must be based on state of the app which you should receive in props.

**Comment by mjackson** [comment]
Again, thanks for the help here @vojtatranta :)
