### ISSUE TITLE
Updated testing docs for Jest

### ISSUE THREAD

**Issue by chiedojohn** [rackt/react-router#2055]
Hey fellas,
Thanks again for all your work on react-router!

Any chance we could get some updated testing docs for Jest though?

Also as an FYI, The link to https://github.com/rackt/react-router/blob/master/docs/guides/testing.md no longer works. I've found it linked to on quite a few posts online.

Work arounds for using react-router with Jest were working with version 0.13.x but the work arounds no longer work with 1.0.x

Specifically, if I render any component that requires react-router, the Jest tests fail. 

For example, the following Jest test will fail:

```js
describe('Test', function() {
  var ReactRouter = require('react-router');
});
```

I get the following error.
```
it encountered a declaration exception
```

Any ideas?

**Comment by chiedojohn** [comment]
Hmmm... I just got all my tests to pass. I'm not sure why they are now passing, but this is what I changed in my package.json. Do you know why react-router no longer complains in the Jest tests?

## Before
```js
  "scripts": {
    "test": "jest",
    "postinstall": "gulp production"
  },
  "jest": {
    "scriptPreprocessor": "./node_modules/babel-jest",
    "unmockedModulePathPatterns": [
      "./node_modules/react",
      "./node_modules/lodash",
      "./node_modules/object-assign",
      "./node_modules/keymirror",
      "./node_modules/chance",
      "./react/constants/Actions",
      "./react/Factories"
    ]
  },
```

## After
```js
  "scripts": {
    "test": "jest",
    "postinstall": "gulp production"
  },
  "jest": {
    "scriptPreprocessor": "../node_modules/babel-jest",
     "rootDir": "./react",
    "unmockedModulePathPatterns": [
      "../node_modules/react",
      "../node_modules/lodash",
      "../node_modules/object-assign",
      "../node_modules/keymirror",
      "../node_modules/chance",
      "./constants/Actions",
      "./Factories"
    ]
  }
```

**Comment by machinealgo** [comment]
:+1: I am running into the same error, but including rootDir in my package.json doesn't solve the problem for me :|

> Also as an FYI, The link to https://github.com/rackt/react-router/blob/master/docs/guides/testing.md no longer works. I've found it linked to on quite a few posts online.  

@chiedojohn , do you mind sharing what those links here?

Thanks

**Comment by chiedojohn** [comment]
Hey @machinealgo I'm not sure I understand your question!

**Comment by knowbody** [comment]
I think @machinealgo meant the correct link to [the 0.13.x testing docs](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/testing.md).

**Comment by chiedojohn** [comment]
Ah, sadly I have not been able to find any correct link

**Comment by bvaughn** [comment]
Speaking of the Testing guide, when will it be restored for 1.x? In commit b21302, `testing.md` was removed and it has not been re-added. There are links scattered around SO and other places that point to it. The structure of the new docs doesn't seem to include any references to testing that I see.

**Comment by bobmonteverde** [comment]
I'm having the same issue.  If react-router is required by a component I am testing I get a "Unexpected token ..." Error.  Can't say the '...' is very specific.  I've been trying to dig further into this, but am having no luck.  Been showing up since upgrading to 1.0.0-rc1.

**Comment by knowbody** [comment]
I opened the issue on rewriting the docs for 1.0, I will do that as soon as I find some time (#2149)

**Comment by chiedojohn** [comment]
Thanks @knowbody

**Comment by bobmonteverde** [comment]
@knowbody Ideally the docs would identify and fix the issue, but my concern right now isn't the docs, it's the fact that react-router v1.0.0-rc1 doesn't work with Jest 0.5.x, I get:

    it encountered a declaration exception

Whenever a file I am trying to test requires react-router.

**Comment by knowbody** [comment]
@bobmonteverde I do agree, I haven't looked into that issue yet hence I left this one open and opened the other issue just for docs.

**Comment by bobmonteverde** [comment]
@knowbody awesome.  Let me know if you want any help.  Sadly the error was pretty vague (and I just put on this project that's using react, react-router, and jest), so I wasn't able to dive into what was actually going wrong.  If you have any insight on what's likely the issue, or need someone to test something out, please let me know, I will gladly help as much as I can.

**Comment by mjackson** [comment]
@bobmonteverde I don't use Jest (I don't know if @knowbody does, or anybody else at rackt for that matter), so I'm not a great candidate to fix this particular issue. If you or someone else who does would like to dive in and figure out why it doesn't like our lib that would be awesome.

**Comment by knowbody** [comment]
I'm not the Jest expert, but I played a bit just now and added some simple tests to my [playground example](https://github.com/knowbody/react-router-playground). Have a look at the setup there, it seems to me like everything should work just fine.

Send me PR in [my playground repo](https://github.com/knowbody/react-router-playground) with the tests which are not working as you expect and I try to help there. Or maybe to keep everything here I just add tests to the examples we have here. But I need some more time to do that. I know I also promised to write the docs on testing, but I need to look a bit more into Jest to do so.

**Comment by chiedojohn** [comment]
Looks like I was able to get things fixed... at least on my setup. @knowbody it seems to be caused by upgrading from old jest, react, etc. setups. Looking at your repo to see your setup was helpful. You were coming into it fresh as opposed to upgrading from legacy setups which probably helped.

Firstly, I needed to remove the following line from my package.json as that is no longer needed.
```
"react-tools": "~0.13.3",
```

Next, I needed to add the following line to my package.json under depenencies
```
"react-addons-test-utils": "0.14.0",
```

Lastly, I needed to replace this:
```
var React              = require('react/addons');
var TestUtils          = React.addons.TestUtils;
```
with this:
```
var TestUtils          = require('react-addons-test-utils');
var ReactDOM           = require('react-dom');
var React              = require('react');
```

Make sure you do an npm clean, install, etc.

Also make sure you have the latest versions of Jest, node 4.X, etc. Pretty confident this should resolve any issues people are having.

Thanks for your help @knowbody

**Comment by knowbody** [comment]
@chiedojohn you're welcome! Would you like to write docs on testing (#2149)?

**Comment by chiedojohn** [comment]
@knowbody It would be my pleasure. I'll get started on it this week.

**Comment by btipling** [comment]
Just in any one else runs into this problem, any dependency that installs `react-tools` will cause the spread operator failure (the "..." is the es6 spread operator). For example, if you require `reactify` as a dependency it will install `react-tools` and your tests will fail when you try to import or require `react-router`. 

The reason for this is because `react-tools` includes its dependencies in a very non-npm friendly way.  If you look inside `react-tools` you will see the path `src/vendor/core/...` and this is a list of third party dependencies `react-tools` needs. This is different from using`node_modules`. 

Furthermore, inside `react-tools` `src/vendor/core` is a warnings.js in es6 syntax. For whatever reason whenever you run jest tests that require `react-tools` the test will grab the es6 `warnings.js` from `react-tools` instead of the `warnings.js` that npm installed as part of installing `react-router`. I have no idea why this happens. I was lucky enough to be able to remove all my dependencies that needed `react-tools` and sorted out the issue that way. 

I doubt that Facebook will make any changes to `jest` or `react-tools` that will help out on this specific issue, they don't seem very open to patches. You're options are to require only two of the three dependencies: `react-router` `jest` and `react-tools`. If you need all three your tests wont work based on what I know so far.

**Comment by knowbody** [comment]
Thanks for this particular problem explanation, might be useful :smile: 

> I doubt that Facebook will make any changes to `jest` or `react-tools` that will help out on this specific issue, they don't seem very open to patches sometimes. 

@btipling I disagree on that a lot, and think that Facebook is very open to improvements, if you have a chance, ping @cpojer - he works on Jest.

**Comment by cpojer** [comment]
Seems like @chiedojohn has a correct explanation on how to make this stuff work. This is not a jest issue at all. @btipling it would be great if you could elaborate more how any of this is related to jest.

The jest examples contain solutions for how to test react 0.14: https://github.com/facebook/jest/blob/master/examples/react/package.json We are currently in the process of updating this to work great with babel 6 as well.

Also, if you have jest questions feel free to join me on discord: facebook.github.io/jest/support.html :)

**Comment by taion** [comment]
Why are you still getting `react-tools` dependencies? I thought that package was deprecated.
