### ISSUE TITLE
Add params to RoutingContext's getChildContext

### ISSUE THREAD

**Issue by canvaskisa** [rackt/react-router#2057]

**Comment by knowbody** [comment]
is that a question? if you can provide some details we will be able to help

**Comment by canvaskisa** [comment]
@knowbody I suppose it will be a good practice in new version of react-router. According to docs, we can access location & history instances with react's context, but none of them is containing params object, it's very useful though

**Comment by knowbody** [comment]
@canvaskisa can you give the example/use case of why it would be very useful?

**Comment by canvaskisa** [comment]
@knowbody in my case, i've got a special Fetcher component, which passes params and other props to actions to request api. Without params in context, i should pass params from every Route component to Fetcher and, surely, it's getting annoying. Of course, we can create own context with params in Root component, but why shouldn't we do it in react-router? And why then it's location object in context?

**Comment by knowbody** [comment]
I still don't understand it. What kind of params are you talking about? Please give the clear explanation of the problem and then we reopen this issue.

**Comment by canvaskisa** [comment]
@knowbody i was talking about location params, such as \<Route path="/some-path/**:id**"/\>, but whatever.

**Comment by knowbody** [comment]
@canvaskisa you can access them via `this.props.params`

**Comment by canvaskisa** [comment]
@knowbody i know, but only in the top component.

**Comment by taion** [comment]
So pass them down to your children.

**Comment by carlitux** [comment]
@canvaskisa you can request context on your component (React component)

```jsx
YourComponent.contextTypes = {
  history: React.PropTypes.object
};
```

And you can use like this in your component.

```jsx
this.context.history
```
