### ISSUE TITLE
Warning: Only functions or strings can be mounted as React components.

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/react-router#2059]
Hello, I've been having an issue when using react-router with an alternative way to compose react components without using classes. Heres my code:
```
import React from 'react';
import { Router, Route, Link } from 'react-router';

function App (props, reactElementInstance) {
    var instance = Object.create(React.Component.prototype);
        instance.context = reactElementInstance;
        instance.props = props;
        instance.render = function () {
            return (
                <div>
                    <h1>hi</h1>
                </div>
            );
        };

    return instance;
}

React.render((
  <Router>
    <Route path="/" component={App}>
        
    </Route>
  </Router>
), document.getElementById('app')); 
```
The issue that I keep receiving from the browser are these:
![image](https://cloud.githubusercontent.com/assets/8888991/10051411/3f7c83b0-61ef-11e5-908a-bfc12ea8ec3b.png)

I rendered the component successfully without `react-router` which is what is causing me confusion as to why when rendered/passed into the `<Route component={App}>` it throws an error.

**Comment by taurose** [comment]
Not getting any errors or warnings with this code (react 0.13.3, react-router 1.0.0-rc1).

**Comment by bosgood** [comment]
@kennetpostigo I think you're probably on the earlier version, `react-router 0.13.3`. npm gave me that version as well at one point. If you do want to use that version, it's got a different API than the `1.x` versions, available here: https://github.com/rackt/react-router/tree/v0.13.3

**Comment by kennetpostigo** [comment]
Let me change the version and see if I get the errors to go away. Thank you @bosgood & @taurose for pointing me to the version numbers.

**Comment by kennetpostigo** [comment]
@bosgood The version I'm trying to use is `react-router 1.0.0` but npm does have it. I tried changing directly from the `package.json` but it kept giving me errors when I would try to `npm install`.

**Comment by knowbody** [comment]
try `rm -rf node_modules && npm install`

**Comment by kennetpostigo** [comment]
@knowbody Thank you!!!! It is working as expected now.
