### ISSUE TITLE
Registering Lifecycle hooks without mixins

### ISSUE THREAD

**Issue by quicksnap** [rackt/react-router#2061]
I'm trying to register a hook similar to the Lifecycle mixin within my `/widgets` route component:

```javascript
  componentWillMount() {
    const route = this.props.route;
    this.props.history.registerRouteHook(route, (location) => {
      console.log('This log is executed.');
      return true; // This should allow transitioning..
    });
  }
```
However, when I navigate to `/widgets` and then attempt to navigate elsewhere, the location state is updated via popState, but the route does not change. As commented, the log is executed. 

Any tips on how to accomplish this? I'm working on code related to #2006, so that transitions may preload their data asynchronously _before_ the route transition occurs.

**Comment by quicksnap** [comment]
Additionally, when I put this code on the root component, all transitions are still blocked, but the console log statement is _not_ executed.

**Comment by knowbody** [comment]
@quicksnap I think what you look for is `listenBefore`. See History's documentation on [Confirming Navigation](https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md#confirming-navigation).
