### ISSUE TITLE
LifeCycle behaviour

### ISSUE THREAD

**Issue by jzlxiaohei** [rackt/react-router#2062]
I do some test using the code below.
     
    //app.jsx
    <Router>
            <Route path='/' component={AppComponent}>
                <Route path='/detail' component={DetailElement}/>
                <IndexRoute component={IndexComponent}/>
            </Route>
     </Router>

    //IndexComponent.jsx
    class IndexComponent extends React.Component{
        constructor(props,context){
            super(props,context)
            console.log('test constructor')// each time from `detail` to `index` 
        }
        componentDidMount(){
            console.log('test didMount')// each time from `detail` to `index` 
        }
        render() {
            //some code
        }
    }

each time  to `index`, the `constructor` and `componentDidMount` would be called. i don't think the document about  `LifeCycle` states this behaviour clearly.

And, could i just invoke the methods only once?

**Comment by knowbody** [comment]
They are invoked only once, when the `componentDidMount`. When you change the URL from one to another you are unmounting one component and mounting the other one.

Could you describe your use case? Why do you need them to be invoked only once and never again?

**Comment by jzlxiaohei** [comment]
@knowbody fetch init data in `componentDidMount ` of `IndexComponent`, and save the data in a `store`. When back from the `DetailComponent`，i have to write some code to prevent to  reload the init data.

**Comment by knowbody** [comment]
This is something you need to deal with yourself. I would fetch the data on the `componentDidMount` and after set the state on this component to `wasDataFetched: true` and make a check in `componentDidMount` if the data has been fetched already. Something like:

```js
componentDidMount() {
  if (this.state.wasDataFetched === false) {
    this.fetchData();
    this.setState({ wasDataFetched: true });
  }
}
```

**Comment by jzlxiaohei** [comment]
@knowbody hi,i don't think it works. As mentioned , `constructor` would be called each time.it was totally new Component.  And I wrote a demo, `console.log('fetch data')` has been called each time back to `Index`

    class AppComponent1 extends React.Component{
        render() {
            return(
                <div className='web-app'>
                    {this.props.children}
                </div>
            )
        }
    }
    
    class IndexComponent extends React.Component{
    
        state={
            wasDataFetched:false
        }
    
        componentDidMount(){
            if (this.state.wasDataFetched === false) {
                //this.fetchData();
                console.log('fetch data') // still called every time from `detail` back to `index`
                this.setState({ wasDataFetched: true });
            }
        }
    
        render(){
            return(
                <div>
                    <div>Index</div>
                    <div><Link to='/detail'>to Detail</Link></div>
                </div>
            )
        }
    }
    
    class DetailComponent extends React.Component{
        render(){
            return(
                <div>
                    <div>Detail</div>
                    <div><Link to='/'>back to Index</Link></div>
                </div>
            )
        }
    }
    
    React.render(
        (
            <Router>
                <Route path="/" component={AppComponent1}>
                    <IndexRoute  component={IndexComponent}/>
                    <Route path="detail" component={DetailComponent} ignoreScrollBehavior>
                    </Route>
                </Route>
            </Router>
        ),
        document.getElementById('mount-dom')
    )

**Comment by knowbody** [comment]
oh yeah, you're right! you said you're using flux right? you could save the state in the store then

**Comment by jzlxiaohei** [comment]
then when to fetch the init data ? i could not find an elegant way

**Comment by knowbody** [comment]
same as I said above, except instead of having state in the component you would have your `wasDataFetched` in the store and you would check if it is `true` or `false` on `componentDidUpdate`

**Comment by jzlxiaohei** [comment]
@knowbody  yes, i add wasDataFetched in the store.
What about reusing  `component` in the Route ,not create a new one.

**Comment by knowbody** [comment]
they are always being mounted and the unmounted if you navigate away, unless I'm missing something

**Comment by jzlxiaohei** [comment]
@knowbody you are right, i think it in a wrong way.  Thank you for your patience
