### ISSUE TITLE
IndexLink doesn't be included in index.js

### ISSUE THREAD

**Issue by yinickzhou** [rackt/react-router#2063]
This should be a minor missing. I cant import the IndexLink by
```import {IndexLink} from 'react-router';```
Which is undefined.

**Comment by knowbody** [comment]
are you using 1.0.0-rc1?

**Comment by yinickzhou** [comment]
"version": "1.0.0-rc1",
I think so

**Comment by knowbody** [comment]
hmm, try to `rm -rf node_mdules && npm install`
it works fine for me, haven't seen any issues with it.

**Comment by yinickzhou** [comment]
I have followed your steps, the issue still. Here is my index.js
```
/* components */
export Router from './Router';
export Link from './Link';

/* components (configuration) */
export IndexRoute from './IndexRoute';
export Redirect from './Redirect';
export Route from './Route';

/* mixins */
export History from './History';
export Lifecycle from './Lifecycle';
export RouteContext from './RouteContext';

/* utils */
export useRoutes from './useRoutes';
export { createRoutes } from './RouteUtils';
export RoutingContext from './RoutingContext';
export PropTypes from './PropTypes';
export match from './match';

export default from './Router';
```

BTW, I'm using windows.

**Comment by knowbody** [comment]
this is what in `index.js` of 1.0.0-rc1 https://github.com/rackt/react-router/blob/master/modules/index.js

try to do:
```js
import IndexLink from 'react-router';
```

**Comment by yinickzhou** [comment]
Thanks. I just noticed the last commit for index.js is to fix this issue :)
