### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by DannyiCracked** [rackt/react-router#2065]
The docs are awful in the latest versions. There used to be a very easy to use and follow API guide that has since vanished. 

Now we get these plain .md files that basically explain nothing. I can't even figure out how to stop my app from using the hash location in the URL.

Please consider upgrading your documentation.

**Comment by knowbody** [comment]
Hey @DannyiCracked we work hard on making the React Router great. And is definitely sad to hear the feedback like yours. Let me know which parts need more focus and what they are lacking. I'd try to fix it or I'd be happy if you send the PR with your suggested changes.

Going back to your "question":
> I can't even figure out how to stop my app from using the hash location in the URL

You should use [Browser History](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#createbrowserhistory) to get rid off `#` in the URL
