### ISSUE TITLE
IndexRoute's becomes active at wrong route

### ISSUE THREAD

**Issue by pjuke** [rackt/react-router#2066]
I have the following setup:

	<Route component={Application}>
		<Route path="/website" component={Website}>
			<Route path="products" component={WebsiteProducts}>
				<Route path=":productId" component={WebsiteProductsProduct} />
				<IndexRoute component={WebsiteProductsIndex} />
			</Route>
			<Route path="contact" component={WebsiteContact} />
			<IndexRoute component={WebsiteOverview} />
		</Route>
	</Route>

With the following links in a menu:

	<Link to="/website" onlyActiveOnIndex={true} activeClassName="active">Overview</Link>
	<Link to="/website/products" activeClassName="active">Products</Link>
	<Link to="/website/products/15" activeClassName="active">Specific product</Link>
	<Link to="/website/contact" activeClassName="active">Contact</Link>

Visiting URL `/website` makes **overview** active, and visiting `/website/contact` makes the **contact** active, just as predicted.

But visiting URL `/website/products` makes _both_ **overview** and **products** active. But if I visit `/website/products/15` the **products** and **specific product** gets highlighted (as intended).

So the issue is that by visiting the products URL, the overview (which is a an IndexRoute) still gets active, why is this? I thought the prop `onlyActiveOnIndex` would prevent this from happening.

**Comment by mjackson** [comment]
Hmm, this sounds like it could be a bug.

**Comment by knowbody** [comment]
@pjuke mind submitting the PR with minimal failing test?

**Comment by mjackson** [comment]
I'm fairly certain this is the same issue as #1957. I'm taking a hard look at that bug right now and trying to fix.

**Comment by pjuke** [comment]
Cool, thank you @mjackson.
Are you planning to release a new version any time soon? I'm using `npm` in my project so I rely on such a version to get this hotfix.

**Comment by pjuke** [comment]
@mjackson this fix did unfortunately not fix my issue; I'm still experiencing the same odd behaviour just as in #1945 as well.

**Comment by knowbody** [comment]
again, could you submit the PR with the failing test, then it's easy for us to make sure that we cover all cases

**Comment by pjuke** [comment]
Please excuse me for my bad GitHub:ing, but I think I managed to do PR. I only modified the original test quick-and-dirty to suit my site. You can find it here https://github.com/rackt/react-router/pull/2079

**Comment by iNikNik** [comment]
@pjuke yep, same for me) I've made some fix for this issue #2113
