### ISSUE TITLE
Override a route handler at child level when using multiple handlers

### ISSUE THREAD

**Issue by amannn** [rackt/react-router#2067]
Coming from your example about multiple route handlers from [the docs](https://github.com/rackt/react-router/blob/master/docs/API.md#components-1): Would it be possible to specify for the route `users/:userId` to override the sidebar? A first test of mine has shown that this isn't working.

Or is that supposed to be working?

**Comment by edvinerikson** [comment]
If I understood your question right, you should be able to do something like this: `<Route path="users/:userId" components={{main: Profile, sidebar: ProfileSidebar]} />`

**Comment by amannn** [comment]
Yes, exactly :).

**Comment by knowbody** [comment]
@amannn yes! 

@edvinerikson thanks for the answer!
