### ISSUE TITLE
What do I need to do get this.props.params populated in 1.0.0?

### ISSUE THREAD

**Issue by ramin32** [rackt/react-router#2068]
When I try accessing this.props.params, it is undefined. this.context.router is {}.
I played with the different variations of adding `contextTypes` to my component:
```  
contextTypes: {
      router: React.PropTypes.func.isRequired
},
```
but had no luck.

**Comment by ramin32** [comment]
As shown here: https://github.com/rackt/react-router/blob/v0.11.6/examples/query-params/app.js, you need to add the Router.State mixin:

```
var User = React.createClass({
  mixins: [ Router.State ],
```

**Comment by rulatir** [comment]
... aaaaaand the same with ES6 classes? How?
