### ISSUE TITLE
Link onlyActiveOnIndex breaking with dynamic routing

### ISSUE THREAD

**Issue by Agrosis** [rackt/react-router#2072]
So I have some route config down low in my hierarchy like such:

```js
path: 'dashboard',
getComponents(location, callback) {
  require.ensure([], (require) => {
    callback(null, require('./components/dashboard/Dashboard'));
  })
},

getIndexRoute(location, callback) {
  require.ensure([], (require) => {
    callback(null, require('./components/dashboard/DashboardIndex'));
  })
},

getChildRoutes(location, callback) {
  require.ensure([], (require) => {
    callback(null, [
     {
       path: 'blah',
       component: require('./components/dashboard/blah')
     },
...
```

In my Dashboard component, i have this:
```js
// I saw IndexLink but i noticed that it wasn't probably exported in the latest rc?
<Link to="/dashboard" onlyActiveOnIndex={true} activeClassName="active">Index</Link>
```

So without dynamic routing, whenever I'm at `/dashboard', the Link is correctly detected as active, but once I stuck in dynamic routing it broke. My current solution is to just make the index route some named route, but it would be nicer to not have a /index. :) Any ideas?

**Comment by Agrosis** [comment]
It didn't fix the problem completely, but it looks like my getIndexRoute implementation was actually wrong. I didn't notice that the component wasn't rendering actually. Here's the new one.

```
        getIndexRoute(location, callback) {
          require.ensure([], (require) => {
            callback(null, [
              {
                path: 'dashboard',
                component: require('./components/dashboard/DashboardIndex')
              }
            ]);
          })
        },
...
```

`onlyActiveOnIndex` still doesn't work though.

**Comment by mjackson** [comment]
I think this may actually be a bug. In dynamically loaded routes, we may not be setting up the `indexRoute` property on the parent route properly. As you can see [in the implementation of `getIndexRoute`](https://github.com/rackt/react-router/blob/e9067ff960b13d933e9dabbb31936358a4dde504/modules/matchRoutes.js#L17-L27), we're not currently passing the parent route through to `createRoutes`. This may be an easy fix, but I'd really like to create a failing test first so we can be sure we've fixed the bug when we do.

Would you be up for that, @Agrosis?

**Comment by Agrosis** [comment]
@mjackson Yeah, totally! I've actually been interested in trying to help out with what you guys have been building, its all so awesome!

So, just create a test that makes sure that index routes that load dynamically are correctly detected as `only active`? Thanks!

**Comment by mjackson** [comment]
Thanks! Ya, that's basically it. I can take it from there :)
