### ISSUE TITLE
Server Sided data loading with 1.0.0

### ISSUE THREAD

**Issue by schauhan19** [rackt/react-router#2073]
Previously with 0.13.x I could pass my custom props into the `RouteHandler` and they would get passed down to the rendered component . The docs for react-router 1.0.0 recommend to use `match` with `RoutingContext`, however I cannot figure out a way to access custom props from the components. 

Here are simplified snippets of my code:

```javascript
/* Server Route handler */
let customProps = {/* some custom props*/};
match({routes, location}, (err, redirectLocation, renderProps) => {
  // removed error checking for simplicity
  renderProps.customProps = customProps;
  let factory = React.createFactory(RoutingContext)(renderProps);
  ReactDOMServer.renderToString(factory);
});
```

```javascript
/* Routes.jsx */
export default (
    <Route path='/' component={App}>
      <IndexRoute component={Home}/>
      <Route path='admin' component={Admin}/>
    </Route>
)
```

```javascript
/* App.jsx */
export class App extends React.Component {
  // this.props does not contain customProps
  render() {
    return(
      <html>
        {this.props.children} // How can I render this with customProps?
      </html>
    )
  }
}
```

The documentation mentions using a `load` function within the route or using `wrapComponentWithData()` on `renderProps.components`, but doesn't mention how this can be accomplished. Is there something I am missing?

**Comment by gaearon** [comment]
Does [`createElement`](https://github.com/rackt/react-router/blob/master/docs/API.md#createelementcomponent-props) prop help?

**Comment by schauhan19** [comment]
@gaearon YES! that helped me get past the SSR issue, but now there are invariant violation errors once I'm back on the frontend.

**Comment by schauhan19** [comment]
It looks like the client is rendering without `data-reactid` on some components. Still no idea why this would happen.

**Comment by dmitrigrabov** [comment]
@gaearon how would the ```createElement``` prop be used in this case?

**Comment by schauhan19** [comment]
@dmitrigrabov you would pass a prop to the RoutingContext component called createElement which would return an element with your custom props loaded:

```javascript
const customProps = {/*Custom Data*/};
match({routes, location}, (err, redirectLocation, renderProps) => {
// Skipping error checking
 const routerProps = {
   ...renderProps,
    createElement: (Component, props) => {
    return React.createElement(Component, {...props, ...customProps});
 }

  let factory = React.createFactory(RoutingContext)(routerProps);
  res.send(ReactDOMServer.renderToString(factory));
};
```

**Comment by dmitrigrabov** [comment]
@schauhan19 thanks very much for the help :)
