### ISSUE TITLE
optional route matching doesn't work as described

### ISSUE THREAD

**Issue by arasmussen** [rackt/react-router#2074]
I have the following route:

    <Route path="/product/:foo(/:bar)" handler={ProductHandler} />

And the following URLs do not match my route:

/product/foo
/product/foo/
/product/foo/bar

It works just fine when I remove the optional segment (just "/product/:foo"). I'm using version 0.13.3.

I'm going off the documentation on this page: https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteMatching.md

**Comment by mjackson** [comment]
The docs on master are for the code on master. The syntax you're using wasn't available in 0.13.

**Comment by arasmussen** [comment]
@mjackson How would you do this in 0.13?

**Comment by arasmussen** [comment]
According to the path matching guide in 0.13.3 this syntax should work fine. https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/docs/guides/path-matching.md

**Comment by eternalsky** [comment]
same problem, /file/(:name) not work as described. it matches '/file/(2)'  , but not match /file
