### ISSUE TITLE
npm can't install react-router globally

### ISSUE THREAD

**Issue by anthonybrown** [rackt/react-router#2075]
I've installed `react` but still getting errors:
` → npm install -g react@latest
/usr/local/lib
└── react@0.13.3

Tonys-iMac: ~
 → npm install -g react-router
/usr/local/lib
├── UNMET PEER DEPENDENCY react@0.13.x
└── react-router@0.13.3

npm WARN EPEERINVALID react-router@0.13.3 requires a peer of react@0.13.x but none was installed.`

**Comment by faergeek** [comment]
For what reason you try to install `react` and `react-router` globally?

**Comment by datnq201088** [comment]
I think install --save-dev is better for your project

**Comment by anthonybrown** [comment]
Installing it globally, I guess isn't a good idea, I was thinking of having it handy since I've been working with it lately. The work around is `npm install -g react react-router`
