### ISSUE TITLE
BrowserHistory as a module breaks on server

### ISSUE THREAD

**Issue by marnusw** [rackt/react-router#2076]
I was trying out the example at [Navigating Outside of Components](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md). It works great client side, but in an isomorphic application where the actions are imported server side as well the `createBrowserHistory()` execution throws a `'Browser history needs a DOM'` error. 

Is this something you've encountered or considered and have a solution for?

I'm using Fluxible, so my current solution is using a plugin to add a `history` instance to the action context which I can then set to a `BrowserHistory` in `client.js` only. The work in progress plugin is [here](https://github.com/LegitTalon/fluxible-plugin-react-router/blob/router1.0.0/react-router-v1.js) FYI.

**Comment by vojtatranta** [comment]
Well I suppose that you just create some condition when rendering on the server.
I am using React-router 1.0.0b2 and it was kind easy...
https://github.com/vojtatranta/Photostore/blob/master/containers/Root.js

Here you can see my solution.

**Comment by marnusw** [comment]
Thanks @vojtatranta, with the Fluxible plugin I'll have a scenario similar to what you have which will work. I'm guessing in all likelihood the "Navigating Outside of Components" approach as is was proposed for client only applications.

**Comment by vojtatranta** [comment]
Please don't forget to close this issue if you consider it resolved.

**Comment by mjackson** [comment]
Thanks for the help here, @vojtatranta
