### ISSUE TITLE
Missing documentation about `onlyActiveOnIndex` prop on <Link>

### ISSUE THREAD

**Issue by chentsulin** [rackt/react-router#2077]
I found that `<Link>`'s `onlyActiveOnIndex` prop is Missing documentation in API section.

And in examples/query-params, `/user/bob?showAge=true` will active two `<Link>` at the same time. I thought this is incorrect In most cases.

![query-params](https://cloud.githubusercontent.com/assets/3382565/10096873/a057756e-63a7-11e5-8f25-ab7268364c3f.png)

Can we just let

`/user/bob?showAge=true`

only active this link?

```
<Link to="/user/bob" query={{ showAge: true }} activeClassName="active">Bob With Query Params</Link>
```

**Comment by mjackson** [comment]
If a link has a `query`, the query must match in order for it to be active. If it doesn't have a query, it only needs to match the route.

If you'd like to add something to the docs, please submit a PR.

**Comment by clay-reed-a** [comment]
@mjackson, I think I have the same issue. It's not clear from the docs what `onlyActiveOnIndex` does. Also, I don't observe what you describe as being the correct behavior for `query` for `hash`. 

```js 
// Both of these will get the .activeClassName 
<Link to="/foo/bar#baz" />
<Link to="/foo/bar#quux" />
```
