### ISSUE TITLE
copy paste createHashHistory URL does not work 

### ISSUE THREAD

**Issue by rosnk** [rackt/react-router#2078]
i am using "createHashHistory" style URL which happens to add  some random key at the end, in order to store location state. **As i copy URL and try to load in a new browser window i get nothing with following error in console**: 

```Uncaught ReferenceError: joblists is not defined```

 URL i am trying to copy looks like this: 

``` http://localhost:8080/#/jobs/jobdetail/1?_k=0x501g ```

My Route: 

``` 
    <Route path="jobs" component={Jobs}>
         <Route path="jobdetail/:id" component={JobDetail} /> 
    </Route>
```

**Comment by knowbody** [comment]
the error is about `joblists` being undefined probably in your `JobDetail` component

**Comment by rosnk** [comment]
**why pasting URL in new browser does not track STORE state ?** 

@knowbody In my "JobDetail" component i am getting id from url and doing a lookup in store(flux) to find the record of that particular id and showing it on page. something like this. 

```
componentDidMount: function(){
		var id = this.props.params.id;
		var joblist = JobStore.getJobById(id);
		console.log(joblist);
},	
```

URL i am trying to copy looks like this:
```
http://localhost:8080/#/jobs/jobdetail/1?_k=0x501g
```
I guess in my case when i paste url in new browser my program has no idea of state of Store.  **So my question was why "joblists" is undefined, isn't whole point of having a key at the end is to preserve "location state".**

**Comment by gaearon** [comment]
>why pasting URL in new browser does not track STORE state ?

URL is just a URL—an address your app can interpret. It does not magically preserve the state of your application. It is up to you to persist it (for example, to localStorage), and read it when your application boots up to prefill your Stores. This is not something a router could do for you.

**Comment by knowbody** [comment]
thanks Dan!
