### ISSUE TITLE
Using v1.0.0 with Flux

### ISSUE THREAD

**Issue by aszwemin** [rackt/react-router#2081]
Hi,

There was a lot said about using earlier versions with Flux, but what's the best practice to get react-router 1.0.0 working with Flux, taking under consideration that history is now a separate module and it is passed to Router when created?

**Comment by vojtatranta** [comment]
Hi,
I got it working easily with Redux (Flux implementation), you can check it out here.
I am using 1b2 version of React-rotuer https://github.com/vojtatranta/Photostore

**Comment by KeitIG** [comment]
@vojtatranta do you have a piece of code or a file to show to us ?

**Comment by vojtatranta** [comment]
@KeitIG yup, but I am using Redux, but I think it does not matter, usage will be similiar.
Take a look here https://github.com/vojtatranta/avcd-test-app/blob/master/containers/Root.js
This is where all the magic happens. You should probably also learn something about [Redux](https://github.com/rackt/redux) to understand it better, or you may just clone my app and you should be good to go:)

**Comment by aszwemin** [comment]
Thanks for that @vojtatranta <https://github.com/vojtatranta>. How do you
handle browser back button? I need to be able to do some logic on it and
redirect if needed, but don't seem to be able to find a good solution for
that.

**Comment by vojtatranta** [comment]
@aszwemin you are totally welcome. 
Sadly, I have no advice for you.

Back button works just as expected with react router. But I have no idea how you could handle back button, maybe History.js (which react-router uses under the hood) may have some event when user goes back, but you should google it, I know nothing about it.

**Comment by knowbody** [comment]
@aszwemin this might be a good start point https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md

**Comment by aszwemin** [comment]
@knowbody I was playing around with transitionHooks to do this, but I can't find a good way to redirect within them if need be.

**Comment by knowbody** [comment]
so do you want to redirect to some page when the user clicks on browser's back button? (don't have much time now to look into it but I'll get back to you)

**Comment by aszwemin** [comment]
Yes. For example user came to email verification page and then got redirected to settings. He then presses back button but I don't want him to be able to get back to verification page and want to redirect him to the index instead. Thanks for taking the time! :)

**Comment by knowbody** [comment]
cool! mind closing this issue? and creating the new one as they are not really related

**Comment by aszwemin** [comment]
will do :)

**Comment by aszwemin** [comment]
moved to #2133
