### ISSUE TITLE
View not updating on parameters change, only if reloaded

### ISSUE THREAD

**Issue by muraveill** [rackt/react-router#2083]
I have a component which content depends on URL query parameters. But it is not re-rendered when query parameters change. Only if I reload the page. I mean, the following changes have no effect unless I reload :

`/#/app` -> `/#/app?42` -> `/#/app?43`
`/#/app` -> `/#/app/42` -> `/#/app/43`

I'd want parts of the view to change if the parameter changes. How can I obtain that ?

Probably from the same kind of reason, when I do 

`/#/` -> `/#/app` 

some of the sub-components produce a warning `setState(...): Can only update a mounted or mounting component`, while if I reload the page everything works. N.B. Due to React warnings not indicating which setState it comes from, it is just a nightmare to identify.

My Routes are defined as follows :

    var routes = (
        <Route path='/' name='main' handler={App}>
            <Route path='/app' name='app' handler={App} />
            <Route path='/app/:db' name='app2' handler={App} />
        </Route>
    );

**Comment by mjackson** [comment]
This is fixed in master. Please try again when we release rc2.
