### ISSUE TITLE
match() doesnt render route correctly serverside

### ISSUE THREAD

**Issue by DWboutin** [rackt/react-router#2084]
Just delete this please

**Comment by edvinerikson** [comment]
What version are you on? Try run `npm list react-router`.
You need to be on `v1.0.0-rc1` to be able to use `match`.

**Comment by DWboutin** [comment]
You can close it, sorry i was in 0.13... I was sure to be at v.1

**Comment by mikhail-riabokon** [comment]
Do you have some errors, then you were trying change path?

**Comment by edvinerikson** [comment]
@DWboutin You should have a "close issue" button somewhere on the page.
