### ISSUE TITLE
Router chooses top-level route instead of a deeply-nested one?

### ISSUE THREAD

**Issue by jtompkins** [rackt/react-router#2086]
I have a route table that looks like this (with lots of additional routes removed):

```
<Router history={this.props.history}>
  <Route id='app' path='/' component={Kanapaha}>
    <Route id='people' name='People' path='people'>
      <Route id='accounts' name='Accounts' path='accounts' component={Accounts}>
        <Route id='account-workbook' name='Account Workbook' path=':accountnumber' component={AccountWorkbook}>
          <Route id='account-positions' name='Positions' path='positions'>
            <Route id='account-positions' name='Positions' path='summary' component={AccountPositionsSummary} />
          </Route>
        </Route>
      </Route>
    </Route>
  </Route>
</Router>
```
When matching a path like `/people/accounts/12345678/positions/summary`, the router is choosing the `/people/accounts/` route over the more deeply-nested route below it. If I remove the `component` attribute from the `accounts` route, the position summary route is properly selected. Can you give me a hint as to why the top level `/people/accounts` route is being chosen instead?

I've been working on this for a while and can't figure out what's going on.

**Comment by jtompkins** [comment]
My parent component does not render the children underneath; I was trying to nest the URLs but not the actual React components.

**Comment by walkerrandolphsmith** [comment]
> My parent component does not render the children underneath; I was trying to nest the URLs but not the actual React components.

How do we get the mentioned behavior? I would like a path like `games/game/123/settings`
