### ISSUE TITLE
have error when i set process.env.NODE_ENV = 'production';

### ISSUE THREAD

**Issue by andyxf1029** [rackt/react-router#2091]
below is router code

```
<Router>
    <Route path="/" component={Application}>
      <IndexRoute component={Home} />
      <Route path="rating" component={ratingApplication}>
      		<IndexRoute component={RatingModify} />
      		<Route path="modify" component={RatingModify}>
      				<Route path="node/:nodeId" component={RatingContent}/>
            	<Route path="step/:stepId" component={RatingStep}/>
      		</Route>
      		<Route path="import" component={RatingImport}/>
      		<Route path="ratetable" component={RateTable}/>
      </Route>
      <Route path="product" component={ProductApplication}>
          <IndexRoute component={ProductImport} />
          <Route path="import" component={ProductImport}/>
          <Route path="maintain" component={ProductMaintain}>
                <Route path="master/:id" component={ProductContent}/>
                <Route path="version/:id" component={ProductContent}/>
                <Route path="element/:id" component={ProductContent}/>
          </Route>

      </Route>
    </Route>
  </Router>


```

When I set process.env.NODE_ENV = 'production' before router  

Uncaught TypeError: Cannot set property 'props' of undefined  issue happen at 
  <IndexRoute component={Home} /> line 

```
    set: function(value) {
      ("production" !== process.env.NODE_ENV ? warning(
        false,
        'Don\'t set the %s property of the React element. Instead, ' +
        'specify the correct value when initially creating the element.',
        key
      ) : null);
      this._store[key] = value;
    }

```

**Comment by andyxf1029** [comment]
Uncaught TypeError: Cannot set property 'props' of undefinedObject.defineProperty.set @ ReactElement.js?ab2f:52ReactElement @ ReactElement.js?ab2f:136ReactElement.createElement @ ReactElement.js?ab2f:193ReactElementValidator.createElement @ ReactElementValidator.js?a599:396(anonymous function) @ index.js?9552:44(anonymous function) @ index.js?9552:64(anonymous function) @ index-25d313150bb1c159f554.js:434__webpack_require__ @ common.js:551fn @ common.js:99(anonymous function) @ index-25d313150bb1c159f554.js:7__webpack_require__ @ common.js:551webpackJsonpCallback @ common.js:22(anonymous function) @ index-25d313150bb1c159f554.js:1

code at line  <IndexRoute component={Home} />

**Comment by knowbody** [comment]
I don't think this is related to React Router. You might be doing something wrong in your `Home` component... If you give some more details maybe we will be able to help, and I'll reopen this issue. But again I don't think it's related to React Router.
