### ISSUE TITLE
Testing rendered routes

### ISSUE THREAD

**Issue by maitriyogin** [rackt/react-router#2092]
Hi,
first thanks for a most excellent router!
I'm trying to test my routes with mocha, jsdom and chai, having followed your test examples.
I want to be able to test the content of the dom to make sure it's reflective of the current route.
So I dug into the Router-test to see how you'd done it and tried the below out.
```js
let node;
  
  before('render and locate element', function() {
    node = document.createElement('div');
  });
  
  it('renders routes', function(done){
    let app = React.render((
      <Router history={createHistory('/inbox')}>
        <Route path="/" component={App}>
          <Route path="about" component={About} />
          <Route path="inbox" component={Inbox} />
        </Route>
      </Router>
        ), node, function (comp) {
          var appDiv = document.getElementById('app');
          expect(appDiv.nodeName).eql('div')
          done()
        })
  });
```
The App component is just a div with App as content ... simple ...
I want to check the dom to make sure that App Div has been rendered and then also test that the Inbox page div is in the dom as it's set in the history -
```js
it('has inbox as the initial page', function(done){
    var inboxDiv = node.getElementsByClassName('PAGE__inbox');
    expect(inboxDiv.nodeName).eql('div')
    done()
  });
```

So... this isn't working..
My question is whether this should work or if I should move this kind of testing into e2e tests?
I kind of like the ability to introspect the dom in a unit test without having to run the whole selinium web driver stuff, so If I could get this working I'd be a very happy man.
Any help is much appreciated.
Cheers,
Stephen.

**Comment by vojtatranta** [comment]
Hm, good question.
You might try different approach. You see that jsdom might not be able to emulate history correctly, and that's may be reason why this does not work.
However react-router can be simply rendered on the server without using anything related to browser.
So you can test your components "from server side". Returned mark up from the server must be equivalent to one that you get in the browser. 
See tutorial for [server-rendering here](https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/guides/advanced/ServerRendering.md).

**Comment by taion** [comment]
`node.getElementsByClassName('PAGE__inbox')` is going to return a list, on which `nodeName` is going to be undefined. And also the `nodeName` is going to be `DIV`, not `div. Your test case should be

```js
expect(inboxDiv[0].nodeName).to.equal('DIV')
```
