### ISSUE TITLE
Creating breadcrumbs from the router.

### ISSUE THREAD

**Issue by Industrial** [rackt/react-router#2094]
Hi.

It used to be so that every route had a name property. I would have been able to fill a breadcrumb navigation based on the selected route this way. Right now, I would need to create a second separate mapping to translate the current URL back to a list of names to display in the breadcrumb.

I'm not a Ruby on Rails user myself but I remember having used the functionality in the past. Having named routes would also make things like (2.3) http://edgeguides.rubyonrails.org/routing.html possible

What's the best way to do this?

**Comment by dmitry** [comment]
Named routes were removed from 1.0.0, at least for now... https://github.com/rackt/react-router/issues/1840

**Comment by vojtatranta** [comment]
Well since the router returns all fetched routes in nested way under components key in route instance, you can simply do something like this:
```js
class MyComponent extends Component {
  static getBreadcrumb() {
     return 'My capital component'
  }

  render() {
    //..
  }
}

//...
class MyNestedComponent extends Component {
  static getBreadcrumb() {
    return 'My nested component'
  }
  
  render() {
    //..
  }
}

class Breadcrumbs extends Component {
  render() {
    <ul className="breadcrumbs">
     {this.props.router.components.map(item => {<li>{item.getBreadcrumb()}</li>})}
    </ul>
  }
}
```
And you should be good. Hopefully, I did not tested this:))

**Comment by Industrial** [comment]
Hmm! That's a pretty nice pattern :o

**Comment by grabbou** [comment]
@mjackson maybe worth adding to one of the examples? Pretty handy.

**Comment by knowbody** [comment]
go for it @grabbou! please send the PR and I'll merge it
