### ISSUE TITLE
How do i add redirect to the routes dynamically?

### ISSUE THREAD

**Issue by mdcsfk** [rackt/react-router#2096]
I have sign in component, which should be available for unauthenticated users. And right after the authentication this component should become unavailable.
```js
   var routes = (
      <Route handler={App}>
        <Route name="signIn" handler={signIn}/>
        {/* redirect, if user is already authenticated */}
        { localStorage.userToken ? (
            <Redirect from="signIn" to="/user"/>
          ) : null
        }
      </Route>
    );

Router.run(routes, (Handler, state) => {
  React.render(<Handler {...state}/>, document.getElementById('main'));
});
```
This code works perfect if user have reloaded webapp for any reason after the authentication, but of course it doesn't if user didn't reload the webapp. I've tried to use this.context.router.transitionTo right to the SignUp component, but it works awful - the component gets rendered, then this script is getting executed.

So I want to add the redirect right into the routes variable to make the router redirect without even trying to render the component.

**Comment by knowbody** [comment]
please have a look at the [auth-flow example](https://github.com/rackt/react-router/tree/0.13.x/examples/auth-flow). It shows exactly what you are trying to do.
