### ISSUE TITLE
Transition and promises

### ISSUE THREAD

**Issue by bbnnt** [rackt/react-router#2098]
Well, the point here will be based on the use of react-resolver; but maybe this problem could affect a larger audience. What react resolver does, is that it wait for the data before rendering. Forget bout transitioning components then when using react-router.

I've looked into many issues here that could relate, but I can't get a real understanding of the state of this problem. Can react-router wait for the component to render and still manage a regular css transition ?

**Comment by mjackson** [comment]
I'm sorry. I don't understand your question.

**Comment by bbnnt** [comment]
Hups, sorry for that.
I mean : if the next router renders with a delay, transition does not work.
React-router does not wait

**Comment by apapirovski** [comment]
@bbnnt you could just adapt my middleware component — that you referenced — for your use. It would enable you to use `ReactCSSTransitionGroup`. Or you can use react-resolver, although it seems somewhat incompatible with Flux architecture.

There is no built-in way of doing this, at least currently.

**Comment by bbnnt** [comment]
thx yep, I'll definetely look into, even if I'm not that really into flux, I think that'd be an added valu to have a better control over transitions. currently that's just a ng-animate-clone; feels like react can 'go further'

@mjackson [there's this one too](https://github.com/ericclemmons/react-resolver/issues/89). My point here was about  having some kind of control over what's happening in the next controller — my example is bound to react resolver, but I guess there are needs for this elsewhere

**Comment by knowbody** [comment]
is this still an issue @bbnnt ?

**Comment by bbnnt** [comment]
@knowbody here (https://github.com/rackt/react-router-mega-demo/blob/master/app/handlers/Root.js#L61) it handles the "page" load, first visit. Correct me if I'm wrong

But you can expect "waiting for data" during your navigation from one component to the other.
I guess it is more about a global app architecture than just react-router; still an issue but I'll find out somehow
