### ISSUE TITLE
`Router` is undefined

### ISSUE THREAD

**Issue by iDuuck** [rackt/react-router#2100]
Hey guys, I am currently developing an application with Electron using React. When I started including the router it just gives the following error to me:
```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```
And the following **warnings**:
```
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: Only functions or strings can be mounted as React components.
```

When I just try to "debug" and `console.log` the different components I am getting an `undefined` in the console for `console.log(Router)`

Here is my script:
```js
import React from 'react';
import AppContainer from './containers/AppContainer';
import TasksContainer from './containers/TasksContainer';
import rootReducer from './reducers';

import createBrowserHistory from 'history/lib/createBrowserHistory';
import BrowserHistory from 'react-router/lib/History';
import { Router, Route } from 'react-router';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import './app.css';

// const history = createBrowserHistory();
const store = createStore(rootReducer);

React.render(
  <Provider store={store}>
    {() =>
      <Router history={BrowserHistory}>
        <Route component={AppContainer}>
          <Route path="/" component={TasksContainer} />
        </Route>
      </Router>
    }
  </Provider>,
  document.getElementById('react-root')
);
```

**EDIT:** Whether `react-router/lib/History`, nor `history/lib/createBrowserHistory` is working, though.

**Comment by mjackson** [comment]
It looks like you're using two different APIs. If you install rc1, you should `import createHistory from 'history/lib/createBrowserHistory'. Also, make sure you `npm install history`.

**Comment by freder** [comment]
sam here:

```javascript
var Router = require('react-router').Router;
console.log(Router);

import { Router2 } from 'react-router';
console.log(Router2);
```

gives me 2 × `undefined`

react-router@0.13.3

**Comment by knowbody** [comment]
@freder you are mixing the versions of React Router (0.13.x and 1.0.0-rc1).

Here are the docs for 0.13.x https://github.com/rackt/react-router/blob/0.13.x/docs/guides/overview.md#with-react-router

for 0.13.x use:

```js
var Router = require('react-router');
```
