### ISSUE TITLE
Uncaught TypeError: type.toUpperCase is not a function

### ISSUE THREAD

**Issue by MoezHmouma** [rackt/react-router#2102]
I get this:
Uncaught TypeError: type.toUpperCase is not a function
in browser console.

and this is my code in app.js:

    "use strict";
     var React = require('react');
     var Router = require('react-router');
     var Header = require('./components/Header');
     var Index = require('./components/Index');
     var About = require('./components/About')
     var Route = Router.Route;
     var IndexRoute  = Router.IndexRoute ;

     var App = React.createClass({
        render: function(){
            return (
                <div>
                    <Header />
                    <div>
                        {this.props.children}
                    </div>
                </div>
        );
      }
    })
    React.render(<Router>
    <Route path="/" component={App}>
    <IndexRoute  component={Index}/>
    <Route path="about" component={About}/>
    </Route>
    </Router>, document.getElementById('app'));

**Comment by mjackson** [comment]
Somewhere in your code you are using `undefined` as a component class.

**Comment by vlad-ignatov** [comment]
I have the same issue. The `<Router>` is the undefined component:

```js
import { Router, Route, Link } from 'react-router';
console.log(Router, Route, Link);
```
The above example logs:
```
undefined,  Route() {
	    _classCallCheck(this, Route);

	    if (_React$Component != null) {
	      _React$Component.apply(this, arguments);
	    }
	  },  Link() {
	    _classCallCheck(this, Link);

	    if (_React$Component != null) {
	      _React$Component.apply(this, arguments);
	    }
	  }
```
What am I missing here?

**Comment by MoezHmouma** [comment]
@mjackson I don't think I'm using    undefined as a component class, because when I remove the <Router> component from React.render function and replace it with any other component like <Header /> the code works fine

**Comment by vlad-ignatov** [comment]
Once again, this doesn't work and there is no Router class exported. The code I get from npm is different from what I see here. I use npm 3.3.3 and node 0.12.0. Then I noticed these:

[![build status](https://img.shields.io/travis/rackt/react-router/master.svg?style=flat-square)](https://travis-ci.org/rackt/react-router)
[![npm package](https://img.shields.io/npm/v/react-router.svg?style=flat-square)](https://www.npmjs.org/package/react-router)

Do you plan to update it?

**Comment by smbecker** [comment]
I'm seeing the same issue where Router is undefined. I think that this needs to be reopened.

**Comment by smbecker** [comment]
For some reason, when I did 'npm install react-router', it installed 0.13.3. When I removed it and added back in using latest released version '1.0.0-rc1', everything worked as expected.

**Comment by vlad-ignatov** [comment]
@smbecker Thanks. That helped me too. For some reason npm provides 0.13.3 but using `npm install react-router@latest --save` does the trick. 

Also note that even the link to the cdn version in the readme points to 0.13.3 ?!?.

**Comment by spike31** [comment]
Thanks @smbecker !
