### ISSUE TITLE
Rendering <Link> inside a mixin?

### ISSUE THREAD

**Issue by jakemmarsh** [rackt/react-router#2104]
I have a few cases in my application where I'm using a mixin to conditionally render an element (modals, etc.). If I try to directly use a `<Link>` component within them, I get the context error:

```
A <Link> should not be rendered outside the context of history; some features including real hrefs, active styling, and navigation will not function correctly
```

In 0.13, I was able to pass down a `navigateTo` function from the initially rendered parent component that just directly called the `navigateTo` method from within the correct context. However, this approach in 1.0.0-rc1 results in the error `maximum call stack size exceeded`.

Is there any better way to have links inside a mixin-rendered element?

**Comment by knowbody** [comment]
Please see #2089
