### ISSUE TITLE
Random Characters in the URL

### ISSUE THREAD

**Issue by bellicose100xp** [rackt/react-router#2105]
My URL have random characters in the end http://localhost:9005/#/__?_k=yl5yqr__ or http://localhost:9005/#/test**?_k=y9id0l**

Heres the file for Router, 

    'use strict';
    import React from 'react';
    import {Router, Route} from 'react-router';

    import App from './app';
    import Homepage from './components/homepage';
    import Customers from './components/customers';
    import Test from './components/test';

    React.render((
        <Router>
            <Route component={App}>
                <Route path="/" component={Homepage}/>
                <Route path="test" component={Test}/>
            </Route>
        </Router>
    ),
    document.querySelector('#app'));

How do I get rid of these? I'm using react-router 1.0.0-rc1

**Comment by vojtatranta** [comment]
Maybe that is because you use hash location, which holds state in url.

**Comment by Spy-Seth** [comment]
Here an explanation: https://github.com/rackt/react-router/blob/8ef625e8fa7c41dda0f3d1d68a10b74bd93a4101/docs/guides/basics/Histories.md#what-is-that-_kckuvup-junk-in-the-url

**Comment by DanielSundberg** [comment]
This was changed between 0.13.3 and 1.0.0-rc1.

There's also this thread:
https://github.com/rackt/react-router/issues/1967#issuecomment-143581059

I have not been able to figure why this has been added or how to get rid of this parameter in the url, and how that would affect my application.
