### ISSUE TITLE
How to capture navigation and ask for confirmation before navigating away from a route?

### ISSUE THREAD

**Issue by brijeshb42** [rackt/react-router#2106]
I am using react-router v0.13.3 and I tried using `willTransitionFrom` to capture navigation but it isn't working. I am using ES6 so I cannot use mixins.
My code:
```javascript
MyComponent.willTransitionFrom = function (transition, component) {
  console.log(transition);
  console.log(component);
  if(!confirm('Are you sure you want to leave?')) {
    transition.abort();
  }
};
```

**Comment by vojtatranta** [comment]
Depends on whether you want this to be global or not. 
I did it differently.
I directly listen to BrowserHistory for changes. Look at my code here https://github.com/vojtatranta/avcd-test-app/blob/master/containers/Root.js

**Comment by brijeshb42** [comment]
I am using v0.13.3. It does not have BrowserHistory.

**Comment by vojtatranta** [comment]
Ahaaa,
then you can do:
```js
//in case you want to have all this sorted on the level or react and router
Router.run(routes, function (Handler) {
  //this gets callend everytime you visit new page
  //so you can do
  if (Handler == HandlerIWantToConfirm) {
    if (!window.confirm('Realy want to quit?')) {
       React.render(<Handler/>, document.body);
    }
  } else {
    React.render(<Handler/>, document.body);
  }
})

//or onbeforeunload is always a possibility, but I am not sure, how it will work in SPA

```

**Comment by knowbody** [comment]
thanks @vojtatranta

**Comment by vojtatranta** [comment]
@knowbody but I am not sure whether this is a legit solution, I am sure that Michael Jackson would do this differently :))

**Comment by knowbody** [comment]
seems legit :+1: 

@mjackson will comment if he sees better solution :)

**Comment by brijeshb42** [comment]
I found a better solution:
```javascript
class MyComponent extends Component {
  static willTransitionFrom(component, transition) {
    if(!window.confirm('Are you sure you want to leave ?')) {
      transition.abort();
    }
  }
}
```

**Comment by ohenrik** [comment]
@brijeshb42 I'm not getting that function to run, is it supposed to work just like `componentWillMount` for example?

Here is the beginning of my class:
```
class RegisterClub extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.componentWillMount = this.componentWillMount.bind(this);
    this.isStage = this.isStage.bind(this);
    this.mutedClass = this.mutedClass.bind(this);
  }

  componentWillMount() {
    if(this.props.clubId) {
      this.props.clubActions.loadClubDetails(this.props.clubId);
    }
  }


  willTransitionFrom(component, transition) {
    console.log('happen');
    if(!window.confirm('Are you sure you want to leave ?')) {
      transition.abort();
    }
  }
```

**Comment by dpikt** [comment]
`willTransitionFrom` was removed in `react-router` 1.x
https://github.com/ReactTraining/react-router/issues/1388#issuecomment-129266129

**Comment by endel** [comment]
How's the 2017 way of doing this? :)

**Comment by endel** [comment]
Just stumbled upon this thread and here's a up-to-date documentation for this: https://reacttraining.com/react-router/web/example/preventing-transitions

**Comment by Sobient** [comment]
In VueJS 2, in your component, use the beforeRouteLeave lifecycle hook. 

Here's a very rudimentary example, like so:

```
  beforeRouteLeave (to, from, next) {
    if (this.contentSaved || window.confirm('You have unsaved changes, do you want to navigate away?')) {
      next()
    } else {
      return false
    }
    next()
  }
```
