### ISSUE TITLE
React-Router's Link render hash in Client-side but not in Server-side

### ISSUE THREAD

**Issue by DWboutin** [rackt/react-router#2111]
Hi, i try to render correctly in my client-side, but i got this error. It render my urls like this: #/home?_k=hqggr8. I want to get rid of these.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 1><a class="" href="#/" data-reactid=".1
 (server) 1><a class="" href="/" data-reactid=".1j
```

This is my repo: https://github.com/DWboutin/drug-lord

I don't know what cause this, i'm relatively new to React, but it been many hours that i search and try to render it another way to make it work. Can someone help me please? All articles i found about this was with the 0.13 version. 

Thank you

**Comment by DWboutin** [comment]
I added the history in my component in isomorphic-router.js `component = (<Router history={createHistory()}>{ renderProps.routes }</Router>);` 

Can someone guide me for the best structure to handle it? Is my project is well structured? Thank you

**Comment by knowbody** [comment]
@DWboutin are you still having those issues? Tried to access your repo but is not available anymore. If yes then I'll reopen the issue.

**Comment by blainekasten** [comment]
I'm currently hitting this same issue. When rendering with a `createHashHistory` `<Link>` tags get server rendered with actual urls, and then gets changed to hash urls on client side, resulting in the typical React error:

```error
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) "><a class="" href="#/0" data-reactid=".
 (server) "><a class="" href="/0" data-reactid=".1
```

**Comment by taion** [comment]
SSR doesn't really make sense in the context of using hash history - the hash isn't ever communicated to the server, so you can't render anything but the landing page. When using `match` the server just uses `createMemoryHistory` which behaves similarly enough to `createBrowserHistory` - https://github.com/rackt/react-router/blob/53623216560e34fbee02a99d926b5c69f163db35/modules/match.js#L7.

**Comment by blainekasten** [comment]
I was afraid that was going to be the answer. I mean, shouldn't it be patchable? If the routes being passed to match has a router with `createHashHistory` then just prepend a '#' on the server to any urls?

**Comment by blainekasten** [comment]
If not, there should probably be an explicit note that hash routing and server rendering are incompatible.

**Comment by taion** [comment]
Well, it's not that it's unsupported per se - it's that hashes aren't communicated to the server, so there's no way for it _to_ work.

**Comment by blainekasten** [comment]
Yes. I get that. I'll only ever get the '/' rendered. Which for my use case is fine. We are basically using the hash routing just to assign an active item in a queue. And that doesn't get decided until client side. So basically I'll I'm asking for is that react-router renders Link `to` urls correctly on the server with the hashes.

**Comment by taion** [comment]
That's a bit different from the "standard" SSR use-case. You should take a look at the implementation of `match` and write something tailored to your specific needs - `match` is just a pretty lightweight convenience wrapper around `history.match`, after all.

**Comment by axelson** [comment]
Another +1 on this because as far as I can tell there is no workaround that will get react-router to render the links on the server-side correctly.

I just need something that will change rendered links from:

    <a class="" href="/0" data-reactid=".1

to:

    <a class="" href="#/0" data-reactid=".

Is this possible? I do not see anything inside of `match` that allows configuring how the links are rendered.

**Comment by taion** [comment]
The reason there's no support for rendering hash history links on the server is that it doesn't make any sense to do so.

Hashes are client-side only and are not sent to the server, so there's no way to do server-side rendering of hash routes. If you try to do this with any other route, you'll actually get a mismatch between client and server markup.

This is a WONTFIX because it doesn't make sense to add support here.
