### ISSUE TITLE
Handling complex render states

### ISSUE THREAD

**Issue by RuudBurger** [rackt/react-router#2112]
I'm having issues with some complex components taking a long time to render. It's a map with 100+ areas on it, which takes 100ms to render on desktop and +1s on mobile or iPad.

Now the problem isn't the rendering itself, I think it's fairly optimized in HTML structure and code. But each time I navigate to another url and go back, it does the whole render process again. I understand this is how components work in react, mounting and unmounting.

I'm wondering if we can have a property on the route itself to keep it in memory? Or maybe you have another option to get this working. 

Without react-router I would set it up like this:

```
<div className="container">
    <ComplexPage1 className={this.state.currentPage == 'ComplexPage1' ? 'active' : ''}>
    <ComplexPage2 className={this.state.currentPage == 'ComplexPage2' ? 'active' : ''}>
    etc..
</div>
```

And then the pages are shown based on the CSS class `active`, keeping them in DOM but hiding the inactive ones. But how to do this in combination with react-router?

**Comment by knowbody** [comment]
This is something what you need to handle yourself. The router knows nothing about your components except that when you navigate to the particular URL it needs to mount some component.

You could use [Redux](https://github.com/rackt/redux) which helps with managing the state of the application to solve your problem.

**Comment by gaearon** [comment]
https://facebook.github.io/react/docs/advanced-performance.html

**Comment by knowbody** [comment]
thanks Dan!
