### ISSUE TITLE
Location  did not match any routes (1.0.0-rc1)

### ISSUE THREAD

**Issue by paveleremin** [rackt/react-router#2117]
_configuration/routes.js
```
import React from 'react';
import {Router, Route, IndexRoute} from 'react-router';

import App from './app';

import UserList from '../user-list/user-list';
import UserPrettyList from '../user-list-pretty/user-list-pretty';
import UserDetails from '../user-details/user-details';
import Error404 from '../errors/error-404.js';

export default function(history) {
    return (
        <Router history={ history }>
            <Route path="/" component={ App }>
                <IndexRoute component={ UserList }/>
                <Route path="pretty" component={ UserPrettyList }/>
                <Route path="users/:id" component={ UserDetails }/>
                <Route path="*" component={ Error404 }/>
            </Route>
        </Router>
    );
};
```

client.js
```
import React from 'react';
import Router from 'react-router';
import { createHistory, useBasename } from 'history';

import routes from './_configuration/routes';

// Add promise support for browser not supporting it
import es6Promise from 'es6-promise';
es6Promise.polyfill();

require('./_configuration/main.less');

const history = useBasename(createHistory)({basename: '/'});

React.render(routes(history), document.body);
```

this code not work at the client side, why?
I'm try to open in browser url:
http://localhost:3000/pretty
Error in console:
Warning: Location "pretty" did not match any routes

**Comment by dictions** [comment]
+1

**Comment by cbioley** [comment]
Have you tried without calling `useBasename`, just `createHistory`?

**Comment by joho** [comment]
I'm experiencing what I think is a similar problem.

client.js
```jsx
import React from 'react';
import Root from './containers/Root';
import { createHistory } from 'history';

//Needed for onTouchTap
//Can go away when react 1.0 release
//Check this repo:
//https://github.com/zilverline/react-tap-event-plugin
var injectTapEventPlugin = require("react-tap-event-plugin");
injectTapEventPlugin();

React.render(
    <Root history={new createHistory()} />,
    document.getElementById('app-container')
);
```

Root.jsx
```
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { Router, Route, RouteHandler, Redirect, IndexRoute } from 'react-router';

import configureStore from '../store/configureStore';
import Layout from '../containers/Layout';

import Groups from '../containers/Groups';

const store = configureStore();

export default class Root extends Component {
  render() {
    return (
        <Provider store={store}>
          {() =>
            <Router history={this.props.history}>
              <Route path='/' component={Layout}>
                <IndexRoute component={Groups} />
              </Route>
            </Router>
          }
        </Provider>
    );
  }
}
```

I first ran into it on the weekend and was experiencing the issue as infinite redirects (using hashHistory). I've since npm updated `history` and switched to plain `createHistory` and instead I get urls like `http://localhost:3000/#/?_k=5ja9he` when I visit `/` with a console warning of `Warning: Location "/" did not match any routes`

I hope I'm just doing something stupid, any help would be appreciated.

**Comment by dcalsky** [comment]
+1

**Comment by lucianlature** [comment]
+1

**Comment by knowbody** [comment]
I'm not entirely sure what this issue is about?

@paveleremin and @joho seems like two different issues to me, one of you is using redux the other is not. Not sure what +1 means? Do you have the same issue as both of them?

I'm happy to help but only if I can understand what the actual issue is.

@joho please have a look [here](https://github.com/rackt/redux-router) on how to use Redux with React Router.

@paveleremin I put the simple example on how to use React Router 1.0.0-rc1:

```js
import React, { PropTypes, Component } from 'react';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import { Router, Route, Link, IndexRoute } from 'react-router';

class Navigation extends Component {
  render() {
    return (
      <div>
        <ul>
          <li><Link to='/'>Main</Link></li>
          <li><Link to='/about'>About</Link></li>
          <li><Link to='/contact'>Contact</Link></li>
        </ul>
      </div>
    );
  }
};

class Contact extends Component {
  render() {
    return <div>Contact</div>;
  }
}

class About extends Component {
  render() {
    return ( <div>About</div> );
  }
}

class Home extends Component {
  render() {
    return <div>Home</div>;
  }
}

class App extends Component {
  render() {
    return (
      <div>
        <h1>App</h1>
        <Navigation />
        {this.props.children}
      </div>
    );
  }
}

export default class Root extends Component {
  render() {
    return (
      <Router history={createBrowserHistory()}>
        <Route path='/' component={App}>
          <IndexRoute component={Home} />
          <Route path='about' component={About} />
          <Route path='contact' component={Contact} />
        </Route>
      </Router>
    );
  }
}
```

please use it as an example, it should solve your problems

**Comment by dcalsky** [comment]
ok,I think I have solved my problem.
just use `history.js` , do not pay attention to 'history/lib/createBrowserHistory'.

### Router.jsx
```
import React from 'react';
import { Router, Route, Link, IndexRoute } from 'react-router';
import { createHashHistory } from 'history';

/* Import Component */
import Home from './pages/home.jsx';
import Layout from './pages/layout.jsx';

/* create history for router */
let history = new createHashHistory();

/* Router Config */
const routes = 
	<Router history={history}>
	    <Route path="/" component={Layout}>
		    <IndexRoute component={Home} />
		    <Route path="home" component={Home} />
	    </Route>
	</Router>
	;

/* export a function for app.js to run whole the app. */
export function start(){
		let rootInstance = React.render(routes , document.getElementById('app'));
		if (module.hot) {
		  require('react-hot-loader/Injection').RootInstanceProvider.injectProvider({
		    getRootInstances: function () {
		      return [rootInstance];
		    }
		  });
		}
};

```

### home.jsx

```
import React from 'react';

const Home = React.createClass({
  tranitionTo(){
    this.props.history.pushState(null, 'the route you wanna go');
  }
});
```

**Comment by bingjie2680** [comment]
I had the same issue, got an error saying `Location did not match any routes`.

I have routers set up like this:
    <Router history={createBrowserHistory()}>
        <Route path="" component={App}>
            <IndexRoute component={Home} />
            <Route path="category/:name" component={Category} />
        </Route>
    </Router>

When I navigate to the URL `localhost:8000/category/action`, it throws the error.

**Comment by nickwaelkens** [comment]
I'm completely new to React, but I'm having the same issue here.
I'm not even using browser history, as I'm using it in my Electron app. The routing works perfectly though, but I'm still getting this warning in console;

`Warning: Location "settings" did not match any routes`

(Using `react-router@1.0.0-rc3` and `react@0.14.0`)

**Comment by FredericHeem** [comment]
+1

**Comment by alexyer** [comment]
+1

**Comment by mcrider** [comment]
Me as well, using hashHistory and browserHistory.

**Comment by FredericHeem** [comment]
Actually, please check the *Link* component as described in https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#links
Use an absolute path instead of the name

**Comment by alexyer** [comment]
Yep. That worked for me. Thanks.

**Comment by mcrider** [comment]
Thanks @FredericHeem that did it -- Just needed to add a slash at the beginning of the route.

**Comment by nickwaelkens** [comment]
Thanks @FredericHeem @mcrider, absolute path did the trick!

**Comment by taion** [comment]
Thanks for sorting that one out.

**Comment by Kureev** [comment]
Had the same problem as a TS. In my case it was about old way I used for nested routes. I've used "Router" inside nested containers. Seems that in 1.0.0 versions it should be changed by `this.props.children`. 

By the way, I think it's worth to add to docs.

**Comment by mayacode** [comment]
probably it could help someone :) I had the same problem (and few additional) and this was what caused it:
`import Link from 'react-router';`

it should be, of course:
`import {Link} from 'react-router';`

**Comment by darrenburns** [comment]
@mayacode Thanks! Just made the same silly mistake :)

**Comment by thochi** [comment]
@mayacode: Thanks, you saved my day!

**Comment by AleffHenrique** [comment]
@FredericHeem That link is broken, could you share what it was about?
I wound't use Redux Router cause it is not stable enough but I had the same problem here (Location "/" did not match any routes). I applied all possible sollutions discursed here but nothing worked to me :(
:+1:

**Comment by AleffHenrique** [comment]
@FredericHeem that link is broken, could you share what it was about?
I have the same issue here (Location "/" did not match any routes), I applied all sollutions discussed here but nothing worked to me :(

**Comment by knowbody** [comment]
@AleffHenrique https://github.com/rackt/react-router/blob/master/upgrade-guides/v1.0.0.md#links

**Comment by AleffHenrique** [comment]
@knowbody Thanks :)

**Comment by sinkovsky** [comment]
@AleffHenrique I seem to have same problem as you with "browser.js:49 Warning: Location "/" did not match any routes". Were you able to find a solution?

**Comment by hoangphuoc25** [comment]
@mayacode thanks it really helps :+1:

**Comment by AleffHenrique** [comment]
@sinkovsky I didn't. you?

**Comment by nramirez** [comment]
+1

**Comment by nodkz** [comment]
I had same problem with react-router 2.0.0.
`Warning: [react-router] 'Router' no longer defaults the history prop to hash history. Please use the 'hashHistory' singleton instead. http://tiny.cc/router-defaulthistorywarning 
Warning: [react-router] Location "/" did not match any routes
`

# Check may be you made typo?!
## code:
<img width="450" alt="code" src="https://cloud.githubusercontent.com/assets/1946920/12775278/f20601ce-ca76-11e5-8e2d-d1575c235187.png">

## incorrect:
`import Link from 'react-router';`
<img width="612" alt="wrong" src="https://cloud.githubusercontent.com/assets/1946920/12775271/e10d82e8-ca76-11e5-9a0e-6293d14e412c.png">


## correct:
`import { Link } from 'react-router';`
<img width="556" alt="correct" src="https://cloud.githubusercontent.com/assets/1946920/12775272/e5b25c9c-ca76-11e5-983b-8bb6bce31e20.png">

**Comment by mdarif** [comment]
Thanks @FredericHeem, you saved me as well, stuck for couple of hours due to the same issue.

Unfortunately it's not documented anywhere.

+1

**Comment by oklas** [comment]
Another reason of same problem is dependency mess.
This solution help rare times, (as for me just now):

    rm -rf node_modules
    npm install

**Comment by Plummat** [comment]
this issue seemingly returned for me after a react-15 update.

**Comment by LeoLiuYan** [comment]
Location "/" did not match any routes
react-router version 2.4.0 and react 15.0.2

**Comment by osadan** [comment]
I have kind of the same problem when I use configuration . 
but when I use the routes direct I don't have the problem 

`const routes ={
            path: '/',
            component: App,
            childRoutes: [
                {path: 'about', component: About},
                {path: 'users', component: Users}
            ]
        } 

render(
	   
	<Provider store={store}>
	<Router history={hashHistory} >
		<Route path='/' component={App} >
			<Route path='about' component={About} />
			<Route path='users' component={Users} />
		</Route>
	</Router>
	</Provider>,document.getElementById("app")

	);`
