### ISSUE TITLE
How can I render server side use react-router and webpack? 

### ISSUE THREAD

**Issue by datnq201088** [rackt/react-router#2119]
I use react-router v1.0 , it's great client side. I am a newbie react. I try to read many documents but I am so confused, I dont know step to render server side? 
this is my file `app.js `

    'use strict';

    import express from 'express'
    import React from 'react'
    import { RoutingContext, match } from 'react-router';
    import createLocation from 'history/lib/createLocation';
    import { renderToString } from 'react-dom/server'

     import Home from './app/components/home/HomeComponent'

    const routes = {
     path: '/',
     component: require('./app/components/App'),
     indexRoute: {component: Home},
     childRoutes: [
       require('./app/components/about'),
        require('./app/components/inbox')
      ]
      }

    let server = express();
    server.use((req, res) => {
	// console.log(res);
	let location = createLocation(req.url)

	match({routes, location }, (error, redirectLocation, renderProps) => {
		if (redirectLocation)
			res.redirect( 301, redirectLocation.pathname + redirectLocation.search)
		else if(error)
			res.send(500, error.message)
		else if (renderProps == null)
			res.send(404, 'Not found')
		else
			res.send(renderToString(<RoutingContext {...renderProps} />))
	})
    })

**Comment by schauhan19** [comment]
Have you tried setting your routes to something like this (where `App`, `Home`, `About`, and `Inbox` would be instances of your components):
```javascript
import {Route, IndexRoute} from 'react-router';

<Route path='/' component={App}>
  <IndexRoute component={Home}/>
  <Route path='about' component={About}/>
  <Route path='inbox' component={Inbox}/>
</Route>
```

**Comment by datnq201088** [comment]
@schauhan19: thanks. I understand what you say. But I want to know flow of this issue. 
1. we must have 2 file: server.js (render server) and client.js (client render).
2. Then run script: `node server.js` 
Is this alright?

**Comment by datnq201088** [comment]
I had error
 `Error: Invariant Violation: renderToString(): You must pass a valid ReactElement.`

**Comment by mgreer** [comment]
What does your component look like? It might not be properly contained.

**Comment by datnq201088** [comment]
When i update to react v0.14.0-rc1 , It works fine!
