### ISSUE TITLE
Firefox: you may not have more than one route named "watch"

### ISSUE THREAD

**Issue by elsassph** [rackt/react-router#2120]
You can't define a route named `watch`, because `Object.prototype.watch`.

:facepalm:

**Comment by knowbody** [comment]
what's the issue?

**Comment by knowbody** [comment]
I'm not sure I understand the problem

**Comment by elsassph** [comment]
That seem to be fixed in the latest version.

It wasn't possible (runtime exception) define a route like: `<Route path="watch" ...`
