### ISSUE TITLE
Upgrading to v1.0.0 - contextType and createHref

### ISSUE THREAD

**Issue by johnnyreilly** [rackt/react-router#2121]
Hi,

First of all, props for creating react-router - it's awesome!  

I've just been attempting a port to react 0.14.0 and react-router 1.0.0 (the release candidates).  I've been tripped up by along the way and after puzzling over the upgrade documentation for a little while I thought I'd raise an issue.

In my existing application I've a number of components that make use of react router, specifically using `transitionTo` and `makeHref`.  From what I can tell it looks like since 1.0.0 you no longer pass the router via contextTypes but instead just [perform an import at the top of each component that required the router](https://github.com/rackt/react-router/blob/master/examples/huge-apps/components/GlobalNav.js). (["But I'm Using Classes" suggests otherwise...](https://github.com/rackt/react-router/blob/master/docs/API.md#but-im-using-classes) - though I'm not using `history` so perhaps this doesn't apply)

Clear as mud?  Of course.  Essentially what I've done is taken this: (0.13.3)

```
import React from 'react';

class NavigationBrand extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const homeHref = this.context.router.makeHref('summary');

    return (
      <div className="navbar-header">
        <div className="navbar-brand">
          <a href={ homeHref }>
            <img src="images/brand.png" />
          </a>
        </div>
      </div>
    );
  }
}

NavigationBrand.contextTypes = {
  router: React.PropTypes.func.isRequired
};

export default NavigationBrand;
```

to this:

```
import React from 'react';
import ReactDOM from 'react-dom'; // eslint-disable-line no-unused-vars
import { Router } from 'react-router';

class NavigationBrand extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const homeHref = Router.createHref('summary');

    return (
      <div className="navbar-header">
        <div className="navbar-brand">
          <a href={ homeHref }>
            <img className="trayport-logo" alt="Joule Direct" src="images/brand.png" />
          </a>
        </div>
      </div>
    );
  }
}

// NavigationBrand.contextTypes = {
//   router: React.PropTypes.func.isRequired
// };

export default NavigationBrand;
```

However this dies a death with:

> Uncaught TypeError: _reactRouter.Router.createHref is not a function

This leads me to the conclusion that I'm doing something wrong.  :sob:

Any ideas?  I'm afraid I've had a trawl through the examples but I can't see any that seem to do much with `transitionTo` / `makeHref`...

**Comment by knowbody** [comment]
please have a look at https://github.com/rackt/react-router/issues/1911#issuecomment-139843893

**Comment by johnnyreilly** [comment]
Hi @knowbody,

I've read the comment but I'm afraid it's not terribly clear.  Based on the comment I tried this:

```
import React from 'react';
import ReactDOM from 'react-dom'; // eslint-disable-line no-unused-vars

class NavigationBrand extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const homeHref = this.context.history.createHref('summary');

    return (
      <div className="navbar-header">
        <div className="navbar-brand">
          <a href={ homeHref }>
            <img src="images/brand.png" />
          </a>
        </div>
      </div>
    );
  }
}

NavigationBrand.contextTypes = {
   history: React.PropTypes.object.isRequired
};

export default NavigationBrand;
```

Happily this seems to work.  Performance appears a little sluggish and there's some quirky behaviour going on - I'll raise a separate issue for those.

**Comment by knowbody** [comment]
```js
class Component extends React.Component {
  static contextTypes= {
    history: React.PropTypes.object
  }
  render() {
    const homeHref = this.context.history.createHref('summary');
  }
}
```
