### ISSUE TITLE
Route onEnter not called when only changing query params

### ISSUE THREAD

**Issue by torarnek** [rackt/react-router#2122]
```js
const history = useQueries(createHistory)();

history.pushState(null, sameUrl, newQuery);
```

Does not trigger onEnter for route sameUrl.

However, when listening on history, state changes are triggered:

```js
history.listen(function (location) {
  console.log(location.query);
})
```
I think onEnter should be called when changing query params. ?

Using 1.0-rc1

**Comment by ufs-ibezler** [comment]
I try onChange, but it is not working in react-router 2.0.0. onEnter doesn't triggering if I change query params via router.push.

**Comment by ibhub** [comment]
I try onChange, but it is not working in react-router 2.0.0. onEnter doesn't triggering if I change query params via router.push.

**Comment by knowbody** [comment]
Please use StackOverflow or Reactiflux for support questions.

**Comment by ryanflorence** [comment]
see #2547
