### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by gorjuspixels** [rackt/react-router#2124]
I noticed the documentation has `ReactRouter.Router` component while it's missing in the lib directory

**Comment by knowbody** [comment]
that is correct and it's [here](https://github.com/rackt/react-router/blob/master/modules/Router.js)

**Comment by gorjuspixels** [comment]
@knowbody using `npm install react-router` to install it (v0.13.3), `import { Router } from 'react-router/lib/Router'` is not defined.. Same thing with `ReactRouter.Router`

**Comment by knowbody** [comment]
I am pretty sure you are looking at docs on master branch which are related to React Router 1.0.0-rc1.

The docs for 0.13.x can be found [here](https://github.com/rackt/react-router/tree/0.13.x/docs/guides).
