### ISSUE TITLE
Please release v0.13.4 so it doesn't break on IE 8?

### ISSUE THREAD

**Issue by ljharb** [rackt/react-router#2128]
getters aren't compatible with IE 8, which React otherwise is. Trying to use `es5-sham`'s `Object.defineProperty` without a "value" but with "get" or "set" throws an exception, by design.

https://github.com/rackt/react-router/blob/0.13.x/build/umd/ReactRouter.js#L915-L919

Is there some reason this can't set a normal "false" property, at least in IE 8?

**Comment by taurose** [comment]
See https://github.com/rackt/react-router/pull/1143

**Comment by ljharb** [comment]
@mjackson Glad to see it's fixed - is there any chance for a `0.13.4` version? It would help the upgrade path to `1.0` to be able to fix this bug in one step, and separately, test the upgrade.

**Comment by ljharb** [comment]
@knowbody can you please provide an explanation for closing this? This is blocking our ability to use or upgrade `react-router`.

**Comment by knowbody** [comment]
@ljharb I closed it as @taurose pointed out the "duplicated" issue. I will try to push on the 0.13.4 release so you can use the 0.13.x without this bug.

**Comment by ljharb** [comment]
Thanks - I was considering this issue "release v0.13.4" :-) i'll update the title.

**Comment by mjackson** [comment]
Thanks for bringing this up @ljharb. We'll cut a 0.13.4 release as you suggest.

**Comment by ljharb** [comment]
Yay, thanks!

**Comment by jefferydutra** [comment]
Any update on the 13.4 release; thank you for doing this, it will be a great help.

**Comment by mjackson** [comment]
Ok, so, uh, when I said this was "fixed" I meant it was fixed in the 1.0 rewrite. :P 

I'll cut a 0.13.4 release that removes the getter but we can't to any more maintenance releases on the 0.13 branch. We just don't have the capacity to maintain two APIs at once. You should upgrade to 1.0 as soon as you can :)

**Comment by mjackson** [comment]
ok, [done](https://github.com/rackt/react-router/releases/tag/v0.13.4)

**Comment by jefferydutra** [comment]
Thank you for this, and thank you for all the work you do for the community.

**Comment by mjackson** [comment]
You're welcome :)

**Comment by ljharb** [comment]
Thank you!

**Comment by ljharb** [comment]
@mjackson can you `npm publish` it also?

**Comment by mjackson** [comment]
@ljharb It's there for me. `npm install react-router@0.13.4`

**Comment by ljharb** [comment]
oops, you're right, i see it - thanks again!

**Comment by mjackson** [comment]
np ;)
