### ISSUE TITLE
Is it possible to match arbirarily deep routes?

### ISSUE THREAD

**Issue by d4goxn** [rackt/react-router#2129]
In my app, I have a category page that handles routes like

```
/entertainment/tv/simpsons
/food/recipes
/cars
```

I would like to match all of these with a single route handler, after matching higher precedence routes like `/login` and `/edit`. Something like:

```jsx
<Route handler={App}>
  <Route path="/about-us" handler={Page}/>
  <Route path="/edit" handler={ArticleEditor}/>
  <Route path="/**" handler={CategoryIndex}/>
  <Route path="/:articleSlug" handler={Article}/>
</Route>
```

It seems that a `*` pattern only matches inside of slashes, it cannot actually match slashes. This is consistent with filesystem globs, so it is not really surprising. I do not want to abuse the `NotFound` route handler to match stuff, partly because that's just wrong, but also because it would prevent me from havingan even lower precedence route that matches articles: `/:article-slug`.

As far as I can tell, this would require a new feature - something like the `**` shell glob operator that matches deep paths. Is this necessary? If so, is it desirable, and are there any special cases that I should be aware of while working on a PR? It looks like there are some special rules around the `.` character, after reading through #142.

**Comment by mjackson** [comment]
You're using an old version of the router. In 1.0 (currently rc1) [you can use `*`](https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteMatching.md#path-syntax) to match "all characters (non-greedy) up to the next character in the pattern, or to the end of the URL if there is none". There's no way to do this elegantly in the 0.13 API.
