### ISSUE TITLE
TypeError: history.listen is not a function

### ISSUE THREAD

**Issue by davetgreen** [rackt/react-router#2132]
Having trouble implementing history with react-router.

Currently using react@0.14.0-rc1 and react-router@latest. The error does rear its head with react@13.3 as well.

This is my main file where I'm requiring the various page controllers (I'm still new to structuring React apps so forgive me if this isn't the Proper Way(tm)) and then rendering my defined routes.

````
// External dependencies.
var React = require('react');
var ReactRouter = require('react-router');
var Router = ReactRouter.Router;
var Route = ReactRouter.Route;
var createBrowserHistory = require('history/lib/createBrowserHistory');

// Internal dependencies.
var HomeController     = require( './controllers/home/' );
var AboutController    = require( './controllers/about/' );
var BlogController     = require( './controllers/blog/' );
var WorkController     = require( './controllers/work/' );
var NotFoundController = require( './controllers/notfound/' );

// Target element.
var site = document.getElementById( 'site' );

// Define routes and render.
React.render((
	<Router history="{createBrowserHistory()}">
		<Route path="/"     component={HomeController}/>
		<Route path="about" component={AboutController}/>
		<Route path="blog"  component={BlogController}/>
		<Route path="work"  component={WorkController}/>
		<Route path="*"     component={NotFoundController}/>
	</Router>
), site);
````

...is producing this warning and error:

`Warning: Failed propType: Invalid prop 'history' of type 'string' supplied to 'Router', expected 'object'.`

`TypeError: history.listen is not a function`

I'm not sure if this is a bug or user error, but I thought I'd post it after @knowbody suggested I do so.

**Comment by knowbody** [comment]
oh get rid off `""`, should be:

```js
<Router history={createBrowserHistory()}>
```

**Comment by davetgreen** [comment]
My bad, I'm tired and should have seen that myself! It converts it to a string rather than being an object, doh! Cheers! :+1:

**Comment by rubenhazelaar** [comment]
Strangely enough I have the same issue, however I believe my code is ok:

    import React, { Component } from 'react';
    import { render } from 'react-dom';
    import { Router,  Link, Route } from 'react-router';
    var createBrowserHistory = require('history/lib/createBrowserHistory');

    render(
	<Router history={createBrowserHistory()}>
		<Route path="/" component={Dashboard}>
			<Route path="/campaigns" component={Campaigns}/>
		</Route>
	</Router>,
	document.getElementById('root')
    );

Results in:

     TypeError: history.listen is not a function

I'm using 1.0.0-rc3

**Comment by rey-wright** [comment]
Note: If you're using Redux Router, you will also get this error if you format the render incorrectly:

```<Provider store={store}>
        <ReduxRouter>
        {routes}
        </ReduxRouter>
    </Provider>```
