### ISSUE TITLE
[query] Redirect from transitionHook

### ISSUE THREAD

**Issue by aszwemin** [rackt/react-router#2133]
Sometimes one may need to redirect users from the transitionHook (e.g. on browser back button when they would navigate to page we don't want them to see again). Any good idea how this could be achieved?

It's a follow up from #2081

**Comment by aszwemin** [comment]
One way seems to be to rewrite location.pathname in the transitionHook, but not sure how sane that is.

**Comment by knowbody** [comment]
I just had a quick look into it. And this is probably super hacky, but you could do something like:

```js
history.listen((location) => {
  if (location.pathname === '/verify' && location.action === 'POP') {
    history.pushState(null, '/');
  }
});
```

So if the user was on `/verify` and then went to let's say `/almost-done` and then click a back button, then your `location.pathname` is going to be `/verify` and the `location.action` would be `'POP'` so you can redirect on that.

Again probably there is a better way of doing that. @mjackson is the History master :stuck_out_tongue_winking_eye:

**Comment by aszwemin** [comment]
I was trying to do the same in registered transition hook and it was sad about doing transition from within the transition. But the above works well.

I wonder if it's possible to stop transition from .listen though
