### ISSUE TITLE
Deeply nested async routes do not mount component with Redux

### ISSUE THREAD

**Issue by DarrenN** [rackt/react-router#2134]
I have a small prototype using React, Redux and React-Router 1.0.0-rc1. The prototype uses Webpack to do code splitting. It currently uses getComponents and getChildRoutes to async load additional routes like so:

```javascript
module.exports = {
  path: 'donations',

  getChildRoutes(location, cb) {
    require.ensure([], (require) => {
      cb(null, [
        require('./routes/Donation'),
      ]);
    });
  },

  getComponent(location, cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/Donations'));
    });
  }
};
```

This works fine, until I hit the nested route `donations/:id`, which looks like:

```javascript
module.exports = {
  path: ':id',

  getComponent(location, cb) {
    require.ensure([], (require) => {
      let mod = require('./components/Donation');
      console.log('module loaded', mod);
      cb(null, mod);
    });
  }
};
```

When I navigate to this route (ex: `/donations/123`), the route is triggered, the bundle.js file is loaded, and the `console.log` values appear in the console, so I know that the route was loaded up into memory. **However**, the component is not mounted and rendered.

The component that is returned is wrapped with Redux's Connect like so:

```javascript
 function Connect(props, context) {
          _classCallCheck(this, Connect);
          _Component.call(this, props, context);
          this.version = version;
          this.store = props.store || c… 
```

Async routes one level deep are fine, but nesting past that doesn't work. The component is loaded, but it doesn't seem like it's executed. I'm going to take a guess that somehow the component being wrapped in `Connect` might be causing problems, but am not sure how to address.

**Comment by DarrenN** [comment]
Small update - 

When I remove the `connect` wrapper from `Donate` and turn it into a dumb component it still fails to mount. `componentWillMount` is not triggered.

**Comment by DarrenN** [comment]
Discovered the issue, had to do with this.props.children.

**Comment by szhclaye** [comment]
how do you solve this problem?

**Comment by DarrenN** [comment]
@szhclaye answer: http://stackoverflow.com/a/32922593/12799

**Comment by szhclaye** [comment]
thanks  very mutch

**Comment by szhclaye** [comment]
But...i still cannot understand the reason why the result of console.log('this.props.children') is undefined? Please....

**Comment by DarrenN** [comment]
@szhclaye perhaps paste some code with an explanation of what's happening?

**Comment by szhclaye** [comment]
app.js
const routeConfig = {
        path:'/',
        component: require('./components/DemoApp'),
        childRoutes:[
            require('./routes/Home'),
            require('./routes/Calendar'),
            require('./routes/Grade'),
            require('./routes/Messages')
        ]
}

function createComponentWithProvider(){
    return (
        <Provider store={store}>
            {()=><ConnectComp />}
        </Provider>
    )
}

React.render(
    <Router history={history}
            routes={routeConfig}
            createElement={createComponentWithProvider}/>,
    document.getElementById('example')
)

ConnectComp.js
function mapStateToProps(state){
    return {
        loginState:state.loginReducer
    }
}

function mapDispatchToProps(dispath){
    return {
        actions:bindActionCreators(LoginActions,dispath)
    };
}

export default connect(
                mapStateToProps,
                mapDispatchToProps
                 )(DemoApp);

DemoApp.js  smart component
export default class DemoApp extends Component{
    render(){
        console.log(this.props.children);
        return (
            <div>
                <GlobalNav />
                {this.props.children}
            </div>
        )
    }
}

Before using redux,console.log(this.props.children) gei result below:
ReactElement {key: null, ref: null, _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}
it runs right
But using redux,console.log(this.props.children) become:
undefined
it is wrong!!

Can you tell me why?

**Comment by DarrenN** [comment]
@szhclaye why are you putting `createComponentWithProvider` in `createElement` ?

**Comment by szhclaye** [comment]
this way I can use createElement making Provider nest my component...

**Comment by szhclaye** [comment]
Like here https://github.com/rackt/react-router/blob/master/docs/API.md#router

**Comment by szhclaye** [comment]
can you give me your example？？

**Comment by DarrenN** [comment]
> this way I can use createElement making Provider nest my component...

Doesn't that wrap every component that the Router injects with `Provider`?

I use React 0.14:

```javascript
// Initial routes
let rootRoutes = {
  component: 'div',
  childRoutes: [{
    path: '/',
    component: require('./containers/MainContainer'),
    childRoutes: [
      require('./routes/Login'),
      require('./routes/ForgotPassword')
    ]
  } /* ... */]
};

/**
 * Inject the store as a prop into all Components from react-router
 */
function createElement(Component, props) {
  let p = Object.assign({}, props, { store });
  return <Component {...p} />;
}

// Render the router
ReactDOM.render(
    <div>
      <Provider store={store}>
       <Router routes={rootRoute}
               createElement={createElement}
               history={history} />
      </Provider>
      {devComponent(store)}
  </div>,
  document.getElementById('root')
);
```

**Comment by szhclaye** [comment]
Thanks，I will try
