### ISSUE TITLE
what's the latest on scrolling?

### ISSUE THREAD

**Issue by davis** [rackt/react-router#2135]
i read through a bunch of the issues re: scrolling, and as of now I still don't know what the best way to make the browser scroll to top on routing. Am I waiting for something to be released? or has it already been released?

**Comment by knowbody** [comment]
still waiting. there should be something in a few weeks

**Comment by jackmoore** [comment]
@davis https://github.com/rackt/react-router/issues/2144#issuecomment-144462974
