### ISSUE TITLE
Render server side error v1.0 

### ISSUE THREAD

**Issue by datnq201088** [rackt/react-router#2139]
I tried to render server side but I get this error. I run `babel-node app/server.js` . What did I miss? 

    Error: Invariant Violation: renderToString(): You must pass a valid ReactElement.
    at invariant (/home/datnq/flux/node_modules/react-dom/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)
    at renderToString (/home/datnq/flux/node_modules/react-dom/node_modules/react/lib/ReactServerRendering.js:31:83)
    at /home/datnq/flux/src/server.js:40:21
    at /home/datnq/flux/node_modules/react-router/lib/match.js:40:5
    at /home/datnq/flux/node_modules/react-router/lib/useRoutes.js:88:15
    at /home/datnq/flux/node_modules/react-router/lib/useRoutes.js:124:15
    at done (/home/datnq/flux/node_modules/react-router/lib/AsyncUtils.js:49:19)
    at /home/datnq/flux/node_modules/react-router/lib/AsyncUtils.js:55:7
    at getComponentsForRoute (/home/datnq/flux/node_modules/react-router/lib/getComponents.js:9:5)
    at /home/datnq/flux/node_modules/react-router/lib/getComponents.js:28:5`

This is `server.js`

    import express from 'express'
    import React from 'react'
    import createLocation from 'history/lib/createLocation'
    import { RoutingContext, match} from 'react-router'
    import { renderToString } from 'react-dom/server'
    var Home = require('./app/components/home/HomeComponent')

    const routes = {
	path: '/',
	component: require('./app/components/App'),
	indexRoute: {
		component: Home
	},
	childRoutes: [{
		path: 'about',
		component: require('./app/components/about/About')
	}, {
		path: 'inbox',
		component: require('./app/components/inbox/Inbox'),
		childRoutes: [{
			path: 'messages/:id',
			component: require('./app/components/inbox/components/Message/Message')
		}]
	}]
    };

    var server = express();
    server.use((req, res) => {
	let location = createLocation(req.url)

	match({routes, location}, (error, redirectLocation, renderProps) => {
		if (redirectLocation)
			res.redirect(301, redirectLocation.pathname + redirectLocation.search)
		else if (error)
			res.send(500, error.message)
		else if (renderProps == null)
			res.send(404, 'Not found')
		else {
           res.send(renderToString(<RoutingContext {...renderProps}/>))
         }
    })
    })

    server.listen(8080, function() {
	console.log('Listening on port: 8080');
    });

My components:

app/components/App.js

    import React from 'react';
    import Header from './common/HeaderComponent';

    const App = React.createClass({
      render() {
        return (
          <div>
            <Header />
            <div className="main-content">
            {this.props.children}
           </div>
         </div>
       )
      }
      })
     export default App;

About: 

    import React from 'react';
    const About = React.createClass({
     render() {
       return (
        <div >
        <h3>About</h3>
        </div>
      )
     }
    })
    export default About;

Inbox: 

     import React from 'react';
    const Inbox = React.createClass({
     render() {
       return (
      <div >
        <h2>Inbox</h2>
        {this.props.children || "Welcome to your Inbox"}
      </div>
      )
      }
    });
    export default Inbox;

Message:

    import React from 'react';
    const Message = React.createClass({
      render() {
       return (
          <div >
              <h3>Message {this.props.params.id}</h3>
         </div>
       )
      }
    })
    export default Message;

**Comment by iNikNik** [comment]
I've got the same issue ~week ago. Unfortunately, I had no time to investigate, but I my it was not the issue with RR. `renderToString(<h1> HELLO </h1)` was throwing same exception.
It happens when I experimented with new react version, after I did rollback to previous version - error has disappeared.

**Comment by brunoqueiros** [comment]
I had the same error.

Using 1.0.0-rc1

**Comment by Predjo** [comment]
Can confirm this. Had same thing happen also with 'Using 1.0.0-rc1'.

**Comment by brunoqueiros** [comment]
@Predjo I updated react to 0.14.0-rc1 and now is working! Before I was using 0.13.3.

thx

**Comment by datnq201088** [comment]
Thanks, It's great when i update  to .14.0-rc1
