### ISSUE TITLE
Nested routers not working

### ISSUE THREAD

**Issue by AdrianRibao** [rackt/react-router#2140]
I have configured this routes:

```html
<Route path="/" component={LimitsApp}>                    
    <IndexRoute component={Limits} />                      
    <Route path="limits" component={Limits}>              
        <Route path="delete/:id" component={DeleteLimit} />
    </Route>                                               
    <Route path="new" component={NewLimit} />              
</Route>                                                   
```

But when I access the url `/limits/delete/1' the `Limits` component is always rendered.

**Comment by datnq201088** [comment]
Do you use should use  `history`  to have pretty url

    import createBrowserHistory from 'history/lib/createBrowserHistory';
    let history = createBrowserHistory();

       React.render(
          <Router history={history} routes={routes} />,
              document.body
     );

**Comment by knowbody** [comment]
@AdrianRibao that would happen if you are not adding `{this.props.children}` inside your `Limits` component
