### ISSUE TITLE
Migration problems with active component

### ISSUE THREAD

**Issue by Dodelkin** [rackt/react-router#2146]
Hi, I've got some problems when I tried to migrate to the new version.

Right now I'm with 0.13.3 version, so, for the sidebar I'm using a library:
https://github.com/insin/react-router-active-component
This lib hasn't got any updates for a long time, and probably it won't be updated to the new react-router version.

The point is that I need to add active class not exactly to    ```  <a> ``` tag, but, for example, to ```<ul> ```or ```<li>```

Do you have any intentions to add some props for the Link component, to set which tag our Link should render?

Or, if you have any suggestions on this problem, you are welcome to share it. 

Thanks in advance!

**Comment by edvinerikson** [comment]
You can use the [History mixin](https://github.com/rackt/react-router/blob/master/docs/API.md#history-mixin) to get access to the [isActive](https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query) method.
See the second [example](https://github.com/rackt/react-router/blob/master/docs/API.md#examples-1) for an implementation.

**Comment by knowbody** [comment]
thank you for helping @edvinerikson
