### ISSUE TITLE
How to avoid redraw when go back

### ISSUE THREAD

**Issue by thinkkevin** [rackt/react-router#2147]
I am building a list and detail type web app using react(v.0.13.3) and history(v1.9.1) react-router (v1.0.0-rc1). 

The list is generated after some AJAX API calls.
When I click any item in the list, it will jump to detail page. Then I click browser's back button, it will go back to list page. But it will resend the AJAX request and re-generate the list. 

This is bad user experience. 

I think react-router could somehow cache the `this.props.children` content with `this.props.location.key`. When go back happen, it will fill `this.props.children` with previous generated contents.

Anyone has some solution or workaround?

Thanks

**Comment by grabbou** [comment]
This is actually something that works in React Native, where when you use Navigator and push a new scene onto your stack, the previous one does not get unmounted. 

Anyway, I guess the proper way to address your issue would've been to use e.g. Redux, keep your data in a store like this:
```
{
   items: null,
   isLoading: false
} 
```

And then, issue an action to load your items from a didMount method only if:
```
If (!this.props.items) { this.props.dispatch(loadItems()); }
```

**Comment by knowbody** [comment]
this is something React Router is not designed for. We do the routing for you, you need to deal with the way you fetch your data.
