### ISSUE TITLE
.toUpperCase undefined when trying to import IndexLink

### ISSUE THREAD

**Issue by georgeamine** [rackt/react-router#2148]
<IndexLink to="/" activeClassName="is-active">Home</IndexLink>

I'm trying to use this so that my Home tab is only active on the IndexRoute, however i get this error.

**Comment by ibjohansen** [comment]
I think that doing an *npm install react-router* as this is written will give you v. 0.13 of the router, which does not have the same methods as these examples describe, see the 0.13 branch docs [here](https://github.com/rackt/react-router/tree/0.13.x) or do an *npm install react-router@1.0.0-rc1*

**Comment by knowbody** [comment]
also make sure that you import it correctly:

```js
import { IndexRoute } from 'react-router';
```

**Comment by sheltonial** [comment]
@georgeamine The upgrade guide (0.13.3 -> 1.0.0) refers to `IndexLink`, though this does not seem to exist in 1.0.0-rc1. Had the same issue as you and stumbled across the `onlyActiveOnIndex` attribute which will do the job.
```
<Link to="/some/indexroute" onlyActiveOnIndex={true}>go</Link>
```
