### ISSUE TITLE
Write the testing docs

### ISSUE THREAD

**Issue by knowbody** [rackt/react-router#2149]
We are missing the testing docs for React Router 1.0

**Comment by chiedojohn** [comment]
Glad this is on the radar

**Comment by chiedojohn** [comment]
I'll be working on the docs this week. (Unless someone else has started and didn't comment here)

I plan to write the docs with the assumption that Jest is being used. Does anyone have objections to that?

**Comment by knowbody** [comment]
great! thanks @chiedojohn. looking forward to seeing the PR :smile:

**Comment by chiedojohn** [comment]
Just wrote some docs and submitted the PR @knowbody. Hope they're sensible. Writing docs in a concise manner is always so challenging. Haha.

**Comment by Dindaleon** [comment]
Do you plan to write docs for those who use mocha?

**Comment by knowbody** [comment]
yes! I'd like the docs to be helpful for everyone!

If you want to do it please submit the PR if not I'll work on that. closing this issue, as I forgot to do it after @chiedojohn PR.
