### ISSUE TITLE
Equivalent of async-data example using v1.0.x

### ISSUE THREAD

**Issue by lionelB** [rackt/react-router#2152]
Hello
Do you plan to add an example like [async-data](https://github.com/rackt/react-router/tree/0.13.x/examples/async-data) using the v1.0 of react-router 

I'm currently trying to migrate my app (a simple master-slave app with server-side rendering) to the latest version of react-router and I don't know how to proceed. I was relying on https://github.com/rackt/react-router/blob/0.13.x/examples/async-data/app.js#L36-L38 to fire flux action. For now I not sure what will be the correct way tot do that.

ps:  I also plan to move from flux to [redux](https://github.com/rackt/redux) )

**Comment by vojtatranta** [comment]
I used 1.0.2b2 in my app https://github.com/vojtatranta/Photostore

**Comment by taion** [comment]
Let's keep discussion regarding this in https://github.com/rackt/react-router/issues/2101.
