### ISSUE TITLE
routerWillLeave not work, need help

### ISSUE THREAD

**Issue by EcutDavid** [rackt/react-router#2153]
Before I add Lifecycle mixin and  routerWillLeave, every thing is fine.    
![worked](https://cloud.githubusercontent.com/assets/10692276/10224043/c06c09b4-688e-11e5-9f8f-abe863a609bd.gif)    
After I add the code like this:
```
  mixins: [PureRenderMixin, Lifecycle],

  routerWillLeave(nextLocation) {
      return 'Your work is not saved! Are you sure you want to leave?';
  },
```   
The url really change, but route not work, still on the same page.   
![notwork](https://cloud.githubusercontent.com/assets/10692276/10224158/407da798-688f-11e5-9839-ec7c29d8720f.gif)
Thanks!!!

**Comment by vn38minhtran** [comment]
https://github.com/rackt/react-router/issues/1930
If same bug it had been fixed. Please wait next release.

**Comment by EcutDavid** [comment]
@vn38minhtran  thank you.
Hope rc2 can fix the problem.
