### ISSUE TITLE
Complete example please of router 1.0.0 RC1 where props are passed to nested routes

### ISSUE THREAD

**Issue by JoeGrasso** [rackt/react-router#2154]
I have scoured this github for insight in passing props to nested routes to no avail. All I see are partial samples, terse responses, and ambiguous links to other issues.

I read phrases bantied about like 'context' or createElement, but no full examples of their implementation.

Can someone offer some decent documentation on using RC1 with nested routes where you pass, as example, a blessed 'title' property to each component in the nested routes?

It is apparent that react-router is the defacto router for React, I just wish there was better documentation.

Thank You.

**Comment by confiks** [comment]
It's in the [upgrade guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#routehandler). Where you could previously use `RouteHandler` to render child routes, you now use `React.cloneElement`. Be wary that if `this.props.children` is null, `React.cloneElement` will raise an exception.

**Comment by JoeGrasso** [comment]
Appereciate the response, but true to form to the guys at RR, everything is terse. It would be nice if once, they laid out a complete example, instead of assuming we are all Carnac the mind readers.

**Comment by knowbody** [comment]
what kind of example are you looking for?

**Comment by confiks** [comment]
Could you explain what is incomplete in this example:
`{React.cloneElement(this.props.children, {someExtraProp: something })}`

**Comment by JoeGrasso** [comment]
It's too terse an explanation. You would make a lousy teacher.

**Comment by knowbody** [comment]
@JoeGrasso you can find a bit more about it in the [Router documentation](https://github.com/rackt/react-router/blob/master/docs/API.md#createelementcomponent-props). Also there was the previous issue opened on the same topic, please have a look here #1531.

and I think this short example in the Upgrade Guide is self-explanatory. If you think we are missing something please tell us what you would like to see or send the PR with suggested changes. We all work to make the React Router better every day :wink:

**Comment by JoeGrasso** [comment]
Would it really kill you to provide a full blown blessed example?

You guys eat, sleep, and sh*t this everyday and you fail to recognize that others do not.

Annoys the frig out of me you cannot provide a blessed 'full blown' example of say a main app and two child routers being passed properties through react-router 1.0.0

I loathe brevity. Verbosity leaves little confusion.

**Comment by confiks** [comment]
You should yourself be a little more considerate to the people you talk to here. Take up your own advice, and be verbose about what you are missing from the [current examples](https://github.com/rackt/react-router/blob/15b05b4f2ca8b4ade5f7378ed1839b752a62babc/examples/passing-props-to-children/app.js). 

With all the information thrown at you now, you should be able to understand how passing props to child routes works. You can thus now create that example yourself, and create a PR to help others.

**Comment by anjdreas** [comment]
See https://github.com/rackt/react-router/issues/1531#issuecomment-146514399 for a detailed example of the 3 methods I know on property passing to routes.

**Comment by conor909** [comment]
Iv adapted the use of `React.cloneElement(this.props.children, { appState: this.state });`  to pass properties.  But my issue is I am passing a function as a property. The function should return an object, but it doesn't.  It is saying my object is undefined.  The function executes so I know I am passing the function down correctly.  Should I be doing something different in this case?
