### ISSUE TITLE
Inner Route not working

### ISSUE THREAD

**Issue by Et3Ali** [rackt/react-router#2156]
Hi,
I am unable to route when switching from inner route to another.
this is my route:
```js
<Router>
  <Route path="/" component={Encounter} />
  <Route name="search" path="search/" component={search} />
  <Route name="notification" path="notification/" component={Notification} />
  <Route name="inbox" path="inbox/">
    <IndexRoute component={Inbox} />
    <Route name="conversation" path=":userID" component={Conversation} />
  </Route>
  <Route path="*" component={NotFound} />
</Router>
```
```
http://localhost:8080/#/encounter -> http://localhost:8080/#/inbox/123 //work fine
http://localhost:8080/#/inbox/123 -> http://localhost:8080/#/inbox/456 //not working
http://localhost:8080/#/inbox/123 -> http://localhost:8080/#/search //work fine
```

**Comment by confiks** [comment]
Try not adding a slash at the end of your paths. So `path="inbox"` instead of `path="inbox/"`.

**Comment by knowbody** [comment]
thanks for the answer @confiks.

As @confiks mentioned, if you include the forward slash in the end of the `path` then the URL will have to have `/` in the end to match, so it's better to not to include it.

The other thing is that React Router does not have named routes anymore. Please have a look at the [Upgrade Guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#route-config).

**Comment by Moussawi7** [comment]
Hello
In fact, I am facing exactly the same issue, 
so It is not working when routing from 
```
http://localhost:8888/#/archive/1 to http://localhost:8888/#/archive/2
```
Thank you.
```
    <Router>
        <Route path="/" component={Home} />
        <Route path="news" component={News} />
        <Route path="archive" >
        <IndexRoute component={archiveList} />
        <Route path=":archiveID" component={archiveDetails} />
        </Route>
        </Router>
```

**Comment by knowbody** [comment]
@Moussawi7 try making your routes look like:

```js
<Router>
  <Route path="/" component={Home} />
    <Route path="news" component={News} />
    <Route path="archive" >
      <IndexRoute component={archiveList} />
      <Route path=":archiveID" component={archiveDetails} />
    </Route>
  </Route>
</Router>
```

**Comment by Moussawi7** [comment]
Hi @knowbody ,
I made the route like you provided, but unfortunately, Home component is always called.
Thanks.

**Comment by knowbody** [comment]
oh I though that's what you wanted. Please have a look into the documentation. Everything is well explained in there.

**Comment by Moussawi7** [comment]
Thanks @knowbody , and sorry for bothering you.
My fault is that i thought that a new instance of ***archiveDetails*** will be created each time it match the route, but in fact it will update the ***props*** only.
So i inserted:
```javascript
   componentWillReceiveProps (nextProps){
          var archiveID=nextProps.params.archiveID;
         //Other instructions
}
```
which work great.

**Comment by knowbody** [comment]
@Moussawi7 well done! and you're not bothering :smile:
