### ISSUE TITLE
1.0.0-beta3 Best way add i18n on url ?

### ISSUE THREAD

**Issue by hank7444** [rackt/react-router#2159]
I would like to this:

```
www.xxx.com  -> redirect www.xxx.com/en
www.xxx.com/en/widgets
www.xxx.com/en/about
www.xxx.com/en/login
```

I want to only define :locale param once on Routers, 
because set on every Route is so stupid, so I tried:

```
<Route path="/:locale" component={App}/> // App only have header & footer
          <Route path="widgets" component={Widgets}/>
          <Route path="/about" component={About}/>
          <Route path="/login" component={Login}/>
<Route>
```

I get 2 problems:

1. how to redirect / to /:defaultLocate ?
2. how to let /:defaultLocate  render  Index Page(Home)?

**Comment by knowbody** [comment]
> how to redirect / to /:defaultLocate ?

You need to use [`Redirect`](https://github.com/rackt/react-router/blob/master/docs/API.md#redirect).

> how to let /:defaultLocate render Index Page(Home)?

Use [`IndexRoute`](https://github.com/rackt/react-router/blob/master/docs/API.md#indexroute). But then in your `Home` component check `this.props.location.pathname` if it doesn't come from default path the you `render()` function should return `null`, and if it comes from your default path then you just return whatever you want to show on `Home` component.

You routes should like:

```js
<Router history={createBrowserHistory()}>
  <Route>
    <Route path='/:locale' component={App}>
      <IndexRoute component={Home} />
      <Route path='widgets' component={Widgets} />
      <Route path='about' component={About} />
      <Route path='login' component={Login} />
    </Route>
    <Redirect from='*' to='/en' />
  </Route>
</Router>
```

**Comment by hank7444** [comment]
@knowbody I tried, it works fine, but it have a little problems, 

when I click <Link to="/"></Link>, it will return error:

```
Unhandled promise rejection Error: Invariant Violation: ReactDOM.render(): Invalid component element.(…)
```

I take look my router data, it redirect find, I don't know why it have this error.

```
location Object {pathname: "/", search: "", hash: "", state: null, action: "PUSH"…}
universalRouter.js:129 redirectLocation Object {pathname: "/en", search: "", hash: "", state: null, action: "REPLACE"…}
```

**Comment by knowbody** [comment]
this error says that whatever is in your `ReactDom.render()` is an invalid component. You must be doing something wrong somewhere else now
