### ISSUE TITLE
V1 on CDN?

### ISSUE THREAD

**Issue by jackfranklin** [rackt/react-router#2164]
Hey,

It would be really useful to have the latest version on CDNJS - currently there's only 0.13 up there. I usually build with jspm and hence use the module through npm, but I'm doing a workshop on React and would like to briefly touch upon React Router and doing this with a script tag to save having to get people to set up a build system would be really useful :)

Thank you all for the work on this library - it's become invaluable to me.

Jack

**Comment by jackfranklin** [comment]
Turns out my eyes don't work, it's absolutely on CDNJS :facepalm:

**Comment by knowbody** [comment]
yeah just for the reference: https://cdnjs.com/libraries/react-router/1.0.0-rc1

**Comment by mdocter** [comment]
The CDNJS mentions 'git autoupdate enabled', but currently the most recent version in the CDN is rc1, while the most recent GitHub release/tag is already rc3? 
I would like to use the new IndexRedirect module.

**Comment by knowbody** [comment]
@mdocter let's follow up in #2296
