### ISSUE TITLE
Typo (or misleading) in 1.0 upgrade guide

### ISSUE THREAD

**Issue by elverskog** [rackt/react-router#2166]
Looking at the latest examples in the repo it seems it is still "activeStyle=..." not "activeStyles=...". Right? I haven't upgraded yet.

See this line:
"In 0.13.x links added the "active" class by default which you could override with activeClassName, or provide activeStyles. Most links don't need this and the check is (currently) expensive."

On another note, it took me a good while to find any docs on how to set the active styling using inline styles (for the older version). With many people moving to the inline styles based solution, maybe this could be given more visibility in the docs?

Thanks for all the great work.

**Comment by knowbody** [comment]
thanks @elverskog I fixed the typo just now in https://github.com/rackt/react-router/commit/dd445858984831337530ca66b5ee53f22fff6e27

And I hear you about the examples. Would you mind writing the docs?

**Comment by elverskog** [comment]
I would love to contribute to the docs but I won't much have time till after the 20th (stiff deadline). That said, I'll take another look through the current docs and maybe just write up a piece for the activeClass/activeStyle feature. Does that make sense?

**Comment by knowbody** [comment]
sure, anything what would make it easier for others is great! let me know if you need any help. closing the issue for now
