### ISSUE TITLE
Pass in values to history only once

### ISSUE THREAD

**Issue by jjvattamattom** [rackt/react-router#2167]
I am making a workflow where I am creating a new user at `/users/new` and when it succeeds, I am taken to new user at `/users/17`. Here is the "redirect" code at `/users/new`:

```
processResponse: function(result) {
    if(!result.error) {
      this.props.history.replaceState({newUser:result.data}, '/users/' + result.data.id);
    }
```

at the handler for /users/:id:

```
if(this.props.location.state && this.props.location.state.newUser){
      this.setState({'data': this.props.location.state.newUser, newUserPassed: true});
```

Problem is, I want this transition to happen only **once**.  Ctrl+F5 at `/users/17` must not pass that browser state. Going back to `/users/17` must not pass that browser state. How do I get what I intended?

I would want something like code below, where messages is a stack:

```
processResponse: function(result) {
    if(!result.error) {
      messages.push(result.data);
      this.props.history.replaceState(null, '/users/' + result.data.id);
    }
```
and

```
if(messages.peek()){
      this.setState({'data': messages.pop(), newUserPassed: true});
```

**Comment by knowbody** [comment]
Could you make it more clear to me. I'm not sure if I understand it correctly.

1. You create the user at `user/new`
2. Redirecting to `user/SOME_USER_ID`

and what happens after that? you fetch some data? you don't want to refetch the data on the refresh or back button?

**Comment by jjvattamattom** [comment]
Creating the user returns data. I then pass that data when redirecting to users/ID to **save a roundtrip**. That data is used (I read that browser history persists state) for subsequent requests in same tab. I want subsequent requests to to not see/use that pushed data anymore, I want it to fetch data again.

Maybe its a bad usage of state?

**Comment by knowbody** [comment]
you could just fetch the data in the `componentDidMount()` inside the component which gets mounted when you hit `user/SOME_ID`. And to not to fetch data when you pass `props` (on the first render when you create a new user) just check if you have this `data` props present inside `componentDidMount()` if not then fetch the data

**Comment by jjvattamattom** [comment]
How do I pass in props when transitioning to a route?

Is there something like goto('/users/17',result.data)?

I was exploring the history project after reading the source of link class.

**Comment by knowbody** [comment]
@jjvattamattom just do it in `componentDidMount` fetch the data there. it does not make sense to pass data in the transition.

I thought you were passing the props from one component to the other as you would do in React. But again it does not make sense to do it in the transition.

**Comment by jjvattamattom** [comment]
In retrospect, I shouldnt be storing state in browser history as it persists a long time. So I used this. When `/users/17` is called normally, `User` class fetches data from API. When I successfully create a new user, I "cache" the value so that  the transition to `/users/17` is quick (I saved an API fetch).

New user class:
```
pushTransitionMessage({newUser:result.data});
this.props.history.replaceState(null, '/users/' + result.data.id);
```

Display user class:
```
let message = popTransitionMessage();
if(message && message.newUser){setState("new user added" message, new user)}
else this.getData()
```

```
pushTransitionMessage({hello:"world"});
popTransitionMessage(); //returns {hello:"world"}
popTransitionMessage(); // returns null
