### ISSUE TITLE
Redirect from "*" appears to not work.

### ISSUE THREAD

**Issue by jhicken** [rackt/react-router#2168]
With this configuration.
``` 
  <Route name="app" path="/">
    <Route path="company/" component={YUP}>
      <Route path="properties" component={YUP2}/>
    </Route>
    <Redirect from="*" to="/company/properties"/>
  </Route>
```

When I land here
`localhost:9002/#/?_k=wfo90m`

It should redirect to
`localhost:9002/#/company/properties?_k=wfo90m`

Alas It does not. 

I would normally just do a PR but I don't have time at the moment.

P.S. This worked fine 0.13 its only broken in 1.0.0

**Comment by knowbody** [comment]
1. we do not support named routes anymore
2. try something like this (without `/` on your parent route):

```js
  <Route>
    <Route path="company" component={YUP}>
      <Route path="properties" component={YUP2}/>
    </Route>
    <Redirect from="*" to="/company/properties"/>
  </Route>
```

**Comment by jhicken** [comment]
removing 
`path="/"`

from 
`<Route path="/">`

worked.

I still think its odd that what I have above worked fine in 0.13 but not in 1.0.0. I would think that should be documented in the migration docs.

**Comment by knowbody** [comment]
@jhicken we have documented how the API has changed., but we are not able to cover every single use case in the Upgrade Guide.

this is why we help here in the issues to solve them. although I'm pretty sure there are similar examples in the docs. But anyway I'm glad your problem is solved now :smiley:
