### ISSUE TITLE
A hook for Redirects

### ISSUE THREAD

**Issue by benjreinhart** [rackt/react-router#2171]
Full disclaimer: I just started learing React and the React Router release candidate for the first time so forgive me if I'm missing something obvious.

I am wondering if there is a reason why there aren't any hooks for `Redirect`s? I understand that `onEnter` and `onLeave` feel inaccurate in this situation but how about something like `onRedirect`?

The use case I currently have is logging a user out. I have a regular "Log Out" `Link` that links to `/logout`. I also have a redirect setup that redirects `/logout` to `/`. It would be very convenient to hook in here and kill the "session" for my current user.

```jsx
<Redirect from="/logout" to="/" onRedirect={ logout }>
```

Without this hook, it seems like the next best thing is to have a `LogOut` component which just uses the `componentDidMount` hook to kill the "session" and then manually redirect via `this.props.history.pushState`. While this isn't terrible, it seems like I'm just recreating `Redirect` with support for hook.

Admittedly, this hook seems useful in this situation but I'm not entirely sure how useful it will be in general.

**Comment by knowbody** [comment]
What you want to do is have the route like:

```js
<Route path='logout' onEnter={this.handleOnLogout} />
```

and then in the `handleOnLogout()` function you can manage clearing your session and after you are done you redirect to `/`, so your `handleOnLogout` is going to look like:

```js
handleOnLogout(nextState, replaceState) {
  console.log('Clear your session here...');
  replaceState({ nextPathname: nextState.location.pathname }, '/');
}
```

so I don't really see the point on creating something like `onRedirect`

**Comment by benjreinhart** [comment]
Ohh nice, that's better. Sorry for the noise.

Thanks!
