### ISSUE TITLE
[query] location.query in history.listen

### ISSUE THREAD

**Issue by aszwemin** [rackt/react-router#2174]
I seem to be having trouble accessing query in history.listen

```
~  25         history.listen((location) ->                                            
+  26             console.log 'Location object', location                             
+  27             console.log 'Object.keys(location)', Object.keys(location)          
+  28             console.log 'location.query', location.query                        
+  29             [section, id] = location.pathname[1..].split('/')                        
+  30             RouterActions.changeRoute(section, id, location.query)                    
+  31
+  32         )  
```

<img width="1055" alt="screen shot 2015-10-06 at 16 35 31" src="https://cloud.githubusercontent.com/assets/7859434/10313659/ae5d0e72-6c48-11e5-94c9-d7d58413125a.png">

The output of the above attached. Any ideas what's going on here? Query seems to be on the object, but can't access it.

**Comment by mjackson** [comment]
Hmm, bizarre. Mind showing me how you setup your `history` object? (BTW, we should probably be discussing this in https://github.com/rackt/history)

**Comment by aszwemin** [comment]
argh, that's where I was intending to put it, gonna move it there.

Create history by:

```
+   3 createBrowserHistory = require('history/lib/createBrowserHistory')              
    4                                                                                 
~   5 history = createBrowserHistory()
```

**Comment by aszwemin** [comment]
Moved to: https://github.com/rackt/history/issues/81
