### ISSUE TITLE
getQuery returns incorrect values

### ISSUE THREAD

**Issue by toddwildey** [rackt/react-router#2180]
I'm currently managing most of my state inside of query params in the URL.

 Whenever state change take place, I call
```
this.replaceWith(this.getPathname(), this.getParams(), newQuery);
```

Whenever navigation takes place, I call
```
this.transitionTo(childRoutePath, this.getParams(), this.getQuery());
```

If I change the pagination state (i.e., current page) on a given page, navigate to another page, and then return to the original page, the current page will ALWAYS be corrupted.  If I don't change the pagination state, and repeat the rest of the process, the current page still becomes corrupted.  The URL will reflect the correct state before any navigation takes place.

As soon as 
```
this.transitionTo(childRoutePath, this.getParams(), this.getQuery());
```
gets called, the URL becomes corrupted.

I'm using version 0.13 of react-router.  I've had issues getting the most recent version working, but I'll try again.

Any help would be appreciated, but I'm pretty sure this is a bug.

**Comment by mjackson** [comment]
I read through this but I'm having trouble following what you're saying. What do you mean by "the page is corrupted"? In any case, you'll probably have better luck getting help if you use 1.0.0-rc1.

**Comment by toddwildey** [comment]
I mean that, before I navigate to another path, the URL in the browser reflects that I'm looking at a given page of the current table.  That is,

```
...&type1Pag[currentPage]=1&...
```

When I navigate to another path, the query param becomes:

```
...&type1Pag[currentPage]=3&...
```

When I return to the original path (NOT by navigating "back" in the browser), the value stays in the query param:

```
...&type1Pag[currentPage]=3&...
```

This means that getQuery/getCurrencyQuery aren't actually retrieving the current query params represented in the URL - they're stale.

**Comment by mjackson** [comment]
If you don't use the browser's back button, how do you "navigate" back?

**Comment by toddwildey** [comment]
The root route has several tabs that allow you to navigate to other routes.  Each route generates new query params, if they don't exist in the URL already.  These params hold most of the state of the current page.

When I navigate to a different page, I don't lose the query params that were previously set.  Navigating back to pages I had visited previously, the query params provide persistent state.

**Comment by taion** [comment]
It's still not clear what you're saying. In your example in https://github.com/rackt/react-router/issues/2180#issuecomment-146380262, what do you expect to happen, and what do you actually observe?

**Comment by knowbody** [comment]
please provide more details on this issue and we will reopen

**Comment by toddwildey** [comment]
I expect

```
...&type1Pag[currentPage]=1&...
```

To stay the same value the entire time.  Before navigating to another tab, I can check the value of getQuery().  It will tell me that type1Pag.currentPage = 3, even though the URL says it's 1.

**Comment by taion** [comment]
Can we do anything about this though? If it's an actual v0.13.x bug with handling queries, I don't see a way for us to actually fix this anyway.

**Comment by knowbody** [comment]
you are right @taion. 

@toddwildey all I can suggest is to upgrade to React Router 1.0 then
