### ISSUE TITLE
Universally allow strings or objects for locations

### ISSUE THREAD

**Issue by timdorr** [rackt/react-router#2186]
As mentioned in #2177, I like to propose that any API that accepts a location object also accepts a string form of the location (and vice versa). 

The reasoning behind this is a matter of convenience, now that history has deprecated calling `createLocation` statically and requires a `history` instance to use the function. A history may not always be readily available, so it requires more boilerplate to get access to that API. In addition, there could be a performance impact from creating and dealing with a history object in cases that don't need it.

Furthermore, the concept of a location object is relatively opaquely defined. It's a POJO with an arbitrary set of fields that may change over time. So, spontaneous creation of location objects by the user are a bad pattern, as they will likely be an upgrade headache at some point in the future and are error-prone. URL strings on the other hand have a very concrete, standardized definition that `createLocation` will always support. They're the "future-proof" way of handling URLs.

And as some may have noticed, [`match` already does this](https://github.com/rackt/react-router/blob/fa364699463f5f337a517adf9e6f7db15e03613e/modules/match.js#L38-L39), so it's not unprecedented. In fact, it's a really nice addition :smile: I believe it's mainly just `matchRoutes` and `useRoutes.match` that need to support this, but I'm probably missing some other uses. It could also be applied to the `history` library, but only if that's a sensible change.

If others think this is a good idea, I can work up a PR to implement the changes. In a perfect world, it won't break any APIs, just augment them, so the impact to upgraders should be low.

**Comment by mjackson** [comment]
I think this is a great idea. We already have the concept of a [path](https://github.com/rackt/react-router/blob/master/docs/Glossary.md#path), which is the string you're describing here.

I think in addition we should allow a `location`-like object that we can coerce into a real `location` using `createLocation` if we need to. This is the same object I was trying to describe in #2177.

**Comment by ngokevin** [comment]
Not directly related to the issue, but for those who have followed the rabbit hole of issues looking for route reversal or named routes, check out https://github.com/ngokevin/react-router-reverse

**Comment by adamziel** [comment]
My try at this, drop-in support for named routes, almost no refactoring required in your software: https://github.com/adamziel/react-router-named-routes

**Comment by taion** [comment]
The problem in general with these implementations, BTW, is that they're incompatible with the async routes stuff, which is sort of how we got here in the first place.

**Comment by adamziel** [comment]
Sure but it's perfect if you just want your app working and don't need the fancy stuff

**Comment by timdorr** [comment]
Hey guys, this is getting *way* off topic. Let's keep this to how we handle location objects and strings via our APIs.

**Comment by taion** [comment]
I think this can be the genesis of a pretty significant API cleanup.

I'd like to push the "strings or objects" concept one level higher into `history`.

Ideally, `history.push` and `history.replace` should support either strings or objects, and we would move to those as the preferred APIs over `pushState` and `replaceState`.

We could then modify `<Link>` to accept either a string or an object for `props.to`, and forward that directly to `history.push` (and something analogous for active state).

This could then allow us to just set up named routes as a history enhancer, e.g.:

```js
const history = useNamedRoutes(createHistory({routes}))
```

This could work by building the route map, then wrapping the underlying `push`, `replace`, and `isActive` accordingly.

**Comment by timdorr** [comment]
This is done :smile:
