### ISSUE TITLE
basic example doesn't work

### ISSUE THREAD

**Issue by gfarrell** [rackt/react-router#2187]
I used to use configure my routes as follows:

```jsx
    let routes = (
        <Route path="/" name="app" handler={AppComponent}>
            <Redirect from="/" to="/streams" />
            <Route path="/streams" name="streams_index" handler={StreamsIndex} />
        </Route>
    );

    Router.run(routes, function (Handler) {
        React.render(<Handler/>, container);
    });
```

(this works)

From the [basic example](https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md), I tried this in a new project:

```jsx
    React.render((
        <Router>
            <Route path="/" component={ AppComponent }>
                <IndexRoute component={ SomeIndexComponent } />
            </Route>
        </Router>
    ), container);
```

but I keep getting errors in the console (and nothing works):

```
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
```

and

```
ReactDefaultInjection.js:53 Uncaught TypeError: type.toUpperCase is not a functionautoGenerateWrapperClass @ ReactDefaultInjection.js:53getComponentClassForElement @ ReactNativeComponent.js:59validatePropTypes @ ReactElementValidator.js:361ReactElementValidator.createElement @ ReactElementValidator.js:408routes @ routes.js:16main @ main.js:6558../routes @ main.js:9s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
```

**Comment by mjackson** [comment]
Somewhere you're creating a React component from `undefined`. It's a common error when you forget to `require` something. In your case, make sure that `Router`, `Route`, `IndexRoute`, `AppComponent`, and `SomeIndexComponent` are all defined when you use them.

**Comment by gfarrell** [comment]
I'm not sure that's the case. I tried leaving literally all my code untouched, and transforming:

```jsx
let routes = (
    <Route path="/" name="app" handler={AppComponent}>
        <Redirect from="/" to="/streams" />
        <Route path="/streams" name="streams_index" handler={StreamsIndex} />
        <Route path="/register" name="register_sensor" handler={RegisterSensor} />
    </Route>
);

Router.run(routes, function (Handler) {
    React.render(<Handler/>, container);
});
```
(which works) to 
```jsx
let routes = (
    <Route path="/" name="app" handler={AppComponent}>
        <Redirect from="/" to="/streams" />
        <Route path="/streams" name="streams_index" handler={StreamsIndex} />
        <Route path="/register" name="register_sensor" handler={RegisterSensor} />
    </Route>
);

React.render((<Router>{ routes }</Router>), container);
```
For which I get: `ReactDefaultInjection.js:53 Uncaught TypeError: type.toUpperCase is not a function`.

If I then change all the `handler=` to `component=`, my first (otherwise functioning) example doesn't work, and neither does the second, giving me the same error as above in `ReactDefaultInjection.js:53`.

This is because in `autoGenerateWrapperClass(type)`, `type` is being passed an `Object`. My guess from its properties is that this object is a `Router` (being passed to React via `<Router>`.

My import statement looks like this:

```javascript
import Router, { Route, Redirect } from "react-router";
```
I tried
```javascript
import { Router, Route, Redirect } from "react-router";
```
as in the example but then `Router === undefined`.

**Comment by halfcrazy** [comment]
@gfarrell I'm afraid i got same error
while `import { Router } from "react-router"` as the Router resolved as undefined
and `import Router from "react-router"` works

**Comment by zhangmengxue** [comment]
It doesn't work for me too.
I'm using 
- react@0.13.3
- react-router@0.13.4
too....

I've tried to make sure the components are all defined when I use.
And I still got the problem,even I tried this: 

```jacascript```
const Hello = React.createClass({
	render() {
		return (
			<div>Hello World!</div>
		);
	}
});

React.render((
	<Router>
		<Route path="/" component={Hello}>
		</Route>
	</Router>
), document.getElementById('root'));
```

same problem...

**Comment by taion** [comment]
The examples on `master` are all for the current series of 1.0.0 pre-releases. If you are still using React Router v0.13.x, please consult the appropriate examples there.

If you have a new project, though, I strongly recommend using the current v1.0.0-rc3. Note, however, that because it is marked as a pre-release, you will have to install it with `npm i react-router@latest`, as omitting the explicit tag will give you v0.13.4.

**Comment by zhangmengxue** [comment]
It works for me ,  Thanks very much!

**Comment by uptownhr** [comment]
i don't think the examples on the home page should reflect something that has not been released yet. That is just my opinion though.

**Comment by taion** [comment]
They are effectively released. If you have a new project, you should use the most recent 1.0.0 RC.

**Comment by tdeheurles** [comment]
hi, so what should we use ?
I'm trying to start the exemple on the main page. I get the App part but no link seems working.

I go with:
- react 0.14
- react-router 1.0.0-rc3

Should we still use react 0.13 ?

**Comment by knowbody** [comment]
@tdeheurles what does it mean is not working? what is your console saying?

**Comment by tdeheurles** [comment]
yes, sorry. wanted to know if reaact 0.14 is the version to use.

here is my app :

```
import React                   from 'react';
import ReactDOM                from 'react-dom';
import { Router, Route, Link } from 'react-router';

const App = React.createClass({
    render() {
        return (
            <div>
                <h1>App</h1>
                <p><Link to="/about">About</Link></p>
                <p><Link to="/users">Users</Link></p>
            </div>
        )
    }
});
const About = React.createClass({
    render() {
        return (
            <h1>About</h1>
        )
    }
});

const Users = React.createClass({
    render() {
        return (
            <div>
                <h1>Users</h1>
                <div className="master">
                    <ul>
                        {/* use Link to route around the app */}
                        {this.state.users.map(user => (
                            <li key={user.id}><Link to={`/user/${user.id}`}>{user.name}</Link></li>
                        ))}
                    </ul>
                </div>
                <div className="detail">
                    {this.props.children}
                </div>
            </div>
        )
    }
});

const User = React.createClass({
    componentDidMount() {
        this.setState({
            // route components are rendered with useful information, like URL params
            user: findUserById(this.props.params.userId)
        })
    },

    render() {
        return (
            <div>
                <h2>{this.state.user.name}</h2>
                {/* etc. */}
            </div>
        )
    }
});

// Declarative route configuration (could also load this config lazily
// instead, all you really need is a single root route, you don't need to
// colocate the entire config).
ReactDOM.render((
    <Router>
        <Route path="/" component={App}>
            <Route path="about" component={About}/>
            <Route path="users" component={Users}>
                <Route path="/user/:userId" component={User}/>
            </Route>
        </Route>
    </Router>
), document.getElementById('root'));
```

It's a copy/paste of the example updated for `React@0.14`

The app launch but the link just do nothing (no error in console)

**Comment by knowbody** [comment]
@tdeheurles you are missing `{this.props.children}` in the `App` component.

**Comment by tdeheurles** [comment]
Unable to make the example working. After adding `{this.props.children}`, it complains now about the `this.props.users` undefined in the `users` component (console error).

I don't understand from where it could find it as now props seems to be given.
Is there code that should be `implicit` ? ...

In the other hand, I've tried `{this.props.children}` on my project and the router is now working.

Thank you for support ^^

**Comment by knowbody** [comment]
@tdeheurles You're welcome! the reason you get the error is because your `Users` component has no state. And you are trying to do: `this.state.users.map....`

should work when you add:

```js
getInitialState() {
  return {
    users: [
      { id: 4, name: 'Matt' }
    ]
  }
}
```

to your `Users` component.

Anyway please have a look into the [documentation](https://github.com/rackt/react-router/tree/master/docs), everything is explained there. Also check out the [example apps](https://github.com/rackt/react-router/tree/master/examples).

**Comment by janzheng** [comment]
It might also because you're importing something as a default / not as default. I ran into this earlier and didn't realize I accidentally wrapped my imported object with { } which made it go crazy
