### ISSUE TITLE
Allow to move to React 0.14.x - would it work?

### ISSUE THREAD

**Issue by pjnovas** [rackt/react-router#2194]
Is there a reason why [package.json has a strong dependency to react `0.13.x`](https://github.com/rackt/react-router/blob/master/package.json#L56)?, my problem right now is react `0.14.0` just came out and I can't use it because it does not meet the dependency with react-router. 

Could it be `"react": "^0.13.x"` instead of `"react": "0.13.x"` ? (I'm talking with short knowledge, maybe the new react wont work with the current version of react-router)

Thanks for this awesome lib BTW! :+1:

**Comment by RinatMullayanov** [comment]
@pjnovas +1

**Comment by RinatMullayanov** [comment]
I try to use reac-router 0.13.4 with react 0.14 get the error in browserify:
```
Error: Can not find module 'react / lib / invariant' from'C:\Users\MullayanovRR\Documents\Projects\MyDev\JS\Mvc4ReactGulp\Mvc4ReactGulp\node_modules\react-router\lib'
```

**Comment by franckmaurin** [comment]
same issue here.

**Comment by almasakchabayev** [comment]
+1

**Comment by knowbody** [comment]
We thought about it already and it's coming soon :smile: 
https://github.com/rackt/react-router/pull/2190

**Comment by taion** [comment]
@pjnovas That's a dev dependency; the actual package itself has no React v0.13.x dependency, and recent 1.0.0 pre-releases work with React v0.14 just fine.

@knowbody I think some of the others in this thread are asking about React v0.14 support for the v0.13.x line.

**Comment by pjnovas** [comment]
@taion yeah, I know it's a dev dependency but I think the problem is with browserify cause it tries to install them too, I think it doesn't goes with a `npm install --production`, so dev dependencies count when you require them from brwoserify.

Am I right with this?

**Comment by taion** [comment]
If you just do `npm install history`, it will not pick up dev dependencies.

**Comment by eriknyk** [comment]
would be great this can be solved once react 0.14.0 is out.

```
% npm install react-router --save                                                        
npm WARN peerDependencies The peer dependency react@0.13.x included from react-router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by pjnovas** [comment]
@taion the error shown by @eriknyk is exactly what happens to me. What I'm thinking is NPM v3 has that requirement that maybe NPM v1 or 2 does not.

**Comment by taion** [comment]
If you just do `npm install react-router`, you install the latest non-pre-release version, in this case v0.13.4. If you want one of the v1.0.0 pre-releases, you'll have to `npm i react-router@latest`.

**Comment by pjnovas** [comment]
oh cool, so this is already fixed for version v1.0.0-rc, it will be working fine with react 0.14 when it gets released then, and you were right it has nothing to do with devDependencies. Thanks!.
I don't know if this issue should be closed now or when the release comes out. I leave it to you guys :+1:

**Comment by taion** [comment]
I think there remains a question as to whether there will be a React v0.14 compatible release on the current stable line. I don't know the answer to that question.

**Comment by knowbody** [comment]
@taion thanks for the clarification, not sure if we should do that for 0.13.x as 1.0 is the recent stable version, and that's the one we should be working on. Why not just upgrade to 1.0?

**Comment by taion** [comment]
I don't know. I upgraded to the 1.0.0 pre-releases a while ago.

I'd guess that some users currently still on v0.13.x will want to upgrade from React v0.13 to React v0.14 without having to upgrade React Router just to do that. It depends on how accommodating we want to be of that.

You'd be surprised (or not). I've literally had people on 5+ month old releases of React-Bootstrap asking me if they'd be able to just upgrade React from v0.13 to v0.14 without upgrading React-Bootstrap.

**Comment by mjackson** [comment]
I really want 0.13.4 to be the last release in the 0.13.x branch. We cannot afford to maintain two APIs. People who want to use 0.13.4 can keep using React 0.13. Yes, I know it sucks, and I'm sure I'll get a lot of people telling me what a terrible person I am for doing this. But we have to move forward.

We'll do a much better job of managing upgrade pain in the future. That's part of the reason I'm pushing so hard for 1.0 right now–so we can commit to an API that we will maintain for a while. But we intentionally made no promises with the 0.x releases because we needed some time to figure stuff out.

We're already managing backwards compat in a much more friendly manner on the [history](https://github.com/rackt/history) project, because we've already hit 1.0 there.

**Comment by taion** [comment]
FWIW I'm totally fine with that. I think upgrading just React while keeping all your dependencies top of React at ancient versions is inane.
