### ISSUE TITLE
contextTypes location no longer works

### ISSUE THREAD

**Issue by esseb** [rackt/react-router#2196]
````
contextTypes: {
  location: React.PropTypes.object
},
```
as described on https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md no longer seems to work in v1.0.0-rc2. `this.context.location` is `undefined`

I'm currently upgrading to react 0.14, so it's possible something else has triggered this issue, I haven't made a reduced testcase yet.

**Comment by esseb** [comment]
Looks like I hit the parent/owner context change in 0.14. Not a react-router bug.

**Comment by framerate** [comment]
@esseb could you elaborate more for the next person going through the upgrade process?

**Comment by esseb** [comment]
I hit the problem when I was using https://github.com/davidtheclark/react-aria-modal and passed a component using ´contextTypes: { location: React.PropTypes.object }´ to show in the dialog.

I haven't had time to investigate the issue enough to report a bug in ´react-aria-modal´ yet, but I suspect the way ´react-aria-modal´ uses ´react-displace´ to render the dialog's content elsewhere in the DOM might be the issue. I worked around the issue in my project by using another modal component.

**Comment by taion** [comment]
@esseb 

You need to use a pattern like https://github.com/react-bootstrap/react-overlays/blob/v0.5.0/src/Portal.js#L66-L68 to properly propagate context into the modal.

I would recommend switching to an actively maintained library like react-overlays or React-Bootstrap for your modal needs.

**Comment by esseb** [comment]
@taion thanks, that sounds useful.

I used `react-aria-modal` because I needed an accessible dialog. I ended up rolling my own simple component instead. I'll check out https://github.com/react-bootstrap/react-overlays next time I need one, although I can't see that it has any aria attributes even though it claims to have them.
