### ISSUE TITLE
Transition example in rc2 is broken

### ISSUE THREAD

**Issue by hackhat** [rackt/react-router#2197]
If you go to http://localhost:8080/transitions/form and click on the link form you will get this error:

    Uncaught TypeError: Cannot read property 'search' of undefined

Line computeChangedRoutes.js:15:

    function routeQueryChanged(prevState, nextState) {
      return prevState.location.search !== nextState.location.search
   }

**Comment by heikkilamarko** [comment]
I started to get this same error after updating my app to use react-router 1.0.0-rc2. React version is 0.14.0.

**Comment by mjackson** [comment]
Thanks for bringing this to our attention, @hackhat :) I'm seeing the same thing in rc3. Looking into it now.

**Comment by JeanCarriere** [comment]
Will there be a release with this fix soon?
