### ISSUE TITLE
Alternatives to Router.run for server rendering with Iso module

### ISSUE THREAD

**Issue by joneslee85** [rackt/react-router#2198]
I happen to know that `Router.run` is gone and now things must be done at lower level than Router API.

I am not a guru here, so I am wondering how would this code at https://github.com/goatslacker/iso/blob/master/examples/react-router-flux/server.js#L50-L68 would get ported?

Many thanks

**Comment by knowbody** [comment]
please check [Server Rendering](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md)

**Comment by joneslee85** [comment]
@knowbody many thanks, worked it out :) :+1:
