### ISSUE TITLE
[need-help] Different React Routers on a single app

### ISSUE THREAD

**Issue by ciaoben** [rackt/react-router#2200]
I have a multirole react app:

when a user login in, I create a router, run it, and the first component that is rendered receive the role of the user logged in from the server. I want to have different routers for every role:

e.g.

for the same instance of house (with id =12) the routes that I want are:

if the user is logged as admin: `/users/123/land/3/house/12`
 if the user is logged as host: `/house`

How can achieve this?

**Comment by timdorr** [comment]
```js
function createRoutes(user) {
  if (user.isHost())
    return createHostRoutes()
  if (user.isAdmin())
    return createAdminRoutes()
}

const router = <Router routes={createRoutes(user)} />
```

**Comment by knowbody** [comment]
thanks for the answer @timdorr
