### ISSUE TITLE
Docs for onEnter are wrong in rc1

### ISSUE THREAD

**Issue by hackhat** [rackt/react-router#2201]
Those are the args I get on the onEnter `function (nextState, replaceState, cb)`

**Comment by knowbody** [comment]
the docs are correct https://github.com/rackt/react-router/blob/e738c88a05a537d4b93b5946097eb2629598fa74/modules/Redirect.js#L24

**Comment by hackhat** [comment]
Then why I got the a function as 3th argument?

**Comment by hackhat** [comment]
In TransitionUtils @ 48 `hooks[index](nextState, replaceState, function (error) {`:

  loopAsync(hooks.length, function (index, next, done) {
    hooks[index](nextState, replaceState, function (error) {
      if (error || redirectInfo) {
        done(error, redirectInfo); // No need to continue.
      } else {
        next();
      }
    });
  }, callback);

And then in the same file @ 5 `hook.apply(route, arguments);`:

function createEnterHook(hook, route) {
  return function (a, b, callback) {
    hook.apply(route, arguments);

    if (hook.length < 3) {
      // Assume hook executes synchronously and
      // automatically call the callback.
      callback();
    }
  };
}

**Comment by quicksnap** [comment]
I'm also seeing this, over at https://github.com/erikras/react-redux-universal-hot-example/pull/320

It works as expected, blocking until the callback is called, which is _really helpful_! For server rendering, it'd be very helpful to fetch data async and block before potentially redirecting, from within `onEnter`.

**Comment by hackhat** [comment]
Why is this closed anyway?

**Comment by taion** [comment]
How does this help you for server rendering? `ReactDOM.render` and friends are synchronous - if you have an async `onEnter`, you just end up with a `noscript` or whatever.

**Comment by taion** [comment]
Oh, wait, I take that back.

Is that part of the hook intentionally exposed for `onEnter` though? It's not shown in the examples.

**Comment by quicksnap** [comment]
Not sure if it's intentional, but it is very useful: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/routes.js#L16-L32

**Comment by taion** [comment]
@quicksnap 

This is actually covered in the API docs: https://github.com/rackt/react-router/blob/b06d1db7864ba16e36dc7bdae40e18ed86d23907/docs/Glossary.md#enterhook

I'm okay with leaving it there for now, because it's somewhat advanced.

If you'd like to contribute e.g. a simple example that shows the use of an async `onEnter` function, though, I'd be positively inclined toward merging it.

**Comment by quicksnap** [comment]
I'm on the fence, since the callback will cause a UI-blocking transition; that sort of behavior is likely best tucked away for advanced uses only.

**Comment by quicksnap** [comment]
As long as it's documented somewhere, I'm happy. I wasn't aware it was in the glossary!
