### ISSUE TITLE
server rendiring redirect outside the routes callbacks examples

### ISSUE THREAD

**Issue by jurgob** [rackt/react-router#2205]
I would like to have an example of a working server side rendiering redirect.

I've tried to do an example by myself, but I'm stuck (I've open a stackoverflow question here: http://stackoverflow.com/questions/32988299/react-router-1rc1-server-side-redirect)

it refers to an old version of my code, right now I did an horrible workaround like saving the redirect callback in an object in order use it elsewhere.

https://github.com/jurgob/iso-login/blob/52289b0399f5142aa5d6a4ca51140df2062c97a1/src/shared/routes.js

```

function historySetup(nextState, replaceState) {

  historyObj.replaceState = replaceState;//TODO: this is the ugliest solution ever

}

```

**Comment by mrtnbroder** [comment]
Take a look at my example here: #2215, looks like you need some dynamic behaviour to check if the user requires authentication.
You'd do it within the `onEnter` callback on the server (I guess, maybe @mjackson has another opinion on this).

```javascript
<Route onEnter={authenticate} component={require('./Auth')}/>
```

**Comment by mrtnbroder** [comment]
Sorry, maybe I should have read your stackoverflow question a bit more carefully. Why do you want to do it on the component? From the looks if it, this should be all you need.

**Comment by knowbody** [comment]
What's your question/issue?

From the SO it seems like you got it working. Either use `onEnter` hook or if you want to do it "inside component" then use `this.history.pushState(null, '/login')`.
