### ISSUE TITLE
ReactDefaultInjection.js:53 Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by zhangmengxue** [rackt/react-router#2207]
I was using react-router and got a problem like above..
this is my code:
```javascript```
import React from 'react';
import Layout from './layout/layout';

// module
import Module from './pages/module/module';
import ModuleList from './pages/module/list/list';
import ModuleCreate from './pages/module/create/create';
import ModuleEdit from './pages/module/edit/edit';
import ModulePreview from './pages/module/preview/preview';

// login
import Login from './pages/login/login';

// router
import { Router, Route } from 'react-router';

// import admin-lte
import './common/admin-lte/dist/css/AdminLTE.css';

React.render((
	<Router>
		<Route path="/" component={Layout}>
			<Route path="login" component={Login} />
			<Route path="module" component={Module}>
				<Route path="list" component={ModuleList} />
				<Route path="create" component={ModuleCreate} />
				<Route path="edit/:name" component={ModuleEdit} />
				<Route path="preview/:name" component={ModulePreview} />
			</Route>
		</Route>
	</Router>
), document.getElementById('root'));
```
and then I open a new page :  http://127.0.0.1:2828/webpack-dev-server/ I got the problem.

when I change the code like this:

```javascript```
import React from 'react';
import Layout from './layout/layout';
import Router from 'react-router';

// module
import Module from './pages/module/module';
import ModuleList from './pages/module/list/list';
import ModuleCreate from './pages/module/create/create';
import ModuleEdit from './pages/module/edit/edit';
import ModulePreview from './pages/module/preview/preview';

// login
import Login from './pages/login/login';

// router
import { DefaultRoute,RouteHandler, Route } from 'react-router';


// import admin-lte
import './common/admin-lte/dist/css/AdminLTE.css';

const Test = React.createClass({
	render(){
		return (
			<div>Hello World!</div>
		);
	}
});
let routes = (
		<Route path="/" component={Test}>
			<Route path="login" component={Login} />
			<Route path="module" component={Module}>
				<Route path="list" component={ModuleList} />
				<Route path="create" component={ModuleCreate} />
				<Route path="edit/:name" component={ModuleEdit} />
				<Route path="preview/:name" component={ModulePreview} />
			</Route>
		</Route>
);

Router.run(routes,function (Handler){
	React.render(<Handler />,document.getElementById('root'));
});
```
There wasn't any mistake,but I got nothing in my page, even Hello world! it just blank.
I don't know what's going wrong...

**Comment by mjackson** [comment]
Please see my answer here: https://github.com/rackt/react-router/issues/2187#issuecomment-146279363

**Comment by halfcrazy** [comment]
same issue
