### ISSUE TITLE
Upgrade to react-router rc2 problems

### ISSUE THREAD

**Issue by justjacksonn** [rackt/react-router#2208]
Hey all, I upgraded npm today in my project and it is now using react 0.14.. been using rc1 prior. Also was using react-router rc1. This update pushed me to react-router rc2. Now, when I start my npm, I get an issue with react-router cant find module qs as well as module deep-equal.

I tried to be clever.. so I went in to the node_modules/react-router and tried running npm install. When I do that I get the following error:

SyntaxError: modules/IndexRedirect.js: Unexpected token (25:19)
  23 |   }
  24 | 
> 25 |   static propTypes = {
     |                    ^
  26 |     to: string.isRequired,
  27 |     query: object,
  28 |     state: object,

Not sure if what I did was incorrect or not..was hoping by manually npm installing the two modules would magically appear and not clear why they are not there in the first place. I see them in package.json.

**Comment by woodb** [comment]
:+1: I'm seeing the same issue here...

**Comment by mjackson** [comment]
This is a dup of #2195

**Comment by justjacksonn** [comment]
mjackson: Sorry.. did a quick read of the issues and didnt notice it. Thanks for getting on this and looking forward to the rc3/fix.
