### ISSUE TITLE
issue with dynamic route 

### ISSUE THREAD

**Issue by bellicose100xp** [rackt/react-router#2213]
dynamic routes, ones with /:customerId don't work when the route is typed directly  (they work when i click link within app).. here's the github repo https://github.com/bellicose100xp/react-input , I hope it's the gulp-connect issue again, but i cannot find anything, is there's something i'm missing. 

    React.render((
        <Router history={history}>
            <Route path="/" component={App}>
                <IndexRoute component={Homepage} />
                <Route path="/customer/:customerId" component={Customer} />
                <Route path="test" component={Test}/>
            </Route>
        </Router>
    
The issue seems to be that when I type the dynamic routes directly, the *css* & *script* link in index.html see that dynamic route as a baseline so instead of looking for `css/bundle.css` it's looks for `customer/:customerId/css/bundle.css` same for `bundle.js` file.

**Comment by edvinerikson** [comment]
You need to add a `/` in front of every static resource.
In `index.html` change `<link rel="stylesheet" href="css/bundle.css">` to `<link rel="stylesheet" href="/css/bundle.css">` and `<script src="scripts/bundle.js"></script>` to `<script src="/scripts/bundle.js"></script>`.

**Comment by mjackson** [comment]
Thanks for the help, @edvinerikson.

**Comment by bellicose100xp** [comment]
thank you, that resolves the issue, interestingly I had tried `./` but that didn't work.
