### ISSUE TITLE
Fix <Link hash>

### ISSUE THREAD

**Issue by aszwemin** [rackt/react-router#2216]
I have two links, one created with `<Link to='/faq' hash='#whatis'>` and the other one created with `<a href='/faq#whereq'>` that look as following when inspecting element on rendered document:

```
<a class="" href="/faq#whatis" data-reactid=".0.2.0.0.0.1.0">...</a>
<a href="/faq#whereq" data-reactid=".0.2.0.0.0.2.0">...</a>
```

When I click on the second one, hash is populated in the location object and I'm being taken to the fragment. When I click on the first one, I'm being taken to `\faq`, hash is not populated in the location object and I'm not being taken to the fragment. Any idea why is that?

**Comment by aszwemin** [comment]
Think I found the reason. 

`if (allowTransition) this.context.history.pushState(this.props.state, this.props.to, this.props.query);`

allowTransition is true in my case so the pushState is called, but it doesn't take hash under consideration.

**Comment by taion** [comment]
It's true in both cases, though. Are you sure you're on RC3?

**Comment by aszwemin** [comment]
Yes, using RC3. Preventing default and doing pushState(this.props.state, this.props.to, this.props.query) seems to make Link not working with hashes.

**Comment by mjackson** [comment]
Good catch, @aszwemin. We really should have a test around this. Are you up for a PR? You can use the existing tests around `<Link>`'s `onClick` behavior as a starting point.

**Comment by timdorr** [comment]
Created a failing test here: https://github.com/rackt/react-router/compare/master...timdorr:test-link-hash

I'll get a fix together shortly.

**Comment by aszwemin** [comment]
:+1:
