### ISSUE TITLE
Make isActive work as expected with pathname and query arguments

### ISSUE THREAD

**Issue by ropez** [rackt/react-router#2218]
Using react-router-bootstrap, and trying to make a generic pagination component, that can generate pagination links without knowing the current path. When clicking this link, I want the URL query to be changed to "?page=2", without changing the rest of the URL:

```
  <NavItemLink to={this.context.router.getCurrentPathname()} query={{page: 2}}>Page 2</NavItemLink>
```

This generates the correct links, but the current page link isn't tagged as 'active'. It turns out that router.isActive doesn't work as I expected when the first argument is the pathname, and the query is given as a third argument. More precisely, it doesn't handle arguments in the same way as router.makeHref.

Given a route for the path `/categories/:category`, and the current URL is `/categories/foo`, I expected all these to be true:

```javascript
Router.isActive('categories', {category: 'foo'}, {page: 1})  // true
Router.isActive('/categories/foo?page=1')  // true
Router.isActive('/categories/foo', {}, {page: 1})  // false
```

However:
```javascript
Router.isActive(Router.makeHref('/categories/foo', {}, {page: 1}))  // true
```

Since the _name_ of the current route isn't easily available, this makes it hard to come up with the correct `<Link>` params.

```
react-router@0.13.4
react-router-bootstrap@0.18.1
```

**Comment by timdorr** [comment]
Most of the development effort over here is on react-router 1.0.0. If you bump your `react-router-bootstrap` to version 0.19.0 or higher, you'll be updated to react-router@1.0.0-rc1. We've proceeded a little farther to rc3, so if @taion has some time to update it to that version as well, this should mostly go away. There are a lot of API changes, but you shouldn't run into this issue.

**Comment by taion** [comment]
Right, the v0.18.x releases of React-Router-Bootstrap are unsupported. v0.19.0 and v0.19.1 both support almost everything in RC3 except for the new `hash` prop.

I think this will largely be superseded by https://github.com/rackt/react-router/issues/2186. For comparison, IIRC, `angular-ui-router` lets you build links that only override e.g. query parameters without otherwise changing the route you're on.

**Comment by taion** [comment]
I'm going to close this because there's nothing actionable here. All development like this now is going to be on the 1.x line rather than the 0.13.x line, so there's no way to address this.
