### ISSUE TITLE
Get rid of return false behavior on Link onClick?

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2219]
Per https://facebook.github.io/react/docs/events.html

>As of v0.14, returning `false` from an event handler will no longer stop event propagation. Instead, `e.stopPropagation()` or `e.preventDefault()` should be triggered manually, as appropriate.

For consistency we should consider dropping `clickResult === false` here: https://github.com/rackt/react-router/blob/v1.0.0-rc3/modules/Link.js#L71.

**Comment by timdorr** [comment]
It should probably be this instead:
```js
if (event. isPropagationStopped() === true || event.defaultPrevented === true)
```
And should be noted in the upgrade guide as a breaking change.

**Comment by taion** [comment]
`#stopPropagation()` on `<a onClick>` doesn't prevent navigation, so I don't think it should prevent navigation here.

**Comment by timdorr** [comment]
That is true. Stopping propagation only applies to elements above this one in the DOM tree, so it doesn't really apply here.

I'm actually not sure why React implemented this change, since [it goes against the spec](http://www.w3.org/TR/html5/webappapis.html#the-event-handler-processing-algorithm), other than providing a better API for stopping events (I remember cringing at dealing with `return false` back in the jQuery days). Regardless, if implemented, it should be noted in the upgrade documentation.

**Comment by taion** [comment]
@timdorr Implemented what change? They took out the special-casing of `false` returns from event handlers, which seems like a straightforward win to me.

**Comment by timdorr** [comment]
Removing the `return false` handling from React's synthetic event system. It's supposed to be that way according to the spec (except for mouseover and beforeunload):
> **Otherwise**
> If return value is a WebIDL boolean false value, then cancel the event.

**Comment by taion** [comment]
Oh. Huh. Fair enough.

**Comment by timdorr** [comment]
Yeah, it's goofy.

Nonetheless, React is king and we should follow its lead to maintain consistency. I can put together a PR and include a note in the upgrade guide.

**Comment by mjackson** [comment]
@timdorr :+1:

**Comment by taion** [comment]
Actually I can just do this, it's pretty straightforward.

**Comment by timdorr** [comment]
Go for it!

**Comment by gaearon** [comment]
>Removing the return false handling from React's synthetic event system. It's supposed to be that way according to the spec (except for mouseover and beforeunload):

I don't think React intended to match DOM event API in all aspects. There are plans to use event handler return values for state updates, so the DOM behavior is much less useful here to React.
