### ISSUE TITLE
postinstall script fails 

### ISSUE THREAD

**Issue by aphillipo** [rackt/react-router#2221]
Sorry to be so fast off the bat on this one!  The commit you just made to fix the windows postinstall script does not work on my mac.

Here is an error message:

    > react-router@1.0.0-rc3 postinstall /Users/aphillipo/Sites/work/dave/static/react/node_modules/react-router
    > node scripts/postinstall.js

    module.js:338
        throw err;
        ^

    Error: Cannot find module '/Users/aphillipo/Sites/work/dave/static/react/node_modules/react-router/scripts/postinstall.js'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Function.Module.runMain (module.js:475:10)
        at startup (node.js:117:18)
        at node.js:951:3
    npm ERR! Darwin 15.0.0
    npm ERR! argv "/Users/aphillipo/.nvm/versions/node/v4.1.1/bin/node" "/Users/aphillipo/.nvm/versions/node/v4.1.1/bin/npm" "install" "--save" "git+https://git@github.com/rackt/react-router.git"
    npm ERR! node v4.1.1
    npm ERR! npm  v2.14.4
    npm ERR! code ELIFECYCLE

    npm ERR! react-router@1.0.0-rc3 postinstall: `node scripts/postinstall.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the react-router@1.0.0-rc3 postinstall script 'node scripts/postinstall.js'.
    npm ERR! This is most likely a problem with the react-router package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/postinstall.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls react-router
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/aphillipo/Sites/work/dave/static/react/npm-debug.log

**Comment by mjackson** [comment]
Sounds like `scripts/postinstall.js` isn't there? What do you get when you `npm run postinstall`? Also, what does `ls -al scripts` give you?

**Comment by taion** [comment]
It's because `scripts` is in `.npmignore`. Probably make an `npm-scripts`? Except I'm trying that and Babel is choking on the stage 0 stuff for some reason.

**Comment by mjackson** [comment]
Oh, right. Let's just remove that line.

**Comment by taion** [comment]
It's easy enough to just move the NPM-required hook scripts and not ship the build stuff though. I'm trying this, though, and the actual `npm run build` is failing for some reason that I can't figure out.

**Comment by mjackson** [comment]
@taion If you can figure it out, feel free to push something else. I'm not too concerned about it though.

**Comment by taion** [comment]
@mjackson 

It's the second weirdest thing I've seen, after that NPM packing bug. For whatever reason, `babel` running for an installed dependency seems to completely ignore the `.babelrc` for that dependency (and any command line options you specify), and instead goes straight to the `.babelrc` of the package for which you're installing the dependency.

In other words, the auto-build on `postinstall` only works on projects that specify stage 0 in their `.babelrc` configs. ¯\_(ツ)_/¯

**Comment by hoskeri** [comment]
I had the same issue, deleting the cached build from .npm seems to make it obey my babelrc again.
