### ISSUE TITLE
Relative replaceState, pushState

### ISSUE THREAD

**Issue by qimingweng** [rackt/react-router#2226]
I was wondering if there is already a way, or to start a discussion about whether or not to support relative state changes.

For example, frequently an action wants to add (or replace) a key in a query, but doesn't care what other things are in there and doesn't want change it. If I'm queries, I also furthermore don't care too much about the path, and having to import and pass these things around only makes the code more fragile.

(Also, I recognize this may have more to do with the history module, but I felt this was a better place to start the discussion)

**Comment by taion** [comment]
Already being discussed at https://github.com/rackt/react-router/issues/2172#issuecomment-146199585. Would be addressed by https://github.com/rackt/react-router/issues/2186 as well (just take the location and override the query).

**Comment by qimingweng** [comment]
A @taion thanks for pointing me in the right direction, I'll contribute to those discussion from now and close this.
