### ISSUE TITLE
Confirming Navigation sample throws an error

### ISSUE THREAD

**Issue by Akudrevatykh** [rackt/react-router#2227]
I have tried the example at https://github.com/rackt/react-router/tree/master/examples/transitions and it worked fine, however I wasn't able to use it in my project.

When confirm navigation is supposed to happen I get the following error:
`Uncaught TypeError: Cannot read property 'search' of undefined`

I have created a small sample to illustrate the issue
https://github.com/Akudrevatykh/react-router-transitions

Thanks.

**Comment by knowbody** [comment]
this bug was fixed by this commit https://github.com/rackt/react-router/commit/6f8ceac463f49f96bec7d429071c5bd3746c1e7c

but it's not released yet. This will be fixed in the RC4

**Comment by jackcasey** [comment]
Thanks for the fix, we're hitting the same on RC3. Is there any timeline on RC4 getting tagged?

**Comment by knowbody** [comment]
@jackcasey Next few days, perhaps today or tomorrow

**Comment by jackcasey** [comment]
Great! Thanks.

**Comment by CosmaTrix** [comment]
Hi all,

I still get that error in RC4. Taking error is coming from `computeChangedRoutes.js` at line 18.

**Comment by taion** [comment]
Double-check that you've upgraded things correctly and are properly using this - we've confirmed that this is in fact fixed.

**Comment by CosmaTrix** [comment]
That's weird. I upgraded from RC3 to RC4 using npm update (package.json was showing the proper version), but it didn't work anyway. After completely removing and reinstalling react-router, it stared working. Something went probably wrong running npm.
Thanks and sorry for bothering you! :)

**Comment by knowbody** [comment]
@CosmaTrix I always do: `rm -rf node_modules && npm install`
