### ISSUE TITLE
Location did not match any routes when useBasename

### ISSUE THREAD

**Issue by jepezi** [rackt/react-router#2230]
I set up a simple repo to demonstrate this issue here https://github.com/jepezi/react-router-rc3-activeclass

The code was taken from IndexLink-test.js, except history.js to use basename and remove '/website/ from the nav link.

Here's the gist.

```javascript
// history.js
import { useBasename } from 'history'
import createBrowserHistory from 'history/lib/createBrowserHistory';

export default useBasename(createBrowserHistory)({ basename: '/website' });
```

```javascript
// index.js
...
// nav
<ul>
  <li><IndexLink id="overviewLink" to="/" activeClassName="active">overview</IndexLink></li>
  <li><Link id="contactLink" to="/contact" activeClassName="active">contact</Link></li>
  <li><Link id="productsLink" to="/products" activeClassName="active">products</Link></li>
  <li><IndexLink id="productsIndexLink" to="/products" activeClassName="active">products index</IndexLink></li>
  <li><Link id="specificProductLink" to="/products/15" activeClassName="active">specific product</Link></li>
</ul>
...
```

Navigate to `http://localhost:3000/website`, I get this error `Location "/" did not match any routes`

I'm not sure if the problem is in the route matching code or the history package but decided to report it here. :dancer:

**Comment by edvinerikson** [comment]
https://github.com/jepezi/react-router-rc3-activeclass/blob/master/index.js#L72
`{ path: '/website', ...}` replace `/website` with `/`. Since you use the basename option there is no need to specify the basename in the routes.

**Comment by jepezi** [comment]
Thanks @edvinerikson  I was confused with another issue. Turns out this [one](https://github.com/rackt/react-router/issues/2212) caused me the confusion. Related: this [failing test](https://github.com/rackt/react-router/commit/f145d0804e4464e5ea29547948039ce2d0e4739d)

**Comment by edvinerikson** [comment]
No problem, glad I could help you! :)
