### ISSUE TITLE
Please make non-JSX users first-class citizens

### ISSUE THREAD

**Issue by jasonzoladz** [rackt/react-router#2234]
React Router is/is-becoming the standard routing solution for react.  As such, AltJS language users -- e.g., Purescript users (my case) -- need to be able to wrap the library, and a JSX transform isn't part of the process.

Please continue creating documentation with non-JSX users in mind.

Thanks!

**Comment by rickharrison** [comment]
Here is the documentation detailing how to create routes without JSX: https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md#alternate-configuration

**Comment by jasonzoladz** [comment]
I'm working with that, but the documentation ends with:
```React.render(<Router routes={routeConfig} />, document.body)```

I'm assuming that I can simply  do this in my wrapper:

```exports.router = function(routeConfig) {                                                                                                                                
        return Object.create(ReactRouter.Router, { routes: routeConfig });                                                                                                   };```

And pass the exported ```router``` to ```React.render```
Is that correct?

**Comment by taion** [comment]
No, you use `React.createElement` per https://facebook.github.io/react/docs/displaying-data.html#react-without-jsx.

This is just straightforward "how to use React components" when not using JSX. You'll need to use the same syntax no matter what React component you're rendering.

Given that there are already pretty extensive docs and examples for setting up routes with POJSOs, I don't think there's anything to do here.

**Comment by jasonzoladz** [comment]
Perfect.  Thanks!
