### ISSUE TITLE
send props to Named Components

### ISSUE THREAD

**Issue by farrrr** [rackt/react-router#2235]
How to send props to Named Components?

Named components is useful. but I dont know how to set props for it.

and I tried main.props.onSomethingElse = this.onSomethngElse;

but console warning me to clone element for add props. so the only way to pass props is clone it?

I use react-router 1.0.0-rc3

**Comment by knowbody** [comment]
There is nothing like "named components" in RC3. Please read [the docs](https://github.com/rackt/react-router/tree/master/docs). Everything is well explained there

**Comment by farrrr** [comment]
yes, I read, and named components is in docs.

https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/API.md#named-components

**Comment by knowbody** [comment]
I'm so bad with this recently, sorry reopening

**Comment by farrrr** [comment]
it's okay. thanks for your help.

because in upgrade guide, it said `Named routes are gone`. so I use named components in docs.

https://github.com/rackt/react-router/blob/v1.0.0-rc3/UPGRADE_GUIDE.md

**Comment by taion** [comment]
Yes, as with anything else in React, the only way to pass in props is to clone. This is a very inexpensive operation. By analogy:

```js
React.cloneElement(this.props.children, {foo: "bar"});
```

likewise:

```js
React.cloneElement(this.props.sidebar, {foo: "bar"});
```

**Comment by farrrr** [comment]
thanks for your quick response..

I really love react-router.
