### ISSUE TITLE
Google Slides embed interferes with route history

### ISSUE THREAD

**Issue by hdavidzhu** [rackt/react-router#2241]
By embedding Google Slides in my website, any event fired from changing a Google slide gets added to the history that React Router manages. Therefore, pressing the back button becomes going to the previous slide, which isn't what I want. Is there a way to bypass other services interacting with the route history?

**Comment by knowbody** [comment]
yes you can do that, use [`listenBefore` (see the docs)](https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md) then you could use `pushState` to redirect wherever you want to.
