### ISSUE TITLE
Pushstate doesn't change props.location.pathname

### ISSUE THREAD

**Issue by sirivan79** [rackt/react-router#2246]
Hi, 

excellent plugin, that I use with great joy. 

When upgrading to v 1.0, I'm experiencing a problem though.

I'm using pushState in a component to change the route:
props.history.pushState( null, this.props.location.pathname, obj );

This changes the URL as desired. However, the location is unaffected by this change. This means, whenever I'm using 'this.props.location.pathname', I still get the old URL prior to the pushstate-change.

Is this a bug, or should I use something else to update the component?

Best Regards

Martin

**Comment by mjackson** [comment]
> excellent plugin, that I use with great joy

Awesome! :D 

You may be using rc1 which had a bug. Try rc3.

**Comment by sirivan79** [comment]
Yeah, I did use rc1. Gonna try with rc3. Thank you for your quick response.
