### ISSUE TITLE
React-Router url

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/react-router#2247]
Hey,
Im using react-router `1.0.0-rc1` on one of my latest projects and I keep getting `?_k=40sveu` added to the end of the url:<img width="890" alt="screen shot 2015-10-12 at 8 24 53 am" src="https://cloud.githubusercontent.com/assets/8888991/10427826/c000cdc8-70ba-11e5-94bd-5a9dd1e96a63.png">

I would appreciate it if you could explain to me why this occurs.

**Comment by knowbody** [comment]
see the [Upgrade Guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#locations)

**Comment by kennetpostigo** [comment]
@knowbody Thank you!

**Comment by knowbody** [comment]
you're welcome
