### ISSUE TITLE
this.props.children undefined

### ISSUE THREAD

**Issue by cbegin** [rackt/react-router#2251]
I've tried this with React 0.13.x and 0.14.x as well as with two versions of Node (just in case). I've been going crazy converting a React-Router 0.13.x to 1.0.0 -- the loss of RouteHander is being felt. RouteHandler worked fantastically. However, I cannot get `this.props.children` to populate -- at all. 

I was going out of my mind, so I copied the code directly from the Readme.md (filling in necessary gaps to get it to run) and even that does not work. The simplest possible scenario will not populate `this.props.children`. 

I'm not sure what other information I can provide, other than perhaps the versions of everything that I'm using, as the code is literally the example from Readme.md. The symptom is simply that `this.props.children` is undefined.

Here's the gist of the versions of everything I'm using. Please let me know if there's any other information I can provide. 

https://gist.github.com/cbegin/bcf735e9f78cb2a28db6

Thanks much.

**Comment by cbegin** [comment]
I'll try the master/detail example in a completely clean directory later.

**Comment by knowbody** [comment]
Have a look at the [examples](https://github.com/rackt/react-router/tree/master/examples).

And also I have something like a playground repo, with react router set up [here](https://github.com/knowbody/react-router-playground).

**Comment by cbegin** [comment]
As mentioned, I tried the example on the Readme.md. I'm not new to ReactRouter, I've been using it for 7 months. I'll try the examples too, but do you have any hint as to what the problem could be, or what I could be doing wrong? As of this moment, point for point, taking ReactRouter 1.0.0 out and replacing it with 0.13.x and using RouteHandler works fine... what else needs to change to make it work (and yes, node_modules completely deleted, etc...). Thanks again.

**Comment by knowbody** [comment]
not a clue with the details you provided above. show some code, share the repo

**Comment by cbegin** [comment]
Hmm... well the code was the example code. but I'll try the other examples in a clean directory. maybe another module conflicting?

**Comment by knowbody** [comment]
I'm not sure... check https://github.com/knowbody/react-router-playground clone it and `npm install && npm start`

**Comment by cbegin** [comment]
Alright, I think I've nailed down the behavior. But I'm not sure if it's expected or not. If it is expected, then I apologize for missing it in the docs and/or upgrade guide.

I have nginx configured to route everything to index.html so that Router can handle all of the URL etc. It behaves the same with both the rewrite and the try_files approach.

```
  location ~ ^/app {
      rewrite ^(.+)$ /index.html last;
      #try_files $uri $uri/ /index.html;
  }
```

And the routes are set up like this:

```
ReactDOM.render((
  <Router>
    <Route path="/" component={App}>
      <IndexRoute component={Index} />
      <Route path="new" component={New} />
      <Route path="detail" component={Detail} />
      <Route path="*" component={NotFound} />
    </Route>
  </Router>
), document.getElementById('example'))

```

Previously, this resulted in a URL such as `http://server/app/new` being rendered directly as the composition of `App` with `New` embedded where `<RouteHandler/>` is placed within App.

But now, something odd happens. As long as I enter a URL that starts with `/app`, React Router will indeed handle it. But it seems to create some root binding to whatever URL is initially passed in. Thus directly accessing `http://server/app/new` will render `IndexRoute`. And then the sub-paths will nest beneath it as hash routes like: `http://server/app/new/#/new?_k=glzxd9`, where the actual binding is the `#/new?` part. I can access the pages successfully using a Link. But this is undesirable from a bookmark and URL perspective. What I hope would happen is what had happened before: `htp://server/app/new` would route to the `App+New` components, even if typed in the URL bar by hand.

To summarize, the URLs that the above Router settings respond to:

* Typed URL to Index: `http://localhost:3030/app/`
* Router then updates the location to: http://localhost:3030/app/#/?_k=zhx05r
* Link to New: http://localhost:3030/app/#/new?_k=drr7gm
* Link to Detail: http://localhost:3030/app/#/detail?_k=4ngogh

And as mentioned before, it will bind to anything under the `/app/`:

To summarize, the URLs that the above Router settings respond to:

* Typed URL to Index: `http://localhost:3030/app/WHATEVER/`
* Router then updates the location to: http://localhost:3030/app/WHATEVER/#/?_k=zhx05r
* Link to New: http://localhost:3030/app/WHATEVER/#/new?_k=drr7gm
* Link to Detail: http://localhost:3030/app/WHATEVER/#/detail?_k=4ngogh

Expected:

* Typed URL to Index: `http://localhost:3030/app/`
* (no updates to URL)
* Link to New: http://localhost:3030/app/new
* Link to Detail: http://localhost:3030/app/detail

Again, sorry if this is intended and I missed something in the docs. If it is intended, then I may just stick with 0.13.x for now.

**Comment by taion** [comment]
You'll want to use `useBasename` and `createBrowserHistory` from the History library.

**Comment by cbegin** [comment]
Thank you so much Taion, that was indeed the answer. I did indeed overlook the Locations section in the upgrade guide, as it wasn't something I had been leveraging in the previous versions of React Router (breadcrumbs etc).

```
If you do not specify a history type (as in the example above) then you will notice some unusual behaviour after updating to 1.0.0. With the default hash based routing a querystring entry not defined by yourself will start appearing in your URLs called "_k". An example of how it looks is this: ?_k=umhx1s.
```

Simply adding this seems to fix everything. 

```
const history = History.useBasename(History.createHistory)({
  basename: '/app'
})
```

Thanks again!
