### ISSUE TITLE
History dependency fixed at v1.12.3 in react-router 1.0.0-rc3

### ISSUE THREAD

**Issue by dlwalsh** [rackt/react-router#2252]
The latest release of react-router (v1.0.0-rc3) sets the history dependency version at "1.12.3".

Is there a reason for mandating "1.12.3" as opposed to "^1.12.3"?

I like to stay on top of the latest releases. I'm having no issues using the latest version of history (v1.12.5), other than the npm errors.

**Comment by taion** [comment]
How are you hitting NPM errors? NPM's fine with libraries having incompatible subdependencies.

**Comment by timdorr** [comment]
It looks like we might switch to a peer dependency for the final release, according to #2211. And if we do that, we'll go full semver and not lock to a specific version. 

In the meantime, as long as you pass in your own history to `<Router>`, it will use it and that can be whatever version works best for you.

**Comment by taion** [comment]
@mjackson What do you think of changing the dependency to `~1.12.3` or `^1.12.3`? Not sure if caret range is okay - is there a risk of accidentally adding new features if history does a minor bump? Actually probably not.

**Comment by mjackson** [comment]
@taion As long as we add the peer dep we're ok, right? I think we can just use `~1`. I'm not planning on introducing any breaking changes without a major version bump.
