### ISSUE TITLE
props assigned via createElement not accessible in onEnter

### ISSUE THREAD

**Issue by ihinsdale** [rackt/react-router#2253]
I have a `createElement` function that looks like:
```
    var createElement = function(Component, props) {
      return React.createElement(Component, _.extend({}, props, {
        dispatcher: dispatcher
      }));
    };
```
That allows me to access my dispatcher as `this.props.dispatcher` on any component, with one exception: `this` inside of an `onEnter` function does not have a `dispatcher` property. If I explicitly add the `dispatcher` prop to the route being matched, then `this` does contain a `dispatcher` property.

Is this an expected shortcoming of using `createElement` to assign custom props? If I want to access `dispatcher` in `onEnter`, do I have to assign it explicitly to the route (which would mean, for my purposes, to *all* routes)?

**Comment by taion** [comment]
`onEnter` doesn't have any access to any props because it runs before we start rendering the components at all. `this` on `onEnter` is the route object, not the element.
