### ISSUE TITLE
Uncaught TypeError in computeChangedRoutes module when using routerWillLeave hook.

### ISSUE THREAD

**Issue by zettadam** [rackt/react-router#2257]
I'm using **1.0.0-rc3** release and I get this error (in `computeChangedRoutes.js` module) when using the `Lifecycle` mixin and `routerWillLeave` hook.

```
Uncaught TypeError: Cannot read property 'search' of undefined
```

Looking at the debugger I see that `nextState` argument in `function routeQueryChanged(prevState, nextState)` does not contain `location` property. Consequently, I get a `TypeError`.

This is how I use it in my component: 

```javascript
import React from 'react';
import { Lifecycle } from 'react-router';

const MyRouteComponent = React.createClass( {
  
  mixins: [ Lifecycle ],
  
  routerWillLeave ( nextLocation ) {
    return  'Are you sure you want to leave?';
  },
  
  //...

} );
```

**Comment by taion** [comment]
Same as https://github.com/rackt/react-router/issues/2217#issuecomment-147469437. Already fixed on `master`.

**Comment by adesmet** [comment]
Have the same issue and can't get around it. Waiting for the next release!

**Comment by knowbody** [comment]
@adesmet soon soon soon :smile: 

we will fix a few bugs and then we cut the RC4

**Comment by adesmet** [comment]
you guys <3 thanks a lot!

**Comment by adesmet** [comment]
Still eagerly awaiting RC4! I can't seem to just include the latest master branch in my package.json, and I need this feature for my project :(

**Comment by knowbody** [comment]
@adesmet there will be no RC4, we will release 1.0 Final instead, after everything from the milestone is going to be checked off.

**Comment by adesmet** [comment]
sounds good, any idea about the timeframe?
