### ISSUE TITLE
react-router depends on babel to install

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#2260]
Just tried to install RR rc3 during a pair programming session. Seems like React Router depends on babel being available globally or throws on install.

**Comment by mjackson** [comment]
The `postinstall` script [calls `npm run build`](https://github.com/rackt/react-router/blob/b73bb1c707061936802ab48ff52e61ff70ad553e/npm-scripts/postinstall.js#L10) which uses [our build script](https://github.com/rackt/react-router/blob/b73bb1c707061936802ab48ff52e61ff70ad553e/package.json#L13) to create the `lib` directory when installing from a git repo. However, this shouldn't cause problems since `babel` is part of our `devDependencies` and you should get it with a normal `npm install`.

Did you use the `npm install --production` by any chance?

**Comment by mjackson** [comment]
I failed to mention it explicitly, but we're not relying on a global `babel`. Running our build script using npm means it'll use `./node_modules/.bin/babel`, which you should get on a normal `npm install`.

**Comment by phated** [comment]
@mjackson I'd be a little nervous doing that because if something specifies react-router as a dependency, the devDeps won't be installed (they are only installed for the top-level and only when not in production mode, e.g. NODE_ENV or --production set).

**Comment by taion** [comment]
@phated 

If something installing `react-router` as a dependency, then it should be pulling `react-router` from NPM, and the built files will already be available, so the build step of postinstall just won't run.

This step only does something if you're installing from the GH repo.

**Comment by phated** [comment]
@taion that would be ideal and expected but people can still depend on libraries pointing to the github repo by specifying it as "rackt/react-router" in their package.json

**Comment by taion** [comment]
@phated 

I don't see a better way to support that short of actually checking in the built files, which IMO is the wrong thing to do. We should only source control the actual source.

As it stands, you can do `npm i rackt/react-router` so long as you have Babel installed globally. It's not perfect, but it's slightly more convenient than e.g. not supporting installing from GH at all. For example, you just can't install React with `npm i facebook/react`.

**Comment by mjackson** [comment]
I'm afraid we can't support people depending on us using a repo URL w/out checking in our pre-built files, which we're not going to do. The `postinstall` hook is for people who want to install stuff from master to play around with it. But that's all I want to support.

**Comment by BerkeleyTrue** [comment]
Running in dev fixed the issue. Thanks @mjackson
