### ISSUE TITLE
History basename wildcard

### ISSUE THREAD

**Issue by killfish** [rackt/react-router#2261]
I have a url like this in my application: /admin/editor/module/561d441c1695f35007947555
I would like to set the basename to something like this as the last part of the path is variable: 

`const history = useBasename(createHistory)({
  basename: '/ admin/editor/module/:id'
})`

or

`const history = useBasename(createHistory)({
  basename: '/ admin/editor/module/*'
})`

The outcome when navigating would be this: /admin/editor/module/561d441c1695f35007947555#/content-slot/edit/321fdsa413432

Is this possible with react router?

**Comment by mjackson** [comment]
It's not possible with `useBasename`, but it's possible with a normal `<Route>`.

```js
<Route path="/admin/editor/module/:id">
  // ... everything else
</Route>
```

**Comment by killfish** [comment]
So just don't set the basename?
