### ISSUE TITLE
Help Using {..this.props.children} instead of reactrouter

### ISSUE THREAD

**Issue by kkotwal94** [rackt/react-router#2263]
I'm not sure if I'm nailing this in my head right, but what I'm trying to do is create a Navbar/sidebar which Ive done and the markup for it exists in a file called Navbar.jsx, however I'd like to not rerender the navbar and sidebar everytime a route changes, I currently have my routes setup like this, where login and signup are independent from this navbar/sidebar. However when we're inside the app (passed authentication) then we want to render the nav+sidebar + the changes, and whenever I change the route then I want the body to just rerender not the nav and sidebar. I have my routes set up as this, but the error I receive whenever I click on the 'About' Link in my sidebar, it says <strong>Warning: Location "about" did not match any routes.<strong> Is my route configuration set up wrong?

------Navbar-------
|
|         Content to change on route/RouteHandler/this.props.children
Side
|
|

```
 <Router>
  <Route component={App}>
    <Route name ="login" path="/" component={Login} />
    <Route name ="signup"path="/register" component={Signup} />
    <Route name ="dashboard" path="/dashboard" component={Dashboard} onEnter={requireAuth} >
       <Route name ="about" path="/about" component={About} onEnter={requireAuth}/>
       <Route name="tasks" path="/tasks" component={tasks} onEnter={requireAuth}/>
       <Route path="*" component={NotFound}/>
   </Route name>
  </Route>
  </Router>
```

**Comment by knowbody** [comment]
React Router 1.0 doesn't have named routes. You nested `About` inside `Dashboard` so the URL which matches the route which mounts `About` is `/dashboard/about`

also make sure that your `Link` looks something like:

```js
<Link to='/dashboard/about'>Take me to about page</Link>
```

**Comment by taion** [comment]
If you're doing `path="/about"` that actually matches the route `/about`, not `/dashboard/about`, per https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md#decoupling-the-ui-from-the-url, which is probably the issue you're hitting.

Separately links don't currently support relative paths so `<Link to="about">` won't work, you'll need either `"/about"` or `"/dashboard/about"` depending on what you're trying to do.
