### ISSUE TITLE
react-router 1.0.0, how to sync state with router transitions?

### ISSUE THREAD

**Issue by raptoria** [rackt/react-router#2266]
I have a tabs component that that I want to keep in sync when certain routes are hit. For example, if the user navigates to "SomePage" from the address bar and arrives at that component, I want to be able to activate that tab link. I used to set the app state inside of Router.run(routes, (Handler)  (0.13.x) . But with the new react router, I don't have a reference to Router..any ideas on how to sync my state to the current route? is there a better way of doing this ?
 
Thanks!

**Comment by taion** [comment]
Your route components receive a `params` prop that has all the current URL parameters, as well as a `routes` prop with all the currently active routes. Between that and `history.isActive`, you ought to be able to infer most things you need to know about the current router state.

**Comment by raptoria** [comment]
thanks a lot! are there any examples/docs you can point me too? For the history, do I have to keep a reference to that myself or is it also accessible as a prop?

**Comment by taion** [comment]
`history` is on context. The rest are injected into route components. Check the docs.
