### ISSUE TITLE
1.0.0 release Roadmap needed.

### ISSUE THREAD

**Issue by subjectix** [rackt/react-router#2271]
Please add a roadmap, milestone or an umbrella issue indicating the required features or bug fixes needed to release 1.0.0. 
I need a stable api for my production code and I wanna know which issues take priority to work on.
I love your new api, it's very clear and declarative and I wanna work on it, but I need to know which of the issues take priority. 

Thank you.

**Comment by knowbody** [comment]
React Router 1.0.0-rc3 is the most recent and stable version, you can use it in production. Have a look at the issues with the `bug` tag. As it is a RC version there will be no more breaking changes introduced. We are planning to release RC4 probably later today.

**Comment by subjectix** [comment]
Oh, very nice. Thank you ^^

**Comment by knowbody** [comment]
you're welcome
