### ISSUE TITLE
API Docs missing ReactRouter.match

### ISSUE THREAD

**Issue by appsforartists** [rackt/react-router#2276]
The [Server Rendering docs](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md) mention `match`, but I don't see it in the [API reference](https://github.com/rackt/react-router/blob/master/docs/API.md).

**Comment by taion** [comment]
Good catch! Mind adding a short section under "Utilities" and setting up the links from the server rendering docs?

**Comment by knowbody** [comment]
updated https://github.com/rackt/react-router/commit/05e37d46f713d6f1b422f1ccf1be1c247c4f61ed
