### ISSUE TITLE
Example Code Doesn't Work Out of the Box (README)

### ISSUE THREAD

**Issue by tonyspiro** [rackt/react-router#2277]
I know that there are assumptions made in the example code in the README and other places in demonstrating how to use react-router.  Why not complete them by adding easy history and page load examples so that users can quickly catch on to how to add this to their app? Asking for a friend :smile:

**Comment by taion** [comment]
I don't think it'd be helpful there. The full example is already quite long, and that's skipping two of the components. Maybe it'd be best just to have a link to the full examples after that code snippet.
