### ISSUE TITLE
Expose params on context?

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2278]
I'm writing a bit of code that uses this and I'm hitting something that touches on https://github.com/rackt/react-router/issues/2255, https://github.com/rackt/react-router/issues/2261, and https://github.com/rackt/react-router/issues/2172.

It's a little bit weird that I can access the current `Location` object from `this.context.location`, but I can't similarly access the route params via something like `this.context.params` and instead have to explicitly pass those params down.

It seems like for consistency it'd be ideal to treat the two identically - for doing something like building a relative `Link`, I'd like to have access in a nested component both to the current URL parameters (from `params`) _and_ the query parameters (from `location`).

**Comment by timdorr** [comment]
This seems like a good idea. Literally the only problem I have is the name `params` being somewhat generic. `routeParams` maybe?

**Comment by taion** [comment]
`routeParams` means something different though. We'd have to call it like `routerParams` or `routingParams` or something. But both `location` and `history` are also somewhat generic-sounding as well.

**Comment by srph** [comment]
I feel that RR is polluting props and context. I want it to namespace to `router` (as in `this.context.router.location`), the same for props. But it would be a breaking change.

**Comment by timdorr** [comment]
@srph react-router only puts [two things into `context`](https://github.com/rackt/react-router/blob/master/modules/RoutingContext.js#L33-L34) and `props` only reach down one level below the route, where you should have a component aware that it's in a router anyways. 

I don't consider it unacceptable to add another `context` item, especially considering it's undocumented as of yet.

**Comment by taion** [comment]
It's actually documented now: https://facebook.github.io/react/docs/context.html

**Comment by timdorr** [comment]
s/undocumented/advanced and experimental/

**Comment by srph** [comment]
Desperately need this for `<Link to={`/users/${this.context.params.uuid}`}> .. </Link>`. Is there another way?

**Comment by taion** [comment]
I have a top-level `App` route that just puts the relevant bits of `params` on `getChildContext`.

**Comment by srph** [comment]
Thanks :+1:, but I would still like to have this out of the box.

**Comment by taion** [comment]
I feel the same, obviously. It's a pretty trivial fix - just want to make sure that we're okay with this change.

**Comment by knowbody** [comment]
:traffic_light: green light. Go for it @taion.

**Comment by taion** [comment]
@mjackson 

Per https://github.com/rackt/react-router/commit/9d346fcde766e974e4d2183807a25684305fb40e#commitcomment-13933868 -

My first choice would actually be to only have `history` on child context. The motivation here is that it seems odd to expose `location` but not `params`.

I can revert #2336, but would it make sense to drop `location`? Or is it not worth making another breaking API change for that?

**Comment by timdorr** [comment]
I would leave `location` for now. This is supposed to be an rc version, so we won't ever get to 1.0.0 if we keep breaking APIs :smile:

**Comment by taion** [comment]
Yeah /: Should we just back out #2336 then? Personally, it's really the inconsistency that bothered me more than not having access to `params`.

**Comment by timdorr** [comment]
Yeah, just revert that and we can discuss how we want to do it for a post-1.0.0 release.

**Comment by taion** [comment]
https://github.com/rackt/react-router/pull/2363

**Comment by knowbody** [comment]
closing for now with the `revisit` tag

**Comment by taion** [comment]
Eh, on second thought let's just not do this.

**Comment by timdorr** [comment]
Why not?

**Comment by taion** [comment]
For a use case like https://github.com/rackt/react-router/commit/9d346fcde766e974e4d2183807a25684305fb40e#commitcomment-13942354, #2186 is a much better way forward.

For something like relative navigation, this doesn't really help anyway without something like https://github.com/rackt/react-router/issues/2177#issue-110068258.

On its own this change isn't really useful - it's essentially an XY problem, and it'd make more sense to track actual use cases.
