### ISSUE TITLE
Concepts missed...

### ISSUE THREAD

**Issue by carlitux** [rackt/react-router#2280]
I need to send extra context on server side rendering but RoutingContext don't sends the props to my components.

What is this.props.children?
What is this.props.components?

**Comment by knowbody** [comment]
what is the "extra context" you want to send? probably there is an other way of doing what you are trying to do. Explain your use case

**Comment by carlitux** [comment]
@knowbody for example when rendering server side I need to populate some props/states so can render correctly to html, with correct data for SEO.

And on browser I had before upgrade:

```jsx
Router.run(routes, Router.HistoryLocation, (Root, state) => {
  React.render(<Root { ...window.__STATE__ } user={window.__USER__}/>, document.getElementById('react-root'));

  // Reset state when first render
  window.__STATE__ = {};
});
```

This helps me to avoid requesting the data.

One new version RoutingContext is not passing this. So what strategies could be used to pass some states to components on first load (server and client side), of course after first loading is not a problem.

**Comment by taion** [comment]
Wrap `Router` or `RoutingContext` with something that has `getChildContext` with the data you want.

**Comment by carlitux** [comment]
@taion there is an error on this approach. I can't remove or stop using context I think is better this #1383 with custom createElement function

**Comment by taion** [comment]
Both can work. Context is nice in that it's not specific to your route components though.
