### ISSUE TITLE
Prevent duplicate consecutive pushStates

### ISSUE THREAD

**Issue by AndrewIngram** [rackt/react-router#2281]
(this may be an issue with history, rather than react-router, in which case please re-open against that project)

If I click a link twice in succession (mainly possible if transitions are blocked until data is ready), both clicks push the new history entry, so that when I use the back button I also need to click it twice.

The expected behaviour (for me) is to prevent pushState from having an effect if the new URL and state are already in the history.

**Comment by mjackson** [comment]
Indeed, this should be opened in the history project. Can you please open an issue there? Thanks!
