### ISSUE TITLE
`props.params` is being passed old parameter data?

### ISSUE THREAD

**Issue by jtompkins** [rackt/react-router#2285]
I'm working on a React project and using hashHistory.

If I'm on a route with a parameter, like this:

`#/accounts/99999999/information`

...and then I push a new location into history that defers only in the value of the parameter:

`history.pushState(null, '/accounts/88888888/information');`

In my component's `componentWillReceiveProps()` method, the route params contains the value of the *previous* route, not the current one. The location that's passed into my props also has the location of the previous route, with a `POP` action; the history has the new route (with a `PUSH`) action.

If I capture the previous prop values in `componentWillReceiveProps`, the *previous* props have the new route's parameter in them.

Can you help me understand what's happening here? Why does the old route appear in the location prop instead of the new route? Why does the `POP` action appear instead of the `PUSH`?

Thanks for any insight you can offer.

**Comment by taion** [comment]
Are you sure you're not switching `nextProps` with `this.props` in `componentWillReceiveProps`? This works for me.

**Comment by taion** [comment]
Oops finger slipped.

**Comment by taion** [comment]
Closing pending further updates.

**Comment by jtompkins** [comment]
Yes, I'm sorry to say that was exactly what I was doing. Thanks for the update, and sorry for the bad report.
