### ISSUE TITLE
Error after upgrading to react 0.14 

### ISSUE THREAD

**Issue by mvlach** [rackt/react-router#2288]
Hi,

I have problem with 

```
<Link to="/" >Home</Link>
```

When I delete this from code, everything works good.
Otherwise....

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Header`.
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Header`.
 ```

**Comment by KeitIG** [comment]
Have you imported the ``Link` component ?

``` javascript
import { Link } from 'react-router'; // es6
var Link = require('react-router').Link;
```

**Comment by knowbody** [comment]
@mvlach The error tells you what it is. You are trying to render the `component` in the wrong format somewhere in your `Header` component.

**Comment by only-style** [comment]
I get the same error, how to solve the problem??

**Comment by KeitIG** [comment]
As already said, the problem is probably not with react-router and you must have an error in your render method.

**Comment by jackyon** [comment]
hm... same issue happened to me, I have look around my codes, seems nothing I did wrong:

```javascript
import './Reset.scss';
import './Bootstrap.min.scss';
import React from 'react';
import ReactDOM from 'react-dom';
import Catalog from './Catalog/App-Catalog.js';
import Cart from './Cart/App-Cart.js';
import CatelogDetail from './Catalog/App-CatalogItem.js';
import Template from './App-Template.js';
import Router from 'react-router-component';
var Locations = Router.Locations;
var Location = Router.location;


class App extends React.Component {
	render() {
		return (
			<Template>
				<Locations>
					<Location path="/" handler={Catalog}/>
					<Location path="/cart" handler={Cart}/>
					<Location path="/item/:item" handler={CatelogDetail}/>
				</Locations>
			</Template>
		)
	}
}


ReactDOM.render(<App />, document.getElementById('main'));
```

**Comment by calbertts** [comment]
I have the same problem, I debugged the issue and I found the problem is on: ReactElementValidator -> createElement

It seems that all Route elements are created well, but when Router element is going to be created this validation is false:

```var validType = typeof type === 'string' || typeof type === 'function';```

Does anyone know how can I deal with this issue?

**Comment by only-style** [comment]
Test the version of react-router you have to make sure it is the latest.

**Comment by knowbody** [comment]
`rm -rf node_modules && npm install` should fix it

**Comment by manubamba** [comment]
rm -rf node_modules && npm install fixed it!
(After wasting one full day banging the wall with my head!)

**Comment by jkeam** [comment]
Dang this saved my life too.  Thanks so much!  I always forget that a lot of times this will fix all the things.  Also, I'll usually run:

`rm -rf ./node_modules && npm cache clean && npm install`

**Comment by pplegend** [comment]
still does not work

**Comment by KeitIG** [comment]
@pplegend upgrade your packages, prunes, reinstall everything, and check the latest docs, this issue happened a year ago. A lot of stuff changed since.
