### ISSUE TITLE
The server side rendering example is not working

### ISSUE THREAD

**Issue by lxjuly** [rackt/react-router#2292]
I am referring to the example given here:
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md

The 'routes' object is not properly described in the example and I made an attempt with the following approach:
```javascript    
var React = require('react');
var ReactRouter = require('../../modules');
var Route = ReactRouter.Route;
var ReactDOMServer = require('react-dom/server');
var match = ReactRouter.match;

var App = React.createClass({
  render: function() {
    return (
	    <div>Server rendering is working</div>
    )
  }
})

var routes = (
	<Route path="/" component={App}>
	</Route>
)

module.exports = function(req, res) {
  console.log(req.url);
  match({ routes, location: req.url }, 
	function(err, redirectLocation, renderProps) {
	  console.log(renderProps);
	  if (renderProps) {
	    res.send(200, 
		ReactDOMServer.renderToString(
		  <RoutingContext {...renderProps} />))
		} else {
		  console.log('Failed to render');
		  res.send(500);
		}
	  }
    );
}
```
Then on the `server.js` I just call the exported the function from one of my routes. However, the `renderProps` is undefined hence the render always failed. Since I am running from the "examples" folder of `react-router`, I should not have any dependency issues. Could this be a bug with `1.0.0-rc3`?

**Comment by taion** [comment]
These `routes` are just the same routes you'd pass into the `Router` component on the client. Check the error.

**Comment by lxjuly** [comment]
For people who might have trouble with server side rendering, what I did wrong is defining the routes:
```javascript
<Route path="/ssr" component={App}>
</Route>
```
I should use `/ssr` since that's the route I used in the `server.js`.

**Comment by ansarizafar** [comment]
@lxjuly Could you please share complete example. Are you also using code splitting with webpack. How are you passing data to components. I want to use GraphQL with server side routing.

**Comment by lxjuly** [comment]
@ansarizafar here is the snippet of my code
```javascript
if ( ExecutionEnvironment.canUseDOM ) {
      // Client-side rendering
      var history = createBrowserHistory();
      ReactDOM.render(<Router history={history}>{routes}</Router>, document.getElementById('root'));
    } else {
      // Server-side rendering
      if ( !appData.path ) {
        return callback(new Error('path cannot be null'));
      } else {
        match({ routes: routes, location: appData.path },
          function(err, redirectLocation, renderProps) {
            if (err) {
              callback(err);
            } else if (redirectLocation) {
              callback(redirectLocation);
            } else if (renderProps) {
              callback(null, ReactDOMServer.renderToString(<RoutingContext {...renderProps}/>));
            } else {
              callback(404);
            }
          });
      }
    }
```
We haven't implemented the complete data flow for server side rendering. What we do is simply invoking an action at the `componentDidMount` event hook to fetch data. We set all initial state to null and program our components such that they display a loading icon before data have been fetched. We will probably switch `Redux` and `Relay` later. Hope this helps
