### ISSUE TITLE
Access useRoutes-enhanced history outside of components

### ISSUE THREAD

**Issue by Shenlok** [rackt/react-router#2295]
Situation: I want to be able to trigger transitions, check the currently active routes etc from outside my components (inside Redux action creators, specifically). I am not using `redux-router` and cannot do so at this time.

Problem: Following the [advice from the docs for this situation](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md), I tried providing my `history` object in its own module. This gives me the ability to `pushState()` and navigate around my app from outside my components. However, the `isActive()` function is not available on this vanilla `history` object, as it is provided by the `useRoutes()` enhancer function which the router applies internally to the `history` object you pass it. This enhanced `history` object is the one passed down to your components in `props`, so you can use `isActive()` there.

I have tried applying the `useRoutes()` enhancer myself to the `history` object before passing it to the `<Router>`, but this causes nothing to render. Is there a way to provide an already-enhanced `history` to the router for use?

I have a workaround currently, where I implement a module that exports a simple wrapper around a `history` object (something like [this](http://codetidy.com/7138)). In my top-level route handler's `componentWillMount()`, I import the wrapper and call `configure(this.props.history)`, and then my action creators can import the wrapper and retrieve the ehanced history object from there. But this doesn't feel like the nicest solution. Is there a better way?

**Comment by th0r** [comment]
I would recommend not to use `<Router>` component at all - it's just a high-level API. It's limited and in my case, for example, I had to move one level down.
Just inspect `<Router>`'s code and create your own router-specific history with `useRoutes` and `createRoutes` and use `history.listen()`.

**Comment by rey-wright** [comment]
+1. Really want this and have been looking around searching for a solution

**Comment by taion** [comment]
I think @th0r's answer is correct - just do things yourself. `Router` really doesn't do very much.
