### ISSUE TITLE
release rc3 on CDN

### ISSUE THREAD

**Issue by knowbody** [rackt/react-router#2296]
this is follow up from #2164

the last version on [CDN](https://cdnjs.com/libraries/react-router) is RC1.

@mjackson could you look into that, thanks.

**Comment by mdocter** [comment]
Thanks @knowbody. 

In the meantime I managed to build the RC3 js file myself by using the `npm run build-umd` and `npm run build-min` commands.
I'm running on Windows, so I had to change the two script entries in the `package.json` file to:

```json
  "scripts": {    
    "build-umd": "SET NODE_ENV=production && webpack modules/index.js umd/ReactRouter.js",
    "build-min": "SET NODE_ENV=production && webpack -p modules/index.js umd/ReactRouter.min.js"    
  },
```

**Comment by taion** [comment]
If you have NPM, they're also available under `umd/` in the NPM package, BTW.

**Comment by mjackson** [comment]
Just submitted a PR https://github.com/cdnjs/cdnjs/pull/5944

**Comment by knowbody** [comment]
@mjackson thank you!

**Comment by mdocter** [comment]
Thanks guys! Keep up the good work.
React Router is great! You are doing an awesome job.

**Comment by knowbody** [comment]
you're welcome @mdocter !

> React Router is great! You are doing an awesome job.

Thanks!
