### ISSUE TITLE
Shared-root example and IndexRoute

### ISSUE THREAD

**Issue by arusakov** [rackt/react-router#2299]
Help me, please. I try to change routing in shared-root example.I want App(SignedIn(Home)) components at "/" path. But it doesn't work! I can not understand why. Code:
```jsx
<Router history={history}>
  <Route path="/" component={App}>
    <Route component={SignedOut}>
      <Route path="signin" component={SignIn} />
      <Route path="forgot-password" component={ForgotPassword} />
    </Route>
    <Route component={SignedIn}>
      <IndexRoute component={Home} /> 
    </Route>
  </Route>
</Router>
```

**Comment by taion** [comment]
`IndexRoute` only applies to its immediate ancestor (it works by setting `route.indexRoute`), so you can't nest routes in that manner.

You can't directly re-use the shared root example in this manner.
