### ISSUE TITLE
Guide request for Router to work with CDN and a <script> tag

### ISSUE THREAD

**Issue by otoinsa** [rackt/react-router#2300]
It does not work out of the box sadly,
right now the first thing everyone gets after includig it in your project by using
`<script src="https://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.4/ReactRouter.js"></script>`
with documentation examples is this error:

*Uncaught ReferenceError: Router is not defined.*

I've tried a lot of approaches (Yes, I did search for it for a few hours) and all of them have ended with other errors (mostly undefines, ContextType issues), even after Router was finally accessible.

I'd like to avoid npm for the project I'm using React for, since I want to keep the dir/file count low.
Also npm is known to disturbing git on windows caused by long paths (package dependency nesting),
I don't want to deal with that ever again.

So is there or will be there a definitive guide how to get this working after
placing
`<script src="https://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.4/ReactRouter.js"></script>`
 in my `<head>`?

**Comment by taion** [comment]
For a new project you should not use v0.13.x.

With the bundle, the components you want are on `window.ReactRouter`, not `window.Router`.

**Comment by otoinsa** [comment]
So there won't be a version, that works with just the cdn script tag ever?
Yes, but even after you access Router via window.ReactRouter, it does not work.
Has anyone tried the cdn build?

**Comment by taion** [comment]
What? No. The imports work just fine - http://jsfiddle.net/gqf0Lsdn/.

**Comment by otoinsa** [comment]
This fiddle is what I've been looking for, thank you :)
I had the react version without addons, so that was the issue for me.

**Comment by taion** [comment]
There is no dependency on addons: http://jsfiddle.net/gqf0Lsdn/1/

**Comment by otoinsa** [comment]
In my project I get *TransitionGroup undefined* error if use the react file included in their samples dir on the downloadable package. The one in the CDN wuth addobs you used in fiddle did not throw this error.

I was also previously using babel browser.js included in their samples dir for compilation, so that could have been a factor too. Switching to the jsx compiler you have in your fiddle might have soled something too.

Could you place this fiddle in documentation?
I think others might benefit from that.

**Comment by taion** [comment]
`TransitionGroup` has nothing to do with React Router. It is a part of the React addons, so you will of course need the React addons for that, but it's not a dependency of React Router, nor is it used, so we have no particular reason to document it.

**Comment by otoinsa** [comment]
In your own fiddle you have mention of TransitionGroup:
```
<div id="app"></div>

<script type="text/jsx">
var ReactTransitionGroup = React.addons.TransitionGroup;
var Router = ReactRouter;
(...)
</script>
```

That gets an error of undefined for version 
of react that does not have addons.
Before then I used a similar example of making the Router avaivable to my react view js that I found on my initial few hour search.

I can provide a jsfiddle if you're not convinced.


The issue was open due to lack of documented examples for use with react and the CDN version of router. That's still the issue here, since It wont work with the bundled version examples.

There is still no such comprehensive tutorial/fiddle in documentation.

So this fiddle is the key to have a working version and not spending useless hours for searching a solution; if it had been in the documentation, I could have started to work with router immidiatley.

But I have a feeling you don't care about that...

**Comment by taion** [comment]
That's just that particular fiddle, and I was working off an existing one to save some time. You can see in http://jsfiddle.net/gqf0Lsdn/1/ that the transition group was entirely peripheral, and everything works just fine with the standard React bundle.

We're interested in supporting all of our users, but the instructions are entirely clear on this matter - just pull in the file from the CDN, and everything's available on `window.ReactRouter`. I just don't see what more there is to document here.

**Comment by otoinsa** [comment]
Nowhere it says I have to do this to make it work with your examples:
'''
var Router = ReactRouter;
var Route = Router.Route, DefaultRoute = Router.DefaultRoute,
Link=Router.Link, RouteHandler = Router.
'''

If I don't do It, it does not work with examples.

How is that being entireley clear on how to make the router functional even if I just drop
your example code there from the get go.

However I am getting bored with the arguments you present and can tell you won't change a thing, so
at this point I see there is no point to continue this, since nothing of value can be added to this thread anymore.

**Comment by gaearon** [comment]
>Nowhere it says I have to do this to make it work with your examples:

>If I don't do It, it does not work with examples.

>How is that being entireley clear on how to make the router functional even if I just drop
your example code there from the get go (and use the cdn)?

Can you please clarify your expectations? Did you expect `Router`, `Link`, etc, to be global exports? I can see how this can be confusing.

>I am getting bored with the arguments you present and can tell you won't change a thing, so
at this point I see there is no point to continue this, since nothing of value can be added to this thread anymore.

Instead of arguing, please create a PR that better explains how to use UMD build.

**Comment by otoinsa** [comment]
I usually expect example code to work without adding anything to it.
Most people do, BTW.

Especially after something like this:
***
If you just want to drop a `<script>` tag in your page and be done with it, you can use the UMD/global build hosted on cdnjs.
***

**Comment by taion** [comment]
What specifically did you try to do that didn't work? As far as I'm aware our UMD packaging is entirely conventional - everything ends up on `window.ReactRouter` per the documentation, just as e.g. React puts everything on `window.React`.

**Comment by otoinsa** [comment]
Ok, so here is what exactly did not work; this is a very common scenario for people who want to just drop a cdn script tag in, I think.

I took the react js downloadable package and used one of the examples.

I took react router cdn js and downloaded it, then included in one of the example projects (react js package) alongside react js and babel (Before adding router, tested with some jsx and view logic and got very excited).

Tried both combinations of import statements  (es6 vs non es6) with the provided examples - none of that worked.

Then came a long hour search-and-try-everything, but none of that worked either. 

Documentation also did not provide a solution.
For me it seemed weird - I had all the dependencies listed and had both of the import statements tested, with the examples provided.

By thinking this is not relevant, you've made some assumptions about the end user. People might avoid node for some reason, maybe they like some projects to be minimal dev env wise. That's OK, we people are emotional beings.

What I don't understand is why it's so f8cking hard to put the solution in documentation (a working fiddle) so these types of thread don't happen. I've done a search, this is not the only 'how to use react js cnd post on the web'; why noy just end it there.

**Comment by edvinerikson** [comment]
@otoinsa something like this? https://github.com/rackt/react-router/pull/2315

**Comment by gaearon** [comment]
Hey everybody, let's chill out. No need to get emotional / defensive / whatever, this is just a docs issue and we can handle it better than that. :-)

**Comment by gaearon** [comment]
@edvinerikson 

>What I don't understand is why it's so f8cking hard to put the solution in documentation (a working fiddle) so these types of thread don't happen. I've done a search, this is not the only 'how to use react js cnd post on the web'; why noy just end it there.

If you're interested in *why* we had this omission in docs, the answer is that there's an example *right above* showing how the internals are structured:

```js
// using an ES6 transpiler, like babel
import { Router, Route, Link } from 'react-router'

// not using an ES6 transpiler
var ReactRouter = require('react-router')
var Router = ReactRouter.Router
var Route = ReactRouter.Route
var Link = ReactRouter.Link
```

The assumption was that the consumer understands that `window.ReactRouter` is exactly the same thing as `require('react-router')` and thus these instructions also apply. I can see this was confusing, so we're fixing that. Thanks.

**Comment by gaearon** [comment]
Fixed via #2315 and https://github.com/rackt/react-router/commit/f892023826910cfe95b117339510242cb9f039cb.

**Comment by gaearon** [comment]
>Also npm is known to disturbing git on windows caused by long paths (package dependency nesting),
I don't want to deal with that ever again.

This is not an issue since NPM 3.

**Comment by gaearon** [comment]
>The issue was open due to lack of documented examples for use with react and the CDN version of router. That's still the issue here, since It wont work with the bundled version examples.

>There is still no such comprehensive tutorial/fiddle in documentation.

>Nowhere it says I have to do this to make it work with your examples

I opened [0.13.x branch](https://github.com/rackt/react-router/blob/0.13.x) and [the first overview in documentation](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/overview.md) contains these lines:

```js
var Router = require('react-router'); // or var Router = ReactRouter; in browsers

var DefaultRoute = Router.DefaultRoute;
var Link = Router.Link;
var Route = Router.Route;
var RouteHandler = Router.RouteHandler;
```

>I usually expect example code to work without adding anything to it.

What example are you referring to? As I said above, the first overview shows you how to do that.

**Comment by edvinerikson** [comment]
I think it's better to "over-document" things like this rather than assuming that the consumer knows everything (I love the docs, but all this stuff may not be clear to everyone).
Might be something to keep in mind for future documentation. :+1: : )

**Comment by otoinsa** [comment]
@gaearon 

You're pointing at
https://github.com/rackt/react-router/blob/0.13.x/docs/guides/overview.md
Which does indeed have the nice
>var Router = require('react-router'); // or var Router = ReactRouter; in browsers
comment statement that makes things clear.

However none of that goodness is here on the frontpage.
https://github.com/rackt/react-router

And the documentation link from there points to here:
https://github.com/rackt/react-router/tree/master/docs



Are you guys really not getting this?
Have you actually tried a scenario of normal use case with script tag?
Try to pretend you don't know everything already and just play out the case, where react-router is something new and you want to add it to your react js project.

Yeah, you know the ins and outs of it,
but is the documentation there for others?
Nope.

**Comment by knowbody** [comment]
@otoinsa But there is a **note** on the front page:
<img width="684" alt="screen shot 2015-10-21 at 10 36 45" src="https://cloud.githubusercontent.com/assets/3802023/10633007/cb3c7968-77df-11e5-9fe6-b16299b6f49c.png">

**Comment by taion** [comment]
I'd just like to add that if you're a new user on a new project, you should definitely be using v1.0, not v0.13.

Thanks for helping us improve that part of the docs. I don't think there's anything further to discuss here.

**Comment by omarshiha** [comment]
hi, i have the same problem "Uncaught ReferenceError: Router is not defined", i installed react, react-router...etc using CDNs , does anyone has solved this problem ??? "iam working with spring boot as backend "
