### ISSUE TITLE
caught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/react-router#2301]
Hi, 

Im using `"react-router": "1.0.0-rc3"` currently on my project, working from my localhost styling and creating component. When I go to view it in my browserI just get a blank page and an error. 
Im coming across this error:
<img width="1280" alt="screen shot 2015-10-16 at 4 49 43 pm" src="https://cloud.githubusercontent.com/assets/8888991/10553033/f0fa96c0-7425-11e5-835c-d1cf881f462b.png">

Funny thing is I had the code on the server and it works great with the exception of typing in any route besides `/` shows a page not found and the only way to navigate to the page is by clicking on links.
<img width="1157" alt="screen shot 2015-10-16 at 4 56 18 pm" src="https://cloud.githubusercontent.com/assets/8888991/10553167/d8fc13b8-7426-11e5-8e36-6976adf186b4.png">
Im not completely sure why this is happening.

**Comment by taion** [comment]
That's not an RR bug, it's just what browsers do when you try to `replaceState` with `file://` URLs: https://code.google.com/p/chromium/issues/detail?id=529313
