### ISSUE TITLE
Release the last version for 0.13.x

### ISSUE THREAD

**Issue by knowbody** [rackt/react-router#2302]
As a follow up for #2262

@mjackson We should release React Router 0.13.5, and make it VERY clear that it is going to be the last release for the 0.13.x and people should upgrade to React Router 1.0

Thanks!

**Comment by joernroeder** [comment]
:+1: for 0.13.5

**Comment by airwin** [comment]
+1

**Comment by jzelenka** [comment]
+1

**Comment by prayerslayer** [comment]
Would like to see this as well so I can upgrade to React 0.14 first :+1:

**Comment by Gregcop1** [comment]
:+1:

**Comment by vincentchalamon** [comment]
+1

**Comment by knowbody** [comment]
there is no point to "+1" this issue, we know about it and it will be done ASAP

**Comment by zhaojunz** [comment]
sorry to kinda of +1 on this, is there an ETA of this release? (we are eagerly waiting for it. :-))

**Comment by TannerRogalsky** [comment]
Temporarily, feel free to use my built fork: https://github.com/TannerRogalsky/react-router/tree/0.13.5-build

`"react-router": "TannerRogalsky/react-router#dc46e526"` in your `package.json`. I will be deleting this fork when this new version is pushed to npm, though.
