### ISSUE TITLE
Rendering "non-root" urls

### ISSUE THREAD

**Issue by bbnnt** [rackt/react-router#2303]
Using simple client rendering.

Calling the root url of the app, everything works fine.

Calling a non-root url (ex. `http://localhost:xxx/myurl`) right away in the browser, I get  a `Cannot get '/myurl` error.
In production, it works fine though, I get what's expected if I hit `http://mydomain/myurl` if accessed right away

In development, hitting `http://localhost:xxx/#/myurl` works

I'm left with a big misunderstanding; if anyone could provide some enlightments, that'd be super-cool

Best

**Comment by nslobodchuk** [comment]
I'm getting the same message. "Cannot GET /about" when I try to enter http://localhost:9004/about into the address url.
On my homepage when I click on the link to About page, the page is rendered fine. When I enter the link into the address bar, I get the error.
When I don't use  history = {createHistory()}, the site works fine with hashes.

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/e7c6f3d848e55dda11595447928e843d39bed0eb/docs/guides/basics/Histories.md#configuring-your-server

**Comment by bbnnt** [comment]
:+1:
