### ISSUE TITLE
Serverside Routing

### ISSUE THREAD

**Issue by bsdo64** [rackt/react-router#2308]
Hello
Thanks for using react-router every time, but I have some problem now.

I'm following docs in [serverside-routing](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md)
When I matched routes to below react element, every url can't routes
But when I use plain object, it works well.

Here is my code
````javascript
app.use(function (req, res) {
    var reactRoutes = routes();
    match({ reactRoutes, location: req.url }, (error, redirectLocation, renderProps) => {

        if (error) {
            res.send(500, error.message)
        } else if (redirectLocation) {
            res.redirect(302, redirectLocation.pathname + redirectLocation.search)
        } else if (renderProps) {
            res.send(200, renderToString(<RoutingContext {...renderProps} />))
        } else {
            res.send(404, 'Not found')
        }
    });

});

````

Don't work :(
````javascript
var routes = function () {

    return  (
        <Route component={App}>
            <Route path="/" components={{header: header, main: main, sidebar: sidebar}} />
        </Route>
    )
}

export default routes;
````

Works well :)
````javascript
    const routes = [{
        path: '/',
        component: App
    }];
````

Could you help me how to use react element routes?

**Comment by edvinerikson** [comment]
The `match` function got the wrong signature.
You need to do something like this: `{routes: reactRoutes, ...}` otherwise the object will be transformed to something like this: `{reactRoutes: reactRoutes, ...}`

**Comment by bsdo64** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

bsdo@naver.com 님께 보내신 메일 <Re: [react-router] Serverside Routing (#2308)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by knowbody** [comment]
thanks for the answer @edvinerikson
