### ISSUE TITLE
npm 1.0.0-rc3 still uses react 0.13

### ISSUE THREAD

**Issue by mfirry** [rackt/react-router#2313]
This is weird. I'm trying to use `react-router` with `react 0.14` but I can only apparently get a version that still uses `react 0.13`

What am I doing wrong?

<img width="918" alt="screen shot 2015-10-19 at 14 32 16" src="https://cloud.githubusercontent.com/assets/1107071/10577814/567dc586-766e-11e5-9745-3133493e7932.png">

**Comment by gaearon** [comment]
It's a dev dependency, you shouldn't worry about it.
1.0 RC3 was out before React 0.14.
The next RC will use 0.14.
