### ISSUE TITLE
Translate Documentation to Chinese

### ISSUE THREAD

**Issue by camsong** [rackt/react-router#2323]
Hi @ryanflorence and @mjackson,

You may have seen that we started a project trying to translate React Router docs to Chinese 
https://github.com/react-guide/react-router-cn , I am the creator of project [redux-in-chinese](http://github.com/camsong/redux-in-chinese), but this time we started a team with 6 members initially trying to keep the translation high quality and always up to date over time.

We think this project will help a lot of Chinese new comer to get started with React Router as well as improve their skills.

Since React Router has not reached 1.0 release, not sure if you are planing for big updates in the near future. Currently, we are translating based on `master` branch.

We did not have a cool url for now, just using the plain url (http://react-guide.github.io/react-router-cn/) with GitBook access. In the near future, we are thinking if there is a way to push Chinese docs back to this official community. Any suggestions are welcomed, thanks.

**Comment by knowbody** [comment]
@camsong this sounds like a great idea! We are not planning any breaking changes to the React Router API so you can definitely use the docs from the `master` branch. We are working on the website for the new docs and we might be adding some new content, but all of this will be added to the docs on the `master` branch first.

Whenever you have something ready, please submit the PR with the link to your docs, we can include in our README file.

**Comment by camsong** [comment]
Thanks for the clarification, will sync up with `master` branch consistently.
