### ISSUE TITLE
Failed PropType validations on nested routes with extra props

### ISSUE THREAD

**Issue by thathenderson** [rackt/react-router#2324]
I have several instances where I'm fetching data and storing it on the state of a parent route component (in a traditional Flux model), then passing a subset of the state down as props to a child route component. The child component then validates the props via PropTypes and renders what it needs to.

This worked in 0.13, but after converting to rc3, I'm getting PropType validation errors on the child component props along these lines:
`Warning: Failed propType: Required prop 'propA' was not specified in 'SomeChildRoute'. Check the render method of 'RoutingContext'.`

```javascript
var SomeChildRoute = React.createClass({
  propTypes: {
    propA: React.PropTypes.number.isRequired,
    propB: React.PropTypes.number.isRequired   
  },

  render: function() {
    return <div>{propA + propB}</div>;
  }
});

var TheParentRoute = React.createClass({
  render: function() {
    return (
     <div>
      {React.cloneElement(this.props.children, { propA: 1, propB: 2 })}
     </div>
    );
  }
});
```

Digging around RoutingContext, it looked like SomeChildRoute gets rendered first, and when React.createElement tries to validate PropTypes, it only sees the props object needed by RoutingContext and not the props SomeChildRoute expects.

Workaround for now is to just remove .isRequired from my PropType validations, which I'd rather not have to do.

I could be way off here. Is there something I'm doing wrong?

**Comment by knowbody** [comment]
It is intentional, please see: https://github.com/facebook/react/issues/4494#issuecomment-125068868

**Comment by benvinegar** [comment]
@knowbody – I think this should be mentioned in the Upgrade Guide.

**Comment by knowbody** [comment]
@benvinegar you're right, mind submitting the quick PR for that?

**Comment by benvinegar** [comment]
Sure.
