### ISSUE TITLE
Passing custom props to RoutingContext in v1

### ISSUE THREAD

**Issue by DominicTobias** [rackt/react-router#2328]
When rendering markup on the server I am getting the content of a route like this:

```js
match({ routes: Routes, location: req.url }, (error, redirectLocation, renderProps) => {
...
renderToStaticMarkup(<RoutingContext {...renderProps} />)
```

Top level components can statically declare the resources to fetch, so at this point I have fetched the resources and would like to pass this data to that route component, however `RoutingContext` doesn't pass any custom props.

Do you know how I can achieve passing this initial data to the component so that I can render it correctly?

Thanks

**Comment by taion** [comment]
If you're not using Flux, I'd recommend a top-level wrapper around `RoutingContext` that exposes child context. You could in principle use `createElement` but I think a context provider is cleaner.

**Comment by DominicTobias** [comment]
@taion Thanks, I'm trying to imagine what you mean, I guess createElement something like this -

```js
React.cloneElement(RoutingContext, { someProp: 'something', ...renderProps })
```

Is that correct? And with regards to the other idea I'd be really grateful if you could provide some pseudo-code as I'm not sure how to expose child context?

**Comment by taion** [comment]
I mean this on top of everything: https://facebook.github.io/react/docs/context.html

`createElement` would be as the prop to `Router`, but don't use that for this.

**Comment by goldensunliu** [comment]
@taion any other way to do this besides using React context? Particularly, I am trying to pass a flux [Marty](https://github.com/martyjs/marty) application object on top of everything without needing to specify ```contextTypes``` in each child component

**Comment by taion** [comment]
Just render a Marty `ApplicationContainer` on top of the `Router`. That's how it works actually. The containers and `@injectApp` all pick it up appropriately. Also separately you should move off Marty :p

**Comment by goldensunliu** [comment]
@taion yeah we are in transition from Marty to Redux.  looks like ```ApplicationContainer``` is new!  Thanks for the heads up!

**Comment by taion** [comment]
Huh? But Marty v0.10.x required an `ApplicationContainer` at top-level for anything to work...

**Comment by goldensunliu** [comment]
I was actually injecting the app in as a prop from the top level

**Comment by taion** [comment]
Ouch. I'm sorry.

**Comment by DominicTobias** [comment]
@taion thanks for the context tip, didn't know react had that feature. Just wondering if you have any idea how to handle this: Have a Provider which sets the `initialState' on the context, on the server directly, and on the client hydrated an inline script with json. The first component that is reached by the router can grab the initialState from the context, but thereafter I don't want subsequent components to try and use that context. Any ideas of a neat way to handle that?

**Comment by taion** [comment]
Not entirely sure what you're trying to do. If you want to make sure a value is read-once for whatever reason, you could always just delete it after using it. Otherwise I don't know.

**Comment by doncams** [comment]
I'm trying to do the same with fluxible.io

`
server.use((req, res, next) => {
    const context = app.createContext();
    const routes = app.getComponent();

    match({routes, location: req.url}, (error, redirectLocation, renderProps) => {
        renderProps.context = context.getComponentContext();
        // console.log(renderProps);
        const markup = renderToString(<RoutingContext {...renderProps}/>);
        const exposed = 'window.App=' + serialize(app.dehydrate(context)) + ';';

        res.render('layout', {
            appContainer: _.startCase(config.appName + ' container').replace(' ', ''),
            markup: markup,
            state: exposed
        });
    });
});
`
