### ISSUE TITLE
Nested router structure..how to trigger IndexRoute of nested route for path "/"?

### ISSUE THREAD

**Issue by raptoria** [rackt/react-router#2329]
I have the following structure:
```js
         <Route path="/" component={AuthenticatedApp}>
            <IndexRoute component={Home} />
            <Route path="login" component={Login}/>
            <Route path="signup" component={Signup}/>
            <Route path="home" component={Home}>
                <Route path="homegrid" component={HomeGrid}/>
                <IndexRoute component={HomeGrid} />
            </Route>
          </Route>
```
Is there a way to route "/" to "home" and have the IndexRoute of home (HomeGrid) be activated when the website first loads? 

Right now, only If I click on a link (Link to) for home, it will correctly display the index link, but by default when the user navigates to "/", he sees Home, but home has another {this.props.children} whose route is yet unspecified so the page is blank.

Any ideas? Or better way to structure this?

Thanks!

**Comment by knowbody** [comment]
You could do something like:

```js
<Route component={AuthenticatedApp}>
  <Route path="login" component={Login}/>
  <Route path="signup" component={Signup}/>
  <Route path="home" component={Home}>
    <IndexRoute component={HomeGrid} />
    <Route path="homegrid" component={HomeGrid}/>
  </Route>
  <Redirect from='/' to='home'>
</Route>
```

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/f5aa145d465d3d85eb63f80f09029c59b6db1b4a/docs/API.md#indexredirect

**Comment by raptoria** [comment]
thank you so much!!

**Comment by knowbody** [comment]
you're welcome @raptoria
