### ISSUE TITLE
How to pass "props" to children in v 1.0?

### ISSUE THREAD

**Issue by GritBear** [rackt/react-router#2331]
In the old world I can pass down the initial props from the parent to children handler by
```javascript
<RouterHandler {...this.props} />
```
However, after the new API it is replaced by 
```javascript
{this.props.children}
```
I can't find an elegant way to pass down other props.This is blocking my upgrade as my child component can not receive initial prop states.

**Comment by knowbody** [comment]
use [`React.cloneElement`](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement).

```js
React.cloneElement(this.props.children, { someProp: 'knowbody' })
```

**Comment by GritBear** [comment]
thanks

**Comment by knowbody** [comment]
you're welcome
