### ISSUE TITLE
Lifecycle mixin's `routerWillLeave` throws error

### ISSUE THREAD

**Issue by jlongster** [rackt/react-router#2333]
I added the Lifecycle mixing and a `routerWillLeave` method, and I'm getting the following error: `TypeError: nextState.location is undefined`. It happens in `computeChangedRoutes.js`:

<img width="531" alt="screen shot 2015-10-21 at 10 00 03 am" src="https://cloud.githubusercontent.com/assets/17031/10638803/b896e1a4-77da-11e5-9768-8255bc6d3a54.png">

I went up the stack to see where this is called and looking at the code above that creates the `partialNextState` it appears that `location` should not be a part of `nextState`. I don't know the correct fix though.

<img width="636" alt="screen shot 2015-10-21 at 10 00 25 am" src="https://cloud.githubusercontent.com/assets/17031/10638827/e9afb644-77da-11e5-821f-db3c847e3ff4.png">

**Comment by jlongster** [comment]
Oh, and this happens when clicking a link that changes the route.

**Comment by jlongster** [comment]
Passing in `partialNextState` to `getRouteHooksForRoutes` instead of `nextState` seems to work, but I don't know if that's the right fix or not.

**Comment by taion** [comment]
It was a bug fixed by https://github.com/rackt/react-router/commit/6f8ceac463f49f96bec7d429071c5bd3746c1e7c. The fix isn't in RC3 unfortunately.
