### ISSUE TITLE
Redirect from root (i.e. `/`) does not work (used to work in v0.13.x)

### ISSUE THREAD

**Issue by andresgarza** [rackt/react-router#2337]
With the following Router, the `Redirect` does not work:

```javascript
<Router history={createBrowserHistory()}>
    <Route path='/' component={App}>
        <Route path='dashboard' component={Dashboard} />
        <Redirect from='/' to='/dashboard' />
    </Route>
</Router>
```

Since the `Redirect` is nested within the `/` route, I also tried the following without any luck:

```javascript
 <Redirect from='' to='/dashboard' />
```

Similar code used to work in v0.13.3.

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/API.md#indexredirect

Feel free to write this up for the upgrade guide if you find it confusing.

**Comment by knowbody** [comment]
we are going to add a warning whenever you try to do what you are trying @andresgarza 
(see this https://github.com/rackt/react-router/issues/1923)

**Comment by andresgarza** [comment]
@taion thanks! totally missed the `IndexRedirect`. Will definitely try to submit a PR with more documentation.

@knowbody that would be really helpful!
