### ISSUE TITLE
Rename createHistory to start with upper case

### ISSUE THREAD

**Issue by franzwong** [rackt/react-router#2341]
The following line will violate the "new-cap" rule in eslint. Suggest to make it starting with upper case or provide alternatives.

```
<Router history={new createHistory()}>
```

```
A constructor name should not start with a lowercase letter  new-cap
```

My workaround

```
const CreateHistory = createHistory;

<Router history={new CreateHistory()}>
```

**Comment by taion** [comment]
It's not a constructor. You call it as e.g. `createBrowserHistory()`, not as `new createBrowserHistory()`. The docs are not lying to you.

**Comment by franzwong** [comment]
I copied the code from another issue. Thanks anyway.
