### ISSUE TITLE
Unable to passing augmented renderProps into RoutingContext

### ISSUE THREAD

**Issue by GritBear** [rackt/react-router#2342]
I'm using match() in server rendering with the following code:
```
var _props = assign(initialState,renderProps);
html = ReactDOMServer.renderToString(React.createElement(RoutingContext, _props));
```
Console.log _props => the augmented props
Console.log this.props in rendered component gives only renderProps (history and etc), with no initialState fields.

Did I miss something? Help appreciated.

**Comment by taion** [comment]
https://github.com/rackt/react-router/issues/2328

Anybody want to add something like this to the docs?
