### ISSUE TITLE
History mixin issue

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [rackt/react-router#2344]
I read that:
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#navigation-mixin

Where does the object `History` of line `mixins: [ History ],` come from?
The capital letter makes me think of windows.History.

In previous examples I found
```javascript
import createBrowserHistory from 'history/lib/createBrowserHistory'
let history = createBrowserHistory()
```

The H is lower case.
I have some errors and it's hard to reduce the scope of investigation.

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/f5aa145d465d3d85eb63f80f09029c59b6db1b4a/docs/API.md#history-mixin
