### ISSUE TITLE
v1.0.0-rc3 gives "Only React Components can be mounted."

### ISSUE THREAD

**Issue by fullvlad** [rackt/react-router#2345]
Hi, sorry if this issue might be duplicate, but I did not see anything similar.

I just updated to **React 0.14** and **React-Router 1.0.0-rc3** and I get a very annoying error that I cannot seem to solve.

Here is a code snippet:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Router, Route } from 'react-router'

(function () {
    class Yoghurt extends React.Component{
        constructor() {
            super();
        }
       render() {
           return (<div>Hello World</div>)
       }
    };

    var routes = (
        <Route path="/" component={Yoghurt}></Route>
    );

    ReactDOM.render(<Router routes={routes} />, document.getElementById('app'));
})();
```
And the error message is:
```
Warning: Only React Components can be mounted.
Uncaught TypeError: instance.construct is not a function
```

What is the cause for this? I know that it may be something trivial, but It's bugging me for some time now.

Thanks in advance.

**Comment by sidhuko** [comment]
You're using JSX as an argument - use the following;

```
var routes = (
  <Router>
    <Route path="/" component={Yoghurt}></Route>
  </Route>
);

ReactDOM.render(routes, document.getElementById('app'));
````

**Comment by fullvlad** [comment]
Nope, that doesn't solve it :(

**Comment by knowbody** [comment]
as you just upgraded, try this first:

`rm -rf node_modules && npm install`

**Comment by fullvlad** [comment]
Wow, that actually solved it, but I know for sure I deleted node_modules and reinstalled them.
Thanks very much!

**Comment by knowbody** [comment]
you're welcome
