### ISSUE TITLE
Found in documentation ` (ALT+96) as string delimiter?

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [rackt/react-router#2346]
As example in
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#path--params

I found
```javascript
<Link to={`/users/${user.id}`}>Mateusz</Link>
```
`/users/${user.id}` is enclosed by ` (ALT+96).

Where can I find some information about it? It looks like by design.

Thanks

**Comment by th0r** [comment]
This is a ES2015 template string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

**Comment by vincenzo-antolini-os** [comment]
Thanks!
