### ISSUE TITLE
1.0.0-rc3 <IndexRoute> in nested route group

### ISSUE THREAD

**Issue by allantatter** [rackt/react-router#2349]
I'd like to separate 2 main route groups, `App` (where only authenticated users have access to) and `Sales` (where everybody have access to) and both route groups are visually different. The thing is, that when I hit "/" path, then `Home` component does not get rendered. When I move `<IndexRoute>` out of `Sales` route group, then `Home` gets rendered but I still need `Home` to be wrapper by `Sales` component.

```js
export default (
  <Route path="/" component={Main}>
    <Route component={App}>
      <Route path="dashboard" component={Dashboard} />
    </Route>
    <Route component={Sales}>
      <IndexRoute component={Home} />
      <Route path="about" component={About} />
    </Route>
  </Route>
);
```

Any ideas?

Thanks.

______

EDIT. There was a typo `components` -> `component`

**Comment by knowbody** [comment]
https://github.com/rackt/react-router/blob/master/examples/shared-root/app.js

**Comment by edvinerikson** [comment]
Try to change `components` to `component` on the `App` and `Sales` routes.

**Comment by allantatter** [comment]
The `components` thing was a typo, didn't fix my issue, but thanks for noticing.

@knowbody In your case, you don't have any route at path "/" at all?

**Comment by allantatter** [comment]
Nasty solution would be to have `<IndexRoute>` to redirect to "/home" or smth but that would make the URL ugly.

**Comment by knowbody** [comment]
@allantatter I don't understand your question

**Comment by allantatter** [comment]
@knowbody Maybe this way you'll understand. When I hit "/", then I'd like to have to html smth like this:

```
<div>
  <div>
    <h1>Sales</h1>
    <div>
      <h2>Home</h2>
    </div>
  </div>
</div>
```

**Main**

```
<div>
  {this.props.children}
</div>
```

**Sales**

```
<div>
  <h1>Sales</h1>
  {this.props.children}
</div>
```

**Home**

```
<div>
  <h2>Home</h2>
</div>
```

In your example with my components, when I hit "/" only `Main` would be rendered:

```
<div>
</div>
```

I hope, I explained understandably enough. Did I?

**Comment by edvinerikson** [comment]
I got this working on the master branch:
```js
<Route path="/" component={App}>
  <Route component={SignedOut}>
    <Route path="signin" component={SignIn} />
    <Route path="forgot-password" component={ForgotPassword} />
  </Route>
  <Route component={SignedIn}>
    <IndexRoute component={Home} />
    <Route path="about" component={() => <h1>About</h1>} />
  </Route>
</Route>
```

**Comment by allantatter** [comment]
Yup :( changed `"react-router": "1.0.0-rc3",` to `"react-router": "git@github.com:rackt/react-router.git#master",` in package.json and there it works. I'll have to wait for it to land in rc4 then.

**Comment by knowbody** [comment]
now I get it :smile: sometimes it takes me a while lol
This is fixed on master and should be released soon, just a few more bug fixes and we will release RC4 :)

**Comment by goldensunliu** [comment]
just ran into this bug myself while upgrading to 1.0.0-rc3. It seems like a pretty common case if one wants to have IndexRoutes nested in path less routes
