### ISSUE TITLE
v1.0.0-rc3 IsActive issues, changelog discrepancies 

### ISSUE THREAD

**Issue by matt-e-king** [rackt/react-router#2352]
Commit https://github.com/rackt/react-router/commit/85c699c is listed in the changelog for v1.0.0-rc3 (https://github.com/rackt/react-router/blob/b17d5c2aee84c21e4f84da6601608ba0d3b2c6a6/CHANGELOG.md) - however, when I checkout the tag/version or download the zip for v1.0.0-rc3, these changes are not actually reflected.

For example here, https://github.com/rackt/react-router/tree/v1.0.0-rc3/modules, I don't see isActiveMixin.js and if you open up modules/index.js https://github.com/rackt/react-router/blob/v1.0.0-rc3/modules/index.js, the `export IsActive from './IsActiveMixin';` is not in there.

When I attempt to `import { IsActive } from 'react-router';` IsActive returns as undefined. 

Am I overlooking something obvious? Any help would be appreciated. Thanks!

**Comment by knowbody** [comment]
see https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query-indexonly

**Comment by knowbody** [comment]
sorry for the tag, wrong issue

**Comment by taion** [comment]
We removed it - the preferred API is to call into `this.context.history` directly; the mixin didn't add any value. Unless you still see this in the docs somewhere, there's nothing to do here.
