### ISSUE TITLE
Link component: activeClassName gets not appended when route is active

### ISSUE THREAD

**Issue by mr-krille** [rackt/react-router#2353]
Worked a few days ago.
history doesn't support isActive. (anymore? ever?)
Tests are skipped.
Can you give us an update?

**Comment by knowbody** [comment]
not sure what problem you are facing, could you be more specific?

**Comment by mr-krille** [comment]
Sure. The Link component does not get the specified class (via activeClassName) appended when the route is active.

**Comment by knowbody** [comment]
can we see some code to help?

**Comment by mr-krille** [comment]
the tests are already there but skipped ;)

**Comment by mr-krille** [comment]
hm, the test is actually passing and I double checked it with a sample.
So this can be closed, but the test should not be skipped.

**Comment by knowbody** [comment]
I reopen as the tests should be passing, I'm looking into that now. I know it works, just fixing tests, will close when it's done

**Comment by knowbody** [comment]
fixed https://github.com/rackt/react-router/commit/45df0ddeaac2ad8b5a6905d4613d6da0886d2ed9
