### ISSUE TITLE
Pushing same route to history

### ISSUE THREAD

**Issue by redmoon7777** [rackt/react-router#2354]
Hi,

How can I stop a route (url) from being pushed to the browser's history if it is the same as the current route. So that clicking twice on <Link to="/test"> won't add "/test" to the browser's history twice.

Thanks

**Comment by taion** [comment]
Check `location.pathname` before pushing.

**Comment by th0r** [comment]
@taion You recommend to rewrite `<Link/>` component?

**Comment by redmoon7777** [comment]
Where should I check for location.pathname ?
