### ISSUE TITLE
Prevent Transition from component

### ISSUE THREAD

**Issue by ponty96** [rackt/react-router#2360]
Please is there a hook like  
      
    window.onbeforeunload = function(){
        if(form_has_data){
        return 'You must click "Buy Now" to make payment and finish your order.  
      If you leave now your order will be canceled.';
     }
    };

for react-router; 
based on the component life cycle, i know its  componentWillUnmount that is called before the transition occurs: 
does react-router | history expose any function of such

**Comment by knowbody** [comment]
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ConfirmingNavigation.md

**Comment by ponty96** [comment]
but thats only when i'm using createClass and not es6 classes.
any options for es6 classes?

**Comment by knowbody** [comment]
then you could use `listenBefore` from the `history`. You can find more here https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md

**Comment by BrunoQuaresma** [comment]
This link https://github.com/rackt/history/blob/master/docs/ConfirmingNavigation.md is out
