### ISSUE TITLE
Back button from external page

### ISSUE THREAD

**Issue by franzwong** [rackt/react-router#2361]
I made a "hacker news"-like web application displaying hyperlinks of external resources. 

Suppose I am viewing page 3 and then I click a hyperlink, and then I click the browser back button. What I expect is the router will re-evaluate "/pages/3", I saw the console logs "Location: /pages/3" and "[ArticleList] componentDidMount", but "componentWillReceiveProps" is not called, so it still kept fetching data of page 1.

In order to do what I expect, is server rendering the only option?

```
const history = useBasename(createHashHistory)({
	basename: '/hacker_news'
});

history.listen(location => {
	console.log(`Location: ${location.pathname}`);
});

ReactDOM.render(
	<Router history={ history }>
		<Route path='/' component={MainApp}>
			<IndexRoute component={ArticleList}/>
			<Route path='/pages/:page' component={ArticleList}/>
		</Route>
	</Router>,
	document.getElementById('root')
);
```

```
export default class ArticleList extends React.Component {
	constructor(props) {
		super(props);

		this._fetchArticles = this._fetchArticles.bind(this);

		this.state = {
			articles: []
		};
	}

	componentDidMount() {
		console.log(`[ArticleList] componentDidMount`);
		this._fetchArticles(1);
	}

	componentWillReceiveProps(nextProps) {
		const page = this._parsePageNumber(this.props);
		const nextPage = this._parsePageNumber(nextProps);

		console.log(`page: ${page}`);
		console.log(`next page: ${nextPage}`);

		if (page !== nextPage) {
			this._fetchArticles(nextPage);
		}
	}

	...
}
```

**Comment by taion** [comment]
Hi - you should review how React lifecycle hooks are supposed to work. This is not React Router related - `componentWillReceiveProps` is not expected to fire in that situation. https://facebook.github.io/react/docs/component-specs.html

**Comment by franzwong** [comment]
I just found that I can access the last value (just before going to external resource) in componentDidMount. So when I click the back button, I can fetch the data in componentDidMount with "this.props.params.page".

I think we can state this scenario in https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md.

**Comment by taion** [comment]
It's the exact same as when you're entering the page for the first time.
