### ISSUE TITLE
Link should pass to as a props to the a element

### ISSUE THREAD

**Issue by tarjei** [rackt/react-router#2368]
Hi, the Link component doesn't pass the `to` prop down to the a element. 

AFAIK there isn't any downsides to doing that, and it has a great upside: You can test the Link using scryRenderedDOMComponentsWithClass. If not you have to get the Link type element and go from there.

Would it be possible to add to to the props of the a-tag in the Link component?

**Comment by taion** [comment]
How does putting `to` on the child element let you scry by class?

It's pretty straightforward to go from the Link element to the anchor anyway - it's just a findDOMNode call.
