### ISSUE TITLE
when go(n), how to let the list data change?

### ISSUE THREAD

**Issue by kazaff** [rackt/react-router#2369]
in my webapp, i have a list page(path like "/list/:page"). 
for example, i am in "/list/2", when  press the browser's goback button, the url will change to "/list/1", but the list always show the data of page2.

how to fix?

**Comment by taion** [comment]
You need to update it yourself based on the new params. If your render functions are appropriately pure, this should just happen for you.

**Comment by kazaff** [comment]
```javascript
......
@connect(select)
export default class UserListContainer extends Component {

  componentWillMount() {
    this.props.dispatch(usersList(this.props.params.page||1, 15, this.props.location.query.keyword));
  }

  render () {
    return (
      <div>
        <UsersList users={this.props.users} loading={this.props.loading} />
        <Pagination page={Number(this.props.params.page)} total={this.props.total} onClick={this._handlePageClick.bind(this)} />
      </div>
    );
  }

  _handlePageClick (page) {
    this.props.history.pushState(null, "/user-list/"+page, {keyword: this.props.keyword});
    this.props.dispatch(usersList(page||1, 15, this.props.keyword));
  }
}
```

**Comment by taion** [comment]
Right so for example you can't do this in `componentWillMount`. See e.g. https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md and structure your code accordingly.

**Comment by kazaff** [comment]
thank you
