### ISSUE TITLE
Rendering error pages on server with RoutingContext

### ISSUE THREAD

**Issue by rpominov** [rackt/react-router#2370]
[Current guide for server rendering](https://github.com/rackt/react-router/blob/d28036b97e1e991b2cf502a108673303ac5e0149/docs/guides/advanced/ServerRendering.md) suggest to return simple strings for error pages. But on real sites we often want to render error pages with React too. And we want to use `<Link>` on error pages as well. The problem is `<Link>` needs `<RoutingContext>` in order to work correctly, but we don't have `renderProps` for it in case of 404 at least (according to the guide).

So what is the best approach to render error pages with React and RoutingContext?

**Comment by rpominov** [comment]
I've manage to work around this problem.

For 404 rendering I've added `<Route path="*" component={NotFound} />` at the end of my routes config. And we have different solution for status codes.

And I think it's ok to render simple string in case of some error during routes resolution, which should not happen normally.

But still it's seems a bit awkward. Maybe there is a better solution? Or maybe the server rendering API should be changed somehow?

**Comment by taion** [comment]
I think the not found route is the right thing to do. How do you figure out if you're rendering that route for purposes of setting the status code?

**Comment by timdorr** [comment]
If there is some sort of error during routing, then you can't expect the router to still function for your `Link` components. You should render a static error message and force the client side to re-request via plain `a` tags, in the hopes that they don't encounter the error again.

The exception being the 404 case, which I've found the `NotFound` option works pretty well.

**Comment by rpominov** [comment]
> How do you figure out if you're rendering that route for purposes of setting the status code?
We use https://github.com/gaearon/react-side-effect for pages meta data like `title`, `description` etc., and also specify status codes using it.

**Comment by rpominov** [comment]
Ok, problem seems to be solved for me. 
Thanks you for clarification about the `NotFound` route @taion and @timdorr !

Not sure if this should be closed or not. I'm totally fine with it being closed.
