### ISSUE TITLE
Scroll behavior

### ISSUE THREAD

**Issue by fatfisz** [rackt/react-router#2373]
Hi, sorry if I'm asking the obvious, but is there a simple built-in way to handle scroll properly? Couldn't find it in the docs.

By "properly" I mean scrolling to the top when navigating to a new page.

**Comment by jozsefs** [comment]
You could place the scrolling functionality in the container App component's `componentWillReceiveProps` function (which is one of the functions that are called after navigation).

Ref: [Lifecycle](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md#lifecycle-hooks-when-routing)

**Comment by fatfisz** [comment]
Hmm I guess that's one way (shouldn't it be `componentDidUpdate` though?).

Thanks for help!

**Comment by knowbody** [comment]
please look through the other issues before opening one: https://github.com/rackt/react-router/issues?utf8=%E2%9C%93&q=is%3Aissue+scroll
