### ISSUE TITLE
Release v1.0.0-rc4

### ISSUE THREAD

**Issue by danieljuhl** [rackt/react-router#2374]
A lot of commits has landed on master since `1.0.0-rc3`. Instead of having to reference the master branch from the git repo in package.json, it would be nice, if a new version could be released. Than would also get more actual testing for the latest commits, and bringing us all closer to a real `1.0.0` stable release.

**Comment by knowbody** [comment]
we will do that soon, still there are a few bugs/enhancements we want to add/fix so they can be included in the RC4
