### ISSUE TITLE
How to test clicking a Link + Transition logic w/out a spy or mock

### ISSUE THREAD

**Issue by toranb** [rackt/react-router#2375]
Coming from the ember world so bare with me :)

In the test below I'm trying to render my application, verify the first Link has the "users" href attribute (and that works fine). But next I'm looking for a way to "click" that link, have the app I rendered transitionTo the next view (w/ a list of people in this example) so I can then verify the behavior + whatever is on the next page. Do you have an example in your tests some place that I could PR up to the testing guides for others (like me) who want /or need this type of testing?

Thank you for such a great OSS project !!!

```js
describe('Given my single page app', () => {
    describe('when we render the application', () => {
        before(() => {
            node = document.createElement('div');
        });
        it('should render person details when clicking through from users', () => {
            render((
                Routes
            ), node, function () {
                var a = node.querySelector('a');
                expect(a.getAttribute('href')).eql('#/users');
                click(a); //after this click we transition to a child route
                var user = node.querySelector('a');
                expect(user.getAttribute('href')).eql('#/users/1');
            });
        });
    });
});
```

https://github.com/toranb/learning-react-and-webpack-2015/blob/master/test/test.spec.js#L31-L33

**Comment by taion** [comment]
Take a look at what our tests do: https://github.com/rackt/react-router/blob/master/modules/__tests__/Link-test.js

Ultimately it's just calling into the React test utils.

**Comment by toranb** [comment]
I already have that much working (simulate import is on line 5)

https://github.com/toranb/learning-react-and-webpack-2015/blob/master/test/test.spec.js#L5

What I'm trying to do is click a url that transitions the app to a child route (like I have in this super tiny example app). How do I verify this end-to-end ish using the runtime (avoiding something like selenium)?

In ember I would get an async callback that looks something like the below. I'm trying to get a basic understanding like ... "yes- async callbacks give you exactly this and here it is" or "no- sorry man this still hasn't been built yet"

```js
//this works in ember today
test('should render person details when clicking through from users', function(assert) {
    visit('/');
    click('#users-link');
    andThen(function() {
        assert.equal(currentURL(), '/users');
    });
    click('#first-user');
    andThen(function() {
        assert.equal(currentURL(), '/users/1');
    });
});
```

**Comment by taion** [comment]
I believe that's exactly https://github.com/rackt/react-router/blob/master/modules/__tests__/Link-test.js#L294-L304. Unless you're using async components, the transitions happen synchronously.

**Comment by toranb** [comment]
Ah, so you can chain these over and over then? Thank you!

Also -what if I do have async work happening in the child components `getInitialState` method? Such as some async xhr/ajax code that "when resolved" fires an event that should (eventually) re-render the child component?

**Comment by taion** [comment]
You'll have to use something on your side to pick up on those (potentially with timeouts). The router won't know about those.

**Comment by toranb** [comment]
Thanks for the detailed replies today. I'm thinking of writing a promise based api (like what you see above in my ember testing example) to accomplish provide a legit async testing story. Has an effort like this already been started/or even talked about that you know of?

**Comment by taion** [comment]
I'm not sure what you mean. It's not even applicable in cases like this because everything is synchronous. There aren't any weird concepts here - React's event loops are simple enough that things mostly just work, and there's nothing async to core React operation.

**Comment by toranb** [comment]
Imagine for a minute that the child component fires off an xhr when loaded. I'd like a simple api (without timeouts/etc) that reads imperative and lets me drive the app like an end user would (think selenium but w/out all the sleep and wait for element hacks).

I have to imagine this is desirable for someone in the community -no?

**Comment by taion** [comment]
I'd suggest getting a bit more familiar with the ecosystem first - the issue with what you're talking about is that React is entirely unopinionated regarding how that data fetching happens. There's not really a "general" concept of those sorts of chained async actions, because there's no necessary connection between the action from the parent and the action initiated by the child - i.e. there's 2 or 3 different ways for doing this pattern that are good in contexts of different application frameworks, and you wouldn't even instrument them the same way.

**Comment by toranb** [comment]
I've got no problem getting familar w/ the ecosystem but I'm also speaking from experience here. I build software for clients and test drive from the outside-in. This style of tdd isn't possible (yet) that I know of w/ React and React Router so I'd like to help pioneer it. Look past my ember roots here please, I'm not looking to build an opinionated framework on top of anything. Instead I'm asking if people write high level tests w/ this project and if so, how are they successful today. If this isn't possible why not and how can I help? I wasn't trying to start a war on github here -just looking for help ...

**Comment by taion** [comment]
Right, the issue is that React Router is too low-level for such a testing framework to be a good fit, if that makes sense. React Router doesn't really know or care about how e.g. you fetch data from component mounting. In other words, the place where you'd integrate something like this would be with a higher-level library or framework that actually had an implicit concept of e.g. data fetching on component mount.

**Comment by toranb** [comment]
Understood - I should have stated earlier that I'm looking to bolt this on above the react-router library itself (and it sounds like that is the only option as you suggest). I'll investigate this myself for basic "xhr" like async loading and see what I can come up with to be productive. Thanks for all the communication today!

**Comment by ryanflorence** [comment]
Hi Toran :)

I don't have internet at my new house yet, but when I do I'll try to find
you in real time to talk more about this with you, in the meantime:

Ember has conventions on data loading with model hooks that the integration
test helpers hook into. We don't have that. You will need your own data
loading conventions and open up API to create your own test helpers like
Ember's. You'll use the router hooks we already use in our tests in
combination with your data API.

**Comment by ryanflorence** [comment]
But to answer your question about high level integration tests, no I don't.
Router already has tests that prove links cause route transitions. I would
just render my component by itself in a test and spy on my ajax code to
make sure it loads data on mount. I'm unclear on what the e2e test would
provide given the tests I just described. In ember it's not so easy to take
a chunk of your app out of context and test it in isolation so e2e tests
are about your only hope, in React it's dead simple making the e2e test
redundant.

**Comment by toranb** [comment]
Hi Ryan :)

I'd love to talk with you in private about my goal(s) and motivation(s) for this. It has more to do with "my view on tdd" and less to do with "ember vs react"

About your comment on e2e or (not) e2e testing with React/Ember. I'm speaking /writing about my current approach to single page app development (the vNext of test-first IMHO) called "outside-In test driven development" (not a new concept but I'm showing how it's used to build JS apps quickly).

In ember my first test (thinking outside-in) is the acceptance test. If I can achieve something like this w/ React (using your router) I'd be able to show people what this really looks like (outside of the ember ecosystem). Don't forget -any great idea often sounds "crazy/ not possible/ not well thought out" the first time you hear it, but I promise you this is not only valuable (to me personally) but it can greatly increase velocity for JS teams (when executed well).

Don't get me wrong -if this style of tdd isn't your thing, cool (don't let me tell you what works/ what doesn't). But to be 100% clear, it is my thing (and honestly it's so far ahead of what most people know about tdd that when they see me do it they all same the same thing "I wish someone had shown me this when I was first learning tdd"). I'm simply looking for a starting point here, not "hey Ryan, please write this or I'll talk badly about your OSS project".

Ping me via email to talk in more detail (if and when you get time + internet access)

toranb at gmail
