### ISSUE TITLE
Some links cause full re-renders

### ISSUE THREAD

**Issue by TylerBrock** [rackt/react-router#2378]
Hey everyone, maybe this is a more appropriate question for the react-bootstrap repository but I'm wondering why some links cause the router to re-render the entire page and others do not. I don't have any problem using `history.pushState()` but some react-bootstrap components that require hrefs cause a full re-render while others do not. One such example is the DropdownButton:

```js
const csvImportHref = this.context.history.createHref(
  `/o/${organizationId}/g/${groupId}/contacts/csvImport`
);
const newLeadHref = this.context.history.createHref(
  `/o/${organizationId}/g/${groupId}/contacts/new`
);

<DropdownButton id="addLeadDropdown">
  <MenuItem href={newLeadHref}>Add</MenuItem>
  <MenuItem href={csvImportHref}>Upload CSV</MenuItem>
</DropdownButton>
```

Selecting an item from the dropdown causes a full page rerender when it should not.

**Comment by taion** [comment]
If you look at `Link`, the way this is handled this is actually with an `onClick` that calls `pushState`. If you actually go through with the default behavior on an anchor with an `href`, you do get an actual page transition.

The easy answer here is to use react-router-bootstrap, which is provided for exactly this use case.

**Comment by TylerBrock** [comment]
Ok, thanks @taion, could I just write the onclick handler myself? It's odd that this worked with the last react-router and not 1.0.0-beta3

**Comment by taion** [comment]
That's all up to you.

**Comment by TylerBrock** [comment]
Thanks Jimmy.
