### ISSUE TITLE
Scrolling behavior, where is it defined or documented ?

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#2379]
I am currently experiencing a problem were a linked (next) page takes the scroll position of the existing / previous page.

I can't find any mention about scroll behavior in the current docs. Where is this defined? I need to the next page to enter at scrollY = 0, except for when using the backbutton. In that case it needs to restore the previous scroll position of the page.

**Comment by knowbody** [comment]
at the moment we do not have the API for scrolling behaviour. But please search the previous issues, this question has been asked so many times. https://github.com/rackt/react-router/issues?utf8=%E2%9C%93&q=is%3Aissue+scroll

**Comment by 0x80** [comment]
You're right I should have searched the closed issues first. Sorry for that. 

However it would clearly be useful to have a something in the docs about this if so many people create issues for it. What is extra confusing is that react-router did have options for scroll behavior before so they are mentioned in the changelog but disappeared from the docs. 

So as I understand it scroll position is preserved if you use a Link to navigate. So if you navigate to a page in your app you probably want to call `window.scrollTo(0,0)` in `componentWillMount()` or something.

**Comment by knowbody** [comment]
I'll add the note in the Upgrade Guide.

back to your question: you can use `onUpdate` hook on the `Route` and do `window.scrollTo(0, 0)`

**Comment by 0x80** [comment]
onUpdate hooks don't seem to fire for me

`<Route component={PageLayout} onUpdate={() => console.log('route update')}>` 

Am I missing something?

**Comment by knowbody** [comment]
I ate the 'r' should've been `Router`

**Comment by 0x80** [comment]
Ah ok. But I don't think I can use that. Some of my pages should use the scroll position that the browser remembers. Like scrolling through a long list of posts and then clicking one to view the post in a new page. I wish each page would just remember its own scroll position, but currently the post takes the scroll position from the overview list. 

Using the back button the browser should land in the list where you left it. That seems to work fine. I don't understand why I need a scrollTo for the post page, but I definitely don't want it for the overview list.

**Comment by taurose** [comment]
You should be able to use `this.state.routes` and `this.state.location` inside the update hook.

But keep in mind that native browser scrolling varies from browser to browser. IIRC Firefox can cause problems when navigating from a short to a tall page since it scrolls before firing popstate.

**Comment by sikanhe** [comment]
@0x80 I had that problem when i have overflow: auto enabled somewhere in the paren css( in my case the html/body root css ) see if you have that enabled, it preserves scroll position when i go from list view to detail view. It could be your case i am not sure

**Comment by jackyon** [comment]
@0x80 did you found the solution? plz advise

**Comment by 0x80** [comment]
@jackyon no sorry I can't help you. The project I worked on has since been parked, and I haven't looked into it again since. I worked around it by firing a scroll to top on the next frame after clicking a Link, but that is obviously a hack and resulted in a visible glitch.

**Comment by jackyon** [comment]
@0x80 yep~ firing a scroll top event is okay for the clicked links, but the main problem is when you click the back button, the position should be remember the scroll position.

I found this scroll behavior for react-router:
https://github.com/rackt/scroll-behavior

but looks this scroll behavior is no perfect, there is still some bugs happened in my test projects.
