### ISSUE TITLE
v1.0.0-rc3 bug with examples/sidebar 

### ISSUE THREAD

**Issue by warmhug** [rackt/react-router#2381]
the `examples/sidebar` In the branch master, works very well. but it can not work in the latest version `v1.0.0-rc3`, please upgrade a version.

**Comment by taion** [comment]
No additional action items on this issue.

**Comment by warmhug** [comment]
I'm sorry, but it has not been resolved. Why close it ???

**Comment by taion** [comment]
We already know we need to release RC4. There's nothing to do to fix this issue.
