### ISSUE TITLE
CDN links to 0.13x version

### ISSUE THREAD

**Issue by dnmfarrell** [rackt/react-router#2382]
But the documentation is for 1.x

**Comment by taion** [comment]
The 1.0.0 prereleases are actually on CDNJS. If you need the v0.13.x docs, go to the v0.13.x branch.

**Comment by dnmfarrell** [comment]
But the 1.0.0 docs link to the 13x version

**Comment by taion** [comment]
It's the package's main landing page on CDNJS. You can choose a version in the dropdown.

**Comment by dnmfarrell** [comment]
Got it, thanks!
