### ISSUE TITLE
Name-less route config equivalent

### ISSUE THREAD

**Issue by alex94puchades** [rackt/react-router#2384]
In react-router v0.13.x I was able to do this:
```js
	<Route name="root" path="/" handler={App}>
		<Route name="login" handler={LoginPage}/>
		<Route name="logout" handler={LogoutPage}/>
		<Route name="dashboard" path="/" handler={Dashboard}>
			<Route name="user-search" path="/users" handler={UserSearch}/>
			<Route name="user-new" path="/users/new" handler={UserNew}/>
			<Route name="user-edit" path="/users/:id" handler={UserEdit}/>
			<Route name="role-search" path="/roles" handler={RoleSearch}/>
			<Route name="role-new" path="/roles/new" handler={RoleNew}/>
			<Route name="role-edit" path="/roles/:id" handler={RoleEdit}/>
		</Route>
	</Route>
```
But in v1.0, with named routes gone (for good), is it possible to have this kind of config? (I'm referring to the dashboard route here) I mean, so that route "/users/" has components disposed like **App > Dashboard > UserSearch**. If not currently, could it be added somehow? Maybe `<IndexRoute component={Dashboard}>...</IndexRoute>` would be the way to go?

**Comment by knowbody** [comment]
`IndexRoute` is a leaf route so you can nest anything within this route. Check the `auth-flow` example for resolving the login part. And then make the `<Route name="root" path="/" handler={App}>` pathless: `<Route component={App}>` and leave `<Route path="/" component={Dashboard}>` with the path.

There is plenty of examples around and also similar issues already, please search.

**Comment by alex94puchades** [comment]
I'm sorry, I've been busy upgrading my codebase to the new version, and so I didn't look for a similar issue before posting. Next time I'll do better, and btw good job with v1.0!

**Comment by knowbody** [comment]
thank you!

feel free to ask more questions if you have problems with upgrading, we are on IRC or http://www.reactiflux.com/
