### ISSUE TITLE
Server-Side Auth Flow

### ISSUE THREAD

**Issue by johnnyji** [rackt/react-router#2387]
I was wondering how to exactly implement authentication flow with React Router if my app is rendering server-side?

#### The scenario:
When the user first arrives at the app, we invoke an `onEnter` router method in order to check if any current user is present (`localStorage`), if they are we will redirect them to their dashboard, otherwise we redirect them to the landing page.

Therefore when my app hits my protected routes `onEnter`, here's ideally what should happen:

```
onEnter: () => {
	if (localStorage.getItem('authToken')) {
		// Authenticate and redirect user to intended path
	} else {
		// Redirect the user to the login page
	}
}
```

The problem here is that because we're rendering server-side, we don't have access to things such as `localStorage`. Can anyone suggest a way to overcome this, or a better way to handle server-side auth with React Router?

**Comment by Nicktho** [comment]
One solution is to not rely on localStorage for authentication, use it just to supply credentials along with alternatives for the server (for example a session). Then handle the actual auth checking with some other code. 

ie in semi-psuedo: 

```
onEnter: () => {
  const auth = isClient() ? getAuthFromLocalStorage() : getAuthFromSession();
  
  if (isAuthorized(auth)) {
     // Authenticate and redirect user to intended path
  } else {
    // Redirect the user to the login page
  }
}
```

**Comment by taion** [comment]
That is the basic approach you have to take. Thanks for answering this!
