### ISSUE TITLE
How can you programmatically trigger a route?

### ISSUE THREAD

**Issue by davis** [rackt/react-router#2388]
in most scenarios I can use a `<Link/>` to put in a link to somewhere

but in other places, i want to programmatically trigger a route. I looked around some of the other issues but couldn't find a satisfying answer. Could someone point me to how I can accomplish this? Do I need to reach down into `history`?

thanks!

**Comment by BerkeleyTrue** [comment]
You can include the History mixin ( or grab it from the context as well). This then places the history object right on the component.

```js
import { History } from 'react-router';

export default React.createClass({
  mixins: [History],
  goTo(uri) {
    this.history.pushState(null, uri);
  },
  //...
});
```

**Comment by taion** [comment]
Thanks for answering that!

**Comment by davis** [comment]
ah! thanks @BerkeleyTrue, but i forgot to mention - i'm using es6 Components so i don't have access to mixins

**Comment by BerkeleyTrue** [comment]
In that case, you just grab it from the context. ref: https://github.com/rackt/react-router/blob/master/modules/History.js

```js
export class extends React.Component {
  contextTypes: {
    history
  },

  goTo(uri) {
    this.context.history.pushState(null, uri);
  },
  //...
});

**Comment by kumarharsh** [comment]
The previous ES6 snippet has some errors. Here's the working code:

```js
export class Item extends React.Component {
  static contextTypes = {
    history: React.PropTypes.object,
  };
  _goto = (url) => {
    this.context.history.pushState(null, url);
  }
  render() {
    return (<div onClick={this._goto.bind(this, '/some-url')}>View</div>);
  }
}
```

**Comment by 5an1ty** [comment]
I finally figured it out, the above example also wasn't working for me...

You need to set contextTypes outside of your class:

MyClass.contextTypes = {
	history: PropTypes.history
};

Oh and also use PropTypes.history instead of PropTypes.object...

I wonder why we need to set contextTypes outside of the class, would love some input on that.

**Comment by BerkeleyTrue** [comment]
@kumarharsh fixed

**Comment by 5an1ty** [comment]
@BerkeleyTrue That does not work for me, see comment above.

**Comment by BerkeleyTrue** [comment]
@5an1ty You need to enable class properties in babel for static properties to work.

**Comment by 5an1ty** [comment]
@BerkeleyTrue I think it is, unless I need to pass an additional parameter to JSPM.
It doesn't really break on the static declaration. When I use your code I receive the following error:

Uncaught TypeError: Cannot read property 'pushState' of undefined

**Comment by knowbody** [comment]
> Oh and also use `PropTypes.history` instead of `PropTypes.object`...

@5an1ty it does not make sense to do `PropTypes.history`, the `history` is type of `object`, hence you should validate the PropTypes: `PropTypes.object`. Read more [here](https://facebook.github.io/react/docs/reusable-components.html#prop-validation).

> I wonder why we need to set contextTypes outside of the class, would love some input on that.

[Class static properties](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/#property-initializers) are proposed changes. And you can enable them by adding [`syntax-class-properties`](http://babeljs.io/docs/plugins/syntax-class-properties/) plugin (Babel 6).
