### ISSUE TITLE
Changing query params no longer preserves scrolling postion?

### ISSUE THREAD

**Issue by sikanhe** [rackt/react-router#2391]
When i call  this.props.history.pushState(null, `/search/path`, { search: e.target.value});

This makes the page jump to the top, if so how can i avoid this? Query param usually means changing the state of the current page, not entering a new page.

Edit: I see this is probably the same issue as #2332

**Comment by taurose** [comment]
Calling `pushState` shouldn't cause any scrolling as far as I can tell. Did you perhaps implement the `onUpdate` hook to do the scrolling as suggested in other issues? Or do you render the content asynchronously after a route/query change?

**Comment by taion** [comment]
Also, this is what you'd get if you followed a normal link that changed the query. It is a page transition, just not a route enter/exit transition.

Regardless, let's consolidate discussion on #2332.
