### ISSUE TITLE
Cannot enter URL manually indeed via navigation

### ISSUE THREAD

**Issue by bdart** [rackt/react-router#2395]
Enter 'http://localhost:3000/booking' in the url prompts me: `cannot get /booking`.

enter 'http://localhost:3000' opens my app and i can click on booking and the url changes to:
'http://localhost:3000/booking' --> I can navigate easily through the navigation. But when I hit reload or enter any url manually it throws always the `cannot get /...`

This is my 'app.jsx' with the routing is it about the `createBrowserHistory()`?

```javascript
ReactDOM.render((
  <Router history={createBrowserHistory()}>
    <Route path="/" component={AuthenticatedApp}>
      <IndexRoute component={Home}/>
      <Route path="login" component={Login}/>
      <Route path="signup" component={Signup}/>
      <Route path="quote" component={Quote}/>
      <Route path="booking" component={Booking}/>
      <Route path='*' component={NotFoundSection} />
    </Route>
  </Router>
), document.getElementById('content'));
```

Another strange behaviour besides this is that my pushState does not change the view. Same procedure as above when I fill out my login form it redirects me to /home but the view stays my login form. Clicking on a link works reload prompts: `cannot get /...`

```javascript
    if (savedToken !== access_token) {
      let history = createHistory();
      history.pushState(null, `home`);
      localStorage.setItem('access_token', access_token);
    }
```

**Comment by knowbody** [comment]
this sounds like your dev server is not supporting the browser history

**Comment by bdart** [comment]
No this is my package

```
{
  "name": "test-app",
  "version": "0.0.1",
  "main": "index.js",
  "browserify": {
    "transform": [
      "babelify"
    ]
  },
  "scripts": {
    "start": "npm run build && serve .",
    "build": "npm run build-js && npm run build-css",
    "watch": "npm run watch-js & npm run watch-css & serve .",
    "test": "npm run lint -s && npm run build",
    "build-css": "rework-npm index.css | cleancss -o build/build.css",
    "build-js": "browserify --extension=.jsx --extension=.js src/app.jsx | uglifyjs > build/build.js",
    "watch-js": "watchify --extension=.jsx --extension=.js src/app.jsx -o build/build.js --debug --verbose",
    "watch-css": "nodemon -e css --ignore build/build.css --exec 'rework-npm index.css -o build/build.css'",
    "lint-eslint": "eslint .",
    "lint-jscs": "jscs .",
    "lint": "npm run lint-eslint && npm run lint-jscs"
  },
  "dependencies": {
    "bootstrap": "^3.3.0",
    "flux": "^2.0.1",
    "jwt-decode": "^1.1.0",
    "react": "^0.14.*",
    "react-dom": "^0.14.*",
    "react-mixin": "^1.1.0",
    "react-router": "^1.0.0-rc3",
    "react-spinkit": "^*",
    "react-ux-password-field": "^*",
    "react-addons-linked-state-mixin": "^*",
    "history": "^*",
    "formsy-react": "^*",
    "cssify": "^*",
    "reqwest": "^1.1.5",
    "when": "^3.7.2"
  },
  "devDependencies": {
    "babelify": "^6.1.0",
    "browser-sync": "^2.1.6",
    "browserify": "^8.0.3",
    "clean-css": "^3.1.9",
    "eslint": "^0.14.1",
    "nodemon": "^1.5.0",
    "rework": "^1.0.1",
    "rework-npm": "^1.0.0",
    "rework-npm-cli": "^0.1.1",
    "serve": "^1.4.0",
    "uglify-js": "^2.4.15",
    "watchify": "^2.1.1"
  }
}

```

**Comment by taurose** [comment]
`serve` doesn't seem to support push state at all. You should consider using another server, e.g. [pushserve](https://github.com/paulmillr/pushserve). Also see https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#configuring-your-server . 

For navigation, don't create a new history object but reuse the one you gave to the router

* inside route components:  `this.props.history.pushState(...)`
* inside other react components: https://github.com/rackt/react-router/blob/master/docs/API.md#history-mixin
* outside react components: https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md

**Comment by knowbody** [comment]
thanks @taurose !

**Comment by bdart** [comment]
Exchanging serve with pushserves resolves nearly everything instead that it do not rerender my page after push or replace state :/ can I provide anything that can point to my problem?
