### ISSUE TITLE
Why were named routes removed?

### ISSUE THREAD

**Issue by mull** [rackt/react-router#2404]
Hi.

I looked searched through the existing issues but found no answer. I was wondering what the reasoning for removing named routes was. I saw it as a great feature, especially as we performed a big URL re-ordering quite recently where I simply grepped for `to="routename"` and `to: "routename"` - which matched all uses.

Thanks!

**Comment by knowbody** [comment]
https://github.com/rackt/react-router/issues/1840

**Comment by mull** [comment]
Oh my, sorry! Can't believe I missed that one.
