### ISSUE TITLE
Document Clarification 

### ISSUE THREAD

**Issue by andrewbrntt** [rackt/react-router#2415]
I am new so please do not crucify me if this is nit-picking or not the correct place for this. I understand that current document is assuming you understand the absolute path syntax. I was just going over the docs and this part seemed to confuse me a little at first glance. I added the whole section just for context.

<h4>Decoupling the UI from the URL</h4>

It would be nice if we could remove the /inbox segment from the /inbox/messages/:id URL pattern, but still render Message nested inside the App -> Inbox UI. Absolute paths let us do exactly that.
`````
render((
  <Router>
    <Route path="/" component={App}>
      <IndexRoute component={Dashboard} />
      <Route path="about" component={About} />
      <Route path="inbox" component={Inbox}>
```````
     {/* Use /messages/:id instead of messages/:id */}
`````
Could this possible read just for better clarification
``````
     {/* Use /messages/:id instead of /inbox/messages/:id */}
```````     
   <Route path="/messages/:id" component={Message} />
      </Route>
    </Route>
  </Router>
), document.body)
``````
At first glance I did not see the difference which I could see being a pitfall for new users such as myself. This is a very low issue or just a recommendation just thought it may help out some people.

**Comment by knowbody** [comment]
@andrewbrntt sorry I don't understand what you mean. Would you like us to do the changes to the docs? or to the API? what is not clear? which part?

**Comment by andrewbrntt** [comment]
I apologize I just meant to update the comment to make the comment more clear as to what you are accomplishing. 
so this comment 
 {/* Use /messages/:id instead of messages/:id */}

would become

**Comment by andrewbrntt** [comment]
Do not know it it ping you went I edit the comment but I had accidentally hit enter before I was finished with my reply so it should make more sense now hopefully.

**Comment by knowbody** [comment]
Ok I see what you mean, but then the docs would be incorrect. This comment is saying how the `path` parameter should look like, not the URL in your browser.

What you are saying is how the URL would look like.

**Comment by andrewbrntt** [comment]
OK I see I guess I was still misunderstanding it. I will keep that in mind like I said was not entirely where to post/ask about this. Appreciate the help and being nice about it and not flaming me lol,

**Comment by knowbody** [comment]
@andrewbrntt I'm happy I could explain it. The issue is closed and it's fine like that, no need to delete.

But as I said, in the future try to ask the question on Reactiflux or SO, there is plenty of people there who can guide you through the React Router.
