### ISSUE TITLE
Plus sign decoded to whitespace in 1.0

### ISSUE THREAD

**Issue by mitsuhiko** [rackt/react-router#2426]
In react router 1.0 the plus sign now seems to be decoded to whitespace in paths.  The plus sign is only supposed to be decoded in query parameters, not in paths.  This is a regression from earlier versions.

**Comment by mitsuhiko** [comment]
Apparently this is a deliberate regression.  It was introduced here: d955d7a69052fd649b58d00bd75301a533f67e06

What's the logic behind this?

**Comment by taion** [comment]
:wave: 

This is related to https://github.com/rackt/react-router/issues/2407.

It's an easy fix but semi-blocked on a bigger change in https://github.com/rackt/react-router/pull/2421 that will lead to merge conflicts.

**Comment by knowbody** [comment]
I've seen the issue about it somewhere recently. Either here or on the history module. Can't find it now.

**Comment by taion** [comment]
Looks like @mjackson just fixed it in https://github.com/rackt/react-router/commit/fbc109c0218508a301caae36469c8fc5d70de5fa.
