### ISSUE TITLE
Fail to install react-router from git

### ISSUE THREAD

**Issue by mitsuhiko** [rackt/react-router#2427]
Since there is no rc4 release yet and there are blocking bugs in rc3 I tried to use the git version as direct dependency.  Unfortunately that currently does not build, reason being this error:

```
> react-router@1.0.0-rc3 postinstall /Users/mitsuhiko/tmp/node_modules/react-router
> node ./npm-scripts/postinstall.js


> react-router@1.0.0-rc3 build /Users/mitsuhiko/tmp/node_modules/react-router
> babel ./modules -d lib --ignore '__tests__'

ReferenceError: [BABEL] modules/AsyncUtils.js: Unknown option: /Users/mitsuhiko/tmp/node_modules/react-router/.babelrc.stage
    at Logger.error (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:205:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:346:16)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
    at Object.compile (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:62:12)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! react-router@1.0.0-rc3 build: `babel ./modules -d lib --ignore '__tests__'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-router@1.0.0-rc3 build script 'babel ./modules -d lib --ignore '__tests__''.
npm ERR! This is most likely a problem with the react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./modules -d lib --ignore '__tests__'
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mitsuhiko/tmp/node_modules/react-router/npm-debug.log
child_process.js:1389
    throw err;
          ^
Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at exec (/Users/mitsuhiko/tmp/node_modules/react-router/npm-scripts/postinstall.js:5:3)
    at /Users/mitsuhiko/tmp/node_modules/react-router/npm-scripts/postinstall.js:10:5
    at FSReqWrap.oncomplete (fs.js:95:15)
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "."
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! react-router@1.0.0-rc3 postinstall: `node ./npm-scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-router@1.0.0-rc3 postinstall script 'node ./npm-scripts/postinstall.js'.
npm ERR! This is most likely a problem with the react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./npm-scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mitsuhiko/tmp/npm-debug.log
```

I did not try yet, but I assume it's the same fix as for history: https://github.com/rackt/history/commit/8b053c2c34ecf31c2f2672e48ea5bccfbe437c2e

This is for the very similar bug here: https://github.com/rackt/history/issues/52

**Comment by mjackson** [comment]
What happens when you clone and run `node ./npm-scripts/postinstall.js` directly from inside the repo root?

I'm not sure which directory npm runs postinstall scripts from. I just assumed it would be the same directory as the package that was just installed. If not, it's probably having trouble finding the `postinstall.js` file.

**Comment by taion** [comment]
That's actually not the issue you're hitting.

The problem is that this build uses the global Babel install, and you have Babel 6 installed instead of Babel 5.

Can you downgrade your version of Babel?

**Comment by taion** [comment]
And we can't quite upgrade to Babel 6 for this project yet. It only just got released, and a number of the integrations we're using like babel-loader and isparta don't support Babel 6 yet - nor would it necessarily be helpful for this use case, since there'd be no guarantee that you'd have the correct Babel presets installed in your global environment.

**Comment by mitsuhiko** [comment]
You're right, babel5 makes it build. Unfortunately I guess you cannot really depend on it via git.  It now cannot find react-router even though it's built.  Need to figure out what's happening there.

**Comment by mitsuhiko** [comment]
Oh I see. It does not create a `lib` directory.  But it builds something.  Maybe it's executing in the wrong path.

**Comment by taion** [comment]
What specifically are you hitting? If I set up my `package.json` as:

```json
{
  "private": true,
  "dependencies": {
      "react-router": "rackt/react-router"
  }
}
```

and run `npm install` in a clean directory with just that package, the package appears to install and transpile just fine.

**Comment by mitsuhiko** [comment]
I set up the dependency with this:

```
"react-router": "git://github.com/rackt/react-router#b57580e93b4415838dbfece80d2e10300f4508f0",
```

But it would appear my version of Babel was too old.  Latest 5.8 fixed it.

**Comment by mitsuhiko** [comment]
Sorry for the noise.

**Comment by taion** [comment]
Yeah, unfortunately this is all a bit best-efforts. I usually just clone the repo and install from a local directory where I can control all the building myself rather than relying on the NPM hooks to build for me when installing directly from GH. It mostly works, but we can't make it totally reliable.

**Comment by taion** [comment]
(Not `npm link`, though - that will do awful things when using React)

**Comment by mjackson** [comment]
Thanks, @taion. You were right on.

**Comment by ondrejhanslik** [comment]
I can reproduce this issue. I have used an empty dictionary and also note that I didn't have `babel` installed globally. `postinstall` failed with "babel: command not found".
In the end I fixed it by installing `babel-cli` separately but I don't think it's a nice solution.

**Comment by taion** [comment]
We don't want to ship Babel with React Router, so I'm not sure there's anything we can really do there. Installing a transpiled package from GitHub instead of npm is just tricky.

**Comment by ondrejhanslik** [comment]
I completely understand. I am doing that only because there are fatal errors in the current (rc3) version and we have to work around it until there is a new official release.
