### ISSUE TITLE
Incorrect result from indexOnly isActive() with nested IndexRoute

### ISSUE THREAD

**Issue by lscspirit** [rackt/react-router#2432]
With a route configuration that contains an IndexRoute at the top level (**/**) and another IndexRoute nested within a child Route (**/child**), `isActive('/', {}, true)` returns true even when the current path is **/child**. 

I was expecting the correct behaviour would be for `isActive('/', {}, true)` to return false and `isActive('/child', {}, true)` to return true.

Below is a sample route:
```
  <Router>
    <Route path='/' component={ Home }>
      <IndexRoute component={ TopIndex }/>
      <Route path='content' component={ TopContent }/>                              
      <Route path='child' component={ Child }>
         <IndexRoute component={ ChildIndex }/>
         <Route path='content' component={ ChildContent }/>                           
      </Route>
    </Route>
  </Router>
```
And a example in CodePen to illustrate the issue: http://codepen.io/anon/pen/wKXjxE
I am using react-router 1.0.0-rc1.

**Comment by taion** [comment]
This was fixed in a later release.
