### ISSUE TITLE
On url change the Router triggers render on all new compoents

### ISSUE THREAD

**Issue by pfzero** [rackt/react-router#2440]
When the URL changes, Router will `setState` accordingly and thus the render method will trigger on all the child components that are used on the new route.
This can lead to issues with data not being fetched and the new components relying on that data might throw errors.
The application flow used by me is to listen to History changes and fetch the required data for the new route via Flux actions. Then, after data is fetched, render the app.

One solution for this would be to show some "loader" component and/or static components.

Another one, a hack actually, would be to extend the Router like this:

```javascript

Class CustomRouter extends Router {
    // so right when the url changes, prevent the router from updating, so that
    // flow of data should go through history.listen handler.
    // Then, when the render is called from that handler, update the app
    shouldComponentUpdate(nextProps, nextState) {
        if(nextState.location.pathname !== this.state.location.pathname) return false;
        return true;
    }
}

```

For now, I am not sure if this is a problem or the intended usage of the Router, but I think it's not the best solution to trigger the render on new components right away. At least, this should be configurable.

What do you guys think?

**Comment by taion** [comment]
That's the wrong flow. If you need to, the preferred way is to manage this with `onEnter` hooks or wrapper components around your route components.
