### ISSUE TITLE
Animations between sibling routes

### ISSUE THREAD

**Issue by bskimball** [rackt/react-router#2441]
RactCSSTransitions work when navigating from a Parent Route to a child route, but does not work when navigating between sibling routes. Is there a different method?

Also, in the animation example you should add transitionEnterTimeout and transistionLeaveTimeout.

**Comment by knowbody** [comment]
fixed the warning https://github.com/rackt/react-router/commit/e4a19e8773cafb8fad52d4a7e88b187aea2fdd7e

**Comment by taion** [comment]
This is by design because nothing is entering or leaving. You'll have to find another path to animate just changes on received props. Not a bug or feature request so I'm closing this.
