### ISSUE TITLE
isActive query comparison does not cater for removing parameters

### ISSUE THREAD

**Issue by mjt01** [rackt/react-router#2444]
Changing the query string triggers a route change as expected. I am using the `isActive` method to conditionally write a history entry (to avoid duplicate consecutive entries). `isActive` is resolving to `true` incorrectly due to a one-way comparison between the `query` and the `activeQuery`.

I identified the problem to be the use of `deepEqual` in `queryIsActive`. It is checking that all the properties in the `query` are present in the `activeQuery` and returns `true`, however there are additional properties in `activeQuery` meaning the queries do not match and should return `false`.

Here is what I believe is a failing test:
```js
Given "a pathname that matches a URL"
and "a query that matches multiple parameters"
When "a parameter is removed"
Then "it is not active"
```

I have been preparing a PR but figured i would start the discussion before submitting. Thoughts?

**Comment by knowbody** [comment]
Could you submit the PR with the failing tests?

**Comment by taion** [comment]
See https://github.com/rackt/react-router/pull/2386 which gives you a way to handle this (not in RC3 yet). The one-way comparison is the correct behavior to prevent false negatives.

**Comment by knowbody** [comment]
thanks @taion

**Comment by mjt01** [comment]
Thanks for the fast response, i just took rc4 for a spin now and still think we are missing something here. The code added certainly fixes an issue around `undefined` values but still does not seem to behave as I would expect.

To illustrate my problem i have pushed a failing test to [my fork](https://github.com/rackt/react-router/compare/master...mjt01:queryIsActive).

Is this any help? I had a fix that passed all the test cases, but need to update it against rc4 changes.

**Comment by taion** [comment]
You need to explicitly set any query keys you expect to be missing as `undefined`.
