### ISSUE TITLE
alternate-configuration unavailable?

### ISSUE THREAD

**Issue by LiaoSept** [rackt/react-router#2445]
```
error info:
Uncaught Error: Invariant Violation: The root route must render a single element

dependencies info:
react 0.14.0
react-router 1.0-rc3
babelify 7.2.0
babel-preset-react 6.0.15
babel-preset-es2015 6.0.15
```
see [alternate-configuration](https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md#alternate-configuration)
see https://github.com/rackt/react-router/blob/master/modules/Router.js#L88
see https://github.com/rackt/react-router/blob/master/modules/RoutingContext.js#L85

**Comment by LiaoSept** [comment]
`export default` can not be used `require` references

**Comment by G3z** [comment]
well actually you can :
```
const configure = [{
    path: '/',
    component: require('./components/pages/SamplePage').default
}];
```
