### ISSUE TITLE
Link `isActive` changes in animations

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#2452]
1. run `npm start`
2. open up to http://localhost:8080/animations/page1
3. click on `page 2`
    - observe that the links flash the wrong color

My git bisect skills are failing me right now to find where this changed, but it used to work.

We need:

1. a failing test case
2. in a separate commit, a fix.

I worry we've made some architectural change that is going to be difficult to back out of, but we absolutely need to be able to "pause the world" in render, so that `isActive` isn't stateful.

**Comment by taion** [comment]
When did this most recently work?

**Comment by ryanflorence** [comment]
React 0.14 caused it D:

https://github.com/rackt/react-router/commit/ff922fe6c6d4d193ca358ce9dd454b42706cd541

**Comment by ryanflorence** [comment]
looks like it only worked because of that old bug in 0.14 context. Not sure what to do about this yet, probably need a StaticContainer in user-land to freeze the world if you've got links with `active` in the animation, but otherwise everything is fine.

Not sure the router should be doing anything. Definitely need an animation guide though.
