### ISSUE TITLE
History listener returns location === null

### ISSUE THREAD

**Issue by halt-hammerzeit** [rackt/react-router#2461]
In my top level component I have

```
	static contextTypes =
	{
		history: React_router_prop_types.history
	}

	componentDidMount()
	{
		// Listen for changes to the current location. 
		// The listener is called once immediately.
		this.unlisten_history = this.context.history.listen(location => console.log(location))
	}

	componentWillUnmount()
	{
		// unmount history listener
		if (this.unlisten_history)
		{
			this.unlisten_history()
		}
	}
```

When I'm navigating my application it always prints `null` to the console (`location` is always null).

(your moderator is misbehaving and closed my previous issue)

**Comment by knowbody** [comment]
hi @halt-hammerzeit 

We are here to help, but you should respect the rules we have on the issue tracker. We've made an issue tracker **exclusively** for bug reports and feature requests.

It helps us to continue making React Router better and better.
If you have problems with React Router there are a lot of great people on [Reactiflux](https://discordapp.com/invite/0ZcbPKXt5bYaNQ46) who are always very helpful.
