### ISSUE TITLE
0.13.x changelog?

### ISSUE THREAD

**Issue by ljharb** [rackt/react-router#2463]
https://github.com/rackt/react-router/blob/v0.13.5/CHANGELOG.md doesn't seem to indicate any differences between 0.13.4 and 0.13.5. Is this an error?

**Comment by taion** [comment]
Yes - v0.13.5 adds some basic support for React v0.14 to offer users a forward migration path.

@ryanflorence @mjackson Should we manually edit the changelog to reflect this?

**Comment by ryanflorence** [comment]
Yes
