### ISSUE TITLE
URL params bug

### ISSUE THREAD

**Issue by lightAfire** [rackt/react-router#2466]
after update react-router from 1.0.0rc3 to 1.0.0 rc4
i found that 
```
<Route path="post_position">
    <IndexRoute component={PPHandler}/>
    <Route path="add(/:from_pid)" component={PPAddHandler}>
        <Route path="first-step/:type" component={PPFirstHandler}/>
    </Route>
</Route>
```
can only match the url have param from_pid like post_position/add/fekljfsdlkjf1kldf2/first-step/1

it can not match post_position/add/first-step/1

but  path="add/(/:from_pid)"   can match  post_position/add/first-step/1

is there something update with url params?

**Comment by lightAfire** [comment]
```
<Route path="post_position">
    <IndexRoute component={PPHandler}/>
    <Route path="add(/:from_pid)/first-step/:type" component={PPFirstHandler}/>
</Route>
```
use this can match both urls that have from_pid and not have from_pid.

**Comment by vvliebe** [comment]
you can use router like that:
```    
<Route path="post_position">
    <IndexRoute component={PPHandler}/>
    <Route path="add(-:from_pid)" component={PPAddHandler}>
        <Route path="first-step/:type" component={PPFirstHandler}/>
    </Route>
</Route>
```

**Comment by taion** [comment]
This should work. Hold on.

**Comment by taion** [comment]
Never mind - this is an error on your side. `:from_pid` is capturing `first-step`. I believe this is working as intended now because our matching is supposed to be greedy on a segment-by-segment basis.
