### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by stefaneg** [rackt/react-router#2467]
I have now spent an hour trying to get npm install to run on windows. It is somewhat hard to determine the exact cause, although the final line is:

C:\src\sample-projects\react-router-master\npm-scripts\postinstall.js:5
  execSync(command, { stdio: [0, 1, 2] })
  ^
TypeError: undefined is not a function
    at exec (C:\src\sample-projects\react-router-master\npm-scripts\postinstall.js:5:3)
    at C:\src\sample-projects\react-router-master\npm-scripts\postinstall.js:10:5
    at Object.oncomplete (fs.js:108:15)

There are multiple errors displayed in the console, first due to lack of python, and then due lack of MSBuild when building karma (which is worthy of another issue with that package).

**Comment by taion** [comment]
You're running an ancient version of Node. You should upgrade it.
