### ISSUE TITLE
Upgrade to Babel 6?

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2476]
I'm sure @ryanflorence is going to hate me for tacking more stuff onto this milestone, but there are little things we should figure out.

One of them is whether to upgrade to Babel 6. If I'm not mistaken, Babel 6 changes the transpilation of ES6 modules such that modules with a single default export no longer put that on `module.exports`. This means that, for users:

```js
var Link = require('react-router/lib/Link')  // This will only work with if we use Babel 5, not Babel 6
import Link from 'react-router/lib/Link'  // This will work in both
```

Do we think of or care about this? i.e. do we even consider this a breaking change? If we do, then this would be our last chance to upgrade from Babel 5 to Babel 6 before 2.x.

**Comment by timdorr** [comment]
I'm waiting on react-transform (it's downstream babel plugin) to go 6.0 compatible before upgrading myself. 

I think we can  hold off until some of these edge cases are worked out. The whole babel ecosystem is still updating to 6, so it's a bit too early for downstream projects to worry about this stuff.

**Comment by taion** [comment]
I'm inclined to agree with you, BTW. Given our timeline for releasing 1.0.0-final, I don't think Babel 6 is mature enough to jump to yet.

**Comment by ryanflorence** [comment]
Can we do some hackery to make it work in both?

```js
export default Link
export Link
```

**Comment by ryanflorence** [comment]
Actually, this shouldn't matter because `index.js` defines our public modules, people shouldn't be reaching into lib.

**Comment by taion** [comment]
Yup, if we don't support people importing from `react-router/lib` directly anyway, then this is irrelevant.

Otherwise the difference is:

```js
// Original
const Link = 3;
export default Link;

// Babel 5
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var Link = 3;
exports["default"] = Link;
module.exports = exports["default"];

// Babel 6 w/es2015 preset
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var Link = 3;
exports.default = Link;
```

The relevant part is the removal of the

```js
module.exports = exports["default"];
```

**Comment by taion** [comment]
Okay, closing this as irrelevant if we're not supporting importing from `lib/`.
