### ISSUE TITLE
activeClassName broken in certain situations with redux connect

### ISSUE THREAD

**Issue by sethen** [rackt/react-router#2483]
I didn't know exactly where to post this issue since it has to do with redux...  I believe it to be an issue with react router so I thought this was the most appropriate place to put it.  If not, let me know so I can post it in the redux issues.

This is sort of an interesting thing I have discovered, so I have made a repository to showcase what I am talking about at: https://github.com/sethen/redux-playground

The issue I am having is when specific components use redux `connect` to provide props to components.  This seems to break the `activeClassName` functionality on `Link` components when navigating from the initial page you start at.  For instance, if you were to navigate to `/todos` initially the link for `Todos` will work as expected with `activeClassName`.  However, navigating to another page `Todos` still stays highlighted and nothing else will become active.

You can see this in action by booting up the application and navigating to `app/js/components/global/Navigation.jsx` to see the code.  Now, if you take out `connect` and just export the component the functionality for `activeClassName` works as expected.

You can actually see the `activeClassName` working as it's supposed to by navigating to the `Todos` link at the top of the app.  I put in a `Link` component in the page to see if the functionality works in other places.  It turns out it does (which is what I would expect anyway).

Any thoughts here?

**Comment by taion** [comment]
See https://github.com/rackt/react-redux/blob/v4.0.0/docs/troubleshooting.md#my-views-arent-updating-when-something-changes-outside-of-redux. Consider using redux-router.

**Comment by sethen** [comment]
Ah, that makes sense.  Thanks a bunch.

**Comment by ryanflorence** [comment]
@gaearon seems like `pure: true` should be opt-in, least amount of surprise, and a premature optimization yeah?

**Comment by gaearon** [comment]
Nah,

Nobody will set it if it's opt-in.
Official Flux Utils also have this flag, and it's also opt-out there.

I already ranted about Link relying on context changes which are currently broken in React. ;-)

**Comment by taion** [comment]
@gaearon The flip side is our animation examples don't work without something like `StaticContainer`. Isn't redux-router an acceptable way to go when using RR + Redux anyway?

**Comment by gaearon** [comment]
@taion Can we use `{ pure: false }` in these examples?

**Comment by taion** [comment]
Which examples?

**Comment by gaearon** [comment]
I think I lost track of what you're asking :-). Can you explain again what is broken?

>The flip side is our animation examples don't work

I'm not sure what exactly you're referring to here. What I was saying that, whatever default behavior React Redux has, it can be turned off with `{ pure: false }`. Are we talking about different things?

**Comment by taion** [comment]
Ah - I'm referring actually to https://github.com/rackt/react-router/blob/master/examples/animations/app.js.

We transition out the old component using a `<ReactCSSTransitionGroup>` after the route transition. For the `<Link>`s to keep their old status, we have to wrap the old component in a `<StaticContainer>` to prevent the `<Link>`s from updating active status.

I end up with a very similar issue with Relay as well.

**Comment by gaearon** [comment]
Woah. I wasn't aware we're using something like that. Thank you for explaining, I get it now.

Specifically in case of links, can't we just pass them old info via context? Like a nested `<RoutingContext>` that has frozen values.

**Comment by liamm12** [comment]
This because `activeClassName` is updating outside of redux.

You can accomplish that by setting `pure` to false

`export default connect(mapStateToProps, null , null, { pure: false })(App)`

> Note that this will make your application less performant, so only do this if you have no other option

Or you can use `withRouter` from `react-router-dom`

`import { withRouter } from 'react-router-dom';`
`export default withRouter(connect(mapStateToProps, matchDispatchToProps)(App));`
