### ISSUE TITLE
stage: 0 is a dead option for Babel 6.x

### ISSUE THREAD

**Issue by xuqingkuang** [rackt/react-router#2485]
In the file
https://github.com/rackt/react-router/blob/master/.babelrc#L2

the dead stage option makes building broken with Babel 6, please fix as soon.

For more information please look https://github.com/babel/babel/issues/2572

**Comment by knowbody** [comment]
we are not using Babel 6 yet https://github.com/rackt/react-router/blob/master/package.json#L41-L42

**Comment by steevel** [comment]
No, you are not. But building OUR packages using babel6 is broken because of your .babelrc right now.

Solution: rm node_modules/react-router/.babelrc

**Comment by xuqingkuang** [comment]
@knowbody Are there any plan to support Babel 6?

In fact, the package was compiled succeed after changed .babelrc file.

**Comment by steevel** [comment]
@xuqingkuang Add exclude: /node_modules/ to your babel-loader section in module.loaders.

**Comment by knowbody** [comment]
@xuqingkuang see #2476

**Comment by taion** [comment]
https://github.com/rackt/react-router/issues/2485#issuecomment-155039559 is right, use `exclude: /node_modules/`. You should always be doing this anyway because there's no reason to re-transpile stuff from npm that's already transpiled.

**Comment by xuqingkuang** [comment]
Thanks @steevel @knowbody 

The problem is solved.
