### ISSUE TITLE
Is there a way to get an active class when we are on the link's route path?

### ISSUE THREAD

**Issue by DWboutin** [rackt/react-router#2490]
Hi,

How can i get a class "active" or other class name to specify when we are in a specific page?

Thank you

**Comment by knowbody** [comment]
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#active-class

**Comment by DWboutin** [comment]
I'm sorry! The docs aren't very clear about this, we just can find it in the Upgrade guide and it's a main functionality.

Thank you for your answer

**Comment by knowbody** [comment]
feel free to send the PR
