### ISSUE TITLE
Asynchronous Loading Fails with Babel 6.1

### ISSUE THREAD

**Issue by michaelahlers** [rackt/react-router#2495]
After updating Babel, loading child routes and components asynchronously (following patterns from the [huge-apps example](https://github.com/rackt/react-router/tree/master/examples/huge-apps) fails (even though breakpoints on callbacks were hit). Haven't tracked this down to a narrow set of causes, and I'll update this ticket as I do.

In the meantime, flipping from:

```javascript
// package.json
{
  // ...
  "devDependencies": {
    "babel-core": "^5.8.23",
    "babel-loader": "^5.3.2",
    "babel-runtime": "^5.8.24"
    // ...
  }
  // ...
}

// webpack.config.js
{
  // ...
  module: {
    // ...
    loaders: [
      {
        test: /\.js$/,
        exclude: modulesPath,
        loader: 'babel',
        query: {
          /* Enable ES7 features. */
          stage: 2,
          experimental: true,
          cacheDirectory: true
        }
      }
      // ...
    ]
  }
  // ...
}
```

To this:

```javascript
// package.json
{
  // ...
  "devDependencies": {
    "babel-core": "^6.1.2",
    "babel-loader": "^6.0.1",
    "babel-preset-es2015": "^6.1.2",
    "babel-preset-react": "^6.1.2",
    "babel-preset-stage-2": "^6.1.2",
    "babel-runtime": "^6.0.14"
    // ...
  }
  // ...
}

// webpack.config.js
{
  // ...
  module: {
    // ...
    loaders: [
      {
        test: /\.js$/,
        exclude: modulesPath,
        loader: 'babel',
        query: {
          /* Enable ES7 features. */
          presets: [ 'es2015', 'stage-2', 'react' ],
          cacheDirectory: true
        }
      }
      // ...
    ]
  }
  // ...
}
```

Effectively toggles between working and not.

**Comment by taion** [comment]
This isn't our issue, Babel 6 changed the way it transpiles modules with a single default export to no longer be CJS compatible.

**Comment by michaelahlers** [comment]
Grumble. Thanks for the quick response. Is a workaround possible?

**Comment by taion** [comment]
There's a few. You could explicitly do `module.default` when using it with `require`. You can also export with both `module.exports = ...` and `export default ...`.
