### ISSUE TITLE
getComponents returning no children

### ISSUE THREAD

**Issue by jabbrwcky** [rackt/react-router#2499]
I found that with 1.0.0-rc4 `getComponents` does not return named child components as properties of `this.props.children` but as direct properties instead.

Route definition (irrelevant parts left out):
```js
export default {
  component: require('../components/App'),
  childRoutes: [
    {
      getComponent: (location, cb) =>{
        cb(null, require('../layout/LoggedIn'))
      },
      childRoutes: [
        {
          path: 'selection',
          getComponents(location, cb) {
             require.ensure([], (require) => {
                cb(null, { content: require('./components/Selection') })
             })
          }
    ]
}

```

LoggedIn component:

```js
import { Reflux, React, Bootstrap }  from '../common'

export default React.createClass({
  render() {
    return(
      <div>
        {this.props.content} //works
        {this.props.children.content} //undefined
      </div>
    );
  }
});
```

`{this.props.content}` works, `{this.props.children.content}` (as used int the examples) is undefined.

Is the example code not up to date or is it my setup?

**Comment by taion** [comment]
This was changed in RC4 because the old way wasn't compatible with React v0.14; see the docs.

**Comment by jabbrwcky** [comment]
Thanks. The examples still use the old version though, which might be confusing.

**Comment by taion** [comment]
Which ones?

**Comment by jabbrwcky** [comment]
Hm, can't seem to find it anymore. Nevermind, maybe my browser overly eager to cache stuff... Evrything up to date as far as I can see.
