### ISSUE TITLE
Knowing which component triggered `onEnter`

### ISSUE THREAD

**Issue by jlongster** [rackt/react-router#2500]
The `onEnter` hook is called with just the routeState, which doesn't have any information about which component actually triggered the call. Let's say we have these routes:

```js
Route(
  { path: '/', component: App },
  Route({ path: 'foo', component: Foo, onEnter: handleEnter }),
  Route({ path: 'bar', component: Bar, onEnter: handleEnter })
)
```

In `handleEnter`, I don't have any obvious way to figure out if `foo` or `bar` triggered it. I could look at the last component in the `components` array of routeState, but this could be called anywhere from a deep tree. It seems like `onEnter` is meant to be used when the user wants to hardcode specific actions to run for a specific route component, but not for generic actions.

Actually, there does seem to be a way to do this that is not mentioned in the docs: **the `this` value of the hook will be the component instance**. So I can actually do `this.component` to get the component class, and call static methods on it. Is this intended? I would rather it be more explicit and just pass in the component that triggered it as the second argument.

If it is intended, it should certainly be documented.

Why am I doing this? This is for automatically fetching needed data generically.

**Comment by taion** [comment]
@jlongster What component instance? You mean the class? These hooks run before we call `createElement` on anything.

**Comment by knowbody** [comment]
@jlongster what if you `bind` some kind of *id* to your `handleEnter` function?

**Comment by ryanflorence** [comment]
`onEnter` won't have an instance since its called before rendering anything, there is no component instance yet.

> I would rather it be more explicit and just pass in the component that triggered it as the second argument.

There can be multiple components, or no component at all for a route, so `this` is the route, which gives you access to everything about it. You can either put your static methods on `this.component` or the route itself.

This hopefully illustrates how you could do it:

https://github.com/ReactTraining/advanced-react/blob/master/subjects/routing/solution.js
https://github.com/ReactTraining/advanced-react/blob/master/subjects/routing/lib/AsyncProps.js

**Comment by taion** [comment]
@ryanflorence 

You beat me to it. We should document this on API.md though - I don't see that part documented anywhere.

There's a hole here when using async components, though - you'd only see `getComponent`(`s`) on the route object and not the component itself. You can still identify the route, but you wouldn't necessarily be able to call anything on the component without jumping through hoops; conceptually this is a similar issue to why I added the `RoutingContext` customization for `react-router-relay` to support roughly the same thing..

**Comment by jlongster** [comment]
If I had this `onEnter` function:

```js
  function onEnter() {
    console.log(this);
  };
```

I get this in the console: 
<img width="407" alt="37e8849d-bb19-4821-b2b5-883b7342c4bd" src="https://cloud.githubusercontent.com/assets/17031/11040273/68b9f956-86d9-11e5-97c0-5792ceb688ad.png">

I am not interested in the user's component. I'm talking about the `Route` component. A `Route` component has to exist; I have to create one to give an `onEnter` hook to!

**Comment by taion** [comment]
Isn't that what you're looking for? Note that `<Route>` components are purely for ease of configuration - we convert them into plain route objects like the one you see above for routing purposes.

**Comment by jlongster** [comment]
Yeah, it is but it's not at all in the documentation. I didn't know if that was an accident or intended. I feel like it would be better to pass that object as the second parameter to `onEnter`.

@ryanflorence AsyncProps is cool, but if you are already using a central store we can just throw data in there. I'm experimenting with just hooking up automatic data fetching at the routing layer and not even having to wrap components. It feels nice because how you fetch data is different in the context anyway (server/client etc).

**Comment by jlongster** [comment]
Sounds like @ryanflorence confirmed that it's intended, not sure if you want to add it to the docs or keep it an undocumented feature. Not sure I understand the `RoutingContext` stuff you mentioned above @taion, sounds like a more complex use case than I'm familiar with. If there are problems with this it can just be an undocumented feature.

**Comment by taion** [comment]
Has to be intentional because why else would someone have written this code: https://github.com/rackt/react-router/blob/v1.0.0-rc4/modules/TransitionUtils.js#L5? XD

Would you be willing to submit a quick PR to write this up for our docs?

**Comment by taion** [comment]
The `RoutingContext` stuff is for the case where I need access to the actual component _class_ associated with the route object when doing data fetching on something like an `onEnter` hook when the route object uses an async component; this is necessary for Relay because the fragments live on the component class, but you can't just do `route.component` if the components are async.

**Comment by ryanflorence** [comment]
@jlongster `Route({ onEnter: createEnterHook(specificLoaderFunction) })` ?

**Comment by jlongster** [comment]
@taion done! #2501 

@ryanflorence Not sure what you mean? I'm actually playing with creating a higher-order `Route` component that automatically adds an `onEnter` hook that when run will fetch the data for that component.

**Comment by ryanflorence** [comment]
want to hop on discord?

**Comment by ryanflorence** [comment]
`longsterRoute({ load: someSpecificLoadFn })`

under the hood creates:

`Route({ onEnter: createLoader(props.load) })`

You know at the time of route definition your loader dependency, you don't need to store it on the route and then look it up again later.
