### ISSUE TITLE
useRoutes changes the meaning of history.listen

### ISSUE THREAD

**Issue by timdorr** [rackt/react-router#2502]
In `history`, the `listen` method is [for listening to when the location changes](https://github.com/rackt/history/blob/54c1943608a7019a37cf8f6e1c81ddc5809a648a/modules/createHistory.js#L63-L65). Pretty simple. 

However, in the router, `useRoutes` [changes this definition](https://github.com/rackt/react-router/blob/4a5ff49de76dad0bbb454d608c404cae38987d47/modules/useRoutes.js#L221-L245) to whatever it interprets the history state change as. Even worse, it changes the callback signature from `history`. 

There's nothing wrong with that. We should have some sort of event listener for when the router is done doing its routing. However, it makes the API tough to reason around, because if you create a `history`, attach a listener, and then get it back out of context/renderProps, it's now changed the meaning of the function you've *just* used. Yikes! 

What would likely make more sense is a separate method for listening to the route changes and leaving `history.listen` unaltered. @taion proposed `routerHistory.listenRoutes` in Discord, so that might be a good name for this.

**Comment by timdorr** [comment]
By the way, the reason this came up is for behaviors and libraries that want to perform some action before the state change. A `useRoutes`'ed history still has `listenBefore` on it, but the signature is different from the enhanced `listen`. 

So, consistency here would be good for the API health and would avoid some confusion for anyone wanting to use `listen`

**Comment by taion** [comment]
My vote would be to rename this method to `listenRoutes` and add a deprecation warning to `listen` (to be removed in v2 of course).

**Comment by mjackson** [comment]
Now that 1.0 has shipped is like to take another look at this API. I'm not
fond of the idea of using a listenRoutes method because that just
introduces more API we have to maintain. Instead, I think the existing
listen method could possibly be changed to conform with other use*
functions.

**Comment by taion** [comment]
I don't know if that makes sense. The routing history doesn't just invoke its callback with a different signature. It invokes its callback at a different _time_ - i.e. when all of the async routing stuff is resolved. Even if we merged the routing information onto the location object, I don't see how we could reconcile the question of the different callback invocation time.

**Comment by taion** [comment]
Questions of state aside, the difference is that one is a synchronous operation, while the other is an async operation that has some concept of possible failure. They're quite different.

**Comment by taion** [comment]
One more benefit to using `listenRoutes` instead of `listen`: this would allow `<Router>` to figure out whether the history already has routes set up, which would allow users to apply history enhancers after `useRoutes`. Currently this is impossible without replacing `<Router>` entirely.

**Comment by taion** [comment]
cc @jlongster @goatslacker

One implication is that right now, you can't actually hook into the routing state from outside of the `<Router>` itself. Something like alt-router or redux-simple-router as written do not have access to `listen` on the `useRoutes`-enhanced `history`, since `<Router>` creates that history, so you have no way to hook into the actual routing state changing (which happens after the `history`'s `location` changes - and potentially asynchronously after when async routing is in play).

**Comment by mariocasciaro** [comment]
@taion Agreed, I'm currently using `redux-simple-router` and I had to patch `react-router` (renaming `listen` to something else) to get everything working. This change is really needed IMO.

**Comment by mjackson** [comment]
I think we're now having the same discussion in #2614. We're all converging around the same idea, anyway. Let's discuss there.
