### ISSUE TITLE
Link documentation is lacking

### ISSUE THREAD

**Issue by afraser** [rackt/react-router#2520]
Hi all. I'm loving react router, but I just spent 30 minutes reading through the docs in the order they are written and was unable to find information about the Link prop `activeClassName` until I got to the changelog. Is this documented somewhere that I just haven't found yet? If not, it'd be swell if you could add it.

**Comment by knowbody** [comment]
If the documentation is lacking something please send the PR with suggested changes. `Link` is included in our public API hence it could probably be found in the API docs - [and that's where it actually is](https://github.com/rackt/react-router/blob/master/docs/API.md#activeclassname).

Github has also the search feature, it can help you search through the code, docs and issues.

**Comment by afraser** [comment]
Thanks, I didn't even see the API link. I tried searching the repo but apparently didn't try hard enough.

**Comment by knowbody** [comment]
:+1:
