### ISSUE TITLE
Run tests against Node

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2538]
The current test setup runs against a number of real browsers via BrowserStack, which is fantastic, but we currently don't test specifically against Node at all.

It would be good to explicitly test against Node, just to have explicit verification that SSR will continue to work.

**Comment by mjackson** [comment]
The tests currently need a large refactoring so they are smarter about
which environment they are running in. We couldn't run the existing tests
in mode without resorting to some hacks solution like phantom or jsdom,
neither of which I will use.

If you're interested in taking on this work, you may want to check out the
tests for the history library which are much smarter about the environment
they are running in and skip certain tests when they aren't actually able
to run.

**Comment by taion** [comment]
I agree with you in principle - in practical terms though I think it makes the most sense to just start with a different entry point for Mocha and e.g. only run the server rendering test (and maybe a couple of others).

**Comment by mjackson** [comment]
What I'm trying to say is I'd like to see a more comprehensive plan for refactoring our test suite than just a new entry point for node. If we split the test suite into two entry points, it will probably stay that way for a long, long time. Unless someone follows through and brings it all back together.

**Comment by taion** [comment]
I agree with the feature sniffing approach in general - we should use it to e.g. support IE9 tests on this repo. However, I think there are two important caveats here.

- Since we'd use Mocha directly for Node testing, we'd need a separate entrypoint anyway; there has to be a `tests.node.js` or equivalent, since `tests.webpack.js` would not be applicable.
- There's a difference between the IE9/&c. case on `history` where the tests in this repo for things like `<Link>` are not unsupported in that sense; they're actually just irrelevant. The sense in which we skip tests for `<Link>` on Node is not the same sense in which we skip the HTML5 history tests on IE9.
