### ISSUE TITLE
request: Add replaceState parameter to Router.onUpdate to match Route.onEnter

### ISSUE THREAD

**Issue by jimbolla** [rackt/react-router#2546]
Currently I have a lot of routes that look like:

    {
        path:      "new",
        component: Add,
        onEnter:   authorize({roles: [admin]}),
    },

Notice the authorize method. I have to pass that around to all the subroute configs and it's mildly annoying. My code would be a lot cleaner if I could do:

    {
        path:      "new",
        component: Add,
        authorize: {roles: [admin]},
    },

and then on the router be able to do:

    <Router roles={roles} onUpdate={(nextState, replaceState) => {
        /* authentication logic here, checking nextState for routes' authorize properties and then calling replaceState on fail */
        }/>

I haven't tested whether it does already or not, but also any custom properties set on the route should be available on the router state. I'd be ok with having to put any custom properties into a custom property such as:

    {
        path:      "new",
        component: Add,
        custom: {
            authorize: {roles: [admin]},
        }
    },

... but flat would be preferred.

**Comment by taion** [comment]
That won't work, I'm afraid - at least not with the same semantics. `onUpdate` gets called after the route matching is finally complete, at which point it's too late to replace the transition - and that's very much intentional, since it reflects the router actually updating once all the `onEnter` hooks have run.

You could in principle call e.g. `this.history.replaceState` in `onUpdate`, but it's not a global "enter any route" hook.

**Comment by taion** [comment]
See also #2547.

**Comment by jimbolla** [comment]
Well then what about adding a Router.onRouteEnter function that fires before any route's onEnter?

**Comment by jimbolla** [comment]
I don't think 2547 is relevant. It's the opposite of what I want. I'm trying to remove behavior from the individual routes and add a global authentication behavior at the router level.

**Comment by taion** [comment]
The idea is that you'd add an `onChange` hook to your top-level route, and dispatch all the logic from there.

The nice thing about doing it this way is that the `<Router>` is only used for state management on the client side - note that the actual route matching on the server API is much more minimal and just wants a location and routes.

**Comment by jimbolla** [comment]
Ok that makes sense. How can I help make that happen?

**Comment by taion** [comment]
You can contribute to the discussion and outline your use case on #2547. You can also submit a PR implementing the feature.
