### ISSUE TITLE
iOS 9 chrome back button not navigating back in history

### ISSUE THREAD

**Issue by kellyrmilligan** [rackt/react-router#2552]
App navigated as expected in safari, but in chrome on iOS the app only navigates forward properly. Tapping the back button almost always takes you back to the beginning of your session.

**Comment by timdorr** [comment]
Are you using a browser or hash history?

**Comment by kellyrmilligan** [comment]
Browser history

**Comment by kellyrmilligan** [comment]
And v13.3

**Comment by timdorr** [comment]
Do you mean 0.13.3? We're no longer developing on that version. Does this error occur in 1.0.0?

**Comment by kellyrmilligan** [comment]
I haven't had the chance to upgrade yet. I'll try and run one of the example apps and pull it up in chrome on iOS 9

**Comment by taion** [comment]
Okay, please let us know - we're not going to cut any more releases on v0.13.x, so any issues remaining there are just non-addressable. We've also more or less entirely re-written the usage of the history API since then, so things are likely to be quite different (and less buggy).
