### ISSUE TITLE
garbled example in readme file

### ISSUE THREAD

**Issue by WanderWang** [rackt/react-router#2553]
in ReadMe file ,there are some docs
```
const App = React.createClass({/*...*/})

...


<Router>
    <Route path="/" component={App}>
      <Route path="about" component={About}/>
      <Route path="users" component={Users}>
        <Route path="/user/:userId" component={User}/>
      </Route>
      <Route path="*" component={NoMatch}/>
    </Route>
  </Router>
```

I follow this example and write this code 
```
class App extends React.Component {

render(){

return (<div>Header</div>)
}


}
```

because of I miss ``` {this.props.children} ``` , I doesn't see ```User``` ```About``` in the browser , and it waste me 3 hours to find this bug

so, please point thie ``` this.props.children ``` in the ReadMe, please 

thanks !

**Comment by knowbody** [comment]
If you read the [introduction](https://github.com/rackt/react-router/blob/master/docs/Introduction.md#with-react-router) you can see that we point this out there.
