### ISSUE TITLE
Confused with this.props.children

### ISSUE THREAD

**Issue by leozdgao** [rackt/react-router#2554]
I have router like this:

    <Route path="/" component={App}>
      <IndexRoute component={Dashboard} />
      <Route path="info" component={Info}>
        <Route path="c/:cid" component={CompanyDetail} />
        <Route path="p/:pid" component={ProjectDetail} />
      </Route>
    </Route>

My Info component is connected by `react-redux`.

As change in react-router v1.0.0, `this.props.children` in Info component should represent CompanyDetail component if `/info/c/123` is reached. But I got this when I try to reach `/info`:

[![enter image description here][1]][1]

It seems the value of `this.props.children` in Info component is itself? And if I try to reach `/info/c/123`, also got this issue, Info component contains Info component itself which contains CompanyDetail component. Here is a sreenshot of react debug tool.

![untitled](https://cloud.githubusercontent.com/assets/8381024/11175004/d13c8c62-8c67-11e5-8de9-657663ca7bc0.png)

I try to reproduce it with a easy demo but it works normally. So it's very confusing to me about it. Any idea?

  [1]: http://i.stack.imgur.com/NvhSq.png

**Comment by leozdgao** [comment]
It caused by `{React.cloneElement(this.props.children, {...this.props})}`, and fixed by preventing copy `this.props.children` to children.

**Comment by shenders13** [comment]
Having the same problem with redux-auth-wrapper.

`const Authenticated = UserIsAuthenticated((props) => React.cloneElement(props.children, props));`

What do you mean by "and fixed by preventing copy this.props.children to children" Thanks!
