### ISSUE TITLE
Hash change event not fired in IE9

### ISSUE THREAD

**Issue by glennt** [rackt/react-router#2564]
When using IE9 (Version 9.0.8112.16421) the hash change in HashLocation is bound using  

if (window.addEventListener) {
        window.addEventListener('hashchange', onHashChange, false);
      } else {
        window.attachEvent('onhashchange', onHashChange);
      }

onHashChange is never fired when using addEventListener, however, when I change the code so it uses attachEvent instead it works.

**Comment by taion** [comment]
React Router v0.13.x is no longer supported. Please upgrade to React Router v1.0.0, which has many bug fixes around history integration.
