### ISSUE TITLE
routerWillLeave not leaving the actual route

### ISSUE THREAD

**Issue by juancabrera** [rackt/react-router#2575]
When I return `true` or a message/string on `routerWillLeave` it won't leave the actual route but the URL still will change. When I return `false` works as a expected, not changing the route at all and staying in the current route.

At the beginning I thought it was because I was using the `Class` syntax for the component and using `react-mixin` to 'convert' the mixing into a decorator. But then I pass the code to the regular `createClass` syntax but keep getting same issues.

This is the code for the actual component (removed most of the render jsx as isn't relevant in this case):

```javascript
import React            from 'react';
import Header           from '../Organism/Header.jsx';
import { Lifecycle }    from 'react-router';

var HomePage = React.createClass({
  mixins: [Lifecycle],

  routerWillLeave: function(nextLocation) {
    console.log('routerWillLeave', nextLocation);
    return 'you sure ?';
  },

  render: function() {
    return (
      <div>
        <Header />
      </div>
    );
  }
});


export default HomePage;
```

I'm using `React 0.14.0` and `react-router 1.0.0`

**Comment by taion** [comment]
Dupe https://github.com/rackt/react-router/issues/2537

**Comment by juancabrera** [comment]
@taion actually isn't. 

He is saying actually the opposite, for me `return false` works as expected.

What isn't working is the `return true` or `return 'message'`

**Comment by taion** [comment]
Load up the `transitions` example and give steps for a repro please.

**Comment by juancabrera** [comment]
I figured it out, had an old conf for `history` on the routes. Changing this:
```javascript
import createBrowserHistory from 'history/lib/createBrowserHistory';
const history = createBrowserHistory();
```

to this:
```javascript
import { createHistory, useBasename } from 'history'
const history = useBasename(createHistory)({
  basename: '/'
})
```

fixed it.

**Comment by taion** [comment]
That seems odd, but I'm glad you found a fix.
