### ISSUE TITLE
Query parameters: updating just the query string

### ISSUE THREAD

**Issue by rauschma** [rackt/react-router#2577]
If one keeps most of one’s state in the query string (vs. the path), one usually wants to update just the query string, without touching the path. This is how I did it – does that look OK?

```js
// In my custom onClick handler:
this.context.history.pushState({}, this.context.location.pathname, { someKey: someValue });

// Via a <Link>
<Link to={this.context.location.pathname} query={{selected: ''}}>Clear selected</Link>
```

Suggestion – mention here: https://github.com/rackt/history/blob/master/docs/QuerySupport.md

**Comment by taion** [comment]
This is being worked on as part of #2186. As mentioned in your issue on `history`, this is currently being worked on through https://github.com/rackt/history/pull/141.

**Comment by rauschma** [comment]
👍
