### ISSUE TITLE
Show a Component while another loads asyncroniously

### ISSUE THREAD

**Issue by fazo96** [rackt/react-router#2578]
The [getComponent](https://github.com/rackt/react-router/blob/5d2af4b03ee191852c4bbef3f0ded838db0a79db/docs/API.md#getcomponentlocation-callback) prop allows for asynchronious module loading (perfect for Code Splitting) but a way to show some other component while the real one loads would be nice.

Maybe support calling the callback for getComponent multiple times, for example the first time with a placeholder and then with the real module loaded asynchroniously

If I have time I'll try it out (maybe it already works) and see what happens

**Comment by taion** [comment]
That would be tricky to integrate - route matching is a one-shot operation right now.

You can handle this right now yourself with `history.listenBefore` and doing the proper handling in that hook to update state appropriately.

@ryanflorence had an example showing that: http://g.recordit.co/sfNcwkQAjX.gif but I'm not sure where the code is.
