### ISSUE TITLE
Clarification for Animation Example

### ISSUE THREAD

**Issue by tjcelaya** [rackt/react-router#2582]
I spent a bit of time trying to figure out why my usage of the animation example in my own code was behaving differently. The example uses `position: absolute` in order to achieve the effect of fading the new content in over the previous content and it would help to clarify that this is needed since both routes will temporarily exist side-by-side. I hadn't used the `ReactCSSTransitionGroup` before and thought the old children would be removed before the new children are added.

If necessary I could open a PR with this explanation added to the comment from #2508

**Comment by taion** [comment]
I think there's a general expectation that you have a basic familiarity with React CSS transitions and with using CSS for that example. It's really meant to show how to use React animations _with_ route transitions, not how to use React animations full stop. If you have a good idea for adding a line or two to clarify things, by all means that'd be welcome, though. I don't think there's particularly an issue here to track, though, so I'm closing this for now.
