### ISSUE TITLE
auth-with-shared-root refresh error

### ISSUE THREAD

**Issue by tinybug** [rackt/react-router#2585]
If I refresh 'http://localhost:8080/auth-with-shared-root/user/foo', I will get the page like this: 
![qq 20151122102319](https://cloud.githubusercontent.com/assets/3439875/11321649/1b6121a0-9103-11e5-8574-2ae8a5101f59.png)
It's no css effect.

**Comment by taion** [comment]
Works fine for me - double-check your setup.
