### ISSUE TITLE
Examples Babel 6 support

### ISSUE THREAD

**Issue by VladShcherbin** [rackt/react-router#2588]
Now, Babel 5 is used in the examples.

With Babel 6 some of them won't work, so the examples are misleading and confusing.

**Comment by taion** [comment]
Which specific ones are not compatible across both?

**Comment by beltyukov1** [comment]
https://github.com/rackt/react-router/tree/master/examples/huge-apps for sure, don't know about others.

**Comment by VladShcherbin** [comment]
yes, the `huge-apps` is broken with babel 6, didn't try the other ones.

**Comment by taion** [comment]
The right thing to do there is to use `module.exports` when using `require` - just don't use transpiled exports if we're not using transpiled imports. Either of you want to take a stab at PRing an update?

**Comment by timdorr** [comment]
The huge-apps one is fixable with just `import App from './components/App'` at the top and switching out the require for just `App`. Simple.

However, there's further breakage with some of babel's helpers. Namely, I'm getting `Uncaught TypeError: Cannot convert undefined or null to object` from the `_toConsumableArray` helper. Any ideas on that? Nothing stands out, but it looks like it happens [inside `matchRouteDeep`](https://github.com/rackt/react-router/blob/master/modules/matchRoutes.js#L82) when `matched.paramValues` is null. At least, that's the end result. I'm not sure of the source.

**Comment by taion** [comment]
Make sure you're just transpiling the example - no clue whether the rest of our code will work.

The only thing we should need to fix are the `export`/`require` consistency. To be compatible with both Babel 5 and Babel 6, we need to either:
- Explicitly do `require('./Component').default` to pull off the default export from a component module, or
- Export from `require`d modules with `module.exports = Component` rather than `export default Component`

**Comment by ryanflorence** [comment]
Who shipped module syntax without loader specs?! :P

I'd say do module.exports, .default is super ugly.

**Comment by taion** [comment]
They took out the backward compatibility shim in Babel 6. Under Babel 5, transpiling

```js
export default Component
```

to CJS would set `module.exports = Component` (and in general for the "single default export" case).

The default ES2015 module to CJS transform on Babel 6 no longer does this, which is why that example in particular breaks.

**Comment by timdorr** [comment]
Fixed that in 4c9364e.

**Comment by taion** [comment]
Unfortunately it's a bit worse than that. All of e.g.

- https://github.com/rackt/react-router/blob/4c9364e667d510a8ddece8fe7da546a317cc8825/examples/huge-apps/routes/Calendar/index.js#L5
- https://github.com/rackt/react-router/blob/4c9364e667d510a8ddece8fe7da546a317cc8825/examples/huge-apps/routes/Calendar/components/Calendar.js#L22

Need to be updated. :cry:

**Comment by timdorr** [comment]
No worries. I can't get that stuff too. Give me just a bit.

**Comment by taion** [comment]
Oof. Yeah - was hoping one of the people reporting the issue would have fixed it.

**Comment by timdorr** [comment]
OK, updated in 47bd66c now. Of note, there is no equivalent to `require.ensure` in ES6, but we weren't really using it for any true code splitting anyhow.

**Comment by taion** [comment]
That's not quite right - `require.ensure` is a webpack thing that actually powers the code splitting and causes the chunks for those components to be loaded as required. The point of the `require.ensure` there was to actually exhibit the code splitting; https://github.com/rackt/react-router/commit/47bd66c9af8540f63654ab3d3cc50ea5abad7448 removes that entirely, which is not what we want.

**Comment by timdorr** [comment]
OK, un-pushed that change.

Well, we either have to remove all ES6 from that example, as it's not possible to code split with import/export, or we have to use `require().default`. Either or. I'm heading to bed shortly, so someone else can get it or I can try to get to it tomorrow.

**Comment by SimenB** [comment]
Webpack 2 also includes support for `System.import` which supports code splitting, if you'd like to encourage that instead. While it was taken out of ES6, it's more idiomatic than `require.ensure`.

https://github.com/webpack/webpack/tree/master/examples/code-splitting-harmony

**Comment by timdorr** [comment]
IIRC, we're waiting on webpack 2 for some other changes as well, so I imagine we can update to `System.import` at that time. For now, since it's still in beta, we'll have to keep to whatever is supported by webpack 1.

**Comment by taion** [comment]
babel-loader didn't work w/webpack 2 yet last I checked anyway - for a runnable example, we'll have to stick to webpack 1 for now.

**Comment by taion** [comment]
Anyway, in the interest of consistency and to minimize confusion, I've updated the huge-apps example.

That said, if you're using the React Router examples as a guide to Babel, I'm not sure I can recommend that course of action.

**Comment by timdorr** [comment]
We've cleaned up the examples for babel 6 now. When we get around to using babel 6 for building the project, that may warrant another refactor. But it looks like it's a combination of upgrading babel and webpack until that happens. For now, it should work on both versions of babel.

**Comment by GreenGremlin** [comment]
> However, there's further breakage with some of babel's helpers. Namely, I'm getting Uncaught TypeError: Cannot convert undefined or null to object from the _toConsumableArray helper. Any ideas on that? Nothing stands out, but it looks like it happens inside matchRouteDeep when matched.paramValues is null. At least, that's the end result. I'm not sure of the source.

@timdorr, this is now also happening in Babel 5.8.35 (but not in 5.8.34). I'm not versed enough in Babel's code to know why, but here is the [diff for 5.8.35](https://github.com/babel/babel/compare/a2b5d5fd2d821d447434fb316eda58d8a85fb3d2...0dcb25b79a1500d1670550be5521ce31638344e1).

Is it considered invalid to spread a null variable?

**Comment by GreenGremlin** [comment]
Hmmm... maybe that's the expected behavior.
https://phabricator.babeljs.io/T934
