### ISSUE TITLE
Clarify createHashHistory in Changelog

### ISSUE THREAD

**Issue by thenickcox** [rackt/react-router#2592]
I'm open to this being immediately closed with the tag "RTFM," but I'm coming off of a day and a half upgrading a medium-ish app (21 routes, 85 components, 23 stores, etc.) to the new router and React 0.14, and I had a lot of pain until I re-read (for the 30th time) the docs on [locations](https://github.com/rackt/react-router/blob/master/CHANGES.md#locations). Here's the part that really threw me:

> If you do not specify a history type (as in the example above) then you will notice some unusual behaviour after updating to 1.0.0. With the default hash based routing a querystring entry not defined by  yourself will start appearing in your URLs called _k. An example of how it looks is this: ?_k=umhx1s

I saw that query string, so I thought, "okay, that _is_ expected." What I found, however, is that without including `history` in the top-level `<Router />`, all of my 0.13-compatible routes broke, and simplifying it to a minimal test case (based on my app) was just not working:

```jsx
  <Route path='/recent-activity' component={App}>
    <IndexRoute component={RecentActivityHandler}>
      <Route path='plagiarism' component={PlagiarismHandler} />
    </IndexRoute>
  </Route>
```

Here, going to `/recent-activity/plagiarism` failed silently. Adding in the history, however, made it work as expected.

I think my issue is with the wording "you will notice some unusual behaviour" (British spelling notwithstanding). It's really possible that my test case wasn't working for another reason, but I think that if not including history breaks the 0.13-compatible routes entirely (it may not, and I may have missed something else), there should be a bigger warning in that section. 

If it's agreed, then I'm more than happy to take a stab at it.

**Comment by taion** [comment]
I'm surprised the routing configuration you have above works at all, with any configuration. It looks incorrect to me - route matching terminates once we hit an index route. I'd expect that to be written as

```js
  <Route path='/recent-activity' component={App}>
    <Route component={RecentActivityHandler}>
      <IndexRoute path='plagiarism' component={PlagiarismHandler} />
    </Route>
  </Route>
```

Can you verify that it's just the change of `history` that makes the pattern you have work? There's something really weird going on if so.

**Comment by thenickcox** [comment]
Sorry, I shouldn't try to file issues right before bed. I think I meant

```jsx
<Route path='/recent-activity' component={App}>
    <IndexRoute component={RecentActivityHandler} />
    <Route path='plagiarism' component={PlagiarismHandler} />
  </Route>
```

**Comment by taion** [comment]
Well, it's hash history, right? So it'd be `#/recent-activity/plagiarism`, not `/recent-activity/plagiarism`.

And sorry, in the above it would be:

```js
  <Route path='/recent-activity' component={App}>
    <Route component={RecentActivityHandler}>
      <Route path='plagiarism' component={PlagiarismHandler} />
    </Route>
  </Route>
```

**Comment by thenickcox** [comment]
Oh, so in that case, do `<Link />`s need to actually route with the `#` in them? Like `<Link to='#/recent-activity/plagiarism' />`?

If you're updating from 0.13.x to 1.0.0, then hashes will _definitely_ break your routes in that case, right? So it's not so much that the behavior will be "unusual," as just that you have to either use history or add the `#` into all your links? Or am I misunderstanding?

**Comment by taion** [comment]
No, `<Link>` doesn't need the hash in the path.

However, if you're hitting the path from your browser, you'd need the URL to have the hash. It's just like hash history v proper history on v0.13.x.

**Comment by thenickcox** [comment]
Okay, I guess that clears it up.

Thanks a lot for your help, and thanks a lot for your work on this library.
