### ISSUE TITLE
Nested routes doesn't work

### ISSUE THREAD

**Issue by pistou** [rackt/react-router#2593]
Hey,
I made an [issue onStackOverflow](http://stackoverflow.com/questions/33891194/react-router-not-displaying-component)

Seems like **nested routes** doesn't work on `react-router v1.0.0`.

This doesn't work:
```
<Router>
    <Route path="/" component={HelloWorld}>
        <Route path="about" component={About} />
    </Route>
</Router>
```

This works:
```
<Router>
    <Route path="/" component={HelloWorld}/>
    <Route path="/about" component={About}/>
</Router>
```

**Comment by chentsulin** [comment]
In nested routes, `About` Element will become `this.props.children` in your `HelloWorld` Element

**Comment by pistou** [comment]
Ok I figured it now.
Thanks for enlightenment
