### ISSUE TITLE
react-router-1.0 forces react-0.14?

### ISSUE THREAD

**Issue by dendril** [rackt/react-router#2595]
Hey guys,

I did a complete migration to react-router 1.0 for a personal project but once I consider my work finished, I found these 2 lines in the package.json (after an NPM throws the error " The package react@0.13.3 does not satisfy its siblings' peerDependencies requirements!"):

```
    "react": "^0.14.0",
    "react-dom": "^0.14.0",
```

I'm using react 0.13 and want to continue using it for some time before migrate to react 0.14.

Suggestions?

**Comment by timdorr** [comment]
1.0.0 was built with React 0.14 and only that version. There is no way to use it with React 0.13. You will have to upgrade your project to use React 0.14 to use Router 1.0.0. Luckily, there isn't really any major breaking change in 0.14, so your upgrade path shouldn't be too difficult.

**Comment by taion** [comment]
Upgrading to React v0.14 is significantly easier than upgrading to React Router 1.0 (:
