### ISSUE TITLE
npm-scripts/postinstall.js hangs on CI builds

### ISSUE THREAD

**Issue by DiogoDoreto** [rackt/react-router#2598]
Hello! 

Currently I'm unable to automatically build my projects because it is hanging on postinstall.js file. Here are the last lines of log:

```
npm info postinstall source-map@0.5.3
npm info postinstall react-router@1.0.0
npm info install js-base64@2.1.9
npm info linkStuff combined-stream@0.0.7
npm info build /drone/src/.../node_modules/webpack-dev-server/node_modules/express/node_modules/accepts

> react-router@1.0.0 postinstall /drone/src/.../node_modules/react-router
> node ./npm-scripts/postinstall.js
```

I left it running for more than 1 hour and it doesn't continue.

Do you really need to build this way? Why don't you run build on prepublish (`"prepublish": "npm run build"`)?

**Comment by taion** [comment]
It's best-efforts support for people installing the package from GitHub.

What's your CI environment? Can you reproduce this issue locally?

**Comment by DiogoDoreto** [comment]
I've tried automatic build from tutum.co and the hosted version of drone.io

Unfortunately it's only hanging on my CI. Locally it works as expected.

**Comment by taion** [comment]
That looks like a problem with your CI environment, then. Not sure what we can do if `fs.stat` doesn't work on Tutum.
