### ISSUE TITLE
[doc] transitionTo / pushState outside of component

### ISSUE THREAD

**Issue by muraveill** [rackt/react-router#2601]
Hello,
In the previous versions of the router, I used to 'router = Router.create()' an instance of it, then store it, then access it as in 'router.transitionTo(...)'
Now with the new API and the minimal documentation, I cannot find a way to transition to another page outside of a component (i.e. without the History mixin). 
For instance I have some Service class that does REST calls, and on success will transition to another page.
Please document it, as well as the difference between pushState, replaceWith, or whatever names that I could never find a definition of.

**Comment by knowbody** [comment]
Have a look at the [CHANGES](https://github.com/rackt/react-router/blob/master/CHANGES.md)

**Comment by muraveill** [comment]
I just read it a thousand times before writing here, which is why I opened an issue out of desperation.

**Comment by knowbody** [comment]
@muraveill as we have a rule that we keep an issue tracker for bugs and feature requests only, please ping me on Discord and I will explain how to do it.

As far as I know we are going to rewrite the docs so they are more clearer and easier to understand.
