### ISSUE TITLE
Clarification of Link 'hash' key documentation

### ISSUE THREAD

**Issue by naemono** [rackt/react-router#2605]
I'm been struggling and struggling with making hash links (anchor links) function properly with react-router.

Full example source here https://github.com/naemono/bootstrap-carousel-react

With a simple router config of this, history set to 'history/lib/createBrowserHistory'

```
render((
  <Router history={history}>
    <Route path="/" component={App}>
    </Route>
  </Router>
), document.getElementById('main'))
```

A div defined by this in src/views/Marketing.js:

```
<div id='marketing'>
```

And a link defined in navbar (src/views/NavBar.js) like so:

```
<li><Link to='/' hash='#marketing'>Marketing</Link></li>
```

It just doesn't work.  The featurette link right after it works fine as this:

```
<li><a href="#featurette">Featurette</a></li>
```

I don't know if I'm mis-reading the documentation, or it's just broken, but any clarification would greatly help.

I am aware that SO is the proper place for this type of question, and there have been a number of them, but they all mention changing the history from a hashhistory, which I've already done.

Thanks for any help you can provide, I'll be happy to give you a PR for the docs once I can understand the proper way to get this functional.

**Comment by taion** [comment]
Doesn't work in that it doesn't scroll to the anchor? That's not properly supported right now: https://github.com/rackt/react-router/pull/2233

**Comment by naemono** [comment]
Thanks @taion.  I wasn't aware of that.  The docs don't mention that it's not supported right now.

Do you think some clarification here is in order:

https://github.com/rackt/react-router/blob/master/docs/API.md#link

If so, I can get you a PR to make that more clear.

Thanks.

**Comment by taion** [comment]
Yes, I'd appreciate that - just add a note that React Router currently doesn't do any scroll position management (for now it'd be in scroll-behavior, but I don't handle scrolling to anchors there either).
