### ISSUE TITLE
isActive should not be on history

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2606]
It'd be a cleaner API - lets us keep the API to `history` stateless, and "active" state does belong naturally to the location object.

**Comment by taion** [comment]
If we have a concept of a "routing location" that supports `isActive`, we can also put `routes` (and `params`, but keep the current injection) on that `location` object.

**Comment by mjackson** [comment]
I'd like to keep location objects as simple as possible (i.e. not add a bunch of methods that make them impossible to serialize). Also, the current design of location objects is analogous to `window.location` which doesn't have an `isActive` method.

**Comment by taion** [comment]
Fair enough there - the issue is more that it's on `history`, which is otherwise stateless and doesn't provide any way to read information about the current location other than by listening.

**Comment by mjackson** [comment]
I agree it's a bit messy. `isActive` should basically be just a utility method like `isActive(route, currentState)`. Then it has everything it needs in order to say whether or not a route is active.

**Comment by taion** [comment]
I'm re-opening this, then.

**Comment by taion** [comment]
Route matching is a property of the `history` object, though - so perhaps this should be `history.isActive(locationSpec, currentLocation)`.

**Comment by taion** [comment]
Fold this into https://github.com/rackt/react-router/issues/2614 as well.
