### ISSUE TITLE
option for stopping propagation

### ISSUE THREAD

**Issue by jonathanong** [rackt/react-router#2607]
i have nested "links" (not really, but the container is clickable and so is a link within it). can we add an option to make `<Link />` stop propagation? maybe something like:

```jsx
<Link to='/user/1' stopPropagation={true} />
```

i can make a PR if we can agree on an API

**Comment by taion** [comment]
Add an `onClick` handler and call `e.stopPropagation()` yourself.

**Comment by minardimedia** [comment]
not working

**Comment by Ericky14** [comment]
Why did you delete my comment? This solution does not work...
Calling `e.stopPropagation()` does not stop the event from bubbling up.

**Comment by pshrmn** [comment]
@Ericky14 I can't comment on the content of your original comment because I did not see it, but this issue was closed two and a half years ago. If you are looking for help, re-opening dead issues is not the way to get it; I would recommend asking on StackOverflow or Reactiflux.
