### ISSUE TITLE
Document callback parameters for `match`

### ISSUE THREAD

**Issue by Download** [rackt/react-router#2622]
I am trying to implement server side rendering, so I'm reading [the ServerRendering documentation](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md) with much interest.

I have trouble with the three parameters of the callback function: `error`, `redirectLocation` and `renderProps`. I am not sure what these parameters look like.

The documentation gives us a glimpse. From the example we can see that `redirectLocation` is apparently an object with at least two fields: `pathname` and `search` and `error` apparently has a field `message`, but I have no idea if this is complete or what else is there to be found.

Looking at [the source for `match`](https://github.com/rackt/react-router/blob/master/modules/match.js), we see that it delegates to `history.match`, which is where I'm sort of stuck on finding details. The `history` object that should have the `match` function on it is created using `createMemoryHistory`, which in turn seems to use `createHistory`... So I'm looking through [the source code of the History project](https://github.com/rackt/history) but I can't find the source for the `match` function anywhere.... In a desperate attempt I cloned the entire project and did a text-search through it but I still can't find the definition of the `match` function anywhere...

Could anyone that does know this code either point me to the source where I can see what shape the parameters of the callback can take, or even better, expand the docs for ServerRendering to include details on these parameters? As it stands I now have to resort to trial and error to figure out what these parameters look like.... Which in the case of `error` is quite tricky as I have to force an error to occur and I have no idea how to go about that.

**Comment by taion** [comment]
Hey, unfortunately we know that we need to revamp the docs for clarity. For the time being, all of our errors are just JS `Error` objects, `redirectLocation` is just a `Location` object (https://github.com/rackt/react-router/blob/master/docs/Glossary.md#location), and the `renderProps` are intended to be largely opaque to you and should just go into the `RoutingContext`.

Is there something missing from the example that's making it difficult to follow? Seems straightforward enough.

**Comment by Download** [comment]
The example is clear for it's purpose (explaining the basic principle). The problem comes when we try to build an implementation and think about corner cases. With just examples it's hard to know how complete the coverage is. E.g, in the example, it is accessing `pathname` and `search` properties on the `redirectLocation` object, but it's not clear whether those are the only two properties that that location object has or not and if not, what the other ones are.

> redirectLocation is just a Location object.

But in this document, that is only implied indirectly through it's name. I'm still learning React and React-Router, and hadn't once looked at the History project yet (there was no need). It would be great if this single line of text (including the link) could be added to that page. I would have read it and it gives me exactly the kind of background info that I'm looking for when trying to implement it.

My question (after reading the server rendering docs):

*What is this `redirectLocation` object and does it have other properties besides the two I see here?*
The answer: It's just a Location object. I click the link and see:

```js
Location = {
  pathname: Pathname;
  search: QueryString;
  query: Query;
  state: LocationState;
  action: Action;
  key: LocationKey;
};
```

That makes a big difference in quickly finding the relevant info. 

Of course to you this is like, duh! But for newcomers this is exactly the info we are unsure about  :)

**Comment by taion** [comment]
That makes sense if you care about the edge cases. I don't have an ETA for a major docs revamp right now - it's one of those things that are always hard to coordinate for an open source project (even a small and active one like React Router), but we're well aware of this sort of issue.

**Comment by Download** [comment]
As I said, just that single line of text would help tremendously... I don't see a need for a major doc revamp from my end. The basics are there and pretty solid (it's one of the things I like about this project, the docs are pretty good). I think fine-tuning of what's here now based on user feedback and incoming issues might be all that's needed.

**Comment by taion** [comment]
Makes sense here - do you want to PR that?

**Comment by Download** [comment]
I knew you were going to ask that!  

Ok I'll give it a shot  :)
