### ISSUE TITLE
Don't touch the URL (for React based widgets)

### ISSUE THREAD

**Issue by ibc** [rackt/react-router#2628]
Just wondering if `react-router` can also be used within complex/big widgets designed to run in any 3rd party website (by adding a single `<script>` tag or whatever...).

In that scenario I do not want that my complex widget mangles the site URL, but at the same time my widget may include different subviews, etc, and I'm fully interested in having a routing framework.

Is that posible with `react-router`? or is it just designed for entire website/apps?

**Comment by timdorr** [comment]
If you use a hash history, it should work just fine. If the server can be configured properly, a browser history should work too. I'm doing this exact thing right now and it works fine.

**Comment by taion** [comment]
`createMemoryHistory` for doing everything in-memory is useful too. The problem is that e.g. back button, &c. won't work, but that might be what you want anyway.

**Comment by ibc** [comment]
Thanks, very useful info.

@taion: yes, I don't care the browser back button because a widget running in an external website should not manage the browser history.

**Comment by taion** [comment]
Yeah, sounds like you want `createMemoryHistory` then.
