### ISSUE TITLE
Move history from peerDependencies to dependencies

### ISSUE THREAD

**Issue by dbkaplun** [rackt/react-router#2637]
`history` should be moved from `peerDependencies` to `dependencies` for two reasons.

1. When I `npm install --save react-router`, `history` gets installed alongside, which is very annoying since my project doesn't use `history` anywhere
2. It is a dependency of react-router, not a peer dependency, as it is not optional

Please fix!

**Comment by taion** [comment]
We deliberately moved away from that. See discussion at https://github.com/rackt/react-router/issues/2211 and the similar.

I'm not sure where you got the impression that "peer dependency" somehow implies "optional", because it doesn't.

**Comment by dbkaplun** [comment]
My app shouldn't depend on `history` when I don't use it at all. Doesn't make sense to me. Sorry, I don't like this.

**Comment by taion** [comment]
There were something like 4000 words of discussion on that issue that led to this conclusion. Did you really read the entire thread in the five minutes it took you to reply to this issue?

We made a careful consideration of the tradeoffs involved before coming to this conclusion. Please do us the courtesy of reading through the extensive linked discussions before making shallow, unconsidered throwaway assertions like

>My app shouldn't depend on `history` when I don't use it at all. Doesn't make sense to me. Sorry, I don't like this.

**Comment by dbkaplun** [comment]
I did in fact read the discussion, I'm a fast reader. I simply happen to think the decision was made in a fervid, 3-day haste and packaging concerns were not considered at all.

If `react-router` *depends* on `history` it should *depend* on it. Or are you saying that `history` *must* be included as a `peerDependency`? That there is no way to get `react-router` to work without it included as a `peerDependency`? I don't think that is the case.

**Comment by taion** [comment]
It depends on history in the same way that it depends on React.

**Comment by dbkaplun** [comment]
Exactly. But *my app* depends on react-router in the same way it depends on React, not in the same way as history! This is what `peerDependencies` is all about.

**Comment by taion** [comment]
The discussion in the linked issue covers exactly why your assertion above is incorrect - the implicit default history is a convenience thing and not really a core part of our API, and the alternative is worse in the typical encouraged use case and leads to confusion with possible version mismatches.

**Comment by dbkaplun** [comment]
@taion please explain to me why my app needs to depend on `history` when it doesn't use `history` at all?

**Comment by vasklund** [comment]
Isn't this kinda the same as e.g. when you set up an Express app? In most cases you'd need to include body-parser, cookie-parser etc. in package.json, then you feed them into your express app something like:
```
var bodyParser = require('body-parser');
...
app.use(bodyParser.json());
```

My understanding is that peerDependencies kinda do the same thing, without you needing to write any code, but still giving you the flexibility to decide which version to include. From that understanding at least it seems to make sense.

**Comment by taion** [comment]
The reason is pretty much that logically the `<Router>` just wraps a history from `history` for you. As a convenience we offer `createHashHistory()` as a default, but you're not really supposed to use it.

If I had my druthers, I'd actually get rid of that default.
