### ISSUE TITLE
Type annotations for URLs

### ISSUE THREAD

**Issue by jjvattamattom** [rackt/react-router#2641]
I guess having type annotation on route parameters is helpful for two reasons.

A request for `/users/staff` hits the first second route instead of the third.

```
<Route path="/users" component={}/>
<Route path="/users/:id" component={}/>
<Route path="/users/staff" component={}>
```

Having annotations like `<Route path="/users/<id:int>"/>` could have prevented this.

I have to arrange stuff like:

```
<Route path="/users" component={}/>
<Route path="/users/staff/x" component={}>
<Route path="/users/staff/y" component={}>
<Route path="/users/staff/z" component={}>
<Route path="/users/:id" component={}/>
```

Also I have to manually check the type of the params. I have a component for `/users/:numericId`, I have to check if numericId is an integer, and to redirect to 404 page if its not.

The router should not match `/users/:numericId` if `/users/apha` were provided.

As an example of type annotations for route params, Flask (server-side Python web framework) allows this:

```
@app.route('/user/<username>') # string
@app.route('/post/<int:post_id>')
@app.route('/post/<float:post_id>')
@app.route('/post/<path:post_id>')
```

**Comment by taion** [comment]
https://github.com/rackt/react-router/issues/2286 starts exactly from the Flask thing, although we're at a bit of a different place now.
