### ISSUE TITLE
Passing data through RoutingContext?

### ISSUE THREAD

**Issue by zackify** [rackt/react-router#2644]
I am server rendering dynamic routes and picking it back up on the client. I'm unsure if what I'm doing is considered bad practice. My server rendering html looks like this:

```js
let html = renderToString(<RoutingContext {...renderProps} params={{initialState}} />)
```
I'm also setting the initialState on the window object. Inside of my top level component I am doing:

```js
class Accounts extends React.Component{
  componentWillMount(){
    this.store = createStore(reducers, typeof window != 'undefined' ? window.__INITIAL_STATE__ : this.props.params.initialState)
  }

  render(){
    return (
      <Provider store={this.store}>
        <Body />
      </Provider>
    )
  }
}
```
Grabbing the state on the server side and client side. Is there anything wrong with this? It may be my fault for not looking hard enough, but I couldn't find if `params` was actually meant for something like this.

**Comment by taion** [comment]
Take a look at the async-props repo, which covers this use case.

**Comment by zackify** [comment]
Thanks.
