### ISSUE TITLE
Rename `RoutingContext` to `RouterContext`?

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#2650]
Since we now export just a `router` to context, maybe the component should be named `RouterContext`, also seems like a good precedent when React context only allows one export to name the components that export a context to be named after the context.

**Comment by mjackson** [comment]
:+1:

**Comment by ryanflorence** [comment]
k, making a PR

**Comment by XescuGC** [comment]
Be careful, if you merge this to `master`, not everyone would have the new features, some one with the 1.0.1 (current) version will get mad reading the documentation ( like me :smile: ) because the `RouteContex`t does not exits and then `React` will complain with a weird exception.

**Comment by timdorr** [comment]
@XescuGC That's a good point, as we currently don't have a separate docs site (working on it! :smile:). We can probably do something similar to what kubernetes does, where they include [a warning for all docs on master](https://github.com/kubernetes/kubernetes/blob/master/docs/design/networking.md) that links to the latest release branch. I don't know how they have that set up (presumably they have some sort of automation), but I can look into it.

For now, here's a link you can use: https://github.com/rackt/react-router/tree/v1.0.1/docs

**Comment by ryanflorence** [comment]
FYI we always push a `latest` tag, I'm going to update the link on the README.md

**Comment by XescuGC** [comment]
And why not working with a branch `1.1` and merge the new code there until it can be merged to master and then create the tag `1.1`. And if its a bug-fix just `cherry-pick` it.

**Comment by timdorr** [comment]
The vast majority of repos keep bleeding-edge code in `master` and use tags for releases. That's how Github itself does it. Branches are normally used for features, not entire divergent lines of development. 1.1 won't last for long. We're about 75% done with it anyways :smile:

**Comment by taion** [comment]
We might want to point rackt.github.io/react-router/ at the version-locked docs; that's pretty typical.

I took a stab at it on https://github.com/rackt/react-router/pull/2529, but it was premature then. Maybe it's the right move now, though, given that we do have API changes on `master`.

**Comment by timdorr** [comment]
Ryan did that in 6cba3db already. We should just point at the `latest` tag, since that's maintained.

**Comment by taion** [comment]
Ah, cool. Nice.

**Comment by XescuGC** [comment]
Yes, that's a good solution too Ryan :+1:
