### ISSUE TITLE
History 1.14 pushState deprecation warnings.

### ISSUE THREAD

**Issue by uipoet** [rackt/react-router#2657]
Will there be an interim 1.0.2 release that correctly uses history's push ahead of the larger 1.1 release?

I'm holding my project's history at 1.13.1 to prevent the warnings, because they are presented via console.error and not console.warn, which is very distracting while developing.

**Comment by taion** [comment]
See https://github.com/rackt/react-router/pull/2659 as well. We could cut it down to not include the new feature. Still blocked on https://github.com/rackt/history/pull/173 though.

**Comment by mjackson** [comment]
I don't understand the question. You should be able to use 1.14 without any
warnings if you don't do deprecated stuff. Is that not the case?

**Comment by taion** [comment]
React Router itself is still using `pushState` and `replaceState` though, via e.g. `<Link>` and what it does for `onEnter` hooks.

**Comment by uipoet** [comment]
My direct use of history is with push (and has been for some some). It's react-rotuer that causes the deprecations warnings from history. I realize that react-router 1.1 will make this issue moot. Just asking if there can be a patch release that only addresses the correct usage of history 1.14 in the meantime.

**Comment by mjackson** [comment]
Ah, sorry. I thought this issue was opened on the history project.

**Comment by timdorr** [comment]
For now, just `npm install --save history@1.13.1` in your project. No need for an interim release.

**Comment by taion** [comment]
This was fixed by https://github.com/rackt/react-router/pull/2659 against the latest `history` release. We'll get a new React Router release out as soon as we can. Thank for your patience.
