### ISSUE TITLE
<Link to={window.location}> is not working properly

### ISSUE THREAD

**Issue by dbkaplun** [rackt/react-router#2665]
It is adding an additional `#/` so the URL comes out as `#/#/posts` rather than `#/posts`.

**Comment by timdorr** [comment]
You shouldn't be using `window.location` when constructing URLs for `Link`. Simply put `<Link to="/posts">`. The browser URL isn't used for computing what route that links to.

**Comment by mjackson** [comment]
This should eventually work, though. Our location descriptor objects are
analogous to window.location.
