### ISSUE TITLE
Warning on <Link>

### ISSUE THREAD

**Issue by 1000ch** [rackt/react-router#2668]
`<Link>` generates following warn messages on react-router `v1.0.1`.

>Warning: the query argument to createHref is deprecated; use a location descriptor instead

It seems that thrown on next code on `Link.prototype.render`.

```js
props.href = history.createHref(to, query);
```

**Comment by taion** [comment]
This was fixed by https://github.com/rackt/react-router/pull/2659. We'll wrap it all up and release as soon as we can. Thanks for your patience.

**Comment by 1000ch** [comment]
>This was fixed by 2659. We'll wrap it all up and release as soon as we can. Thanks for your patience.

Ah, Sorry and Thank you so much. Waiting release :+1:
