### ISSUE TITLE
Warning: the query argument to createHref is deprecated; use a location descriptor instead

### ISSUE THREAD

**Issue by littlee** [rackt/react-router#2670]
I copy the code from doc and see this error, how do I fix it?
https://github.com/rackt/react-router/blob/master/docs/Introduction.md#with-react-router
```js
return (
	<div>
		<h1>App</h1>

		<ul>
			<li><Link to="/about">About</Link></li>
			<li><Link to="/inbox">Inbox</Link></li>
		</ul>

		{this.props.children}
	</div>
);
```
I can not find any solution for me inside CHANGES.md
https://github.com/rackt/react-router/blob/master/CHANGES.md#accessing-location

**Comment by Ikhtiyor** [comment]
The same issue with this dependencies below

**Comment by 1000ch** [comment]
Related to #2668 ?

**Comment by Ikhtiyor** [comment]
Yes

**Comment by taion** [comment]
-> https://github.com/rackt/react-router/issues/2669

**Comment by jackyon** [comment]
waiting for the new release
