### ISSUE TITLE
Pass props to components in route declaration 

### ISSUE THREAD

**Issue by Bnaya** [rackt/react-router#2673]
I think it would be useful to have a way to pass props to the component in the route declaration
Something like:

```jsx
<Route path="/" component={App} componentProps={prop1: 'propValue'}>
```

**Comment by taion** [comment]
https://github.com/rackt/react-router/blob/v1.0.1/CHANGES.md#routehandler

**Comment by taion** [comment]
Oops - I mean to say that you can handle this yourself in `createElement` (should we rename this to `render` for consistency?).

**Comment by taion** [comment]
Sorry, momentary confusion - I'm going to _actually_ leave this open. Apologies for the spam.

**Comment by Bnaya** [comment]
If i understand correctly, i will have redundant instance for the active component?
And i'm not show how i should use it

Thanks!

**Comment by taion** [comment]
`cloneElement` doesn't do that if that's what you're asking. `createElement` doesn't really give a good API for this, which is why I deleted that comment.

**Comment by ryanflorence** [comment]
```js
<Route component={Whatev} foo="bar"/>

// is available at
`this.props.route.foo`
```

**Comment by taion** [comment]
D'oh!

**Comment by Bnaya** [comment]
Thanks for all of your help
