### ISSUE TITLE
Warning: the query argument to createHref is deprecated; use a location descriptor instead

### ISSUE THREAD

**Issue by Robinnnnn** [rackt/react-router#2679]
Suddenly getting this error in my console. Anyone else run into this issue, or know how to fix it?

**Comment by taion** [comment]
Use 1.0.2 and respect the peer dep.

**Comment by Robinnnnn** [comment]
Hi @taion, thanks for your response. I'm continuing to face the error despite using 1.0.2. What do you mean by "respect the peer dep?"

**Comment by timdorr** [comment]
Make sure you're using history 1.13.1. It's listed in the peerDependencies for router.

**Comment by Robinnnnn** [comment]
This did the trick. I was using history 1.13.0, and updating to the latest 1.15.0 threw an error. Solution: `npm install history@1.13.0`

Thanks @timdorr
