### ISSUE TITLE
Warning: the query argument to createHref is deprecated

### ISSUE THREAD

**Issue by qamil** [rackt/react-router#2688]
The history module logs a warning when rendering a Link:

```Warning: the query argument to createHref is deprecated; use a location descriptor instead```

Apparently they made a change in the api few days ago:

```
**Feature** Accept location descriptors in `createPath` and `createHref` ([#173])
**Deprecation** Deprecate the `query` arg to `createPath` and `createHref` in favor of using location descriptor objects ([#173])
```

https://github.com/rackt/history/commit/e491c960f1bf07d601ab9aaa9c7890f5860da701

**Comment by juliensantos87** [comment]
:+1:

**Comment by chentsulin** [comment]
For now, you should use `history: "~1.13.x" before next release of router.
