### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by des-des** [rackt/react-router#2690]
I have been having trouble today, react-router seems to be crashing our travis build. [Here](https://travis-ci.org/jgne/bubbles/builds/95814915#L189) is the error as travis gives it. This problem persists even if I change our history dependency in the package to 1.13.0.. Any advice on solving this would be appreciated.

**Comment by SeeThruHead** [comment]
In npm 2 peerdeps get installed with `^` which means that npm will update the minor version. Since react relies on history 1.13.x and not 1.x.x this installation pattern will fail. You will need to change history to
`~1.13.0`

**Comment by des-des** [comment]
Thank you! That solved it. Not sure about whether history follows semver.

**Comment by timdorr** [comment]
@SeeThruHead We do. We have added deprecation warnings for 1.14.0 and 1.15.0, but no API breakage. Router is still using the deprecated APIs, hence we locked at 1.13.1 to avoid deprecation warnings. But now we have a peer dep issue, so damned if you do, damned if you don't...

**Comment by SeeThruHead** [comment]
@Timdorr when will these apis be removed? 1.16? or 2.0?

**Comment by timdorr** [comment]
@SeeThruHead [v2.0.0](https://github.com/rackt/history/issues/172)

**Comment by SeeThruHead** [comment]
The peerdep in react-router should then be history 1.x no?

**Comment by timdorr** [comment]
Again, we are using deprecated APIs in router and we want to avoid those from cropping up. This is the simplest way to avoid them and enforce the right version.

**Comment by SeeThruHead** [comment]
Ok so your recommended course of action is for everyone to edit the peerdep that npm saves to the package.json to be locked to a minor version? What if the user want's to upgrade to 1.15 and is ok with react-router using deprecated apis? We would then manually edit react-router peerdeps to prevent npm errors? Please advise. At a glance this seems like it might not be the best solution.

**Comment by timdorr** [comment]
We're prepping a 1.1 release that will solve the issue. We have a *lot* more users that will want to simply make the warnings disappear than those that want to use just-released APIs for the history subproject.

**Comment by SeeThruHead** [comment]
Understood. Thank you for the insight.
