### ISSUE TITLE
example code with flux?

### ISSUE THREAD

**Issue by littlee** [rackt/react-router#2691]
Is there any example code that using react-router with Flux pattern?

**Comment by knowbody** [comment]
@littlee I think the good example might be https://github.com/gaearon/flux-react-router-example the code is a bit outdated but should give you the idea.

**Comment by ajsharp** [comment]
Bump on this. The fact that that link is out of date sort of defeats the purpose. It's super frustrating to try to use react-router right now b/c there's very sparse documentation on how to use it with flux / fluxxor.

**Comment by ryanflorence** [comment]
Working on it :) we just barely got the API and implementation we like, docs and guides are next.

I always wonder if people open these issues on the flux repos...

**Comment by ajsharp** [comment]
Yep: https://github.com/BinaryMuse/fluxxor/issues/137

**Comment by littlee** [comment]
Oh~, I've followed the example provide by knowbody since last week. :see_no_evil: :joy:

**Comment by timdorr** [comment]
Note that @knowbody's example now lives in Redux as [the `real-world` example](https://github.com/rackt/redux/tree/master/examples/real-world). That's still stuck on react-router 1.0.0-rc1 (!), so I'll make sure to update that once 2.0.0 is out.

**Comment by es6Test** [comment]
wow versions move fast these days, only just found out about 1.0.0 not that long ago.
