### ISSUE TITLE
How do you stop the deprecated warnings?

### ISSUE THREAD

**Issue by btipling** [rackt/react-router#2695]
I've looked at #2688 and #2646 and I'm still lost as to how to have react-router and history not spam my console with warnings.

I've tried installing the latest react router with history 1.13.x and 1.15.x and in both cases it's warnings in the console and peer dependency warnings on the command line:

```
npm i

> history@1.15.0 postinstall /Users/bjorn/dev/MW/node_modules/history
> node ./npm-scripts/postinstall.js

MW@0.0.1 /Users/bjorn/dev/MW
└── UNMET PEER DEPENDENCY history@1.15.0

npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.
npm WARN EPACKAGEJSON MW@0.0.1 No repository field.
npm ERR! code 1
```

![2015-12-09 at 3 36 pm](https://cloud.githubusercontent.com/assets/249641/11702341/beb29fb6-9e8a-11e5-8468-96b8e4bc1c24.png)

Again I've tried package.json with both `"history": "^1.13.x",` and  `"history": "1.15.0",` and various variants and they all have the same problem.

**Comment by smazurov** [comment]
try it with `"history": "1.13.1",`

**Comment by d0f** [comment]
```
kelvin@gnux:~/workspace/blog> npm i --save-dev css-loader
npm WARN install Couldn't install optional dependency: Unsupported
jxnblk.github.io@256.0.0 /home/kelvin/workspace/blog
├── css-loader@0.13.1 
└── UNMET PEER DEPENDENCY history@1.13.x
npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.
```

**Comment by nickcolley** [comment]
This fails my CI build currently, any ideas?

**Comment by taion** [comment]
For the moment, specify `react-router@^1.0.2` and `history@1.13.x`. We'll get new releases out soon.

**Comment by jeffscottward** [comment]
Can confirm the error
`npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.`
on a totally fresh install of of a different boilplate repo.

**Comment by smazurov** [comment]
@jeffscottward thats not an issue - read up on peer dependancies. Although if it happens in the boilerplate you might want to open an issue there. If you lock to `history` to `1.13.1` it works correctly.

**Comment by ryanflorence** [comment]
> Can confirm the error
> `npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.`
> on a totally fresh install of a different boilplate repo.

BTW, this is not an error. Its now npm@3 handles peer dependencies. You have to install them yourself.

**Comment by d0f** [comment]
thanks
