### ISSUE TITLE
Shouldn't history be a regular dependency and not a peer-dependency?

### ISSUE THREAD

**Issue by ssboisen** [rackt/react-router#2697]
Hi fellas,

This is regarding the current 1.0.2 release.

react-router has a direct dependency on history as can be seen in both [match.js](https://github.com/rackt/react-router/blob/v1.0.2/modules/match.js#L2) and [Router.js](https://github.com/rackt/react-router/blob/v1.0.2/modules/Router.js#L3) and I believe this warrants the use of a direct dependency since you can't even require react-router without also having history. If you just do `install react-router --save` you can't compile since history is missing.

Now if you instead do `npm install react-router history --save` history will get the default npm ^1.13.x dependency version spec. This causes history 1.15.x to be installed since it's the latest major and since history seem to have broken semver in versions with a major higher than 1.13.2 this causes exceptions. 

Obviously part of the problem is the fact that history seem to have broken semver but it would have been solved if only react-router had a depedency on history exactly 1.13.x.

Below is the exception and stacktrace I get when using react-router 1.0.2 with history 1.15.x:

```
Uncaught TypeError: Cannot read property 'query' of undefined
createPath @ useQueries.js:124
createLocationFromRedirectInfo @ useRoutes.js:77
(anonymous function) @ useRoutes.js:111
done @ AsyncUtils.js:13
(anonymous function) @ TransitionUtils.js:56
(anonymous function) @ TransitionUtils.js:16
(anonymous function) @ TransitionUtils.js:54
next @ AsyncUtils.js:20
loopAsync @ AsyncUtils.js:26
runEnterHooks @ TransitionUtils.js:53
finishMatch @ useRoutes.js:107
(anonymous function) @ useRoutes.js:91
done @ AsyncUtils.js:13
(anonymous function) @ matchRoutes.js:178
(anonymous function) @ matchRoutes.js:145
done @ AsyncUtils.js:13
(anonymous function) @ matchRoutes.js:178
(anonymous function) @ matchRoutes.js:145
done @ AsyncUtils.js:13
(anonymous function) @ matchRoutes.js:178
(anonymous function) @ matchRoutes.js:118
getIndexRoute @ matchRoutes.js:31
(anonymous function) @ matchRoutes.js:102
matchRouteDeep @ matchRoutes.js:124
(anonymous function) @ matchRoutes.js:176
next @ AsyncUtils.js:20
loopAsync @ AsyncUtils.js:26
(anonymous function) @ matchRoutes.js:175
matchRoutes @ matchRoutes.js:184
(anonymous function) @ matchRoutes.js:139
getChildRoutes @ matchRoutes.js:19
matchRouteDeep @ matchRoutes.js:134
(anonymous function) @ matchRoutes.js:176
next @ AsyncUtils.js:20
(anonymous function) @ matchRoutes.js:180
matchRouteDeep @ matchRoutes.js:155
(anonymous function) @ matchRoutes.js:176
next @ AsyncUtils.js:20
loopAsync @ AsyncUtils.js:26
(anonymous function) @ matchRoutes.js:175
matchRoutes @ matchRoutes.js:184
(anonymous function) @ matchRoutes.js:139
getChildRoutes @ matchRoutes.js:19
matchRouteDeep @ matchRoutes.js:134
(anonymous function) @ matchRoutes.js:176
next @ AsyncUtils.js:20
loopAsync @ AsyncUtils.js:26
(anonymous function) @ matchRoutes.js:175
matchRoutes @ matchRoutes.js:184
match @ useRoutes.js:87
(anonymous function) @ useRoutes.js:266
(anonymous function) @ useQueries.js:109
listen @ createHistory.js:102
listen @ createDOMHistory.js:31
listen @ createHashHistory.js:165
listen @ useQueries.js:108
listen @ useRoutes.js:262
componentWillMount @ Router.js:94
ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:210
ReactPerf.measure.wrapper @ ReactPerf.js:66
ReactReconciler.mountComponent @ ReactReconciler.js:37
ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225
ReactPerf.measure.wrapper @ ReactPerf.js:66
ReactReconciler.mountComponent @ ReactReconciler.js:37
ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225
ReactPerf.measure.wrapper @ ReactPerf.js:66
ReactReconciler.mountComponent @ ReactReconciler.js:37
mountComponentIntoNode @ ReactMount.js:266
Mixin.perform @ Transaction.js:136
batchedMountComponentIntoNode @ ReactMount.js:282
Mixin.perform @ Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:94
ReactMount._renderNewRootComponent @ ReactMount.js:476
ReactPerf.measure.wrapper @ ReactPerf.js:66
ReactMount._renderSubtreeIntoContainer @ ReactMount.js:550
ReactMount.render @ ReactMount.js:570
ReactPerf.measure.wrapper @ ReactPerf.js:66
(anonymous function) @ app.js:3
__webpack_require__ @ bootstrap c21a76f9d289539d16cf:19
(anonymous function) @ bootstrap c21a76f9d289539d16cf:39
(anonymous function) @ bootstrap c21a76f9d289539d16cf:39
```

**Comment by taion** [comment]
History did _not_ break semver. It's entirely acceptable to add deprecation warnings in a minor release. We modified the dependency as a convenience to users because we didn't want to stick you with deprecation warnings that you couldn't do anything about, since the usages were in React Router code rather than in History code.

The current model in the 1.0.x API is for React Router to be a History extender, so the current dependency setup is appropriate. We discussed this extensively at https://github.com/rackt/react-router/issues/2211.

Things are changing a little bit for 1.1.x but with the current API, we are using the peer dependency exactly as we should.

**Comment by ryanflorence** [comment]
Hey @ssboisen 

We've decided to change the way we do these deprecations with versions, you can read about it here:

Check out https://medium.com/rackt-and-roll/upgrading-and-backwards-compatibility-for-react-router-and-other-rackt-repos-ec24978a58b2#.grnrzw86v

Also in router 2.0 (which Jimmy referred to as 1.1) history will actually become a normal dependency,

**Comment by ryanflorence** [comment]
also here: https://gist.github.com/ryanflorence/40706116a1ca090f07db

**Comment by ryanflorence** [comment]
also this: https://github.com/rackt/history/issues/185

:P 

So, yeah, we get what you're talking about! :)
