### ISSUE TITLE
Location Description for History module not part of the latest release 

### ISSUE THREAD

**Issue by alansouzati** [rackt/react-router#2698]
I'm using react-router version 1.0.2 that was release yesterday. Thanks for working on that!

I see in the source code that the new api for history module is being applied using location descriptors. See this line https://github.com/rackt/react-router/blob/master/modules/Link.js#L101

On the other hand, when I look at the compiled NPM distribution, it seems not to be reflecting the latest code.

I still this `props.href = history.createHref(to, query);`

This is causing the following warning on my console:

> Warning: the query argument to createHref is deprecated; use a location descriptor instead

**Comment by taion** [comment]
Fix your peer dependency - you need to go back to history 1.13.x for now.
