### ISSUE TITLE
routerWillLeave not being consistently called

### ISSUE THREAD

**Issue by jlucas91** [rackt/react-router#2699]
Hi all,

I want to track changes from one component to another and routerWillLeave seemed like a good usecase. Unfortunately I'm seeing an issue where routerWillLeave is not called 100% of the time and I'm not sure why. My route/component structure is fairly simple - three routes all hit one top level component. This top level component then renders one of two subcomponents based on the parameters given to the route. When changing between the 3 routes, routerWillLeave is triggered sometimes, but not all of the time. I can see no discernible pattern in when it does/when it does not get triggered. I've attached below a rough mock up of my basic design. Note: I haven't tested/run this code - it's for explanatory purposes only. If I have some time later I will try to build a reproduction case.

Has anyone encountered this issue before? Am I doing something wrong? 

Components:
```js
var TopLevelComponent = React.createClass({

  mixins: [ RouteContext ],

  render: function() {
    if (this.props.params.param1 {
      showSubComp1 = true;
    }    

    return (
      <div>
        {
          showSubComp1
          ? <SubComponent1
              param1={this.props.params.param1}
            />
          : <SubComponent2
              param2={this.props.params.param2}
            />
        }
      </div>
    );
  }
});

var SubComp1 = React.createClass({

  render: function() {
    return (
      <p>
        SubComp1
      </p>
    );
  }
});

var SubComp2 = React.createClass({

  mixins: [ Lifecycle ],

  routerWillLeave(nextLocation) {
    console.log('in_router_will_leave');
  },

  render: function() {
    return (
      <p>
        SubComp2
      </p>
    );
  }
});
```

Routes:
```js
    <Route component={TopLevelComponent} path='/test/' onEnter={func1} />,
    <Route component={TopLevelComponent} path='/test/:param1/' onEnter={func2} />,
    <Route component={TopLevelComponent} path='/other/:param2/' onEnter={func3}/>
```

**Comment by ryanflorence** [comment]
can you make a table like this?

old url | new url | willLeave called?
---|---|---
/test/1 | /test/2 | yes

**Comment by taion** [comment]
Need an update/repro - otherwise I don't think we should keep this open.

**Comment by ryanflorence** [comment]
If a table shows up suggesting a bug we'll reopen.
