### ISSUE TITLE
Loading a different Component for "/" route depending on if user is authed

### ISSUE THREAD

**Issue by mezod** [rackt/react-router#2703]
Hello,
I am trying to copy the behaviour of sites like facebook/twitter where the "/" route shows a landing page to those not authed, and the feed page to those who are.

so:
if authed "/" -> Pages.Feed
else "/" -> Pages.Landing

Here's my Router: https://github.com/mezod/listlogs/blob/joan/app/src/utils/router.js

I have tried using getComponents as suggested here: http://stackoverflow.com/questions/33558526/having-route-show-a-different-component-depending-on-if-user-is-authed

but I am not managing to get it to work given the "/" is right now just loading de wrapper container, and the IndexRoute is the one actually loading the Pages.Feed component. I tried something like:

    <Route path="/" getComponent={(location, callback) => callback(authed ? Containers.AppLayout : Components.Landing)}

without luck.

Any ideas of how could I get it to work? Thanks

**Comment by ryanflorence** [comment]
I'd do it in the component.

`<Route component={App} path="/"/>`

```js
const App = React.createClass({
  render() {
    return authed ? <AppLayout/> : <Landing/>
  }
})
```

**Comment by mezod** [comment]
Hey Ryan, thanks for your answer.

I tried what you suggest, it looks like

       return this.props.loggedUser.id ? this.props.children : <LandingLayout/>;

This way, when the user is logged in, everything works wonderfully, however, when the user is not logged in, only the LandingLayout is loaded, without the content loading up. Makes sense, because I am just loading the LandingLayout and not calling the route again that should execute lines from 22-24 here: https://github.com/mezod/listlogs/blob/joan/app/src/utils/router.js#L22

Probably I should restructure all the router tree..? Thanks!
