### ISSUE TITLE
Handle reload on single page app

### ISSUE THREAD

**Issue by Antonhansel** [rackt/react-router#2709]
Hello,

I'm migrating from an old version of react-router and trying to get familiar with the new API.

Using the following route configuration:

```
<Router history={history}>
    <Route path="/" component={App}>
      <Route path="clients" component={Clients}/>
    </Route>
  </Router>
````

When I get on the /clients and reload, the browser obviously tries to get /client on the server, which doesn't exist.

I tried setting #/ before my paths but it doesn't seem to work properly, the component is not rendered at all.

What would be the best way to handle this? I think I'm missing something here.

**Comment by ugogo** [comment]
You should use `createHashHistory`.
See https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md
