### ISSUE TITLE
Include more information in all deprecation warnings

### ISSUE THREAD

**Issue by timoxley** [rackt/react-router#2710]
> Warning: the query argument to createHref is deprecated; use a location descriptor instead

I don't know what a "location descriptor" is and that makes me feel dumb.

Would be great if all deprecation messages included some additional information that helped the user understand exactly what they need to do.

One great thing that react does to help users migrate away from deprecated APIs is to include links to additional information (e.g. an issue that explains the change, or a place in the wiki):

> Warning: Failed propType: transitionLeaveTimeout wasn't supplied to ReactCSSTransitionGroup: this can cause unreliable animations and won't be supported in a future version of React. See https://fb.me/react-animation-transition-group-timeout for more information…

or a direct reference to the replacement API:

> Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

**Comment by ryanflorence** [comment]
Yep, we agree, as you can see on React Router master:

https://github.com/rackt/react-router/blob/master/modules/Lifecycle.js#L38
https://github.com/rackt/react-router/blob/master/modules/RouterContext.js#L52
(there are others)

It was an accident that you got the new version of history in your router deps with those warnings, we won't be doing that anymore:

https://medium.com/rackt-and-roll/upgrading-and-backwards-compatibility-for-react-router-and-other-rackt-repos-ec24978a58b2#.ibavsdl2n

We'll get a better message over there on history for that deprecation. Thanks.
