### ISSUE TITLE
Documentation mismatch with NPM release -- RouterContext doesn't exist

### ISSUE THREAD

**Issue by acjay** [rackt/react-router#2713]
Clicking the [v1.0.2 release tag](https://github.com/rackt/react-router/tree/v1.0.2/modules), it's clear that the change from `RoutingContext` -> `RouterContext` didn't make the release. That's really confusing though, because the docs clicked from the README are ahead of what's actually released. I suppose it's partially my fault for not selecting the proper release tag on Github before reading the docs, but I think it's probably an error most users would make.

As a side question, I also would have figured this issue out more quickly had my ESLint setup and my Babel set up flagged the importing of the nonexixstent `RouterContext` as an error, instead of blowing up at runtime. The basic ESLint checks don't catch this because there's no way for ESLint to know whether an import will exist or not. Does anybody know if and how such a static check could be enabled?

-----
(The story of how I figured out what's going on, in case anybody else runs into something similar) 

I installed `react-router` with the suggested method in the README. Following the docs on server-side rendering, I was attempting to set up my pre-rendering using the `match` -> `RouterContext` methodology, but I got an error with the following stack trace:

```
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. at invariant (/Users/alan/projects/prediction/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15) at [object Object].instantiateReactComponent [as _instantiateReactComponent] (/Users/alan/projects/prediction/node_modules/react/lib/instantiateReactComponent.js:64:134) at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/alan/projects/prediction/node_modules/react/lib/ReactCompositeComponent.js:223:36) at [object Object].wrapper [as mountComponent] (/Users/alan/projects/prediction/node_modules/react/lib/ReactPerf.js:66:21) at /Users/alan/projects/prediction/node_modules/react/lib/ReactServerRendering.js:42:38 at ReactServerRenderingTransaction.Mixin.perform (/Users/alan/projects/prediction/node_modules/react/lib/Transaction.js:136:20) at renderToString (/Users/alan/projects/prediction/node_modules/react/lib/ReactServerRendering.js:40:24) at /Users/alan/projects/prediction/server/home/index.js:63:27 at run (/Users/alan/projects/prediction/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47) at /Users/alan/projects/prediction/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
```

I couldn't find any solid info when searching for help, but I eventually realized when examining `node_modules` that there was no `RouterContext` module:

<img width="285" alt="screen shot 2015-12-13 at 2 53 17 pm" src="https://cloud.githubusercontent.com/assets/1256382/11768918/5118196e-a1a9-11e5-99ca-ff9f4bcad5e6.png">

**Comment by taion** [comment]
Yeah we tried to address this a bit in https://github.com/rackt/react-router/issues/2650 and https://github.com/rackt/react-router/commit/088f1d53945f739628aeebfc00809fae8c332035 but it should be a more obvious warning à la https://github.com/kubernetes/kubernetes/tree/master/docs#readme.

**Comment by ryanflorence** [comment]
The link on the README points to `latest`, which is part of our release script. Wonder why its out of sync.

**Comment by taion** [comment]
The problem is that a naive search on e.g. Google drops you to https://github.com/rackt/react-router/tree/master/docs, which has no explicit caveat that it isn't talking about the current release.

This will be less of an issue once we have a proper docs page.

Also, it's sorta easy to accidentally end back up on `master`.

**Comment by taion** [comment]
BTW, k8s has that warning in _every_ doc entry on `master`: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/bare_metal_offline.md.

**Comment by taion** [comment]
Well, doesn't matter now that 2.x-rc is out.

**Comment by ryanflorence** [comment]
after 2.0 release we're going to make the default github branch "stable" or something, that points to the latest release as long as the repo docs are the official docs

**Comment by dannypaz** [comment]
@taion This still may be a thing? I ran into the same issue @acjay described. I found where I went wrong when I tried to downgrade `react-router` to an older version (and noticed that I was already on 1.0.3 instead of 2).
