### ISSUE TITLE
getChildRoutes signature suggestion (resolve, reject, location)

### ISSUE THREAD

**Issue by jayphelps** [rackt/react-router#2725]
Bikeshedding a bit here, but I've found myself forgetting the signature of `getChildRoutes` several times as well as that the first argument of the resolve callback being for any error.

Anyone else interested in changing it on the next major rev to be closer to Promise?

`getChildRoutes(resolve, reject, location)`

**Comment by taion** [comment]
It's really standard for this sort of callback to take `error` as the first arg. Look through e.g. the Node docs.

**Comment by ryanflorence** [comment]
Also, while you won't find much promise love around here, that's not the reason we don't use them. Its important for all of our async stuff to be able to also operate synchronously for server rendering :trophy:
