### ISSUE TITLE
Router onUpdate handler should provide prevProps and nextProps as arguments

### ISSUE THREAD

**Issue by SRachamim** [rackt/react-router#2733]
I think onUpdate handler should provide the previous and next props.

As in this case:
```javascript
<Router onUpdate={onRouterUpdate}>
....
</Router>

const onRouterUpdate = (prevProps, nextProps) => {
...
};
```

**Comment by taion** [comment]
That's not the right spot for it. Use e.g. `componentWillReceiveProps` on a route component.

**Comment by SRachamim** [comment]
And if I want to share functionality in many routs? Should I decorate every Route com ponent with a custom componentWillReceiveProps?

What is the purpose of onRouterUpdate then?

**Comment by taion** [comment]
It's to let you _do_ something after an update. It takes place after the update and re-render have already completed. If you need this behavior, you could use something like a single top-level abstract route or whatever.
