### ISSUE TITLE
Optional path with dash

### ISSUE THREAD

**Issue by mmahalwy** [rackt/react-router#2735]
I cannot get this to work:
```
<Route path="/r/:displayGid(-:seoSlug)" component={Region}/>
```
returns when visiting `/r/123-asd`:
```
{displayGid: '123-asd', seoSlug: undefined}
```

My solution for now is:
```
<Route path="/r/:displayGid*-*(:seoSlug)" component={Region}/>
```

Which returns:
```
{displayGid: '123', slug: Array[2], seoSlug: 'asd'}
```

**Comment by taion** [comment]
Subset of https://github.com/rackt/react-router/issues/2286.

**Comment by mmahalwy** [comment]
@taion sorry, i think I am missing how it's a subset, correct me if I am wrong please :)

**Comment by timdorr** [comment]
That issue, once implemented, will allow you to customize how URLs are matched, including having optional ones.

**Comment by mmahalwy** [comment]
@timdorr awesome - really appreciate it!
