### ISSUE TITLE
Server side routing: multiple webpack chunks

### ISSUE THREAD

**Issue by mattkrick** [rackt/react-router#2741]
I've been loving react-router v1.0! Instead of writing multiple entry chunks, I can just async require everything like:
```
//routes.js (assuming babel 6 & webpack 2)
{
    path: 'signup',
    getComponent: async (location, cb) => {
      let mod = await System.import('components/Signup/Signup');
      let component = mod.default;
      cb(null, component)
    }
}

//client.js entry chunk
<Router history={history} routes={routes}/>
```

Is this the correct way to do things? Does this mean if an app uses react-router we'll never write more than 1 entry chunk in our webpack config?

User story: For serverside routing, I'd like to send a chunk-specific css file for each async request. `match` can resolve an async route just fine, but `<RoutingContext {...renderProps} />` fails to return anything for async chunks. As a workaround, I ended up making only 1 chunk for server side rendering, which means I serve the same big ol css file regardless of route.

Any ideas on how to make `RoutingContext` play nicely with other chunks?

Note that the require polyfill hack seen in `https://github.com/rackt/example-react-router-server-rendering-lazy-routes` doesn't work for stylesheets.

**Comment by ryanflorence** [comment]
The demo you linked to shows how to integrate with webpack and its chunks, I haven't used webpack 2 yet so I can't offer any advice.

As for CSS, that's outside of the router's concern, we give you a callback, everything else is up to you :)

**Comment by deju** [comment]
@mattkrick How do you solve your problem?

@ryanflorence You said 'a callback', what does this mean?  :)
