### ISSUE TITLE
Optional path not work as expected

### ISSUE THREAD

**Issue by serco-chen** [rackt/react-router#2771]
```javascripts
<Route path='/(:locale)' component={App}>
  <Route path='projects/:projectId' component={Project}  />
</Route>
```
This matches only `/en/projects/1`. It does not match `/projects/1`.

```javascripts
<Route path='/(:locale/go)' component={App}>
  <Route path='projects/:projectId' component={Project}  />
</Route>
```
This will match both `/en/go/projects/1` and `/projects/1`.

**Comment by taion** [comment]
It's greedily matching `projects` as `:locale`. That's just how our route matching works.

**Comment by serco-chen** [comment]
@taion Thanks for explanation. 
How can I match both `/en/projects/1`,  `/fr/projects/1` and `/projects/1`?  Is there a way to do something like this?
```
<Route path='/(en|fr)' component={App}>
  <Route path='projects/:projectId' component={Project}  />
</Route>
```

**Comment by taion** [comment]
Track https://github.com/rackt/react-router/issues/2286.

**Comment by ryanflorence** [comment]
Workaround:

```js
<Route path="/" component={App}>
  <Route path="/:locale" component={App}>
    {otherRoutes}
  </Route>
  {otherRoutes}
</Route>
```

**Comment by serco-chen** [comment]
@ryanflorence 
Since you guys are talking about syntax for customizable url matching, have you ever consider syntax like following(taken from Rails)
```
<Route path='/(:locale)' component={App} locale={/en|fr/}>
  <Route path='projects/:projectId' component={Project} projectId={/\d+/}  />
</Route>
```

**Comment by taion** [comment]
Take a look at the linked issue, where we discuss this exact thing.

**Comment by ryanflorence** [comment]
I'm the wrong person to ask, I wish we didn't even have optional params :P but there's enough interest in this stuff that we'll eventually have pluggable matching, 

(Personally, I'm happy just doing it all with route config and onEnter hooks.)

**Comment by taion** [comment]
@ryanflorence What do you mean w/r/t `onEnter` hooks? We don't have an equivalent of `next` the way Express does, do we?

**Comment by drewblaisdell** [comment]
@ryanflorence I'm also curious how you handle this with `onEnter` - would you mind elaborating?

**Comment by retroalgic** [comment]
For anyone rans into the same trouble, another workaround is to move your optional locale param to lower-level Route components:
```js
<Route path='/' component={App}>
  <Route path='(:locale/)projects/:projectId' component={Project}  />
</Route>
```
This works fine for me (v3.0.2). Both `/en/projects/1` and `/projects/1` will be matched.

**Comment by CodHeK** [comment]
@serco-chen  How can render the same component using different routes for example I need to render the same components at "/" and "/console?query=someQuery&headers=someHeader"

```
<Route path="/" component={App} onEnter={validateLogin(store)}>
      <Route path="login" component={generatedLoginConnector(connect)} />
      <Route
        path=""
        component={Main}
        onEnter={composeOnEnterHooks([requireSchema, requireMigrationStatus])}
      >
        <Route path="">
          <IndexRoute component={generatedApiExplorer(connect)} />
          <Route
            path="api-explorer"
            component={generatedApiExplorer(connect)}
          />
          <Route path="metadata" component={metadataConnector(connect)} />
          {makeDataRouter}
          {makeEventRouter}
          {customResolverRouter}
        </Route>
      </Route>
      <Route path="404" component={PageNotFound} status="404" />
      <Route path="*" component={PageNotFound} status="404" />
    </Route>
```

This is the code for the Router
