### ISSUE TITLE
react-routers hashBrowser is not working with Auth0 callbacks

### ISSUE THREAD

**Issue by Moezalez** [rackt/react-router#2776]
When auth0 is using the provided callback it usually has the format https://webiste.com/#access_token=abc

react-router interpret that as  https://webiste.com/#/access_token=abc and complains that there is no route access_token.

Is there any way around that? 
I know there is browserHistory, but that seems to require a massive rewrite of my backend.

**Comment by taion** [comment]
https://github.com/rackt/history/pull/131

**Comment by rblakeley** [comment]
@Moezalez I copied your question to StackOverflow http://stackoverflow.com/questions/34805236/react-router-auth0-callback-redirect-history-hash. Would like to see if you found a workaround.

**Comment by ryuheechul** [comment]
I had a same problem but you can work around by parsing hash and edit/clear hash before render router dom.

example code below

```javascript
const lock = new Auth0Lock('client_key','domain');
var idToken = localStorage.getItem('userToken');
const authHash = lock.parseHash(window.location.hash);
if (authHash) {
  if (authHash.id_token) {
    idToken = authHash.id_token
    localStorage.setItem('userToken', authHash.id_token);
    location.href = '/#/';
    // location.hash = '';
    // history.pushState('', document.title, window.location.pathname);
  }
  if (authHash.error) {
    console.log("Error signing in", authHash);
  }
}

ReactDOM.render(
  <Provider store={store}>
    <Router history={history} routes={routes} />
  </Provider>
  , document.getElementById('root')
);
```

**Comment by Glavin001** [comment]
I can confirm that @ryuheechul 's workaround does in fact work! Thank you!

**Comment by Dr-Horv** [comment]
Since the release of Auth0-lock v10 this workaround seems not to work anymore?

**Comment by dcworldwide** [comment]
I'm having the same issue. Could someone please kindly confirm how to integrate auth0 with RR 2.4x?

**Comment by andys8** [comment]
I'm experiencing the same warning. Will this issue be addressed again? The example from Auth0 is using `react-router`: https://auth0.com/docs/quickstart/spa/react/01-login

**Comment by kit426** [comment]
I adjusted the work around to handle it in the following way:

if(window.location.hash.indexOf('access_token') > -1){
	window.location.hash = window.location.hash.replace('#/access_token', '#access_token')
	setAccessToken();
	window.location.href = '/#/';
}

**Comment by taylorbryant** [comment]
Any word on this? I'm hosting a React app on Netlify, so I need to use Hash Router. 

**I'm wanting to do something like:**
```
  auth0 = new auth0.WebAuth({
    domain: "exampledomain.com",
    clientID: "[hidden]",
    redirectUri: "https://exampledomain.com/#/callback",
    audience: "https://exampledomain.com",
    responseType: "token id_token",
    scope: "openid profile email"
  });
```

I get this error back: *parameters not allowed on the `/authorize` endpoint*.

Has anyone found any kind of workaround?
