### ISSUE TITLE
auth flow example doesn't work with @1.0.1 through npm

### ISSUE THREAD

**Issue by maximmcnair** [rackt/react-router#2780]
When running the `auth flow` example through webpack or browserify with react-router installed through npm I get this issue.

```
Warning: Failed Context Types: Required context `router` was not specified in `Login`. Check the render method of `RoutingContext`.
```

I also get it with this repo if I remove the resolve and use the react-router npm module.
```
  resolve: {
    alias: {
      'react-router': path.join(__dirname, '..', 'modules')
    }
  },
```

**Comment by timdorr** [comment]
First, we're at 1.0.3 now, so make sure you update.

Our master branch is currently whatever is being prepared for 2.0.0. Make sure you're building against [the 1.0.3 tag](https://github.com/rackt/react-router/tree/v1.0.3).
