### ISSUE TITLE
[Question]: How to learn about the internals of onUpdate?

### ISSUE THREAD

**Issue by toranb** [rackt/react-router#2781]
I've been looking over the source and see that onUpdate is a function but that's about all I could see looking over the router itself here

https://github.com/rackt/react-router/blob/master/modules/Router.js#L32

This in itself wasn't detailed about how the function is called/ with what and when. Where might I look to understand more about the onUpdate function and how it works?

Thank you in advance!

**Comment by timdorr** [comment]
Just look [down a little further](https://github.com/rackt/react-router/blob/68fdc826f6688e05d436add207cf296c8f5def6d/modules/Router.js#L82). It's the callback used when we `setState` after a history change. It's roughly equivalent to `.listen`ing to a `history` that you create.

**Comment by taion** [comment]
BTW, if you have any questions about RR internals, you might find it useful to check out #rackt on Reactiflux; a lot of us are on that channel.

**Comment by toranb** [comment]
@timdorr thank you !!! very much looking forward to some source diving this week :)
