### ISSUE TITLE
hashHistory isn't a function (like createHashHistory() was), so you cannot set queryKey to false

### ISSUE THREAD

**Issue by sean-clayton** [rackt/react-router#2784]
In 1.x:
```js
import { Router, createHashHistory } from 'history'

const history = createHashHistory({
  queryKey: false
})

<Router history={history} />
...
```

Works fine! No weird hash in the address bar :+1: 

In 2.0.0-rc2
```js
import { Router, hashHistory } from 'react-router'

const history = hashHistory({
  queryKey: false
})

<Router history={history} />
...
```

2.0.0-rc2 results in the following error:
`Uncaught TypeError: (0 , _reactRouter.hashHistory) is not a function`

:cry: :panda_face:

I looked through the source and noticed `hashHistory` is actually just `createBrowserHistory` from the `history` package (as seen [here](https://github.com/rackt/react-router/blob/3f5bfc9a152f226c17366db635b041f4598ba446/modules/hashHistory.js#L2-L4)), but it doesn't allow us to pass the object like we could in 1.x

Am I overlooking something or was queryKey deprecated (no dep warnings in console when using it)?

**Comment by taion** [comment]
You may be interested in https://github.com/rackt/history/issues/163.

For now, I think we want the default history singletons to just be the defaults. You can always use `useRouterHistory` and build your own from a custom `createHashHistory({queryKey: false})` if you want.

**Comment by ryanflorence** [comment]
`userRouterHistory(createHashHistory)({ queryKey: false })`

**Comment by woshi7hao** [comment]
However, if we remove _k, we cannot pass data through location.state!
How to deal with this problem? Any suggestions?

**Comment by developit** [comment]
For those discovering this via Google, here's a demo of preact-router + hash history:
https://jsfiddle.net/developit/gLyL6rbn/
