### ISSUE TITLE
Bad npm package for 2.0.0-rc2

### ISSUE THREAD

**Issue by insin** [rackt/react-router#2785]
The `node_modules/history` issue is back in the 2.0.0-rc2 npm package:

http://registry.npmjs.org/react-router/-/react-router-2.0.0-rc2.tgz

**Comment by patrickheeney** [comment]
Is this the issue you are referring to?

```
ERROR in ./~/react-router/~/history/lib/useQueries.js
Module not found: Error: Cannot resolve module 'query-string' in node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/useQueries.js 15:19-42

ERROR in ./~/react-router/~/history/lib/createHistory.js
Module not found: Error: Cannot resolve module 'deep-equal' in node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/createHistory.js 10:17-38
```

If so, I am experiencing this as well.

**Comment by taion** [comment]
@ryanflorence What version of npm are you on?

**Comment by taion** [comment]
Contra the npm3 release notes, it looks like this fix wasn't applied to npm3 because the relevant check got vendored. I backed out my build tooling change: https://github.com/rackt/react-router/pull/2789. I guess we'll have to re-release. Sorry.

**Comment by mjackson** [comment]
If it ain't broke... :P

**Comment by taion** [comment]
@mjackson The npm release notes claimed it was fixed. I even checked that it was... just not for npm3, which I don't use. Oops.

The relevant npm issue is https://github.com/npm/npm/pull/10445, for those interested.

**Comment by mjackson** [comment]
It's ok :) I break stuff all the time. nbd

**Comment by insin** [comment]
2.0.0-rc3 looks good :+1:

**Comment by ryanflorence** [comment]
If you don't ship 4 rc's in one day, then you just aren't shipping enough.

**Comment by taion** [comment]
We should ship a 5th w/a `history` v2 dependency as soon as we publish `history` v2, BTW.

**Comment by ryanflorence** [comment]
soon as @mjackson ships it, will do.

**Comment by mjackson** [comment]
i'm on it
