### ISSUE TITLE
ActiveState mixin gone

### ISSUE THREAD

**Issue by tyrsius** [rackt/react-router#2787]
Several issues reference this url (https://github.com/rackt/react-router/blob/master/docs/api/mixins/ActiveState.md), which is now dead. It is the only solution I can find to setting a container (i.e., *not* a `<Link>`) to active when a route is active.

What is the new method for doing this?

**Comment by tyrsius** [comment]
the close button sure is easy to misclick...

**Comment by taion** [comment]
That mixin hasn't been present for many releases. It wasn't even in 1.x. Use `context.router.isActive` now (against 2.0; consult relevant docs for other releases).

**Comment by tyrsius** [comment]
Isn't that a boolean? How will that tell me if a given route is active?
