### ISSUE TITLE
Maximum call stack size exceeded on rc3

### ISSUE THREAD

**Issue by patrickheeney** [rackt/react-router#2791]
![screen shot 2015-12-30 at 4 17 52 pm](https://cloud.githubusercontent.com/assets/1407228/12059122/326ced84-af12-11e5-8ead-2f31c044344b.png)

```
import { Provider } from 'react-redux';
import { Router, browserHistory } from 'react-router';
import { Route, IndexRoute } from 'react-router';
import CoreLayout from 'modules/core/views/CoreLayout';
import IndexView from 'modules/core/views/IndexView';

ReactDOM.render(
  <Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/" component={CoreLayout}>
        <IndexRoute component={IndexView}/>
      </Route>
    </Router>
  </Provider>,
  document.getElementById('root')
);
```

**Comment by taion** [comment]
You have webpack misconfigured to use `.` as a root for resolving imports. Don't do that.

**Comment by patrickheeney** [comment]
Not sure I understand what you mean? This error only showed up when using rc2 and above. 

This is what I assume you are talking about in my webpack.config, which is pretty common, no?

```
resolve: {
    root: path.join(__dirname, 'src'),
    extensions: ['', '.js', '.jsx'],
    modulesDirectories: ['lib', 'node_modules']
  }
```

**Comment by taion** [comment]
The `'lib'` in `modulesDirectories` is no good. It means that

```js
require('warning')
```

In `react-router/lib/warning` ends up requiring itself, not the npm `warning` package.

**Comment by patrickheeney** [comment]
Thanks!
