### ISSUE TITLE
[V2] Add a custom getUserConfirmation on singleton browserHistory

### ISSUE THREAD

**Issue by ingro** [rackt/react-router#2801]
Hello! I upgraded this morning to the last v2 rc version and I have a little problem with the new history singleton.

On 1.x I created the history used by React-Router like this:

```javascript
import { createHistory } from 'history';

const history = createHistory({ getUserConfirmation: (message, cb) => {
    swal({
        title: 'Attention!',
        text: message,
        type: 'warning',
        showCancelButton: true
    }, (res) => {
        cb(res);
    });
}});
```

So I added a nicer confirm message with `swal`. but now I think that's not possibile with the new singleton. Is there a workaround for this or it is not possible anymore?

**Comment by timdorr** [comment]
[Use `useRouterHistory`](https://github.com/rackt/react-router/blob/master/modules/useRouterHistory.js). Or just copy what it's doing inside of there.

**Comment by ryanflorence** [comment]
I just added a new section to the upgrading guide:

https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories

**Comment by ingro** [comment]
Thanks, wasn't aware of that! Anyway that was a smooth update overall!
