### ISSUE TITLE
v2 UMD build missing ability to create custom hash/browser histories

### ISSUE THREAD

**Issue by ghempton** [rackt/react-router#2808]
UMD only exposes `hashHistory` and `browserHistory`. Now that `History` is embedded, UMD builds needs ways to access the history creation methods. E.g.:

```
let history = useRouterHistory(ReactRouter.createBrowserHistory)({
  parseQueryString: function (queryString) {
    return parse(queryString);
  },
  stringifyQuery: function (query) {
    return stringify(query);
  }
});
```

**Comment by ghempton** [comment]
Should be fixed by #2778 if that is the right approach

**Comment by taion** [comment]
Follow https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories, please.

**Comment by ghempton** [comment]
@taion can you explain how do to that using the UMD build without using webpack?

**Comment by taion** [comment]
You'll need to pull in the history UMD bundle separately.

**Comment by ghempton** [comment]
That means we are required to have *two* copies of history? One in the UMD and one outside?

**Comment by taion** [comment]
How is that any different from before?

**Comment by ghempton** [comment]
Before it was a peer dependency and I was under the impression it was not included? Maybe I am mistaken, but in any case it seems way less than ideal to require two copies of a library.

**Comment by taion** [comment]
It's always been pulled in.

It's not ideal, but the situation with history and the UMD build has always been non-ideal just because you normally only use one history, but end up pulling all of them in regardless.

I agree that it sucks – it's one of those things where I think there literally isn't a good answer in UMD space, though. I'm not sure... maybe we should make a `react-router-without-history` bundle or something.

It's just really tough... UMD sorta sucks ):

**Comment by ryanflorence** [comment]
People, even my friends, who use UMD just have to deal with UMD and extra code, we aren't going to mess around with custom builds.

Perhaps maintain an internal fork that does what you need?

**Comment by ghempton** [comment]
Fine, I suppose I can live with that :P. Thanks guys.

**Comment by ryanflorence** [comment]
Yeah, sorry, that's why we invented modules and bundlers!

I'm still unclear why broccoli is the problem ... is there no commonjs module bundler that works with broccoli?

**Comment by ghempton** [comment]
There are a few webpack plugins for Broccoli that might get us there if we put some effort into it. Our main issue is that our tooling was originally based off of ember-cli and uses bower for all of its external dependencies.
