### ISSUE TITLE
Add deprecation error for replaceState in onEnter callback

### ISSUE THREAD

**Issue by mattkrick** [rackt/react-router#2820]
Similar to `Link` ( https://github.com/rackt/react-router/blob/fae5518618da0329e17e1ba5dd45dd00630d1760/modules/Link.js#L109 ) it'd be nice to show an error on the `replaceState` arg that gets passed to the `onEnter` callback. Currently, it's silently failing, which isn't great. Should be as easy as checking for the number of args. 

eg throw error on `replaceState(null, '/login', {next});`

**Comment by timdorr** [comment]
Can you work up a PR that adds this?

**Comment by taion** [comment]
This entire thing: https://github.com/rackt/react-router/blob/master/modules/createTransitionManager.js#L48-L52 looks a bit questionable. Not sure how our tests are passing.

**Comment by mattkrick** [comment]
just dug into it... do you still want to offer support for the deprecated style, or is it enough to just throw the error? If you chose the latter, you could probably save a good 5 or 6 closures.

**Comment by taion** [comment]
Well, my first question is how https://github.com/rackt/react-router/blob/master/modules/__tests__/transitionHooks-test.js is still passing.

**Comment by mattkrick** [comment]
that test suite isn't checking for a query, just a pathname

**Comment by taion** [comment]
Uhh, so

- `replaceState` there needs to take a location descriptor instead of a (`state`, `path`, `query`) tuple
- Where are you seeing the `query` get dropped? Looks like it should still be getting plumbed through right now

**Comment by mattkrick** [comment]
`history.createPath(pathname, query)` now only takes a `location` param

**Comment by mattkrick** [comment]
not how history is used in the rest of the router or how the path is created from `Link`, but i noticed this was the only occurrence of `createPath` so it may be possible to drop it?

**Comment by taion** [comment]
That's not true - the `useQueries`-wrapped `history.createPath` still has the backward compat shims to accept a `query`.

**Comment by mattkrick** [comment]
there's another `createPath` function in `useBasename.js` that's the one that's first called & only takes a location

**Comment by taion** [comment]
Ah - I see. Can you put together a PR that just switches the order of the two in `useRouterHistory`? I think that's all we need.

Separately we'll have to actually update this API; I guess we forgot to do so.
