### ISSUE TITLE
createMemoryHistory API not exposed

### ISSUE THREAD

**Issue by scriptjs** [rackt/react-router#2821]
The v2.0.0-rc4 does not expose the createMemoryHistory API. From history (created from createMemoryHistory from history module) I was also able to call createLocation. I am hoping this will not be a problem v2.0.0.

I am creating programmatic routes but unable to do so just yet with what is available in the rc release to migrate away from v1.0.3 and history 1.17.0. Hope some of these breaking changes will stop soon. Its been a bumpy ride.

**Comment by timdorr** [comment]
This will be exported in the next version: https://github.com/rackt/react-router/commit/ed630a5e8384d7f5a38f34384fb924735d95896e
