### ISSUE TITLE
Route reuse is not possible

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#2823]
We have fairly complex component - `UserProfile`.
This component has a number of tabs each with multiple tabs on their own.
This results in generating about 20-25 routes for just this component.

Now this component can be visited by multiple routes.
It seems the only way to implement this is to literally copy/paste the routes for `UserProfile` in every single parent route.

This is terrible since for every route we add/remove inside `UserProfile`, we now have to copy/paste the change for every parent route. Not to mention if we ever need to move the component around to a different path, again similar issues would pop up.

The React router needs a way to easily point to a set of routes from multiple parents. This way we can make the changes in one place and just have multiple parents point to the same set.

**Comment by theaqua** [comment]
Make array and then `.map` it.

```
const childRoutes = [{
  path: '/first',
  component: First
}];

{childRoutes.map(route => <Route path={route.path} component={route.component} />)}
```

**Comment by taion** [comment]
This is actually totally possible. Just use the same children for more than one route or whatever.

**Comment by ryanflorence** [comment]
JavaScript has variables, just use those :P

```js
var someRoutes = [
  <Route path="one" component={One}/>,
  <Route path="two" component={Two}/>
  <Route path="three" component={Three}/>
]

<Router>
  <Route path="first-parent" children={someRoutes}/>
  <Route path="second-parent" children={someRoutes}/>
</Router>
```
