### ISSUE TITLE
The 'history' used in intro should be hashHistory instead of browserHistory to avoid 404s

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#2825]
Currently the [intro](https://github.com/rackt/react-router/blob/latest/docs/Introduction.md) doc uses `{browserHistory}`. 

This means that unless someone has configured their server explicity, when they hit refresh on a url in the browser they will get a 404.

Having just run into this myself, I cant tell you its a terrible first experience. 

Please use `hashHistory` in the intro so it works for everyone when they hit refresh in the browser

**Comment by ryanflorence** [comment]
I agree, probably just an oversight when updating the docs. Go ahead and click "edit" in github and I'll merge the change.

Thanks.
