### ISSUE TITLE
Using hashHistory causes browser to reload entire page on router.push()

### ISSUE THREAD

**Issue by pdeva** [rackt/react-router#2832]
Confirmed that this is a bug since it surfaces in Chrome and Edge not in Firefox (things work fine in firefox i mean).

Full details on this [Stackoverflow post](http://stackoverflow.com/questions/34583413/routercontext-push-reloads-page-on-navigation).

I can copy/paste here too if you want.

**Comment by pdeva** [comment]
This seems to be happening with `browserHistory` too.

Here is a video demoing it:
http://screencast.com/t/PLWsYI6JD

It seems the route is loaded and then somehow there is a refresh.

The eventual 404 is cause the page is reloaded fully and i havent configured the server to use `browserHistory`

**Comment by taion** [comment]
You have something misconfigured somewhere on your side – this works fine in our examples and code. The issue tracker is not a support forum and this is not the first time you've been told that it's not appropriate to ask for support here.
