### ISSUE TITLE
createMemoryHistory is not a function

### ISSUE THREAD

**Issue by kristianroebuck** [rackt/react-router#2838]
I've just dropped React Router 2.0-rc4 into a project. Within the tests I changed where createMemoryHistory is pulled in from, previously it was coming from `import createMemoryHistory from 'history/lib/createMemoryHistory';` and as of the React Router 2.0-rc4 drop in it's now `import { createMemoryHistory } from 'react-router';`.

When I run the tests I'm getting the following error when running my tests
`TypeError: (0 , _reactRouter.createMemoryHistory) is not a function`. 

Within the tests I'm using `createMemoryHistory` as follows:
```
import { createMemoryHistory } from 'react-router';

...
const history = createMemoryHistory('/');
const rendered = renderToString(
  <Root history={history} />
);
```

The docs don't show an example of importing `createMemoryHistory` so I assume I'm importing it incorrectly and it isn't a subtle bug.

**Comment by taion** [comment]
It's been fixed on master.

**Comment by kristianroebuck** [comment]
Thanks for the heads up @taion

**Comment by Sawtaytoes** [comment]
I'm getting error in `1.0.3` when using Webpack to do a `target: node` bundle.
I also tried `import { createMemoryHistory } from 'history/lib/createMemoryHistory'` to no avail.

**Comment by timdorr** [comment]
It's a default export. You don't need to import the individual function: `import createMemoryHistory from 'history/lib/createMemoryHistory'`

**Comment by Sawtaytoes** [comment]
Thanks! This fixed my issue.

**Comment by holms** [comment]
@timdorr it says 
```
TypeError: history is undefined
```
routes.js:
```
import React from 'react'
import { Router, ReactRouter, Route, IndexRoute } from 'react-router';
import createHashHistory from 'history';

var Main = require('../components/Main');
var Home = require('../components/Home');

var routes = (
    <Router history={createHashHistory}>
        <Route path='/' component={Main}>
            <IndexRoute component={Home} />
        </Route>
    </Router>
);

module.exports = routes;
```

**Comment by sugandhhgoyal** [comment]
I get the

**Comment by leongaban** [comment]
`import { createMemoryHistory } from 'react-router';`
`import { createMemoryHistory } from 'react-router-dom';`

Hi I'm still getting this error, tried both above. My react-router and react-router-dom versions are both `4.1.1`

**Comment by pshrmn** [comment]
@leongaban v4 no longer re-exports history objects. Instead, just import directly from `history`.

```js
import { createMemoryHistory } from 'history';
```
