### ISSUE TITLE
Missing Dependency react-router@1.0.3 -> history@^1.17.0

### ISSUE THREAD

**Issue by skormos** [rackt/react-router#2840]
`npm install react-router` creates the warning:

```
EPEERINVALID react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed.
```

**Comment by kristianroebuck** [comment]
If you're using npm v3 and higher then peer dependancies aren't automatically installed. Try `npm install history` to resolve your issue.

As of React Router v2 `history`  is a normal dependancy. From the docs (https://github.com/rackt/react-router/blob/latest/upgrade-guides/v2.0.0.md#history-singletons-provided)

> You no longer have to install and maintain history separately. Batteries included!

**Comment by skormos** [comment]
@kristianroebuck Ah my mistake. Thanks for the follow up and explanation.
