### ISSUE TITLE
Add guide for minimizing bundle size (by excluding history)

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2853]
Right now it looks like we're exporting everything, including histories.

This means that users will always pull in _our_ bundled histories (maybe except when using the ES6 module build – hah!).

This is probably not ideal. What do we think of e.g. pulling out the history singletons into `react-router/lib`?

**Comment by timdorr** [comment]
What's the size difference between having them and not having them? 

Damn, we need tree shaking...

**Comment by taion** [comment]
It's just messy - especially since history is now just a normal dependency.

**Comment by taion** [comment]
Per notes on #2903, we still pull in `useQueries`, `useBasename`, and `createMemoryHistory`, but this should keep us from pulling in the actual histories when not needed.

**Comment by taion** [comment]
I've updated the title to the actual action item per our closing #2903.

**Comment by mbrevda** [comment]
For the record, I see about a 10k in size decrease when using this method (although all the extra imports are costing me about 1k). I don't want to open another issue, but I would be nice if there was a way to bring the size down even more  (I'm seeing ~43k w/ `history`).
