### ISSUE TITLE
Use history.createLocation for converting location descriptors to locations

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2859]
`transitionManager.isActive`:
This logic is wrong and should go through `history.createLocation`: https://github.com/rackt/react-router/blob/3494ed3974020b42c9af9490d681877829f3e9e1/modules/createTransitionManager.js#L37-L39

`match`:
Should be using `history.createLocation` in all cases: https://github.com/rackt/react-router/blob/3494ed3974020b42c9af9490d681877829f3e9e1/modules/match.js#L30-L31

Blocked on https://github.com/rackt/history/pull/200.

**Comment by taion** [comment]
`match` is handling this wrong too – updated the OP.

**Comment by taion** [comment]
Huh, the naive `isActive` fix will actually break https://github.com/rackt/react-router/pull/2386. Need to think about this a bit.

**Comment by seoyoochan** [comment]
I just followed ^2.0.0-rc upgrade guide documentation, using `"history": "^2.0.0-rc2"` and `"react-router": "^1.0.3"`.  
However, I get this error,
`Uncaught TypeError: Cannot read property 'query' of undefined`  

My code looks like this..
```
function requireAuth(nextState, replace) {
  const isLoggedIn = store.getState().auth.isLoggedIn;
  if (isLoggedIn) {
    console.log('Verified User.');
  } else {
    replace('/login');
  }
}

const routes = (
  <Provider store={store}>
    <Router history={browserHistory}>
      <Route path='/' component={App} onEnter={requireAuth}>
        <IndexRoute component={Dashboard}/>
        <Route path='login' component={Login}/>
      </Route>
    </Router>
  </Provider>
);
```

Is this a bug? how can I solve this?

**Comment by taion** [comment]
See https://github.com/rackt/react-router/issues/2897.

**Comment by seoyoochan** [comment]
@taion thanks for the answer, but i get this infinite redirection error, `Uncaught RangeError: Maximum call stack size exceeded` though. is there any workaround for this?

**Comment by taion** [comment]
Closing this to track #2910 instead.
