### ISSUE TITLE
Don't use StaticContainer in animations example

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2870]
Per discussion on https://github.com/facebook/react/issues/2517#issuecomment-169787456, we should not be encouraging the use of `<StaticContainer>` to "freeze" routing state (for indicating links as active or not).

**Comment by taion** [comment]
I'm not sure how to do this, to be honest. The transition manager is mutable, so we can't easily freeze it on state.

It might be nice if `router.isActive` just took the current `location` as an argument.

Thanks @jimfb :p

**Comment by ryanflorence** [comment]
Yeah, the 2.0 changes set us up for a better `isActive`, also, I already removed static container from the example and just removed the links. its unlikely most apps are animating links that have active states anyway.

**Comment by taion** [comment]
Cool! Didn't notice that StaticContainer got dropped there.
