### ISSUE TITLE
Rename <Link>...</Link> to <Anchor>...</Anchor>

### ISSUE THREAD

**Issue by vanesyan** [rackt/react-router#2873]
Hello there! Thanks you for such a great project, you are awesome guys! I see that there is a plan to ctu a new major release of `react-router` and it's mean we can break compatibility with v1. So what about
renaming or deprecating and mapping `<Link to="...">...</Link>` to/with `<Anchor href="...">...</Anchor>`.
IMHO it's better name for such component and better align with html, as `<a href="...">...</a>` actually mean anchor and `<link href="...">` is a tag used to makes relationships between the current document and an external resource.

**Comment by david-crespo** [comment]
v2 will not be breaking backwards compatibility. See https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md

**Comment by timdorr** [comment]
`Link` is better because it indicates intent. `Anchor` indicates establishing an anchor link to a particular place on the page, which is not what we're doing. I think the semantics of intent are more important than matching the HTML standard.

**Comment by vanesyan** [comment]
@timdorr Hey, thanks for the answer, but can you also re-open the issue to let other collaborators give their opinions...

Romain,
Cheers

**Comment by taion** [comment]
I agree with @timdorr.

`<a>` in HTML is a legacy thing – it used to be the case that these could serve as anchors for hyperlinks. They're not even usable as anchors any more in HTML5, and our `<Link>`s certainly aren't intended as anchors.
