### ISSUE TITLE
onEnter & replace: replace wants state as first arg in rc4

### ISSUE THREAD

**Issue by alexfedoseev** [rackt/react-router#2877]
I'm upgrading app to `2.0.0-rc4` and notice an issue with `onEnter` hook:

```js
(nextState, replace) => replace('/foo') // <--- throws
(nextState, replace) => replace(null, '/foo') // <--- ok
```

Looks like it is an issue in `rc4`: https://github.com/rackt/react-router/blob/v2.0.0-rc4/modules/Redirect.js#L41
And it's fixed in master: https://github.com/rackt/react-router/blob/master/modules/Redirect.js#L41

If I get it right, issue can be closed. Reporting just in case :)

**Comment by taion** [comment]
Yes, you'll see that I made this change after rc4 was cut.
