### ISSUE TITLE
Consider Adding Babel6 Dynamic Routes Info

### ISSUE THREAD

**Issue by mjrussell** [rackt/react-router#2881]
I have an app with dynamic routing and recently tried upgrading to babel 6 and was stuck with . Took me a while to figure out that because require no longer imports the default automatically, my async route config was wrong. Here's a similar SO https://stackoverflow.com/questions/33847789/react-router-dynamic-routes-not-rendering-component/33861495#33861495

Would it be worth updating the docs so that the example such as:

```
getComponents(location, callback) {
    require.ensure([], function (require) {
      callback(null, require('./components/Course'))
    })
  }
```

Includes a line (before or after) that if you use Babel6 you will need  `require('./components/Course').default`?

If so, I can submit a quick PR

**Comment by mjrussell** [comment]
Also I wonder if there's a way to add a warning on getComponent/getComponents that no Component was returned (undefined or null) instead of having it complain: "The root route must render a single element". Thats correct, but harder to track down the source of the problem

**Comment by taion** [comment]
Our examples w/r/t dynamic routes explicitly avoid ES6 modules for exactly this reason: https://github.com/rackt/react-router/commit/e183fcde7cec6c7dd2a984a98d4eea7dd8890580.

**Comment by mjrussell** [comment]
Ah ok, then its all user error then :smile: 

Is it possible to add a warning like I mentioned or would this be impractical since there no different between "not loaded yet" and "no component returned from getComponent(s)"

**Comment by taion** [comment]
Seems like a good idea – but I'm watching AGDQ right now, and I know where we fixed the examples offhand, but not where we make that check.

**Comment by taion** [comment]
We can't actually do this in general – it's valid for a route to not have components configured. Otherwise I don't think we should be documenting how Babel 6 transpiles ES6 modules here – seems a bit out of scope to me.

**Comment by mjrussell** [comment]
@taion what about if the getComponent(s) is defined it should return a valid element(s)?

I understand you might make `<Route path='/'>` or something like that without defining a component, but if you define the function it seems like it would be a good check to make sure that it returned the route. Could just compose the functions passed in with a warning check when it is called.

**Comment by taion** [comment]
It's not invalid for `getComponent` to return `null`, though. It doesn't break anything so long as at least one route renders something.
