### ISSUE TITLE
Set declarative options by route

### ISSUE THREAD

**Issue by acjay** [rackt/react-router#2894]
As far as I can tell, the API doesn't yet support a simple way to have routing parameters set by the route configuration. For example, I might have a wiki, which could have an meta routes for each page:

```
  <Route path="/" component={WikiComponent}>
    <Route path=":page" options={ { mode: 'read' } }>
      <Route path="edit" options={ { mode: 'edit' } } />
      <Route path="talk" options={ { mode: 'talk' } } />
  </Route>
```

Let's say I designed the app so that the root component is the same, but throughout the app, different components will modify their behavior based on this mode property. Also, I want to render universally, so I want to be able to access the mode property via `match`, because perhaps I want to prefetch some data based on mode. Is there a way to do this? The idea of reparsing the URL elsewhere to infer the mode smells, if the route config should be the source of truth.

**Comment by taion** [comment]
The route object is on `this.props.route` on the route component. In your case, it'd be e.g. `this.props.route.options`.

BTW, @dblock pointed me at your redux-react-controller repo on the NYCTech Slack – you should take a look at discussions regarding the future of context, specifically from e.g. https://github.com/rackt/react-router/issues/2646#issuecomment-165938198; I believe the pattern that you use is at meaningful risk of breaking in future React releases.

**Comment by acjay** [comment]
Ah, great! I'm not sure if I missed something when scanning the docs (and I just rescanned them again), but did not realize this was the case. The structure `renderProps` doesn't appear to be explained at all, other than as something you need to pass intact to `RouterContext`.

In case someone else does a similar thing, I'm using this like:

```
// routes:

<Route path="/" component={WikiComponent}>
  <Route path=":page" mode="read" } }>
    <Route path="edit" mode="edit" />
    <Route path="talk" mode="talk'" />
</Route>

// in `match`:
function routeProp(routeObjects, propName) {
  return routeObjects.reduce((last, route) => route[propName] || last);
}

match({ routes, location: req.url }, (routeError, redirectLocation, renderProps) => {
  //...
  const mode = routeProp(renderProps.routes, 'mode');
  //...
}
```

**Comment by taion** [comment]
You're right – we probably need a more advanced "server rendering" guide that covers use cases beyond "feed `renderProps` as an opaque object into `<RouterContext>`).

**Comment by acjay** [comment]
Re: redux-react-controller, thanks for the info.

> "React 15 is only going to allow components to export only one object to "context" (we only want one anyway)

seems particularly applicable. Sounds like a good change, to prevent `context` from being one big swamp. Not too concerned though, I'd already been considering refactoring using [recompose](https://github.com/acdlite/recompose)'s [`withContext`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withcontext) to bridge from `context` to `props`. Obviously, that decorator will be at risk too, but with the change, client code won't really need to be able to worry, and I'll work around the plumbing changes in the library.
