### ISSUE TITLE
[Question] createPath(string, params)

### ISSUE THREAD

**Issue by CosticaPuntaru** [rackt/react-router#2895]
is there a way to generate a path?
example:
```javascript
var path = router.generatePath('/list/:itemId/edit'. {itemId: 1});
console.log(path); // /list/1/edit
```

**Comment by CosticaPuntaru** [comment]
found my answer:

import {formatPattern} from 'react-router/lib/PatternUtils';

**Comment by JAndritsch** [comment]
Is this really resolved? I don't see `formatPattern` anywhere. I did find a `generatePath` function, however it doesn't appear to be part of the main exports in the `index` file. Maybe that's just a miss?

**Comment by JAndritsch** [comment]
I think this is a bug. I've submitted #5701.
