### ISSUE TITLE
Cannot read propery 'query' of undefined. Async onEnter.

### ISSUE THREAD

**Issue by andrewcoelho** [rackt/react-router#2897]
I'm trying to protect some async routes but am getting the following error when attempting to navigate to those routes: 

`Cannot read property 'query' of undefined` @ useQueries.js:127

I'm using `"react-router": "^2.0.0-rc4"`

Here is my setup:

Client:

    import { router, browserHistory } from 'react-router'
    import routes from './RootRoute'

    render(
      <Router routes={routes} history={browserHistory} />,
      root
    )

Root route:

    {
      path: '/',
      component: App,
      getChildRoutes(location, cb) {
        require.ensure([], (require) => {
          cb(null, [
            require('./Protected').default
          ])
        })
      }
    }

Protected routes:

    {
      path: 'protected',
      component: Protected,
      getChildRoutes(location, cb) { ... },
      onEnter(nextState, replace) {
        if (!auth.loggedIn()) {
          replace({
            pathname: 'login',
            state: { nextPathname: nextState.location.pathname }
          })
        }
      }
    }

Is this a bug or a problem with my code?

**Comment by taion** [comment]
The syntax you're using for `replace` was only added in https://github.com/rackt/react-router/pull/2855, which was after rc4.

**Comment by zweicoder** [comment]
@taion encountered this problem as well using `"react-router": "^1.0.3"` after following the auth-flow [example](https://github.com/rackt/react-router/blob/1.0.x/examples/auth-flow/app.js). Where can I find out what the correct syntax should be?

**Comment by andrewcoelho** [comment]
@zweicoder heres what I ended up using
```
onEnter(nextState, replaceState) {
  if (!auth.loggedIn()) {
    replaceState(null, 'login')
  }
}
```

**Comment by zweicoder** [comment]
@andrewcoelho Hey, that worked! I'm using `replace({nextPathname: nextState.location.pathname}, '/login')` to track the next state. Thanks a bunch!
