### ISSUE TITLE
There should be a way to hook into any route request regardless whether there is or isn't a route change

### ISSUE THREAD

**Issue by m4nuC** [rackt/react-router#2912]
I can't seem to find anywhere a hook that will get called even if `computeChangedRoutes` returns no routes ? It seems that if the user requests a route, there should be a way to hook into that?

**Comment by ryanflorence** [comment]
What are you trying to do in non-technical, product language?

What do you mean by "user requests a route"?

**Comment by m4nuC** [comment]
> What do you mean by "user requests a route"?

I mean user clicking on a link. 

>What are you trying to do in non-technical, product language?

I have state that needs to be reseted every time a route is requested. The concrete case is an expendable menu that retracts itself when landing on the requested page. 
Since `onEnter` it doesn't get triggered if `computeChangedRoutes ` finds no match the menu wont retract if the requested is the current one. 
A use case is: User is on his profile page, open the menu then click on *profile* link. In that case I'd expect the menu to retract as well.

**Comment by ryanflorence** [comment]
It's just a component, you detect "changes" the same way as any other component:

```js
// in a route component:
  componentWillReceiveProps(nextProps) {
    if (nextProps.location !== this.props.location) {
      // location changed, do your menu thing
    }
  }
```

**Comment by m4nuC** [comment]
Ok thanks but my case for when the route changes, `onEnter` does the trick. I have filters in place and that works great. 

```
const applyOnEnterMiddlewares = fp.curry((store, route) => {

	route.onEnter = (nextState, replaceState) => {
			console.log('entering route')
		// Display delayed notificatinos
		filters.processPendingNotifications(store, route)(nextState, replaceState);

		// Dispatch title change action
		filters.dispatchPageChange(store, route)(nextState, replaceState);

		// Checks for auth
		route.requireAuth && filters.applyAuth(store, route)(nextState, replaceState);

		// isOwner
		route.requireOwnership && filters.checkOwnership(store, route)(nextState, replaceState);
	}
})
```

I was hoping to be able to apply logic here as well. An hook like `onRequest` would be nice.

**Comment by taion** [comment]
Dupe https://github.com/rackt/react-router/issues/2547
