### ISSUE TITLE
IndexRedirect not working with basename in v2.0.0-rc5 as it used to with v1.0.3

### ISSUE THREAD

**Issue by oanylund** [rackt/react-router#2917]
I have a basename '/basename' set up with my browserhistory.

This is part of my route setup:

```
...
<Route path='birthdays' component={Birthdays}>
  <IndexRedirect to='calendar'/>
  <Route path='calendar' component={BirthdayCalendar}/>
  <Route path='list' component={BirthdayList}/>
  <Route path='add' component={BirthdayAdd}/>
</Route>
...
```

In v1.0.3, hitting the route '/basename/birthdays' would redirect to '/basename/birthdays/calendar'.
After upgrading to v2.0.0-rc5 this route redirects to '/birthdays/calendar'.

Everything else than the indexRedirect works as expected.

**Comment by oanylund** [comment]
This is my history setup:

```
import { createHistory } from 'history'
import { Router, Route, IndexRoute, IndexRedirect, useRouterHistory } from 'react-router'

...

const browserHistory = useRouterHistory(createHistory)({ basename: '/basename'})

...
```

**Comment by taion** [comment]
This works fine for me. Make sure you have the correct version of `history` installed.

**Comment by oanylund** [comment]
I am running history at v1.17.0. Is that not the correct one?

**Comment by taion** [comment]
Ah. I see. You actually need https://github.com/rackt/history/pull/200.

I'll leave this open until we merge that.

**Comment by oanylund** [comment]
Thank you taion.
v1.17.0 was a peerdep from react-router-bootstrap.

**Comment by taion** [comment]
Closing now that https://github.com/rackt/history/pull/200 has been merged.
