### ISSUE TITLE
<Link to='/url?param=whatever'/> no longer matching `/url` in 2.x

### ISSUE THREAD

**Issue by mhart** [rackt/react-router#2920]
We have routes like `<Route path='/url' ... />` and Links that have `<Link to='/url?param=whatever' />`

In 1.x this works fine. In 2.x – it works for all POP actions, like back/forward navigation – but for PUSH actions, like clicking the link, it doesn't match the route.

Logging in `matchRoutes` shows the location being passed in like this when you click the link:

```json
{
  "pathname":"/url?param=whatever",
  "search":"",
  "hash":"",
  "state":null,
  "action":"PUSH",
  "key":"3zxs8m",
  "query":{},
  "$searchBase": {
    "search":"",
    "searchBase":""
  }
}
```

But if you click back from there, and forward again, it matches fine:

```json
{
  "pathname":"/url",
  "search":"?param=whatever",
  "hash":"",
  "state":null,
  "action":"POP",
  "key":"c5blde",
  "query":{"param":"whatever"},
  "$searchBase": {
    "search":"?param=whatever",
    "searchBase":""
  }
}
```

Poking around quickly I wonder if it's to do with the introduction of `createLocation` in [this commit](https://github.com/rackt/react-router/commit/f6870b2c0790fdd2122ca1a5d57b84a4b9a8c4f0)

**Comment by taion** [comment]
Yes, this got broken at some point between https://github.com/rackt/react-router/pull/2658/files#diff-c7fd3a70340dad9a76157e1ad2e35baaR117 and https://github.com/rackt/react-router/pull/2659/files#diff-c7fd3a70340dad9a76157e1ad2e35baaR24. I guess we hadn't covered this with tests.
