### ISSUE TITLE
Documentation error for Custom Query

### ISSUE THREAD

**Issue by gabrielenosso** [rackt/react-router#2924]
The example from the doc is:

const appHistory = createAppHistory({
  parseQueryString: parse,
  stringifyQueryString: stringify
})

You can see it here: https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing

But the parameter to pass to appHistory is "stringifyQuery" and not "stringifyQueryString"!

So it should be:

const appHistory = createAppHistory({
  parseQueryString: parse,
  stringifyQuery: stringify
})

**Comment by ryanflorence** [comment]
Want to hit the "edit" button on the file in github and fixing the typo? thanks :)

**Comment by gabrielenosso** [comment]
PR created :)

**Comment by taion** [comment]
Thanks!
