### ISSUE TITLE
ComponentLifecycle not working according to documetation

### ISSUE THREAD

**Issue by trsh** [rackt/react-router#2927]
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md

At step 2 "componentDidUpdate" is also called on "Home" :(

**Comment by taion** [comment]
If it is, that's because of e.g. redux-simple-router, not because of anything here.

**Comment by trsh** [comment]
@taion how this help me?

**Comment by trsh** [comment]
@taion I do not use any redux-simple-router or whats ever. Can you check this bug before trashing it?

**Comment by taion** [comment]
I did. If you want to check it yourself, look at the active-links example. You are doing something incorrect on your side.

**Comment by trsh** [comment]
@taion please recheck with <Transition transitionName="pathchange" transitionEnterTimeout={451} transitionLeaveTimeout={501}>, that is using "import ReactCSSTransitionGroup from 'react-addons-css-transition-group'". Bug seems to be gone, when not using transitions.
