### ISSUE TITLE
ComponentLifecycle not working according to documetation with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by trsh** [rackt/react-router#2929]
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md

Tested with https://github.com/rackt/react-router/tree/master/examples/animations, adding componentDidUpdate events. 

When routing from page 1 to page 2 "componentDidUpdate" is called on Page1 component.

**Comment by taion** [comment]
Invalid per https://github.com/rackt/react-router/issues/2927
