### ISSUE TITLE
Performance regression from 1.x

### ISSUE THREAD

**Issue by mhart** [rackt/react-router#2932]
Ok, following on from #2922 I did some testing and there are some performance differences between 1.x and 2.x – I've narrowed down a small benchmark to illustrate:

```js
var React = require('react')
var ReactDOMServer = require('react-dom/server')
var ReactRouter = require('react-router')
var RouterContext = ReactRouter.RouterContext || ReactRouter.RoutingContext

var routes = React.createElement(ReactRouter.Route, {
  path: '/',
  component: React.createClass({
    render: function() {
      return React.createElement('div')
    }
  })
})

var start = Date.now()

matchBench(0)

function matchBench(i) {
  if (i >= 10000) return console.log('%d ms', Date.now() - start)

  ReactRouter.match({routes: routes, location: '/'}, function(err, redirectLocation, renderProps) {
    if (err || redirectLocation) throw (err || new Error('Unexpected redirectLocation'))
    if (renderProps) {
      ReactDOMServer.renderToString(React.createElement(RouterContext, renderProps))
    }
    process.nextTick(() => matchBench(i + 1))
  })
}
```

Here are the results of five runs on Node.js v4.2.4:
```
v1.0.3:
3117 ms
3167 ms
3194 ms
3229 ms
3289 ms

v2.0.0-rc5:
4062 ms
4171 ms
4181 ms
4361 ms
4790 ms

loopAsync-unwind-recursion:
4119 ms
4120 ms
4273 ms
4239 ms
4328 ms
```

So v2 is about 30% slower in this case.

If you eliminate the rendering by matching on, say, `location: '/a'`, you see a ~50% difference:

```
v1.0.3:
650 ms
668 ms
686 ms
736 ms
769 ms

v2.0.0-rc5:
1033 ms
1056 ms
1059 ms
1079 ms
1124 ms

loopAsync-unwind-recursion:
1038 ms
1068 ms
1069 ms
1107 ms
1119 ms
```

It's still unclear to me whether this benchmark highlights what's causing the performance differences in our app, so this may not be anything to be concerned about – just thought I'd highlight it anyway.

**Comment by timdorr** [comment]
Just so I'm 100% on this, is that showing that they slow down over time? Sounds like an associated memory leak, if so.

**Comment by mhart** [comment]
@timdorr no sorry, I sorted the results so it's easier to see the median

**Comment by mhart** [comment]
@timdorr each run was a separate node invocation

**Comment by timdorr** [comment]
Did you give it any warmup?

**Comment by taion** [comment]
Simpler benchmark with some basic warmup that still shows the issue:

```js
var React = require('react')
var ReactDOMServer = require('react-dom/server')
var ReactRouter = require('react-router')
var RouterContext = ReactRouter.RouterContext || ReactRouter.RoutingContext

var routes = React.createElement(ReactRouter.Route, {
  path: '/',
  component: React.createClass({
    render: function() {
      return React.createElement('div')
    }
  })
})

function noop() {}

function runBench() {
  for (var i = 0; i < 10000; ++i) {
    ReactRouter.match({ routes: routes, location: '/' }, noop);
  }
}

// Warmup.
runBench()

var start = Date.now()
runBench()
console.log('%d ms', Date.now() - start)
```

**Comment by taion** [comment]
@mhart Can you confirm if you're using `NODE_ENV=production`? I see the difference nearly go away when I do that. We have a _lot_ of debug checks in 2.0.0 for deprecated usages.

**Comment by mhart** [comment]
@taion ahhhh, really good point. I wasn't.

**Comment by mhart** [comment]
I see the same thing – ok, closing this.

(we do use `NODE_ENV=production` in our app – this benchmark's clearly not illustrating anything that we're seeing though)
