### ISSUE TITLE
async-props interferes with dynamic segments

### ISSUE THREAD

**Issue by bdefore** [rackt/react-router#2941]
I've made a fork where I was trying to build an async-props example with RR2, using its latest from master, but noticed that dynamic segments are not working correctly. The address bar will update but the next view will not load. Hitting the back button at that point will cause it to render the view that previously would have rendered.

Here's my example: https://github.com/bdefore/react-router/blob/async-props-example/examples/async-props/app.js

The only difference between it working correctly and causing this behavior is in removing AsyncProps from `render`:

```
<Router render={(props) => <AsyncProps {...props} />} history={browserHistory}>
```

vs:

```
<Router history={browserHistory}>
```

**Comment by taion** [comment]
Please file this on the async-props repo.

**Comment by bdefore** [comment]
https://github.com/rackt/async-props/issues/50
