### ISSUE TITLE
Nested query params are no longer supported

### ISSUE THREAD

**Issue by IanVS** [rackt/react-router#2942]
The change within `history` from `qs` to `query-string` (https://github.com/rackt/history/issues/171) introduced what might be considered a breaking change between react-router `1.0.2` and `1.0.3`.  Previously, we could use nested params like `?foo[bar]=2`, and this would be parsed into `{foo: {bar: 2}}`.    This is similar to how jQuery would deparam the string.  However, this no longer works, as `query-string` intentionally [does not support nesting](https://github.com/sindresorhus/query-string#nesting). This may be worth at least a changelog entry or release note, to prevent others from being confused the same way I was when my URLs stopped working after a patch version change.

**Comment by taion** [comment]
Dupe https://github.com/rackt/history/issues/196. This is in `history` so it's not in RR proper. `history` warns when you try to do this, though – and you can always manually switch back to `qs`.
