### ISSUE TITLE
question about 0.13.x doc 

### ISSUE THREAD

**Issue by uinika** [rackt/react-router#2944]
Hi, guy.

i found a question about example in react document.
https://github.com/rackt/react-router/blob/0.13.x/doc/00%20Guides/Router%20Overview.md

if i take below configration. it will be ok when i enter /inbox/message/232.
    <Route path="about" handler={About} />
    <Route path="inbox">
      <Route path="message/:id" handler={Message} />
    </Route>

but your markdown has a little difrent. i think it is wrong.
    <Route path="inbox" handler={Inbox}>
      <Route path="messages/:id" handler={Message}/>
    </Route>

PLS mend this , if it is really clerical error.

**Comment by taion** [comment]
v0.13.x is no longer supported.

**Comment by uinika** [comment]
but 2.x is RC right now. what time is the stable time?

**Comment by taion** [comment]
1.x is stable. 2.x is almost stable and is preferred, though.
