### ISSUE TITLE
[feature] add a data object to each router state

### ISSUE THREAD

**Issue by BerndWessels** [rackt/react-router#2949]
Hello

We need a way that routes can store data.

So that each route/page we visit can store local modifications temporarily (for the lifetime of the application).
That enables us to move between routes/pages and when coming back to a route/page it can restore itself with modifications the user has made before moving away from that route/page.

At the moment everybody has to write their own way like constantly storing local changes to a page in local storage to be able to retrieve them later.
But having a way for the router to provide a data object for each route would make things much easier.

I think the best would be to add a routeData property - the routes component can then store everything it wants into `this.props.routeData` and retrieve it from there again everytime the user comes back to this route.

Alternatively we could add a `data` property to each route - that would allow the component to see its own data and the parents routes data.

**Comment by taion** [comment]
That's out of scope. Use Flux for that.

**Comment by timdorr** [comment]
Or just put it on `location.state` when you push/replace your location.

**Comment by BerndWessels** [comment]
@timdorr I would love to use `location.state` - but it seems that even though in my component I do

    componentWillReceiveProps(nextProps) {
        this.props.location.state = { number: 5 }
    }

The next time I come to this route the `location.state` is `null` again.

    componentWillMount() {
        console.log(this.props.location);
    }

Or am I doing something wrong?

**Comment by taurose** [comment]
Imo `location.state` is more for state that's created by the source anchors (`<Link>`) to allow different anchors to pass different state for showing different content depending on where the user came from.

What you're looking for is storing data based on `location.key`, preferably in sessionStorage, since you don't need to worry about lifetime and cleanup then.

```
componentWillReceiveProps(nextProps) {
    sessionStorage.setItem('myApp-' + this.props.location.key, JSON.stringify({ number: 5 }));
}

componentWillMount() {
    var state = JSON.parse(sessionStorage.getItem('myApp' + this.props.location.key));
    console.log(state);
}
```

**Comment by BerndWessels** [comment]
Thank you @taurose .

You are right, and `sessionStorage` actually covers my particular use case very well. Since my whole app is based on `relay/graphql` only I really don't want to introduce any other kind of `flux store` to it.

From `ui-router` I was just used to a more complete router that has all these things build in already, that's why I suggested that feature here.

Thanks again
Bernd
