### ISSUE TITLE
Nest multiple components on the same route

### ISSUE THREAD

**Issue by madshargreave** [rackt/react-router#2954]
I have the following routes defined

```
    const routes = (
      <Router history={history}>
        <Route path='/' component={Landing}>
          <Route path='' component={Invitation}/>
          <Route path='signin' component={Signin}/>
        </Route>
        <Route path='*' component={NoMatch}/>
      </Router>
    );
```

I would like that when visiting the root `/` route, that the `Invitation` component gets rendered inside the `Landing` component, but I havent found a way to do this without using a nested route/url

Any ideas?

**Comment by timdorr** [comment]
Use IndexRoute.
