### ISSUE TITLE
onEnter hook from the docs

### ISSUE THREAD

**Issue by Diokuz** [rackt/react-router#2955]
Who can tell me what exactly onEnter hook from [Router Configuration](https://github.com/rackt/react-router/blob/latest/docs/guides/basics/RouteConfiguration.md) page do?

```js
{ path: 'messages/:id',
            onEnter: function (nextState, replaceState) {
              replaceState(null, '/messages/' + nextState.params.id)
            }
          }
```
Its looks to me like it do nothing: just replacing nextState with nextState.
And I suppose that it will be triggered infinite times (recursion).
Am I right?

**Comment by timdorr** [comment]
You can either cancel the navigation or redirect by replacing state.
