### ISSUE TITLE
suggestion: allow onEnter lifecycle method to return false to cancel routing

### ISSUE THREAD

**Issue by jhudson8** [rackt/react-router#2957]
IMHO, this might be a better way to handle things like authentication.  It could look something like this to avoid any component rendering when not necessary

```
function requireAuth(path, component) {
  function onEnter () {
    if (!isAuthenticated()) {
      // we are trying to hit an secure route and we aren't authenticated
      // navigate to login page

      // cancel current routing
      return false;
    }
  }

  return <Route path={path} component={component}/>
}

<Router>
  {requireAuth('/foo', SomeComponent)}
</Router>
```

**Comment by taion** [comment]
"Cancel routing" is not well-defined; this `onEnter` hook runs after the `history` transition completes. If you want to "go back", just call `history.goBack()` from there.

**Comment by jhudson8** [comment]
sorry, no offense intended, but what is not well defined about cancelling routing?  I don't know how else to say that the routing (component rendering which is associated with the current browser URI) should be halted.

This would prevent the component (bound to the current route) from rendering which would be beneficial because that component might trigger an XHR request that requires an authenticated state.

Or, is there already a way to do this that I'm not aware of?  Please help me understand because it seemed that the [auth-flow](https://github.com/rackt/react-router/tree/master/examples/auth-flow) example would still have this problem.

Thanks very much for your time and help.

**Comment by taion** [comment]
And then what? You can't just halt "component rendering which is associated with the current browser URI" unless you want to render a blank page or something. At the point that `onEnter` hooks are run, you've already transitioned to the next URL – thus the `onEnter` hook actually has to take the user _somewhere_.

**Comment by jhudson8** [comment]
Yes, correct, I agree that you would end up with a blank page *if you did not do anything else*.  The intent here would be to allow for a new route to be triggered (for example, a login page) that would be presented instead.

I would not return from this lifecycle method if I did not intend to handle the routing in some other way (to avoid a blank page).

Again, if I'm missing something and react-router can already do something like this, please let me know - not trying to be difficult.  Thanks.

**Comment by jhudson8** [comment]
Sorry, I should be more clear.  I previously said "intent here would be to allow for a new route to be triggered" - all I mean by that statement is that, once you return false from the `onEnter` method, you are free to make something else happen.

In other words, I'm not suggesting that the `onEnter` method itself expose any additional functionality outside of just halting the current routing.

**Comment by taion** [comment]
You don't need it – just handle this in `render` on the component attached to the route, or "wrap" the protected routes with a component that does this.

**Comment by jhudson8** [comment]
ok, IMHO that seems like a hack (referring to having to use the render method of a component to trigger a route change) but if that is the suggested pattern, that is what I will use.  Thanks for your time.

**Comment by taion** [comment]
You're looking to control what renders from that route (i.e. block rendering child components) – that should exactly be handled by the route component, not the `onEnter` hook.

**Comment by jhudson8** [comment]
agreed, if you don't want the browser url to change to reflect a login page - that would be appropriate.  Seems like a hack IMHO though if you do want the browser URL to reflect the login page.  But I'll stop beating this horse to death.  Again, thanks for your help.
