### ISSUE TITLE
pass location.state in server rendering redirectLocation?

### ISSUE THREAD

**Issue by ilionic** [rackt/react-router#2964]
Following `auth-flow` example and Server Rendering guide I am wondering how to combine those ways and keep `location.state` for nextPathname. 
If protected url accessed directly, `redirectLocation` in `match` contains state at first then redirect happens
`res.redirect(302, redirectLocation.pathname + redirectLocation.search)`
and state is reset, so after auth there is no redirect back to the protected page.

**Comment by timdorr** [comment]
You should store your state in some other form, such as Redux.

**Comment by benwiley4000** [comment]
@timdorr this is a helpful suggestion. However, would you be able to elaborate on a standard scheme for doing this? It seems like a fairly ordinary concern that should perhaps be documented or included in an example. In the meantime, I'd love to hear your advice.

**Comment by benwiley4000** [comment]
Pending any response I've chosen to include the name of the destination path after auth as part of the query string in the redirect request on the server. That way the client knows a redirect took place, and will know where to transition after auth. I considered using redux-router, but this seems like a much cleaner solution that can be easily compatible with react-router-redux.
