### ISSUE TITLE
when using browserHistory, router.push() reloads entire page.

### ISSUE THREAD

**Issue by julienvincent** [rackt/react-router#2975]
This issue is similar to [#2832](https://github.com/rackt/react-router/issues/2832) which was closed with no explanation as to why this is happening. Running chrome on iOS 9, router.push() will reload entire page. This does not happen on Safari.

**Comment by julienvincent** [comment]
Confirmed, happens with react-router examples.

**Comment by taion** [comment]
https://github.com/rackt/history/pull/208

**Comment by julienvincent** [comment]
Thanks
