### ISSUE TITLE
<Redirect/> drops queries

### ISSUE THREAD

**Issue by ulyssesz** [rackt/react-router#2977]
Using `v2.0.0-rc5`, redirects drop the queries.

e.g.
Code
```
...
   <Redirect from='*' to='/404' />
...
```

Link:
`localhost:3000/test?hello=world`

Expected link: (Words in `v1.0.1`)
`localhost:3000/404?hello=world`

Actual link:
`localhost:3000/404`

**Comment by taion** [comment]
Same as https://github.com/rackt/react-router/issues/2917, fixed on master of history.
