### ISSUE TITLE
Live React Load Causes Warning

### ISSUE THREAD

**Issue by SC7639** [rackt/react-router#2982]
Using react-router with livereactload causes a warning that renders the livereloading unusable. I'm not sure how to proceed as I'd like to be able to use both in my app. Is there a way I can get them both to coexist?

```Warning: You cannot change <Router routes>; it will be ignored```

**Comment by timdorr** [comment]
You can hot reload routes. At least not yet... 

If you have a wrapper component around your Router, don't do that. Instead, just have a function or object export that contains only your routes and feed that into your Router, which should be in the same spot that you ReactDOM.render.

**Comment by jeffshaver** [comment]
@timdorr I don't understand what the solution to this is? Is there one?

**Comment by timdorr** [comment]
Typo'ed. You **can't** hot reload routes yet.

**Comment by jeffshaver** [comment]
@timdorr thanks for the correction. I think I am missing some key piece of info though. If I have a route like this:

```jsx
<Router history={history}>
  <Route
    component={App}
    path='/'
  >
    <Route
      component={Analytics}
      path='analytics'
    />
  </Route>
</Router>
```

Does that mean I can't hot reload the `Analytics` component? Is the solution to make a wrapper around the `Analytics` component so that it isn't referenced by the route itself?

**Comment by timdorr** [comment]
You can hot reload the route components all you want. The actual route elements themselves cannot be hot reloaded. Basically, you can't hot reload a module containing routes.

**Comment by jeffshaver** [comment]
@timdorr So maybe my problem is different? I keep getting these errors when i try to modify the `Analytics`.

```
"<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/rackt/react-redux/releases/tag/v2.0.0 for the migration instructions." bundle.js line 98 > Function:65:1

Warning: [react-router] You cannot change <Router history>; it will be ignored bundle.js line 98 > Function:50:9

Warning: [react-router] You cannot change <Router routes>; it will be ignored
```

Routes are defined here: https://github.com/jeffshaver/safe-app/blob/finish-analytics-component/src/js/index.jsx

Analytic Component is here: https://github.com/jeffshaver/safe-app/blob/finish-analytics-component/src/js/components/Analytics.jsx

Event added the module.onReload stuff to my store: https://github.com/jeffshaver/safe-app/blob/finish-analytics-component/src/js/configureStore.js

The smallest of changes to Analytics.jsx throws those errors in the console

**Comment by timdorr** [comment]
You're using browserify for hmr? I have never used that before, so you're on your own. It looks like it's trying to hot reload your entry point. But that's just a guess.

**Comment by jeffshaver** [comment]
@timdorr i actually tried switching to webpack and got the same messages. If you could help if i had webpack, than i can switch it over.

**Comment by jeffshaver** [comment]
@timdorr so i finally got webpack workign and am getting similar errors about the parent elements not knowing how to reload themselves...

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
bundle.js:67847 [HMR]  - ./src/js/components/AnalyticSelect.jsx
```

Routes are defined here: https://github.com/jeffshaver/safe-app/blob/webpack/src/js/index.jsx

Analytic Component is here: https://github.com/jeffshaver/safe-app/blob/webpack/src/js/components/Analytics.jsx

Event added the module.onReload stuff to my store: https://github.com/jeffshaver/safe-app/blob/webpack/src/js/configureStore.js

**Comment by timdorr** [comment]
You're looking for react-transform then. That's here https://github.com/gaearon/react-transform-hmr and here https://github.com/gaearon/babel-plugin-react-transform. If you have issues with that, you need to take it up with the appropriate channels. A closed issue on an unrelated project isn't best. I'd post on StackOverflow or join up in Reactiflux.

**Comment by jeffshaver** [comment]
@timdorr thanks! that worked. sorry if this was an inappropriate place. thanks for the help

**Comment by jeffshaver** [comment]
@timdorr thanks! that worked. sorry if this was an inappropriate place. thanks for the help
