### ISSUE TITLE
Promise in an onEnter hook causes TypeError in component render to be swallowed.

### ISSUE THREAD

**Issue by tybro0103** [rackt/react-router#2990]
# Summary

A promise is used in an `onEnter` hook. It resolves after one second and invokes `done()`, as it should. There's an intentional run-time error in one of the component's `render()`. Inside `match()`'s callback, `error` is null, and `renderProps` is present. When attempting to `renderToString()` the error is encountered, but is somehow wrapped in a promise, and being swallowed. By enabling the promise lib's rejection tracking, you can confirm an unhandled rejection has happened.

Really, I can't tell if I'm handling something wrong, or if React Router is.

There's a bit more context here: https://gist.github.com/tybro0103/8c131f6e7b73741c08bf

# Relevant Code

### server.js

```javascript
// without this, you see no error at all!
require('promise/lib/rejection-tracking').enable();

app.get('*', (req, res, next) => {
  match({routes, location: req.url}, (error, redirect, renderProps) => {
    if (error) return next(error);
    if (redirect) return res.redirect(`${redirect.pathname}${redirect.search}`);
    if (renderProps) {
      let comp = <Html><RouterContext {...renderProps} /></Html>;

      // tmp fix is to wrap this in try/catch
      let html = renderToStaticMarkup(component);
      
      return res.send(`<!DOCTYPE html>${html}`);
    }
    next();
  });
});
```

### routes.js

```javascript
let onEnter = function(nextState, replaceState, done) {
  new Promise((resolve, reject) => {
    setTimeout(resolve, 1000);
  }).then(done, done);
};

export default (
  <Route path="/" component={App} onEnter={onEnter}>
    <IndexRoute component={Home}/>
    <Route path="about" component={About} />
  </Route>
);
```

### about.jsx

```javascript
export default class About extends Component {
  render() {

    // intentional error
    this.what.the();

    return <h2>About</h2>;
  }
}
```

**Comment by tybro0103** [comment]
I should add I'm using version 2 RC5

**Comment by taurose** [comment]
This is a general problem when using promises with a callback-based API. If you don't want the errors to be swallowed, you have to use `setTimeout`.

```js
let onEnter = function(nextState, replaceState, done) {
  new Promise((resolve, reject) => {
    setTimeout(resolve, 1000);
  }).then(
    () => setTimeout(() => done()),
    (err) => setTimeout(() => done(err))
  );
};
```

**Comment by taion** [comment]
What @taurose said, this is just a general promise-related consequence, nothing we can really do here.

**Comment by tybro0103** [comment]
&$@($ing promises. Good to know.

**Comment by ryanflorence** [comment]
broken promises ... so many broken promises.
