### ISSUE TITLE
upgrading to 2.0.0 Link with params not goes well

### ISSUE THREAD

**Issue by RainKolwa** [rackt/react-router#2993]
After upgrading to 2.0.0,I found that if I use` <Link to="/a?param=b"></Link>`,I would get a _Warning: [react-router] Location "/a?param=b" did not match any routes_,but if I refresh the page with url '/a?param=b',anything would be in the right way.

I compared with the state before and after refreshing page, and I found that routing.location.search comes to be empty before,but comes to be "?param=b" after, not sure if this caused the issue

====================
Already found the solution:
Maybe I should use:
`<Link to={{ pathname: '/a', query: { param: b} }}></Link>`

**Comment by ryanflorence** [comment]
@taion this sounds like a bug around the location descriptor stuff, I'd expect a string w/ a query to still parse correctly, can you confirm?

**Comment by taion** [comment]
This was fixed by https://github.com/rackt/react-router/pull/2921. It's not in Router RC5. How are we doing on history RC3?

**Comment by ryanflorence** [comment]
Michael has been traveling basically for a month straight, still has another week next week, so probably the week after that, unless we can find some time to do it at the hotel in san diego.

**Comment by taion** [comment]
Any chance of adding another publisher to `history` then? Either you or one of us?
