### ISSUE TITLE
Query of LocationDescriptor does not work with replace callback in onEnter hook

### ISSUE THREAD

**Issue by kmees** [rackt/react-router#2998]
When using an onEnter hook like
```
const onEnter = (nextState, replace) => { 
  replace({ pathname: '/foo', query: { bar: 'baz' }})
}
```
the `query` parameter does not get respected by [`history.createLocation`](https://github.com/rackt/history/blob/master/modules/createLocation.js) and is therefore missing in the resulting `UPDATE_LOCATION` action. i guess that is a bug?

**Comment by taion** [comment]
Fixed on master of history.
