### ISSUE TITLE
Navigation outside components does not trigger routerWillLeave

### ISSUE THREAD

**Issue by joscha** [rackt/react-router#3013]
Using this: https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md combined with https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ConfirmingNavigation.md does not seem to work.
The `routerWillLeave` method is called for "normal" navigation via `<Link...` but not for an automatically triggered one.

**Comment by timdorr** [comment]
Do you have an example repo I could take a look at?

**Comment by joscha** [comment]
unfortunately it is closed source, but I could create a sample showing the problem if needed.

**Comment by timdorr** [comment]
That would be extremely helpful. Particularly to show exactly how you're using it and expecting it to work.

**Comment by taion** [comment]
This doesn't reproduce for me against our `confirming-navigation` example.

Make sure you're using exactly the same history (i.e. not a custom history that just happens to be a `createBrowserHistory()`).

**Comment by joscha** [comment]
I just tried this again (rewrote the sample) as well and can't reproduce it any more either. Must have been something in my component. Thanks for checking up on this!
