### ISSUE TITLE
Pushing with a param doesn't work

### ISSUE THREAD

**Issue by zackify** [rackt/react-router#3017]
I'm not quite sure how to narrow this one down. Code looks like this:

```js
import { browserHistory } from 'react-router'

browserHistory.push('job/1/basic-info')
```
The root route object path is `'job/:jobId'`. When I push to a nested route with a param in between, the route does not update, but the url changes. If I take off the param and push to the route, it works correctly. Wish I could show a better way to reproduce. I'm fairly certain the problem is not async-props in this case.

**Comment by timdorr** [comment]
Push an absolute route. You need a slash in front.

**Comment by zackify** [comment]
@timdorr that was a mistake in my code example. Sorry about that. I am pushing the route correctly. Like I said, it works without a route parameter. As soon as it gets added, the url updates, but content does not change

**Comment by taion** [comment]
@zackify Any debug logging? That usually means the location didn't match. What do your routes look like?

**Comment by zackify** [comment]
@taion no, nothing in the console. It obviously matches because doing a hard reload shows the correct page.

**Comment by zackify** [comment]
I take out the route param, and push the route and pass the data through state and it works just fine. This route is nested if that matters. It's not ideal to pass this through the state either.

**Comment by zackify** [comment]
Here are video demos. Routes will not change with params. Work fine without. 

[Archive.zip](https://github.com/rackt/react-router/files/115191/Archive.zip)

**Comment by zackify** [comment]
Aha! a close-to-the-top level shouldComponentUpdate was blocking the page rerender, only when there was a route param. Very weird but it makes sense.
