### ISSUE TITLE
wrong pathname/search for `?/` when using dynamic navigation

### ISSUE THREAD

**Issue by Swatinem** [rackt/react-router#3029]
I have the url `http://localhost/?/`.

On initial load, this gives me the correct `{pathname: '/', search: '?/'}` (this matches what `window.location` does).

When navigating via `<Link>` or `browserHistory.push` however, I get the wrong `{pathname: '?/', search: ''}`

This is with react-router 2.0.0-rc5.

**Comment by taion** [comment]
Works fine for me against master.

**Comment by timdorr** [comment]
Which is to say this will probably get fixed by the next release.
