### ISSUE TITLE
Introduction App should actually work

### ISSUE THREAD

**Issue by zwhitchcox** [rackt/react-router#3035]
So, I just copied and pasted the app from the introduction,and it didn't work. Because `About` and `Inbox` were undefined. I have no idea how to make this work, and this is basically my starting point for creating a react app. It would be really great if the first sample actually worked, so I had something that worked to start from and build off of.

**Comment by taion** [comment]
Dupe https://github.com/rackt/react-router/issues/2933.

Though I should note that the introduction to React Router is just that – an introduction to React Router, not an introduction to React. And we have plenty of fully worked out, runnable examples.

**Comment by zwhitchcox** [comment]
Where are they?

**Comment by zwhitchcox** [comment]
And yeah, I've read an introduction to react and get the concept, but I wanted to make an app using react with your software. So, it would make sense to have a working example of how React works with your software.

**Comment by timdorr** [comment]
I'm going to spend a lot of this weekend writing docs for react-router so we're in a better place when 2.0 lands. rc6 should be the last one before that happens.
