### ISSUE TITLE
Scroll to top when clicking links (restore #121 for react-router 2)

### ISSUE THREAD

**Issue by boosh** [rackt/react-router#3037]
Seems like the same issue as #121 exists again with v2. Is there a good reason it was dropped? Is it intentional for us to have to add
```
componentDidUpdate() {
  this.getDOMNode().scrollTop = 0 ;
},
```
to every component?

**Comment by taion** [comment]
Dupe of a ton of other issues, search around.

**Comment by mjhamm75** [comment]
Adding the `onUpdate` to your `router` stops you from having to add the event to each component
```
<Router onUpdate={() => window.scrollTo(0, 0)} history={history}>
        {routes}
</Router>
```

**Comment by protoEvangelion** [comment]
@mjhamm75  Thank you!!!!!  I was having a lot of trouble finding a concise and correct answer for this. Much appreciated :)
