### ISSUE TITLE
Document the hooks

### ISSUE THREAD

**Issue by robcolburn** [rackt/react-router#3048]
I'm really trying to grok `onEnter` and `onLeave` hooks. Where do I put them? On the component, in the route tree, with a mixin, an HOC, …?

These seem like a good thing to help me avoid "Loading pages", but how do I accomplish this? There are boiler-plates, but then I've got to spend ten minutes figuring out some other app and if the author is down with server-side-rendering or doesn't care at all about that.

Does `onEnter` fire during server-side rendering, does `match()` wait for it?

Right now there are docs in the upgrade guides and some information in Glossary. None of this helps much.  Ok, enough complaining, I'm off to blow things up.

**Comment by taion** [comment]
https://github.com/rackt/react-router/issues/2933
