### ISSUE TITLE
NotFound route blocks for redirect routes when defined above the latter

### ISSUE THREAD

**Issue by nwinger** [rackt/react-router#3049]
Took me a while before figuring this out, and I'm not quite sure if this is an issue or just me doing it wrong. I seem to remember in earlier versions that one could define a `<NotFoundRoute> `before a `<Redirect> `route, and this would work fine. Where as now I need to explicitly place my `    <Route path="*" component={NotFound} />` as the last route for redirect to work.

```
import React from 'react';
import {IndexRoute, NotFoundRoute, Route, Redirect} from 'react-router';

const routes = (
  <Route path="/" component={App} >
    <IndexRoute component={Home} />
    <Route path="about" component={About} />
    <Route path="authors" component={AuthorPage} />
    <Redirect from="about-us" to="about" />
    <Route path="*" component={NotFound} />
  </Route>
);

export default routes;
```

Please do close this issue asap if I'm wrong, but consider updating the docs :smile:

**Comment by taion** [comment]
Is there anywhere where the docs say otherwise? All of our `path="*"` examples show that route at the bottom, I believe.

**Comment by nwinger** [comment]
@taion I suspect not, so might have been a misinterpretation from my side. For someone not used to working with routers like this, it might not be obvius. :) You can go ahead and close this issue as far as I'm concerned :smile:

**Comment by taion** [comment]
https://github.com/rackt/react-router/commit/1a81557c65b7561d095fabb5bf6337232a28a7a7
