### ISSUE TITLE
404 Error?

### ISSUE THREAD

**Issue by thomasvaeth** [rackt/react-router#3055]
```js
const {browserHistory, Router, Route, Link} = window.ReactRouter;

class App extends React.Component {
	render() {
		return (
			<div>
				<Router history={browserHistory}>
					<Route path="/" component={HomePage} />
					<Route path="about" component={About} />
				</Router>
			</div>
		);
	}
}
```

I can go to http://localhost:8000/ and render the application. And I can click on the navbar and go to the about page. But if I type http://localhost:8000/about into the address bar I get an Error response - error code 404. I am not sure what the problem is.

**Comment by timdorr** [comment]
https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#configuring-your-server

**Comment by suprMax** [comment]
@timdorr you've linked to 404

**Comment by timdorr** [comment]
It was moved: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#configuring-your-server

**Comment by suprMax** [comment]
Nice! Thanks!

**Comment by lejoss** [comment]
@timdorr please provide link, still linked to 404, thanks.

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server

**Comment by gabrielfgularte** [comment]
The error still happens to me, but only in Safari.

Here's my nginx conf:

```
server {
  server_name mysite.com;

  location = /favicon.ico {
    access_log off;
    log_not_found off;
  }

  location / {
    root /home/ubuntu/webapp/application;
    try_files $uri $uri/ =404;
  }

}
```

PS.: I've tried to put a `index.html` between `$uri/` and `=404` without success.

**Comment by mghazanfar** [comment]
@thomasvaeth  While stating your <Route>s, remember to wrap them in <Switch> tag so the error does not remain there. It is defined in the following link:
https://reacttraining.com/react-router/web/example/no-match

**Comment by abhisharkjangir** [comment]
Thanks @timdorr It works :)
