### ISSUE TITLE
Is there a way to tell wether the user just hit the back or forward button?

### ISSUE THREAD

**Issue by Ahrengot** [rackt/react-router#3072]
I'm trying to build animated transition between my views and for that I need to know if the user is moving forward or backwards in history. Is there any way, based on the props received from the router, to tell if the user just moved forwards or backwards in history?

If I look at `*routehandler*.props.location.action` that's always 'POP' for clicks on the back button as well as the forward button. If I manually trigger `history.push('some/path')` then the `action` reflects that by reading 'PUSH'. I'm not saying this is a bug, I'm just trying to figure out if I can tell which button in the browser the user clicked :)

**Comment by mjackson** [comment]
No, there currently isn't a way to tell if the back or forward button was used. See https://github.com/rackt/history/issues/36
