### ISSUE TITLE
Link that only updates the query (`this.updateQuery`)

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#378]
Very often you want a link that only updates one or a few parts of the query or params, having to reconstruct and then mutate the current stuff is a pain (I'll type up some real-world use-cases later, I'm in a bit of a hurry right now).

Perhaps we can do a couple things to `<Link/>` make this awesome:

### Optional `to`

I know, we had this once and @machty is awesome.

If you leave off `to` in a link, it will just use the current route.

### add `setQuery` and `setParams`

These would work like `setState` in a component, namely, it merges the current data with new data.

### add `replace` option

Would be `false` by default, if `true` the router will use `replaceWith` instead of `transitionTo`.

### Use Case

Imagine headers in a sortable table, when you click them, you want to update the query, but not all of it, and you don't actually care what route you're at, you just want to change `sortBy`. Finally, you don't want an entry in the history.

```xml
<th><Link setQuery={{sortBy: 'firstName'}} replace={true}>First Name</Link></th>
<th><Link setQuery={{sortBy: 'lastName'}} replace={true}>Last Name</Link></th>
```

WHATCHOOTHINK?

**Comment by murphyrandle** [comment]
Hi, friends! I'm feeling the pain right now of building a whole link just to set a query string. Has this ticket taken a back seat?

**Comment by murphyrandle** [comment]
Welp, I don't really know what I'm doing, but here's a pull request!

https://github.com/rackt/react-router/pull/773

Feel free to tell me that I don't know what I'm doing! :camel: :fireworks: :leaves:

**Comment by marnusw** [comment]
Earlier @mjackson said

> `setQuery` and `setParams` **do** kind of make sense as helper methods for programmatically updating the URL, but that's what `transitionTo` and `replaceWith` are for.

I have the case where I'm using a `<select>` to switch between view states:

```jsx
<Input type="select" value={this.props.query.groupBy} onChange={this.handleGroupBy}>
  <option value="category">View by Category</option>
  <option value="date">View by Date</option>
</Input>
```

and then in my handler I do:

```javascript
handleGroupBy(ev) {
  // ...
  this.context.router.replaceWith(this.context.router.getCurrentPathname(), 
    this.props.params, {groupBy: value});
}
```

It seems like a lot of code just to update the query as opposed to

```javascript
this.context.router.setQuery({groupBy: value});
```

Changing the `path` or `params` seems to imply a transition, but updating the `query` quite often only affects the layout/state of the current page. I would, therefore, argue that the `setQuery` method does have merit. I gather that the `<Link>` element can solve this issue, but changing the query programmatically would also be handy.

If there is a better way to do the above which I'm missing please let me know!

**Comment by rafaelsales** [comment]
The last suggestion is very welcome
