### ISSUE TITLE
Transparently handle transition.redirect on the server

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#387]
Currently, `transition.redirect` is not handled properly when doing server-side rendering. Ideally, the router would know how to handle a redirect in these cases, without letting it bubble all the way up to the `renderRoutesToString` callback.

**Comment by rpflorence** [comment]
We handle redirects with `onAbort` https://github.com/rackt/react-router-mega-demo/blob/master/app/server.js#L23-L25

**Comment by shubhamsizzles** [comment]
Now that `onAbort` no longer works, is there a way to solve this in v2.x ?
