### ISSUE TITLE
Hash links

### ISSUE THREAD

**Issue by CezaryDanielNowak** [rackt/react-router#394]
Hey,
I'd like to write something like this:
```
<Link to="home#about">Home</Link>
```
It should open `home` route and scroll to `<section id="about"></section>`

Will it be possible ?

Regards, Cezary Daniel Nowak

**Comment by rpflorence** [comment]
Seems like this should already work if you've got `HistoryLocation`. You can link to URLs with `<Link to="/foo/bar#baz"/>`. Anything starting with a slash will just get passed through as the path you want. If it doesn't work, a failing test case would be fantastic :)

**Comment by scabbiaza** [comment]
Yes, it works when you write in the `to` attribute URL as a string.
But how to add hash if you are using route name?

Works:
```
<Route name="about-page" path="/about" handler={About}/>
<Link to="/about#hash"></Link>
```

Doesn't work:
```
<Route name="about-page" path="/about" handler={About}/>
<Link to="about-page#hash"></Link>
```

Error:
```
Uncaught Error: Invariant Violation: Unable to find <Route name="about-page#hash">
```

**Comment by schickling** [comment]
+1

**Comment by lostpebble** [comment]
Yep, doesn't work for me either. Both ways. Shows up in the address bar as it should but never goes to the location on the page.

**Comment by juampy72** [comment]
Does not work for me either.

**Comment by whatupdave** [comment]
Yeh, this should be reopened. I'm using params to generate a more complex URL and need to add the hash.

**Comment by clementdubois** [comment]
Does not work for me either. This should be reopened please

**Comment by iyn** [comment]
+1, I'm also interested in a solution.

**Comment by krrg** [comment]
+1 for reopening this issue

**Comment by NickPresta** [comment]
As a workaround, in my main "app", I've added the following to `componentDidMount`:

```
componentDidMount() {
  // Decode entities in the URL
  // Sometimes a URL like #/foo#bar will be encoded as #/foo%23bar
  window.location.hash = window.decodeURIComponent(window.location.hash);
  const scrollToAnchor = () => {
      const hashParts = window.location.hash.split('#');
      if (hashParts.length > 2) {
        const hash = hashParts.slice(-1)[0];
        document.querySelector(`#${hash}`).scrollIntoView();
      }
    };
    scrollToAnchor();
    window.onhashchange = scrollToAnchor;
}
```

**Comment by mouhsinelonly** [comment]
+1

**Comment by Mythli** [comment]
Not working with Router.HistoryLocation. It just follows the link and does nothing.

**Comment by Pouja** [comment]
@NickPresta solution did not work for me.
Instead I just override the scrollBehavior in the router config.
So the config looks like this:
```javascript
var router = Router.create({
    routes: routes,
    location: Router.HashLocation,
    scrollBehavior: {
        /**
         * Sets the behaviour for scrolling when changing state.
         * If there is a second hash in the url, scroll to the element with matching identifier.
         * Otherwise scroll to the top.
         * @override
         */
        updateScrollPosition: function updateScrollPosition() {
            window.location.hash = window.decodeURIComponent(window.location.hash);
            const hashParts = window.location.hash.split('#');
            if (hashParts.length > 2) {
                const hash = hashParts.slice(-1)[0];
                const element = document.querySelector(`#${hash}`);
                if (element) {
                    element.scrollIntoView();
                }
            } else {
                window.scrollTo(0, 0);
            }
        }
    }
});
```

**Comment by alansouzati** [comment]
thanks @Pouja, your solution helped me to solve the issue I was facing. But I'm using HistoryLocation and for me I had to do the following:

```javascript
var router = Router.create({
    routes: routes,
    location: Router.HistoryLocation,
    scrollBehavior: {
        updateScrollPosition: function updateScrollPosition() {
          var hash = window.location.hash;
          if (hash) {
            var element = document.querySelector(hash);
            if (element) {
              element.scrollIntoView();
            }
          } else {
           window.scrollTo(0, 0);
          }
        }
    }
});
```

**Comment by davis** [comment]
does this work in 1.0.0?
how can i configure this in jsx?

**Comment by knowbody** [comment]
@davis in 1.0 there is nothing like `scrollBehavior`, you need to handle it yourself for now. we are working on it

**Comment by davis** [comment]
got it, thanks!

**Comment by alansouzati** [comment]
@scabbiaza not sure if you were able to fix your issue, but if you want to use the route name you can invoke the `makeHref` function from react router like this:

```
var Component = React.createClass({

  contextTypes: {
    router: React.PropTypes.func.isRequired
  },

  render: function() {

    var aboutPathHref = this.context.router.makeHref('about-page');

    return (
      <Link to={aboutPathHref + '#hash'}
    )
  }
});
```

**Comment by dopeboy** [comment]
@alansouzati, your solution worked great. Thank you.

**Comment by taion** [comment]
1.0.0-rc3 actually has a `hash` prop on `Link`. You should use that.

**Comment by davis** [comment]
@taion how do you use it?

**Comment by taion** [comment]
You pass the hash to it.

**Comment by davis** [comment]
nvm, it's still not working in 1.0.0-rc3 (#2216)

**Comment by alansouzati** [comment]
That's great to hear that react-router 1.0.0 supports that. But I believe some folks will need some time to migrate to react 0.14. In the meantime this work around will help people to get going.

**Comment by adrianleb** [comment]
@davis I thought the same, in the end also had to update `history` to the latest version (currently `1.2.5`) and it all works as expected now, relates to https://github.com/rackt/history/commit/8d4ece5eedf93b22585518b2e1522884d0e26526

**Comment by tachang** [comment]
@adrianleb you mean 1.12.5 ?

**Comment by gschwa** [comment]
Is there a resolution/example of this issue? I have a page that lists items alphabetically and I am trying to link down to a particular "letter". I have tried:

```
<Link hash='M' to='/'>M</Link>


<a name='M' id='M'></a>
```

to no avail. What am I missing? BTW. I am using `createHashHistory`.

**Comment by taion** [comment]
https://github.com/rackt/history/blob/master/docs/HashHistoryCaveats.md#caveats-of-using-hash-history

**Comment by bcherny** [comment]
Can someone please document, step by step, how to get anchor links working with React-Router. Reading through the comments it is not clear.

**Comment by dsteinbach** [comment]
+1

**Comment by solugebefola** [comment]
This doesn't use react router, but as a workaround for the scrolling, I incorporated this function into my relevant component.  It requires one to use `createBrowserHistory` but the parsing could probably be done for `createHashHistory` and still use the general idea:
    
    scrollToAnchor: function () {
        let anchorName = this.props.location.hash;
        if (anchorName) {
            anchorName = anchorName.replace("#","");
            let anchorElement = document.getElementById(anchorName);
            if(anchorElement) { anchorElement.scrollIntoView(); }
        }
    },

**Comment by scabbiaza** [comment]
@alansouzati's answer works perfectly. Thank you!

**Comment by figalex** [comment]
What about using hash links with Dynamic routing? I'm getting ```Location "/create#name" did not match any routes``` error when I add "#name" to "create" route, it doesn't even call the ```getChildRoutes()``` function of "create" route when I add "#name". I would expect that the same route handler was called when I add some hash stuff at the end.

**Comment by RainKolwa** [comment]
I met the same problem with @figalex ,but from my side,only when I hit the link,I got the error message as ''Warning: [react-router] Location "http://xxx#comment" did not match any routes,and if I click the link again,it generates a link like "http://xxx#comment#comment",both circumstances not react on scroll behavior

**Comment by rblakeley** [comment]
@solugebefola thanks for pointing out the `.scrollIntoView()` method ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)).

I'm able to scroll to an element on the page with just this:
```
  scrollToResourcesPending = () => {
    const {resourcesPending} = this.refs;
    resourcesPending.scrollIntoView();
  }
```

This doesn't bother with the URL bar, but I don't need an anchored route for my use case.

**Comment by botteu** [comment]
But what if you have content on your page that is loaded dynamically, inserted into your React-component via dangerouslySetInnerHtml, that includes anchors?

Example this might be loaded and inserted into some element in you component:

`<a href="#somelink">In standard HTML, this would jump to the a-tag with the name/id specified in the href-attribute</a>

Here's some general text or whatever. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque at mi nec sodales. Aenean scelerisque vulputate sem sit amet ornare. Nullam a imperdiet sem, sit amet porta felis. Pellentesque lectus ante, ornare id turpis quis, interdum pharetra mi. Vivamus augue augue, bibendum eu ex sit amet, venenatis lobortis ex. Suspendisse at turpis consequat, cursus sapien ac, fermentum lorem. Duis id tortor leo. Praesent risus justo, consectetur a euismod et, feugiat in nibh. Nulla bibendum orci sed risus venenatis vulputate. Praesent libero orci, eleifend tincidunt ex eu, tincidunt mattis dui. In maximus fringilla justo et tempor. Nunc nec posuere purus.

<a id="somelink">The above link should jump here</a>`

Here you only mention the Link React component.
I'm at a loss here. You could look through all the anchor-tags in the content and look for # and then modify it.

**Comment by gharwood** [comment]
+1 This is still a issue.

**Comment by rafrex** [comment]
I created a lightweight workaround to this issue.
Repo: https://github.com/rafrex/react-router-hash-link-scroll
Live example: http://react-router-hash-link-scroll.rafrex.com

It uses a Router `onUpdate` hook and calls `element.scrollIntoView()` if a `#hash` is present in the url. Since it's defined on the Router component, the scroll functionality will work with every route, and it works when linking to a `#hash` on the current route, or when linking to a `#hash` while navigating to a different route.

Check out the [example site][liveExample] to see it in action (*the example site is built with [Single Page Apps for GitHub Pages][spaGHP] to allow for using `browserHistory` with GitHub Pages*).


```javascript
import React from 'react';
import { render } from 'react-dom';
import { Router, Route, browserHistory } from 'react-router';

const routes = (
  // your routes
);

function hashLinkScroll() {
  const { hash } = window.location;
  if (hash !== '') {
    // Push onto callback queue so it runs after the DOM is updated,
    // this is required when navigating from a different page so that
    // the element is rendered on the page before trying to getElementById.
    setTimeout(() => {
      const id = hash.replace('#', '');
      const element = document.getElementById(id);
      if (element) element.scrollIntoView();
    }, 0);
  }
}

render(
  <Router
    history={browserHistory}
    routes={routes}
    onUpdate={hashLinkScroll}
  />,
  document.getElementById('root')
)
```

[liveExample]: http://react-router-hash-link-scroll.rafrex.com/
[spaGHP]: https://github.com/rafrex/spa-github-pages

**Comment by rafrex** [comment]
@botteu using `<Link to="/your/path#somehash">go to dynamically loaded content</Link>` with the above `onUpdate` hook I think will work.

**Comment by mbrochh** [comment]
@rafrex thanks for this! works for me 👍

**Comment by adjohnson916** [comment]
@rafrex Thanks for the solution. I've published a solution based on that as a module to npm called [anchorate](https://github.com/adjohnson916/anchorate).

**Comment by vimniky** [comment]
I have some code like this: 
```js 
<Route name="about-page" path="/about" handler={About}/>
<Link to="/about#hash"></Link>
```
When I manually refresh my browser on `/about#hash` , location.hash changed to an empty string "", I can't figure out why !

**Comment by adjohnson916** [comment]
@vimniky Does the same thing happen with `/about/#hash`?

**Comment by dschinkel** [comment]
Ok so I'm looking at this long thread.  What's the way everyone is able to get hashes working now at this point in time?  Do you still have to put in a hack to intercept the hash and rework it so that react-router knows what to do with it when you are using browserHistory?

**Comment by IsurusPrime** [comment]
works great, thanks! @rafrex

**Comment by kelchm** [comment]
I'm finding that onUpdate is called before the child components in my view have rendered.  If I use a `setTimeout` of sufficient length scrolling down the page works, but this obviously isn't a reasonable solution.

I'm currently using /makeomatic/redux-connect, which I suspect might be what is causing this behavior.  Anyone else out there using redux-async-connect?

**Comment by rafrex** [comment]
@kelchm, I haven't used redux-connect, but I think what you're saying is that linking to the new url causes your app to fetch data from the server asynchronously, and only after the data loads is the element with the id corresponding to the #hash available on the page.

Can you use the `hashLinkScroll` function as an on success callback to your async data fetch?

**Comment by kelchm** [comment]
@rafrex, The problem is that I need a reliable way to know when the element with the provided ID has actually been rendered.  Even using a combination of `SetTimeout` and `requestAnimationFrame` I was not able to get things working reliably.

I've come up with a solution that, while inelegant, should _always_ work:

```js
function hashLinkScroll(retryCount = 0, retryLimit = 300) {
  console.debug('hashLinkScroll retry count: ', retryCount);
  const { hash } = window.location;
  if (hash !== '') {
    window.requestAnimationFrame(() => {
      const id = hash.replace('#', '');
      const element = document.getElementById(id);
      if (element) element.scrollIntoView();
      else if (retryCount < retryLimit) setTimeout(hashLinkScroll(retryCount + 1), 100);
    });
  }
}
```

**Comment by dschinkel** [comment]
I've been using [react-scroll](https://github.com/fisshy/react-scroll) and it's worked great plus it's got effects built into it.  I figure on this one, why reinvent the wheel if it's already been done.

**Comment by rafrex** [comment]
It's my understanding that react-scroll doesn't support scrolling based on `#hash-links`, is that not true?

**Comment by dschinkel** [comment]
I'm using browserHistory with the <DirectLink> component in react-scroll.

**Comment by rafrex** [comment]
Yea, I'm using browserHistory too. If I copy/paste a url like `http://example.tld/foo/bar#some-id` will react-scroll scroll to the element on the page with id of `some-id`? If so, do you have a code example? I had looked at react-scroll before but didn't think it supported this (none of the examples they provide use `#hashes` in the url).

**Comment by dschinkel** [comment]
@rafrex here's an example of my code using it.  

```
const TableOfContents = Component({
    store: Store('/companies'),
    contextTypes: {
        router: React.PropTypes.func.isRequired
    },
    componentDidMount() {
        const el = ReactDOM.findDOMNode(this);
        new Ink.UI.Sticky(el,{offsetTop: 50, topElement: "#ft-company-profile", bottomElement: "#footer"});
    },
    render(){
        return (
            <div>
                <p className="margin-8"><span className="blue medium"><DirectLink to='interviewee' spy={true} smooth={true} duration={500}>Interviewee</DirectLink></span></p>
            </div>
        )
    }
})
```

Here is the component to which the to is looking for in terms of the hash:

```
const Interviewee = Component({
    store: Store('/companies'),
    render(){
        var company = this.props.company,
            interviewee = company.interview.interviewee,
            pastCompanies = interviewee.pastCompanies.map(pastCompany =>
                            <span className="ink-badge black font-11">{pastCompany}</span>);
        return (
            <div id="ft-interviewee" className="all-100">
                <p className="section-heading bold font-22" id="interviewee">Interviewee</p>
                <div className="column-group horizontal-gutters">
                    <div className="all-10">
                        <div><img src={interviewee.portraitImage} /></div>
                    </div>
... rest of component code
```

When I click the DirectLink it scrolls down or up to the interviewee section.

**Comment by rafrex** [comment]
> When I click the DirectLink it scrolls down or up to the interviewee section. So mine isn't going to a hash added lets say at the end of a full route definition... like mine's not going to /something/somethingelse#someAnchor. It's just looking for an anchor that exists on the same page.

So if I understand you correctly, it's not scrolling based on the `#hash` in the url. This is definitely useful for a lot of use cases (especially with the smooth transitions), but not if you need to save scroll position independent of the session, e.g. share a link like [https://github.com/reactjs/react-router/issues/394#issuecomment-220221604](https://github.com/reactjs/react-router/issues/394#issuecomment-220221604)

**Comment by dschinkel** [comment]
@rafrex ah I see yea, I'm not needing that right now...

**Comment by sanakr** [comment]
how to use <a href="mailto:viratiyen@gmail.com> in Link

**Comment by timdorr** [comment]
@sanakr Just use a normal `<a>` element. Don't use Link.

**Comment by sanakr** [comment]
@timdorr   i got solution, its possible in Link . 

 `<Link to={{pathname:`mailto:${value}`}} className={style.qLink} target="_blank">{value}</Link>` just like this.

**Comment by timdorr** [comment]
You shouldn't do that. Just use a normal `<a>` element.
```js
<a href=`mailto:${value}` className={style.qLink} target="_blank">{value}</a>
```
Our `<Link>` component isn't designed to take in URLs with different protocols and you are taking a performance hit that you don't need to be taking by adding the overhead of that component.

**Comment by Gijsjan** [comment]
I've had success with using the ref's callback.
```
{
  items.map((item) =>
    <li
      ref={(el) => {
        if (el != null && item.id === this.props.routeParams.id) {
          el.scrollIntoView();
        }
      }
    >
  )
}
```

**Comment by Agalla81** [comment]
Is there any supported way to prevent re-rendering while using named anchors to sections on the same page? This causes an unnecessary overhead.

**Comment by kelchm** [comment]
> Is there any supported way to prevent re-rendering while using named anchors to sections on the same page? This causes an unnecessary overhead.

@Agalla81, have you tried using `Link` with the full URI rather than just an anchor with a hash href?

**Comment by ligaz** [comment]
@Agalla81 I'm successfully using the following "workaround": override `shouldComponentUpdate` in the route's component and return `false` when you detect hash navigation.

**Comment by jask84** [comment]
I was wondering if there is now an accepted way to getting anchor links working with react-router? I have attempted many of the methods outlined and failed so had to revert to regular named anchors using id's. I couldn't find much on the internet about this. Would love to know more. Thanks.

**Comment by iddan** [comment]
Has been any progress on this?

**Comment by kopax** [comment]
I have tried @rafrex solution and it appear it work but the view get rerendered while it should not, is there a way to prevent this ?

**Comment by chandan7193** [comment]
Comes error when I npm install and use react-router-hash-link Error in ./~/react-router-hash-link/lib/index.js
instead of link

**Comment by paolomangiadev** [comment]
@rafrex i fkng love you!

**Comment by abumalick** [comment]
A simple solution with https://www.npmjs.com/package/scroll-to-element that a friend found.
```
import { browserHistory, Link } from 'react-router';
import scrollToElement from 'scroll-to-element';
componentDidMount() {
    this.jumpToHash();
  }
  componentDidUpdate() {
    this.jumpToHash();
  }
  jumpToHash = () => {
    const hash = browserHistory.getCurrentLocation().hash;
    if (hash) {
      scrollToElement(hash, { offset: -120 });
    }
  }
```
After that you add some div with an corresponding `id` on the page

**Comment by gajus** [comment]
I did not like the @rafrex proposal because it requires to use custom `Link` component. Here is a simple solution that achieves the same result but without requiring to override the `Link` component:

```js
// @flow

/**
 * @param history {@see https://www.npmjs.com/package/history}
 * @param timeout A number of milliseconds to wait for the element to appear after PUSH action has been received.
 */
export default (history: *, timeout: number = 1000) => {
  let observer;
  let timeoutId;

  const reset = () => {
    if (timeoutId) {
      clearTimeout(timeoutId);

      timeoutId = null;
    }

    if (observer) {
      observer.disconnect();
    }
  };

  const createScrollToElement = (id: string) => {
    return () => {
      const element = document.getElementById(id);

      if (element) {
        element.scrollIntoView();

        reset();

        return true;
      }

      return false;
    };
  };

  history.listen((location: *, action: *) => {
    if (action !== 'PUSH') {
      return;
    }

    if (timeoutId) {
      reset();
    }

    if (typeof location.hash !== 'string') {
      return;
    }

    const elementId = location.hash.slice(1);

    if (!elementId) {
      return;
    }

    const scrollToElement = createScrollToElement(elementId);

    setTimeout(() => {
      if (scrollToElement()) {
        return;
      }

      observer = new MutationObserver(scrollToElement);

      observer.observe(document, {
        attributes: true,
        childList: true,
        subtree: true
      });

      timeoutId = setTimeout(reset, timeout);
    });
  });
};

```

**Comment by huy-nguyen** [comment]
Just to add to @abumalick's solution, the `history` object (which he/she imports as `browserHistory` from `react-router-dom`) is also available as `this.props.history` on the `Route` component. In that case, the `hash` is available via `this.props.history.hash`.

**Comment by abumalick** [comment]
Yes, my solution is for react-router 3. With react-router 4 you should take history from props

**Comment by G2Jose** [comment]
@rafrex's solution (https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604) worked really well, but I didn't want to make such a top level change on a production website just in case there are regressions. 

I only had one place where I needed this logic, so I used a ref instead - 

```
 <a
	href="#questionid"
	id="questionid"
	ref={element => {
		const { hash } = window.location;
		if (hash !== '') {
			const id = hash.replace('#', '');
			if (element.id === id) element.scrollIntoView();
		}
	}}
>
	Text
</a>
```

**Comment by lemmingapex** [comment]
Although it was not ideal, this worked out of the box for me with both HashRouter and BrowserRouter: https://github.com/rafrex/react-router-hash-link

```
import { HashLink } from "react-router-hash-link";

<HashLink to="/my-cool-page#my-cool-section">Goto Cool Section</HashLink>

<div id="my-cool-section">The coolest</div>
```
