### ISSUE TITLE
Prevent parent route from re-mounting/rendering when moving from parent to nested route

### ISSUE THREAD

**Issue by natew** [rackt/react-router#411]
Note: I'm working on the react-async branch, but that shouldn't be related to this question.

With routes set like so:

```text
<Route name="articles" handler={Articles}>
  <Route name="article" path=":id" handler={ArticleView} addHandlerKey={true} />
</Route>
```

I'd like to use a transition when moving from `/articles` to `/articles/:id` to have an article slide over the list of articles. My `render()` for Articles looks like this:

```jsx
render() {
  var ArticleView = this.props.activeRouteHandler || function() {
    return <div></div>;
  };

  return (
  <div>
    <ul>
      {_.map(this.props.article, (article) => {
        return <Link to="articleView" params={{id: article.id}}>{article.title}</Link>;
      })}
    </ul>
    <ReactCSSTransition>
      <ArticleView />
    </ReactCSSTransition>
  </div>
  )
}
```

Now, when clicking on a link it seems to be working fine, but because it's calling render() again on Articles I see a flicker. Also, `getRouteProps` is being called so it's recalling for the data. I'm probably just being a bit obtuse on this one, but is there a way to re-structure this so I can bring in the sub-route without re-rendering the parent? I know this sort of violates the react structure, but it does seem like a valid use case to want to be able to "add" in child views without modifying the parents.

**Comment by rpflorence** [comment]
we've change the code quite a bit since this ticket was opened, if this is still a problem please let me know, I'll reopen. I've done similar things and haven't had any issues in the latest code. Thanks :)

**Comment by themre** [comment]
I'm using leaflet component and router. And i put Map in render method and when I move,I store location and push variables to router. And then router rerenders map and I see flickering. How can I solve this?

**Comment by mtz87** [comment]
@natew did you ever find a solution? Please update this issue with a resolution. Thanks!
