### ISSUE TITLE
Additional instance lifecycle hooks.

### ISSUE THREAD

**Issue by ghempton** [rackt/react-router#415]
We have the need for stronger lifecycle methods than just the static `willTransitionTo` and `willTransitionFrom`.

Consider the example below:

```
<Routes location="history">
  <Route path="/" handler={Wizard}>
    <Route path="/step1" handler={Step1} />
    <Route path="/step2" handler={Step2} />
  </Route>
</Routes>
```

We have the need to setup some state when `Wizard` is entered for the first time– but not when child routes are navigated between. `willTransitionTo` is not a strong enough hook for a couple reasons:

1. We want access to `this.context`. In a static method this seems awkward and not sure how that would jive with `contextProps`.
2. We want to manipulate `state` and not `props`.

`addHandlerKey={true}` is not sufficient since we do not want re-mounting in between `step1` and `step2`. `willReceiveProps` is also not sufficient since there is no conventional way to differentiate between an internal and external transition.

Would be nice to have a hook such as `didTransitionTo` that is at the instance-level.

Thoughts?

**Comment by rpflorence** [comment]
Any additional requirements can be handled `Router.run(routes, () => /* here */)`. `componentWillReceiveProps` and the run callback cover every possible lifecycle point there is.
