### ISSUE TITLE
Router with location="none" doesn't seem to work

### ISSUE THREAD

**Issue by whather** [rackt/react-router#419]
We use location="none" in our Ember Router on a chrome plugin we developed which works on top of LinkedIn in a sidebar. The expected behavior of "none" is to be able to navigate through our site in the sidebar without changing the browser url or affecting the history manager. So hitting "back" in the browser after navigating through our app in the sidebar would go back to the last LinkedIn page you were on instead of the last page you were on in our sidebar.

We are in the process of migrating our app over to React. I've tried various location="none" in React Router and haven't had any success in the pages loading. This is the temporary hack I'm doing now (which does affect the history manager):

```html
<Routes location="hash">
  <Route path="/" name="sequences.index" handler={SequencesIndex} />
</Routes>
```

Is location="none" not fully implemented yet? Or do I have to define my routes a little differently to get them to load? 

Thanks!

**Comment by rpflorence** [comment]
We now have `RefreshLocation`.
