### ISSUE TITLE
ActiveState.isActive issue

### ISSUE THREAD

**Issue by snow01** [rackt/react-router#447]
In ActiveState mixin (https://github.com/rackt/react-router/blob/master/docs/api/mixins/ActiveState.md) - 

isActive function implementation currently checks truth for param and query values, but not their names. In my opinion, a param or query active means whether some value of those are available in the routes, that is given param or query have some valid values. As far as I think, most use cases for dynamic routes, require to check only the presence of the param or query, and not their values.

What's your opinion ? 

If you see above as a valid issue, I can submit a fix for above. Please let me know.

**Comment by rpflorence** [comment]
I'm not sure I'm following completely, but sounds like you want to ignore param/query values in isActive? We don't want links to `/users/123` and `/users/234` to both be "active". Perhaps we've just named this poorly?

Trying to clean out the issues, and @gaearon has a great solution for checking if a route is active, I'm going to close, but I'll happily reopen with some noise :)
