### ISSUE TITLE
Navigation mixin's goBack method behaving weird

### ISSUE THREAD

**Issue by zeusdeux** [rackt/react-router#449]
In my app, goBack(), instead of taking me the previous element in the history, takes me to my current route with a '?' appended to it while the browser back button takes me back correctly.

Am I missing something?

#### Some info about my usage:

Lets say I have two routes 1 & 2 that correspond to components 1 & 2.

Each route displays a different component but they are logically connected (like steps 1 and 2 in a process). 

When the user completes step 1 and hits next, an action is fired. This leads to a change in the store that backs component 2.

In the change handler for this store (which is in my top level component), I perform a `transitionTo` to route 2 and also call `setState` for the second component.

When I hit back (which is bound to goBack) from the second component, I end up at route 2 appended with a '?' but when I hit the browser back button, it works as expected.

Am I missing something? Also, let me know if any clarifications are needed.

Cheers!

**Comment by rpflorence** [comment]
Has been 2 months, please reopen if this is still a problem. I've got `goBack` in several places and its behavior properly, but we may have edge case bugs. Let us know :D

**Comment by zeusdeux** [comment]
Oh hey.
Forgot to update this, apologies.

It seemed to have gotten fixed by updating. Thanks @rpflorence :)
