### ISSUE TITLE
Static function willTransitionTo  not triggered.

### ISSUE THREAD

**Issue by xeodou** [rackt/react-router#468]
In my case router `/a` redirect to router `/b`,  then router `/b` have a static function `willTransitionTo` check some data, then redirect back to router `/a` use `transition.redirect` . But the function `willTransitionTo` not triggered.

I try to find this bug in source , I can't find it. 
So i using the `componentWillMount` and `componentWillUnmount` instead of `willTransitionTo` and `willTransitionFrom`.

**Comment by rpflorence** [comment]
as far as I can tell this is working as designed, both route transitions are called. What behavior are you expecting?

http://jsbin.com/duyaxa#/a
