### ISSUE TITLE
Non-JSX examples

### ISSUE THREAD

**Issue by Chrazy** [rackt/react-router#508]
It would be great if there could be some examples using regular js syntax, it's sometimes hard to know what the different classes return and how they're supposed to be used after the latest update.

**Comment by rpflorence** [comment]
If people don't want to use JSX, they don't have to, but they do have to learn how, I'm going to keep using JSX in the docs.

**Comment by gryzzly** [comment]
An example without JSX that also has route nesting:
```js
// this snippet was tested with react 0.13.1 
// and react-router 0.13.2
import Router from 'react-router';
import App    from './components/App';
import Inbox  from './components/Inbox';

const AppRoute = Router.createRoute({
  path: '/',
  name: 'app',
  handler: App
});

const InboxRoute = Router.createRoute({
  name: 'inbox',
  handler: Inbox,
  parentRoute: AppRoute
});

// Important: you have to export the root route wrapped in array 
export default [AppRoute];
```

**Comment by michaelBenin** [comment]
+1 for showing how to create routes without JSX. 

As someone coming from History.js, Backbone.js, and Ember.js background, I would rather write my routes using JS instead of writing them as JSX markup. Thank you @gryzzly for the example.

**Comment by michaelBenin** [comment]
Is it possible to create routes dynamically in jsx?

**Comment by contra** [comment]
Watched the talk @mjackson gave at ReactEurope and he mentioned a new declarative non-JSX interface to the router in 1.0. Are there any docs available for this yet?

**Comment by cesarandreu** [comment]
@contra the v1.0.0-beta3 [docs](http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Plain Route) have a short section on plain routes.

**Comment by flocks** [comment]
Is there a way to do the same implementation than the  [Pinterest example]( https://github.com/rackt/react-router/blob/master/examples/pinterest/app.js) but using JSX ? 

In the [documentation](http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Plain%20Route), it's written 
>A route configuration object. Router turns JSX <Route/>s into these objects, but you can use them directly if you prefer. All of the props are the same as <Route/> props, except those listed here.

Does that means there is no way to use getChildRoutes in JSX ?
