### ISSUE TITLE
Link makes checksum incompatible

### ISSUE THREAD

**Issue by clintandrewhall** [rackt/react-router#528]
I'm experimenting with isomorphic rendering with react-router, and everything has been going great until I tried to add the Link component.  Now I get:

Uncaught Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side.

If I don't include the Link component, the checksum matches; include even just one and it doesn't.  Any ideas what might be causing this?

**Comment by rpflorence** [comment]
I'm doing plenty of isomorphic stuff right now and have not seen this, I'll happily reopen if a test case showing the bad behavior shows up :)

**Comment by rpflorence** [comment]
woops, missed the sample code

**Comment by rpflorence** [comment]
If you're doing server side rendering, you need to be using Router.HistoryLocation. I'm sure your checksums are busted because of `#`.

If there's a valid reason to use `HashLocation` I'll reopen, but browsers don't send the hash to servers anyway.

**Comment by clintandrewhall** [comment]
@rpflorence Sorry, what do you mean when you say use Router.HistoryLocation?

**Comment by rpflorence** [comment]
in the client you need to use `Router.run(routes, Router.HistoryLocation, callback)`, and on the server `Router.run(routes, req.path, callback)`.

**Comment by HzJavier** [comment]
@clintandrewhall Were you able to fix the problem with that Ryan commented or did something else? I'm having the same issue but didn't quite get the way to solve it.

**Comment by iyoukeyyewei** [comment]
I have the same issue. Anyone can help on resolution? thanks

**Comment by anatomic** [comment]
I've stumbled on this thread because my checksum isn't matching. Debugging it a few different ways I think the issue is that a `<noscript>` is being rendered by React on the client while React Router performs it's async work (and secondary bundles are loaded in by webpack). I fear that the universal javascript and webpack chunking may never play well together :(

Has anyone else seen this issue?

**Comment by jarib** [comment]
I'm also seeing a `<noscript>` difference. 

![image](https://cloud.githubusercontent.com/assets/572/8592442/989e003c-262f-11e5-82a5-32eddc060cdc.png)

@anatomic Did you find a solution?

**Comment by anatomic** [comment]
@jarib I did, posted my solution in issue #1402 https://github.com/rackt/react-router/issues/1402#issuecomment-116723037
