### ISSUE TITLE
How do I access my flux object within `willTransitionTo` and `willTransitionFrom`

### ISSUE THREAD

**Issue by AndrewIngram** [rackt/react-router#552]
Like many (I assume) I'm using Flux to manage data flow within my app, in particular I'm using Fluxxor. For lack of better ideas, I want to use the `willTransitionTo` and `willTransitionFrom` functions respectively to handle data loading and cleanup during navigation changes. Since these methods are static, they don't have access to the context or properties, which is how the flux object normally gets passed down the tree. Is there some way I can inject the flux object into these methods with react-router as it stands now? Or it feasible to add support for this pattern?

**Comment by rpflorence** [comment]
closing, follow #590 (or make a container module for your route instance)
