### ISSUE TITLE
Cloning a RouteHandler

### ISSUE THREAD

**Issue by natew** [rackt/react-router#558]
I've hit a blocker with ReactRouter with the following pseudo-code:

```js
render() {
  var numRoutes = this.getRoutes().length;
  var hasChild = numRoutes > 1;

  return <ViewList showIndex={numRoutes}>
    <ViewSide {...} />
    {hasChild && <RouteHandler />}
  </ViewList>;
}
```

In ViewList I'm animating between views when RouteHandler becomes active. Think of RouteHandler as the message view of the Mail app on an iPhone, whereas ViewSide is the list view of messages.

ViewList uses the same trick that is used by ReactTransitionGroup in that it takes it children properties and clones them into state. So something like:

```js
getInitialState() {
  { children: cloneChildren(this.props.children) }
}
```

Now, the problem. When I go "back" from RouteHandler (its set for false), ViewList should do this:

1. Receive new props with false for RouteHandler
2. Animate back to ViewSide (300ms)
3. Update state with new props, removing old RouteHandler view

My problem is this... Before the animation in step 2, I can see the RouteHandler view removed. I think this is happening because despite me cloning RouteHandler inside ViewList, it is still relying on context for it's data. So it re-renders RouteHandler immediately with the new props. It seems there may be a few ways around this...

1. Somehow deep clone (costly, ugly, not sure if possible)
2. Integrate with willTransitionTo. Problem here is then I have to put logic into *every* subView, when really I want the logic inside ViewList.
3. Somehow make RouteHandler work with an old context or passing in my own overrides...

**Comment by mjackson** [comment]
@natew Let's close this for now since we have the mixin. Thanks for bringing this to our attention!
