### ISSUE TITLE
willTransitionFrom: component undefined on second instance

### ISSUE THREAD

**Issue by WRidder** [rackt/react-router#567]
I am using the following mixin to prevent a transition if needed:

    var approveTransition = {
      statics: {
        willTransitionFrom: function (transition, component) {
          if (component.mayPreventTransition()) {
            if (!confirm('You have unsaved information, are you sure you want to leave this page?')) {
              transition.abort();
            }
          }
        }
      } 
    };

Which is used in the following component:  

    var NewQuestion = React.createClass({
      mixins: [approveTransitionMixin],
      mayPreventTransition: function() {}
      ..
    });

This component is used to create a new question and instantiated in the following way:

    var routes = (
      <Route name="app" path="/" handler={App}>
        ...
        {/* Question routes*/}
        <Route name="questions" path="questions" handler={QuestionList}/>
        <Route name="questionsNew" path="questions/new" handler={NewQuestion}/>
       ...
      </Route>
    );

The first time I navigate away from this page no problem arises. However, if I navigate to this page again and try to navigate away again the following error occurs:

    Uncaught TypeError: Cannot read property 'mayPreventTransition' of undefined 

This indicates that the `component` argument of the `willTransitionFrom` function is undefined. Right now I don't have a clue yet why this occurs.

**Comment by rpokorny** [comment]
I was having a similar problem, and it turned out that had added <RouteHandler> children to several components that did not have child routes.  Removing the extraneous RouteHandlers cleared up the problem.

In my case however the issue didn't appear on the second visit to the same route - it appeared when I visited a particular route after having already been to another particular route.

**Comment by WRidder** [comment]
@gaearon `App` seems to be properly defined. Regarding `mayPreventTransition`: that's a custom function on my component to check whether it allows transitioning away.

@rpokorny Thanks for the pointer, will check that.

**Comment by WRidder** [comment]
@rpokorny Turned out a RouteHandler without child routes was the cause of my problem as well. Thanks!

**Comment by gaearon** [comment]
Shouldn't we throw or at least warn if `RouteHandler` is used where there's no nested routes?

@rpflorence @mjackson

**Comment by WRidder** [comment]
I agree on the warning, as requested in #703 as well.
