### ISSUE TITLE
detect non-existing route on the server side

### ISSUE THREAD

**Issue by romeovs** [rackt/react-router#573]
I've got a simple express app that follows the basic structure as described in the [server-rendering](https://github.com/rackt/react-router/blob/master/docs/guides/server-rendering.md) guide.

My routes are fully defined in the `react-router` style so I don't want to add server-side routes for this part of the app.

I would like to set the correct response status when I'm trying to render a route that does not exist (apart from rendering it with the `DefaultRoute`. Is there a way to detect wether `Router.run` picked an existing route or went to the fallback route at server-side?

**Comment by ColCh** [comment]
To spot non existing route, we can catch **mount** event of `NotFoundRoute`
Since we can't properly pass props here from top component to bottom, I suggest use **contexts**

Here is some code from my live project;

Main route definittion:
```
var NotFound = require('components/Not-found');
var routes = (
    <Route ...>
      ...
      <NotFoundRoute handler={NotFound} />
    </Route>
  );
```

__NotFound__ component:
Since I use contexts, I created a wrapper for it to pass callback from context to props nicely:
```
var NotFoundWrapper = React.createClass({

  contextTypes: {
    onNotFound: React.PropTypes.func
  },

  render: function() {

    var handleNotFound = this.context.onNotFound;

    return (
      <NotFound onBeforeMounted={handleNotFound} />
    );
  }

});
```

__NotFound__ component himself:
```
var NotFound = React.createClass({

  mixins: [PureRenderMixin],

  contextTypes: {
    onNotFound: React.PropTypes.func
  },

  getDefaultProps: function() {
    return {
      onBeforeMounted: new Function
    };
  },

  componentWillMount: function() {
    this.props.onBeforeMounted();
  },

  render: function() {
    return (
      <div>
        <h1>Не найдено</h1>
        <h2>Похоже, искомая страница не найдена</h2>
      </div>
    );
  }

});
```
Notice: I call `this.props.onBeforeMounted` inside of `componentWillMount`!

That's about isomorphic part.
And now serverside and clientside part:

Clientside:
```
Router.run(routes, Router.HistoryLocation, function (Handler) {
    React.withContext({
        onNotFound: function () {
            alert('NOT FOUND FROM CONTEXT');
        }
    }, function () {
        React.render(<Handler />, document.getElementById('content'));
    });
});
```

Serverside. Since React is sync, we can use one Promise (instead of two Promises):
```
var getMarkup = function (req) {
    return new Promise(function (res, rej) {

        var location = req.url;

        Router.run(routes, location, function (Handler) {
            React.withContext({onNotFound: rej}, function () {
                var handler = React.createElement(Handler);
                var markup = React.renderToString(handler);
                res(markup);
            });
        });

    });
};

module.exports = function reactRoute_middleware (req, res, next) {
    getMarkup(req).then(function (markup) {
        res.render('index', { title: 'Express', content: markup });
    }, next);
};
```

Hope it will help.

**Comment by romeovs** [comment]
Wow, seems a lot of work for something that simple.

I'm taking another approach now. I just name the `NotFound` handler and than look for that name in `Router.run` on the server side:

```
// file: routes.jsx
var routes = (
  <Route name='app' handler={App}>
    // other routes....
    <NotFoundRoute name='404' handler={MyNotFound} />
  </Route>
);
```
```
// file: render.js (server side render file)
Router.run(routes, path, function(Handler, state) {
  var notfound = state.routes.filter(function(route) {
      return router.name === '404';
  }).length > 0;
  if ( notfound ) {
    throw "Route not found!";
  }
});
```

**Comment by ColCh** [comment]
@romeovs ha, thank you for this trick! I didn't knew about `state` param in `Router.run` callback. Yez, that's a lot better than my way.

**Comment by rpflorence** [comment]
I do this: https://github.com/rackt/react-router-mega-demo/blob/master/app/server.js#L33

We will eventually leverage `<NotFound/>` and `<Redirect/>` to make sending the right status on the server friendlier, but *is* possible so I'm going to close this ticket.

**Comment by ESTEBANMURUZABAL** [comment]
Hi @nikhedonia, Did any of you had to upgrade your react-router version? I am trying to do it like this:
Router.run(app.getComponent(), req.originalUrl, async function (Handler, state) {
to
ReactDOM.render(app.getComponent(), req.originalUrl, async function (Handler, state) {

but I am getting this error: Target container is not a DOM element.
Could you point me out please what I am doing wrong?

**Comment by pshrmn** [comment]
@ESTEBANMURUZABAL You have been commenting on a number of long dead issues. Please use StackOverflow or Reactiflux for asking questions.
