### ISSUE TITLE
willTransitionTo called before own fetchData

### ISSUE THREAD

**Issue by klimashkin** [rackt/react-router#576]
Hello!
I have own async data fetcher as static method at component (like https://github.com/rackt/react-router/blob/master/docs/api/run.md#examples-1), and I have willTransitionTo, which check if user logged in, and if not - redirect him.
Data for that check I receive only in data fetcher, but willTransitionTo called before it. So users always redirects.
Mmm..

**Comment by rpflorence** [comment]
closing since this is a question, but happy to continue the conversation.

perhaps you can fetch your authentication data in `willTransitionTo`? Or take that out and do the auth check in `componentDidMount`, mixin `Navigation`, and `this.redirect` if they aren't authenticated.
