### ISSUE TITLE
react-router and React Dev Tools (Unknown component)

### ISSUE THREAD

**Issue by ferrannp** [rackt/react-router#577]
I am using react-router 0.11.2 and React Dev Tools 0.12. I noticed that the component immediately inside the RouterHandler appears as Unknown:

![router](https://cloud.githubusercontent.com/assets/774577/5342258/d842b0fa-7efc-11e4-8830-73c2c025bdd8.jpg)

Is this a bug of RDT or react-router? Or something am I doing wrong? :)

**Comment by davidtheclark** [comment]
@ferrannp Are you *not* using JSX? If you *do* use JSX the `displayName` is automatically set for you: http://facebook.github.io/react/docs/component-specs.html#displayname

**Comment by ferrannp** [comment]
Thanks for you answer guys. Yes, the problem is creating components in this way:

    module.exports = function(x, y) {
      var MyComponent = React.createClass({
       ...
    });
      return MyComponent;
    };
