### ISSUE TITLE
Can the active Link have a ref?

### ISSUE THREAD

**Issue by blainekasten** [rackt/react-router#578]
So, it'd be really awesome if I could easily access my active Link via a ref easily. Something like this:

    render: function(){
        return (
            <Link to="inbox"> Inbox </Link>
            <Link to="account"> Account </Link>
        )
    }

Then, say if I clicked inbox, It would set a ref to something like `this.refs.activeLink` so then I could easily in another method reference that dom node. I can even do the work for this if it is something you guys are interested in.

**Comment by rpflorence** [comment]
If you want something like this, you could wrap our `Links` in your own component, and do some checking if its active.
