### ISSUE TITLE
Calling a function in a component when a query parameter changes

### ISSUE THREAD

**Issue by tmcw** [rackt/react-router#579]
Right now I'm working on moving some of our component state into query parameters so that pages are bookmarkable and other components can cleanly change the values.

It looks like react-router will call `.render` when a query parameter changes, but it's not clear how to tell which part of the URL / which query parameter changed, and the work I'm doing is outside of .render, in an onChange or componentDidUpdate lifecycle method.

Is there a clean way of implementing this? It seems like I either need to:

* Duplicate the query parameters in the component's state so I know when they change
* Or pass the query parameters down my view hierarchy from the router as a prop

**Comment by rpflorence** [comment]
If I need that info I pass the params/query down my route view hierarchy.

```js
Router.run(routes, (Handler, state) => {
  React.render(<Handler {...state}/>, document.body);
});

// and then everywhere else:
<RouteHandler {...this.props}/>
```

Now its available here on every component:

```js
  componentWillReceiveProps (nextProps) {
    var old = this.props.query;
    var new = this.props.query;
  }
```

**Comment by abergs** [comment]
@ryanflorence I believe you meant:

     componentWillReceiveProps (nextProps) {
        var old = this.props.query;
        var new = nextProps.query;
      }

**Comment by mhils** [comment]
FWIW, in 0.13.2 `this.context.router.getCurrentQuery()` always returns the same object reference (which is then updated). This makes passing it down the hierarchy as a prop to compare it with nextProps impossible (this.props is already updated as well). Cloning before passing it down the hierarchy is a possible workaround.

**Comment by ryanhomer** [comment]
With RRv4, `nextProps.location.search` works for me, once the component is wrapped with `withRouter`.

**Comment by vannleonheart** [comment]
Same with me, I assume this happened when using render on <Route />. The return component from this render function (on route) did not get the next props.

`
<Route match="/any" render={(nextProps) => <ComponentDidNotReceivedTheNextProps />} />
`

**Comment by abelkbil** [comment]
@ryanhomer can you please share the code.
Thank you
