### ISSUE TITLE
Transition fails to render new handler

### ISSUE THREAD

**Issue by merk** [rackt/react-router#582]
I have the following routes

```js
var routes = [
    <Route handler={Portal}>
        <Route name="dashboard" path="/p/" handler={Dashboard} />
        <Route name="support" path="/p/support" handler={Support} />
    </Route>,

    <Route name="logout" path="/p/logout" handler={Logout} />,
    <Route name="login" path="/p/login" handler={Login} />,
    <NotFoundRoute name="not-found" handler={NotFound} />
];
```

In the componentDidMount method in my LoginHandler I am doing some checking for certain conditions and transitioning to the dashboard route if they are met.

The URL updates, but the page does not re-render, staying on the Login handler. If I transition to the logout path it works as expected.

I dont know enough about internals to debug further but would appreciate any assistance.

**Comment by rpflorence** [comment]
Having an array of routes is fine.

What you're describing is very basic behavior of the router that is both tested in this project and working in my apps. I'm going to need more to go on.

I'm closing the ticket but I'd like to help you get it working. Can you post some code?
