### ISSUE TITLE
Asynchronous data loading only in children components on first page load

### ISSUE THREAD

**Issue by Tailzip** [rackt/react-router#589]
Hey,

I'm using the async-data example right now, but on first page load it waits the data to be fully loaded before rendering the whole app.

Basically, I have this now :
```
- App
-- Component 1 -> /component1
--- Sub-component (dynamic content) -> /component1/:id
-- Component 2 -> /component2
--- Sub-component (dynamic content) -> /component2/:id
```

So when a user loads **_/component1/555_**, I want the user to see something like this while data is asynchronously loaded :

```
- App (loaded)
-- Component 1 -> /component1 (loaded)
--- Sub-component (dynamic content) -> /component1/:dynamic (loading...)
-- Component 2 -> /component2 (not loaded)
--- Sub-component (dynamic content) -> /component2/:dynamic (not loaded)
```

Is there a way to achieve this?

Thanks!

**Comment by rpflorence** [comment]
We don't prescribe data fetching, so I'm closing.

If you want to render before data lands, do your data fetching in `componentDidMount` of your component, if you want data before rendering, do it before you render in the `Router.run` callback. If you want some combination, load up an array/object of promises in `Router.run` but don't wait for them to resolve before rendering, pass them into the `Handler` and then deal with them in `componentDidMount` of the relevant components.
