### ISSUE TITLE
[Proposal] add sync attribute to Link

### ISSUE THREAD

**Issue by maxhoffmann** [rackt/react-router#593]
In some cases I would like to link to other pages using route names, but still do a full page refresh.

What do you think about adding a `sync` property?

```html
<Link to="name" />
<Link to="name" sync={true} />
```

**Comment by rpflorence** [comment]
Mixin `Navigation`:

`<a href="{this.makeHref(route, params)}">Will do a full page reload</a>`

If I understand the use-case though, I think I'd detect Africa and switch to `RefreshLocation` in the router.
