### ISSUE TITLE
[Proposal] Default to not adding "activeClassName"

### ISSUE THREAD

**Issue by natew** [rackt/react-router#594]
More looking for feedback on this one but I've found personally in most cases I don't want the router to set a link to active.

I noticed some performance issues with animations and noticed that one link on a page was causing re-renders because it was being set active/non-active.

If we did remove that activeClassName by default, I'd suggest documenting that people could simple make their own CalloutLink class or something similar and curry the activeLinkClass attribute.

**Comment by rpflorence** [comment]
I'd merge a PR where `activeClassName={null}` works like `""`. I wouldn't want a new property though because then there's code and docs and decisions around what to do when both are defined.
