### ISSUE TITLE
Always render parent routes handler

### ISSUE THREAD

**Issue by Tailzip** [rackt/react-router#596]
I have the following routes setup:

```javascript
var Routes = (
  <Route handler={App}>
    <Route handler={Light}>
        <Route name="Home" path="/" handler={Home} />
        <Route name="Articles" path="/articles" handler={Articles} />
        <Dark />
    </Route>
    <Route handler={Dark}>
        <Route name="Browse" path="/d/browse" handler={Browse} />
    </Route>
    <NotFoundRoute name="NotFound" handler={NotFound}/>
  </Route>
);
```

I want to always render **Dark** and **Light** no matter what is the path. But each of these components have children routes. Is there a way to do that? Does it make sense?

Thank you!

EDIT : The ultimate goal of this is to keep **Light** component active when browsing a **Dark** route and keep **Dark** component active when browsing a **Light** route. I also want a nice slide animation transition between these routes. I've been playing with **TransitionGroup**, but components get removed from DOM when animation ends.

**Comment by rpflorence** [comment]
Sounds like you want the ability to keep the previous screen around for animations. This is exactly what `TransitionGroup` does, why is having it destroyed after the animation bad?
