### ISSUE TITLE
Can't get transitionTo to work from within promise resolve

### ISSUE THREAD

**Issue by mwq27** [rackt/react-router#600]
Here's my code:

```js
routes = (
		<Route handler={AppContainer}>
			<Route name="admin" path="/admin" handler={Admin}>
				<Route name='login' handler={AdminIndex}/>
				<Route name="dashboard" handler={AdminDashboard} />
			</Route>
		</Route>
);
Router.run(routes, Router.HistoryLocation, function (Handler) {
	React.render(<Handler/>, document.body);
});
```

```js
var Admin = React.createClass({
	mixins: [Router.Navigation],

	render : function(){
		return(
			<div>
				<NavBar class="style-two"/>
				<RouteHandler />
			</div>
		);
	}
...
```

```js
var AdminIndex = React.createClass({
	mixins : [ Router.Navigation ],

	getInitialState : function(){
		return _getAdminState.apply(this);
	},
	_loginUser : function(creds){
		var self = this;
		UserActions.adminLogin(creds).then(function(res){
			console.log('Succesful call', res);
			UserStore.setAdminLoginToken(res.body);
			self.transitionTo('/admin/dashboard');
		}, function (err){
			console.debug('big error son', err);
		});
	},
	_onChange : function() {
		if(UserStore.isAuthenticated()) {
			this.transitionTo('/admin/dashboard');
		}
		this.setState(_getAdminState.apply(this));
	},
	componentDidMount: function() {
		UserStore.addChangeListener(this._onChange);
	},
	componentWillUnmount: function() {
		UserStore.removeChangeListener(this._onChange);
	},

	render : function () {
		console.debug('isAdmin', this.state.isAdmin);
		return (
			<div className='container'>
				<div className='row'>
					<h1>Admin Login</h1>
					<LoginForm loginUser={this._loginUser}/>
				</div>
			</div>
		);
	}
});
```

There in the _loginUser() method in AdminIndex, I am calling transitionTo, and the warning I get thrown is 
```
ReactMount: Root element has been removed from its original container. New container: null
```
And nothing will load for me on the /admin/dashboad page.

Does anyone see something that I'm missing?

UPDATE: 
I changed the router container from : 
```
React.render(<Handler/>, document.body);
```
to
```
React.render(<Handler/>, document.getElementById('main');
```
and the transition is working, with no more react warning.

**Comment by rpflorence** [comment]
please let us know if you discover what the problem was :)

**Comment by darkyen** [comment]
I have the same problem now.

**Comment by darkyen** [comment]
Upon further inspection this is what I found out.
![screen shot 2015-02-07 at 7 18 43 pm](https://cloud.githubusercontent.com/assets/1041315/6092294/382a51d6-aefe-11e4-9bf5-571a774902b0.png)

**Comment by darkyen** [comment]
```javascript

  getInitialState(){

    var query = this.getQuery();

    console.log('Get Initial State', this.getRoutes());
    if( query.access_token ){
      var at = query.access_token;
      app.http.setHeaders({
        'Authorization': 'MRAuth ' + at
      });
    }

    console.log("does this needs authes");
    var needsAuth = this.getRoutes().reduce(function(currentState, route){
      return currentState || app.restrictedRoutes.indexOf(route.name) !== -1;
    }, false);
    if( needsAuth && app.user.isLoggedIn() === false ){
      setTimeout(function(){
        self.transitionTo('/login/');
      }, 10);
    }

    return {};
  }
```

The above works but

```javascript

  getInitialState(){

    var query = this.getQuery();

    console.log('Get Initial State', this.getRoutes());
    if( query.access_token ){
      var at = query.access_token;
      app.http.setHeaders({
        'Authorization': 'MRAuth ' + at
      });
    }

    console.log("does this needs authes");
    var needsAuth = this.getRoutes().reduce(function(currentState, route){
      return currentState || app.restrictedRoutes.indexOf(route.name) !== -1;
    }, false);
    if( needsAuth && app.user.isLoggedIn() === false ){
        self.transitionTo('/login/');
    }

    return {};
  }
```
But without the defer it doesn't.

**Comment by tmcwilliam** [comment]
I'm having the same issue when deep linking into the app from an email link. It appears to be a race condition, but I haven't been able to drill down to the root cause.

**Comment by gaearon** [comment]
Can you make a minimal failing project?

**Comment by taurose** [comment]
Unless you use async transition handlers or render async in your run callback, `this.transitionTo(..)` effectively translates to `React.render(..)`. So starting a new transition within `getInitialState` or `componentDidUpdate` will start a new render before the ongoing one is finished.

You should use `Handler.willTransitionTo` and then [redirect](https://github.com/rackt/react-router/blob/master/docs/api/Transition.md#redirectto-params-query) instead.

**Comment by tmcwilliam** [comment]
moving `transitionTo` out of React life cycle methods fixed the problem. Is there a life cycle method that is safe to use `transitionTo`?

**Comment by gaearon** [comment]
@taurose This bit more than one person. Should we document this?

**Comment by taurose** [comment]
I guess so. Perhaps we can also show a warning. I wonder why react doesn't.

**Comment by jbrodriguez** [comment]
hi @taurose, I'm having the same issue.

I need to look at this.props to decide which route I should transition to, so willTransitionTo doesn't help here, since it's static.

Short of creating a global for this sole purpose (I think should work), do you guys have any other suggestion ?

**Comment by robert-chiniquy** [comment]
I've got the same problem. I want to conditionally redirect based on `this.props.params`, so `willTransitionTo` can't work. Using `componentWillMount` though triggers this error message.

**Comment by eipark** [comment]
Having the same issue. Seems like calling `transitionTo` from the `componentWillMount` of my top level handler creates a new `Router` instance, I imagine because there's some condition somewhere checking if the handler had mounted yet.

**Comment by robyoder** [comment]
Hmm, this bit me too. Would love a way to abort mounting/rendering when calling `transitionTo` from inside `componentWillMount`

**Comment by robyoder** [comment]
I ended up with a hacky workaround. Perform the check in `componentWillMount` and `setState` with the result, then `return null` in `render` if the check failed (so as to not start rendering child components that depend on a successful check), then `transitionTo` in `componentDidMount`

**Comment by veddermatic** [comment]
I too had this problem but doing this:

    statics: {
        willTransitionTo: function (transition, params, query) {
            if (someCheck()) {
                transition.redirect('newroute');
            }
        }
    },

Seems to work just fine. I couldn't use @robyoder 's solution because I was rendering components "outside" the router as well.

**Comment by rafaelbiten** [comment]
I was having the same issue and moving transitionTo to `componentDidMount` did the trick. I'm glad I found this thread! I'm using 0.13.1. Does anyone know if this is any different with 1.0?
