### ISSUE TITLE
Docs History and Hash location types 

### ISSUE THREAD

**Issue by frostymarvelous** [rackt/react-router#604]
Just wanted to say, that I think the docs dont mention anything about the location types and especially how they are selected apart from one example where HistoryLocation was passed to the router. 

After looking through the docs, what I think happens is that createRouter uses a HashLocation by default unless a HistoryLocation is passed. And if a HistoryLocation is passed and the browser doesn't support it, a RefreshLocation which simply refreshes the entire page is used. 

This is vital information that needs to be made available. Sometimes, a person might need to handle the the fallback differently by maybe using the Hash location and knowing how this works helps. 

Personally, I wasn't sure if it would fallback on hashes which would break my site or not, so I had to dig in the source to be sure.

**Comment by ryanflorence** [comment]
new docs site has a full section on the history objects
