### ISSUE TITLE
Redirect Route abortReason caught before use

### ISSUE THREAD

**Issue by CaseyLeask** [rackt/react-router#612]
In the code

```javascript
/**
 * The default aborted transition handler for new routers.
 */
function defaultAbortHandler(abortReason, location) {
  if (typeof location === 'string')
    throw new Error('Unhandled aborted transition! Reason: ' + abortReason);

  if (abortReason instanceof Cancellation) {
    return;
  } else if (abortReason instanceof Redirect) {
    location.replace(this.makePath(abortReason.to, abortReason.params, abortReason.query));
  } else {
    location.pop();
  }
}
```

The location is always a string, hence the rest of the code fails.
I've got an example of the problem at https://github.com/CaseyLeask/react-router-mega-demo/commit/ffb06da63677546e3296e675aa22bb32cad21629

**Comment by maxhoffmann** [comment]
@gaearon You are right. `instanceof` doesn’t work. We currently use the constructor’s name. Also hacky, but works for now.

```js
function handleRouterAbort(abortReason, location) {
  if (abortReason.constructor.name === 'Redirect') {
    return response.redirect(this.makePath(abortReason.to, abortReason.params, abortReason.query));
  }
}
```

**Comment by irvinebroque** [comment]
I ran into this too -- here's an implementation that uses express.js:

https://github.com/irvinebroque/isomorphic-hot-loader/blob/redirects/server.js#L38-L44

However, it breaks when redirect.to doesn't match the redirect path. Unless I'm reading them wrong, it looks like the workarounds from @maxhoffmann @CaseyLeask encounter this too.

Returning `abortReason.path` in addition to `abortReason.to` would solve this.

**Comment by rpflorence** [comment]
Let's add `abortReason.path`. Closing in favor of a pull request from @irvinebroque @maxhoffmann @CaseyLeask :P

I still think status code handling in SSR is clunky, would like to rethink some of the API around it.

**Comment by shyambalu-sellaco** [comment]
What was the conclusion on this, I'm running into the same error. I need to override the onAbort function on server?

**Comment by martintietz** [comment]
+1 :)

**Comment by benjie** [comment]
I've only just started with ReactRouter, I'm using the following which seems to work:

```
middleware = (req, res, next) ->
  router = Router.create
    routes: routes
    location: req.url
    onError: (error) ->
      next(error)
    onAbort: (abortReason) ->
      if abortReason.constructor.name is 'Redirect'
        {to, params, query} = abortReason
        url = router.makePath(to, params, query)
        res.redirect url
      else
        next(abortReason)

  router.run (Handler, state) ->
    # ...
```
