### ISSUE TITLE
Same route multiple handlers

### ISSUE THREAD

**Issue by reggi** [rackt/react-router#616]
Lets say I had two different views / handlers for the same route.

In this example I have a `/blog:post` route. I have two different templates one for a `food` post and one for a `cocktails` post.

```
<Route path="/blog/:post" name="blog-food" handler={BlogPost({"type":"food"})} />
<Route path="/blog/:post" name="blog-cocktails" handler={BlogPost({"type":"cocktails"})} />
```

or

```
<Route path="/blog/:post" name="blog-food" handler={ BlogPostFood } />
<Route path="/blog/:post" name="blog-cocktails" handler={ BlogPostFood } />
```

I'd want to specify some boolean prop somewhere that specifies specific `post_type` from my data source and not here at the top level.

You could imagine I'm pulling JSON at the post level like this.

```
{
  "post": {
    "type": "food"
  }
}
```

Is this possible?

I know that at the `Route` level I could supply a component like this:

```
var BlogPost = React.createComponent({
  render: function(){
    return (
      <If condition={ this.props.type === "food" }>
      <BlogPostFood>
      </If>
      <If condition={ this.props.type === "cocktail" }>
      <BlogPostCocktail>
      </If>
    )
  }
});
...
<Route path="/blog/:post" name="blog-cocktails" handler={ BlogPost } />
...
```

However and I know this is tricky, I need to render both of these blog post types to strings. So I'd need some way of providing a flag somewhere in `Router.run` or the `Element` in the code below that would specific what layout I need to be rendered.

```
Router.run(Routes, path, function (Handler) {
    var Element = React.createFactory(Handler);
    var rendered = React.renderToString(Element());
});
```

**Comment by rpflorence** [comment]
I'm sorry, I still don't get it, but yes, you can pass props to the handler, they will be available in `this.props`.

Again, the router will match a path to a handler, render whatever you want inside of it. I wish I could help more. I'm closing this since there's nothing actionable coming out of it, but please feel free to try to help me understand the use-case better :(
