### ISSUE TITLE
Resource action routes

### ISSUE THREAD

**Issue by tacomanator** [rackt/react-router#648]
I find myself wanting to write:

    <Route name="resource/:id" path="resource" handler={Resource}>
        <Route name="resource-view" path="view" handler={Resource}>
        <Route name="resource-edit" path="edit" handler={Resource}>
    </Route>

From within ```Resource```, how can I determine if the active named route is ```resource-view``` or ```resource-edit```? The mixins in ```Router.State``` allow inspection of the path, but this seems that it is not the right approach. I can't seem to pass data into the handler as props either.

I thought to perhaps have a separate handler for each action as in ```ViewResource``` and ```EditResource```. However, the content and state of many of the actions is so similar that I would then end up with a bunch of components whose only purpose is to pass a single property (the current action) into the actual ```Resource``` component.

What I am doing currently is to use a dynamic segment for the action (view, edit, etc.), and then using ```getParams()``` to lookup, but then I lose the ability to name the routes.

**Comment by rpflorence** [comment]
> I would then end up with a bunch of components whose only purpose is to pass a single property (the current action) into the actual Resource component.

That's perfectly fine, to me. If it really bothers you, you can:

```
mixins: [ Router.state ],

render () {
  var name = this.getRoutes().reverse()[0].name;
  // branch here
}
```

but declarative is always better, and that's what you get when you use separate handlers.
