### ISSUE TITLE
Regex based active state?

### ISSUE THREAD

**Issue by drewhamlett** [rackt/react-router#653]
Say I have something like this
```html
<Route name="stores" path="/stores" handler={Stores} />
<Route name="storesShow" path="/stores/:id" handler={StoresShow} />
<Route name="storesEdit" path="/stores/:id/edit" handler={StoresEdit} />
```

Using `<Link to="stores">`, the first route is the only route that get's the active state.  How could I make it so the Link gets an active state if the other two routes(stores/:id, stores/:id/edit) gets the active state?

Thanks!

**Comment by mjackson** [comment]
You need to use `<Link to="storesShow">` or `<Link to="storesEdit">` to get active state on links to those routes. Does that make sense?

**Comment by rpflorence** [comment]
If they were nested, the parent would be active when a child is. When they are not nested, they are not active.
