### ISSUE TITLE
ignore scroll behavior docs?

### ISSUE THREAD

**Issue by kellyrmilligan** [rackt/react-router#655]
I need to scroll the page to top when the query param changes. I can just do it in component will receive props or something like that , but I found an issue where this was specficially changed to not scroll when the query param changes vs teh route param. it mentions ignore scroll config, but I can't find this anywhere in the docs. is there an example somewhere?  what is the suggested way to scroll to the top when the query string params change?

**Comment by gaearon** [comment]
I think you'll need to do that in `componentWillReceiveProps` in this case.

Currently the way it works is like this:

* When only query changes doesn't do anything—that's entirely on you
* When params *or* route changes, router respects whatever `scrollBehavior` is set in config (by default, `ImitateBrowserBehavior`)
* There is an exception to second rule: if any of the shared ancestors of previous and next route have `ignoreScrollBehavior` option, router does nothing

**Comment by kellyrmilligan** [comment]
Cool that works for me. Isnignorescrollbehavior and option on a route then? I couldn't find it in the docs at all

**Comment by gaearon** [comment]
Yup, it's an option on `Route`. You're right it's not in the docs. @rpflorence

**Comment by gaearon** [comment]
@kellyrmilligan 

Thank you for raising this!
It's here now:

https://github.com/rackt/react-router/blob/master/docs/api/components/Route.md#ignorescrollbehavior

**Comment by tiemevanveen** [comment]
The router [doesn't manage](https://github.com/reactjs/react-router/blob/master/docs/API.md#link) scroll positions any more. Try https://github.com/taion/react-router-scroll.
