### ISSUE TITLE
ES6 classes and the use of mixins

### ISSUE THREAD

**Issue by jbrantly** [rackt/react-router#659]
With React v0.13 the use of ES6 classes will be available. According to facebook/react#1380 mixins will not be magically supported for ES6 classes like they are today with `createClass`. With React Router v0.9 taking away the RouteStore methods and making them only available via mixins, are there any plans for supporting React Router with ES6 classes once v0.13 lands?

**Comment by josebalius** [comment]
+1

**Comment by rpflorence** [comment]
Of course :)

Though, Sebastian just said at ReactConf  "keep using mixins until there is a better solution".

We haven't explored any alternatives to mixins, so we'll keep using them until then, but like React, we don't want to prescribe an object model either.

**Comment by alexeygolev** [comment]
Was wondering if subclassing can solve it for now. A 'mixin' can extend ```React.Component``` and all the components we need to use this 'mixin' could just extend it. Seems to be working. Am I missing something? (besides the fact that the mixins already created are not compatible with this pattern)

**Comment by edygar** [comment]
I think it could keep existing anyway. The way I would use would be something like this:

*Obs: Borrowed State Mixin the example from docs.
```js
import mixin from './utils';
import React from 'react';
import Router from 'react-router';
const {State, Link} = Router;

export default class Tab extends mixin(React.Component, State) {
  render() {
    let isActive = this.isActive(this.props.to, this.props.params, this.props.query);
    let className = isActive ? 'active' : '';
    let link = (
      <Link {...this.props} />
    );
    return <li className={className}>{link}</li>;
  }
}
```

**Comment by badsyntax** [comment]
@edygar can you share the code in your mixin() function?

**Comment by gilbox** [comment]
fwiw, here is a simplistic implementation of Mixin that works similar to what edygar posted above:

```
assign = require('object.assign');

/**
 * merges two objects and returns a new class as the result
 * @param mixins: 1 or more classes
 * @returns {Function}
 */
module.exports.Mixin = function Mixin(...mixins) {
  var Class = function(...args) {
    mixins.forEach((mixin) =>
      mixin.constructor && mixin.constructor.call(this, ...args)
    );
  };

  assign(Class.prototype, ...mixins);

  return Class;
};
```

You pass in regular javascript objects and it will treat the property `constructor` like actual class constructors.

Of course, this implementation does not include all of that React magic that merges lifecycle methods. In most cases you I think we should avoid using mixins with lifecycle methods. That said, I still use `React.createClass`.

**Comment by kidwm** [comment]
@ryanflorence so how to handle this with ES6 Class after react-router 1.0? or should I just write a decorator to do the mixin functions with Babel?
