### ISSUE TITLE
Easy way to check if there's a child route that's active

### ISSUE THREAD

**Issue by KyleAMathews** [rackt/react-router#660]
Pre API changes, I used to be able to easily create index pages like the following:

```
<Route handler={Things}>
  <Route handler={EditThing} />
</Route>
```

Then within the `Things` handler:

```javascript
render: function () {
  if (has_active_child_route()) { // I forget the function now
    render_child();
  }
  else {
    <Index things={@props.things} />
  }
}
```

Is there an easy way still to check within a route handler if there's currently a child route that's also active? I can do what I want with some fiddling with the State mixin but it's not as simple as just asking if there's a child route active or not.

**Comment by gaearon** [comment]
Why not make `Index` also a nested route (and the default one)?

**Comment by KyleAMathews** [comment]
Ahem, [DefaultRoute](https://github.com/rackt/react-router/blob/master/docs/api/components/DefaultRoute.md) is what I wanted. Thanks!

**Comment by KyleAMathews** [comment]
Well... sorta. This requires that I have an empty Route handler around the index/subpage routes. Though that's still better overall.

**Comment by KyleAMathews** [comment]
Though that did let me whip up a little breadcrumb component to use there.
