### ISSUE TITLE
transitionTo not working after async call

### ISSUE THREAD

**Issue by cmschuetz** [rackt/react-router#663]
Hi all,

I'm having an issue with multiple transitionTo calls where the first renders correctly, but the second does not after an async call.

```javacript
  mixins: [Navigation],

  handleSubmit: function(){
    this.transitionTo('loading');
    var entid = this.refs.entid.getDOMNode().value.trim();
    var pass = this.refs.pass.getDOMNode().value.trim();
    scrammer.scrape(entid,pass,this.afterScrape);
  },

  afterScrape: function(courses){
    console.log(courses)
    this.transitionTo('courses')
  }
```

After a form submission, handleSubmit gets called and transitionTo correctly renders the loading screen.  After, my scraper gets called, returns, and successfully calls afterScrape because it logs the courses that it found.  With that said, the courses page never renders.

I've also tried putting in a Link to courses on the loading page and when it gets clicked, courses successfully renders.  Does anyone have any idea why the second transitionTo isn't working?

**Comment by gaearon** [comment]
No errors in console?

Can you normally access `courses` by typing its path in address bar? Could there be an stuck `willTransitionTo` waiting for something that never happens?

**Comment by cmschuetz** [comment]
is there a way I can use transitionTo without the mixin?

**Comment by gaearon** [comment]
Yup, see this for example:

https://github.com/rackt/react-router/blob/master/docs/guides/flux.md

**Comment by cmschuetz** [comment]
Guess who's an idiot?

I forgot to call preventDefault after the form submission so the page would refresh and throw everything off.  It's now working.  Thank you, and this can be closed out

**Comment by gaearon** [comment]
Whoops, I haven't thought about it.
Thanks for checking in back, hopefully somebody else who stumbles into this will find it :-)
