### ISSUE TITLE
Links as Bootstrap Tabs

### ISSUE THREAD

**Issue by nickretallack** [rackt/react-router#666]
In bootstrap, the class="active" on tabs is unfortunately applied to the ```<li>```, not the ```<a>```.  Is there a way to work around this, so I can have links that look like bootstrap tabs?

**Comment by nickretallack** [comment]
Hm.  Can you subclass stuff in react?  This would be pretty easy if I could just make my own version of Link with a slightly different render method on it.

**Comment by gaearon** [comment]
React doesn't allow inheritance (at least not until ES6) and it's a [deliberate decision](https://github.com/facebook/react/issues/613#issuecomment-29280175):

>Many people have become accustomed to using OO inheritance not just as a tool, but as the primary means of abstraction in their application. I've you've worked at a Java shop, you'll know what I'm talking about. In my personal opinion, classical OO inheritance (as implemented in many popular languages) is not often the best tool for most jobs, let alone all jobs. But the situation should be approached with even more caution when inheritance is used within a framework or paradigm that uses functional composition as its primary abstraction (React). There are certain patterns we'll want to prevent (there are many strange things that people can come up with when combining render with inheritance that don't make sense and are addressed via simple composition). There's also risk of making mutation more convenient. It might make sense to start with ES6 classes simply as a better syntax for React component creation, intentionally limiting some use cases (limiting inheritance depth, making some React base class methods final) (only when used with React components of course - all non-React use of ES6 classes wouldn't be restricted).

Mostly when you want to inherit something in UI, you can achieve the same much easier with composition. For example:

```
var MyLink = React.createClass({
  mixins: [State],

  render: function () {
    var isActive = this.isActive(this.props.to, this.props.params, this.props.query);
    return (
      <li className={isActive ? 'active' : null}>
        <Link {...this.props}>{this.props.children}</Link>
      </li>
    );
  }
});
```

`{...this.props}` is called [JSX spread attribute](https://gist.github.com/sebmarkbage/07bbe37bc42b6d4aef81) syntax, it allows you to destructure objects into props. In this case, I'm just passing all MyLink's props to inner Link.

**Comment by nickretallack** [comment]
This works, thanks.

**Comment by justin808** [comment]
@gaearon Just updated to latest and I get this deprecation message:
```
Warning: Router.State is deprecated. Please use this.context.router.isActive() instead
```

The new code can be found here: https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md

```
var Tab = React.createClass({
  render: function () {
    var { router } = this.context;
    var isActive = router.isActive(this.props.to, this.props.params, this.props.query);
    var className = isActive ? 'active' : '';
    var link = (
      <Link {...this.props} />
    );
    return <li className={className}>{link}</li>;
  }

});
```

**Comment by gaearon** [comment]
The docs fail to mention you need to declare `contextTypes` for context to work.

**Comment by gaearon** [comment]
@ryanflorence I added https://github.com/rackt/react-router/commit/c17ef2717bef98c145f90e9a46c13f9e211bf1ed as this seems to be the main source of confusion.

**Comment by four43** [comment]
Thanks @gaearon and @justin808 

Using the docs as referenced by @gaearon here: https://github.com/rackt/react-router/blob/c17ef2717bef98c145f90e9a46c13f9e211bf1ed/docs/api/RouterContext.md

Here is my final component that is working as of React v0.13.1 and React-Router v0.13.2

```javascript
var React = require('react'),
	Link = require('react-router').Link;

var NavTab = React.createClass({
	contextTypes: {
		router: React.PropTypes.object.isRequired
	},
	render:       function () {
		var isActive = this.context.router.isActive(this.props.to, this.props.params, this.props.query);
		var className = isActive ? 'active' : '';
		var link = (
			<Link {...this.props} />
		);
		return <li className={className}>{link}</li>;
	}

});

module.exports = NavTab;
```

**Comment by zhangda89** [comment]
isActive is not undefined

**Comment by mdornseif** [comment]
You can "route around" that issue also by just fixing bootstrap:
```
<style>
.nav-tabs > li > a.active,
.nav-tabs > li > a:hover.active,
.nav-tabs > li > a:focus.active {
  color: #555;
  cursor: default;
  background-color: #fff;
  border: 1px solid #ddd;
  border-bottom-color: transparent;
}
</style>
```
