### ISSUE TITLE
How to get parent url?

### ISSUE THREAD

**Issue by natew** [rackt/react-router#669]
Wondering if react-router exposes a way to programmatically traverse the route tree, in my specific use case I want to get the parent of my current route.

Is this doable now? Was thinking the Navigation mixin would be a nice place to add something like this, I could take a stab.

**Comment by gaearon** [comment]
You should be able to do that with [`State#getRoutes`](https://github.com/rackt/react-router/blob/master/docs/api/mixins/State.md#getroutes).
