### ISSUE TITLE
access props of component being unmounted

### ISSUE THREAD

**Issue by kellyrmilligan** [rackt/react-router#670]
I am managing meta data and some page classes from page to page, and what i'm seeing is that when I get the new data for a new page, it runs through my app.jsx, passes the new props down the chain, and when the old routhandler's component will unmount lifecycle method is called, it now has the new data and not the data that was associated with it. 

any ideas on how to access the data for the component that is being unmounted?

**Comment by rpflorence** [comment]
When you get the new data, what do you think about storing it somewhere for later?

**Comment by kellyrmilligan** [comment]
I was just thinking through that actually. for the timebeing, I went with a different approach of a convention to know what to remove first for each update, instead of relying on previous data to do it. but yeah, down the road i'm going to store the existing data as it comes in to be able to access it later on for things like page transitions, etc.
