### ISSUE TITLE
Misleading error message as result of comments

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#672]
This one has bitten me several times. If you're not very used to jsx yet, and by accident put a // comment somewhere in the router jsx structure, you will get an error like this

```Invariant Violation: Unrecognized route configuration element "<UnknownComponent>"```

Someone like me might read that there is a mistake in one of the active routes, and starts looking in all the wrong places. Maybe even commenting out other blocks which only adds to the problem.

It would be great if the error could print something more informative. I've just wasted a few hours tracking this down and really felt like I was going insane. When scanning over the source code my brain is really trained to ignore comments.

**Comment by 0x80** [comment]
Sorry nevermind. I didn't test properly. The error was actually coming from "//" style comments in the jsx structure. Shouldn't code with a hangover. But these kinds of errors are really hard to track down. Just wasted a few hours on this :(

**Comment by zhiyelee** [comment]
+1 and thx @0x80

**Comment by mpal9000** [comment]
Hi, can you please publish this change df38294. My problem is not about comments but in element.type checking, which is fixed by this change.
