### ISSUE TITLE
Avoid exception when tearing down a router with string location

### ISSUE THREAD

**Issue by olance** [rackt/react-router#673]
The current `teardown` static method of the Router component is:

```javascript
teardown: function() {
              location.removeChangeListener(this.changeListener);
          }
```

The `removeChangeListener` function being absent on the `String` class, this will raise an exception when a router with "static" location is tear down. I'd suggest this simple change:

```javascript
teardown: function() {
            if(location.removeChangeListener)
            {
              location.removeChangeListener(this.changeListener);
            }
          }
```

Would it be reasonable to add this check?

**edit** I have gotten myself out of the situation where this was a problem for me, but the issue might still stand anyway?

**Comment by mjackson** [comment]
@olance This is fixed in master.

**Comment by olance** [comment]
ok thanks :)
