### ISSUE TITLE
Breaking style sheet links? 

### ISSUE THREAD

**Issue by benoneal** [rackt/react-router#675]
This seems like it shouldn't happen... and if it were happening, that it should have caused a riot already... but in my app, it appears that my stylesheet links are breaking because the urls are being intercepted by react-router. When I attempt to navigate to the css via view page source, it shows me the NotFoundRoute handler, and if I look in the resources panel of Chrome, it shows me the html...

**Comment by gaearon** [comment]
This doesn't look like router's problem—you're probably serving index.html even for CSS paths.
What server do you use?

**Comment by benoneal** [comment]
It's definitely the router's problem. Using react-router on a completely different app, it tried to hijack the script src attribute, redirecting "/build/client.js" to the NotFoundRoute handler. It looks like if you use a href or src attribute on any native tags, the router redirects them. :(

**Comment by gaearon** [comment]
A client-side router can't possibly “hijack” other requests.
This is a problem with your server setup.

Which is why I'm asking: what server do you use for serving static files in development environment?

**Comment by benoneal** [comment]
Well then the issue is that the router is running server-side. I'm making an isomorphic app, Express4 server, using webpack to bundle. I was under the impression that react-router was suitable for server-side rendering?

**Comment by gaearon** [comment]
Do you use webpack-dev-server for serving static files in development?

**Comment by benoneal** [comment]
Yup.

**Comment by gaearon** [comment]
So dev-server and Express app run on different ports?

See example setup: https://github.com/gpbl/isomorphic-react-template

It seems that you're requesting JS/CSS on Express' port instead of Webpack's.

**Comment by gaearon** [comment]
See also: https://github.com/gaearon/react-hot-loader/issues/46#issuecomment-66960643

**Comment by benoneal** [comment]
For dev, the assets are called from the absolute webpack port, for live, they are called relatively from the app. It's the live assets that are giving me grief, when webpack isn't even running.

**Comment by gaearon** [comment]
How do you configure Express to serve static assets?

**Comment by benoneal** [comment]
```js
'use strict';

require('node-jsx').install({ harmony: true });
var express = require('express');
var expressState = require('express-state');
var navigateAction = require('./actions/navigate');
var favicon = require('serve-favicon');
var cors = require('cors');
var compression = require('compression');
var debug = require('debug')('CharityProfileApp');

var React = require('react');
var app = require('./application');
var HtmlComponent = React.createFactory(require('./app/frames/Html'));
var Router = require('react-router');

var server = express();
expressState.extend(server);
server.set('state namespace', 'App');
server.use(favicon(__dirname + '/favicon.ico'));
server.use('/public', express.static(__dirname + '/build'));
server.use(cors());
server.use(compression());

server.use(function (req, res, next) {
  var context = app.createContext();
  var scriptSrc = process.env.NODE_ENV === 'development'
                  ? 'http://localhost:9001/build/client.js'
                  : '/build/client.js';

  debug('Executing navigate action');
  Router.run(app.getAppComponent(), req.path, function (Handler, state) {
    context.executeAction(navigateAction, state, function () {
      debug('Exposing context state');
      res.expose(app.dehydrate(context), 'App');

      debug('Rendering Application component into html');
      var html = React.renderToStaticMarkup(HtmlComponent({
        scriptSrc: scriptSrc,
        state: res.locals.state,
        markup: React.renderToString(
          React.createElement(Handler, {
            context: context.getComponentContext()
          }), null)
      }));

      debug('Sending markup');
      res.write(html);
      res.end();
    });
  });
});

var port = process.env.PORT || 9000;
server.listen(port);
console.log('Listening on port ' + port);
```

**Comment by gaearon** [comment]
I think you're configuring Express to serve statics by `/public` path:

```js
server.use('/public', express.static(__dirname + '/build'));
```

but `scriptSrc` starts with `/build`: 

```js
  var scriptSrc = process.env.NODE_ENV === 'development'
                  ? 'http://localhost:9001/build/client.js'
                  : '/build/client.js';
```

**Comment by rpflorence** [comment]
happy to keep providing help here, but its simply not possible for the router to do this to you, there's a problem in your server's config.

**Comment by benoneal** [comment]
So just to clarify, having resolved this, that the router *is* capable of hijacking all file requests (such as stylesheets and javascript and other assets), unless those requests are instead handled outside the router. My issue was that I was serving assets from paths which weren't blocked from the router, so the router was trying to handle them and resulting in NotFoundRoute intercepting the request. In the end, it *was* the server config, because I wasn't blocking all asset routes from the router.

**Comment by rpflorence** [comment]
>  the router is capable of hijacking all file requests

I guess the word "hijacking" is what I'm trying to clarify. Your server was configured to have React Router handle routes that it shouldn't have, but its not hijacking anything :)

**Comment by RyanCCollins** [comment]
@benoneal would you happen to know how you ended up fixing this?  I am seeing the same behavior.  With a properly configured express app, after adding React Router on the server, instead of loading the static assets, my Not Found Route is being rendered and sent instead.  Thanks so much!

**Comment by benoneal** [comment]
@ryanccollins any route that you don't explicitly handle via express, will be handled by react router. In my case, I fixed my issue with these changes:

server.use('*/fonts', express.static(__dirname + '/build/fonts', { redirect: false }))
server.use('*/images', express.static(__dirname + '/build/images', { redirect: false }))
server.use('/build', express.static(__dirname + '/build', { redirect: false }))
(sorry I don't have backtick on my phone's keyboard)
