### ISSUE TITLE
Improve the testing story

### ISSUE THREAD

**Issue by tarjei** [rackt/react-router#678]
Hi, as I am upgrading from 0.7 to 0.11.6 I find that testing the router has become harder.

The problem as I see it is that it has become harder to separate out the router and to mock it's behaviour.

1. Link relies on context. 
---------------------------------

This is the first problem. Due to this any component that uses the Link element (or Navigation) must be rendered within a completely rendered router. I used:

```js

var router;
module.exports = {
    clear: function() {
        router.teardown();
        router = null;
    },
    renderWithRouter: function(component, props, context) {
        if (router) {
            console.error("Router allready created, should be destroyed!");
        }
        var page;

        function getPage(name) {           
            return DummyComponent;
        }
        var AppRoutes = require('../routes.jsx')(getPage);

        router = Router.create({
            routes: (
                <Route handler={App}>
                <Route name="test-context-route" path="*"  handler={component}/>

                {AppRoutes}
                </Route>
                ),
            location: Router.HistoryLocation
        });

        router.run(function(Handler, state) {
            //console.log("Handle state:", state.pathname)
            React.withContext(
                context || {}, 
                function() {

                    page = ReactTestUtils.renderIntoDocument(

                        <Handler {...props} />
                    );
                }
            );
        });
        return page;


    }

}
```

Yes, that is a lot of code, and the location:HistoryLocation param is wrong, but IMHO the problem here is that I have to go through all this just get my Link tags right.

**Suggested solution:**

Create a simple way to create a router that doesn't route. I.e. one that just reads the Route structure and validates routes against it. Preferably it could also state which route it has routed to.

Something like:

```js
var router = Router.createTestInstance(routes);

var component = React.render(<div><Link to="myRoute">Test</Link></div>);

var node = component.getDOMNode();

expect(node.querySelector('a').href).toEqual("#/my/path/with/params");

ReactTestUtils.Simulate.click(node.querySelector('a'));

expect(router.currentRoute).toBe('myRoute');

```

In this example, the click simulation will not change the routing because the router does not actually listen to history events. 

2. Subroutes are handled via RouteHandler
-----------------------------------------------------------
The problem here is one of dependency injection. It is very hard to inject dummycomponents into a component to see how it handles rendering a subroute. 

Example:

```
<Route name="main" path="/">
  <Route name="course-frame" path="/course/:id"> 
      <Route name="course" path="/course/:id" />
      <Route name="course-participants" path="/course/:id/participants" />
   </Route>
</Route>
```

Here the route `course-frame` wraps the subroutes and provides loading of the course and various other resources that these subroutes depend on. In 0.7 the subroute was injected as the activeRouteHandler prop that could easily be injected into the component when testing. Now, the component uses the RouteHandler that again uses the context to get the same information.

**Suggested solution: **
There must be a simple way to inject the current Route into the component without having to create a complete routing scenario (this quickly gets tedious). If it would be possible to have back the old way of injecting it via a prop, that would be best.

The point here is that for a larger application having to create a complete router just to check some states quickly gets tedious. 

I apologize for not having had time to follow the API changes as they happened (and thus could have complained earlier) but IMHO the main culprit here is the use of context to inject state in a way that makes it hard to stub.

**Comment by rpflorence** [comment]
Yeah, stubbing context is sort of a pain, but once you get over the hump it makes it pretty easy to send your code down the path you want to test, if this link doesn't help out, please make some noise and I'll reopen this.

https://github.com/rackt/react-router/issues/437

Also, I want to write a testing guide and put some test helpers in the project to make it simpler.
