### ISSUE TITLE
Animations: documentation or integration

### ISSUE THREAD

**Issue by mschipperheyn** [rackt/react-router#681]
I would like to use page transitions in the common way, which I think is:

* Overview page => Detail page = slide left
* Detail page => Overview page = slide right

I would think that the best way to define these kinds of transitions is in the router definition. It's not clear to me what is the best way to execute these basic things. Is it something you guys would consider making part of react-router or is that something more for the default transition tools of react. If so, I would appreciate some documentation on this.

The example provided relates the transition to the RouteHandler but somehow doesn't feel right. I'm not even sure I could achieve the described basic transition without managing state (are we in the overview page or detail page).

**Comment by rpflorence** [comment]
what's tricky about these animations for the web is that you can link from anywhere to anywhere, where on native you tend to have to define a flow of screens.

For this kind of think I like to pass the router state down as props from the top, and then use the lifecycle hooks to decide which way to animate:

```js
Router.run(routes, (Handler, state) => {
  React.render(<Handler {...state}/>, document.body);
});
```

Now you'll have `state.routes` and `state.params` to decide which kind of animation you want to do to which elements in `componentWillMount` and `componentWillReceiveProps`.
