### ISSUE TITLE
RouteHandler nesting requirement?

### ISSUE THREAD

**Issue by mschipperheyn** [rackt/react-router#682]
If I have a tree like this

* Home
     - Inbox
        * Message x

I found it a little surprising that when I started with react-router which is that if I don't nest a RouteHandler throughout an entire tree: Home and Inbox, click a link to say Message x, will end me up at Home.

It would make more sense to me that react-router would apply the highest level available RouteHandler to everything below it.

Because, if Inbox is its own page design which has nothing that transfers to Message x except the url, you end up using stubs for this, right? In the example, what if message takes over the entire inbox page?

* Home
     - Inbox stub
        * Inbox
        * Message x

Perhaps I'm not yet getting it all correctly.

**Comment by gaearon** [comment]
Sorry, can you give a simple (pseudo)code/config example to make this more clear?

**Comment by rpflorence** [comment]
I'm not fully understanding, but let me take stab at it.  Are you saying:

1. Your `Message` view does not share UI with `Inbox`?
2. You want your `Inbox` url to be something like `/inbox`
3. You want your `Message` url to be something like `/inbox/123`

If so, don't nest the routes. The point of nesting is to share UI. You can still "nest" the urls.

```xml
<Route handler={App}>
  <Route name="inbox" path="/inbox" handler={Inbox}/>
  <Route name="message" path="/inbox/messages/:messageId" handler={Inbox}/>
</Route>
```
