### ISSUE TITLE
Dynamic segment doesn't play well with HTML history API.

### ISSUE THREAD

**Issue by crocket** [rackt/react-router#684]
There is a dynamic segment named `/articles/page/:page` in my program.

When I fetch articles on page 2 and transition from `/articles/page/1` to `/articles/page/2`, HTML history doesn't remember the states of page 1.

Thus, when I go back, the URL becomes `/articles/page/1`, but I still see articles on page 2.

**Comment by rickharrison** [comment]
You probably need to implement `componentWillReceiveProps` to update the state for your component.

**Comment by crocket** [comment]
I know that I can check whether dynamic segments changed in componentWillReceiveProps, but if I set states in componentWillReceiveProps, would it save states in HTML history?

**Comment by rickharrison** [comment]
What do you mean by html history. It is up to your component to look at the params passed in and then make sure that your `render` function shows the correct html.

**Comment by crocket** [comment]
When I transition to non-dynamic routes, HTML history remembers what the pages looked like.

But, browsers don't remember what `/articles/page/1` looked like when I come back to it.

**Comment by crocket** [comment]
Oh... browsers don't remember HTML when pushState is invoked.

Forget about it.

**Comment by rpflorence** [comment]
> It's HTML history API. As far as I know, window.history.pushState should memorize what previous pages looked like.

The router + react will rerender what it looked like before, but the browser simply gives us hooks to be able to do that.
