### ISSUE TITLE
Docs dynamic segments componentDidMount

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#685]
In the section "Important Note About Dynamic Segments" it says:

<blockquote>If you have dynamic segments in your URL, a transition from /users/123 to /users/456 does not call getInitialState, componentWillMount or componentWillUnmount.</blockquote>

I believe componentDid(Un)Mount should also be mentioned?

**Comment by mjackson** [comment]
@0x80 I think that's already implied, isn't it? If you'd like to make a PR, go for it. But I don't think it's necessary here.

**Comment by rpflorence** [comment]
Would love to merge an edit from you @0x80 :)

If not, I'll get around to it in my next doc sweep.

(also, there is no `componentDidUnmount`)

**Comment by 0x80** [comment]
It was about time I started practicing with PRs :) Here you go #749

**Comment by 0x80** [comment]
@rpflorence you even mentioned that there is no componentDidUnmount and I still put it in. Haha jeez. Never mind I'll contribute when I have something meaningful to add... :)

**Comment by rpflorence** [comment]
`git commit --amend`
`git push origin docupdate -f`

the pull request will update automatically :)

**Comment by 0x80** [comment]
I had already deleted the branch out of shame :) But I'm learning and this amend thing is very useful! Thanks for your help.

**Comment by inca** [comment]
Sorry about stupid question, but... How to fetch dynamic data, if `componentDidMount` not set? The recipe prescribed by React's [official docs](https://facebook.github.io/react/tips/initial-ajax.html) won't work, then?
