### ISSUE TITLE
Allow extensions to createRoutesFromChildren

### ISSUE THREAD

**Issue by mikew** [rackt/react-router#689]
I've been working on something that allows users of react-router to add their own transforms to react-router. ex:

```jsx
addTransformForType(CollectionRoute, function (child, index) { /* ... */ })
addTransformForType(NamespaceRoute, function (child, index) { /* ... */ })

// now we can do this:
var routes = (
  <Route handler={App} path="/">
    {/*
    This gives the following routes
    They will be wrapped by *WrapperComponent*

    /posts
    /posts/:id
    */}
    <CollectionRoute
        name="posts"
        handlers={{
          index: IndexComponent,
          show: ShowComponent,
          wrapper: WrapperComponent
        }} />

    <NamespaceRoute name="admin" handler={AdminWrapper}>
      {/*
      This gives the following routes
      They will be wrapped by *AdminWrapper*

      /admin/posts
      /admin/posts/:id/edit
      */}
      <CollectionRoute
          name="posts"
          handlers={{
            index: IndexComponent,
            edit: ShowComponent,
          }} />
    </NamespaceRoute>
  </Route>
)
```

I'm wondering if you would be interested in this being added to react-router proper, or if you think this is best suited for an external package.

**Comment by mjackson** [comment]
@mikew I'm afraid I don't quite understand what you're doing here. Can you please explain in a non-technical way what you're trying to achieve?

**Comment by rpflorence** [comment]
Is this sorta like rails `resources :photos` stuff?

**Comment by mikew** [comment]
@rpflorence that's the influence yeah, and to let people add their own transforms for whatever pattern their app may follow.

[Here's the interface I came up with](https://github.com/mikew/react-router-extensions/blob/5b5c16b63d40cfc7e750859851ba77a726e9c631/spec/createRoutesFromChildren.spec.js#L27-L44). The idea is people simply register a function that returns one (or an array of) Route components.

[Here is a more complete example of `CollectionRoute`](https://github.com/mikew/react-router-extensions/blob/5b5c16b63d40cfc7e750859851ba77a726e9c631/spec/included-transforms/transformCollectionRoute.spec.js#L97-L121)

**Comment by rpflorence** [comment]
I think that's pretty cool.

> I'm wondering if you would be interested in this being added to react-router proper, or if you think this is best suited for an external package.

I'd say external package. Every bit of API we internalize has an expense on maintenance and we'd like to keep our focus on the minimum feature-set. Thanks for sharing though :)
