### ISSUE TITLE
How do I get React-Router to play nice with Flux?

### ISSUE THREAD

**Issue by tybenz** [rackt/react-router#691]
So I've been playing with react-router and reflux. I like the idea of having stores at the top level app component and having the state change there trickle down to subcomponents (through props).

If you look at reflux's Todo example, they're using react-router a bit differently than I thought it was intended to be used: https://github.com/spoike/refluxjs-todo/blob/master/js/components.jsx.js#L168

Looks like they have a router component and no matter the route, it uses the `TodoMain` component, which has a switch statement based on the route. Seems odd to me. But I haven't found another good way to define state at the top level and have it trickle down as props to the other components.

Is there a recommended way to do this with react-router?

**Comment by nearengine** [comment]
I haven't used reflux with react-router, but have you taken a look at Fluxxor? They have a mixin you include that trickles the flux object down through your components automatically.

**Comment by gaearon** [comment]
This is a very old example, router API has changed since then.

Check this out:

https://github.com/rackt/react-router/blob/master/docs/guides/flux.md

and this for simple react-router Flux app (not using Flux for routing though):

https://github.com/gaearon/flux-react-router-example

**Comment by tybenz** [comment]
I guess what I'm really asking is... Is there a way for me to specify the same props on all RouteHandler components? What I'd like to do is define my top-level component's state from my 3 main stores and have all route handler components get that data passed in as props. Looks like react-router doesn't have a way to define state on the top-level route handler.

**Comment by gaearon** [comment]
>Is there a way for me to specify the same props on all RouteHandler components?

You can just pass them down as props.

```js
return <RouteHandler someProp={this.props.someProp} />;

// or, for all props,
return <RouteHandler {...this.props} />
```

Is this what you're asking?

**Comment by tybenz** [comment]
@gaearon: Getting closer. Is there a way to set the state on a RouteHandler though? The same way I would on a component?

**Comment by gaearon** [comment]
Your route handlers are normal components. `RouteHandler` is just react-router's wrapper that will pass its props to your route handler matching the current component.

**Comment by rpflorence** [comment]
I updated the flux guide, let me know if it doesn't answer your questions. https://github.com/rackt/react-router/blob/master/docs/guides/flux.md

**Comment by modestkdr** [comment]
@ryanflorence https://github.com/rackt/react-router/blob/master/docs/guides/flux.md returns a 404.

**Comment by timdorr** [comment]
@modestkdr Those docs are based on 0.13 and earlier, so they're very out of date. But if you need to find them, they are here: https://github.com/rackt/react-router/blob/0.13.x/docs/guides/flux.md
