### ISSUE TITLE
"You cannot use <TestLocation> without a DOM"

### ISSUE THREAD

**Issue by mikew** [rackt/react-router#692]
Trying to test the router using jasmine-node and this error seems to fly in the face of the description of `TestComponent`:

> A location that is convenient for testing and does not require a DOM

Here's the whole contents of the test case

```jsx
var Router = require('react-router')
var TestLocation = require('react-router/modules/locations/TestLocation')

describe('Integration', () => {
  it('works', () => {
    var routes = []
    var router

    TestLocation.history = ['/baz']

    router = Router.create({
      routes,
      location: TestLocation
    })

    router.run((Handler) => {
      console.log(Handler)
    })
  })
})
```

**Comment by mjackson** [comment]
Eh, hmm. Ya, that's definitely not supposed to happen. I'll take a look.
