### ISSUE TITLE
Link: support ignoreScrollBehavior

### ISSUE THREAD

**Issue by sdemjanenko** [rackt/react-router#693]
It would be really useful if I could control this on a Link by Link basis.

**Comment by gaearon** [comment]
Can you tell me more about your use case?

**Comment by sdemjanenko** [comment]
I have a list view and i have a details view. The details view has a tabbed
view within it. I would like to scroll to the top when linking to a tab
from outside the details view. But when inside the details view i would
like the scroll position to be maintained.

**Comment by gaearon** [comment]
That's what `ignoreScrollBehavior` should do when applied to details route handler (ancestor of tabs' routes).
