### ISSUE TITLE
Simple routing via nested

### ISSUE THREAD

**Issue by fellz** [rackt/react-router#696]
I am kinda new to react and react-router and found this part pretty confusing and not explained in guide clearly, took a day to clear things out. Will try to explain what i mean.

First i decided to make simple routes with ```react-router``` . Suppose we have 2 components Main and Hello i want to load *Main* component  at url **/** and *Hello* component with **/hello**  , no nesting. I've tried guide and examples and failed to build that scenario. Later i asked @gaearon to explain stuff and he suggested this 

```
var routes = [
   route1
   route2
]
```
That works fine, but not explained in the guide. Later i realized that best practice for ```react-router``` -always nest strategy. Like this: 

```
var routes = (
    <Route handler={App}>
       <DefaultRoute path="/" handler={MainApp}/>
       <Route path="hello" handler={Hello} />
    </Route>
  )
```
We have something like layout and major handler that holds all our other routes. If i am right this could be clearly explained in the guide.

**Comment by rpflorence** [comment]
I'll make sure to add that you can use an array for `routes` in the guide. Thanks for the feedback and your patience :)
