### ISSUE TITLE
Animations based on Previous Route

### ISSUE THREAD

**Issue by skevy** [rackt/react-router#698]
Ok. I'm stumped.

I would like to change parameters of transitions based on the route that I'm transitioning from, and I can't figure out how I can do this with ReactRouter.

The specific use case is the following:

When I transition from my home page to my "browse" page, I have this fancy animation that does a build out and then build in of the browse page. It's a special one off case. When I transition from my browse page to any other page (or vice versa), it's just a simple fade animation. I need to be able to control the parameters of what animations happen when.

I need to some how pass information between two RouteHandlers during a transition (either by props or by some other mechanism). Is this at all possible, or am I going about this completely the wrong way?

I think I'm having a similar problem to the issue described in #681.

Any help would be very much appreciated.

Thanks!
-Adam

**Comment by rpflorence** [comment]
```js
Router.run(routes, (Handler, state) => {
  React.render(<Handler {...state}/>, document.body);
});
```

You'll have `this.props.routes` that you can inspect, as well as `this.props.params`. Every route transition will also now cause `componentWillReceiveProps` to fire where you have access to `nextProps` and `this.props` to do whatever comparisons you need :)
