### ISSUE TITLE
Would anybody talk to me for 1 hour on Skype right now for $60? I really need help.

### ISSUE THREAD

**Issue by andrerpena** [rackt/react-router#699]
I'm really sorry for posting this here.. It might be inappropriate. But I'm deciding whether to use react-router and I'd like to clarify some questions. I'd pay in advance through PayPal.

My Skype is live:andrerpena@gmail.com

You must be experienced with react-router, be able to talk with sound and screen-sharing, and this offer expires in 1 hour.

**Comment by gaearon** [comment]
I think https://www.codementor.io is more appropriate for this.

**Comment by andrerpena** [comment]
Thanks @gaearon . I didn't mean to ask anything inappropriate here.
