### ISSUE TITLE
promise-based solution + flux stores, a clean solution?

### ISSUE THREAD

**Issue by stopachka** [rackt/react-router#700]
Hey everyone, 

I'm trying to implement the async dataflow example, as shown in the [announcement](https://github.com/rackt/react-router/wiki/Announcements), but add stores in the mix, to make sure they are up to date after loading.

```
Comp  = React.createClass
  statics:
      data: (params) ->
           promise...
  mixins: Reflux.listenTo(FooStore, "onFoo")
  getInitialState: ->
     foo: @props.data.promise # set the result of the promise
  onFoo: (foo) ->
      ...
      @setState(foo: foo) # update foo when store emits change event
```

The thing I don't like is that I'm setting state from the @props.data.promise, then connecting it to the store. Seems a bit confusing.

Is there a better way to do this?

**Comment by gaearon** [comment]
I don't think you should ever need to put promises into a store.
I just use a helper like this:

https://gist.github.com/gaearon/886641422b06a779a328

**Comment by stopachka** [comment]
Hey gaearon, the promise is in the component. Essentially what I'm looking to do is something like this ->

1) Don't render a component until all promises have resolved  -- similar to the async data implementation in the announcement --

```
  // 6-line async data implementation
  var promises = state.matches.filter(function (match) {
    return match.route.handler.fetchData;
  }).reduce(function (promises, match) {
    promises[match.route.name] = match.route.handler.fetchData(state.params)
    return promises;
  }, {});

  resolveHash(promises).then(function (data) {
    React.render(<Handler data={data}/>, document.body);
  });
```

2) Once promise finishes, connect to store make sure the promise is up to date.

I'm guessing this isn't the best approach. Your solution looks pretty cool, is there an example I could take a look at that's a bit more involved?

**Comment by gaearon** [comment]
I don't have any readily available code but basically you just implement `fetchData` like this:

```js
fetchData(params) {
  FooActionCreator.fetchFoo(params.id);
  return observeStore(FooStore, s => s.hasFetchedFoo());
}
```

As you can see from my Gist promise returned by `observeStore` resolves when Store emits a change event *and* the predicate you passed to `observeStore` is true.

Does this make sense?

**Comment by johanneslumpe** [comment]
@gaearon cool solution! I was using a hackish approach, by creating dispatch groups, which wait for certain dispatches to happen and then resolve a promise. But this looks nice!

**Comment by rpflorence** [comment]
At the moment, we don't recommend any data solution, but you have the ability to implement your own :)

I like to fill up my stores in `Router.run` and then just pull from them in my components.

**Comment by gaearon** [comment]
>I like to fill up my stores in Router.run and then just pull from them synchronously in my components.

The reason I don't suggest this approach is that you're putting `Handler` in a store. Which means action payload is non-serializable, and record/replay impossible. Now, I'm not using record/replay right now in my Flux app, but I'd like to eventually.

I think I'll file an issue for this scenario..

**Comment by rpflorence** [comment]
I don't put Handler in the store, just data.

```js
Router.run(routes, (Handler, state) => {
  primeStores(state.routes).then(() => {
    React.render(<Handler/>, document.body);
  });
});
```

In `primeStores` it'll load them all up, then when I render you can just ask the stores for their data and it'll be there.

**Comment by gaearon** [comment]
I get it now, makes sense.

**Comment by mockdeep** [comment]
Tuning in a bit late to this conversation, but I've been trying to move some stuff into stores in an application and I'm having trouble understanding how to do something gracefully without promises. For example, I have a page with a form that posts back to the server and then transitions to another page. If I transition right away after making the request, then I get some pop-in while the next page syncs up with the server, and if I just attach to a generic change event on the store, any other change could cause the transition before it has completed. The simplest thing to me is to return the request promise and transition on success. Am I missing something?
