### ISSUE TITLE
Route Inside DefaultRoute not recognized

### ISSUE THREAD

**Issue by yaru22** [rackt/react-router#701]
Hello,

I have routes that look like this:
```js
<Route name="current" handler={require('app/Root')} path="/">
  <DefaultRoute handler={require('app/AdminPage')}>
    <DefaultRoute handler={require('app/AdminCurrent')} />
    <Route name="history" handler={require('app/AdminHistory')} />
    <Route name="preview" handler={require('app/AdminPreview')} />
  </DefaultRoute>
</Route>
```
It calls `AdminCurrent` handler when I go to `/`, as expected.

However, if I have `<Link to="history">History</Link>`, it says 

`Uncaught Error: Invariant Violation: Unable to find <Route name="history">`

Is this a bug? If not, what would be the proper way to structure the routes?

Since AdminCurrent, AdminHistory and AdminPreview all share the same page layout (as defined in AdminPage), I'd like to put the three inside a route that has AdminPage as handler.

Thanks.

**Comment by mjackson** [comment]
@yaru22 A `<DefaultRoute>` can't have children. Try this instead:

```xml
<Route name="current" handler={require('app/Root')} path="/">
  <Route handler={require('app/AdminPage')}>
    <DefaultRoute handler={require('app/AdminCurrent')} />
    <Route name="history" handler={require('app/AdminHistory')} />
    <Route name="preview" handler={require('app/AdminPreview')} />
  </Route>
</Route>
```

**Comment by yaru22** [comment]
Thanks @mjackson. That worked like a charm.
