### ISSUE TITLE
[docs] Reference to nonexisting handler

### ISSUE THREAD

**Issue by morenoh149** [rackt/react-router#705]
this section https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments At the end mentions `Look at the Contact handler in the master-detail example.` But looking above at the example https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#more-nesting there is not `Contact` handler.

**Comment by taurose** [comment]
Seems to be referring to [this example](https://github.com/rackt/react-router/blob/master/examples/master-detail/app.js#L69)

**Comment by morenoh149** [comment]
@taurose so it's refering to a method not within the same document? I think that's an oversight

**Comment by morenoh149** [comment]
:+1:
