### ISSUE TITLE
React peerDependency version

### ISSUE THREAD

**Issue by BinaryMuse** [rackt/react-router#709]
`package.json` lists React as a peerDependency with the version `0.12.x`. Should/could this be relaxed? I'm experimenting with 0.13 alpha and running into issues installing due to this setup.

**Comment by mjackson** [comment]
I'm not sure if this could be relaxed or not. I haven't had any time to play around with 0.13 yet. By all means, relax the dependency version locally, test things out, and let us know how it goes ;)

**Comment by BinaryMuse** [comment]
Things seem okay except for one warning that gets shown on the console quite a bit:

> Warning: owner-based and parent-based contexts differ (values: `[object Object],[object Object],[object Object]` vs `[object Object],[object Object]`) for key (routeHandlers) while mounting ReactCompositeComponent (see: http://fb.me/react-context-by-parent)

I glanced around the code for a quick fix, but I'm not familiar enough with the internals to figure out exactly what's going on.

**Comment by rpflorence** [comment]
We can't relax it, last time we had it relaxed everything went to crap when 0.12 was released. We'll bump it to 0.13 when we know it works with 0.13. With the context changes I'm sure we're in for some issues.

**Comment by mjackson** [comment]
Closing for now. Let's follow up with 0.13 support in #638.
