### ISSUE TITLE
mystery solved

### ISSUE THREAD

**Issue by sjansen** [rackt/react-router#713]
After converting my (toy) app to use react-router, I started getting the following exception when navigating from one route to another:

> Uncaught Error: Invariant Violation: ReactMount: Root element ID differed from reactRootID.

This was caused by my App component used a `body` tag to wrap its children. After switching to a `div` tag the exceptions stopped.

This issue can be closed. I created it in the hope it helps someone else in the future.

**Comment by FoxxMD** [comment]
What does this happen? I need to render multiple components at the top-level of my app and then all need to go in `body` -- how else would I achieve this?

**Comment by srph** [comment]
I think he is referring to:

```es6
React.createClass({
  render() {
    return <body> ... </body>
  }
});
```

**Comment by magicyu90** [comment]
Yeah,that because the <body> tag...
