### ISSUE TITLE
Remove delay on touch devices when touching <Link>s

### ISSUE THREAD

**Issue by OscarGodson** [rackt/react-router#714]
Maybe this works and I just don't know how, but I want touch events to work with this. The only items that have delays right now are the `<Link>`s I have in the app and I want to get rid of those.

**Comment by irvinebroque** [comment]
@OscarGodson - I had the same issue, and it's pretty easy to write your own `<Link/>` component to handle touch events -- all `<Link/>` really does is use the Navigation and State mixins:

https://github.com/rackt/react-router/blob/master/components/Link.js

Just need to call `React.initializeTouchEvents(true)` and use `onTouchStart`:

http://facebook.github.io/react/docs/events.html#touch-events

**Comment by OscarGodson** [comment]
Yeah, like I mentioned im using it everywhere else so I know about the initializeTouchEvents thing but just not on Link. So I think I can just copy paste the Link source code and then add touchStart. Hm. Thanks!

**Comment by stefanfisk** [comment]
I've had success using FastClick for this. Using webpack it's just `var FastClick = require('fastclick'); FastClick.attach(document.body);`.

**Comment by OscarGodson** [comment]
@stefanfisk im not sure FastClick works with React since they're all faux events. I just tried it again to be sure and I'm not seeing it working at all.

**Comment by stefanfisk** [comment]
@OscarGodson I've confirmed it working both by using my app and in the debugger. As long as React doesn't stop bubbling of the touch events FastClick will handle them when they reach `body`, and then trigger a `click` event at the originating element, which React handles like any other click event.

**Comment by OscarGodson** [comment]
@stefanfisk ah, since im using browserify I had to use a bit different syntax but I think fastclick is working. Thank you! Im going to close this since fastclick works for now, but i think it would make sense for the router to accept ontouchstart
