### ISSUE TITLE
component passed to willTransitionFrom hook is component transitioning to, not from

### ISSUE THREAD

**Issue by WickyNilliams** [rackt/react-router#717]
I have views: `ProjectsView` and `EditorView`. EditorView has a `willTransitionFrom`, which warns user before exiting. 

If I open browser straight to EditorView and navigate to ProjectsView then willTransitionFrom gets passed the correct component. However, if I navigate `ProjectsView` -> `EditorView` -> `ProjectsView` then willTransitionFrom gets passed ProjectsView, which is not the desired result.

I have created a reduced test case, and issue seems to be present. You can clone this gist, `npm install` and `npm start`: https://gist.github.com/WickyNilliams/1ec4ee2cab3968b41352

Possibly related to to #703, #567

**Comment by WickyNilliams** [comment]
Tried creating a test for this, which mimics exactly the test case above, but it seems to pass \*sigh\*

```js
it.only('sends the correct component', function(done) {
  var div = document.createElement('div');

  var Bar = React.createClass({
    statics: {
      willTransitionFrom: function (transition, component) {
        expect(component.constructor.displayName).toBe("Bar");
      }
    },
    render: function () {
      return <div id="bar">bar</div>;
    }
  });

  var OuterFoo = React.createClass({
    render: function() {
      return (
        <div>
          <Router.RouteHandler />
        </div>
      );
    }
  });
  var Foo = React.createClass({
    render: function () {
      return <div id="foo">foo</div>;
    }
  });

  var routes = (
    <Route path="/" handler={Nested}>
      <Route handler={OuterFoo}>
        <Router.DefaultRoute name="foo" handler={Foo}/>
      </Route>
      <Route name="bar" path="/bar/:id" handler={Bar}/>
    </Route>
  );

  TestLocation.history = [ '/' ];

  var steps = [];
  steps.push(function () {
    TestLocation.push('/bar/123');
  });
  steps.push(function () {
    TestLocation.push('/');
  });
  steps.push(function () {
    done();
  });

  Router.run(routes, TestLocation, function (Handler, state) {
    React.render(<Handler/>, div, function () {
      setTimeout(function() {
        steps.shift()();
      }, 1);
    });
  });
});
```

**Comment by taurose** [comment]
I think this was fixed in master c6ed6faf439521375376d5890f6d1b2658e1bfbd .

**Comment by WickyNilliams** [comment]
It seems you're right. If i checkout v0.11.6, the test fails.

Interestingly, the test passes if there is no OuterFoo handler...

@mjackson is there a release planned? I guess the fix is tangled with a lot of other changes, so maybe not. Is there some way to put out a patch release with just this fix?

**Comment by taurose** [comment]
Yeah, this only happens after you've been to a route with a higher nesting level (depth).

The underlying problem is that the component list maintained by the router is never cleaned up. Instead, new components just set their reference for their depth when mounted. So in your example the list looks like this: `App > Editor > SavedProjects` (SavedProjects was never replaced).

The way the from transition handler (Transition.from) worked before is that it received all components and matched them to exiting routes starting at the end, so it would match SavedProjects to Editor (since SavedProjects is the deepest known component and Editor the deepest exiting route). If App was exiting, too, it would get the Editor instance. Since the commit, Transition.from gets a trimmed component list whose indexes match with the exiting routes, so it can simply ignore those stale components.

If you want to try a quick fix yourself, I think this should work:

createRouter,js, dispatch(), before:

```js
transition.from(fromRoutes, components, function (error) {
```

after:
```js
// trim components to routes that are actually active
var prevComponents = components.slice(0, prevRoutes.length);
transition.from(fromRoutes, prevComponents, function (error) {
```

**Comment by WickyNilliams** [comment]
Hmm I guess, without having to create a temporary fork, i could just reduce the nesting of the routes. Doesn't actually necessitate big changes:

1. Convert `DashboardView` to use `{this.props.children}` instead of `<RouteHandler />`
2. Wrap everything in returned from `SavedProjectsView` render method with `<DashboardView>{whatever}</DashboardView>` 
3. remove the nesting of routes, so it's like:

var routes = (
  <Route  path="/" handler={require("./AppView")}>
    <DefaultRoute name="saved" handler={require("./SavedProjectsView")}/>
    <Route name="editor" path="/edit/:id" handler={require("./EditorView")}/>
  </Route>
);

Seems to work for now...

**Comment by mjackson** [comment]
@WickyNilliams I'm working up the 0.12 release right now. Will you please close this when it ships, if your issue is resolved? Thanks!

**Comment by WickyNilliams** [comment]
@mjackson sure thing, I'll keep an eye on it. Is it worth making  a PR with the above test case, to guard against future regressions?

**Comment by rpflorence** [comment]
@WickyNilliams we should merge in the test anyway if we don't already have something that tests this :)

**Comment by mjackson** [comment]
@WickyNilliams Absolutely, that would be great.

**Comment by ryanflorence** [comment]
1.0 api on master doesn't keep track of components for transition hooks, so this doesn't apply anymore
