### ISSUE TITLE
active class always set on default route

### ISSUE THREAD

**Issue by theverything** [rackt/react-router#722]
I have a page where I am using tabs to load different "things" into my component. I am using the Link component to create anchor tags for the tabs. When clicking on the tabs the tab associated with the default route is always active.

The default route shows all of the "things"

Is there any way around this?

```
<Route handler={Things} name="things" path="/things">
  <DefaultRoute handler={ThingList} /> // <-- this is always active
  <Route handler={ThingList} name="thingsnew" path="new" />
  <Route handler={ThingList} name="thingsactive" path="active" />
</Route>
```

**Comment by mjackson** [comment]
Ah, this sounds like a bug.

**Comment by rpflorence** [comment]
workaround is to not use DefaultRoute and put the path on it.

```xml
<Route handler={Things} name="things" path="/things">
  <Route name="thingsdefault" path="/things" handler={ThingList} /> // <-- will match first
  <Route handler={ThingList} name="thingsnew" path="new" />
  <Route handler={ThingList} name="thingsactive" path="active" />
</Route>
```

**Comment by taurose** [comment]
Looking at your route config, if you build links like this

```js
<Link to="things">Default</Link>
<Link to="thingsnew">New</Link>
<Link to="thingsactive">Active</Link>
```

I'd expect the first link to always be active when one of the others are, since it's associated with the parent route.

I think you're just missing a name on your default route:
```js
<Route handler={Things} name="things-container" path="/things">
  <DefaultRoute handler={ThingList} name="things" /> 
  <Route handler={ThingList} name="thingsnew" path="new" />
  <Route handler={ThingList} name="thingsactive" path="active" />
</Route>

// a link to "/things" somewhere in your app
// stays active as long as as any type of things (tab) is shown
<Link to="things-container">Go to things</Link> 

// links for tabs
// only one will be active at a time
<Link to="things">Default</Link>
<Link to="thingsnew">New</Link>
<Link to="thingsactive">Active</Link>

```

**Comment by theverything** [comment]
@taurose was correct. I needed to add a name to the DefaultRoute. Everything works as expected now. Thank you!

**Comment by rpflorence** [comment]
Love it when the users know the router better than the authors.

**Comment by fredguest** [comment]
i think this is still a bug if the default route is the root. for example if the route config was:
```
<Route name="app" path="/" handler={App}>
    <DefaultRoute name="things" handler={ThingsView} />
    <Route name="account" handler={AccountView} />
    <Route name="about" handler={AboutView} />
</Route>
```
the default route would always be active, even with an explicit name attribute, because the non-default routes obviously build on top of the root so for any of them to be active the default route must also be.

**Comment by fredguest** [comment]
and actually the workaround doesn't work in this case either:
```html
<Route name="app" path="/" handler={App}>
  <Route name="things" path="/" handler={ThingsView} />
  <Route name="account" path="/account"  handler={AccountView} />
  <Route name="about" path="/about"  handler={AboutView} />
</Route>
```
still results in the "things" link being permanently active.

**Comment by fredguest** [comment]
just kidding. it's not a bug. i had the links setup wrong, like this:
```html
  <li><Link to="app">Things</Link></li>
  <li><Link to="account">Account</Link></li>
  <li><Link to="about">About</Link></li>
```
instead of like this:
```html
  <li><Link to="things">Things</Link></li>
  <li><Link to="account">Account</Link></li>
  <li><Link to="about">About</Link></li>
```
so now with the following config:
```html
<Route name="app" path="/" handler={App}>
  <DefaultRoute name="things" handler={ThingsView} />
  <Route name="account" handler={AccountView} />
  <Route name="about" handler={AboutView} />
</Route>
```
the "things" link is active at the root, but not active at /account or /about, so everything works as expected.
