### ISSUE TITLE
Issue in examples

### ISSUE THREAD

**Issue by bgryszko** [rackt/react-router#724]
I couldn't get examples to work because of an error `undefined 'react-router'` I had. I've fixed it by deleting those lines in `examples/webpack.config.js`:

```
  resolve: {
    alias: {
      'react-router': '../../index'
    }
  },
```

I'm not sure what is  the purpose for that?

**Comment by mjackson** [comment]
This was fixed in 0839f13c51de8e5c3698864640d2022058591d6d
