### ISSUE TITLE
access to path utilities?

### ISSUE THREAD

**Issue by stopachka** [rackt/react-router#729]
I'm working on a project where a section uses react-router, and section doesn't. For the other section, I'd like to extract queries out of the url, to store certain keys in localStorage. 

react-router's `Path` utiil was great for this, but I feel a bit shy about directly requiring this, since it might change in the future. 

Does it make sense to consider exposing some of the utility functions in the main React Router exports?

**Comment by rpflorence** [comment]
You can pull it in, just be mindful when you upgrade, I hear @mjackson say all the time he wants to kill that module.

Another option is to require `qs`, the dependency we use for parsing/serializing query strings. If you package supports deduping, you won't add any overhead to the project.
