### ISSUE TITLE
How do I detect if a transition is trigged by popstate? 

### ISSUE THREAD

**Issue by k88hudson** [rackt/react-router#734]
I'm trying to set the transitionName to something specific if a user clicked a back button. Is there some way to detect this in `willTransitionFrom` or `willTransitionTo`?

**Comment by gaearon** [comment]
Hmm..

This is available on `state` object you get as a second argument in `Router.run` callback. You can check `state.action === 'pop'`. However this is true both for Back and Forward browser buttons (we can't really tell between these two).

As for getting that into component hooks.. There's a discussion in https://github.com/rackt/react-router/pull/590 on passing that `state` object to hooks but it's not finalized yet. Hopefully what I wrote in previous paragraph can help you get started!

**Comment by k88hudson** [comment]
Thanks  @gaearon, much appreciated

**Comment by rpflorence** [comment]
Unless I'm mistaken, we are telling you everything we can know. Closing this ticket, but please continuing the "state sent to hooks discussion" on #590 :)

**Comment by k88hudson** [comment]
Will do, thanks!
