### ISSUE TITLE
posible false 'Invariant Violation: Missing parameter "id" for path "/article/:id"' Error when using Link

### ISSUE THREAD

**Issue by alexaivars** [rackt/react-router#737]
The following type of component throws a Error: Invariant Violation: Missing "id" parameter for path "/article/:id" if the article prop is undefined. But we handle this type of situation by render nothing if our prop is undefined. Is this bug in react-router or am I just using a bad style of coding and is there a better way to handle such situations?  
```
var routes = [
     <Route path="/" handler={ApplicationHandler}>
       <Route name="article" path="/article/:id" handler={ArticleHandler}/>
       <NotFoundRoute name="404" handler={NotFoundHandler}/>
     </Route>
   ];

var Example = React.createClass({
      propTypes: {
       article: React.PropTypes.shape({
         id: React.PropTypes.string.isRequired
        })
      },
      render: function () {
        var article = this.props.article;
        if (!article) {
          return false;
        }
        return (
            <article>
              <Link to="article" params={{id: article.id}}>{article.title}</Link>
            </article>
        );
    }
});
```

**Comment by alexaivars** [comment]
sorry just move along, apparently a late night coding bug.

**Comment by adibsaad** [comment]
It'd be nice to know what it was for people who might have had a similar issue.

**Comment by tjwebb** [comment]
+1

> apparently a late night coding bug.

Lots of people have these

**Comment by alexaivars** [comment]
just a typo article not empty but article.id was undefined and I missed the warning. 
but we now started wrapping our route with en handler 

<Route path="/article" handler={ArticleHandler}/>
  <Route path="/article/:id" handler={ArticleItemHandler}/>
</Route>

**Comment by csaintc** [comment]
This issue made my grandma cry.

It would be immensely useful to be able to know which Link is throwing the exception.
:+1:

**Comment by SimonErich** [comment]
In my case it was a <Link to=".." /> Component, that did not have the params yet.
I guess this is the case for most of those errors as well, because you don't think about it, when you see the error message.
Just for future searchers: after you change your route, change if you gave all Link components the new params as well ;)

**Comment by DelvarWorld** [comment]
In my case, also a strange debugging nightmare, I was rendering a `<Link />` without a `to` component by a typo (hard to spot). An error specifying that it's a **link** component causing the error would be helpful - I kept thinking something was erroneously triggering a transition.
