### ISSUE TITLE
Parent route handler loses state when I navigate it's child routes

### ISSUE THREAD

**Issue by evindor** [rackt/react-router#738]
My routing:
```
  <Route name="app" path="/" handler={Application}>
    <Route name="login" handler={Login}>
      <Route name="signup" handler={SignUp}>
        <Route name="signup-step-one" path="step-one" handler={SignUpStepOne}/>
        <Route name="signup-step-two" path="step-two" handler={SignUpStepTwo}/>
        <Route name="signup-verification" path="verification" handler={SignUpVerification}/>
        <DefaultRoute handler={SignUpIndex}/>
      </Route>
      <Route name="signin" handler={SignIn}/>
      <DefaultRoute handler={LoginIndex}/>
    </Route>
  //......    
  </Route>
```

As you can see I have several sign up screens and I need to save the state (user's input) for last `SignUpVerification` view where I'll submit it to server. I decided to keep that state in the `SignUp` component. The problem is that I lose state on my `SignUp` component on every route update. If I simply `console.log` something in all components' `getInitialState`, I get the following results:
1. `Application` component logs only once and keeps state no matter the route
2. `Login` and `SignUp` components log to console every time I switch between `/login`, `/login/signup/`, `/login/signup/step-one`, `/login/signup/step-two` etc.

I'm pretty sure it's me doing something wrong as I checked out [shared root example](https://github.com/rackt/react-router/blob/master/examples/shared-root/app.js) and it's `SignedOut` component doesn't reinitialize every time I navigate it's children routes. Could someone help me out with that?

**Comment by gaearon** [comment]
Can you show Application's render code?

**Comment by evindor** [comment]
@gaearon sure,
```javascript
  render: function() {
    var name = this.getRoutes().reverse()[0].name;
    return (
      <div>
        <div className="snap-drawers"><MenuDrawerView snapper={this.state.snapper}/></div>
        <div id="app" className="snap-content">
          <TransitionGroup transitionName="example">
            <RouteHandler snapper={this.state.snapper} key={name} />
          </TransitionGroup>
        </div>
      </div>
    );
  },
```

**Comment by evindor** [comment]
Further, `Login` render code is just
```
  render: function() {
    return (
      <RouteHandler/>
    );
  },
```

and `SignUp`:
```
  render: function() {
    return (
      <RouteHandler user={this.state} updateUser={this.setState.bind(this)}/>
    );
  },

```

**Comment by rpflorence** [comment]
Its because you have keys on your `RouteHandler`s. That causes the component to be torn down and re-created (that's also why you can have two on the page at the same time to animate them).

You'll need to move that state up to App or a store somewhere.

**Comment by evindor** [comment]
Thanks! I had so much headache with this.
