### ISSUE TITLE
Unit testing React components with `Link` components is impossible

### ISSUE THREAD

**Issue by gregeinfrank** [rackt/react-router#739]
I know there is this TestLocation: https://github.com/rackt/react-router/pull/686

But, it's not clear how this really helps if I want to unit test a component within my views. Something like a side nav, that has a bunch of `Link`s, I need to set up routes with the TestLocation if I want to just render the side nav alone to unit test?

Can someone maybe explain how I should be using `TestLocation` properly if that fixes my issue?

Thanks!

**Comment by jacobstr** [comment]
I just figured this out last night and it was a moderately confusing experience... Un momento.

**Comment by jacobstr** [comment]
Just wanted to sanitize this as much as I could.

    jest.dontMock('../Logs');
    
    var React;
    var TestUtils;
    var Logs, LogHandler, Logstore;
    var Router, TestLocation;
    var routes;
    
    describe('Logs', function() {
      beforeEach(function(){
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
    
        Logs = require('../Logs');
        LogHandler = Logs.LogHandler;
        LogStore = Logs.LogStore;
    
        Router = require('react-router');
        // Yes, this is officially ok.
        TestLocation = require('react-router/modules/locations/TestLocation');
        TestLocation.history = ['/logs/all/all/date_desc/1'];
        routes = <Router.Route name="logs" path="/logs/:kind/:filter/:sortBy/:page" handler={LogHandler}/>;
      });
    
      // The Logs component contains a few Links that toggle the various routes.
      // I just wanted to test that my table was rendering results 'reasonably', but
      // but Link elements within it were causing problems.
      describe('Filtering', function() {
        it('should filter log data', function() {
          // Implementation detail for my project.
          LogStore.getLogs = jest.genMockFunction().mockReturnValue([
            {id: 0, kind: 'transfer' },
            {id: 1, kind: 'magicdance' },
            {id: 2, kind: 'safetydance' }
          ]);
    
          // Important.
          TestLocation.history = ['/logs/transfer/all/date/1'];
          Router.run(routes, TestLocation, function(Handler) {
            var handler = TestUtils.renderIntoDocument(<Handler />);
            // So this was the gotcha for me. The handler was not the component I was
            // looking for. Toss a console.log here for a better view. A repl would
            // be ideal but Jest made it a bit of pain.
            var component = handler.getRouteComponents()[0];
            // This is what I've registered as a change handler.
            component.onChange();
            expect(TestUtils.scryRenderedDOMComponentsWithClass(component, 'log-entry').length).toBe(1);
          });
        });
      });
    });

**Comment by rpflorence** [comment]
I finally pushed this guide, sorry for the trouble. https://github.com/rackt/react-router/blob/master/docs/guides/testing.md

**Comment by kellyrmilligan** [comment]
I keep on finding references to this guide in searching for an example on how to test my page handlers, will this be available in the new docs soon?

**Comment by maksad** [comment]
@ryanflorence unfortunately the reference does not exist

**Comment by izaakrogan** [comment]
@ryanflorence :+1:

**Comment by robcolburn** [comment]
@ryanflorence - your link broke, because it's no longer on `master`, here's the tagged version.
https://github.com/rackt/react-router/blob/0.13.x/docs/guides/testing.md

Is the 1.0 version?

**Comment by knowbody** [comment]
@robcolburn we don't have docs for `testing` yet. If anyone is up for writing those I'll be happy to merge that PR. If not I try to write something when I find some free time.

**Comment by kivohin** [comment]
The link mentioned before in comments is now: [https://github.com/rackt/react-router/blob/master/docs/guides/Testing.md](url)

**Comment by imjared** [comment]
and moved again... https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/testing.md

**Comment by NullVoxPopuli** [comment]
this is what I do:

```js
import React from 'react';
import { MemoryRouter } from 'react-router-dom';

export const withRouter = (Component, locations = ['/']) => props => (
  <MemoryRouter initialEntries={locations}>
    <Component location={{}} { ...props }/>
  </MemoryRouter>
);
```

usage:

```js
const wrapper = mount(withRouter(Component)(myProps));
```

**Comment by Lomse** [comment]
In case you are using `react-test-renderer`, you can do the following as well when testing the `Landing` component which contains a`Link` component: 
```
import React from 'react'
import renderer from 'react-test-renderer'
import { MemoryRouter } from 'react-router'
import Landing from './Landing'

test('Landing renders correctly', () => {
	const component = renderer.create(
		<MemoryRouter>
			<Landing />
		</MemoryRouter>
	)
	const tree = component.toJSON()
	expect(tree).toMatchSnapshot()
})

```

Below is the `Landing` component
```
import React from 'react'
import { Link } from 'react-router-dom'

const Landing = () => (
  <div className="landing">
    <h1>Movie Library</h1>
    <input type="text" placeholder="Search..." />
    <Link to="/search">or Browse All</Link>
  </div>
)

export default Landing

````

But do I need to install the whole `react-router` library just to test one component which contains a `Link` component?

**Comment by joshjung** [comment]
This problem is further compounded when using `enzyme`. Enzyme only lets you do things like `setState` etc. on the root component you have mounted. This means if you wrap your component that contains a `Link` inside a router, then the root component is now the router and you cannot test your component with `setState` or `update`... as least as far as I can see. Any ideas?

**Comment by NullVoxPopuli** [comment]
Checkout this project: https://github.com/NullVoxPopuli/react-vs-ember/tree/master/testing/react (specifically that folder) 

It demonstrates how to test anything and everything *worth* testing.
