### ISSUE TITLE
Navigation.goBack(), then setState on destination page

### ISSUE THREAD

**Issue by pxwise** [rackt/react-router#740]
When using Navigation.goBack(), I am returned to a version of the previous page that has not been refreshed with the latest state variables from the Store. I cannot seem to find an event or hook to trigger a global setState after landing on my destination page.

Is there an event listener like [pageshow](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow) that fires when a route has been navigated to? If not, I'd like to request that feature.

If not is there some other pattern that I can use to detect that my page has been navigated back to?

**Comment by gaearon** [comment]
Have you looked at [transition hooks](https://github.com/rackt/react-router/blob/master/docs/api/components/RouteHandler.md#willtransitiontotransition-params-query-callback)?

**Comment by pxwise** [comment]
Yes, I'm finally on the right track now with willTransitionTo. I hadn't uncovered these docs yet. These appear to do exactly what I need and more. Thanks @gaearon
