### ISSUE TITLE
Stop run()-ing once started?

### ISSUE THREAD

**Issue by josephsavona** [rackt/react-router#742]
Once the router is started with `Router.run(routes, callback)`, is it possible to stop it and unmount those routes? (eg, so a future `Router.run()` call does not use those old routes)

**Comment by gaearon** [comment]
```js
var router = Router.create({ routes: routes, location: Router.HistoryLocation });
router.run(callback);
...
router.stop();
```

**Comment by rpflorence** [comment]
Also, there's some trickery here where `<Handler/>` is actually the router instance too, so unmounting that component will stop the router.

```js
Router.run(routes, (Handler) => {
  React.render(<Handler/>, document.body);
});

// later
React.unmountComponentAtNode(document.body);
// router is torn down automatically
```
