### ISSUE TITLE
Too much stuff on `context`

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#744]
I wonder if we can remove some of it, we add a lot to it, making testing kind of a pain to stub out, if any of it can be removed I'd like to remove it (like, its just convenient for the router, but not useful for the consumer).

**Comment by mjackson** [comment]
Let's just have one single prop in context called `router`. Both the `Navigation` and `State` mixin just call stuff on the router object anyway. We could provide a very simple mixin with a `getRouter` method for people that are still using mixins. All others can access the router object on `this.context.router`.

**Comment by gaearon** [comment]
+1

**Comment by rpflorence** [comment]
ooh, lovely
