### ISSUE TITLE
<Link to={'misspelled-route'}>

### ISSUE THREAD

**Issue by ndreckshage** [rackt/react-router#745]
I was just changing a few routes names to constants. Misspelled one. Application didn't display. But no errors / exceptions in console. Took me a while to find the issue. Maybe just throw hard exception if Link to prop doesn't match a route name?

**Comment by rpflorence** [comment]
you sure? 

1. https://github.com/rackt/react-router/blob/master/modules/components/Link.js#L77
2. https://github.com/rackt/react-router/blob/master/modules/createRouter.js#L234
3. https://github.com/rackt/react-router/blob/master/modules/createRouter.js#L217-L221

Maybe you were giving it absolute paths. If so, we can't easily tell if its valid or not.

**Comment by ndreckshage** [comment]
Ill try and get an example / failing test up later. But ya I'm seeing this no matter what the path is. Ex: <Link to={'usser'}>Account</Link> which doesn't match <Route name={'user'} path={'/user'} handler={User} />. Seems to be failing silently + doesn't render anything.

**Comment by ndreckshage** [comment]
Hm I just stepped through and it is hitting invariant. But then thats swallowing it. Ill keep digging into it.

**Comment by ndreckshage** [comment]
Ah mystery solved. resolve routes in a promise, and wasnt catching error
