### ISSUE TITLE
Example: Async Data: cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by dok** [rackt/react-router#748]
Looks like an async issue, specifically with the promises.

![screen shot 2015-01-31 at 5 59 56 pm](https://cloud.githubusercontent.com/assets/1214868/5990702/35870932-a973-11e4-9365-3706782a068d.png)

**Comment by rpflorence** [comment]
works for me, are you on master and using `npm run examples` ?

**Comment by rpflorence** [comment]
just did a fresh clone of the repo and it also worked.

**Comment by gaearon** [comment]
Could be a bad connection issue where API returns you garbage for some reason?
