### ISSUE TITLE
How to call a callback defined in parent handler?

### ISSUE THREAD

**Issue by hezjing** [rackt/react-router#750]
Hi

May I know how to pass a callback defined in the parent handler to the child handlers?

In the following example I have a updateState(),
```
var App = React.createClass({
  updateState: function() {    
  },
});
```

How can  I pass updateState() into Inbox handler?
```
<Route name="app" path="/" handler={App}>
  <Route name="inbox" handler={Inbox}/>
  <DefaultRoute handler={Dashboard}/>
</Route>
```

**Comment by kilometers** [comment]
[Not an expert]

I've gotten away with passing callbacks into the `<RouteHandler />`'s props, so any child routes who occupy that spot will receive the callback. I'm curious if there's a better approach.

**Comment by gaearon** [comment]
>I've gotten away with passing callbacks into the `<RouteHandler />`'s props

That's how you do it, right. Pretty much the way you'd do without a router.
Closing out, let me know if there's some problem with this approach :-)

**Comment by hezjing** [comment]
Thanks and added the following code snippet to close this issue:
```
var App = React.createClass({
  updateState: function() {    
  },
  render: function() {
    return (
      <RouteHandler onStateChange={this.updateState}/>
    );
  }
});
```
It would be very helpful to mention this in the documentation too!
