### ISSUE TITLE
mobile safari triggers Router.run twice on initial page load

### ISSUE THREAD

**Issue by bmcmahen** [rackt/react-router#753]
I haven't had too much time to test this in other contexts, but within my app I've noticed that on the initial page load `Router.run` is triggered twice on the initial page load -- both times with the same state / route information. I haven't noticed this happening in any other browsers. As a quick fix, I've stored the current route information and done the relevant checks to determine if it has, indeed, changed.

**Comment by rpflorence** [comment]
interesting, let us know if you discover anything else.

**Comment by mjackson** [comment]
I think this is a WebKit bug. See

https://bugs.webkit.org/show_bug.cgi?id=93506
https://bugs.webkit.org/show_bug.cgi?id=80697

@bmcmahen Are you using `HistoryLocation` by any chance? That bug is specific to using the HTML5 history API.

Also, [Twitter worked around this bug by ignoring `popstate` events when the `state` property is `undefined`](https://blog.twitter.com/2012/implementing-pushstate-for-twittercom).

**Comment by bmcmahen** [comment]
Yep, I was using `HistoryLocation`. I haven't been able to explore the issue all that much more, but I have only encountered it while using mobile safari with `HistoryLocation`.

**Comment by mjackson** [comment]
@bmcmahen Thanks for confirming. I'm just going to assume we're running into the same bug that Twitter was for now. Please let us know if you still see this behavior when using 3d8a883.

**Comment by dlindenkreuz** [comment]
Still getting onPopState event on initial page load with Safari 8.0.6.

Check should be changed from `if (event.state === undefined)` to `if (event.state === null)`. Apparently, the `state` property is never `undefined`.

**Comment by ryanzec** [comment]
I think this needs to be re-opened as I am still seeing this issue.  Following @dlindenkreuz suggestion, I changes that if to:

```javascript
if (event.state === undefined || event.state === null) {
 return;
}
```

and it seems to work in safari after that.
