### ISSUE TITLE
Ability to have a duplicate route with different params

### ISSUE THREAD

**Issue by defrex** [rackt/react-router#758]
When building faceted navigations, it's often the case that you have multiple URLs for the same handler. For example:

    /items
    /items/us
    /items/us/ny
    /items/us/ny/nyc

These URLS would all point to an `Items` handler, just with different params. Currently, the best way to implement this seems to be to name these routes separately. Something like this:

    var routes = (
      <Route name="items" handler={Items} path="/items">
        <Route name="items-country" handler={Items} path=":country">
          <Route name="items-state" handler={Items} path=":state">
            <Route name="items-city" handler={Items} path=":city"/>
          </Route>
        </Route>
      </Route>
    );

The problem with this is that you need to know which facets you are pointing to when creating a `Link`. In this example it might not be that bad, but this type of navigation can get quite complex.

    {params.country && !params.state && !params.city ? (
      <Link to="items-country" params={params}/>
    ) : ''}
    {params.country && params.state && params.city ? (
      <Link to="items-city" params={params}/>
    ) : ''}

Ideally, I'd like to define these routes like so (or a nested version of the same):

    var routes = (
      <Route name="items" handler={Items} path="/items">
        <Route path=":country"/>
        <Route path=":country/:state"/>
        <Route path=":country/:state/:city"/>
      </Route>
    );

And then let `Link` determine the path structure based on the params.

    <Link to="items" params={{country: 'us'}}/> {/* => /items/us */}
    <Link to="items" params={{country: 'us', state: 'ny', city: 'nyc'}}/> {/* => /items/us/ny/nyc */}
    
This would allow much more flexibly generating this kind of navigation.

What do you think?

**Comment by rpflorence** [comment]
If you don't want the nesting, you can do optional params:

`<Route path=":country?/:state?/:city?"/>`

**Comment by defrex** [comment]
Hm, yes, that might work. My actual situation is a little more complex then the example I gave though. I'll give that strategy a shot and let you know how it goes.

**Comment by defrex** [comment]
Okay, so in the example you gave, you would end up with extra `/`s when you leave out the arguments if using `Link`. To make things more complex, in my case, I need to match a pattern like:

    /items/
    /items/in-:city/
    /items/:tag/
    /items/in-:city/:tag/

What I might do it make everything optional (`in-` and all the `/`s), and then write a customer version on `Link` that will generate the correct URLs for me.

**Comment by defrex** [comment]
I ended up making a custom `Link` to centralize the cases.

    const ItemsLink = React.createClass({
      render() {
        var linkProps = this.props;

        if (params.country && !params.state && !params.city)
          linkProps.to = 'items-country'
        else if (params.country && params.state && !params.city)
          linkProps.to = 'items-state'
        else if (params.country && params.state && params.city)
          linkProps.to = 'items-city'
        else
          linkProps.to = 'items'

        return (
          <Link {...linkProps}>{this.props.children}</Link>
        );
      }
    });

Not ideal, but it'll get the job done.

**Comment by rpflorence** [comment]
Love how composable components are :)

If you think of anything we could do that can solve this problem in a more generic way, please let us know.
