### ISSUE TITLE
Transition hooks for goBack?

### ISSUE THREAD

**Issue by plasticine** [rackt/react-router#761]
Hey there,

There seems like there is a bit of an inconsistency in the sourcecode commentary around `goBack` — it seems to indicate that transition hooks are applicable there, however the implementation is merely doing a `location.pop`.

It seems like there could be a reasonable use-case for allowing hooks for transitioning via `goBack` (iOS style stateful preference forms/views).

<3 react-router btw — thanks!

**Comment by plasticine** [comment]
@rpflorence would this be something you would consider a PR for?

**Comment by gaearon** [comment]
IMO there shouldn't be a difference between calling `goBack()` programmatically and pressing Back, so calling `location.pop()` makes sense.

Don't transition hooks run for you? `location.pop()` should go into router's change handler, and call transition hooks from there.

**Comment by plasticine** [comment]
> IMO there shouldn't be a difference between calling goBack() programmatically and pressing Back, so calling location.pop() makes sense.

Yeah, I agree — however it seems useful to be able to hook into this route change if possible.

> Don't transition hooks run for you? location.pop() should cause a pop event, go into router's change handler, and call transition hooks from there.

No— transition hooks never run when using `location.pop`.

**Comment by plasticine** [comment]
Apologies — user error.

My handler component is being wrapped in a loader component that is handling webpack bundle loading.

**Comment by rpflorence** [comment]
keep an eye on #755 :wink:

**Comment by mbrio** [comment]
I know this was closed about a month ago but is there a way to determine if a transition hook was called from goBack? My hooks are being called, but it would be immensely useful to know whether the transition was actually initiated from goBack. An example would be in an animated environment where there are transitions from one component to another, going forward may have a different transition from going backward.

**Comment by gaearon** [comment]
@mbrio One thing I can say is `'pop'` would be in `state.action` in `Router.run` callback, but there's no way for us to determine whether it was caused by Back or Forward, for example (browsers just don't tell).

**Comment by mbrio** [comment]
Is it possible to check if the previous length of history was greater than it is now? Would this not indicate a popping? or could the entire history have been replaced?

**Comment by mbrio** [comment]
@gaearon I looked into the option you described above, is there any way of determining the handler's component definition at the point of that callback in order to access it's `.statics` property? I tried a number of things but couldn't seem to get at the definition from `Router.run` `Handler` or `state` arguments.

**Comment by gaearon** [comment]
Something like `state.routes[i].handler` where each route corresponds to a nesting level.
