### ISSUE TITLE
can't make auth-flow example work with HistoryLocation

### ISSUE THREAD

**Issue by sardaukar** [rackt/react-router#764]
Hello!

I have replicated the auth-flow example codebase, with two differences: no more About page, and going to "/" and "/login" when logged in redirects to "/dashboard". 

It all works with normal fragment URIs, but using Router.HistoryLocation breaks it. The redirects still changes the browser address bar, but the dashboard component is not rendered, but instead the component matching the address before the redirect (ie, going to "/" renders the home component, but the browser URL says "/dashboard").

The code change that breaks it is changing this:
```javascript
Router.run(routes, function (Handler) {
  React.render(<Handler />, document.body);
});
```

to this: 
```javascript
Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(<Handler />, document.body);
});
```
as stated on the docs.

I have a repo up with the code https://github.com/sardaukar/auth-flow-example

Thanks for any help.

**Comment by gaearon** [comment]
You don't need to call `replaceWith` inside `componentWillMount`, as router supports [transition hooks](https://github.com/rackt/react-router/blob/master/docs/api/components/RouteHandler.md#static-lifecycle-methods).

In your example, that would be

```js
statics: {
    willTransitionTo: function (transition) {
      if ( auth.loggedIn() ) {
        transition.redirect('/dashboard');
      }
    }
}
```

**Comment by sardaukar** [comment]
I commited a change to the repo https://github.com/sardaukar/auth-flow-example/commit/79bfbdde44a36b864521fa12a47a56b786064ba8 but not I get infinite recursion :/

**Comment by gaearon** [comment]
>I commited a change to the repo sardaukar/auth-flow-example@79bfbdd but not I get infinite recursion :/

You don't need this on `App`, I believe. Dashboard is a subroute of App, so that's why you're recursing.

Regardless of this, I agree there is an issue related to state here. Calling `replaceWith` from within `componentWillMount` makes router do strange things.

**Comment by sardaukar** [comment]
Ok, removing it from App fixes it, and /login redirects (and renders) Dashboard properly. So what is the proper way in this example to make "/" redirect to Dashboard when logged in?

**Comment by gaearon** [comment]
I'd just add `<Redirect from='/' to='dashboard' />`:

```js
  <Route handler={App}>
    <Route name="login" handler={Login}/>
    <Route name="logout" handler={Logout}/>
    <Route name="dashboard" handler={Dashboard}/>
    <Redirect from='/' to='dashboard' />
  </Route>
```

**Comment by sardaukar** [comment]
Cool! Thanks for the help!

**Comment by gaearon** [comment]
I suggest we keep this issue open for now because there seems to be a bug when `replaceWith` is called from `componentWillMount`. At least I want to figure out why that happens.

**Comment by sardaukar** [comment]
Actually, the Redirect doesn't do what I'm trying to do. It should only go to /dashboard from / when logged in...

**Comment by gaearon** [comment]
When not logged in, it will immediately redirect to login (dashboard will do that). Isn't this what you wanted?

**Comment by sardaukar** [comment]
Not really. So, if not logged in, App renders normally. But if loggedin, the user's "homepage" becomes the dashboard.

**Comment by gaearon** [comment]
Then, instead of redirect, define a default route for / path and have willTransitionTo there refirect to dashboard if logged in.

**Comment by sardaukar** [comment]
OK, got it! https://github.com/sardaukar/auth-flow-example/commit/8bbb3b047f4ffd5ddabf3fd37653d03f1a2e0761 thanks for your help!
