### ISSUE TITLE
Advanced navigation patterns

### ISSUE THREAD

**Issue by taurose** [rackt/react-router#767]
I think it would be great to offer some advanced navigation functionality such as:

* `canGoBack()`
* `canGo(n) `
* `go(n)` // n positive or negative, like with history.go(n)
* `canGoBackTo(name, params, query)`
* `goBackTo(name, params, query)` // goes back to when the route was last active
* `state.historyId` // e.g. for caching stuff based on current history entry like form data, or choosing animations by comparing to previous state

This could also be very useful for implementing [up navigation in Android](https://developer.android.com/training/implementing-navigation/ancestral.html).

While this seems trivial to implement for in memory locations (for react-native), in my opionion it would also be great to have this for web apps. I've actually played around with this in the past, and I think it might actually be possible to make this happen for `HistoryLocation` by managing a counter within the history state object. I don't think it's possible with `HashLocation` or `RefreshLocation` though. 

Implementation-wise there's also the problem of how to provide persistency (hitting refresh button, closing browser), but I first wanted to hear what you think about this API.

On a related note, the current `goBack()` doesn't play well when using browser navigation. With this kind of approach, it should be possible to make it work reliably.

Related #765

**Comment by natew** [comment]
Using the [RouteHandler mixin](https://github.com/rackt/react-router/blob/master/modules/RouteHandlerMixin.js#L37) you have some ability to implement a few of these functions. I started working on some similar stuff here: https://github.com/reapp/reapp-platform/blob/master/src/mixins/RoutedViewListMixin.js

I agree, the more logic we can put into the navigation mixin, the better. Just need the community to come up with some pull requests.

**Comment by stefanfisk** [comment]
@natew your link is dead :(

**Comment by natew** [comment]
@stefanfisk 

More permanent link: https://github.com/reapp/reapp-routes/blob/838fc33bb672b9d7cc3914e32d05c6c240324eba/react-router/RoutedViewListMixin.js#L1

**Comment by ryanflorence** [comment]
@taurose let me know if we need to reopen this

**Comment by dipdipdip84** [comment]
Could you please reopen it ? History.go() and History.state needed ! Is it something that is planed ?
