### ISSUE TITLE
how to <Link> to a nested route?

### ISSUE THREAD

**Issue by tjwebb** [rackt/react-router#772]
```
<Route name='a'>
  <Route name='b' />
</Route>
```

I want to `<Link to='a/b'>` but that doesn't work. `to='b'` doesn't work either. I get `Unable to find <Route name="b">`. What am I missing?

**Comment by tjwebb** [comment]
I realized I can't use a nested route under a `DefaultRoute`. So then how do I have a default route?

**Comment by ryanflorence** [comment]
Are you trying to redirect? DefaultRoute matches its parent's path, so it
becomes the RouteHandler in the parent's render.

**Comment by salper** [comment]
Let's say we have the following configuration :
```javascript
<Route name="app" handler={App}>
  <Route name="user" handler={User}>
    <Route name="profile" handler={Profile}/>
  </Route>
<Route>
```
How can we provide a default route from ```/```to ```/user/profile```?

**Comment by gaearon** [comment]
@salper Does `<Redirect from='/' to='/user/profile' />` help? I'm not sure if it's idiomatic way of doing that though.

**Comment by salper** [comment]
@gaearon Well, that was the main (hidden) question. I wanted to know if there was a way to do so using DefaultRoute component. I'll go with the Redirect one til something idiomatic comes up. Thx.

**Comment by taurose** [comment]
To me it sounds like redirection is exactly what you're looking for.

> How can we provide a default route from /to /user/profile?

The way I see it, DefaultRoute is not meant to affect your URLs in any way, or allow you to show the same content for different urls, but to give your parent routes a default RouteHandler in case they match the url exactly. A bit like index.html on webservers.

If you really wanted to use the same handlers for `/` and `/user/profile`, I think you could simply use routes with `path="/"`:

```js
<Route name="app" path="/" handler={App}>
  <Route name="user-index" path="/" handler={User}>
    <Route name="profile-index" path="/" handler={Profile} />
  </Route>
  <Route name="user" handler={User}>
    <Route name="profile" handler={Profile} />
  </Route>
<Route>
```

**Comment by salper** [comment]
That sounds pretty well to me, thx.
