### ISSUE TITLE
Request for update to auth-flow example

### ISSUE THREAD

**Issue by uberllama** [rackt/react-router#776]
First off, thanks for putting this example together. It's a good start, but doesn't handle the typical scenario of async loading a "current user" from an endpoint on login/mount. A great addition would be to fire an async request on mount if a local storage token is present, instead of ending with the retrieval of the token. Cheers.

**Comment by ryanflorence** [comment]
You would get the token, and the user data here: https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L137-L146, could then store the user just like the token.

**Comment by uberllama** [comment]
That's not the issue. The issue is that the example as it stands is basing login-state-on-mount off of a synchronous lookup for the access token in local storage, whereas the realistic approach is that you would then send that access token to ensure its still valid and to receive your current user. So this would be an asynchronous process, with potentially weird UI ramifications if the API request takes a second and you've navigated to the login page or whathaveyou in the interim. The lookup almost needs to be blocking.

**Comment by ryanflorence** [comment]
`willTransitionTo` can be asynchronous and blocking:

https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L42-L47

On the latest release you do it like this:

```js
willTransitionTo(transition) () {
  transition.wait(somePromise());
}
```

on master you use the callback

```js
willTransitionTo(transition, params, query, callback) () {
  asyncStuff(callback);
}
```

**Comment by uberllama** [comment]
Cool, will give it a shot Thanks Ryan.
