### ISSUE TITLE
<Link> hash path in NodeJS

### ISSUE THREAD

**Issue by trungpham** [rackt/react-router#779]
How can I get the Link component to generate href with `#` when rendering on the server?

https://github.com/rackt/react-router/blob/10359a50cc6df934a10dea581a8ac81eeff68efd/modules/createRouter.js#L235
The code seems to be checking for HashLocation, which is not available in Node.

Thanks.

**Comment by ryanflorence** [comment]
#hashlinks

**Comment by ryanflorence** [comment]
On the server you need to give the router a path.

```js
Router.run(routes, req.path, callback)`
```

The links won't have hash the `#` in them.

http://jsbin.com/duyaxa/6/edit

**Comment by trungpham** [comment]
But I want the link generated on the server to start with #.

**Comment by ryanflorence** [comment]
If you have server rendering, use `HistoryLocation` in the client. Why would you want to use hashes?

**Comment by trungpham** [comment]
I use HashLocarion on th client.
