### ISSUE TITLE
simplified syntax?

### ISSUE THREAD

**Issue by Pomax** [rackt/react-router#784]
While the XML syntax is no doubt nice, it's actually getting in the way of reading what react-router is doing for me, more often than not. Much as React offers JSX vs. plain JS, is there an option to use "plain js" for react-router without all the decoration?

For instance, given the example code
```
var routes = (
  <Route handler={App} path="/">
    <DefaultRoute handler={Home} />
    <Route name="about" handler={About} />
    <Route name="users" handler={Users}>
      <Route name="recent-users" path="recent" handler={RecentUsers} />
      <Route name="user" path="/user/:userId" handler={User} />
      <NotFoundRoute handler={UserRouteNotFound}/>
    </Route>
    <NotFoundRoute handler={NotFound}/>
    <Redirect from="company" to="about" />
  </Route>
);
```

Is there something available for us to use this instead?

```
var router = {
  name: "root"
  handler: this.App,
  notFound: this.NotFound,
  path: "/",
  default: { handler: this.home },
  redirect: {
    from: "company",
    to: "about"
  },
  routes: [{
    name: "about",
    handler: this.about
  },{
    name: "users",
    handler: this.users,
    notFound: this.UserRouteNotFound,
    routes: [{
      name: "recent-users",
      path: "recent",
      handler: this.RecentUsers
    },{
      name: "user",
      path: "/user/:userId",
      handler: this.User
    }]
  }]
};
```
mostly, this makes assembling routing much easier because the total sum of routes can be modularized, and simply assembled when needed, a la:

```
var router = {
  name: "root"
  handler: this.App,
  path: "/",
  routes: [
    require("routing/about"),
    require("routing/users")
  ]
};
_.extend(router, require("routing/defaults"));
```

**Comment by ryanflorence** [comment]
```js
var routes = (
  <Route handler={App}>
    {require("./routing/about")}
    {require("./routing/users")}
    {require("./routing/defaults")}
  </Route>
);
```

yes? no? maybe?

**Comment by manpages** [comment]
What OP proposes is achievable with a library (for instance, when I was getting acquainted with React, I wrote a lispy way to compose elements).
There is no need to put this feature in r-r.

Besides, last time I checked, route modularization is considered to be a bad practice in r-r philosophy.

**Comment by Pomax** [comment]
on the other hand, require() in React itself is considered extremely good practice. Not sure why you'd say "it's not good for r-r" when it's one of the more powerful bits of React itself...

**Comment by ryanflorence** [comment]
I'm confused. didn't I just show how you can build up your routes with `require` inside?

Personally, I like big giant route configs. No reason to make your team jump across files to see which routes your app responds to, but you can do whatchoowant :)

**Comment by ryanflorence** [comment]
Also, we are planning on a non-jsx-and-very-friendly way to configure your routes, so stay tuned.

**Comment by Pomax** [comment]
sorry, the top comment was in response to manpages's note on require being bad practice in r-r -- I like modular routes as an option, since some of the projects we work on (mozilla foundation) are pretty stable and the routes are likely to never change, but some apps/sites have routes that get shuffled around surprisingly often, and being able to update those local to the bits being shuffled around becomes important, so it's great to see both are possible!

**Comment by manpages** [comment]
@Pomax please take my initial commentary with a grain of salt!

I also found out that the best practice for huge projects is for teams to write their code in separately-tested and maintained projects and having app integration project that composes functionality and routes.

We're composing routes in the way similar to the one proposed by @ryanflorence; 

Re: announcement of "non-JSX way" of composing routes. It'd be nice to have an officially supported DSL for this as a library, but putting it into the core project seems unreasonable.

**Comment by gnapse** [comment]
I actually think it's reasonable to provide a non-JSX way of expressing routes, so it's great to know that's on the roadmap @ryanflorence. And I think it's something this library should provide baked-in, not through yet another library on top of it.

I like react-router a lot, but never understood why using JSX/XML for expressing the routes, when a JSON-like syntax can do a better job. Doesn't XML vs JSON ring a bell?
