### ISSUE TITLE
App doesn't load unless root domain visited first.

### ISSUE THREAD

**Issue by fredguest** [rackt/react-router#785]
When visiting '/' the app loads, and then navigating to any other path such as '/about' loads that component, so everything behaves as expected, but if the initial page visited is anything other than '/', for example if you open a window and visit '/about' directly, the application doesn't load it's just a blank page. I assume this is misconfiguration on my part, but I can't find the relevant part of the docs. here is my routes.jsx file:
```javascript
var App = require('../components/App.jsx');
var BlabView = require('../components/BlabView.jsx');
var AboutView = require('../components/AboutView.jsx');
var AccountView = require('../components/AccountView.jsx');
var DefaultRoute = ReactRouter.DefaultRoute;
var Route = ReactRouter.Route;

module.exports = (
  <Route name="app" path="/" handler={App}>
    <DefaultRoute name="blabs" handler={BlabView} />
    <Route name="account" handler={AccountView} />
    <Route name="about" handler={AboutView} />
  </Route>
);
```

here is the full codebase: https://github.com/fredguest/blabber

and here is a live demo: https://blabs.herokuapp.com

**Comment by taurose** [comment]
Your server returns a blank page and 404 for those paths, so your app and react-router aren't even started. You need to set it up to send index.html for unmatched requests, or integrate react-router server-side to do pre-rendering and send appropriate status codes, but that's a bit more involved.

**Comment by fredguest** [comment]
yes! that makes lots of sense. actually i think i can set rails up to respond with index.html for any request that's not content-type json, which is exactly how it should behave otherwise you could visit the data endpoints and just get json dumped in your browser. still adjusting my mental model to a json only server :/ thanks for the quick help!

**Comment by ryanflorence** [comment]
yep, if you're using `HistoryLocation` you need to configure your server. Until you want to tackle that, use `HashLocation`. You can just flip the switch to `HistoryLocation` w/o changing anything else in your react app.

**Comment by fredguest** [comment]
ok cool, good to know there's a quick fix thanks Ryan. i've read a bunch of things like this http://danwebb.net/2011/5/28/it-is-about-the-hashbangs and this http://ngriffith.com/2012/02/20/hash-banging-the-intertubes (Dan Webb is the engineer at Twitter that was charged with re-writing their url scheme to remove hashes) that have left me strongly inclined to go with pushState. i'm almost home on a server configuration that solves the issue while maintaining pushState.

**Comment by fredguest** [comment]
bingo! works now -> http://blabs.herokuapp.com/account

the key changes were locking down the data endpoints to json formated requests only and adding a catch-all route as the last line of the routes file:
```ruby
Rails.application.routes.draw do
  match '*all', to: 'application#preflight', via: [:options]
  scope format: true, constraints: { format: :json } do
    resources :blabs, except: [:new, :edit]
  end
  match '*all', to: 'application#index', via: [:get]
end
```
adding a viewless action for the catch-all route:
```ruby
class ApplicationController < ActionController::API
  def index
    render file: 'public/index.html' and return
  end
end
```
and specifying a content-type in all API requests:
```javascript
var Endpoint = '/blabs.json';

module.exports = React.createClass({
  getBlabsFromAPI: function() {
    reqwest({
      type: 'json',
      method: 'get',
      contentType: 'application/json',
      url: this.props.host + Endpoint,
      success: function (data) {
        this.setState({data: data});
      }.bind(this),
      error: function (err) {
        console.error(this.props.host + Endpoint, status, err.toString());
      }.bind(this)
    });
  },
  render: function() {
    ...
  }
});
```

**Comment by schickling** [comment]
@ryanflorence what exactly do you mean by "you need to configure your server"?

**Comment by fredguest** [comment]
@schickling i wrote up an example that is specific to a Rails server but it may clarify what Ryan was talking about and point you in the right direction. the write up is here: http://fredguest.com/2015/03/06/building-a-stateless-rails-api-with-react-and-twitter-oauth/ and scroll all the way down the the section called "Loading React Outside of the Root Path".

**Comment by schickling** [comment]
Thanks! My problem was that I missed trailing slashes at the end of each route.

**Comment by fredguest** [comment]
oh nice! glad you got it sorted.
