### ISSUE TITLE
RequireJS compatibility

### ISSUE THREAD

**Issue by kirill-konshin** [rackt/react-router#787]
The line
```js
var React = (typeof window !== "undefined" ? window.React : typeof global !== "undefined" ? global.React : null);
```

kills the benefits of using RequireJS. I had to create a proxy AMD module where I first load React, then make it global, then load the rest of application, ugly as hell:

```js
require(['react'], function(React) {
    window.React = React;
    require(['jsx!./js/app.jsx'], function() {});
});
```

You can use UMD wrap to ensure that module will feel OK in any environment: CommonJS, AMD, pure browser.

It is as easy as
```js
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports', 'b'], function (exports, b) {
            factory((root.commonJsStrictGlobal = exports), b);
        });
    } else if (typeof exports === 'object') {
        // CommonJS
        factory(exports, require('b'));
    } else {
        // Browser globals
        factory((root.commonJsStrictGlobal = {}), root.b);
    }
}(this, function (exports, b) {
    //use b in some fashion.

    // attach properties to the exports object to define
    // the exported module properties.
    exports.action = function () {};
}));
```

See https://github.com/umdjs/umd/blob/master/commonjsStrictGlobal.js

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/issues/171#issuecomment-59872520

**Comment by ryanflorence** [comment]
That would work fine for React, but not for our other dependency, `qs`. In order to barf UMD at the top of a lib, all your deps must too, but they don't, so we don't.

**Comment by ryanflorence** [comment]
additionally, all of our modules would need that UMD garbage up top as well.

**Comment by kirill-konshin** [comment]
All you need to do is add "UMD garbage" around your build only once.

Shuld look like this:

```js
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(['exports', 'react'], function (exports, React) {
            factory((root.ReactRouter = exports), React);
        });
    } else if (typeof exports === 'object') {
        factory(exports, require('react'));
    } else {
        factory((root.ReactRouter = {}), root.React);
    }
}(this, function (exports, React) {
    // the rest of your existing unmodified codebase
}));
```

And this is it!

**Comment by kirill-konshin** [comment]
Since you're using `webpack` its even easier, try to patch your config:

```js
  output: {
    library: 'ReactRouter',
    libraryTarget: 'umd'
  },

  externals: {
    react: 'react'
  },
```

**Comment by kirill-konshin** [comment]
QS by the way is packed too, so it's not a problem.

**Comment by ryanflorence** [comment]
If you can make it work, send a pull request.

**Comment by ryanflorence** [comment]
You're right, yet again webpack proves to have solved every module woe in the world.

```js
var webpack = require('webpack');

module.exports = {

  output: {
    library: 'MyLib',
    libraryTarget: 'umd'
  },

  externals: {
    react: 'React'
  },

  node: {
    Buffer: false
  }
};
```

Outputs a file with `qs` embedded but react required externally with my old friend UMD.

Feel free to send the pull request for this, or wait for me to do it, got a daddy daughter dance tonight, but sometime next week I'll get around to it.

**Comment by kirill-konshin** [comment]
Next week sound OK to me. In the mean time I'll investigate what I can do regarding pull request.

**Comment by kirill-konshin** [comment]
Here is working config:

```js
    output: {
        library: 'ReactRouter',
        libraryTarget: 'umd'
    },

    externals: [
        {
            "react": {
                root: "React",
                commonjs2: "react",
                commonjs: "react",
                amd: "react"
            }
        }
    ],
```

Externals should be configured this way to have `require('react')` for CJS/AMD (lowecase) but use `window.React` (capital R).

**Comment by kirill-konshin** [comment]
I've created a PR.
