### ISSUE TITLE
Dom diff on dynamic segment change is problematic

### ISSUE THREAD

**Issue by uberllama** [rackt/react-router#793]
I've been having a world of trouble maintaining correct state after modifying the dynamic segment of a component that has children with state. A good example is an edit page `posts/123/edit` which renders `Post`, which in turn renders `PostForm`. The problem arrises from the nested components not mounting as per usual when the dynamic segment is changed on the URL, and instead relying on `componentWillReceiveProps` at the parent level. This results in the parent component content changing but not its children, when changing the address to `posts/124/edit`.

I could be doing something horribly wrong, but as far as I know I'm not engaging in any bizarro component composition patterns. Would it be possible to provide a global off switch for this that can be passed to `Router.run` that would perform a normal transition?

Thanks.

**Comment by gaearon** [comment]
What kind of issue do you have? You can give explicit `key` to child stateful component, based on current props. Or you can implement `componentWillReceiveProps` in child components and reset state there when post ID changes.

**Comment by uberllama** [comment]
I am using keys but the problem persists. I'll try to get an example up this afternoon, baby naps willing. :) But your comment on implementing `componentWillReceiveProps` on child components is a good one, because I feel that's where another issue with this implementation lies: every component has to do double duty on setting up state depending on how it was mounted, normally or via a segment change. I wonder if the optimization is worth it, and that's why I'd like to be able to disable it altogether.

**Comment by gaearon** [comment]
You can add key to `RouteHandler` in root route handler. See example here: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md (find "addHandlerKey" on page).

**Comment by uberllama** [comment]
The other thing I'll point out is that the behaviour is inconsistent on some of my pages. For several URL changes in the edit example, the form component will re-render correctly, then it'll just stop.

**Comment by gaearon** [comment]
It's hard to say what the issue is without playing with your code. Can you reproduce it on RR examples in the repo?

**Comment by uberllama** [comment]
Will attempt to do so later this aft. In the interim, your suggestion worked! Everything just mounts now. Is this a sanctioned technique? I ask because I didn't see it anywhere in the doc or API. Cheers.

**Comment by gaearon** [comment]
The link above is from the docs (Upgrade Guide, to be specific).

**Comment by uberllama** [comment]
Cool, I'll submit a PR to add it to the overview doc where it talks about dynamic segments.

**Comment by gaearon** [comment]
Please do. Thanks!

**Comment by uberllama** [comment]
PR submitted. I'll still submit an example for the original issue.

**Comment by uberllama** [comment]
Okay here's the gist: https://gist.github.com/uberllama/7226f8e0ea3800a1f517

Try navigating between edit pages by changing the id in the address bar (1,2, or 3). You will see that the post title changes, but the form state does not. There's nothing out of the react norm here as far as state handling goes.

**Comment by gaearon** [comment]
I think the problem is your `Input` retaining state. It only reads `props.value` once, at the time of the mount, but disregards any changes to it and uses its own local state instead.

Adding

```js
        componentWillReceiveProps: function(nextProps) {
          if (nextProps.value !== this.state.value) {
            this.setState({ value: this.props.value })
          }
        },
```

to `Input` helps but it's more of a workaround. Instead, you should remove local state from `Input`, add `onChange` to it and update `post` in parent component, so new data flows down to the input. This way, when `post` is replaced by another post, data will also flow down.

**Comment by gaearon** [comment]
I'll close this out but feel free to reopen if I missed something.

**Comment by uberllama** [comment]
Again though, I don't think this is a realistic proposition (no pun intended). You're saying that in order to use react-router in its default behaviour, every component must act on `componentWillReceiveProps` for state handling, in the event that its included by another component that's subject to dynamic segment switching.

**Comment by uberllama** [comment]
Further to my last comment, I would argue that the safer default option for react-router would be to re-mount by default, and allow opting into dom diffing when a dynamic segment changes. This would mean less code overhead and tricky bugs.

**Comment by uberllama** [comment]
cc @ryanflorence @mjackson

**Comment by gaearon** [comment]
Let's reopen this and wait for owners to say their word! On one hand, I agree it can sometimes be problematic, on the other hand, I don't feel that router should behave differently than other React components by default.

**Comment by uberllama** [comment]
Thanks Dan, I certainly don't want to be pushy. :) Just presenting my experiences.

**Comment by uberllama** [comment]
After further reflection, I'm going to close this myself. :)

**Comment by gaearon** [comment]
You probably realized this already but blowing the state away can be just as unexpected as keeping it. For example, you don't want to re-mount a seach page on each keypress. Same goes for tabbed pages.
