### ISSUE TITLE
Pass props to handler component

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#799]
I just ran into a situation where I'd want to reuse a handler component in two or more routes. But to be able to do this I need to pass props in order to change its behavior between both locations.
```
<Route name="one" handler={SameComponent}/>
<Route name="two" handler={SameComponent}/>
```
Can I pass properties to SameComponent?

**Comment by insin** [comment]
Not since 0.11.x - the upgrade guide has some examples of ways to do this: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#route-props-passed-to-handlers

I've used something like this before where the route handler also had other props passed to it when rendered:

```javascript
function sameHandler(type) {
  return React.createClass({
    render() {
      return <SameComponent {...this.props} type={type}/>
    }
  })
}
```
```
<Route name="one" handler={sameHandler('foo')}/>
<Route name="two" handler={sameHandler('bar')}/>

**Comment by 0x80** [comment]
Hey it's my friend from SO :smile: 

Thanks for the info. Although I think I prefer the 0.10 approach. O well.

I don't understand how using static properties in the second 0.11 suggestion from the upgrade guide is anything like reusing a component. That seems a bit silly to even mention.
