### ISSUE TITLE
When query value starts with #, router doesn't recognize it

### ISSUE THREAD

**Issue by gaearon** [rackt/react-router#804]
I'm doing `this.replaceWith('search', {}, { q: '#test2' })`. In this case `q` is just a string user types into an input field. It's a search field, and user may want to find something by a hashtag.

In this case router will simply ignore this query parameter as if it never was there. I'd expect it to be encoded and correctly returned in `state.query` later.

`qs.stringify` encodes it, but [`decodeURIComponent` decodes it back](https://github.com/rackt/react-router/blob/master/modules/utils/Path.js#L136) and so it is passed verbatim to the location that assumes it's a hash.

Should we just manually encode `#` in a query? cc @mjackson who knows that logic

**Comment by gaearon** [comment]
In fact it seems that replacing `decodeURIComponent` with `decodeURI` [on this line](https://github.com/rackt/react-router/blob/master/modules/utils/Path.js#L136) solves the issue.

This also fixed subtle breakage caused by entering something like `&q=lalala` in search field (which causes `state.query.q` to become an array).

**Comment by gaearon** [comment]
Another failing case: if I call `replaceWith` with `a+b` in one of the query parameters, it will come back as `a b` to me.

**Comment by gaearon** [comment]
My proposed fix is https://github.com/rackt/react-router/pull/805 along with previously failing tests.
Does this make sense?

**Comment by gaearon** [comment]
Actually all I did to get it working was removing `decodeURIComponent` call: 42ddc23d5671403d48ed64e4dd85460af3105a5c.

When @mjackson is back, I hope he can shine some light on why he added it.

**Comment by mjackson** [comment]
@gaearon I'm looking at this right now. Time to get rid of this bug :)
