### ISSUE TITLE
Wanted to share react-router-proxy-loader with you

### ISSUE THREAD

**Issue by seanadkinson** [rackt/react-router#806]
Wasn't sure the best place to put this, but I just published this loader I've been using for awhile on my own projects, and it might be something you guys would like to know about, or perhaps put in the docs.

Called it `react-router-proxy-loader`, based entirely off `react-proxy-loader`, but adapted for `react-router`.  Here is the link: https://github.com/odysseyscience/react-router-proxy-loader

Makes it so you can dynamically load routes only when they are about to be rendered, utilizing `willTransitionTo` and `require.ensure` to resolve the bundle.  Usage like this:

```js
<Route name="user" handler={require('react-router-proxy!./User.jsx')} />
```

**Comment by browniefed** [comment]
:+1:

**Comment by gaearon** [comment]
That's cool. Make to later update it for the master which uses callbacks instead of `transition.wait`.

**Comment by seanadkinson** [comment]
@gaearon Done, published `react-router-proxy-loader@0.2` which depends on `react-router@0.12`.  Upgraded to use the callback pattern, which was nice since it removed my dependency on `bluebird`.

**Comment by gaearon** [comment]
:+1:

**Comment by mjackson** [comment]
@seanadkinson cool stuff :) Let's put it under ["Related Modules"](https://github.com/rackt/react-router#related-modules) in the README and close this issue. Thanks for sharing!

**Comment by gaearon** [comment]
Done via 1a3d702dbdf4b95a7750ba606fdc676286f3d471.
Thanks!
