### ISSUE TITLE
Redirect is included in childRoutes

### ISSUE THREAD

**Issue by Lars-Andersen** [rackt/react-router#808]
The goal is to dynamically display a progress bar indicating how many steps are edit/.

From what i can see theres no other way of doing this, other than grabbing childRoutes and filtering out those without a name.

Is there a need for Redirect to be included in the childRoutes?

Example:
```
<Route handler={App}>
	<Route name="items" path="/items" handler={list}></Route>
	<Route name="edit" path="/items/edit/:itemid?" handler={edit}>
		<Route name="title" path="title" handler={require(title)}/>
		<Route name="description" path="description" handler={description}/>
		<Route name="file" path="file" handler={file}/>

		<Redirect from="/items/edit/:itemid" to="/items/edit/:itemid/title" />
	</Route>
</Route>
```
Edit handler
```javascript
getInitialState: function() {
	var _this = this,
		n = 0,
		children = _.findWhere(this.getRoutes(), {name: 'edit'}).childRoutes;

	children = _.filter(children, function(child, i) {
		if(child.name && _this.isActive(child.name)){
			n = i;
		}
		return child.name;
	});

	children = _.pluck(children, 'name');

	return {
		progress: n,
		steps: children
	}
}
```

**Comment by gaearon** [comment]
I don't think depending on route order is a good idea. Somebody can come and rearrange them in `routes.js` without realizing they are being enumerated.

Why not make step a parameter and keep one route?

**Comment by Lars-Andersen** [comment]
I just like the idea that adding a new route inside edit automatically makes it part of the edit steps.
It might be a bad design choice - it doesn't really matter.

The real question remains - should redirects be in childRoutes?

**Comment by mjackson** [comment]
@Lars-Andersen Yes, `<Redirect>` needs to be included in the `childRoutes` array because it is order-dependent. But anyway, this is an implementation detail and certainly not part of the public API.

If you need to make a progress bar through a form, I'd suggest keeping this config separate from your routes, and perhaps even dynamically generating your routes from it, instead of doing the reverse.
