### ISSUE TITLE
Issue with Async Data Example

### ISSUE THREAD

**Issue by aldendaniels** [rackt/react-router#809]
If I'm reading the [async data](https://github.com/rackt/react-router/blob/master/examples/async-data/app.js) example correctly, this will reload all data for all components whenever the application state changes.

This seems undesirable. Imagine a two pane UI:

```
 --------------------------------------------------
| http://www.myapp.com/users/123                   |
|--------------------------------------------------
| John Smith (*)       | Name: John Smith          |
| ---------------------|                           |
| Sally Jones          | Age: 39                   |
| ---------------------|                           |
| ...                  | Occupation: Explorer      |
 --------------------------------------------------
```

Each time you navigate to a different user, we should request a new user for the right-hand pane but should not reload the list of users on the left hand page.

Currently, I'm loading data via the `willTransitionTo` static method to achieve this behavior.

Maybe I'm missing something?

**Comment by cody** [comment]
My understanding is that the data gets cached in `getJSON._cache`, so it gets only loaded once.

The async example is a bit complicated. Instead I prefere the flux pattern for data fetching.

**Comment by ryanflorence** [comment]
```js
function getJSON(url) {
  if (getJSON._cache[url])
    return Promise.resolve(getJSON._cache[url]);
  // ...
}
```

The example is not meant to be a fully baked pattern for your app, but just to demonstrate the touch points the router provides for you to it however you'd like. I tend to fill up my stores and then read directly from them in the component, that example gets the data and passes it down.

**Comment by aldendaniels** [comment]
Thanks! Makes sense.
