### ISSUE TITLE
Link without query param is set to active

### ISSUE THREAD

**Issue by rickharrison** [rackt/react-router#811]
I have a route definition like this:

```
<Route name="products" handler={baz}>
  <Route name="products-active" path="/products/active" handler={foo} />
</Route>
```

Then in a menu I have the following two links:

```
<Link to="products-active">Text</Link>
<Link to="products-active" query={{ foo: 'bar' }}>Text</Link>
```

When I am on the path `/products/active` only the first link has the `active` class applied to it, however when the path is `/products/active?foo=bar` both links have the active class applied.

@ryanflorence and I discussed the best way to fix this in IRC and we think that the preferred API would be `<Link to="foo" query={null} />`

Currently, setting it to null does not do anything due to the check on https://github.com/rackt/react-router/blob/master/modules/StateContext.js#L76

I'd like to start a discussion about the best way to achieve this API. In the meantime, you can fix the issue I described above by using the `Navigation` mixin and creating a link like this: `<Link to={this.makeHref('route-name')}>Text</Link>`

**Comment by vhmth** [comment]
I am also experiencing this issue. Actually, if you follow the [official guide](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md), you'll run into this issue as well.

**Comment by ftorre104** [comment]
I had the opposite problem -- I had query parameters and it was not marking the Link as active.

If you use the full path (as opposed to the route name) for `to` value in Link, it should work as you expect.

    <Link to="products-active">Text</Link> // will be active with or without query parameters in current url
    <Link to="/products/active">Text</Link> // will be active only when there are no query parameters  in current url

And, given your comments, I assume, that works the same way with or without query parameters in the link.

    <Link to="products-active" query={{ foo: 'bar' }}>Text</Link> // will be active with or without query parameters  in current url
    <Link to="/products/active" query={{ foo: 'bar' }}>Text</Link> // will be active only when there are no query parameters in current url

**Comment by taion** [comment]
Was resolved by https://github.com/rackt/react-router/pull/2386.

**Comment by rickharrison** [comment]
Thanks so much @taion !
