### ISSUE TITLE
Route without handler

### ISSUE THREAD

**Issue by anthonator** [rackt/react-router#814]
I'm having an issue where I want to display a modal based on a route. The problem I'm running into is that the route doesn't have a ```handler``` since the modal is being brought in as a partial. Is there a way around this or a pattern that's better suited for this scenario?

**Comment by grrowl** [comment]
On one hand, it seems to be supported in [`Route.js`](https://github.com/rackt/react-router/blob/master/modules/components/Route.js#L43):
```js
/*
 * If no handler is provided for the route, it will render a matched child route.
 */

  getDefaultProps: function(){
    return {
      handler: RouteHandler
    };
  }
```

Yet I get the warning `Warning: Required undefined `handler` was not specified in `Route`.` (can't find in source) and it fails:

```
TypeError: Cannot read property 'willTransitionTo' of undefined
    at webpack:///./~/react-router/modules/utils/Transition.js:72:1
    at webpack:///./~/react-router/modules/utils/Transition.js:16:1
    at Array.reduce (native)
    at runHooks (webpack:///./~/react-router/modules/utils/Transition.js:13:1)
```

**Comment by irvinebroque** [comment]
@anthonator - here's how I approached this.

With a route config like this, where `New User` is route that should trigger a modal...

    <Route name="Users" path="goats" handler={require('./views/Users/Handler')}>
      <Route name="New User" path="new" handler={require('./views/Goats/views/NewUser/Handler')}/>
      <Route name="User" path=":id" handler={require('./views/Users/views/User/Handler')}/>
    </Route>

... `New User` renders the following:

    return (
      <View title="New User" {...this.props}>
        <Modal {...this.props}>
          {modalContent goes here}
        </Modal>
      </View>
    );

That's one of the nice things about react-router's view nesting -- in this case the modal is rendered over the `Users` route, and you can call `transitionTo` to close the modal and transition back to the `Users` route (or anywhere else). The open/close state of the modal is simply the state of the router, so you get the whole transition lifecycle of react-router for free. Comes in handy when you want to do something async before a modal loads, before it's closed, when you want multiple steps inside a modal, etc.

I'm not quite sure what you're trying to do with "route without a handler" -- if you want something to render based on a route, that route needs a handler, unless it has children, but modals generally don't have child routes. Are you maybe looking for query params?

**Comment by anthonator** [comment]
Thanks for the input. I think I'm taking the wrong approach using the route to manage the modal. If the component can't be managed using ```<RouteHandler />``` then it probably doesn't deserve a route. Triggering the ```hide``` state of a pre-rendered component seems like a flawed approach.

If that's seems right let me know and I'll close.

**Comment by krawaller** [comment]
@grrowl That was [added just recently](https://github.com/rackt/react-router/pull/794), so its not in the distributed version yet.

**Comment by grrowl** [comment]
:+1: Thanks for letting me know.
