### ISSUE TITLE
Dynamic Component Loading

### ISSUE THREAD

**Issue by arb** [rackt/react-router#821]
I'm using webpack and I would like to load the components that are required for a given route. For example if I request "/home" I would like to make a request back to my server for the "/home.js" file that has the definition of the react "home" component. 

```js
var routeHandler = function (page) {
    return function () {
        require.ensure([], function() {
            var Element = require('./pages/' + page);
            return Element;
        });
    };
};

var App = React.createClass({
    render: function () {
        return (
            <div className='viewport  viewport--has-drawer-left  viewport--has-flyout-right  page--has-sidebar'>
                <MainNav />
                <main className='viewport__fixture  viewport__fixture--left  page-section  page-section--main' id='main'>
                    {/* This is the "outlet" or "nv-view" or whatever - the thing that changes! */}
                    <RouteHandler/>
                    <Footer />
                </main>
            </div>
        );
  }
});
var routes = (
  <Route name="app" path="/" handler={App}>
    <Route name="home" handler={routeHandler('home')}/>
    <Route name="foo" handler={routeHandler('foo')}
    <Route name="bar" handler={routeHandler('bar')}
  </Route>
);
```

I tried something like this but I get warnings and alerts about `hanlder` being a generic JavaScript function and not a component. Is there a way to just use a generic handler function or something instead of passing a component directly into the Route definition?

**Comment by cody** [comment]
Maybe this example helps: https://github.com/rackt/react-router/tree/master/examples/partial-app-loading

It uses the `bundle` loader that utilizes `require.ensure` internally.

**Comment by arb** [comment]
That looks like a good start, but when I try to plug that in I get an error from React saying:
>  Uncaught Error: Invariant Violation: createClass(...): Class specification must implement a `render` method.

If I implement the `render` method with the same code from `preRender`, the content never seems to change. Any suggestions? Do you need to see code?

**Comment by Neta-Alon** [comment]
Example changed to 'huge apps': https://github.com/rackt/react-router/tree/master/examples/huge-apps
