### ISSUE TITLE
Root route params

### ISSUE THREAD

**Issue by m64253** [rackt/react-router#823]
Is there a way to have a params on the root path like this:

```
<Route name="root" path="/:lang" handler={App}>
    <Route name="mac" handler={Mac} />
    <Route name="iphone" handler={IPhone} />
    <Route name="ipad" handler={IPad} />
</Route>
```

Without having to set the `lang` property on every `<Link />`, `transitionTo` etc.

**Comment by gaearon** [comment]
You can have your own `Link` component that fills `lang` from current `state.params.lang`.

**Comment by m64253** [comment]
Ok thanks, I'll give that a try.
