### ISSUE TITLE
Behavior when transitioning to same path

### ISSUE THREAD

**Issue by taurose** [rackt/react-router#826]
Right now, when clicking a link to the currently active path, the browser will 

* create a new history entry (HistoryLocation)
* not create a new history entry (HashLocation)
* not "refresh" the page by calling the run callback

On static web sites, all the browsers I tested do refresh the page, but they don't create new history entries, so I think we should do this, too. Or at least make HistoryLocation and HashLocation consistent.

**Comment by gaearon** [comment]
How do you tell it creates a new entry? I click many times on current page's link in my app and I can go back in a single Back click.

**Comment by taurose** [comment]
> I click many times on current page's link in my app and I can go back in a single Back click.

That's not what I'm observing at http://react-router-mega-demo.herokuapp.com/ with either Chrome, Firefox or IE. Are you sure you tried with HistoryLocation?

**Comment by gaearon** [comment]
Sorry, indeed you're right. I verified on `HashLocation` by mistake!

**Comment by RickWong** [comment]
@taurose Did you find a work-arround?

**Comment by taurose** [comment]
I've been meaning to create a PR but haven't gotten around to it yet. 

I don't think there's a simple and clean way to get the always-refresh behavior. As for not creating new history entries for `HistoryLocation`, you should be able to intercept `HistoryLocation.push()`:

```js
HistoryLocation._push = HistoryLocation.push;
HistoryLocation.push = function(path){
  if(path !== HistoryLocation.getCurrentPath())
    HistoryLocation._push(path);
}
```

**Comment by RickWong** [comment]
✅ Thanks @taurose, it works!

**Comment by darrenmce** [comment]
> not create an additional history entry if path has not changed (HistoryLocation and TestLocation)

+1

thanks for workaround in the meantime!

**Comment by ryanflorence** [comment]
I imagine we still have this issue on master

**Comment by ryanflorence** [comment]
@taurose @mjackson please reopen if I'm wrong, but I think your work on `history` defined this stuff.

**Comment by JakovlevDS** [comment]
hey guys, what about this:
> not create an additional history entry if path has not changed (HistoryLocation and TestLocation)

I'm on react-router 1.0.0-rc3 + "history/lib/createBrowserHistory" and this problem still appears for me.
Thanks.
