### ISSUE TITLE
Binding transitionTo directly to onClick

### ISSUE THREAD

**Issue by 0x80** [rackt/react-router#832]
In a component which uses the router Navigation mixin, I was trying to do this:

```
<a onClick={this.transitionTo.bind(this, 'create')} icon="action-note-add">click me</a>
```
...as a lazy way to transition to a different route without having to create a url or handler method in my component. BTW I'm not actually using the anchor tag in my code otherwise I would have used Link.

It works only half. I get a lot of extra mess appended to the url like

```
http://localhost:1338/#/create?0=.&1=0&2=.&3=2&4=.&5=0&6=.&7=0&8=.&9=1&10=.&11=0&12=.&13=1&14=%253A&15=2
```

Is this just a bad idea or am I missing something here?

**Comment by BerkeleyTrue** [comment]
transitionTo takes three arguments, onClick provides the function its bound to with an event object. You are essentially passing in the event object itself as the params. 
try

```<a onClick={this.transitionTo.bind(this, 'create', null, null)} icon="action-note-add">click me</a>```

**Comment by 0x80** [comment]
Ah that makes perfect sense, thanks!

**Comment by taurose** [comment]
Or just do `<a onClick={() => this.transitionTo('create')} icon="action-note-add">click me</a>` with harmony flag enabled.
Saves you from trouble if another parameter was added ;)

**Comment by 0x80** [comment]
I like that solution, thanks.
