### ISSUE TITLE
qs/lib/utils merge function causing issues after bumb to version 2.3.3.

### ISSUE THREAD

**Issue by 1313** [rackt/react-router#833]
Pull request created for qs. 
https://github.com/hapijs/qs/pull/68

**Comment by 1313** [comment]
Issue affects the Path.withQuery method as you cannot override query parameter values through replaceWith.

```javascript
this.replaceWith("route", {}, {a:"a"});
// query a still has value "a" after this call...
this.replaceWith("route", {}, {a:"b"});

**Comment by 1313** [comment]
This is the line that causes the issue by using the merge function:
https://github.com/rackt/react-router/blob/master/modules/utils/Path.js#L131

**Comment by mhils** [comment]
See also: https://github.com/hapijs/qs/issues/67

**Comment by ryanflorence** [comment]
query parsing/stringifying is now pluggable, so if there are issues like this again you can workaround by providing your own.
