### ISSUE TITLE
Problem with path delimiter and values

### ISSUE THREAD

**Issue by Hyra** [rackt/react-router#841]
I want to have URLs looking like:

/someone/12345-projectslug

I use the following route for it:
```javascript
<Route name='project' path='/:owner/:projectId-:projectSlug' handler={Project} />
```

This works well, unless there's a dash `-` inside the projectSlug

One solution would be to have a double dash as a delimiter, but this doesn't look as nice, and maybe there's a better solution.

Any help is appreciated!

**Comment by mjackson** [comment]
We should probably make the regex greedy so that when it's trying to match `projectSlug` it matches all the way to the next char that doesn't make sense.

**Comment by taion** [comment]
This sort of thing would be much better handled with #2286.

**Comment by alexesDev** [comment]
I know this is an old issue, but tip... just change route like this:
```
<Route name='project' path='/:owner/:projectSlug-:projectId' handler={Project} />
```
