### ISSUE TITLE
can react-router generate a mapping file for express/htaccess/etc?

### ISSUE THREAD

**Issue by Pomax** [rackt/react-router#842]
Is there a utility available to generate the necessary server-side path mapping so that users visiting a specific URL can get directed to the main react app with all the necessary arguments to load up the component and state associated with a particular route?

(.htaccess rewrite, express/hapi routing instructions, etc?)

**Comment by Schniz** [comment]
For express you can just use a middleware that catches everything.
You can also check for route existence with `Router.run` (and checking the state)

**Comment by Pomax** [comment]
I could, but catching everything is not a good thing when automating a deploy. white listed routes are generally preferred (if the route doesn't exist, it shouldn't even bother trying to resolve, it should be an instant 404). Using Router.run sounds like a better strategy, thanks.

**Comment by davidascher** [comment]
Checking for existence is fine but still requires serverside logic.  It'd be good to also be able to get a list of all paths corresponding to routes, so that the app could be served e.g. out of an s3 bucket.

**Comment by ryanflorence** [comment]
You use the router on the server to map the urls just like the client, check out the mega demo: https://github.com/rackt/react-router-mega-demo

**Comment by Pomax** [comment]
That's pretty neat! Although it's also pure code without code comments or documentation, which is less neat.

**Comment by ignaciosegura** [comment]
Just for the record, if you just want to pipe all your app URLs to your React app, a simple HTACCESS file will do the trick fast and neat:

http://stackoverflow.com/a/38827810/381914
