### ISSUE TITLE
HashLocation should preserve GET parameters

### ISSUE THREAD

**Issue by basham** [rackt/react-router#849]
When the app mounts using the `Router.HashLocation` location, it strips all GET parameters. These should be preserved.

More specifically, this starting URL:

```
http://localhost:3000/?work=please
```

Would be replaced with this URL, once the router mounts:

```
http://localhost:3000/#/
```

Although I want it to be this URL:

```
http://localhost:3000/?work=please#/
```

I've resolved this by duplicating `HashLocation.js` is my own code, with the only modification being its dependency paths.

```js
// `main.jsx`
var React = require('react');
var Router = require('react-router');
var Route = Router.Route;
var DefaultRoute = Router.DefaultRoute;

var HashLocation = require('./locations/HashLocation');

var App = require('./components/App');
var Home = require('./components/Home');

var routes = (
  <Route handler={App}>
    <DefaultRoute name="home" handler={Home} />
  </Route>
);

Router.run(routes, HashLocation, function(Handler, state) {
  React.render(<Handler params={state.params} />, document.getElementById('app'));
});
```

```js
// `./locations/HashLocation.js`
var LocationActions = require('./LocationActions');
var History = require('react-router').History;

// The rest of this file is identical to:
// https://github.com/rackt/react-router/blob/db2607d4d33322acb2c77c8906068015f2254c12/modules/locations/HashLocation.js
```

```js
// `./locations/LocationActions.js`

// This file is identical to:
// https://github.com/rackt/react-router/blob/f92dd20aa0f411a7812fb1d05e280e3aa748aa45/modules/actions/LocationActions.js
```

I wonder if there's some check in [`createRouter.js`](https://github.com/rackt/react-router/blob/master/modules/createRouter.js) that is looking for the internal instance of `HashLocation`. That check would fail when I send it my custom instance and the GET parameters would be retained.

**Comment by mjackson** [comment]
@basham Which version of the router are you using? We should [already be preserving the query string](https://github.com/rackt/react-router/blob/master/modules/locations/HashLocation.js#L104).

**Comment by basham** [comment]
I'm using version 0.11.6. Didn't realize about the 0.12.0 release from last week. That fixed it. I need to stay more on top of my dependency releases. Thanks. Closing the issue.
