### ISSUE TITLE
[Question] How to use react-router to scroll to any location with in a page

### ISSUE THREAD

**Issue by akiran** [rackt/react-router#852]
I am trying to building a parallax website with react and react-router.
I couldn't figure out a way to scroll within a page using react-router.
Is there any example for this ?

I also posted it on stackoverflow
http://stackoverflow.com/questions/28590040/how-to-use-react-router-to-jump-to-specific-location-in-the-page

**Comment by gaearon** [comment]
If seems that you'd want a single route, and use `params` to tell between the active slide.

**Comment by gaearon** [comment]
I think I'll close this. There are multiple ways you might want to have scrolling: without animation, with animation. Router shouldn't dictate that. You can solve this with `params` + `componentDidMount`/`componentWillReceiveProps` to track their changes. You can also solve this by specifying a custom `scrollBehavior` in router options.
