### ISSUE TITLE
Matching both `path` and `path/`

### ISSUE THREAD

**Issue by malandrew** [rackt/react-router#853]
The path matching document doesn't really indicate how to get an app to mount to both `path` and `path/`  (with the trailing slash).

I recently encountered this problem when mounting an application as an express sub-app (which will always mount the sub-app with a trailing slash).

**Comment by mrtnbroder** [comment]
Also got the same problem. My DefaultRoute has to work on the following paths:

`/us`, `/us/` however, it only works on `/us`

```
<Route path='/us' handler={require('./views/Handler')}>
  <DefaultRoute name='frontpage' handler={require('./views/Frontpage/Frontpage')} />
  <NotFoundRoute name='NotFound' handler={require('./views/NotFound/NotFound')} />
</Route>
```

**Comment by malandrew** [comment]
I tried the redirect option, but then it doesn't work if the app is mounted somewhere that redirects to trailing slashes. What I want is it to respond to both.

**Comment by mrtnbroder** [comment]
I asked a similar question earlier, try this:

`<Route path='/us/?' handler={require('./views/Handler')}>`

notice the `/?` at the end.

**Comment by mjackson** [comment]
We really need an easy way to make the trailing slash optional. Let's follow up in #820.
