### ISSUE TITLE
Nested routes and parameters

### ISSUE THREAD

**Issue by efdee** [rackt/react-router#854]
Hello,

I'm having an issue creating nested routes where the parent route contains a parameter. This is my desired end result:
* I want #/projects/1 to be handled by ProjectDashboard
* I want #/projects/1/documents to be handled by ProjectDocumentIndex,
* Both components should be wrapped in ProjectWrapper

This is my current route setup:

        <Route name="project" path="/projects/:projectId" handler={ProjectWrapper}>
            <Route name="project-detail" path="XXXXXXXX" handler={ProjectDashboard} />
            <Route name="project-documents" path="documents" handler={ProjectDocumentIndex} />
        </Route>

I'm unsure what to substitute for XXXXXXXX:
* If I try "/", I get an error: Invariant Violation: Missing "projectId" parameter for path "/"
* If I try "", I don't get an error, but #/projects/1 renders ProjectWrapper without ProjectDashboard
* If I try "/projects/:projectId", I get an error: Invariant Violation: Missing "projectId" parameter for path "/projects/:projectId/documents"
* If I remove the project-detail route entirely and replace it with <DefaultRoute handler={ProjectDashboard} />, I get an error: Invariant Violation: Missing "projectId" parameter for path "/projects/:projectId/documents"

What should I do?

**Comment by ganmor** [comment]
I would say : 

```xml
 <Route name="project" path="/projects/" handler={ProjectWrapper}>
        <Route name="project-detail" path="/projects/:projectId" handler={ProjectDashboard} />
        <Route name="project-documents" path="/projects/:projectId/documents" handler={ProjectDocumentIndex} />
    </Route>
```

**Comment by efdee** [comment]
#/projects/ is a route that is handled by another component that should not be wrapped in ProjectWrapper (and that, itself, can't act as a wrapper for ProjectDashboard or ProjectDocumentIndex either). I really need the wrapper to be used only on #/projects/:id and pages below that.

**Comment by ganmor** [comment]
#/projects/  will not be matched by /projects/:projectId

As for the awkwardness of having to repeat the path, I would say it makes sense because you can see by just looking at a particular route what is the url and what are the parameters.

**Comment by efdee** [comment]
Not sure what you mean with that. I don't want #/projects/ to be matched by /projects/:projectId. My point was that in your example, #/projects/ will be rendered by ProjectWrapper instead of the (already existing) handler that I have set up for it. Maybe I should have pasted a larger excerpt from my routing. This is what I currently have (but it's not working):

    <Route name="app" path="/" handler={Page}>

        <Route name="projects" path="/projects" handler={ProjectIndex} />
        <Route name="projects-new" path="/projects/new" handler={ProjectNew} />
        <Route name="project" path="/projects/:projectId" handler={ProjectWrapper}>
            <Route name="project-documents" path="documents" handler={ProjectDocumentIndex} />
            <DefaultRoute handler={ProjectDashboard} />
        </Route>
        (...)
    </Route>

As for the awkwardness, still feels wrong, but I can live with that.

**Comment by taurose** [comment]
Sounds like you're looking for DefaultRoute. Try this

```js
 <Route name="project" path="/projects/:projectId" handler={ProjectWrapper}>
        <DefaultRoute name="project-detail" handler={ProjectDashboard} />
        <Route name="project-documents" path="documents" handler={ProjectDocumentIndex} />
</Route>
```

**Comment by efdee** [comment]
@taurose That's what I thought (you can see that's what I tried in my latest paste). But that when I do that, and then go to #/projects/1, I get this error: Invariant Violation: Missing "projectId" parameter for path "/projects/:projectId/documents"

I find it kind of weird that I get an error on the documents route one while triggering the detail route, but I guess it's trying to evaluate it.

**Comment by taurose** [comment]
Perhaps I'm missing something here, but that does sound like a bug. Are you using the latest release?

Have you tried without the slashes at the beginning of the paths?

```js
<Route name="app" path="/" handler={Page}>
    <Route name="projects" path="projects" handler={ProjectIndex} />
    <Route name="projects-new" path="projects/new" handler={ProjectNew} />
    <Route name="project" path="projects/:projectId" handler={ProjectWrapper}>
        <Route name="project-documents" path="documents" handler={ProjectDocumentIndex} />
        <DefaultRoute handler={ProjectDashboard} />
    </Route>
    (...)
</Route>
```

**Comment by efdee** [comment]
@taurose Yes, I tried that, still the same problem though. I'm on 0.12.0.

However, I was trying to create a small test case to reproduce, and it looks like in the test, everything works. I'll see if I can get it to fail and report back here.

**Comment by efdee** [comment]
Well this is embarassing.

The error message didn't actually come from the router setup. Everything was working as it should have (especially with the latest version with DefaultRoute), but the selected component was rendering a Link element that was missing a parameter required for the route it was linking to.

Finally figured it out by taking a deep good look at the stack trace when the error occurred.

Sorry for wasting your (and my) time.

**Comment by taurose** [comment]
That makes sense. No worries, glad you figured it out eventually.

**Comment by fnitschmann** [comment]
Hey guys, I'm fighting with the same problem. Did you found a solution @efdee ? Thanks in advance!

**Comment by efdee** [comment]
@fnitschmann In my case the problem was caused by me, not react-router. This issue has been closed though, maybe you should create a new issue with more information, or post it to StackOverflow.

**Comment by fnitschmann** [comment]
Thanks for your fast reply @efdee! 
The solution for me, my problem , and I think in generell to stop struggling around with deep nested routes + parameters, is/was an upgrade to the new react-router ` 1.0.0-rc1 `. It solves many problems and brings a lot of cool new things. 
I'm not sure, maybe there is also an an solution possible with any 0.13.x version... 
But nevermind.
