### ISSUE TITLE
Retrying on a transition with query parameters redirects to a path without "?"

### ISSUE THREAD

**Issue by SBRK** [rackt/react-router#857]
1. Navigate to a path with a query like "mypage/foo/?foo=bar"
2. In the willTransitionTo, redirect to another page (in my case, the login page)
3. Call retry on the original transition with a query (once the user is logged in)
4. The resulting path is missing the "?" : "mypage/foo/foo=bar"

**Comment by gaearon** [comment]
A failing test would be very welcome! Can you manage that?

**Comment by ryanflorence** [comment]
so `transition.retry` doesn't keep the query around?

**Comment by mjackson** [comment]
`transition.retry` is removed in the 1.0 API.
