### ISSUE TITLE
Location always matches the first root /

### ISSUE THREAD

**Issue by kimmobrunfeldt** [rackt/react-router#858]
This might be my own silly mistake but the router always matches to the first handler, which in this case is `App`. I'm doing server side rendering.

This can be reproduced easily, I isolated the issue here: https://github.com/kimmobrunfeldt/react-router-problem/

My routes:

    var routes = (
        <Route name="index" path="/" handler={App}>
            <Route name="login" path="login" handler={Login}/>
            <NotFoundRoute handler={NotFound}/>
        </Route>
    );

Rendering with forced `"/login"` url:

    ReactRouter.run(routes, '/login', function(Handler, state) {
        var handler = React.createElement(Handler, {
            params: state.params,
            query: state.query
        });
        var initialHtml = React.renderToString(handler);

        console.log(initialHtml);
    });

Will always render contents off App component.

**Comment by taurose** [comment]
You need to add a `<RouteHandler />` to the render method of handlers that can have child routes/handlers (in your case the App component). This allows you to decide where in the DOM the child handler should be rendered. You can also pass props this way. 
See, for example, [the overview guide](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md).

**Comment by kimmobrunfeldt** [comment]
Oh I missed that part, thank you! :)
