### ISSUE TITLE
Ampersands in query are not being escaped (v0.12.0)

### ISSUE THREAD

**Issue by jackmoore** [rackt/react-router#859]
If I do a transition with a query such as `{ foo: "bar&baz"}`, the router transitions to an URL like `?foo=bar&baz`, which the router then interprets as `{foo: "bar", baz: ""}`

This issue is similar to #343, which was resolved.

**Comment by mjackson** [comment]
This was fixed in #805. We still need to cut a release with the fix.

**Comment by jackmoore** [comment]
Great, thank you.
