### ISSUE TITLE
Abstract routes

### ISSUE THREAD

**Issue by Carlsson87** [rackt/react-router#860]
Do you have any plans on implementing abstract routes/states?

For example
```
<Route path="/" handler={Site}>
    <Route path="one" handler={PageOne}/>
    <Route path="two" handler={PageTwo}/>
    <Route path="three" handler={PageThree}/>
    <Route handler={Container}>
        <Route path="three/contained" handler={PageThree}/>
    </Route>
</Route>
```
So whenever `/three/contained` is requested `PageThree` is rendered within the handler of the abstract parent route.

I only know this concept by the name "abstract state" from using it in [ui-router](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#abstract-states) with angular, so if it goes by any other name around here please enlighten me =)

**Comment by gaearon** [comment]
I read the doc but I don't understand what “abstract states” do.
Can you explain this from user perspective? As in, what do you want user to see.

**Comment by Carlsson87** [comment]
What I am trying to accomplish is the possibility to render the same handler within two different contexts WITHOUT having to have that context represented in the path.

For example, say that I have the component `LoginForm`, I want to be able to render it directly on the page, or within a modal/dialog. Right now I can do that, but each of those contexts has(?) to be represented by a declared route with it's own path.

For example:
```
<Route path="/" handler={Site}>
    <Route path="login" handler={LoginForm}/>
    <Route path="modal" handler={Modal}>
        <Route path="login" handler={LoginForm}/>
    </Route>
</Route>
```

1. `/login` - shows the login form on the page
2. `/modal/login` - shows the login form in a modal

Route nr 2 makes the login form render in the context of a modal, but the context (the modal) is defined by a concrete route segment (`path="modal"`).

I would like to do this:
```
<Route path="/" handler={Site}>
    <Route path="login" handler={LoginForm}/>
    <Route handler={Modal}>
        <Route path="login/modal" handler={LoginForm}/>
    </Route>
</Route>
```
In this case, the path `/login/modal` would be matched and the LoginForm would be rendered in within the modal. In this case the context (the modal) doesn't have it's own segment in the path, it is implied by where the matched route is in the hierarchy.

**Comment by mjackson** [comment]
@Carlsson87 Absolutely. Your second example should work as-is. Have you tried it?

**Comment by taurose** [comment]
Wouldn't that cause '/' to be resolved to Site > Modal ? And DefaultRoute couldn't help either, since it's matched last.

**Comment by mjackson** [comment]
@taurose The way I read the second route definition you'll get:

```
/               => Site
/login          => Site > LoginForm
/login/modal    => Site > Modal > LoginForm
```

**Comment by taurose** [comment]
Are you sure? Looking at [that line](https://github.com/rackt/react-router/blob/v0.12.4/modules/Route.js#L82) it should be equivalent to

```js
<Route path="/" handler={Site}>
    <Route path="login" handler={LoginForm}/>
    <Route path="/" handler={Modal}>
        <Route path="login/modal" handler={LoginForm}/>
    </Route>
</Route>
```

**Comment by mjackson** [comment]
@taurose Maybe we need something like an `AbstractRoute` or `WrapperRoute` that only matches if one of its children does?

**Comment by taurose** [comment]
Yeah I think that could be useful. I also thought about making it implicit when neither path nor name is given, but it would probably break some valid use cases.

**Comment by mjackson** [comment]
> I also thought about making it implicit when neither path nor name is given

That's interesting, especially because I just made the mistake above of assuming that's how routes with no `name`/`path` work! I think it's worth exploring in greater depth.

**Comment by auser** [comment]
+1 I'm experiencing this myself

**Comment by matrinox** [comment]
:+1:

**Comment by LeviBotelho** [comment]
:+1:

**Comment by ryanflorence** [comment]
Paths are now required in 1.0, so these ambiguities shouldn't happen.

Additionally, to share UI among routes, like `LoginForm`, you don't have to assign it as the route component, you can just render it inside of any route component you want.
