### ISSUE TITLE
Should we keep JSX configuration?

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#865]
I'm opening this issue to discuss whether or not we want to keep `<Route name>`. In c5a24a5 I introduced the `Route` class which lets you use a `Route` object directly in `<Link to={MyRoute}>`. This is nice when you have many, many routes that you can't keep all in one file.

Technically, this eliminates the need for `<Route name>` because you can just use object references. Indeed, I started the work on c5a24a5 excluding names altogether. However, when I went back to make the examples work with the new object reference style, it didn't feel nearly as convenient as just using a string name. I don't want people just getting started with the router to have to go through the ceremony of creating a bunch of object references, when a fairly high % of our users (arguably most) will get by just fine using only route names.

I can also understand people being bothered by the fact that there's more than one way to link to stuff. But it doesn't bother me enough to remove the feature entirely.

/cc @ryanflorence @taurose @josephsavona

**Comment by rickharrison** [comment]
I really like having the ability to define all my routes in JSX. Both apps I have in production have around 40 files, and I haven't felt any pain in maintaining a `routes.jsx` file with all of my definitions. I also like being able to just have a quick link as `<Link to="foo-list">`. I am in favor of keeping the name.

**Comment by ryanflorence** [comment]
@rickharrison what if you just linked to the path? I find my route names end up just being truncated versions of the path, could conventionally say "foo/:id/bar/:name" becomes `<Link to="foo.bar." params={params}/>` where `.` just holds the place of dynamic segments?

**Comment by taurose** [comment]
Perhaps I'm missing something, but why drop `<Route name>` while keeping JSX configuration? Or is this about dropping JSX altogether? Without the name, we couldn't even generate links without using absolute URL paths, could we?

**Comment by ryanflorence** [comment]
One benefit of getting rid of `name` is testing. If we supported these two ways to create a link:

```js
<Link to="same/:path/as/:route/config" params={params}/>
<Link to={RouteObject} params={params}/>
```

Then we wouldn't need context at all to generate links. Any chance to not rely on context I'd love to take.

I also like how simple it is to `<Link to="someName"/>` though.

**Comment by mjackson** [comment]
> Without the name, we couldn't even generate links without using absolute URL paths, could we?

@taurose Great observation. Yes, that's correct. I preserved `<Route name>` for this reason.

@ryanflorence I'd rather not introduce yet another notation for paths. We already have URL patterns that have special notation. Another special notation is confusing, IMO.

**Comment by mjackson** [comment]
> we wouldn't need context at all to generate links

@ryanflorence Yes, that's a great point too and IMO the strongest argument in favor of not supporting string names. But I also think that @taurose has a great point: if we get rid of `<Route name>` we might as well get rid of JSX config altogether. `<Route name>` was always just a way to refer to a route without an actual reference to it.

**Comment by rickharrison** [comment]
@ryanflorence I don't like linking full paths all throughout the code base, because there have been instances where I change the URL for a particular resource. Then I just have to change it in one place and add a simple `<RedirectRoute>` to make sure the old url works.

For me, I just wouldn't want to add 40 more files to my project all for things which are just one line of configuration.

**Comment by mjackson** [comment]
> I just wouldn't want to add 40 more files to my project all for things which are just one line of configuration.

@rickharrison I hear you. That's exactly how I felt when I went to refactor all of our example apps to not use `name`. It felt tedious.

**Comment by ryanflorence** [comment]
> because there have been instances where I change the URL for a particular resource. Then I just have to change it in one place and add a simple <RedirectRoute> to make sure the old url works.

Yeah, that was my original intent on `name`. Might as well keep it, @mjackson. I'd like to *not* build them up for people (I think your new code does `parent.child` with the name), because removes the conveniences @rickharrison's mentions, and the reason I made `name` in the first place.

**Comment by ryanflorence** [comment]
Just keep name as it works today, they're all just global references, don't concat or with parents or anything.

**Comment by ryanflorence** [comment]
whah what the heck, there are two issues here? all of these comments were for #865

**Comment by ryanflorence** [comment]
wait, what is going on? why the topic change? keeping "name" and ditching "jsx" are different things.

**Comment by mjackson** [comment]
@ryanflorence See @taurose' comment above https://github.com/rackt/react-router/issues/865#issuecomment-75666002
