### ISSUE TITLE
doesnt work with pure render mixin

### ISSUE THREAD

**Issue by contra** [rackt/react-router#866]
since the route is essentially a new form of state the react pure render mixin doesn't work out of the box. i wrote one that does work that could be used instead

```js
'use strict';

var shallowEqual = require('react/lib/shallowEqual');
var lastPath;

module.exports = {
  shouldComponentUpdate: function(nextProps, nextState) {
    // component is route-able
    var routeChanged = this.getPath && didPathChange(this.getPath());
    return routeChanged ||
      !shallowEqual(this.props, nextProps) ||
      !shallowEqual(this.state, nextState);
  }
};

function didPathChange(currPath) {
  var pathChanged = lastPath !== currPath;
  lastPath = currPath;
  return pathChanged;
}
```

not sure if this is just a documentation item or something you want to put in the repo

**Comment by gaearon** [comment]
I believe this to be a duplicate of #470. I currently solve this by having my own mixin where I explicitly subscribe to my own `RouterStore` so it gets into `state`.

Related: facebook/react#2517

**Comment by contra** [comment]
cool - didnt get anything when i searched for "pure" but that is def a duplicate.

**Comment by tajo** [comment]
ES6 style solution: https://github.com/tajo/este/blob/master/src/lib/linkcomponent.js

**Comment by CezaryDanielNowak** [comment]
This issue still occours
