### ISSUE TITLE
Flow fails on requiring react-router

### ISSUE THREAD

**Issue by Dignifiedquire** [rackt/react-router#868]
This is an underlying issue with flow itself, but it would be great if it could be fixed here for now.

If I do 
```js
/* @flow */
var ReactRouter = require('react-router');
```
flow will fail with:

```
path/to/file:2 lib
Required module not found
```

Changing the `main` property from `lib` in the package.json of react-router to be `lib/index` makes it work.

* `flow@0.4.0`
* `react-router@0.12.2`

Ref: https://github.com/facebook/flow/issues/278

**Comment by ryanflorence** [comment]
facebook/flow@0.5.0 ?
