### ISSUE TITLE
DefaultRoute ignored if given a name property in 0.12.2

### ISSUE THREAD

**Issue by mshick** [rackt/react-router#870]
With the update to 0.12.2 my `willTransitionTo` hook is never being called. It's nested in a reasonably complex app, so extracting out the precise point of failure would take some work, but I wanted to create an issue to get it on your radar. 

Reverting to 0.12.0 solved the problem.

**Comment by mjackson** [comment]
@mshick Thanks for the report. A failing test case would be invaluable here.

**Comment by mshick** [comment]
After some digging it seems to be because a `DefaultRoute` with a name property is now ignored. I wonder if this is intentional? I was using route names to coordinate some app actions, so this puts a crimper in that.

**Comment by mshick** [comment]
Here's a simple test I set up: https://gist.github.com/37d11269063ecfdda22e

If you try running that it will just hit up the App route. If you remove `name="Dashboard"` from the default route it will work as expected.

**Comment by mjackson** [comment]
@mshick Ah, I see what you mean. Yes, this is indeed a regression. We don't have a test for it :/

Working one up now.

**Comment by mjackson** [comment]
@mshick The fix for this regression is released in 0.12.3. Sorry about that!

**Comment by mshick** [comment]
Thanks for the quick attention, and the project.
