### ISSUE TITLE
Using TransitionGroup and nested routes, only animate the parent once

### ISSUE THREAD

**Issue by mattapperson** [rackt/react-router#874]
Has anyone found a way to animate a nested route in such a way that the parent route animates in, but when navigating between child elements, the parent does not keep re-animating? I am at a bit of a loss...

**Comment by ryanflorence** [comment]
I hope to spend some time with more complex animations, but for now the one in the examples is all we've got for you :\

**Comment by ThibWeb** [comment]
Hey @mattapperson, I had the same issue and tried to solve it by removing the children's segment of the path from the parent component's `RouteHandler` `key`. Here's some code: https://github.com/rackt/react-router/pull/1226.
