### ISSUE TITLE
Navigation's `goBack()` method doesn't work

### ISSUE THREAD

**Issue by voronianski** [rackt/react-router#875]
Everytime it returns `Warning: goBack() was ignored because there is no router history`.

Creating router like:

```javascript
import ReactRouter from 'react-router';
import routes from './routes.jsx';

export default ReactRouter.create({
    routes: routes,
    location: ReactRouter.HistoryLocation
});
```

Also it's used on server-side 'cause app is isomorphic:

```javascript 
...
ReactRouter.run(routes, req.url, function (Handler) {
      let content = React.renderToString(React.createElement(Handler, { flux }));
      res.render('base', { title, content, mainJs, mainCss, snapshot });
});
```

Any issues with latest version?

**Comment by gaearon** [comment]
`goBack` won't go back if you just entered the app. There's rarely any sense in going Back to Google, for example. If you really want to go Back wherever the user was, you can call `window.history.back()`.

However, if you already navigated somewhere inside the app, `goBack` should work fine (unless you used `replaceWith`).

Which situation is this? Do we have a bug?

**Comment by voronianski** [comment]
@gaearon I'm using `Navigation`'s `transitionTo` method, I will provide a fiddle or some demo in order to reproduce this issue.

**Comment by ryanflorence** [comment]
20 days old w/o a response, please holler if I should reopen and you've got a demo :)

**Comment by voronianski** [comment]
@ryanflorence sorry, that's fine now :+1:
