### ISSUE TITLE
TransisionTo between different layouts

### ISSUE THREAD

**Issue by kylehotchkiss** [rackt/react-router#882]
Hey there,

I had a quick question that hopefully makes sense. My app has several different "layouts". I can successfully transisionTo between two routes within the same "layout", but when I try to transisionTo between different layouts, i get errors (all I can squeeze out of the error message is `framesToPop: 1`)

I was just wondering if there was support for transisions between seperate layouts or if a different sort of redirect should be attempted. Thanks!

**Comment by gaearon** [comment]
Hard to say without a failing example. Can you manage one?

**Comment by ryanflorence** [comment]
this is about a month old w/ no response. Closing.
