### ISSUE TITLE
Code to interrogate a Route

### ISSUE THREAD

**Issue by zol** [rackt/react-router#885]
Has anyone written or knows of code to list an app's routes. I.e, something like

``` js
var routes = (
  <Route name="app" path="/" handler={Application}>
    <Route name="about" handler={About}/>
    <DefaultRoute name="home" handler={Home}/>
  </Route>
);

interrogate(routes);
```

That would return (at least)

```
['/', '/about', '/home']
```

This would be useful for the static site generator I'm building.

**Comment by johanneslumpe** [comment]
You could use something like this:

```javascript
const routes = (
  <Route name='root' path='/' handler={RootHandler}>
    <Route name='nested' path='firstLevel' handler={FirstLevel}>
      <Route name='nested' path='secondLevel' handler={SecondLevel} />
    </Route>
    <Route name='nested' path='anotherFirstLevel' handler={AnotherFirstLevel} />
    <DefaultRoute name="home" handler={DefaultHandler}/>
    <NotFoundRoute name="notfound" handler={ErrorHandler}/>
  </Route>
);

import {join} from 'path';

const interrogate = function interrogate(routes, parentPath) {
  let result = [];
  routes = Array.isArray(routes) ? routes: [routes];

  routes.forEach((route) => {
    const props = route._store.props;
    let path = props.path;

    if (path) {
      path = parentPath ?
        join(parentPath,path) :
        path;

      result.push(path);
    }
    if (props.children) {
      result = result.concat(interrogate(props.children, path));
    }
  });
  return result;
};

console.log(interrogate(routes));
```

The above will then log

```javascript
[ '/',
  '/firstLevel',
  '/firstLevel/secondLevel',
  '/anotherFirstLevel' ]
```
You actually wanted `about` and `home` to show up as paths, but those are your internal route names, not their paths. I took the liberty to actually use the route paths, but you get the idea.

Note that his makes use of the internal state store of the factory, which might break at any point. Is this what you are looking for?

**Comment by zol** [comment]
Brilliant, thats exactly what I what I was looking for. Thanks very much @johanneslumpe

**Comment by CaseyLeask** [comment]
@johanneslumpe That's a much neater version of the exact same thing I wrote for this. Have you thought of making a package for it? It feels like a waste to let it sit in a closed issue.

**Comment by johanneslumpe** [comment]
@CaseyLeask actually I haven't thought about it. I didn't think that a lot of people would use this :D

**Comment by CaseyLeask** [comment]
@johanneslumpe It's useful enough that I made it a `module` in my react-router to jekyll project. https://github.com/CaseyLeask/caseyleask.github.io/blob/blog-take-four/src/util/interrogate-react-router.js
