### ISSUE TITLE
Warning: <DefaultRoute> may not have a "path" prop

### ISSUE THREAD

**Issue by micahlmartin** [rackt/react-router#886]
This confused me for a bit. I thought it was saying that `it's possible that the path prop is not set on DefaultRoute`, but in reality it means `DefaultRoute SHOULD NOT HAVE a path prop`. It's a minor tweak in language but definitely clears it up. I'm happy to submit a PR, but I can't seem to find where that comes from. Is it actually buried in React somwhere?

**Comment by mjackson** [comment]
@micahlmartin The message is generated [here](https://github.com/rackt/react-router/blob/master/modules/PropTypes.js#L12)
