### ISSUE TITLE
Using programmatic routes is not matching the route

### ISSUE THREAD

**Issue by vasya10** [rackt/react-router#887]
Using 0.12.4 (tried .2 and .3 too). Instead of jsx declaration, Im trying the programmatic way of creating routes. I have many 'modules' in my application and I want each of them to declare their own router, ie I dont want to put all my routes in one place, but they all reuse the one parent route.

//showing together for sample, they could each be in different files.
var MainRoute = Router.createRoute({ name:"main", path: "/", handler: ..})
Router.createRoute({name: "login", path: "/login", parentRoute: MainRoute, handler:...})
Router.createRoute({name: "profile", path: "/profile", parentRoute: MainRoute, handler..})
Router.createDefaultRoute({parentRoute: MainRoute})
Router.run(MainRoute, function(Handler) {React.render(<Hander/>, document.body});

However when I run this, I see warning in browser console: Warning: No route matches path "/". Make sure you have <Route path="/"> somewhere in your routes. I dont see the page loading obviously.

If I do the same in jsx, it works fine:

var routes = (
  &lt;Route name="main" path="/" handler={}&gt;
    &lt;Route name="login" path="/login" handler={} /&gt;
    &lt;Route name="profile" path="/profile" handler={} /&gt;
  &lt;/Route&gt;
);

Are these constructs equivalent? Am I missing something when I create the routes programmatically?

Thanks for help!

**Comment by vasya10** [comment]
I solved it after debugging through the Router.js. The this.match(path) was failing, because this.routes was not set. Since routes is an array, I had to change it to the following:

Router.run([MainRouter], function(Handler) {React.render( .., document.body)};

**Comment by gaearon** [comment]
We should probably treat single item as valid there. @mjackson ?

**Comment by ryanflorence** [comment]
yes

**Comment by jketcham** [comment]
Was also experiencing this issue, thanks for the workaround for now

**Comment by ryanflorence** [comment]
1.0 allows a single route or array of routes
