### ISSUE TITLE
Are Route names supposed to be unique?

### ISSUE THREAD

**Issue by Dashed** [rackt/react-router#890]
Using `react-router v0.12.4`.

Are Route names supposed to be unique? The following doesn't seem to work.

```js
<Route name='app' path='/' handler={MainApp} >
    // instead of DefaultRoute, we use path matching
    <Route path="/" name="dashboard" handler={Dashboard}>
        <DefaultRoute name="main" handler={DashboardMain}/>
        <Route name='settings' handler={DashboardSettings} />
    </Route>

    <Route name='settings' handler={AppSettings} />
</Route>
```

**Comment by dhenson02** [comment]
:+1: per [API guidance](https://github.com/rackt/react-router/blob/master/docs/api/components/Route.md#name) this is left ambiguous.

> **name**
The name of the route, used in the Link component and the router's transition methods.

**Comment by mjackson** [comment]
Yes, they are supposed to be unique. We used to warn you about it.. we should probably still do that.

**Comment by Dashed** [comment]
Thanks for the clarification. I thought there was some sort of scoping.

**Comment by gaearon** [comment]
I suppose clarification didn't hurt so I added it. https://github.com/rackt/react-router/commit/c9864af0af1214f0f5317cc056fd1d1af0a91d46
