### ISSUE TITLE
Linking to same Route with different Params

### ISSUE THREAD

**Issue by jrogozen** [rackt/react-router#892]
Hi,

I currently have my routes set up like this:

```
var routes = (
  <Route name="app" path="/" handler={App}>
    <DefaultRoute handler={Archive}/>

    <Route name="post" path="/post/:year/:month/:day/:title" handler={Post}>
      <DefaultRoute handler={PostContent} />
    </Route>
  </Route>
);
```
Within a component I have a link that looks like this:

```
<Link to="post" params={{year: post.date.year, month: post.date.month, day: post.date.day, title: post.title}}>{post.title}</Link>
```

If I'm currently already on the "post" route, the URL will update but the content within the PostContent component won't change.

That component fetches data from a Fluxxor store like this:

```
  getStateFromFlux: function() {
    return {
      post: this.getFlux().store('post').post
    }
  },

  componentDidMount: function() {
    var params = this.getParams();
    this.getFlux().actions.posts.loadPost(params);
  },

  render: function() {
    var post = this.state.post;
    return (
      <div>
        <h1>{post.title}</h1>
        <div dangerouslySetInnerHTML={{__html: post.content}}>
        </div>
      </div>
    );
  }
```

Is there some way to tell the component that it needs to send an action to the dispatcher / store? I think that since the Route is already loaded, the component doesn't call "componentDidMount" again, even after the url change.

Thanks!

edit: To clarify a bit, if I have a list of posts within my "/" path, and they are linked to name="post", the url will change to /post/**** with the correct data in PostContent.

if I'm already in the name="post" path and click a link that updates the parameters, the URL will change to the correct /post/**** but the content within PostContent doesn't change. The component never sends an action to the dispatcher -> store that says it needs to load the new post based on the new URL params.

**Comment by jonathanpmast** [comment]
I think the solution to this is covered under the "Dynamic Routes" section of the [overview doc](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md)

Unless I'm misunderstanding, you need to implement `componentWillReceiveProps` and go fetch your data again.

**Comment by jrogozen** [comment]
Exactly what I was looking for, thanks!

**Comment by JimGorman17** [comment]
@jonathanpmast That link is broken. Is there a new link?

**Comment by knowbody** [comment]
All of the docs are [here](https://github.com/rackt/react-router/blob/master/docs/). It has a nice ToC which makes it easy to find things.

[Dynamic Routing docs](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md) are here.

**Comment by deanq** [comment]
^ Your docs are 404. It's here https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md

**Comment by fikriauliya** [comment]
It is 404 again, LOL. Here https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md

**Comment by aequasi** [comment]
Also, does not actually provide any information for this use case anymore

**Comment by nickolasacosta** [comment]
dead links again...

**Comment by Losses** [comment]
@aequasi your link disappeared again.
Why, why move the link here and there, again and again 😂

**Comment by wisetc** [comment]
I can't fix it.

**Comment by simonw** [comment]
Every single link in this thread is 404ing. Here's the most recent permalink I could find for the DynamicRouting document: https://github.com/ReactTraining/react-router/blob/c865bc6b331eabd853641dcc7e0224a7dce76f3b/docs/guides/DynamicRouting.md
