### ISSUE TITLE
Route without handler but with path

### ISSUE THREAD

**Issue by Hyra** [rackt/react-router#895]
I have an UI where a few pages show as "modal" in the page.

```
<Route name='project' path='/:owner/:projectSlug' handler={Project}>
  <Route name='project-tasks' path='tasks' handler={ProjectTasks}>
    <Route name='project-task' path=':task' handler={ProjectTask} />
  </Route>
  <Route name='project-settings' path='settings' handler={ProjectSettings} />
</Route>
```
In the Project component I have the following:

```
<TransitionGroup component="div" transitionName="modal">
    { this.getPathname().split('/').slice(-1)[0] === 'settings' ? <NavMask /> : null }
</TransitionGroup>
```

This will get triggered when the route changes to /settings, which is great, but the underlying contents/page gets replaced by what is being rendered by ProjectSettings

This makes sense, but how would one achieve the same but without the underlying page being re-rendered?

I realise I could rewrite it to work with query parameters, but i like the clean urls.

**Comment by ryanflorence** [comment]
parent route handler content isn't replaced if child routes are entered/changed. I'm confused.

**Comment by ryanflorence** [comment]
I would like having routes not require a components, I've actually done this before (though I still don't totally understand what's going on with this issue)

**Comment by mjackson** [comment]
This feature [is present](https://github.com/rackt/react-router/blob/41bd525c9209661a7ef4ea37037d35e727d595d1/modules/Router.js#L270-L271) on current master (was added in the 1.0 rewrite). There's even [a test](https://github.com/rackt/react-router/blob/41bd525c9209661a7ef4ea37037d35e727d595d1/modules/__tests__/Router-test.js#L69-L80) for it. :D
