### ISSUE TITLE
nested Redirect throws error

### ISSUE THREAD

**Issue by maxhoffmann** [rackt/react-router#896]
Having a `Redirect` in my routes setup like this:

```html
<Route name="accounts" handler={Accounts}>
  <Route path=":account" name="account" handler={Account}>
    <Route name="profile" handler={Profile} />
    <Redirect path="/accounts/:account" to="profile" />
  </Route>
</Route>
```

react-router throws this error in version >= `0.12.1`:

`Error: Invariant Violation: You cannot nest path "/accounts/:account" inside "/accounts/:account`

There is no error using version `0.12.0` though. Is this a bug or did you change the API?

**Comment by taurose** [comment]
Not sure if that's intentional or not, but this looks a lot like the scenario in #883 .

**Comment by ryanflorence** [comment]
yep, I just do this https://github.com/rackt/react-router/issues/883#issuecomment-76299927

I would merge a `<DefaultRedirect/>` though.
