### ISSUE TITLE
testLocation module no longer works in 0.12.4

### ISSUE THREAD

**Issue by azaharakis** [rackt/react-router#899]
https://github.com/rackt/react-router/wiki/Announcements

As mentioned in the guidelines here when using testLocation, for me its throwing an error
`Cannot call a class as a function`

**Comment by mjackson** [comment]
`TestLocation` is now a class instead of a singleton. You can see examples of how to use it throughout our tests. For example, [here](https://github.com/rackt/react-router/blob/e0a15ebc81d76119935fef27e0ab7d7b024b98fd/modules/__tests__/History-test.js#L17-L20).

**Comment by azaharakis** [comment]
Excellent, thanks for your help!
