### ISSUE TITLE
Feature request: Absolute pathing or base href feature request

### ISSUE THREAD

**Issue by thecaddy** [rackt/react-router#900]
Currently there is no way to use React Router to add absolute pathing, I.E. all the paths are relative

```
<a href="/">root</a>
<a href="/sub>sub</a>
```

I'd like to be able to specify something along the lines as below:

```
  <Route name="app" path="http://localhost:123/" handler={ require('./components/header') }>
  </Route>
```

or 

```
  <Route name="app" base="http://localhost:123" path="/" handler={ require('./components/header') }>
  </Route>
```

**Comment by gaearon** [comment]
How would that work? Router can't possibly match host/port because it runs on a specific page that is already served from that host/port.

**Comment by thecaddy** [comment]
I haven't taken the time to go through how react router works, but my initial thoughts are on compilation with browserify or webpack you'd pass in a base url to use for absolute pathing, in my case it was a localhost, it could be an ip and port, it could be "https://myuri.com".  This url would be used to construct all Router.Link tags.  The matching could still be performed on then 'path="/"' prop.

**Comment by gaearon** [comment]
What are you trying to accomplish? I don't understand the end goal.

**Comment by thecaddy** [comment]
You get one benefit of debatable importance, for public facing static websites you deter scrapers who would have to go through and replace the href values.

**Comment by thecaddy** [comment]
The speculative benefit is that it helps with SEO and navigating crawlers across your site.

**Comment by gaearon** [comment]
I don't think it's a real issue.

Crawlers can read any kind of URLs that browsers read, or they're bad crawlers. Wikipedia uses relative URLs everywhere and it is the top hit in search. I never heard of any search penalty for using non-absolute URLs.

There's no real benefit to doing this.

Closing, but let me know if I missed something!
