### ISSUE TITLE
qs arrayFormat configuration

### ISSUE THREAD

**Issue by willbutler** [rackt/react-router#901]
[Line 149 of PathUtils.js](https://github.com/rackt/react-router/blob/master/modules/PathUtils.js#L149) currently calls stringify with {indices: false}, which forces the qs arrayFormat to 'repeat.' It would be great if we could specify the arrayFormat when configuring react-router.

**Comment by willbutler** [comment]
It appears that this request depends on a yet to be released version of qs (v2.3.4).

**Comment by mjackson** [comment]
Yes, [I made the PR that introduced the `arrayFormat` option](https://github.com/hapijs/qs/commit/9c46a9539834560616445eeb5c529aa7412a23d5). When `qs` ships a stable release with that option we'll use `arrayFormat: "brackets"`. I'll leave this open to remind me to do it :)
