### ISSUE TITLE
Explain language-selection as topmost route

### ISSUE THREAD

**Issue by pkese** [rackt/react-router#902]
I'm trying to build a multilingual site where the language preference is part of the URL, e.g.

    http://example.com/en/<somepage>  (English)
    http://example.com/jp/<somepage>  (Japanese)
    http://example.com/../            (etc)

The language selection is supposed to be dynamic and new languages will be added as time goes (the `en` and `jp` part should be variable).

I went through documentation and examples but couldn't find such a case. How can I configure my routes in such a way? Is it documented somewhere? Was this discussed before (it seems like a common pattern used on many sites).

**Comment by gaearon** [comment]
[Overview](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md) covers nesting, although for a different use case.

Your route config might look like:

```js
var routes = (
  <Route name="app" path="/:lang" handler={App}>
    <Route name="something" handler={SomePage}/>
    <Route name="other" handler={SomeOtherPage}/>
    <DefaultRoute handler={Dashboard}/>
  </Route>
);
```

+

```
Router.run(routes, function (Handler, state) {
  React.render(<Handler/>, params={state.params});
});
```

+

```
var App = React.createClass({
  render() {
    return <RouteHandler lang={this.props.params.lang} />
  }
}
```

This way all your nested route handlers (`SomePage`, etc) will get `lang` prop.

**Comment by Maximilianos** [comment]
How does this handle the default language case, ie having:

```
http://example.com/    (english) <-- no :lang attr right?
http://example.com/fr/ (french)
http://example.com/de/ (german)
```

**Comment by Maximilianos** [comment]
I found a router setup that suggests a solution here: http://stackoverflow.com/a/35075669/1253297. 

The proposed Router config is as follows:
```javascript
var innerRoutes = (
  <Route>
    <Route path="somepage" component={Somepage}/>
    <Route path="otherpage" component={Otherpage}/>
  </Route>
);

var routes = (
  <Route path="/" component={App}>
    {innerRoutes}
    <Route path=":lang">
      {innerRoutes}
    </Route>
  </Route>
);
```

This setup works in my application as well so far, but it does feel inelegant.
Please let me know what you think of it.

**Comment by timdorr** [comment]
@Maximilianos You would get that as a param on your route components. A component at the top of your subRoutes tree could set that in some global or on `context` when it mounts or receives props.

**Comment by Maximilianos** [comment]
Hey @timdorr thanks for help. I was just looking at getting the lang from the passed props but unlike gaearon's solution, because I am not using a dynamic segment in my url for the language (no `:lang`) I don't get that bit of info passed down to my rendering components params.

The best I seem to be able to get is the `props.location.pathname` but extracting the lang from this prop seems hacky.

Is there a way to define a prop on a route that would get passed down to its children?
If not do you think using the `onEnter` hook is a valid place to set this global state?
Using redux I could potentially use something like: (I removed the map operation from the configuration to make it slighty easier to read)

```javascript
export default function createRoutes(store) {
  const subRoutes = ( ...same as above...);

  return (
    <Route path="/" component={App}>
      <Route path="fr" onEnter={() => store.dispatch(switchLang('fr'))}>
        {subRoutes}
      </Route>
      <Route path="de" onEnter={() => store.dispatch(switchLang('de'))}>
        {subRoutes}
      </Route>
      {subRoutes}
    </Route>
  );
}
```
