### ISSUE TITLE
HTML5 Mode

### ISSUE THREAD

**Issue by jrogozen** [rackt/react-router#904]
Hi,

I currently enabled HTML5 mode (want to get rid of #'s) by using this in my app.jsx

```
Router.run(routes, Router.HistoryLocation, function(Handler) {
  React.render(<Handler flux={flux} />, document.getElementById('app'));
});
```

It works, so my urls look like this:

```
http://localhost:8080/post/2015/2/22/react-js-part-two
```

However, if I try to go directly to the above url (vs clicking on a link from my root localhost url, I get a path not found. I know this is due to the way I'm setting up my routes in Express.

Currently, I'm just routing calls to '/' to send my index.html file

```
app.get('/', function(req, res) {
  res.sendFile(path.join(__dirname + '/dist/index.html'));
});
```

If I change the .get matcher to '*', I get weird console errors, like 

```
Uncaught TypeError: Cannot read property 'map' of null
```

When trying to load a component's state.

Not sure if this is the right place to post this, but I would love some help!

**Comment by grrowl** [comment]
Do you have the middleware `serve-static` (or similar) *before* your `app.get('*', function...)` middleware? Sounds like your catch-all is catching requests for javascript files too. Check the "network" tab to see what the server's returning for JS assets.

**Comment by jrogozen** [comment]
This is what I'm trying right now

```
app.use(function(req, res, next) {
  if (path.extname(req.path).length > 0) {
    next();
  }
  else {
    req.url = '/index.html';
    next();
  }
});

app.use(express.static('./dist'));
```

It looks like the index.html file is loading the correct bundle.js (i can view the file it's requesting in network tab), but I'm still getting console errors when a React component tries mapping over something / checks object values.

Thanks!

**Comment by WRidder** [comment]
@jrogozen I've implemented the same support as well. You can see a demo here: http://react-spa.herokuapp.com/

The relevant code is in the static file configuration (https://github.com/WRidder/react-spa/blob/cfd6f4d1a7ef4a797a15edababc7147bcf1435f9/server/src/config/server.js) and the *isomorphic* router +  controller which catches anything except the static files (https://github.com/WRidder/react-spa/blob/cfd6f4d1a7ef4a797a15edababc7147bcf1435f9/server/src/routes/isomorphic.js + https://github.com/WRidder/react-spa/blob/cfd6f4d1a7ef4a797a15edababc7147bcf1435f9/server/src/controllers/isomorphic.js).

If you have any questions, let me know!
