### ISSUE TITLE
Nested routes but avoid nesting handlers

### ISSUE THREAD

**Issue by natew** [rackt/react-router#905]
Basically, to "fake" nesting and keep the child handlers as siblings in my render. Is this already possible? I'd assume with something like:

```js
<Route handler={App} path="/">
    <Route name="about" path="/about/1" handler={About} />
    <Route name="aboutSub" path="/about/1/sub/" handler={AboutSub}>
</Route>
```

And then the render of App:

```
render() {
   return (
     <div>
        <RouteHandler />
        <RouteHandler />
     </div>
   )
}
```

**Comment by ryanflorence** [comment]
Route config nesting is for UI nesting, your route path name "nesting" is up to you.

- If your route path starts with `/` it will ignore the parent routes and be "absolute".
- If it does not start with `/` it will concat with the path of the parent.
- Nested `<Route/>` config will nest inside the view.

So you're right, except for the double `<RouteHandler/>` bit. Not sure what your assumptions are but you only need one and it will render the active child route's handler.
