### ISSUE TITLE
Question: react-router equivalent to Angular's named view?

### ISSUE THREAD

**Issue by yaru22** [rackt/react-router#908]
I understand that `<RouteHandler />` is equivalent to Angular ui-router's `ui-view` directive. But Angular also supports named view (e.g. `<div ui-view="view-name-1">`), which makes loading different components to different parts of the view easy (see https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views for more detail if you are not familiar)

Does react-router have something equivalent currently? If not, is there any plan to make such feature available?

Thanks!

**Comment by gaearon** [comment]
This is *not* supported now. I think it would require a big overhaul of how router works internally so I doubt that is planned for the near future.

Personally I have mixed feelings about this. Do the benefits of this model outweigh added complexity in your opinion? After all, React offers a really great composition model out of the box and you can always leverage that when you want to go “more custom” than router allows in configuration.

**Comment by apreg** [comment]
I'd love to see this implemented also. It would be useful in the given scenario for example: There is a main layout grid component with blocks/cells which could be named views and in the child page/component you could define into which block you want to render a given component.

**Comment by gaearon** [comment]
Yeah. From what I've heard, Relay folks want this too in order for RR to work with it. I figure the next big RR release will need to support this, but I can't give you any timeframe on this.

**Comment by apreg** [comment]
Thx for the info.

**Comment by ryanflorence** [comment]
#1008
