### ISSUE TITLE
a slash in a dynamic segment

### ISSUE THREAD

**Issue by stopachka** [rackt/react-router#910]
Hey everyone, I have an app that allows users to enter various types of sentences. Each sentence has it's own page. 

```coffeescript
   (Route name: "eval/:q", handler: HanderClass)
```

When users enter a sentence that has a / in it, react-router gets confused. Has this ever been encountered before, and is there a nice solution to it?

**Comment by WRidder** [comment]
One option may be to create slugs from those titles. This basically means stripping certain characters from the sentence in your case, thus removing slashes for example. 

I am using the following function at the moment: https://github.com/WRidder/react-spa/blob/master/src/helper/slug.js

**Comment by ryanflorence** [comment]
use a splat:

```coffee
(Route name: "eval/*", handler: HanderClass)
```

then access on `params.splat` instead of `params.q`.
