### ISSUE TITLE
Example or standalone component

### ISSUE THREAD

**Issue by iamdustan** [rackt/react-router#912]
I wrote this thing that automatically generates our navigation by using ReactRouter’s `getRoutes` method. My question is do you think this would better serve as an example in this repo or should I flesh it out and release it standalone?

Implementation is here: https://gist.github.com/iamdustan/12f69c9cf3aeb6a64a70

The following code creates the following screenshot:

```javascript
var ROUTES = (
    <Route handler={App} path="styleguide">
      <DefaultRoute name="Welcome" handler={Home} />
      <Route path="components">
        <DefaultRoute name="Components" handler={Components} />
        <Route name="Task item" path="task-item" handler={Components.TaskItem} />
        <Route name="Scrollable" path="scrollable" handler={Components.Scrollable} />
        <Route name="Logo" path="logo" handler={Components.Logo} />
      </Route>
      <NotFoundRoute handler={NotFound} />
    </Route>
);


var App = React.createClass({
 render(): ?ReactElement {
    var routes = this.getRoutes();
    var routeName = last(routes).name;
    // ignore the root app, this is only for the styleguide
    var ROUTES = routes[1];

    return (
      <App>
        <Toc routes={ROUTES} width={this.state.leftPosition} />
          <div className="Content" style={{paddingLeft: this.state.leftPosition + 'px'}}>
            <RouteHandler />
          </div>
      </App>
    );
  }
});
```

![screen shot 2015-03-05 at 10 54 28 am](https://cloud.githubusercontent.com/assets/227879/6508303/0c0d6782-c326-11e4-8415-20e08872b900.png)

**Comment by ryanflorence** [comment]
That's cool. I'd merge a pull request, I'll probably tweak it a bit, but yeah, send a pull request.

(closing, in favor of a PR :)
