### ISSUE TITLE
Navigation.getRouteName()

### ISSUE THREAD

**Issue by eriklharper** [rackt/react-router#914]
In addition to the Navigation mixin's `getPathname()` function, it would be nice to also be able to get the current route's name as well.  Any plans to implement this?

**Comment by johanneslumpe** [comment]
Afaik the mixins are going to get deprecated soon, as you can already see in https://github.com/rackt/react-router/blob/master/modules/Navigation.js

The preferred way is to use `this.context.router` to access that type of functionality now. So maybe you could then use the `match` function to retrieve a set of matching routes and extract the actual name from there. Here is a little helper function for that:

```javascript
function getRouteName(router, path) {
  const match = router.match(path);
  if (match) {
    return match.routes[match.routes.length-1].name;
  }

  throw new Error('No route matched the path');
}
```
And then you could just use it like this:

```javascript
// inside one of our components methods
const router = this.context.router;
const routeName = getRouteName(router, router.getCurrentPathname());
```

I know this is not a real answer to your question, but maybe it helps to get you by in the meantime.

**Comment by andru** [comment]
Thanks for the workaround.  I'd also be super interested in seeing this make it as a helper method on the Router.

**Comment by eriklharper** [comment]
While perusing some of the examples, I came across this useful little nugget that I think @ryanflorence may have written originally that grabs the name attribute for the current route: `this.getRoutes().reverse()[0].name`.  I created my own little function to wrap that guy:

```
getCurrentRouteName: function() {
    return this.getRoutes().reverse()[0].name;
}
```
That's all I ended up needing in the end, simple one-liner.  Love when that happens!

**Comment by andru** [comment]
Yeah I found the same thing and have been using it but it sometimes returns undefined. I'm not quite sure why; I've just been putting up with it for now.

**Comment by taurose** [comment]
I think that's because the routes array is never trimmed. When you switch to a path that has less routes, the last element will be undefined or null. Example:

1. path: "/", routes: [AppRoute]
2. path: "/about", routes: [AppRoute, AboutRoute]
3. path: "/", routes: [AppRoute, null]

You could try filtering the falsy routes before calling reverse().

**Comment by ryanflorence** [comment]
eww, we should be returning a new fresh array each time w/o null values

**Comment by ryanflorence** [comment]
I just confirmed, we are returning a new array (at least on master).

Note, you can also get the routes in `Router.run(routes, (Handler, state) => state.routes)`

**Comment by taurose** [comment]
Right. I must have mixed that up with our mountedComponents array.
