### ISSUE TITLE
Convert testing.md to use ES5

### ISSUE THREAD

**Issue by toolness** [rackt/react-router#918]
I found the incredibly helpful [React Router Testing](https://github.com/rackt/react-router/blob/master/docs/guides/testing.md) guide but am not well-versed in ES6, so it took me a while to figure out how to make it work in ES5.

As far as I can tell, all the other documentation in react-router uses ES5... Would you accept a PR that converted `testing.md` to use ES5 instead of ES6?

No worries if not, just trying to make things easier for others who might not yet know or use the still-evolving ES6 standard.

**Comment by ryanflorence** [comment]
going to move everything to ES6, actually :) Lets move forward, not backward :)

**Comment by james-gardner** [comment]
More like sideways, isn't it.

**Comment by taion** [comment]
Please don't comment on ancient, closed issues unless you have something to add.
