### ISSUE TITLE
Redirect from default route

### ISSUE THREAD

**Issue by bigblind** [rackt/react-router#920]
Is there a way to do something like this?

    <Route name="app" path="/" handler={App}>
        <Route name="chat" path="/rooms/:roomSlug" handler={Chat} />
        ....
    <Redirect from="/" to="chat" para=s={{roomSlug:"general"}} />
    </Route>

It doesn't seem to work.

**Comment by benstokoe** [comment]
That works for me.

Not sure if copy and paste error but params is misspelt in the redirect, maybe that could be the problem?

**Comment by bigblind** [comment]
Yep, I had some other mistake.

**Comment by lalitmee** [comment]
Hello Guys, 
I want my homepage rendering with some path like `/some-path`. It will be dynamic. I don't know how to do this. I am trying to do but no luck.

- **routes.js**
```
<div>
<div>
    <App>
      <Route component={ScrollToTop} />
      <Route path="/" exact component={HomePage} />
      <Route path="/merchants" component={MerchantsPage} />
      <Route
        path="/terms-of-service"
        component={TermsOfService}
      />
      <Route
        path="/privacy-policy"
        component={PrivacyComponent}
      />
      <Route
        path="/faqs"
        component={FaqComponent}
      />
    </App>
  </div>
```
Can you help me? :innocent:
