### ISSUE TITLE
please don't depreciate mixins

### ISSUE THREAD

**Issue by jquense** [rackt/react-router#925]
It seems like the navigation and state mixins are being deprecated? I know 0.13 brings es6 class compatible components, but createClass isn't being deprecated (as far as I know) and neither are mixins for those using it. It would be easy enough to recreate the mixins myself but it seems like an unnecessary migration and the maintenance coat of y'all keeping them around seems minimal.

I realize that there isn't a specific solution from the react team but needing to declare context types and direct access to the router feels like leaky implementation details. Its certainly a matter of preference on y'all's part. but it could be migration path win for those of us continuing to use createClass post 0.12 :)

**Comment by gaearon** [comment]
Personally I think having the same way to access router in ES6 classes and `createClass`-style classes is very convenient and important.

I feel that router being on context is no longer an implementation detail, but integral part of how router works, and we have to educate people about `context` now. This also makes router less magical. Once React 0.14 “fixes” context, this will be even more “official”.

I know it's a weird transition phase but I think we can manage it well if ES6 and old style components explicitly use context without additional magic or abstraction around it.

**Comment by jquense** [comment]
I can appreciate that rational :) I guess it feels weird to me to have consumers explicitly declare `contextTypes`, but this may just be b/c the current pattern is to hide that behind a mixin (in most libs). It also exposes the users directly to an undocumented, and unfinished API as well, but perhaps practically that isn't any different than the way it is now.

I am just dealing with what feels like an unnecessary migration burden, in light of the continued support of `createClass`. But I can appreciate the value in only having one way to talk about propagating router state. 

The switch to plain classes by React feels really premature for use by normal react consumers, considering that there seems to be a suggestion that the ecma spec will handle the missing pieces (in what, 4 years?). It seems like that was mostly a feature for things like OM, I didn't expect vanilla react consumers to switch so soon, but I do see how ya'll have to support whatever React does.

**Comment by mjackson** [comment]
`context` was invented to support routing. We should be using it instead of mixins.

**Comment by AsaAyers** [comment]
Thanks for un-depricating the mixins. https://github.com/rackt/react-router/commit/e5ad53ba1e377d92c8f416b9c5a96efc285b2bc7

You were so set on depricating them that I was curious where the discussion happened that changed your mind. I can't seem to find it.

**Comment by mewben** [comment]
So will this mean that we should not use ES6 style yet?

**Comment by jquense** [comment]
@mewben no it just means that those of us who are still using `createClass` can use mixins. If you are not using `createClass` then nothing changesyou still declare `contextTypes` and use `this.context.router`

**Comment by mewben** [comment]
Ahhh... Okay. Thanks @jquense
