### ISSUE TITLE
Meta attributes inside Route?

### ISSUE THREAD

**Issue by mikechau** [rackt/react-router#927]
I'm building breadcrumbs for my application and I think it would be really helpful for a Route to have a sort of `meta` property, where you could give it whatever attributes you want.

For example:
```
<Route name="profiles" path="/profiles" meta={{ breadcrumbName: 'Company Directory', icon: 'phonebook' }} />
```

Then you could just iterate over `this.getRoutes()` and do whatever you need to do. I think it would be much more convinent for simple cases then maintaining a seperate `store` that has mappings for each route by `name`. Or is using a `store` with a mapping to the route names preferred?

#492 @irvinebroque

**Comment by taurose** [comment]
Using a (global, immutable) name-props mapping is probably what I would do.

If you don't plan on using handlers for multiple routes, you could also consider putting those props on the handler statics and then do `routes[0].handler.myProp`. Finally, you could also wrap your handlers in a function as suggested in the [Upgrade Guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#route-props-passed-to-handlers). 

There's another discussion about this in #615.

**Comment by malte-wessel** [comment]
+1

**Comment by malte-wessel** [comment]
I made a PR: #1002

**Comment by ryanflorence** [comment]
You can put that meta data on your handlers:

```js
<Route name="profiles" path="/profiles" handler={Profiles} />

class Profiles extends React.Component {
  render () {
    var { icon } = this.constructor.breadcrumbs;
  }
}

Profiles.breadcrumbs = {
  breadcrumbName: 'Company Directory',
  icon: 'phonebook'
};
```

**Comment by ryanflorence** [comment]
oh, sorry @taurose I jumped straight to the comment box and missed yours!

**Comment by ivan-kleshnin** [comment]
> You can put that meta data on your handlers

Most HOC builders entirely block access to original component, therefore to static. 
We really need to reopen this issue.
