### ISSUE TITLE
server side routing example is incomplete

### ISSUE THREAD

**Issue by funkjunky** [rackt/react-router#928]
https://github.com/rackt/react-router/blob/master/docs/guides/server-rendering.md

There is no view engine, so it errors. I wasted time looking up how to render react view in express, and now I realize I should just use an html engine, and not worry about react for the index page.

Although I'm still unsure if this is the best option. Could you guys update this example with the simplest possible fully working example?

**Comment by benjie** [comment]
You can use any template engine you like, just putting the `content` variable in as unescaped HTML, e.g. in handlebars you could use something like

```handlebars
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My App</title>
  </head>
  <body>
    <div id='react-root'>{{{content}}}</div>
    <script src="/bundle.js"></script>
  </body>
</html>
```

**Comment by johanneslumpe** [comment]
Or you could use an actual react component as wrapper and then use `React.renderToStaticMarkup` to generate your page. No need for a separate templating engine.

**Comment by benjie** [comment]
If you do that, don't forget to add the doctype to the rendered string.

**Comment by johanneslumpe** [comment]
great point @benjie thanks for mentioning that :)

**Comment by ryanflorence** [comment]
@johanneslumpe would be great if that doc was copy/pastable but there are so many other things to consider when creating an express server, even simple stuff like what the name of your app bundle is. 

The doc merely provides the concepts. I think this line implies that a different rendering engine is in play:

`res.render('main', {content: content});`

Perhaps we should link to https://github.com/rackt/react-router-mega-demo in the doc.

**Comment by johanneslumpe** [comment]
@ryanflorence I think you meant to mention @benjie - I'm advocating the use of a React component, which gets rendered to static markup.

**Comment by benjie** [comment]
Probably @funkjunky actually ;)
