### ISSUE TITLE
Multiple optional segments

### ISSUE THREAD

**Issue by LKay** [rackt/react-router#929]
I couldn't find that in the docs. Is it possible to define a single route which has multiple optional segments? Let's say I have a list with optional sorting and pagination so I'd like to define route like: `/list?(/s/:sort?(/:order)?)?(/page/:page)?`. The other thing is matching segments by RegExp, so in the above example the parameter `:order` could only have values `asc` or `desc`. From what I found in Issue #142 there was no matching feature implemented, is that right? For now I ended up with defining 4 different routes pointing to the same handler depending on uri, which is not the optimal solution...

**Comment by johanneslumpe** [comment]
Yes correct, there is no support for matching using regular expressions currently. I'm not sure about this, but I think you cannot have multiple dynamic segments. A possible solution would be to just move the optional params like sorting and pagination into query params, because they are actually part of a query, not directly of the URI.

**Comment by ryanflorence** [comment]
You can always do whatever crazy stuff you want in splat paths anywhere in the hierarchy.

```js
<Route path="list" handler={List}>
  <Route path="*" handler={GoNuts/>
</Route>

class GoNuts extends React.Component {
  render () {
    var stuff = parseThatCrazyUrl(this.context.router.getCurrentPath());
    // do some branching on stuff to render what you want
  }
} 
```

**Comment by ivan-kleshnin** [comment]
> A possible solution would be to just move the optional params like sorting and pagination into query params, because they are actually part of a query, not directly of the URI.

And loose the ability to bookmark :(

**Comment by elyobo** [comment]
@ivan-kleshnin Why would you lose those?  If they're in the query params then they're still in the URL, so are bookmarkable and shareable.
