### ISSUE TITLE
Capability for full page rendering (HEAD, META, etc)

### ISSUE THREAD

**Issue by geekyme** [rackt/react-router#930]
Hello, 

I have an isomorphic setup and I want to handle rendering different meta tags / title tags on different pages. Is there a way to do this with react-router? 

Something like how react-router-component is doing with their full page rendering? http://strml.viewdocs.io/react-router-component/server-side

**Comment by taurose** [comment]
Have you tried wrapping the `Handler` from the run callback: `React.renderToString(<html><head>..</head><body><Handler /></body></html>);`? As for assembling the meta data, you can make use of the state param. There's a related issue #927.

**Comment by irvinebroque** [comment]
See:

https://github.com/gaearon/react-side-effect
https://github.com/gaearon/react-document-title/issues/5#issuecomment-78040599

These approaches solved my use cases. I haven't revisited it in awhile, but I imagine the move away from mixins, towards using context, will resolve what I ran into in #492 as well.

**Comment by ryanflorence** [comment]
not really related to the router, so I'm closing, great links :)
