### ISSUE TITLE
Get active routes outside react component

### ISSUE THREAD

**Issue by nickdima** [rackt/react-router#934]
Is it possible in some way?
I want to avoid calling some static methods for fetching data on parent components when only a child route changes.

**Comment by johanneslumpe** [comment]
The router has a `getCurrentRoutes` method, which returns the currently active routes. That should probably fit your needs.

**Comment by ryanflorence** [comment]
> I want to avoid calling some static methods for fetching data on parent components when only a child route changes.

Yeah, I've been thinking about how we could tell you what the "pivot" route is, for now I just make sure my data fetches are cached so that it isn't an expense.

You can create your own diff on the matched routes though:

```js
var lastRoutes = [];
Router.run(routes, (Handler, state) => {
  var newRoutes = getNewRoutes(lastRoutes, state.routes);
  lastRoutes = state.routes;
  fetchData(newRoutes).then(...);
  // etc.
});
```

Then your data fetching only looks at statics on the new routes
