### ISSUE TITLE
How to see url changes in examples included?

### ISSUE THREAD

**Issue by sunglee** [rackt/react-router#938]
Quick question about included examples code.
I downloaded the react-router zip file and run "npm install" and "npm run examples" as the doc said.
I am able to see the example pages from web browser but none of them shows url changing.

For example, I can see this page on
http://localhost:8080/webpack-dev-server/simple-master-detail

but when I click a state in the page, browser url doesn't change at all.
Please help what I am missing. Thank you.

**Comment by taurose** [comment]
Go to http://localhost:8080/simple-master-detail instead.

/webpack-dev-server/ runs in an iframe.

**Comment by sunglee** [comment]
Awesome. Thanks! :+1:
