### ISSUE TITLE
Server side redirection

### ISSUE THREAD

**Issue by dazld** [rackt/react-router#947]
I'm having a slightly hard time figuring out how (or if) react-router supports the concept of redirection on the server.

If I have a static willTransitionTo as follows:

```

willTransitionTo: function(transition, params, query, callback){
            if (!params.lang || params.lang === 'en') { // or whatever
                // throw new Error('no link');
                transition.redirect('/de');
            } else {
                callback();    
            }
        }

```

..then, currently the router hangs on the server if the redirect call is made for `/`or `/en`.

 `/de` as a route is rendered fine.

I've tried adding both `onError` and `onAbort` handlers when the router is created on the server, but neither is called. I was guessing that the abort handler would be called on the server, which I could then do something with via express (for example) - but perhaps I'm missing something.

Any advice?

**Comment by dazld** [comment]
Nevermind! Wasn't calling the callback. Simple things :)

**Comment by kjs3** [comment]
@dazld Can you post a little more info on how you got this to work?
Here's what I'm trying and it works fine in the browser but I get an internal server error on the server.

```
statics: {
  willTransitionTo: function (transition, params, query, callback) {
    transition.redirect('/');
    return callback();
  }
}
```

I get the following error in the console.

```
Error: Unhandled aborted transition!
```

**Comment by dazld** [comment]
@kjs3 you need to do something like this:

https://github.com/dazld/react-router-fetch-data-demo/blob/master/server/index.js#L40-L44

**Comment by dazld** [comment]
ie, it sounds like you are not setting up an `onAbort` handler on the server...?

**Comment by kjs3** [comment]
@dazld Fantastic, thank you! That whole demo project is great.

So, redirect and abort are handled as you would expect in the browser but are identical server-side?
Docs are hazy on this.

**Comment by dazld** [comment]
Thanks! It's not 'perfect' yet, but it's going vaguely in the right direction. Glad it was useful!

About the handlers - yes, so far as I've needed it, they work in the same way, with the proviso that on the server you are clearly not running a continuous application (although.. if the state doesn't change, then the markup doesn't change.. which is another issue to think about for optimisation perhaps.. hmm..) so - redirection is by sending headers vs setting document location or whatever on the browser. 

That's one of the few places where the code really severely branches, but a well designed isomorphic app handles this through abstractions. I suppose the `react-router` team chose the approach they did for exactly these reasons. The docs could use a better full on isomorphic example, but there are so many ways to do it, with so many caveats that it would be very hard to present a 'canonical' way of approaching it all. 

Maybe if we invoke @ryanflorence he could provide some insight ;) not sure if they have such an example in mind..?

**Comment by dazld** [comment]
https://gist.github.com/dazld/c1f81fd398a0f2abdaee < current approach after reading about how others are fetching data. Indicating which store is currently loading could be done too with some kind of hook on the client, for show loading spinners or so on. Anyway, something like this.
