### ISSUE TITLE
How can I do an initial, on server render, populated with data from the stores?

### ISSUE THREAD

**Issue by andre0799** [rackt/react-router#949]
I'm using react-router with reflux. The thing is if I disable javascript the page doesn't render at all. What I wanted is the first render to be made on the server, and the serve the page with all the content that came from the api.

Thanks!

**Comment by andre0799** [comment]
Right now I'm doing this:

```javascript
 statics: {

    willTransitionTo: function (transition, params, query) {
      var self = this
      console.log(' ### willTransitionTo ###')
      transition.wait(
        featuredActions.request().then(function(){
        
        })
      );
    }

  },

```

but I get "Uncaught TypeError: undefined is not a function" for transition.wait

**Comment by andre0799** [comment]
I got this going. But the problem is I'm almost sure that is not being done on the server.

```javascript
statics: {

    willTransitionTo: function (transition, params, query) {
      var self = this
      console.log(' ### willTransitionTo ###')
      featuredActions.request().then(function(){
        console.log('callback');
      });
    }

  },

```

**Comment by johanneslumpe** [comment]
In order for the transition to wait you need to use the 4th argument (missing in your function), which provides a callback. That callback can be used to tell the transition to continue. If it's not present in your arguments list, then react-router will call the callback for you. As this happens synchronously, your request won't be finished.

**Comment by kedashoe** [comment]
Hi @andre0799. As @johanneslumpe mentions, to do anything async, you'll need to accept that 4th parameter in your callback, ie

    statics: {
        willTransitionTo: function (transition, params, query, cb) {
            var self = this
            console.log(' ### willTransitionTo ###')
            featuredActions.request().then(function(){
                cb();
            });
        }
    }

However I believe (I am brand new to react and react-router, please someone correct me if I've got this wrong) the bigger problem may be `var self = this`. [statics](http://facebook.github.io/react/docs/component-specs.html#statics) will not have the `this` scope of the react class. This can be worked around, but I think is not ideal as you'd like to have access to `state`, etc.

Is there a preferred way to run async operations on the server? If there is not, how might I access the actual react class after routes are run before rendering? With something like

    Router.run(routes, req.path, (handler, state) => {
        let elem = React.createElement(handler);
        ...
        let component_html = React.renderToString(elem);

Can I get access to the classes in the current route from `handler` or `elem`? I tried inspecting the objects but it was not immediately clear to me. Thanks!

**Comment by ryanflorence** [comment]
we're all figuring out isomorphic apps. I don't know how to do it with your app, but I've got this demo that doesn't rely on anything to simply show all the touch points the router is involved with an isomorphic app. I hope it can help you figure things out :)

https://github.com/rackt/react-router-mega-demo
