### ISSUE TITLE
share react routes with express?

### ISSUE THREAD

**Issue by samsel** [rackt/react-router#953]
I am build a Single page app that gets rendered on the server first and then client picks up the state and takes over navigation etc.. 

Having said that, I want to share the routes that I am declaring in the react-router with my express router, so that I can tell express router that `hey! these are all the react routes and you need to run this express  middleware function for them.`  without duplicating the route info on express side.

The essence is I want the declared react-router routes to be shareable with the express router. Is it possible?

is this even relevant to the question? :smile: 
https://github.com/rackt/react-router/pull/382

**Comment by johanneslumpe** [comment]
Maybe you can use the function I posted as solution for #885 for this? It will extract the paths for a given set of routes and return them as an array. You could then use that array to build your express routes.

**Comment by samsel** [comment]
@johanneslumpe: thanks! that is what i was looking for.
