### ISSUE TITLE
HashLocation does "pop" with transition.redirect()

### ISSUE THREAD

**Issue by zupzup** [rackt/react-router#958]
I'm building a hybrid (phonegap) app at the moment using react and react-router. From what i gathered (https://github.com/rackt/react-router/issues/310), this means, that I need to use Router.HashLocation, because the app runs on the filesystem.

Is that still correct?

If so, I think I found a problem with the redirect-handling of HashLocation.

The use-case:
A simple auth-flow, where the user is redirected to the login page using the willTransitionTo hook.

```javascript
willTransitionTo(transition) {
    let nextPath = transition.path;
    if (!transition.context.getActionContext().getStore(AuthStore).isLoggedIn()) {
        transition.redirect('/login', {}, {'nextPath': nextPath});
    }
},
```

Now, the problem is, that **HashLocation** internally does a push first, and then a replace, same as HistoryLocation, but it does so using **window.location.replace**, which is then handled via the **onHashChange** event, which is asynchronous.

Because of this, there seems to be a race-condition, where the **_actionType** gets set to null for the "push" [here](https://github.com/rackt/react-router/blob/master/modules/locations/HashLocation.js#L40), right before the "replace"'s notifychange gets triggered, which results in the replace getting propagated as a "pop" [here](https://github.com/rackt/react-router/blob/master/modules/locations/HashLocation.js#L39), which is wrong and makes back-handling almost impossible, as it is a faulty pop-event.

I fixed this locally by resetting the _actionType to null asynchronously in the next tick. This works in all the cases relevant for my app. Can you think of any situations, where this could cause problems?

regards,
mario

**Comment by taurose** [comment]
Thanks for the detailed report :+1: 

The way I understand it, this should be a more reliable solution:

```js
function onHashChange() {
  if (ensureSlash()) {
    var curActionType = _actionType;
    _actionType = null;
    notifyChange(curActionType || LocationActions.POP);
  }
}
```

Can you try and see if that fixes your issues as well?

**Comment by mjackson** [comment]
@taurose Ah, ya. That should work. :)

@zupzup Can you give it a go and see if it resolves your issue? Thanks!

**Comment by zupzup** [comment]
@mjackson @taurose: works like a charm :)

**Comment by mjackson** [comment]
Awesome. Anyone wanna put up a PR?

**Comment by zupzup** [comment]
I'd be happy to if @taurose isn't already on it :)

**Comment by taurose** [comment]
I'm not; feel free to :smile:

**Comment by zupzup** [comment]
alrighty
