### ISSUE TITLE
Get rid of ? in paths

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#960]
Using a `?` in path definitions has limitations. For example, if you want to match a path that has an optional segment in it, you actually need two of them: one for the parameter name and another for the slash. So people end up using paths like `/users/:userID?/?edit`.

I'd like to suggest that instead of `?` we use `(` and `)` to indicate that portions of a path are optional. This gives us the ability to indicate where the optional portion of a path begins and ends. So you can do `/users(/:userID)/edit` which, at least to me, is a little cleaner.

This may help us address #820 

See also #929

**Comment by BerkeleyTrue** [comment]
+1 adds readability IMHO. I hate this `?:someParam?` it reminds me of this "¿ por que ? ".

**Comment by jquense** [comment]
so... backbone router syntax? +1 I much prefer `( )` to `?`

**Comment by johanneslumpe** [comment]
Looks definitely cleaner, because the visual grouping going on there! :+1:

**Comment by ryanflorence** [comment]
Or kill it altogether and allow route configs w/o handlers to simply configure a route to match. Any use-case for optional segments can be solved with child route configs.

```xml
<Route name="foo" path="/foo(/:id)" handler={Foo}/>

<!-- can already be handled with -->

<Route name="foo" path="/foo" handler={Foo}/>
  <Route name="fooWithId" path=":id">
</Route>
```

You don't need a handler on `fooWithId`, `Foo` can just not ever render a `RouteHandler` and do the same parameter branching it does already w/ optional params. Removing optional params would also clean up our path matching and active link className code simpler. I think it also makes user code clearer.

**Comment by jquense** [comment]
Personally I'd really prefer keeping a path syntax for optional parts.

```jsx
<Route name="foo" path="/foo" handler={Foo}/>
  <Route name="fooWithId" path=":id">
</Route>
```
seems unnecessarily verbose, and I find it harder to grok quickly compared to: `/foo(/:id)`...take that with as much weight as appropriate for anecdotal aesthetic opinions from strangers.

I definitely see how it would make your lives easier to be able to remove some complexity from path matching. If i'm being honest though, I'd prefer you folks handle the complexity instead of me :P

**Comment by ryanflorence** [comment]
The thing I don't like is this:

```js
<Route name="foo" path="/foo(/:id)" handler={Foo}/>

// ...

// URL is `/foo/123`
<Link to="foo">do I have the active class?</Link>
<Link to="foo" params={null}>do I have the active class?</Link>
<Link to="foo" params={{id: 123}}>do I have the active class?</Link>
<Link to="foo" params={{id: 234}}>do I have the active class?</Link>
```

**Comment by rowbare** [comment]
I like the idea of killing off the magic characters. Using child routes, while more verbose, is clean, readable and declarative. It think it will also be a bit more intuitive when using Redirect to set default paths. I think it will ultimately make for more maintanable code which is more important that saving a few keystrokes initially.

**Comment by theaqua** [comment]
@mjackson when it'll be released?
