### ISSUE TITLE
Find a way to pass additional context to willTransition* hooks (isomorphic flux)

### ISSUE THREAD

**Issue by stefanoverna** [rackt/react-router#961]
[The react-router guide](docs/guides/flux.md) does not cover the scenario of isomorphic Flux implementations (ie. flummox/fluxible), where stores, dispatchers and action creators are not singletons, but instances.

Just to give some context, this is a pretty standard server-side setup with ie. flummox:

```
var app = express();
app.use(...);

app.get(/.*/, (req, res, next) => {
  var flux = new Flux();

  var onAbort = function(abortReason) {
    if (abortReason instanceof Cancellation) {
      return;
    } else if (abortReason instanceof Redirect) {
      res.redirect(this.makePath(abortReason.to, abortReason.params, abortReason.query))
    } else {
      res.redirect('/');
    }
  };

  var router = Router.create({
    routes: routes,
    location: req.url,
    onAbort: onAbort
  });

  router.run(function (Handler, state) {
    var renderedApp = React.renderToString(<Handler flux={flux} {...state.params} />);
    var html = template.replace("%CONTENT%", renderedApp);
    res.send(html);
  });
});

app.listen(process.env.PORT || 3000);
```

As you can see, a new Flux instance is created for each request: the specific Flux instance is then passed down to the Handler, to make it available everywhere. 

Everything works great, except the willTransitionFrom/willTransitionTo hooks. The guide suggests [this kind of pattern](docs/api/components/RouteHandler.md):

```js
    willTransitionTo: function (transition, params) {
      if (!auth.isLoggedIn()) {
        transition.abort();
        auth.logIn({transition: transition});
        // in auth module call `transition.retry()` after being logged in
      }
    },
```

Unfortunately, with isomorphic flux there's no `auth` singleton, but rather something like this:

```js
statics: {
    willTransitionTo: function (transition, params) {
      var flux = ???;
      var auth = flux.getStore('auth');
      if (!auth.isLoggedIn()) {
```

In other words, we need to find a way to pass the flux instance to hooks, or otherwise it's impossible to build any kind of logic. I'm not sure what could be the most elegant way to solve the problem, but one possible way is to add an additional `context` property to `Transition` objects:

```js
function Transition(path, retry, context) {
  this.path = path;
  this.abortReason = null;
  this.context = context;
  // ...
}
```

And let the developer fill it with everything they need with an additional option on `Router.create` (in my example I've called it `buildTransitionContext`):

```js
app.get(/.*/, (req, res, next) => {
  var flux = new Flux();

  var router = Router.create({
    routes: routes,
    location: req.url,
    onAbort: /* ... */,
    buildTransitionContext: function() {
      return { flux: flux };
    }
  });
```

This way it would become trivial to access the flux instance:

```js
statics: {
  willTransitionTo: function (transition, params) {
    var flux = transition.context.flux;
    var auth = flux.getStore('auth');
    if (!auth.isLoggedIn()) {
```

The change to react-router would be extremely easy to make:

```js
  // this line on react-router/lib/createRouter.js...
  var transition = new Transition(path, this.replaceWith.bind(this, path));

  // becomes...
  var transition = new Transition(path, this.replaceWith.bind(this, path), options.buildTransitionContext());
```

Is this a good idea? I'm willing to make a PR out of this issue, if someone gives me a :+1: on the proposed direction.

**Comment by joemcbride** [comment]
Same basic idea as https://github.com/rackt/react-router/pull/590

**Comment by stefanoverna** [comment]
exactly the same idea as #590, indeed. thanks for pointing that out @joemcbride :cocktail:
