### ISSUE TITLE
Dynamic props to layout-component based on handler component

### ISSUE THREAD

**Issue by henit** [rackt/react-router#963]
I have been looking for a solution to an app-structuring issue. I just created a post explaining the details here:

http://stackoverflow.com/questions/29092680/reactrouter-props-from-handlers-to-header

I appreciate any help.

**Comment by ryanflorence** [comment]
I'd like to add multiple handlers per route so you could do something like `<RouteHandler for="header"/>` and be able to do the automatic view nesting with your routes in multiple sections of your UI, where right now there's only one.

You can still do what you need to do though, it just takes quite a bit of imperative code. Check out the sidebar example https://github.com/rackt/react-router/blob/master/examples/sidebar/app.js#L85.

The parent component inspects the route information and passes it as props to the sidebar, and then it responds.

**Comment by ryanflorence** [comment]
#1008
