### ISSUE TITLE
Question: Is it possible to use one path with different handlers?

### ISSUE THREAD

**Issue by arthurpark** [rackt/react-router#966]
I was wondering if I can use ```path="/"``` for logged in state and logged out state, Like twitter website. Is this possible with react-router?

**Comment by johanneslumpe** [comment]
This does not necessarily have something to do with `react-router`. You can of course just use a single handler for `/`. Inside that handler you can check in your auth lib, your stores, or whatever, whether your user is logged in or not, and then render a nested component based on that.

And if you need to make sure that a user is authenticated inside a nested route, then you can use the `willTransitionTo` hook for that and redirect, if the user is not authenticated.

**Comment by arthurpark** [comment]
Got it. Thx!
