### ISSUE TITLE
Question: handling browser back button

### ISSUE THREAD

**Issue by morenoh149** [rackt/react-router#967]
I'm developing for mobile so getting the back button working is pretty important.
I found you can detect it with
```
window.onpopstate
```
it's passed an event with the following format
![screenshot 2015-03-18 13 08 09](https://cloud.githubusercontent.com/assets/587438/6718282/daae46da-cd6f-11e4-9876-db11a606acda.png)

Any ideas how I can hook this object up to react-routers state management? I think it'd be great to just call whatever code is called when a `Link` component is clicked.

**Comment by BerkeleyTrue** [comment]
in createClass spec using the navigation mixin

```js
onBackButtonEvent:(e) => {
  e.preventDefault();
 this.goBack();
}

componentDidMount: () => {
  window.onpopstate = this.onBackButtonEvent;
}
```

**Comment by morenoh149** [comment]
awesome. `goBack()` didn't work for some reason so I went with `transitionTo()`
here's the code
```
var ChatRoom = React.createClass({
  mixins: [State, Navigation],

  onBackButtonEvent: function (e) {
    debug('handling back button press')
    e.preventDefault()
    this.transitionTo('chatrooms')
  },

  componentDidMount: function() {
    window.onpopstate = this.onBackButtonEvent
  },

  render: function() {
    return (
    // jsx
    )
  }
})

module.exports = ChatRoom
```

**Comment by hckrmoon** [comment]
In this [document](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) says, the popstate event is not cancellable. 


> Specification: HTML5
> Interface: PopStateEvent
> Bubbles: Yes
> Cancelable: No
> Target: defaultView
> Default Action: None

**Comment by ccorcos** [comment]
`window.onpopstate` gets called when going forward as well

**Comment by probablycorey** [comment]
Do we still need to listen to `window.onpopstate` to handle pressing the back button in react-router? Or is there a different way to handle this now?

**Comment by viru9** [comment]
componentDidUpdate(){
  
	window.onpopstate  = (e) => {
		//your code...
	}
  
    }

**Comment by morenoh149** [comment]
@probablycorey unless otherwise noted, it's the same
