### ISSUE TITLE
there is no `componentWillUnmount` called, is this right?

### ISSUE THREAD

**Issue by teamrun** [rackt/react-router#970]
when i route to different handlers, some of handler's life-circle methods are called, some are not:

routes: 

    <Route name="app" path="/" handler={App}>
        <DefaultRoute name="cal" handler={Calendar} />
        <Route name="list" handler={List} />
        <Route name="photo" handler={Photo} />
    </Route>

handler renders here: 

    var name = this.getRoutes().reverse()[0].name;
    var navNodes = navItems.map(function(item, index){
            return <li key={index}><Link to={item.toLowerCase()} >{item}</Link></li>;
    });
    return (
    <div className="app">
        <nav>
            <ul>
                {navNodes}
            </ul>
        </nav>
        <main>
            <RouteHandler key={name}/>
        </main>
    </div>
    )

i set break points at Calendar component, got these result. 

* page load and first time route to this handler:  `getDefaultProps, getInitialState, componentDidMount` were all called
* switch to another handler: Calendar component's `componentWillUnmount` is **not** called
* switch back to Calendar handler: `getInitialState, componentDidMount` called, `getDefaultProps` not called.

is there a special strategy to call component life circle methods?

**Comment by teamrun** [comment]
read the react doc again, understand why getDefaultProps only called once:
> getDefaultProps: Invoked once and cached when the class is created.

**Comment by teamrun** [comment]
so there is only one question: 
*when switch to another handler, why the previous one's componentWillUnmount are not called...*

**Comment by johanneslumpe** [comment]
Please check out this fiddle: http://jsfiddle.net/2mmhuq8o/

Specifically: Click on the links and check the console. You will see that `componentWillUnmount` is called normally for each handler.

**Comment by teamrun** [comment]
Yeah... i add console.log in `componentWillUnmount`, this proves it is called. i just can't catch its execution by adding breakpoint... ok, this maybe webpack's fault, i use `devtool: 'eval'` config and got this. Change to `source-map`, breakpoint in `componentWillUnmount` works... 

OK, thank you for your time~ there is no farther question
