### ISSUE TITLE
feature: replaceWith without router re-run.

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#971]
use case: 

Rendering a view with a param. That param is used to search for a model using regex. I would like to update URI with full model name returned from regex search without causing a re-render. 

Using history location calls notifyChange which intern causes react-router to re-render essentially the same route.

Adding a flag to to replaceWith to prevent this default behavior would be super cool.

my current hac... workaround

```js
  componentDidMount: function() {
    // get history object
    var his = typeof window !== 'undefined' ? window.history : null;
    // spinal-case bonfireName
    var bonfireName = this.state.name.toLowerCase().replace(/\s/g, '-');
    // create proper URI from react-router
    var path = this.context.makePath('bonfires', { bonfireName: bonfireName });

    // if html5 push state exists, update URI
    // else we are using hash location
    if (his) {
      his.replaceState({ path: path }, '', path);
    } else {
      this.context.replaceWith('bonfires', { bonfireName: bonfireName});
    }
  },
```

**Comment by gaearon** [comment]
What is the issue with re-rendering? React won't blow away existing components.

**Comment by BerkeleyTrue** [comment]
The issue is not with re-rendering, but with the side effects of react-router run callback being re-run. We are doing data fetching here, but to give another example, lets say I initiate a socket connection in this view. Given this, where all I want is to change the URL, now react-router is forcing my app to re-initiate a socket connection.

**Comment by gaearon** [comment]
Render callback is supposed to be idempotent. Firing it twice shouldn't break the app. You should consider initializing in componentDidMount and handling path change in willTransitionTo or componentWillReceiveProps.

**Comment by BerkeleyTrue** [comment]
App isn't breaking. callback is idempotent. The issue is that I would like to not fire twice needlessly making two data fetch calls. App is built in Flux and isomorphic so initialization for routes needs to happen before React.render is called. I don't want to change the path, just the URL hence using replaceWith.

**Comment by gaearon** [comment]
I don't quite understand. Why not fire actions in methods I mentioned above?

**Comment by BerkeleyTrue** [comment]
CDM only happends client side. At that point app has rendered with data from GIS that is not what the URL dictates. This will cause React to throw away what was rendered on the server, warn me that data id's are not correct, render the app with default data, data fetch, and then rerender app to what it was on initial page request. Not cool. The app is not the view.

**Comment by johanneslumpe** [comment]
@BerkeleyTrue if you don't want to fire actions twice, why not make sure whether the required data is already available, prior to firing the action?

**Comment by BerkeleyTrue** [comment]
@johanneslumpe I am not firing the action twice. Data availability is not the issue. 

I think there is a lot of confusion as to what my app is doing.

*server*

* Camper (our users are called campers) visits `/bonfires/spinal`
* express server hits react endpoint.
* React Router matches `/bonfires/:bonfireName'
* Run callback is hit on the server
* Run callback first fetches data for { bonfireName: 'spinal' }
* It finds the closes equivalent using regex { bonfireName: 'spinal-tap-case' }
* data is used to initiate stores, React render is called, pulling initial state from store.

*client*

* loads html
* loads app
* React Router matches `/bonfires/:bonfireName`
* Run callback is hit on the client
* Run callback first fetches data for { bonfireName: 'spinal' } (yes I know I should be rehydrating/dehydrating )
* It finds the closes equivalent using regex { bonfireName: 'spinal-tap-case' }
* data is used to initiate stores, React render is called, pulling initial state from store.
* CDM uses bonfire full name to update url so param matches full path.
* React-Router detects this as a page change and reruns run callback
* Run callback fetches data for { bonfireName: 'spinal' } a third time now (yes I know, I know... hydrating shmydrate... cache smash...)
* It finds the closest equivalent using regex { bonfireName: 'spinal-tap-case' }
* data is used to initiate stores, React render ...

Got it? 

Now, how bout them cowboys?

**Comment by cesarandreu** [comment]
The fluxible guys just have a conditional in the run callback, see [here](https://github.com/yahoo/flux-examples/blob/6af0a3293115c94e658a80eb6523266f41ec1a03/react-router/client.js#L38). Why not do the same?

**Comment by johanneslumpe** [comment]
I still don't see the issue. It just sounds like you don't want to fetch data twice.

This can be mitigated by hydration as you already pointed out. The callback might call the method which is actually fetching the data twice but it won't fetch twice if a condition checks for data availability.

And if you're concerned about multiple re-renders, I think that's a non issue there.

Or did I still not understand your issue?

**Comment by johanneslumpe** [comment]
Another solution could be to actually do a redirect to the closed matching url - on the server. So a 302 redirect to the new url.

Your flow would then be:

### server

#### 1st run
* Camper (our users are called campers) visits /bonfires/spinal
* express server hits react endpoint.
* React Router matches `/bonfires/:bonfireName'
* Run callback is hit on the server
* Run callback first checks whether 'spinal' is the canonical name.
* It redirects using 302 to '/bonfires/spinal-tap-case'

#### 2nd run
* express server hits react endpoint.
* React Router matches `/bonfires/:bonfireName'
* Run callback is hit on the server
* Run callback first checks whether 'spinal-tap-case' is the canonical name.
* Run callback fetches data for { bonfireName: 'spinal-tap-case' }
* data is used to initiate stores, React render is called, pulling initial state from store.

### client

* loads html
* loads app
* React Router matches /bonfires/:bonfireName
* Run callback is hit on the client
* Run callback does not need to fetch data because you are using hydration/dehydration now ;)
* React render is called, pulling initial state from store.

This does put a little bit more load on your server, but simplifies the whole flow from my point of view.

**Comment by BerkeleyTrue** [comment]
I appreciate all the critiques, but this isn't me asking for help. This is me saying "wouldn't it be cool if we added a feature to give the user choice in this matter".

What I expected: "That's not really the way replaceWith was meant to be used." And I would totally understand that response.

As the general response was "you are doing it wrong, let me show you the right way" I am going to take it that replaceWith was not meant to used this way and there is no interest in extending it, so I am going to close this issue.

**Comment by johanneslumpe** [comment]
I'm sorry that you're upset. I on my part wasn't telling you that you're doing it wrong. I just wanted to offer you a different view point, to help you maybe find a different solution. Anyway, no hard feelings.
