### ISSUE TITLE
inject `router` into `props` of route handlers

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#978]
context is an undocumented feature and I was happy to use it because it was hidden from Router users.

Since `0.13` and the death of mixins, everybody has to deal with it. I think we should just inject `router` into `this.props` of route handlers so folks don't have to deal with it, (and maybe one day we don't rely on it at all?)

I'll work up a PR tonight.

**Comment by johanneslumpe** [comment]
That means we'd have to manually pass down the router again to child components. So a component cannot just declare that it needs the router, but has to make sure that every single component up the tree passes down the router prop. Does not sound preferable to me. Or were you thinking of just adding the prop injection and still keep the router on context and if somebody wants to use the context they're free to use it?

**Comment by ryanflorence** [comment]
keep it in context so `Link` and friends work. Injecting as a prop will allow people to not have to think about context (until they start testing, and for that I want to provide a helper function).

**Comment by johanneslumpe** [comment]
Ah ok cool. I read your idea about `stubRouterContext` or what it was called. Seems like a good idea.

So this is in addition to using context. If we want to use context, we are free to do so, but we also additionally get the router passed through props, which we could pass down explicitly if we wanted to do so. :+1:

**Comment by emmenko** [comment]
@ryanflorence what if a component is not in a `RouteHandler` context and you need e.g. `transitionTo`?
You can't access it via `this.context.router.transitionTo` since `router` is `undefined`. I understand we can pass it down the component via `props`, but is there a better way to do it? With the `Navigation` mixin you didn't have this problem.

Thanks

PS: see here for practical example https://github.com/emmenko/flux-react-router-example/commit/7ab6327eabacba3216990e56af5145fe1808f918

**Comment by ryanflorence** [comment]
@emmenko yeah, that's why context is useful but people tend to freak out about it because its not documented, so for them, they can pass through props.

I suppose they can just do this already in `Router.run` ...

**Comment by emmenko** [comment]
@ryanflorence I'm sorry but I don't think I understand your answer...how should I use `transitionTo` if router is not in `context`?

**Comment by eek** [comment]
I also think it would have more sense to have access to transitionTo even if the router is not in `context`, this was how things were a version ago, I use it from a Reflux Store and router context is undefined :(

I currently fixed it in a way that @emmenko also did, on Store Initialisation sent the transitionTo function from context. But that's a very dirty fix :( 

@mjackson any ideas about it? :(
