### ISSUE TITLE
PathUtils.withQuery bug, calls Path.withoutQuery instead of PathUtils.withoutQuery, examples fail

### ISSUE THREAD

**Issue by joekrill** [rackt/react-router#979]
When I tried to run the examples I noticed I was getting a "Path is undefined". Looks like a minor typo on line 154 of modules/PathUtils.js introduced in commit 4a8b7563a2f64be2f056ffe7503faa69d683a21d:

    return Path.withoutQuery(path);

should be

    return PathUtils.withoutQuery(path);

**Comment by gaearon** [comment]
Fixed, thanks.
