### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by vinnymac** [rackt/react-router#984]
It is nice to have a place to discuss things. I have found myself using [gitter](http://gitter.im) frequently. Seeing `underscore`, `webpack`, `gulp`, `mocha`, `karma`, and others on it has become increasingly useful to me. I am not proposing `react-router` use gitter specifically, however I am proposing a different medium of discussing this tool outside of github issues. I.e. irc, hipchat, gitter, etc. Thoughts?

**Comment by cesarandreu** [comment]
I've seen lots of people going on IRC to #reactjs to ask react-router questions.

I dunno if gitter is better, but I've noticed that when smaller libraries/frameworks/tools make their own channels they tend to be pretty dead. For example, #webpack in IRC is absolutely dead.

**Comment by gaearon** [comment]
I use Gitter all the time. I think it's a great place for a chat so I'd love it react-router had one.

**Comment by tmbtech** [comment]
http://reactiflux.slack.com has a react-router channel, it's semi-active and there are a lot of people hanging out there.

**Comment by johanneslumpe** [comment]
There is also the #rackt irc channel on freenode.

**Comment by vinnymac** [comment]
@tmbtech [slack](http://slack.com) requires a new account, no? [Gitter](http://gitter.im) would be taking advantage of your existing github account.

@johanneslumpe IRC is a good option.

Whatever is decided, it should be mentioned and linked to in the [ReadMe](https://github.com/rackt/react-router/blob/master/README.md) so others can join in on the discussion easily.

**Comment by tmbtech** [comment]
@vinnymac, It does, but there are also other channels in that slack group that pertains to react. ie reflux, fluxxor, need-help, react-native, flummox etc

**Comment by ryanflorence** [comment]
so many chats ... I wish gitter had a desktop client.

**Comment by vinnymac** [comment]
@ryanflorence https://gitter.im/apps

**Comment by gaearon** [comment]
They do, but it's a wrapper over HTML5 app. Also more lagging than Chrome web version.

**Comment by ryanflorence** [comment]
alright, I added a gitter room for the repo https://gitter.im/rackt/react-router

I'll try to be available in all three places, may the best room win!

**Comment by ryanflorence** [comment]
953319bc39778b8464b2be8365014f22fab631da

**Comment by aniketnandan** [comment]
I am new to react-router. I am using babelify for making es6 to es5. but whenever I am trying "gulp babel" it throws an error of "unexpected token" at <Router> in public/js/components/init.jsx. I am sending my repo link. please help in this issue. 
```
https://github.com/aniketnandan/learnRedux
```
thank you very much
