### ISSUE TITLE
Dynamic Segments behavior needs work

### ISSUE THREAD

**Issue by nickretallack** [rackt/react-router#986]
I've read this:

https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments

Why is this work-around not built in?  It would be really nice if this could be turned on and off or otherwise configured with a property on ```<RouteHandler/>```.

Second, if you are going to try and work with the optimization by implementing `componentWillReceiveProps`, how can you tell if one of your dynamic segments actually changed?  `componentWillReceiveProps` might have just been called because some other property changed.  There's no indication of what the old value of a dynamic url segment was in case you want to compare.  Do you have to track this yourself?

My specific problem is, if I have a route that renders a form for a particular record, if I switch between editing one record and another, any stateful inputs in that form carry their values over into the other record and get mixed in with that record's data.

**Comment by ryanflorence** [comment]
Its not really a workaround, we're just doing normal React. When a url changes from `/foo/123` to `/foo/344` the component doesn't unmount, its still around, just some data changed.

My preference is to pass props down the route tree and use the hooks React provides.

```js
Router.run(routes, (Handler, state) => {
  // pass the router's state down as props, you'll get `this.props.params`
  React.render(<Handler {...state}/>, document.body);
})

// And then for all RouteHandlers, pass the parent route handlers props
// down as well
<RouteHandler {...this.props}/>
```

Now you can use `componentWillReceiveProps(nextProps)` to do whatever work you need to do.

Let me know if that works out for you.

**Comment by nickretallack** [comment]
Oh, I guess that is one way to do it.

I find it kind of weird that react even calls componentWillReceiveProps when a url changes, since your component won't actually receive any new props at this time.
