### ISSUE TITLE
Is it possible in Router.run callback determine name of the route which was resolved?

### ISSUE THREAD

**Issue by wheercool** [rackt/react-router#988]
My approach is based on http://jaketrent.com/post/react-router-with-flux/
I want to use one action per router in my Application, so it would be very handy do something like:

Router.run(routes, Router.HistoryLocation, function (Handler, state) {
  React.render(<Handler/>, document.body);
     AppActions\[**state.routeName**\](state.params);
});

**Comment by wheercool** [comment]
Router.run(routes, Router.HistoryLocation, function (Handler, state) {
React.render(, document.body);
AppActions\[state.routeName\](state.params);
});

**Comment by taurose** [comment]
There is no *single* active route; URLs/paths are always matched to a list of routes.

```js
Router.run(routes, function(Handler, state){
  var deepestRouteName = state.routes[state.routes.length - 1].name;
  var topLevelRouteName = state.routes[0].name;
  var allRouteNamesArray = state.routes.map(route => route.name);
});
```

**Comment by wheercool** [comment]
DeepestRouteName is what I need. Thanks a lot!!
