### ISSUE TITLE
willTransitionTo not called on first page load?

### ISSUE THREAD

**Issue by vespakoen** [rackt/react-router#989]
Hi there,

I am using react-router (^0.12.4) and when adding the willTransitionTo static, it does not get called on first page load.
When I click around, and go back to the view that contains the static willTransitionTo property, it get's called correctly.

Shouln't it also get called when I refresh the page?

**Comment by johanneslumpe** [comment]
I'm using `0.13.1` where it works as you'd expect it. If you visit a route, `willTransitionTo` gets called on the appropriate elements. First load, refresh, etc. all working fine. I also do not remember having any issues with `0.12.*`. But just to make sure, here is a dummy fiddle for you, using `0.12.4`: http://jsfiddle.net/cftpLhg0/ If you check the console, you will see that the hook is called normally.

**Comment by vespakoen** [comment]
Thanks! especially for putting together the fiddle!

I figured out that my code was not working due to react being initialized after I was connected to a websocket (hence no data =))

Closing now.. thanks again

**Comment by johanneslumpe** [comment]
Ha sure, no problem :)
