### ISSUE TITLE
Migration guide for 0.13

### ISSUE THREAD

**Issue by aaronshaf** [rackt/react-router#992]

**Comment by thecaddy** [comment]
+1

**Comment by gaearon** [comment]
There is no migration guide for 0.13.1, it is only a bugfix.
However it is missing from changelog so leaving this open.

**Comment by aaronshaf** [comment]
I meant 0.13

**Comment by gaearon** [comment]
It's there now: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#012x---013x
