### ISSUE TITLE
passing props not clear

### ISSUE THREAD

**Issue by juancabrera** [rackt/react-router#993]
I've seen lots of issues/comments related to this, but none of them gives a clear explanation.

The issue #314 after a lot of conversation says its not longer an issue, that we should check the upgrade guide, but none of those options to pass props to Handlers works (I'm using version 0.13.1).

Did this change for version 0.13.x ? [Upgrade Guide](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md) and [changelog](https://github.com/rackt/react-router/blob/master/CHANGELOG.md) are out to date.

**Comment by gaearon** [comment]
Since 0.10, we no longer render your route handlers. You do that, in `Router.run` callback and down the chain wherever you use `<RouteHandler />`. Therefore it's up to you to put anything in its props.

**Comment by juancabrera** [comment]
@gaearon thank you for the info.
will try to get this working!
if you have any example you can share will be much appreciated.

**Comment by ryanflorence** [comment]
```
Router.run(routes, (Handler) => {
  React.render(<Handler any="prop" you={want}/>, document.body);
});

// and then in render methods of your components
<RouteHandler any="other" props="you want"/>
```

They are just plain ol' components like anything else. Several of the examples in this repo pass props (like data-flow).
