### ISSUE TITLE
React 13.1 dynamically created routes won't show up

### ISSUE THREAD

**Issue by joernroeder** [rackt/react-router#994]
Hey,
I've used the following pattern with success to create routes dynamically from a json data-store: After upgrading to 13.1 i've got the [`Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.`](https://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#problem-cant-be-differentiated-from-arbitrary-objects) and changed my `pageRoutes` object to `pageRoutes = []` accordingly to fix the warning. After my changes the dynamically created routes didn't show up in the router and in the root-routes childroute-array anymore.

Is this a react-router bug or should i just use an array and create a new fragment for the `pageRoutes` variable? What do you think?

```jsx
var pageRoutes = {}; // this could be an array now!

// setting up routes
for (var i = 0, l = pages.length; i < l; i++) {
	…
	var slug = page.slug;

	pageRoutes[slug] = (
			<Route 
				name={pageName}
				path={permalink}
				handler={page.handler} />
		)
}

// adding routes to the router
return (
	<Route name="index" path="/" handler={layoutHandler}>
		{pageRoutes} {/* could be replaced with React.addons.createFragment(pageRoutes) */}

		<NotFoundRoute name="notfound" handler={notFoundHandler)} />
	</Route>
);
```

**Comment by joernroeder** [comment]
I've also logged the `children` variable at https://github.com/rackt/react-router/blob/master/modules/createRoutesFromReactChildren.js#L78 to the console and got the following results when using the `pageRoutes` as an array:

`[Array[0], ReactElement]` the first item is the above mentioned `pageRoutes` array and the `ReactElement` represents the manually created `notfound` route…

**Comment by WRidder** [comment]
Might be similar, I've created something like this as well using json as route definition:
https://github.com/WRidder/react-spa/blob/9af1da2bd43eb9409b394d37b416d93cb7b16e82/client/src/routes/routes.jsx

I'm using an array there as well.

**Comment by ryanflorence** [comment]
This is just JSX, not the router. But yes, just use an array.

**Comment by joernroeder** [comment]
all right! thanks for looking into this issue :)
